### ISSUE TITLE
Menu "click" sound breaking down

### ISSUE THREAD

**Issue by dogukangulyasar** [xbmc/xbmc#23292] opened 2023-05-16 21:32 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

The menu "click" sound is breaking down when the up/down keys are held on.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The sound should be stable.

## Actual Behavior

The sound speeds up and the menu hover does not move.

### To Reproduce

1. Open Kodi
2. Put the cursor on the first menu item in the list
3. Hold up or down key

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [X] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: MACOS Ventura 13.0.1
 - Kodi version: latest

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by sarbes** [comment] 2023-06-16 12:33
No log, no video, and almost no description of what is actually wrong.

Please provide at least some rudimentary information, or we will close the issue.

**Comment by thexai** [comment] 2023-06-20 14:20
Probably duplicate of https://github.com/xbmc/xbmc/issues/23376

**Closed by thexai** 2023-06-20 14:20 UTC
Labels: Ignored rules, Triage: Needed
