### ISSUE TITLE
Video calibration settings changes are lost after Kodi restart

### ISSUE THREAD

**Issue by CvH** [xbmc/xbmc#15165] opened 2018-12-30 17:09 UTC
### Describe the bug
Video calibration settings are lost after restart of Kodi.

Update: bug started with that change https://github.com/xbmc/xbmc/compare/abaf617...36c6db1

## Expected Behavior
Video calibration settings are saved after restart of Kodi.

## Actual Behavior
Video calibration settings are **not** saved after restart of Kodi.

## Possible Fix
workaround
close Kodi, change calibration settings at the guisettings.xml, start kodi

### To Reproduce
1. calibrate the screen to some value
2. exit Kodi
3. start Kodi

### Debuglog
[set-calibration.log](https://github.com/xbmc/xbmc/files/2717330/set-calibration.log)
[restart-of-kodi.log](https://github.com/xbmc/xbmc/files/2717331/restart-of-kodi.log)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ x ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ x ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LE9 / Windows
 - Kodi version: 18.0-RC4 Git:20181228

https://github.com/xbmc/xbmc/issues/14700 might be the same problem or similar but is marked as solved

**Comment by MediaBrasil** [comment] 2019-01-09 22:49
Yes, happen the same here using windows 10 64 bits, don´t save in guisettings.xml, changes maked via gui in kodi settings, video calibrations.

**Comment by neeto33** [comment] 2019-01-20 08:33
Same problem with "Tone mapping" - forgets the settings across restarts

**Comment by DaVukovic** [comment] 2019-01-20 16:40
Added some labels as I'm able to reproduce this issue on both platforms.

**Comment by SupahNoob** [comment] 2019-01-27 02:56
+1 for me; Kodi 18.0-RC5 on Ubuntu 18.04 @ 1920x1080 59.88Hz

I go to System > DIsplay > Video Calibration, set my bottom right overscan to 24,0 to fit and upon Kodi restart, all is lost. I have tried a clean shutdown. I have tried setting the value while playback is happening (vs through the System settings). When Kodi is restarted, these values are set to default.

**Comment by stevehoek** [comment] 2019-02-01 17:48
Same issue for me... Denon X5200 AVR and Samsung PN60F8500 TV, 
LibreElec 8.95.3 on Intel NUC8i5

**Comment by janos-szenfner** [comment] 2019-02-04 20:32
Same issue Libreelec 9.0
Philips television.

**Comment by DaVukovic** [comment] 2019-02-05 08:14
@stevehoek

Your TV has the option to adjust that. The problem your facing is called "Overscan". A little Google search for this TV model and "Overscan" gives multiple results how to solve that. It's also mentioned at the e-manual (page 75-76). Look at the zoom options. 

Not saying that this issue should not be fixed as it also affects the subtitle position, but if it's only about the overscan-problem (Kodi GUI bigger than the visible screen) it can be fixed for 95% at the TV settings. Using Kodis calibration should only be the very last resort with very very old HD-ready TVs (and older ones). Newer full hd TV should all! be able to display the native resolution. The manufactory simply hide those options at the zoom-options or they call it something like "PC-mode". In rare cases it's also only available at a specific HDMI input. Using Kodis calibration is nly a lost of native resolution. 

For all who are reading, please check your TV settings first. It's mostly (for 95%) fixed if you setup your TV correctly.

**Comment by Xgox** [comment] 2019-02-06 10:53
@DaVukovic  Thank you for the tip but even if I adjust the screen size in my TV settings I would still like to set the subtitles where I want them - at the bottom of the screen and that only works with the setting in Video Calibration and not with the "at the bottom" button under subtitles. 
Don't you think that bug is fixable?
Greetings!

**Comment by DaVukovic** [comment] 2019-02-06 17:12
Generally it's not "adjusting the screen size", it's more "displaying the screen correctly" ;)

As said, configuring your TV will ofc not fix the problem and I can for sure understand that users want different/individual positions for their subtiltes. I guess this issue is fixable. It's simply that I can't do it ;).

The only benefit (if one could say so) this issue currently has, is that users care to configure their TV in the correct way to show the native resolution the device they hook up on their TV presents. By using the screen calibration without looking at the manual of TV, you will never get the native resolution you set up at Kodi on your TV. It's always a loss. 

This issue is still open (and will be). So I guess if someone finds the time to look at it, it will be fixed sooner or later.

**Comment by DaVukovic** [comment] 2019-02-06 18:18
Not much progress, but probably important for someone who wants to look at it. I compliled Kodi 18-RC1 and the issue already existed there

**Comment by ericzolf** [comment] 2019-02-10 08:18
I can confirm the issue under Fedora 29 with kodi-18.0-0.24.rc5.fc29.x86_64 and with a TV set which doesn't allow to compensate the overscan (at least the menu doesn't show anything like this and the [usage guide](http://downloadcenter.samsung.com/content/UM/200505/20050503170104265_BN68-00883J-00Ger.pdf) doesn't use the word overscan) making the use of Kodi quite painful. Removing alltogether `~kodi/.kodi` didn't help. A fix or at least a workaround would be very much appreciated.

**Comment by hitn** [comment] 2019-02-10 08:37
@ericzolf:

Workaround can be found here:
https://forum.libreelec.tv/thread/14028-8-95-1-on-wetek-play-video-calibration-not-persistent/

**Comment by CvH** [comment] 2019-02-10 10:59
tracked it down with help of @MilhouseVH builds
https://github.com/xbmc/xbmc/compare/abaf617...36c6db1
```
#1030-gaf991c8.tar ok
#1031-g76ed873.tar not ok
```

So @peak3d broke it likely with https://github.com/xbmc/xbmc/commit/e8c158606000f19fef478184e20898f8ff8bd5c4 (I did not confirmed that)

**Comment by yuri-sevatz** [comment] 2019-02-13 02:11
^^ I think I found it.  Seems to work on my system when applied.  I don't fully understand everything that's going on here but that off-by-1 struck me as an oddity in the above diff.

**Comment by Xgox** [comment] 2019-02-14 10:18
Nice @yuri-sevatz  ....so do you think it will be fixed in the next release? (18.1 RC1) :)

**Comment by yuri-sevatz** [comment] 2019-02-15 00:18
@peak3d Your fix seems to work!  Ignore my PR, I think mine was creating clones of the desktop resolution like your fix from a few months back had originally tried to fix.

Looks like you stumbled on something a lot more nuanced :+1:

**Comment by ericzolf** [comment] 2019-02-17 12:12
@hitn workaround didn't work for me. Are description and xrandrid somewhat relevant? Perhaps we should have the discussion in a forum rather in this ticket?

**Comment by peak3d** [comment] 2019-02-17 12:44
@ericzolf the ticket is fine for this discussion, pls. provide a debug log and explain what is not working.

**Comment by hitn** [comment] 2019-02-17 15:34
@ericzolf: Yes. Correct content of the "description" element is crucial! In fact this is the ID to match against. To not scatter the bug report, maybe you want to join the discussion in the LibreELEC forum, since there is already the matching thread for this.

**Comment by iGamerHD** [comment] 2019-02-17 23:56
So i tried to fix this overscan problem tonight, because it's also really annoying for me having to apply the settings every time i restart kodi again.
The workaround with the guisettings.xml file didn't work for me, the settings were also lost.
What I discovered, if i switch the frequency to 50hz my overscan settings, applied in the gui, are saved.
I don't know why, but when i try to do this with 60hz they are lost again.
It's more a workaround than a fix for me, because the image quality suffers quite a bit from that, but maybe it helps someone, who also has this problem with old TVs.

**Comment by Essam315** [comment] 2019-02-19 10:37
You could try to use this nightly, I think it should have "peak3d" PR by now.

https://mirrors.kodi.tv/nightlies/windows/win64/master/KodiSetup-20190218-5e82ff95-master-x64.exe

**Comment by Essam315** [comment] 2019-02-20 08:16
The problem of losing the video calibration settings after a restart is fixed for me with this nightly, Kodi 18.2 Leia, many thanks for "peak3d" for fixing it.

https://mirror.de.leaseweb.net/xbmc/nightlies/windows/win32/master/KodiSetup-20190219-d21fed4a-master-x86.exe

https://mirror.de.leaseweb.net/xbmc/nightlies/windows/win64/master/KodiSetup-20190219-d21fed4a-master-x64.exe

https://mirrors.kodi.tv/nightlies/

**Comment by Xgox** [comment] 2019-02-21 11:13
@Essam315  Nice! Does that mean it will be fixed for sure in the upcoming official 18.2 RC2 version? Greetings!

**Comment by MartijnKaijser** [comment] 2019-02-21 16:22
Yes

**Closed by MartijnKaijser** 2019-02-21 16:22 UTC
Labels: Linux, Settings, Windows

**Comment by kdre** [comment] 2019-03-10 18:20
I tried today the latest milhouse libreelec #309 for my raspberry pi 3b+ (first installed the latest official libreelec and the the update). Unfortunately, the bug is still present. Each time I change the video calibration settings, they are lost after a reboot.

Milhouse confirmed that PR #15516 is included in the build. Seems like it didn't fix the problem.

Any suggestions?

**Comment by fritsch** [comment] 2019-03-10 18:30
Do you reboot by pulling the powerplug? If yes -> it can't work.

**Comment by DaVukovic** [comment] 2019-03-10 19:25
I can't even reproduce the problem with 9.0.1 and HDMI out on my TV. All screen calibrations are being saved and 9.0.1 doesn't even include #15516 

But I also installed current MH build #309 and I'm also not able to reproduce that problem. All settings I've done are being saved if I power down my RPi correctly. Talked to Milhouse and he said that some ppl are affected and some not. So please, @kdre , please ensure you power down your RPi correctly. 

As you told in your thread you are using composite out, it would also be nice to know if you facing the same problem while using HDMI if you have the option to test that.

**Comment by peak3d** [comment] 2019-03-10 19:49
@kdre pls: start kodi, change a setting, power off / power on and then provide guisettings.xml and kodi_old.log (or similiar). Let us know which resolution / refresh rate you had active whilechanging in calibrations, and tell us what setting you have changed (from value -> to value.

**Comment by kdre** [comment] 2019-03-10 23:30
> Do you reboot by pulling the powerplug? If yes -> it can't work.

No, of course not. I rebooted via the kodi menu. The powerplug was never pulled.

@peak3d
Will do it tomorrow and report back.
I changed the UI resolution to 540, but where can I see/set the refresh rate?

**Comment by peak3d** [comment] 2019-03-10 23:32
If you open calibration settings, the current resolution + refresh rate is displayed on top of the screen (or on bottom, I forgot, but you'll find)

**Comment by kdre** [comment] 2019-03-11 01:08
OK, I did it. Here is a zip file with all the stuff:
https://drive.google.com/open?id=1ynwz4a5rbGwfAR6mVwuM7JnhvnUfuzVS

1. This is just a "side note", but maybe it helps to track down the bug. 

* official libreelec 9.0.1 -> update mh 9.1 build 309
Result: Video calibration settings are lost after a reboot

* Downgrade to the last known working version (9.0 build 1030)
Result: Video calibration settings are _not_ lost after a reboot

* Again upgrade to mh 9.1 build 309
Result: Video calibration settings are still there after a reboot!
(Folder with log + guisettings.xml: 9.0-1030_9.1-309)

So, mh 9.0 build 1030 helped to make the settings persistent, even after a reboot and even after an upgrade to the latest version.
However, when I manually add the resolution stuff to guisettings.xml of a buggy installation, it is automatically erased from the file (=settings are lost).

2. Here is the real test now.

* Fresh install of LE 9.0.1 without changing any settings.
Result: Video calibration settings are lost after a reboot

* Upgrade to mh 9.1 build 309
Result: Video calibration settings are lost after a reboot.

Log and guisettings.xml before I changed the settings are in folder "before".
Log and guisettings.xml after I changed the settings are in folder "after".
After some time I tried again. Log + guisettings.xml are in folder "after_2".
Pictures of the calibration process are 1_.jpg, 2_.jpg, 3_.jpg, 4_.jpg, 5_.jpg (they show what I changed and and that video calibration settings after reboot looked like how it was before reboot).

Please note that in (1) the rpi was configured with sdtv=2 in /boot/config.txt, because I am in europe with PAL and 50HZ.
For the test in (2) I used a fresh install without changing anything. It is per default set to NTSC with 60HZ.
Anyway, it does not matter for the bug to appear. Settings are not saved no matter if I add "sdtv=2" or not.

I think that justifies to change this issue from closed to open.

**Comment by peak3d** [comment] 2019-03-11 07:27
@kdre thx. for spending so much time providing a lifecycle of 2 LE versions and 2 different TV's.
Beside the fact that the kodi logs are not with debug enabled, it is too much for me to analyze.

Lets start again:

- Install LE (the "broken" version)
- Add this line to your advancedsettings.xml: <loglevel hide="false">1</loglevel>
- restart kodi
- open calibration, make a photo of the screen
- change a setting, and let me know which setting you have changed
- leave calibration settings
- terminate kodi
- start kodi
- provide guisettings.xml / kodi.log / kodi old log

Thx.

**Comment by kdre** [comment] 2019-03-11 13:20
@peak3d 

> Lets start again:
> 
>     * Install LE (the "broken" version)

Installed LE 9.0.1 and then updated to mh 9.1 build 309.

>     * Add this line to your advancedsettings.xml: `<loglevel hide="false">1</loglevel>`

File did not exist. I created it in .kodi/userdate and added the following:

```
<advancedsettings>
    <loglevel hide="false">1</loglevel>
</advancedsettings>
```

>     * restart kodi
Done.

>     * open calibration, make a photo of the screen

-> see 1.jpg

>     * change a setting, and let me know which setting you have changed

-> see 2.jpg
(changed top left corner from (0,0) to (40,30))

>     * leave calibration settings
>     * terminate kodi
>     * start kodi
Done.

>     * provide guisettings.xml / kodi.log / kodi old log

Requested files:
https://drive.google.com/file/d/1NZg7WWwXSatVtyt1KLG2t2i8LAhFTuB6

Hope this helps.

**Comment by peak3d** [comment] 2019-03-11 16:53
@kdre The one and only supported resolution is only inserted as RES_DESKTOP but has to be also inserted in RES_CUSTOM to get it work. We need some rbpi developer here, not sure if @popcornmix reads already here.

**Comment by kdre** [comment] 2019-03-11 18:39
> @kdre The one and only supported resolution is only inserted as RES_DESKTOP but has to be also inserted in RES_CUSTOM to get it work. 

Dont know what this actually means, but I have a question:
The broken build (MH9.1 b309) works if I downgrade it to MH9.0 b1030 (the last known working build) and then upgrade back to MH9.1 b309. After that nothing is lost anymore. Why?
This seems to imply  that I should be able to manually edit something to get it working without down- and upgrading.
The log file doesn't mention RES_CUSTOM either after down- and upgrading, only this (PAL TV!):

```
2019-03-10 23:53:49.258 T:1937213280  NOTICE: Found resolution 675 x 540 with 720 x 576i @ 50.000000 Hz
2019-03-10 23:53:49.258 T:1937213280  NOTICE: Found (675x540i@50.000000) at 16, setting to RES_DESKTOP at 16
```

Do you have an idea what a down- and upgrade does to the system so that video calibration works without losing the settings, even after modifications?

**Comment by peak3d** [comment] 2019-03-11 19:18
@kdre this is nothing you can solve by yourself

**Comment by kdre** [comment] 2019-03-11 19:37
> @kdre this is nothing you can solve by yourself

I experimented a littlein the last hour and I got it to work. 

Here is what I tried:
1. I copied the complete <resolutions>...</resolutions> tag guisettings.xml of the working version to guisettings.xml of the broken version.
Result: After a reboot the settings were gone.

2. I copied the complete guisettings.xml file from the working version and replaced the one from the broken version.
Result: It works. I can change settings and it persists after a reboot.

So, I dont know what exactly is in guisettings.xml that has to be copied, but I solved it temporarily by myself :-)

**Comment by spokemon** [comment] 2019-03-19 10:24
@kdre thanks for the workaround, I too have this problem and have been struggling for months.
Recalibrating the screen after each reboot was getting really old.
I followed your steps in your previous post and it worked:

My setup:
NUC DN2820FYKH -> HDMI -> Philips Flat TV 30PF9946D/37 (very old 2004?)
- Format installed Official Libreelec 9.0.1 (calibration settings **lost** after reboot)
- Upgrade to Milhouse 9.1 build 309 (calibration settings **lost** after reboot)
- Downgrade to Milhouse 9.0 build 1030 (calibration settings **remained** after reboot)
- Upgrade to current latest Milhouse 9.1 (calibration settings **remained** after reboot)

The reason for this post is because I may have more helpful info to add.
I did a comparison of the non-working and working guisettings.xml.
Most settings where the same except for an additional **`<resolution>`** section added by the
downgrade to **Milhouse 9.0 build 1030**. The important part is the **`<description>`**, 
as you can see from the 'grep' output below, the first line is in a different format from 
all the others. The new `<resolution>` section was added by Milhouse 9.0 build 1030.

If I delete the new `<resolution>` section, the calibration settings are lost.
If I manually add the new `<resolution>` back in, the settings remain.
However, the `<description>` must be exactly as printed, even down to the spacing,
otherwise the calibration will be lost. 

My conclusion: (I may be totally wrong, it wouldn't be the first time)
- Milhouse 9.0 build 1030 CREATES a new `<resolution>` section if it doesn't find a match.
- Non-working builds will NOT create a new `<resolution>` section, but will UPDATE if it finds a match.

HTH

>grep description guisettings.xml

`<description>`1920x1080@ 30.00`</description>`
`<description>`HDMI1: 1920x1080i @ 30.00Hz`</description>`
`<description>`HDMI1: 1920x1080i @ 29.97Hz`</description>`
`<description>`HDMI1: 1280x1024 @ 75.02Hz`</description>`
`<description>`HDMI1: 1280x768 @ 59.67Hz`</description>`
`<description>`HDMI1: 1280x720 @ 60.00Hz`</description>`
`<description>`HDMI1: 1280x720 @ 59.94Hz`</description>`
`<description>`HDMI1: 1024x768 @ 75.03Hz`</description>`
`<description>`HDMI1: 1024x768 @ 70.07Hz`</description>`
`<description>`HDMI1: 1024x768 @ 60.00Hz`</description>`
`<description>`HDMI1: 1152x648 @ 75.01Hz`</description>`
`<description>`HDMI1: 1024x576 @ 85.06Hz`</description>`
`<description>`HDMI1: 832x624 @ 74.55Hz`</description>`
`<description>`HDMI1: 800x600 @ 72.19Hz`</description>`
`<description>`HDMI1: 800x600 @ 75.00Hz`</description>`
`<description>`HDMI1: 800x600 @ 60.32Hz`</description>`
`<description>`HDMI1: 800x600 @ 56.25Hz`</description>`
`<description>`HDMI1: 800x450 @ 85.04Hz`</description>`
`<description>`HDMI1: 720x480 @ 60.00Hz`</description>`
`<description>`HDMI1: 720x480 @ 59.94Hz`</description>`
`<description>`HDMI1: 720x480i @ 30.00Hz`</description>`
`<description>`HDMI1: 720x480i @ 29.97Hz`</description>`
`<description>`HDMI1: 640x480 @ 75.00Hz`</description>`
`<description>`HDMI1: 640x480 @ 72.81Hz`</description>`
`<description>`HDMI1: 640x480 @ 66.67Hz`</description>`
`<description>`HDMI1: 640x480 @ 60.00Hz`</description>`
`<description>`HDMI1: 640x480 @ 59.95Hz`</description>`
`<description>`HDMI1: 640x480 @ 59.94Hz`</description>`
`<description>`HDMI1: 720x400 @ 70.08Hz`</description>`
`<description>`HDMI1: 640x360 @ 84.95Hz`</description>`

**Comment by peak3d** [comment] 2019-03-19 11:29
@spokemon pls. provide a full kodi debug log

**Comment by kdre** [comment] 2019-03-19 13:13
@spokemon 
Nice that I could help you out.

BTW: Your findings are exactly like mine. However, when I only copied the resolution-section I overlooked that I copied it from a "60 Hz" setup to a "50 Hz" setup, so the description-text was probably wrong. After a reboot, kodi deleted the complete resolution-section.
As described above, when I copied the complete guisettings.xml, it worked. I didn't analyze it further, thou. I am just happy that it works now for me and I can live with this workaround, because I only have to do it once in the lifetime of the installation. However, it should be fixed, because it is frustrating for new users.

BTW: This probably also explains why some ppl report that everything works for them, even with "broken versions". In my opinion it is because they just upgraded from a "good version" (at least at some point along their upgrade path) and did not install a fresh broken version. As a matter of fact they have a good & working guisettings.xml, which a broken version does not delete.

I am just asking myself why this issue is still marked as "closed"? It is obviously not fixed.

**Comment by jghaanstra** [comment] 2019-04-02 18:37
@MartijnKaijser I just upgrade to LibreElec 9.0.1 to find out this issue is bothering me. Obviously it has not been fixed with Kode 18 RC2. Could you re-open this issue?

**Comment by MartijnKaijser** [comment] 2019-04-02 18:41
No.
Libreelec 9.0.1 does not include Kodi 18.2RC

**Comment by jghaanstra** [comment] 2019-04-02 19:58
> No.
> Libreelec 9.0.1 does not include Kodi 18.2RC
Oh right, I figured it was fixed in Kodi 18 RC2 and not in Kodi 18.2 RC ... small but relevant difference ... I'll go bug the LibreElec team.

**Comment by DaVukovic** [comment] 2019-04-02 20:40
Simply install one of the Milhouse nightlies which will include the fix. 

LibreELEC will include the fix in its next release. This will most likely happen when Kodi releases 18.2 as its stable release. 

If this issue bugs you that much, then (as said) install the Milhouse builds.

If overscan is your only problem, then I would recommend to read the manual of your TV. Most overscan need to be solved at the TV itself and not within Kodi. Look for something in the zoom options or if your TV has a "PC mode" or something similar. Every vendor calls it different. So it's sometimes well hidden. In case you can't find it, name the vendor and the exact model of your TV and I'll have a look.

**Comment by jghaanstra** [comment] 2019-04-02 20:45
> In case you can't find it, name the vendor and the exact model of your TV and I'll have a look.

Thank you for taking the time to reply and offering help. I was actually looking into the TV settings at that same time and did got it fixed it by changing the TV screen setting from 16:9 to full screen. That solved it for me.

**Comment by DaVukovic** [comment] 2019-04-02 20:49
Glad to hear that. Now, if you have done that for the first time using LE and always used the screen calibration before, you will now get 100% of the native resolution for the very first time. 

Screen calibration is only the very last resort and for very old TVs only which will still suffer from overscan. Using it on a TV which is capable of disabling it, will only end up in the lost of native resolution. 

Just FYI

**Comment by Dancorp** [comment] 2019-04-23 21:25
Hi everyone.
I use Kodi on a Raspeberry equipped with an RGB-Pi cable. (allows to obtain an RGB video signal www.rgb-pi.com).
So I use a particular resolution, set using HDMI_Timings in config.txt.
For example, it's 1920x288@00.0 Full screen.
In my situation, what is the best way to avoid the problem of losing calibration settings?
Thanks in advance for your help.
Dan

**Comment by arnova** [comment] 2019-04-24 06:11
@Dancorp: Please take this to the forum. Github issues is only for bug discussion.

**Comment by DaVukovic** [comment] 2019-04-24 07:05
@Dancorp 

as said. that issue is fiixed and will be included in the next LibreELEC release. 

To answer: 

>In my situation, what is the best way to avoid the problem of losing calibration settings?

either use the milhouse builds or wait for the next LibreELEC release ;)

**Comment by micobarac** [comment] 2019-12-01 19:15
I am experiencing the same issue with Kodi "Leia" 18.5 on Android 8.0. Calibrating settings are lost after Kodi restart.

**Comment by MauriceW67** [comment] 2019-12-17 22:33
Same here on an Nvidia Shield with Android Pie. Issue started with Kodi 18.4, it worked fine on 18.3 and 18.2 for me. Issue has been reported here:

https://github.com/xbmc/xbmc/issues/16683

And here:

https://forum.kodi.tv/showthread.php?tid=348813

Unfortunately, no developer has looked into it sofar.

Reading the comments above, I'm starting to suspect that it has something to do with the resolution descriptions. On my system they look to have very strange values for the refresh rates such as:

            <description>1920x1080 @ 23.976025 - Full Screen</description>
            <description>1920x1080 @ 59.940060 - Full Screen</description>

Should the refresh rates in the descriptions really have such a lot of decimals after the dot?

**Comment by olivluca** [comment] 2020-03-28 21:32
Every few months I take out from the drawer my raspberry pi zero and install the latest milhouse nightly to see if I can actually use it, but the bug is still there.
It's been fixed for android (bug #16683) but not for the raspberry pi. 
Should I open a new bug or will somebody reopen this one?
@DaVukovic I want to use it with an old tv using analog video and a lot of overscan.

**Comment by ajmcc** [comment] 2020-03-29 08:35
This same bug brought me here.. LibreELEC 9.2.1 on a RPi 2B v1.1.
I needed another running TV so dug out my classic old widescreen Sony Trinitron, spent time and effort building a nice DIY videostreamer with DAC etc. All works great, except for various software issues with Kodi. I'd definitely support reopening this bug, but I'm really not at all confident of how the Kodi/LibreELEC software QC is actually working..

**Comment by ajmcc** [comment] 2020-03-29 09:01
I was able to workaround this fault by replacing my guisettings.xml with the one provided by kdre at:
https://drive.google.com/open?id=1ynwz4a5rbGwfAR6mVwuM7JnhvnUfuzVS
Following this I just changed the various locale settings to suit my needs, tweaked the overscan compenation a bit to suit my old Trinitron. Then, following a reboot, all the settings were retained !!!
Thanks, kdre !

**Comment by olivluca** [comment] 2020-03-29 10:05
Yes! 
Those settings worked. Not only that, but once they were in place I could change the calibration from kodi and they persisted after a reboot.
Maybe it could explain why the bug cannot be reproduced by everybody: if one has already the _correct_ settings in guisettings.xml he would never see the bug, while if one starts from a clean configuration it would never work.

**Comment by olivluca** [comment] 2020-03-29 10:23
FWIW, [this is the diff](https://gist.github.com/olivluca/f21a388bb716004b803acfcf0e31bd46) between my original guisettings.xml (whre I already tried to hand create a resolution section) and the new, working, one.

**Comment by hoorna** [comment] 2020-06-09 20:56
The last two days I have struggled with the non-saving-problem for the calibration settings. With the posts in this thread I found the following results/workarounds. I hope this will help developers to solve this terribly annoying problem if it is impossible to change the calibration on a monitor.

- Resolution data will be for the first time written to guisettings.xml when the calibration is changed. If the calibration is never changed then there are no resolution data in guisettings.xml.

- Resolution data will be for the first time written using a HDMI-monitor. Using a Composite monitor there will be never for the first time resolution data written to guisettings.xml.

- Using a Composite monitor new calibration settings will be written when there are resolution data available in guisettings.xml: with no resolution data in guisettings.xml new calibration settings will not be written.

- New calibration settings will be written at shutting down/rebooting Kodi/Raspberry.

- Calibration changes will only be written when the _exact_ resolution description is available in guisettings.xml. Even with the smallest deviation there will be no calibration changes written. 

- Editing guisettings.xml is possible in Windows 10->Explorer ->Network->LIBREELEC->
Userdata->guisettings.xml. Use the following procedure. 1) Via SSH: "systemctl stop kodi". 2) Edit guisettings.xml. 3) Via SSH: "systemctl start kodi".

- To find the exact resolution description for your monitor create in Windows 10 the file advancedsettings.xml and copy it to ->Network->LIBREELEC->Userdata. Restart Kodi. Look via SSH in .kodi/temp/kodi.log and search the _exact_ description.

- Change in guisettings.xml the description for your monitor to the exact description you found in advancedsettings.xml. Only if this matches fully calibration changes will be written to guisettings.xml.

- In my case I installed LIBREELEC using a HDMI monitor connected to Raspberry Pi. Then I changed the calibration settings (so resolution data will be written to guisettings.xml). Next I created advancedsettings.xml and restarted the Raspberry connected to the Composite monitor. Then I searched in kodi.log for the exact monitor description and compared it with the description in guisettins.xml. In kodi.log I found "<description>720x480 (720x480) @ 60.00i - Full Screen</description>" and in guisettings.xml I found "<description>720x480 (720x480) @ 60.00 - Full Screen</description>". Notice that there is a slight difference of only one character: "i". So I edited the monitor description in guisettings.xml using the procedure I wrote above.
Problem solved: from that moment on the calibration changes are kept by Kodi even after a restart.

**Comment by hoorna** [comment] 2020-06-10 10:00
Finally I conclude that the bug in Kodi has to do with:

- Calibration changes are not written to guisettings.xml when using a Composite monitor.

- If there are calibration data written in guisettings.xml by using an other monitor than a Composite monitor (i.e. a HDMI monitor) there possibly will be written wrong descriptions for Composite monitors. The result is that Kodi cannot write new calibration changes to guisettings.xml if you switch over to a Composite monitor.

**Comment by matijaerceg** [comment] 2020-08-03 15:27
Can confirm that using the correct description for the resolution makes the setting stick for RPi with Composite after restarting Kodi.

In my **guisettings.xml**, I replaced `<resolutions />` with:

```
<resolutions>
    <resolution>
        <description>720x480 (720x480) @ 60.00i - Full Screen</description>
        <subtitles>406</subtitles>
        <pixelratio>0.949895</pixelratio>
        <overscan>
            <left>46</left>
            <top>21</top>
            <right>671</right>
            <bottom>458</bottom>
        </overscan>
    </resolution>
</resolutions>
```

Thanks @hoorna

**Comment by JamieEC** [comment] 2020-08-16 15:23
Still experiencing this issue on latest version using Raspberry Pi.
Why has this been closed?

**Comment by RowanUnderwood** [comment] 2020-08-26 19:01
I also still have this issue, appears to be caused by using a raspberry pi, setting up XBMC on HDMI, then moving over to 480i crt.  Judging by the number of complaints, this appears to be a use case for a lot of folks :)  Plenty of CRTs out there still in use, which do not have overscan settings or even H-size and V-size options.

**Comment by devtibo** [comment] 2020-09-12 08:03
> Can confirm that using the correct description for the resolution makes the setting stick for RPi with Composite after restarting Kodi.
> 
> In my **guisettings.xml**, I replaced `<resolutions />` with:
> 
> ```
> <resolutions>
>     <resolution>
>         <description>720x480 (720x480) @ 60.00i - Full Screen</description>
>         <subtitles>406</subtitles>
>         <pixelratio>0.949895</pixelratio>
>         <overscan>
>             <left>46</left>
>             <top>21</top>
>             <right>671</right>
>             <bottom>458</bottom>
>         </overscan>
>     </resolution>
> </resolutions>
> ```
> 
> Thanks @hoorna

Thanks. This solution work for me. Overscan persist after reboot. So I stopped Kodi and modified guisettings.xml by adding the mentioned code.  

I just remove the "i" next to 60.00 and adjust the resolution description to the one found in kodi.log. Then I restart Kodi and everything is fine. Same after reboot. Thanks a lot!

`<resolutions>
    <resolution>
        <description>800x480 (800x480) @ 60.00 - Full Screen</description>
        <subtitles>406</subtitles>
        <pixelratio>0.949895</pixelratio>
        <overscan>
            <left>46</left>
            <top>21</top>
            <right>671</right>
            <bottom>458</bottom>
        </overscan>
    </resolution>
</resolutions>
`
 [MY CONFIG = RPi3 - LibreElec 9.2.4 - Kodi  18.8.0 - Official Raspberry 7" TouchScreen]

**Comment by ridgekuhn** [comment] 2021-07-11 09:19
Thank you @matijaerceg, that's exactly the solution I needed for composite-out on my Raspberry Pi running OSMC.

**Comment by EddyOlivier** [comment] 2022-10-08 11:51
@hoorna thanks a lot, you saved my day.
Editing my ".kodi/userdata/guisettings.xml" file, to set the exact correct "description" field in <resolution> XML tag did work.

I used your trick by :
- creating an empty ".kodi/userdata/advancedsettings.xml" file 
- calibrating my screen onced in Kodi
- looking at ".kodi/temp/kodi.log", I found exact "description" for my video adapter, which is: "DWE SL-S00T: 1360x768 @ 59.80Hz"
- editing ".kodi/userdata/guisettings.xml", which was having resolution description tag set to: "DWE SL-S00T: 1360x768" to change it for the exact correct one "DWE SL-S00T: 1360x768 @ 59.80Hz"

And now calibration is being saved in Kodi.
I am unsure how you 'guessed' this , but that is brillant, thanks once again.

**Comment by hoorna** [comment] 2022-10-08 19:52
@EddyOlivier, you're welcome. Happy audio/video/photo streaming with Kodi!

**Comment by redia00** [comment] 2022-11-12 17:59
Hello. I'm having the same issue on my android version. I moved my android TV (Xiaomi MiBox) to a different samsung TV and I have now this calibration that I can't save issue.
My Kodi is the last playstore one - (19.3 (19.3.0) Git:20211024-49a04cd6a7). Platform: Android ARM 32-bit

I try to do what @EddyOlivier  did following @hoorna trick

1. creating an empty ".kodi/userdata/advancedsettings.xml" file
2. doing a calibration in kodi system menu
3. then looking in .kodi/temp/kodi.log

But I not able to find the good "description" (I guess)

In the log I found 
ERROR <general>: Error loading special://profile/advancedsettings.xml, Line 0
                                                   Failed to open file

So that's good it mean I did not forget to copy the empty file ;-)
Then I have
`INFO <general>: CAndroidUtils: SetNativeResolution: : 720x480 720x480@0.000000`
and
`INFO <general>: GUI format 720x480, Display Windowed`

Which one is the good one?
I tryed booth, without success of course.

`        <resolution>
            <description>720x480 720x480@0.000000</description>
            <subtitles>406</subtitles>
            <pixelratio>0.949895</pixelratio>
            <overscan>
                <left>46</left>
                <top>21</top>
                <right>671</right>
                <bottom>458</bottom>
            </overscan>
        </resolution>
        <resolution>
            <description>GUI format 720x480, Display Windowed</description>
            <subtitles>406</subtitles>
            <pixelratio>0.949895</pixelratio>
            <overscan>
                <left>46</left>
                <top>21</top>
                <right>671</right>
                <bottom>458</bottom>
            </overscan>
        </resolution>	
`

So what is the good one, and what I'm doing wrong?
Thanks

**Comment by DaVukovic** [comment] 2022-11-12 19:31
Could you please be more specific what this "different Samsung TV" is exactly?

I'm asking because you shouldn't be in need of using the calibration setting at all. If some parts of Kodi are out of screen it's most likely an overscan-issue which needs to be fixed at the TV itself. Most likely it's hidden under the "zoom"-options your TV provides. 

If you tell us the exact model you are using, then we could point you to the correct section at the manual. Or you will have a look at it yourself. 

In any way...if your TV is younger than 10 years, then it's capable of displaying 1080p natively. Overscan is a leftover of very very old TVs.

**Comment by redia00** [comment] 2022-11-13 09:38
Thanks for your reply.
This TV (Samsung UE26EH4000W) is pretty old, but don't launch me on that I just move recently from a old classic  Philips Trinitron (non flat screen) with XBMC on a XBOX first generation to flat. And the XBOX/XBMC was much more easy to use by the kids...
Anyway, I don't think I can change the settings on my TV, and that it won't mess up with other devices.
Thanks

**Comment by hoorna** [comment] 2022-12-06 10:45
Last years I do not use Kodi. I cannot help you. Sorry.

**Comment by redia00** [comment] 2022-12-10 12:23
Ok thanks. It working. Not very convenient as when I plug the Nintendo from the kids, I need to change back the setting but it's fine. Thanks. Sorry that I wrote on the "bug" section but for me it's a bug. Changing the video calibration, as it's possible is easier. Not being able to save is a bug...
Anyway, thanks a lot for the time you took to help me. I appreciate. And even if it does not solve my issue it's a good workaround...

**Comment by almodovaris** [comment] 2023-02-02 20:48
Well, for Linux users I have this tip: disable Wayland and Kodi will remember its pixel ratio calibration.

**Comment by jlindgren90** [comment] 2025-03-08 19:09
This issue still exists (on Wayland) in Kodi 21.2.
As a workaround, the following patch forces the default pixel ratio to 1.0:

```
diff --git a/xbmc/windowing/wayland/WinSystemWayland.cpp b/xbmc/windowing/wayland/WinSystemWayland.cpp
index ce0d4d4..afd3d15 100644
--- a/xbmc/windowing/wayland/WinSystemWayland.cpp
+++ b/xbmc/windowing/wayland/WinSystemWayland.cpp
@@ -466,7 +466,7 @@ void CWinSystemWayland::UpdateResolutions()
   for (auto const& mode : modes)
   {
     bool isCurrent = (mode == currentMode);
-    float pixelRatio = output->GetPixelRatioForMode(mode);
+    float pixelRatio = 1.0f; // output->GetPixelRatioForMode(mode);
     CLog::LogF(LOGINFO, "- {}x{} @{:.3f} Hz pixel ratio {:.3f}{}", mode.size.Width(),
                mode.size.Height(), mode.refreshMilliHz / 1000.0f, pixelRatio,
                isCurrent ? " current" : "");
```
