### ISSUE TITLE
Proper Anime support

### ISSUE THREAD

**Issue by scythe000** [xbmc/xbmc#24658] opened 2024-02-06 18:50 UTC
name: No Anime Support
about: Create an extensive report to help us document a problem

---

### Describe the bug
Here is a clear and concise description of what the problem is:

The only thing that's really keeping Kodi from being perfect for me is the total lack of proper Anime handling. 
Almost none of it scans into the DB, and it mixes Anime with TV Shows.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

1. Scan Anime
2. It matches show
3. It goes into its own menu item

## Actual Behavior

Nothing is detected

## Possible Fix

There's an advanced regex file parser in the wiki, why isn't it included by default? 
(https://kodi.wiki/view/Anime#Scanning_files_without_renaming_them)

Here's my thought:

1. Make the advanced parser included by default
2. Give us a default menu option called Anime
3. Make a separate video type called Anime, to differentiate it from TV Series and Movies
4. We can even implement the regularly updated scraper data from here: https://github.com/Anime-Lists/anime-lists

This would be amazing if it could be implemented.

### To Reproduce

1. Drop Anime into scan folder
2. See nothing happen

### Debuglog

The debuglog can be found here:
None needed

### Screenshots
Here are some links or screenshots to help explain the problem:

None

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

None

### Your Environment
Used Operating system:

 - [ X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
20.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by scythe000** [comment] 2024-02-06 18:59
Updated

**Comment by KarellenX** [comment] 2024-02-06 19:59
@scythe000 

Sorry, but I will need to close this.

Your report is a feature request. Github is for confirmed bug reports only.

Please repost on the Kodi forum.

Thanks.

**Comment by neo1973** [comment] 2024-02-06 20:00
> There's an advanced regex file parser in the wiki, why isn't it included by default?

Because it's specific to how anime releases are named and would clash with other, more common file names.

> Make the advanced parser included by default

See above

> Give us a default menu option called Anime

Why? We also don't add menu options for western cartoons, Chinese soap operas, etc. If you want separate menus the wiki has several options for that.

 > Make a separate video type called Anime, to differentiate it from TV Series and Movies

Anime are either a TV series or a movie.

> We can even implement the regularly updated scraper data from here: https://github.com/Anime-Lists/anime-lists

Scrapers are addons. Someone already created one for this data source in the past but it's not maintained anymore: https://forum.kodi.tv/showthread.php?tid=142835
Anyway, Kodi has it's default scrapers that fir 99% of the users, the rest has to look for special scraper addons.

My general recommendation: Rename everything to match themoviedb.org and use the Kodi default scraper. I do this for years and it works great.

**Closed by KarellenX** 2024-02-06 19:59 UTC
Labels: Ignored rules, Triage: Needed

**Comment by scythe000** [comment] 2024-02-06 20:03
> @scythe000
> 
> Sorry, but I will need to close this.
> 
> Your report is a feature request. Github is for confirmed bug reports only.
> 
> Please repost on the Kodi forum.
> 
> Thanks.

Understood, thank you :-)

**Comment by scythe000** [comment] 2024-02-06 20:07
> > There's an advanced regex file parser in the wiki, why isn't it included by default?
> 
> Because it's specific to how anime releases are named and would clash with other, more common file names.
> >It' surprising though, in 2024 the Kodi scraper still works so much worse than the Mediaportal one did 5-7 years ago.
> > Make the advanced parser included by default
> 
> See above
> 
> > Give us a default menu option called Anime
> 
> Why? We also don't add menu options for western cartoons, Chinese soap operas, etc. If you want separate menus the wiki has several options for that.
> >Because it's such a huge separate area, with it's own needs for how the data is scraped and handled, but point taken.
> > Make a separate video type called Anime, to differentiate it from TV Series and Movies
> 
> Anime are either a TV series or a movie.
> >They aren't, though. OVAs are very common and don't fit neatly into either category. Also many Anim TV series don't folow the standard season/episode model.
> > We can even implement the regularly updated scraper data from here: https://github.com/Anime-Lists/anime-lists
> 
> Scrapers are addons. Someone already created one for this data source in the past but it's not maintained anymore: https://forum.kodi.tv/showthread.php?tid=142835 Anyway, Kodi has it's default scrapers that fir 99% of the users, the rest has to look for special scraper addons.
> 
> My general recommendation: Rename everything to match themoviedb.org and use the Kodi default scraper. I do this for years and it works great.
>>The problem with this is that it makes it difficult to track releases unless you implement a hasher like some other solutions have. I may want to replace a series with a different release at some point and it's hard to tell which one I have if i've renamed everything.
