### ISSUE TITLE
Lost setting for WASAPI

### ISSUE THREAD

**Issue by chchia** [xbmc/xbmc#22021] opened 2022-10-12 03:52 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

Every time i need to manually switch the audio output to WASAPI from DirectSound as it always return to DirectSound when i turn off my TV or AV Receiver.

my current connection is HTPC -> Yamaha AV Receiver -> Panasonic TV

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Expected behavior should be KODI to remember always use the last setting, if user selected WSAPI default, it should be always try to apply WASAPI Default.

## Actual Behavior

it keep back to directsound when the TV or AV received is turned off, or restarted the HTPC.

### To Reproduce

1. Set audio output to WSAPI default.
2. Turn off AV received, TV and KODI
3. start KODI and it return to DirectSound

### Your Environment
Used Operating system:

 - [x] Windows

 - Operating system version/name: Windows 11
 - Kodi version: actually, this problem happens quick some time since few months ago, using 19, 20 included test build and problem still persists.
 - NVidia RTX3060 HDMI out
 - Yamaha RX-A2A receiver
 - Panasonic TV

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by thexai** [comment] 2022-10-12 06:54
No debug log provided

**Comment by thexai** [comment] 2022-11-08 11:26
Duplicate of https://github.com/xbmc/xbmc/issues/21852 closed this because other seems have more info

**Closed by thexai** 2022-11-08 11:26 UTC
Labels: Ignored rules, Triage: Tested and not reproduced
