### ISSUE TITLE
Kodi 19.4 crashes after hibernation on Fire Cube

### ISSUE THREAD

**Issue by DJDoena** [xbmc/xbmc#21413] opened 2022-05-16 18:47 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

This happens reproducible and always:
- Start Kodi
- Start movie
- Stop movie
- Press Home button on Fire Cube
- Select Kodi again -> crash

## Expected Behavior
-Kodi should come back from hibernation where it was left
### Debuglog

https://paste.kodi.tv/ebaweteyap.kodi

### Your Environment
Used Operating system:
 - [ X] Android Fire Cube
 - Operating system version/name:

 - Kodi version:
19.4 but has been happening for all of 19.x and even earlier

**Comment by quietvoid** [comment] 2022-05-16 20:21
Duplicate of https://github.com/xbmc/xbmc/issues/20620

**Comment by DJDoena** [comment] 2022-05-16 21:34
> Duplicate of #20620

It does not lock up actually as described in #20620, it will just close again and upon next try to open Kodi will start from scratch (including splash screen)

**Comment by quietvoid** [comment] 2022-05-16 21:38
It's the same issue. The launcher isn't keeping Kodi in memory.

**Comment by thexai** [comment] 2022-05-16 21:46
Closed in favor of https://github.com/xbmc/xbmc/issues/20620

**Closed by thexai** 2022-05-16 21:46 UTC
Labels: Resolution: Duplicate
