### ISSUE TITLE
TrueHD passthrough option is not available anymore in Kodi 19.0 for Mi Box 3 (MDZ-16-AB) Oreo

### ISSUE THREAD

**Issue by tranb3r** [xbmc/xbmc#19607] opened 2021-04-20 19:51 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

TrueHD passthrough option is not available anymore in Kodi 19.0 for Mi Box 3 (MDZ-16-AB) Oreo.
This option was available (and working) in Kodi 18.9, so it seems to be a regression introduced in Kodi 19.0.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The TrueHD passthrough option should be available in Kodi 19.0 (for Mi Box 3 (MDZ-16-AB) Oreo).

## Actual Behavior

The TrueHD passthrough option is not available anymore in Kodi 19.0 (for Mi Box 3 (MDZ-16-AB) Oreo).

## Possible Fix

I've checked the log. 
STREAM_TYPE_TRUEHD appears in 18.9 log, but not in 19.0 log.

### To Reproduce

1. Install Kodi 19.0 or 18.9 on Mi Box 3 (MDZ-16-AB) Oreo (I'm using firmware r2562)
2. In the settings, check if the TrueHD passthrough option is available.

### Debuglog

The debuglog can be found here:
- Kodi 18.9 (ok) : https://paste.kodi.tv/azozuhareq
- Kodi 19.0 (ko) : https://paste.kodi.tv/amalayageq

### Screenshots 
Here are some links or screenshots to help explain the problem:

N/A

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

N/A

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: AndroidTV Oreo r2562 for Mi Box 3 (MDZ-16-AB)
 - Kodi version: 19.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fritsch** [comment] 2021-04-20 19:55
The hacks for non standard firmware were removed from v19 entirely, we only support Android's standard Audiotrack enumerated formats. As your box seems to use amlogic special firmware which is not compatible, please stay on v18.

**Comment by tranb3r** [comment] 2021-04-20 20:01
Thank you for your answer.
Considering the number of people using this box around the world (the only cheap one supporting TrueHD), I'm a bit surprised by this decision.
Could you please explain a bit more why you consider its firmware "special" or "non standard", and also what kind of hack was removed (and why) ?

**Comment by fritsch** [comment] 2021-04-20 20:13
When kodi starts, we ask Audiotrack (https://developer.android.com/reference/android/media/AudioFormat#ENCODING_DOLBY_TRUEHD) which formats the box supports. We ask it for every format defined by the official google android implementation.

Whatever the box supports is enumerated.

On older kodi version we had some "intrusive" hacks for amlogic boxes concerning audio (separate jni definition, separate forced / hardcoded manual detections, separate, special reverse engineered format / channel combinations). These hacks broke modern amlogic boxes, famous example FireTV Cube.

Therefore after a grace period of more nearly 5 years (16, 17, 18, 19) - it was removed. That's it.

Here you see the change: https://github.com/xbmc/xbmc/commit/926d2e30c4e6dfad1730229b71e36b1b5e80dbe7#diff-9884fdeb14fb2a0179b4983db00f524e1298005123d633a3b2ed9a261248e1e9

Btw. you might not have seen it yet. Kodi v19 gives the option to decide between RAW and IEC passthrough device. Perhaps your box supports more formats with one than the other.

And for the reasoning: Kodi's android is currently not maintained anymore, maintaining all diverse hackarounds when fixing a bug was simply not doable anymore.

**Comment by fritsch** [comment] 2021-04-20 20:16
And please post your debuglog, here we can see what the box officially supports.

**Comment by fritsch** [comment] 2021-04-20 20:22
Wait a moment:

v18:
```
Running on Xiaomi MIBOX3 with Android 8.0.0 API level 26, kernel: Linux ARM 32-bit version 4.9.54
2021-04-20 21:03:07.818 T:25627   DEBUG: AESinkAUDIOTrack: Using IEC PT mode: 13
2021-04-20 21:03:07.895 T:25627   DEBUG: 8 Channel PT via IEC61937 is supported
```

v19:
```
Running on Xiaomi MIBOX3 with Android 8.0.0 API level 26, kernel: Linux ARM 32-bit version 4.9.54
...
2021-04-20 21:21:59.363 T:5509    DEBUG <general>: E-AC3 and DTSHD-HR via IEC61937 is supported
2021-04-20 21:21:59.381 T:5509    DEBUG <general>: VerifySinkConfiguration samplerate: 192000 mask: 6396 encoding: 13 success: **false**
```

That basically makes no sense. Your box is one of those that implements 8 channels IEC61937 - it's not affected by any of the above changes also not affected by the removal of this code.

Infact: on your old log the box opened 8 channel IEC format, on the new log it did not - this code path had zero changes in v19, therefore I wonder if a power cycle of the AVR / TV with this new version might help.

**Comment by altaroinj** [comment] 2021-04-21 08:39
Hello Fritsch,
Could you please explain what you mean by "a power cycle of the AVR / TV" ?
I have the exact same issue.
And by the way, do you know a procedure to backup first the DB of Kodi 18 before trying to reinstall Kodi 19 and make the test ?

**Comment by tranb3r** [comment] 2021-04-21 08:39
@fritsch I've read everything but I think I'm a bit lost.

- Kodi's android is not maintained anymore : is there a fork or a suggested alternative ?
- RAW vs IEC passthrough device in Kovi v19 : no difference for TrueHD option visibility, as shown in the log (device1 vs device2)
- The change that removed the AML hack : I understand you had to remove it, but maybe you could have given the user the choice to enable it or not (with an expert setting, and a clear explanation of the risk) ?
- Then you add "that basically makes no sense". Does it mean the AML hack removal is not the reason for this issue ? How can I help ? Is there a test I can do to help with the investigation ?

**Comment by tranb3r** [comment] 2021-04-21 08:42
> And finally, could you explain me how to get the logs just like @tranb3r did ?

For the log, use the "kodi logfile uploader" addon, then enable debug log in kodi settings, then restart kodi and launch the add-on and upload the file, you'll get the url in a qrcode.

**Comment by pipapapipipapa** [comment] 2021-04-21 11:40
Possibly the reason is https://github.com/xbmc/xbmc/pull/16958 ?

**Comment by fritsch** [comment] 2021-04-21 19:48
Good catch! Let's try.

Build is running here: https://jenkins.kodi.tv/job/Android-ARM/21093/ will have the name "revtest" in the filename and land here: http://mirrors.kodi.tv/test-builds/android/arm/

Thanks much for testing.

**Comment by fritsch** [comment] 2021-04-21 20:03
http://mirrors.kodi.tv/test-builds/android/arm/kodi-20210421-4caddf48-revtest-armeabi-v7a.apk

**Comment by tranb3r** [comment] 2021-04-21 20:21
> http://mirrors.kodi.tv/test-builds/android/arm/kodi-20210421-4caddf48-revtest-armeabi-v7a.apk

I've just tested this build, and it works: the truehd passthrough option is available.

**Comment by fritsch** [comment] 2021-04-21 20:24
Perfect. I create another build right now, where I reduce the size to two times the minimum. Will post it in some minutes.

**Comment by tranb3r** [comment] 2021-04-21 20:29
Wait. The option is available. But the signal sent to the avr is pcm.

**Comment by tranb3r** [comment] 2021-04-21 20:32
Also for some unknown reason the log uploader add-on does not work with this build...

**Comment by fritsch** [comment] 2021-04-21 20:34
Next try, please: http://mirrors.kodi.tv/test-builds/android/arm/kodi-20210421-409afa82-revtest-armeabi-v7a.apk

**Comment by fritsch** [comment] 2021-04-21 21:36
Curious for your log. I found another position where the same thing could basically hit you. The debuglog file now with opening TrueHD will tell.

**Comment by tranb3r** [comment] 2021-04-22 16:07
Here are the logs for both versions:
- https://paste.kodi.tv/goforoqale.kodi
- https://paste.kodi.tv/sevaketira.kodi

In both versions, the truehd passthrough option is available, BUT when playing a TrueHD file, the AVR receives a PCM signal.

**Comment by fritsch** [comment] 2021-04-22 16:31
http://mirrors.kodi.tv/test-builds/android/arm/kodi-20210422-3c0bf32b-revtest-armeabi-v7a.apk Here we go. That should work again, right?

**Comment by tranb3r** [comment] 2021-04-22 19:50
Yes, this one seems to work !
Here is the log : https://paste.kodi.tv/demonihame.kodi

**Comment by fritsch** [comment] 2021-04-22 20:00
Great news. I have another build in the pipeline that tries to open a bit more buffer. Currently the dts-hd / truehd is at the very minimum of the device. Whenever some interruption happens, your audio will click or stutter. Therefore I try to at least aim at 80 ms, while I tried 150 before. Would be nice, if you could test the next build I upload as well.

**Comment by fritsch** [comment] 2021-04-22 20:01
What works here? http://mirrors.kodi.tv/test-builds/android/arm/kodi-20210422-5acae881-revtest-armeabi-v7a.apk

**Comment by tranb3r** [comment] 2021-04-23 11:55
The 5acae881 does not work properly:
- the passthrough options are available
- but when playing hd files, I only get stereo for most of them (I've tested both truehd and dts-hd ma files, in 5.1 and 7.1)
Here is the log : https://paste.kodi.tv/joweheyafe.kodi

Also, I've done a quick test with your previous build (3c0bf32b), and my DTS-HD MA 7.1 test file actually does not work.

(no issue for all my test files in Kodi 18.9)

**Comment by fritsch** [comment] 2021-04-23 13:35
Okay. Then so only the first version from yesterday evening works for you. This is still the case right?

**Comment by fritsch** [comment] 2021-04-23 13:37
Okay, got it. So the version that worked yesterday which included the non changed PT in comparison to Leia worked yesterday but not today.

Then I am out of ideas, sorry.

**Comment by tranb3r** [comment] 2021-04-23 16:05
We're on different timezones so I'm totally lost when you refer to "yesterday evening"...

Maybe it would help if you tried to recap what you've changed in the different builds, and what progress you've made regarding the different issues I'm facing:
- the availability of the hd audio passthrough options
- the proper playback of truehd files
- the proper playback of dts-hd ma files

**Comment by fritsch** [comment] 2021-04-23 16:55
Which build is working for you?

**Comment by altaroinj** [comment] 2021-04-23 17:19
Correct me if I'm wrong @tranb3r, but what you meant is :
1. You tested Dolby True HD passthrough on build [3c0bf32b](https://github.com/xbmc/xbmc/commit/3c0bf32b1357aba024ee338a279c7cbda6cd6758) and it worked.
2. Then, on build [5acae88](https://github.com/xbmc/xbmc/commit/5acae881bbfd4a58022898ee2d51e9e494cad4b7), none of your files worked (Dolby True HD or DTS HD MA).
3. And finally, you got back on build [3c0bf32b](https://github.com/xbmc/xbmc/commit/3c0bf32b1357aba024ee338a279c7cbda6cd6758) where you tested your DTS HD MA files (I assume you hadn't try them the first time), and those were not working.

Did I undertand well what happened ? If not, I will just shut my mouth.  ;-)

**Comment by fritsch** [comment] 2021-04-23 18:03
TrueHD and DTS-HD MA via IEC is from "Android POV" exactly the same. They only open 8 channels / 192 khz in IEC mode - they have no idea if we send TrueHD or DTS-HD IEC frames.

So it makes limited sense that one works and the other not. I cannot speak for the AVR behind it.

**Comment by fritsch** [comment] 2021-04-23 18:07
So, then post the logs with this version again: http://mirrors.kodi.tv/test-builds/android/arm/kodi-20210422-3c0bf32b-revtest-armeabi-v7a.apk

Also make sure that it actually installs, as it's now a downgrade.

**Comment by tranb3r** [comment] 2021-04-23 19:26
@altaroinj YES
- 4caddf48eb : AVR receives PCM for TrueHD file
- 409afa8283 : AVR receives PCM for TrueHD file
- 3c0bf32b13 : TrueHD works ; DTS-HD MA 5.1 works ; DTS-HD MA 7.1 does not work
- 5acae881bb : none of my HD files worked

**Comment by tranb3r** [comment] 2021-04-24 12:55
I've given a quick look at the code, and this buffer size logic is a bit weird...

For capability detection, maybe it would be better to start with a small buffer size, and then increase it if it is not enough ? Instead of aiming for the perfect multiplicator (4 or 2 or whatever) which obviously does not seem to work.

For the playback issue, there is not enough comments in the code to understand the changes. 
Many constant values have been modified between leia and matrix, and I'm not expert enough to understand the logic. 
There are also plenty of mysterious multiplications and divisions of sizes....
Maybe if you can explain a bit the logic, we can figure out how to fix it ?

**Comment by fritsch** [comment] 2021-04-24 13:13
What you read from the code is wrong :-). In audio world two things are important: enough buffer (else underruns), enough time to come back to add new samples, else underrun and immense cpu load. The Verify code was increased cause there were devices out there that said: sorry I cannot open the format with just 2 minbuffer sizes. The Mi-Box DTS-HD-MA / TrueHD issue is a separate edge case, which is unfortunate but yeah - all other boxes work.

So what an implementation needs to do:
These two things need to be mitigated. On all our platforms we aim at 200 ms buffer and 50 ms periods. Means you can easily be blocked for 150 ms without adding any data and nothing will hapn. If you would open it with 100 ms buffer and just 50 ms periods, you would get an underrun right away when you miss to add one buffer.

From this logic it gets clear that buffer size needs to be at least twice the period size so that it works at all (minbuffer vs minbuffer by 2). So still if minbuffer is below 100 ms and only can take small periods cpu load goes up, underruns will happen.

The reason was that a very power ful device (Nvidia Shield) had constant audio drop outs whenever you went into the menu while playing back audio. Means: basic features won't work if you configure too low - if someone's dts-hd leds blink properly is of second interest there. Also: For now only this MI-Box has issues with this combination.

Never the less: http://mirrors.kodi.tv/test-builds/android/arm/kodi-20210424-ca95fd99-revtest-armeabi-v7a.apk
This restores Leia behaviour 1:1 for dts-hd-ma and truehd by using minbuffer*2 as buffer and minbuffer as periods.

Please check what works and provide a log when it does not, especially with DTS-HD-MA that you did not yet do with the "working" version.

**Comment by tranb3r** [comment] 2021-04-24 15:44
@fritsch Thanks a lot for the answer. 
I really appreciate your taking the time for a detailed explanation.

> if someone's dts-hd leds blink properly is of second interest there

I totally understand. By the way, if you think we're our time here, feel free to close this issue. I'm happy with staying with kodi 18.9 if you think this is the only viable long-term solution.

> Please check what works and provide a log when it does not

No time right now, but I'm happy to do one more test if this can help, so I'll do it and post the result here asap.

**Comment by fritsch** [comment] 2021-04-24 16:22
No hurry. Private life is important to everyone. Whenever you get time, please post me a debuglog with the last build I linked. Maybe download it now, so that it does not vanish from the build server.

Have a nice weekend.

**Comment by tranb3r** [comment] 2021-04-25 12:50
Everything is ok with build ca95fd99, except for the "DTS-HD MA 7.1.m2ts" file, for which my AVR receives only DTS (core).
Here is the log : https://paste.kodi.tv/morakisapo.kodi

**Comment by fritsch** [comment] 2021-04-25 16:48
Awesome. That last file has nothing to do with Audiotrack, parsing failes from ffmpeg (0 Channels detected) and also our internal parser only finds DTSHD-Core. Are you sure that worked on Leia?

**Comment by fritsch** [comment] 2021-04-25 16:50
Could you post me another log with a succesful playing DTS-HD-MA? Then I can verify the buffers / period timings and maybe we could try another iteration if you like.

**Comment by tranb3r** [comment] 2021-05-02 13:04
I've tested 3 different DTS-HD MA files.
- DTS-HD MA 5.1.mkv 
- DTS-HD MA 7.1.mkv
- DTS-HD MA 7.1.m2ts

Here is the audio stream information for these files, as shown by mediainfo:
- DTS-HD MA 5.1.mkv :
```
ID                                       : 2
Format                                   : DTS XLL
Format/Info                              : Digital Theater Systems
Commercial name                          : DTS-HD Master Audio
Codec ID                                 : A_DTS
Duration                                 : 1 min 7 s
Bit rate mode                            : Variable
Bit rate                                 : 4 259 kb/s
Channel(s)                               : 6 channels
Channel layout                           : C L R Ls Rs LFE
Sampling rate                            : 48.0 kHz
Frame rate                               : 93.750 FPS (512 SPF)
Bit depth                                : 24 bits
Compression mode                         : Lossless
Stream size                              : 34.4 MiB (10%)
Title                                    : dts-hd ma 5.1
Language                                 : English
Default                                  : Yes
Forced                                   : No
```

- DTS-HD MA 7.1.mkv :
```
ID                                       : 2
ID in the original source medium         : 4352 (0x1100)
Format                                   : DTS XLL
Format/Info                              : Digital Theater Systems
Commercial name                          : DTS-HD Master Audio
Codec ID                                 : A_DTS
Duration                                 : 18 s 944 ms
Bit rate mode                            : Variable
Bit rate                                 : 2 595 kb/s
Channel(s)                               : 8 channels
Channel layout                           : C L R LFE Lb Rb Lss Rss
Sampling rate                            : 48.0 kHz
Frame rate                               : 93.750 FPS (512 SPF)
Bit depth                                : 24 bits
Compression mode                         : Lossless
Stream size                              : 5.86 MiB (9%)
Title                                    : Surround 7.1
Language                                 : English
Default                                  : Yes
Forced                                   : No
Original source medium                   : Blu-ray
```

- DTS-HD MA 7.1.m2ts :
```
ID                                       : 4352 (0x1100)
Menu ID                                  : 1 (0x1)
Format                                   : DTS XLL
Format/Info                              : Digital Theater Systems
Commercial name                          : DTS-HD Master Audio
Muxing mode                              : Stream extension
Codec ID                                 : 134
Duration                                 : 1 min 27 s
Bit rate mode                            : Variable
Channel(s)                               : 8 channels
Channel layout                           : C L R LFE Lb Rb Lss Rss
Sampling rate                            : 48.0 kHz
Frame rate                               : 93.750 FPS (512 SPF)
Bit depth                                : 24 bits
Compression mode                         : Lossless
```

With Kodi 18.9, all 3 files work as expected. 
Here is the log : https://paste.kodi.tv/rexitijumo

With Kodi ca95fd9927:
- both .mkv files work as expected: AVR receives DTS-HD MA signal
- for the .m2ts file, the ARV receives only DTS.
- here is the log: https://paste.kodi.tv/qugelabupa.kodi

Do not hesitate to ask if you need more information.
Thanks !

**Comment by fritsch** [comment] 2021-05-02 16:47
Thanks and good that DTS-HD MA in general as well as TrueHD work again. The m2ts case is a different regression. When you see the log there ffmpeg triggers a stream change and after this stream change it detects 0 channels and just DTS, with this DTS your file is opened. I don't have time to look into this second issue.

You might even have luck playing it by just renaming (no kidding) to .mp4 ... as this will trigger a different code path.

**Comment by tranb3r** [comment] 2021-05-15 19:56
Thanks again @fritsch for this fix!  
Do you know if it's part of the 19.1 release?

About the second issue: I've tested renaming the m2ts file to mp4, but the result is the same.
It's not a big deal for me, so feel free to open a new ticket if you think it's worth it.

**Comment by fritsch** [comment] 2021-05-16 08:23
No, it's not in - will be in 19.2

For the file:
ffmpeg -i "yourfile.m2ts" -c:a copy -c:v copy yourfile.mp4

**Comment by tranb3r** [comment] 2021-05-16 13:46
> No, it's not in - will be in 19.2
Ok. Perfect!

> For the file:
> ffmpeg -i "yourfile.m2ts" -c:a copy -c:v copy yourfile.mp4
I confirm it works. Thank you.

**Comment by supermanscottbristol** [comment] 2021-07-28 19:24
Hi folks - is it possible to get a copy of this version with the truehd passthrough enabled?  
I've got the same Mi Box 3, Android 8 and was hoping to test out a TrueHD receiver I have installed.

Thank you.

**Comment by tranb3r** [comment] 2021-07-29 11:27
> Hi folks - is it possible to get a copy of this version with the truehd passthrough enabled?
> I've got the same Mi Box 3, Android 8 and was hoping to test out a TrueHD receiver I have installed.
> 
> Thank you.

Simply download the latest kodi 19.1 version here: https://mirrors.kodi.tv/nightlies/android/arm/Matrix/
Then you can enable passthrough in kodi system audio settings (assuming your mi box 3 has not been updated to android 9).

**Comment by supermanscottbristol** [comment] 2021-07-29 12:16
Thanks again for the info - but I'm looking for a TrueHD option which I do not get.  I get various options like DTS, Dolby Digital Plus, but nothing about TrueHD or DTS HD MA
When I enable passthrough and try and use either of these sound formats I get no sound.

**Comment by supermanscottbristol** [comment] 2021-08-07 18:53
When trying the nightly version, it greys out my choice of passhthru device, and in the passthru section there is literally nothing at all.

Does anyone know the version that would give me TrueHD passthru on MiBox3 with Android 8 ?

**Comment by rajrajan21** [comment] 2021-09-08 06:43
Hi, This is a very useful post.
I am using Mi TV and also facing the same issue when passthrough the audio from my android TV to Atmos soundbar (Supported for DOLBY TRUE HD ATMOD). 
Dolby True HD audio files are not getting passthrough in Kodi version 19.1 installed in my android tv, also it is not showing Dolby True HD receiver option in Audio -> Expert settings.
I am going to try installing Kodi version 18.9 with the build (ca95fd99 or 3c0bf32b) that you have posted in this forum. However, the mirror links are given in below which were given are no longer working and the file is not found.
http://mirrors.kodi.tv/test-builds/android/arm/kodi-20210422-3c0bf32b-revtest-armeabi-v7a.apk
http://mirrors.kodi.tv/test-builds/android/arm/kodi-20210424-ca95fd99-revtest-armeabi-v7a.apk

Could you please upload or repost this apk file to work this out? Thanks for your help.

Kindly let me know if you need any information.

**Comment by tranb3r** [comment] 2021-09-08 07:11
@rajrajan21 Did you test the latest 19.1 nightly build ?
https://mirrors.kodi.tv/nightlies/android/arm/Matrix/kodi-20210907-86093ca4-Matrix-armeabi-v7a.apk

**Comment by Kischen** [comment] 2021-09-08 10:52
Hi guys,

I cant even choose passthrough anymore. Like, the field underneath passthrough is empty.
I use novaplayer as well and PT is working there, not for HD-audio but still better than 2.0 pcm.

**Comment by tranb3r** [comment] 2021-09-08 11:20
@Kischen This thread is about Mi Box 3. I think that Mi Box S does not support HD-audio.

**Comment by rajrajan21** [comment] 2021-09-08 12:59
> @rajrajan21 Did you test the latest 19.1 nightly build ?
> Hi Peter,
Yes, Kodi version in my tv is 19.1.0 and Dolby truehd receiver is not enabled.

The below link which you sent seems like a recent build. Let me check this also. 
https://mirrors.kodi.tv/nightlies/android/arm/Matrix/kodi-20210907-86093ca4-Matrix-armeabi-v7a.apk

**Comment by rajrajan21** [comment] 2021-09-08 13:21
Unfortunately this above link with the kodi version 19.1 is not working either. It is showing me an option to enable Dolby TrueHD receiver option in Audio passthrough. Please let me know if you want a log to be shared.
Also, kindly let me know if i need to open a new thread.
Actually this forum is really helpful to try for options and providing support, thats great and I really appreciate it.

**Comment by Kischen** [comment] 2021-09-08 14:06
> @Kischen This thread is about Mi Box 3. I think that Mi Box S does not support HD-audio.

I seem to have a mi box 4 :/ I could be wrong but i had passthrough, now i dont, im not sure if it had HD audio, its not a big deal actually but the passthrough as a whole are.

I just found this thread, seems like a place for good information, sorry if im at the wrong thread but the issue seems related.

**Comment by Kischen** [comment] 2021-09-08 14:43
I found my problem. I dont know why caused it but kodi had changed do "audiotrack raw" without offering iec, i unistalled kodi and installed again. All is well :)

**Comment by vijayinvites** [comment] 2021-09-28 14:50
> Unfortunately this above link with the kodi version 19.1 is not working either. It is not showing me an option to enable Dolby TrueHD receiver option in Audio passthrough. Please let me know if you want a log to be shared. Also, kindly let me know if i need to open a new thread. Actually this forum is really helpful to try for options and providing support, thats great and I really appreciate it.

@rajrajan21 Were you able to make it work on MI TV? I have MI TV 5X as well, and trying to get Atmos TrueHD work. Please let me know which TV are you using.

**Comment by rajrajan21** [comment] 2021-09-28 15:19
@vijayinvites 

To conclude, Dolby True HD would not work in MI tv, at least at present. I raised a call with MI service center, a technician visited and understood the problem I reported but can't provide any solution yet.

I found a workaround by connecting my laptop in a HDMI cable to my sound bar and then plays Dolby True HD Atmos from VLC player in Laptop (Setup Audio Passthrough option) and it sends Atmos signal to Sound bar and works fine. Even connecting from laptop to TV through HDMI and from there also through eArc passthrough from TV to Sound bar, True HD Atmos working perfectly fine.

So this confirms at least MI TV does supports the Dolby True HD Atmos passthrough in eARC from TV to sound bar, but only from Mi TV Apps, it couldn't pass through True HD Audio to Sound bar. Thats the reason KODI app in TV is not showing Dolby True HD option enabled. May be we need to wait till they do some software updates on MI android tv to get it fixed. I doubt so anyways.

Besides Dolby Digital plus (Atmos) was not working in my MI QLED earlier and now after the software updates came in June/July version, it works. At least Netflix with DD+ Atmos is working directly from MI TV

Let me know if you need any information.

**Comment by vijayinvites** [comment] 2021-09-28 15:26
@rajrajan21 Thanks for the response. I tried MX player on the TV and it was able to play the Atmos TrueHD, but the sound was not at all good. There was a crackling sound, not at all good. But the soundbar said it was Dolby Atmos. So looks like MX Player can play it, but when I tried it was not at all pleasant. Can you try MX player and see if it works for you.

**Comment by rajrajan21** [comment] 2021-09-28 16:52
@vijayinvites,
Few weeks back, I tried mx player with codec, mx pro, Plex, Nova and few more Android tv players which I found in web, nothing played true HD Atmos from tv.

May I know how did you get the source to  play Dolby true HD in mx player in TV. I used xplore android tv software which access my pc network drive to play from there.
But I can give a try again on mxplayer and let you know. Thanks.

**Comment by vijayinvites** [comment] 2021-09-28 16:55
@rajrajan21 I have Atmos demo disk on my harddrive, which I attached it to the TV. Launched MX Player, setting the Audio as passthrough and it played. But the sound was unbearable. Stop and start kind of sound. I thought MX Player was not able to handle the atmos bandwidth or may be the TV.

**Comment by rajrajan21** [comment] 2021-09-28 17:27
@vijayinvites 
Installed mxplayer with mx AIO codec to support Dolby true HD and played a local file copied it to my TV storage and played using mxplayer (audio passthrough), no Atmos displayed in my sound bar but sound quality is good.

I noticed although Kodi app in tv does not passthrough true HD Atmos, the quality of sound is almost similar to how I play from pc connected to sound bar with 'Atmos' displayed. Anyways for now I will stick to pc hdmi to play true hd until any software updates.

**Comment by vijayinvites** [comment] 2021-09-28 17:30
> @vijayinvites Installed mxplayer with mx AIO codec to support Dolby true HD and played a local file copied it to my TV storage and played using mxplayer (audio passthrough), no Atmos displayed in my sound bar but sound quality is good.
> 
> I noticed although Kodi app in tv does not passthrough true HD Atmos, the quality of sound is almost similar to how I play from pc connected to sound bar with 'Atmos' displayed. Anyways for now I will stick to pc hdmi to play true hd until any software updates.
I don't think you should install any codec. If you had selected passthrough, the bit stream will be sent to the soundbar. MX player shouldn't need any codec. If you use codec, MX player decodes atmos and send the audio to the soundbar. That is not what we want.

**Comment by rajrajan21** [comment] 2021-09-29 02:25
@vijayinvites 
If I install the default MX player software in TV and play Atmos file, it says true HD audio format not supported and audio is very low. Then I added mx audio codec AIO and the error is not anymore and the sound quality is good. No Atmos in sound bar.
That's fine, I am fine with VLC player played it from pc which outputs Atmos great 😁

**Comment by vijayinvites** [comment] 2021-09-29 05:23
> @vijayinvites If I install the default MX player software in TV and play Atmos file, it says true HD audio format not supported and audio is very low. Then I added mx audio codec AIO and the error is not anymore and the sound quality is good. No Atmos in sound bar. That's fine, I am fine with VLC player played it from pc which outputs Atmos great 😁

Cool, thanks rajrajan. Whenever you find a way to get TrueHD from TV app itself, do let me know. I will do the same. 

Also, please let me know, when the TV starts, do you get a message saying "HDMI ARC device connected" or "HDMI eARC device connected" ?

**Comment by vijayinvites** [comment] 2021-09-29 12:42
> @vijayinvites
> 
> 
> 
> ...Even connecting from laptop to TV through HDMI and from there also through eArc passthrough from TV to Sound bar, True HD Atmos working perfectly fine.
> 
> 
@rajrajan21 The method that you mentioned above, did not work for me. I could see that TrueHD option was available on Kodi, but when I played, my sound bar did not recognize it as Atmos sound. When I changed the track to DD+, it recognized. So I am still suspecting that TV is not sending the TrueHD through eARC.

**Comment by altaroinj** [comment] 2021-09-29 13:52
Hi guys,
I think you are not on the right ticket to discuss about your issue, as if I understand well, it concerns Mi TV.
This ticket is about MiBox 3 only, and especially in version Oreo 8.0.
Newer version of firmwares, starting Oreo 8.1, deactivated Dolby True HD passthrough at Android level (and MiBox S never had the chance to have this feature, even though it shares the same hardware specs).

@fritsch
Do you know when Kodi 19.2 will be released and are you sure this fix will be included in the release ?

**Comment by thexai** [comment] 2021-09-29 16:31
Fix is already merged in both master and Matrix

**Closed by thexai** 2021-09-29 16:31 UTC
Labels: Triage: Needed

**Comment by cybermay** [comment] 2022-09-29 06:22
In the latest version of the test still did not fix this problem ah
