### ISSUE TITLE
GUI Notifications issue when debug logging is OFF

### ISSUE THREAD

**Issue by piejanssens** [xbmc/xbmc#14583] opened 2018-10-11 14:04 UTC
I originally noticed an issue with the notifications when I was switching subtitles. I would expect to see the next subitlte language notification to appear immediatly on screen and be allowed to switch languages faster than the notifications appear and dissappear on screen. This is currently not the case.

I did a test with a key map that shows a very odd difference between debug logging ON and debug logging OFF. 

When debug logging is OFF and you trigger multiple notifications in close succession it only shows the first (and sometimes the second), but not the others. When debug logging is turned ON the latest notification will be shown immediately and it cancels the previous one. This latest behavior is what I expect and also the only behavior that works for circulating through subtitle languages.

### To Reproduce
Using latest Kodi Nightly e78d2d41:
1.  Set keymap for testing
```
<keymap>
	<global>
		<keyboard>
			<F1>Notification(Testing,#1)</F1>
			<F2>Notification(Testing,#2)</F2>
			<F3>Notification(Testing,#3)</F3>
			<F4>Notification(Testing,#4)</F4>
			<F5>Notification(Testing,#5)</F5>
		</keyboard>
	</global>
</keymap>
```
2. Open Kodi
3. Press 'F1', 'F2', 'F3', ... one after the other
4. You can only see the first notification message
5. Switch debug logging on
6. Press 'F1', 'F2', 'F3', ... one after the other
7. You can see the latest notification each time

I also have the impression that the reaction time of pressing the Fn key and the notification being shown on screen should be less to make it feel more responsive.

### Debuglog
!!! This issue does not occur when debug logging is on!!! 
The debuglog can be found here: [kodi.log](https://github.com/xbmc/xbmc/files/2469226/kodi.log)

**Comment by DaVukovic** [comment] 2018-10-11 14:15
I see the same behaviour on Linux (Ubuntu) as well.

**Comment by piejanssens** [comment] 2018-11-21 20:03
This issue does not occur on macOS.
So far it's confirmed on Windows and Linux (Ubuntu/OSMC).
I can't belief this hasn't been raised more often as it's really annoying not being able to see what language you are selecting when pressing 'next subtitle' and cycling through.

**Comment by YisraelV** [comment] 2018-12-12 18:07
@piejanssens @DaVukovic are you sure it would be correct for the new notification to hide the previous one? what if they come from different sources? In other apps usually notifications stack in some way next to each other.

**Comment by piejanssens** [comment] 2018-12-12 19:01
In case of subtitles the only correct scenario is that you see the language you switch to immediately. Right now I'm completely lost as soon as I press next subtitle, next subtitle I have no visual feedback and need to wait for the subtitle to appear on screen to see if it's the language I'm looking for or not. 

One possible implementation would be to distinguish between notifications that are triggered by the user (these go to the front of the queue and replace other notification of this type in case there is still one on screen) vs other (these queue up, each with their own screen time to shine).

**Comment by pkerling** [comment] 2018-12-19 11:56
@piejanssens How do you switch subtitles?

I can reproduce with the keymap example. But not with subtitles. When I press `l` to cycle through the subtitle streams, the notification always appears instantly regardless of debug setting.

**Comment by pkerling** [comment] 2018-12-19 12:37
nvm I think I have the issue, toasts have a queue and all but the redraw is missing when the text is short, so you see the first message all the time

**Comment by piejanssens** [comment] 2018-12-19 21:37
Awesome! I hope the fix is not to complicated.

**Comment by pkerling** [comment] 2018-12-20 08:38
@piejanssens Please test #15097

**Comment by piejanssens** [comment] 2018-12-20 09:44
@pkerling Happy to test, but where do I download the bins?
Couldn't find it in http://mirrors.kodi.tv/test-builds/ or Perkins

**Comment by pkerling** [comment] 2018-12-20 10:23
@piejanssens should be there now

**Comment by piejanssens** [comment] 2018-12-20 14:13
Fix is good.

**Comment by DaVukovic** [comment] 2018-12-20 17:21
@pkerling 

I can confirm that the issue is fixed with your PR.

**Closed** 2018-12-20 18:09 UTC
Labels: Rendering GUI, v18 Leia
