### ISSUE TITLE
Image based subtitles in Nexus

### ISSUE THREAD

**Issue by kenzoka24** [xbmc/xbmc#21141] opened 2022-03-18 07:43 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

Image based subtitles stretch in 2.40ar video files, compress in 4:3 videos
Kodi matrix used to scale them to display resolution (most of displays being 16:9 AND on ultrawide monitors you could scale to a 16:9 resolution but it doesn't work anymore in the latest kodi nexus nightly) but the latest kodi nexus nightly scales the subtitles to video resolution which distorts them

## Expected Behavior

subtitles should be scaled to display resolution

## Actual Behavior

subtitles are scaled to video resolution which compresses them

### To Reproduce

1. video file https://drive.google.com/file/d/1Pgl7ZoYyCsROz4yABWSAnwMaQlhkS2bf/view?usp=drivesdk
2. I have included 3 subtitles in this mkv which can cycled through in kodi to see the behaviour

### Debuglog

The debuglog can be found here:

### Screenshots
Here are some links or screenshots to help explain the problem:

Kodi 19 overscan
![immagine](https://user-images.githubusercontent.com/3257156/159120111-bb4afc48-387a-4084-afe6-0899566beaa3.png)
Kodi 20 overscan
![immagine](https://user-images.githubusercontent.com/3257156/159120157-06ca55ee-69b4-4122-be22-c13ca3ad2137.png)
Kodi 20
![immagine](https://user-images.githubusercontent.com/3257156/159120123-def3e6d6-4756-407f-91de-b2e71c13cba1.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

this is most certainly a down grade compared to Matrix

### Your Environment
Used Operating system:

 - [ ✓] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ✓] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 20 Nexus 20220315

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment] 2022-03-18 10:27
I can confirm this issue (not sure when it started to happen but was not the case a few time ago). Maybe added with the fixes for bluray/dvd menus @CastagnaIT ?

**Comment by kenzoka24** [comment] 2022-03-18 10:42
I just wanted to see if it was a problem in Nexus,
tried it and was scared enough to bring this to attention

**Comment by CastagnaIT** [comment] 2022-03-19 12:17
i have tried testing attached video file by using or not overscan and also by resizing window,
in my tests and also from your screenshots i do not see nothing of wrong for Nexus, also comparing with VLC and MPV players

On nexus has been fixed the aspect ratio of the image subs and also his position on screen that was broken on Kodi 19
and was not respecting where the text should appear.

**Comment by kenzoka24** [comment] 2022-03-19 12:29
> i have tried testing attached video file by using or not overscan and also by resizing window,
> in my tests and also from your screenshots i do not see nothing of wrong for Nexus, also comparing with VLC and MPV players
> 
> On nexus has been fixed the aspect ratio of the image subs and also his position on screen that was broken on Kodi 19
> and was not respecting where the text should appear.
> 
> This is not a bug but intended as correct functioning

have you tried the different subtitles included in the file?

they look distorted man, no two way about it

even when you convert bluray remuxes with handbrake or staxrip they automatically crop and remove "black bars" from the video

which changes the aspect ratio of the video from 16:9 to something like 4:3 or 2.40

So if kodi doesn't match the aspect ratio of 16:9 they will distorted like this

it obviously looks worse, even if it is the intended functionality or not

what is the aspect ratio of the display you tested on?

**Comment by kenzoka24** [comment] 2022-03-19 12:41
> On kodi 19 the subs images are referred to the display rect, and this is wrong because not respect the position where the (video) authors want place the subs, furthermore, this also involves the remote possibility of sub images exceeding the screen size or also being positioned in the wrong location (for dialogues cases).



you have got to understand please 🙏


ONLY videos with 1920x1080 and 3840x2160, show the image based subtitles correctly



If I reencode it with handbrake or staxrip, it changes the aspect ratio automatically cause it removes the black bars from the video

AND when I remux the subtitle and audio stream from the original file with mkvtoolnix, the  subtitles look distorted


this is solving problems for the 1920x1080 and 3840x2160 videos and **creating** problems for **NON**16:9 videos

**Comment by CastagnaIT** [comment] 2022-03-19 12:44
PGS are referred to the video source if you crop the video height the subs will not respect the original aspect ratio anymore

IMO you are asking a custom feature that you should ask in the forum feature section
if this will be considered, it will of course best for your use case, but it will break the subs with the original videos

**Comment by kenzoka24** [comment] 2022-03-19 12:51
> PGS are referred to the video source if you crop the video height the subs will not respect the original aspect ratio anymore
> 
> IMO you are asking a custom feature that you should ask in the forum feature section
> if this will be considered, it will of course "best" for your use case (despite the side effects), but it will break the subs with the original videos

it **still** breaks VOBSUB subtitles

**Comment by CastagnaIT** [comment] 2022-03-19 12:54
your video height is cropped then all image based subs will be with wrong aspect ratio this is normal behaviour

**Comment by CastagnaIT** [comment] 2022-03-19 12:55
> this is breaks the pre existing functionality from the last 2 years I have been using it

you are not read what i wrote some comment above
Kodi 19 was providing a broken feature
if you dont like this keep to Kodi 19 or ask for a new feature

**Comment by kenzoka24** [comment] 2022-03-19 12:56
> your video height is cropped then all image based subs will be with wrong aspect ratio this is normal behaviour

**ALL** the media that exists outside of bluray, and uhd bluray is **always** cropped in someways or another


it will always have this problem

**Comment by kenzoka24** [comment] 2022-03-19 12:59
> > this is breaks the pre existing functionality from the last 2 years I have been using it
> 
> you are not read what i wrote some comment above
> Kodi 19 was providing a broken feature
> if you dont like this keep to Kodi 19 or ask for a new feature

this is solving problems for the 1920x1080 and 3840x2160 videos and creating problems for NON 16:9 videos with VOBSUB and HDMV PGS

**Comment by CastagnaIT** [comment] 2022-03-19 13:25
> kodi matrix is only player that works perfectly

this affermations is wrong, only for your use case will work as you wish (without take in account of the side effects that you do not see with your test subs),
but all others media correctly encoded will be broken, and there is no way to have both ways.

For normal use case the current behaviour is right, and you have already seen with all other video players that are handled in same way.

The only way is to add a new option (more likely on advancedsettings) to exchange between one and the other way

**Comment by kenzoka24** [comment] 2022-03-19 13:28
> > kodi matrix is only player that works perfectly
> 
> this affermations is wrong, only for your use case will work as you wish (without take in account of the side effects that you do not see with your test subs),
> but all others media correctly encoded will be broken, and there is no way to have both ways.
> 
> For normal use case the current behaviour is right, and you have already seen with all other video players that are handled in same way.
> 
> The only way is to add a new option (more likely on advancedsettings) to exchange between one and the other way

that would TOTALLY work for me, but having no option sucks

**Comment by CastagnaIT** [comment] 2022-03-19 13:39
yeah i am not saying that what you ask for is wrong,
but you have opened a bug Issue thinking for a bug where instead is a intended behaviour in Nexus version and then i have explained the reasons behind, nothing prevents us from adding a new setting option somewhere

**Comment by kenzoka24** [comment] 2022-03-19 13:59
> yeah i am not saying that what you ask for is wrong,
> but you have opened a bug Issue thinking for a bug where instead is a intended behaviour in Nexus version and then i have explained the reasons behind, nothing prevents us from adding a new setting option somewhere
> 

so what do I have to do for this?

what's next?

**Comment by CastagnaIT** [comment] 2022-03-19 16:51
nothing just wait, at this point leave this issue opened
in the future if not me someone else dev will take over this task to try add this new setting

**Comment by CastagnaIT** [comment] 2022-03-23 08:23
@kenzoka24 
After investigating i found a third way, to avoid add a new setting,
tested your video sample file and to me works good now

please install one of these test builds and test it with your video files:
Win64bit: http://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20220323-495403da-subtitleimage-x64.exe
Android armv7: http://mirrors.kodi.tv/test-builds/android/arm/kodi-20220323-495403da-subtitleimage-24817-armeabi-v7a.apk
Android arm64: http://mirrors.kodi.tv/test-builds/android/arm64-v8a/kodi-20220323-495403da-subtitleimage-22136-arm64-v8a.apk

let me know

**Comment by kenzoka24** [comment] 2022-03-23 08:47
> @kenzoka24 After investigating i found a third way, to avoid add a new setting, tested your video sample file and to me works good now
> 
> please install one of these test builds and test it with your video files: Win64bit: http://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20220323-495403da-subtitleimage-x64.exe Android armv7: http://mirrors.kodi.tv/test-builds/android/arm/kodi-20220323-495403da-subtitleimage-24817-armeabi-v7a.apk Android arm64: http://mirrors.kodi.tv/test-builds/android/arm64-v8a/kodi-20220323-495403da-subtitleimage-22136-arm64-v8a.apk
> 
> let me know

IT WORKS!

it works without distorting subtitles on my other files too

even on ultra wide monitor


thank you thank you thank you!

**Comment by kenzoka24** [comment] 2022-03-23 18:58
> @kenzoka24 
> After investigating i found a third way, to avoid add a new setting,
> tested your video sample file and to me works good now
> 
> please install one of these test builds and test it with your video files:
> Win64bit: http://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20220323-495403da-subtitleimage-x64.exe
> Android armv7: http://mirrors.kodi.tv/test-builds/android/arm/kodi-20220323-495403da-subtitleimage-24817-armeabi-v7a.apk
> Android arm64: http://mirrors.kodi.tv/test-builds/android/arm64-v8a/kodi-20220323-495403da-subtitleimage-22136-arm64-v8a.apk
> 
> let me know

sample file https://drive.google.com/file/d/1-zVy_wBdoD2G1yODQlfBu-t55xkhkkKK/view?usp=drivesdk

4:3 video file where subtitle is compressed horizontally (PGS)

**Comment by CastagnaIT** [comment] 2022-03-24 08:03
thanks for the sample will be fixed also this case

**Closed** 2022-03-25 18:00 UTC
Labels: Triage: Confirmed, v20 Nexus, Component: Subtitles
