### ISSUE TITLE
Kodi 19.1 Crashes on Startup Loading PVR Icons - Starting PVR channel icon search

### ISSUE THREAD

**Issue by JCalvi** [xbmc/xbmc#20028] opened 2021-08-09 01:54 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

On enabling PVR Channel Icons there are intermittent crashes on startup with Kodi 19.1 Windows.
Have tried many different things until narrowing down, refer steps to reproduce...

Can supply TV.db if it helps. I had cleared all old channel names etc but none of this seemed to help.
Every channel had a matching icon file and all works except for the intermittent crashes.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Should not crash at startup.

## Actual Behavior

Kodi crashes on the "Starting PVR channel icon search" Command

## Possible Fix

Setting Icons manually and removing the icon folder stops the issue.
More specifically - Setting  pvrmenu.iconpath to nothing fixes the issue.   
`<setting id="pvrmenu.iconpath" default="true" />`

Opening the TV38.db and setting bIsUserSetIcon to 1 and `<setting id="pvrmenu.iconpath" default="true" />` allows icons without crashing.

This does not happen with pvr.iptvsimple which loads its icons fine.

Also it happens everytime when a recording is active on my Hauppauge card on startup so suspect it may be related to Kodi PVR, Mediaportal Plugin, Card being active etc.

If no recording is active the crash happens once then not on any restart until the next day or so. Perhaps after a new recording but I cannot be sure.

### To Reproduce

1. Start a recording with my Hauppauge card with 3rd party software (TV Scheduler Pro in my case)
2. Start the MediaPortal TV Service
3. Start Kodi with pvrmenu.iconpath set to a folder with icons, eg: C:\TVIcons (Folder location does not matter).
4. Kodi crashes shortly after starting when attempting to load the icons.

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/epujusaqus.kodi

### Screenshots
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
kodi-19.1-Matrix-x64
&
19.1 (19.1.0) Git:20210716-dcec5f4974
&
19.1 (19.1.0) Git:20210730-8691eb7cb2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by mkreisl** [comment] 2021-08-19 17:46
Something similar has been happening on Raspberry Pi's for years. And with every version it gets worse
but I haven't had the nerve to find out the problem yet. would be good if it's because of that too.

**Comment by JCalvi** [comment] 2021-08-19 23:46
Yes, I am happy to troubleshoot if someone wants to work on it. I can reproduce in my system easily. Happy to load a debug/test version etc. as required.

**Comment by ksooo** [comment] 2021-09-02 20:27
Please provide a log with PVR component logging enabled, thanks.

**Comment by JCalvi** [comment] 2021-09-03 13:27
Done...
https://paste.kodi.tv/xuzokupeqi.kodi
Stacktrace:
Thread 13268 (process 12212)
# 0

**Comment by ksooo** [comment] 2021-09-03 13:43
> Stacktrace:
Thread 13268 (process 12212)

 Can you supply an actual stack trace? That would be great. The thread/process id alone does not help.

**Comment by ksooo** [comment] 2021-09-03 13:46
I really need a stack trace. the log does not contain anything suspicios/obvious, imo. And I'm unable to reproduce myself.

**Comment by JCalvi** [comment] 2021-09-03 14:07
That’s all that’s in the stacktrace, but here is the file.

[kodi_stacktrace-19.1 Git_20210822-34a88a9059-20210903-223751.txt](https://github.com/xbmc/xbmc/files/7106409/kodi_stacktrace-19.1.Git_20210822-34a88a9059-20210903-223751.txt)

**Comment by JCalvi** [comment] 2021-09-03 14:12
Here’s the lot, log, dmp, trace etc if it helps. 
[20210903223758.zip](https://github.com/xbmc/xbmc/files/7106469/20210903223758.zip)

**Comment by ksooo** [comment] 2021-09-03 14:31
No Windows here, cannot read dmp files. You need to run windbg and post the text (file) it generates.

**Comment by ksooo** [comment] 2021-09-03 14:36
https://helpdeskgeek.com/windows-10/how-to-analyze-memory-dump-files-dmp-in-windows-10/

**Comment by JCalvi** [comment] 2021-09-04 01:24
Ok, ran analyze as well:
https://paste.kodi.tv/weruyemere.kodi

**Comment by ksooo** [comment] 2021-09-04 06:07
Thank you very much. Nothing helpful in there, sorry.

**Comment by ksooo** [comment] 2021-09-04 06:08
> Something similar has been happening on Raspberry Pi's for years. And with every version it gets worse
but I haven't had the nerve to find out the problem yet. would be good if it's because of that too.

@mkreisl send me the crashlog, please.

**Comment by ksooo** [comment] 2021-09-04 07:36
@JCalvi here is a test build where I added some more logging. It contains no fix yet. Could you please run that build and post the log? => http://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20210904-15de2e17-pvr-fix-startup-crash-x64.exe

**Comment by JCalvi** [comment] 2021-09-04 07:41
Will do, any log settings I should activate or will it log what it needs irrespective of Kodi log settings?

**Comment by ksooo** [comment] 2021-09-04 07:43
debug and pvr component logging

**Comment by ksooo** [comment] 2021-09-04 07:44
I hope to see that it actually crashes while searching icons.

**Comment by ksooo** [comment] 2021-09-04 07:45
Also, as this is a debug build there are chances to get valuable stack traces.

**Comment by JCalvi** [comment] 2021-09-04 08:08
Ok here you go:
Log: https://paste.kodi.tv/marofofeye.kodi
Stacktrace: [kodi_stacktrace-19.1 Git_20210904-15de2e17bc-20210904-175853.txt](https://github.com/xbmc/xbmc/files/7109433/kodi_stacktrace-19.1.Git_20210904-15de2e17bc-20210904-175853.txt)
Dumpfile: https://paste.kodi.tv/oqabiqizaj.kodi

**Comment by mkreisl** [comment] 2021-09-04 10:01
@ksooo, unfortunately I can't provide a crashlog, but since I installed this hack i haven't had a segfault anymore (Kodi 20)

```diff --git a/xbmc/pvr/PVRManager.cpp b/xbmc/pvr/PVRManager.cpp
index 388e11e..8df0ef9 100644
--- a/xbmc/pvr/PVRManager.cpp
+++ b/xbmc/pvr/PVRManager.cpp
@@ -532,11 +532,11 @@ void CPVRManager::Process()
     {
       {
         CSingleLock lock(m_critSection);
-        m_bFirstStart = false;
+        //m_bFirstStart = false;
       }

       /* start job to search for missing channel icons */
-      TriggerSearchMissingChannelIcons();
+      //TriggerSearchMissingChannelIcons();

       /* try to play channel on startup */
       TriggerPlayChannelOnStartup();
@@ -558,6 +558,13 @@ void CPVRManager::Process()

     if (IsStarted() && !bRestart)
       m_pendingUpdates->WaitForJobs(1000);
+      if (m_bFirstStart)
+      {
+        m_bFirstStart = false;
+        /* start job to search for missing channel icons */
+        CLog::Log(LOGINFO, "PVR Manager: TriggerSearchMissingChannelIcons");
+        TriggerSearchMissingChannelIcons();
+     }
   }   

   CLog::LogFC(LOGDEBUG, LOGPVR, "PVR Manager leaving main loop");
```
Maybe it helps to find the error.
By the way i have 3 PVR addons active: vdr-vnsi, hts and iptvsimple

**Comment by ksooo** [comment] 2021-09-04 10:08
> installed this hack 

 yep, this is definitely not the proper fix. ;-)

**Comment by ksooo** [comment] 2021-09-04 10:10
@JCalvi here is another test build. Please run and supply the log (no dmp needed), even if it does not crash, which could be the case with this build. But this will be not the final fix. We will need some more iterations I'm afraid. => http://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20210904-cc84db56-pvr-fix-startup-crash-x64.exe

**Comment by mkreisl** [comment] 2021-09-04 10:16
I know that myself. but with earlier versions there was no segfault at the first start of Kodi. with further starts it happened as long as I didn't switch off the tvheadend server. Now with Kodi 20 it happened that no matter if tvheadend or vdr was running, there was almost always a segfault. And since I have changed nothing on the server side guaranteed, it must be the Kodi itself.

With the patch it did not occur once more.

**Comment by ksooo** [comment] 2021-09-04 11:06
> I know that myself. 

 Sure. You have seen my smiley, haven't you.

>  Now with Kodi 20 it happened that no matter if ...

 As you can see, open an issie and there are chances that somebody steps up trying to solve the problem. ;-) And now let's stop talking about anything not directly related to fixing this issue. Thanks.

**Comment by ksooo** [comment] 2021-09-04 11:09
> Now with Kodi 20 it happened that no matter if tvheadend or vdr was running, there was almost always a segfault.

 Please post the crashlog! As you are running Kodi on a Raspi this is easy and the stacktraces generated by LInux are relly very helpful. Thanks.

**Comment by JCalvi** [comment] 2021-09-04 13:54
OK, Latest Test build log: https://paste.kodi.tv/catofaxuhu.kodi
Thanks for working on this, off to bed now, happy to try some more tomorrow.

**Comment by ksooo** [comment] 2021-09-04 15:24
So, this build still crashed, right?

**Comment by ksooo** [comment] 2021-09-04 18:02
Okay, next round, with even more logging. Still no idea what goes wrong, no fix intended. => http://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20210904-38e06b2c-pvr-fix-startup-crash-x64.exe

**Comment by JCalvi** [comment] 2021-09-04 22:50
Yes, still crashed, will test 38e06b2c later today.

**Comment by JCalvi** [comment] 2021-09-05 12:45
Ok, restarted at least 30 times and cannot get this build to crash (usually takes 1-2 starts max with others). Not sure if that’s good or a manifestation of “Heisenberg's Uncertainty Principle”, i.e adding the debugging somehow fixed the problem. Hopefully you can work out why the changes fixed the problem.

I might load an older version and just make sure it crashes again later.

**Comment by ksooo** [comment] 2021-09-05 12:55
I need a log, especially if it did not crash.

**Comment by ksooo** [comment] 2021-09-05 12:56
Latest test did not only contain log enhancements.

**Comment by ksooo** [comment] 2021-09-05 13:54
@JCalvi have you seen my comment? I really need a log from a successful run of the latest test build! Preventing the crash is just to get more log output and not the final fix. I need to see what's in the log to find the right fix. Thank you.

**Comment by JCalvi** [comment] 2021-09-05 22:10
No worries, will send this morning, suspect we are in different time zones.

**Comment by JCalvi** [comment] 2021-09-05 23:07
Log from last night: https://paste.kodi.tv/unacilabul.kodi
Log from this morning 1: https://paste.kodi.tv/yukawumozo.kodi

**Comment by ksooo** [comment] 2021-09-06 06:05
> suspect we are in different time zones.

 Definitely. I'm in Germany, you in Australia (the logs indicate).
 
Thanks for the logs. Now know what is wrong and here is a test build with the intended final fix. Please run the build and send logs (even if there is no crash). => http://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20210905-e08d3ffc-pvr-fix-startup-crash-x64.exe

**Comment by JCalvi** [comment] 2021-09-06 11:56
Run 1: https://paste.kodi.tv/ohecujudor.kodi
Run 2: https://paste.kodi.tv/unadojuril.kodi
No crashes

**Comment by ksooo** [comment] 2021-09-06 12:39
Very cool. Then, we have found the root cause and were able to fixed it. Thanks for your support and patience. I will open PRs for master and Matrix to get the fixed integrated in the code lines.

**Comment by JCalvi** [comment] 2021-09-06 12:42
Well done and thanks!

**Closed** 2021-09-07 17:45 UTC
Labels: Component: PVR, Triage: Needed
