### ISSUE TITLE
Download subtitles on file folder

### ISSUE THREAD

**Issue by felipegregercolin** [xbmc/xbmc#15740] opened 2019-03-13 16:36 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:
When I select the subtitle and press botton Enter to make the download, the file of subtitle do not created in the file folder.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: 18.1.0.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment] 2019-03-13 18:57
You failed to provide a debug log (https://kodi.wiki/view/Log_file/Easy) and you also don't fully respect our issue template (how can we reproduce the failure)?

Furthermore the issue looks like addon related, i.e. the subtitles addon you're using to download subtitles fails to download them. This issue will be marked as invalid until you provide the missing information.

**Comment by enen92** [comment] 2019-03-15 14:09
@felipegregercolin This issue will be closed in the next days if the requested information is still missing.

**Closed** 2019-03-16 18:46 UTC
Labels: Ignored rules, Resolution: Won't fix
