### ISSUE TITLE
Kodi crashes with certain type of subtitles

### ISSUE THREAD

**Issue by zelea2** [xbmc/xbmc#16498] opened 2019-08-15 03:53 UTC
# Bug report
### Describe the bug
Kodi crashes when playing a movie with the attached subtitles:
[Le_Brio_2017.en.srt.zip](https://github.com/xbmc/xbmc/files/3504248/Le_Brio_2017.en.srt.zip)

### Your Environment
Used Operating system:
Debian testing
 - Operating system version/name:
$ uname -a
Linux mov 4.16.0-1-amd64 #1 SMP Debian 4.16.5-1 (2018-04-29) x86_
 - Kodi version:
$ dpkg -l | grep kodi
ii  kodi                                 5:18.3-dmo1                      all

**Comment by DaVukovic** [comment] 2019-08-15 04:41
Please follow our issue template. By not providing the necessary info this issue will be closed in 7 days

**Comment by DaVukovic** [comment] 2019-08-15 07:57
Oh, just seem that you are using some patched debian version. So you have to report that issue to those who are maintaining those packages. That's nothing officiallly provided by us. 

Sorry

**Closed by DaVukovic** 2019-08-15 07:57 UTC
Labels: Ignored rules

**Comment by zelea2** [comment] 2019-08-16 19:43
So rather than getting the provided subtitles file and trying it in your latest official kodi version and then saying either "I can't reproduce it" or "yes, it segfaults I confirm the bug" you prefer to just close the issue and ignore it. Fine by me but don't expect me to report any other issues.

**Comment by DaVukovic** [comment] 2019-08-16 21:13
Exactly.

Reporting an issue by using an unofficial Kodi version on the official Kodi issue tracker doesn't make sense at all. Feel free to compile Kodi from source, try again and provide the log if it still fails for you. Our devs are working on this on their free time and are in no way interested in bugs caused by unsupported and patched Kodi version. 

If it still fails with an official Kodi version I'll happily re-open this issue again.
