### ISSUE TITLE
Cannot play video with "&" in its filename from a network location, the protocol is network server directory(http&https)

### ISSUE THREAD

**Issue by gek64** [xbmc/xbmc#20696] opened 2021-12-18 10:58 UTC
### Describe the bug
Can't play video with symbol & in the file name from network location which protocol is the network server directory (https) or server directory (http)

The same video with the symbol & in the file name can be played normally from the network location using the protocols webdav(http&https) and smb

### What caused this bug
For example, using the file name 1&2.mp4, it can be accessed through `http://192.168.1.2:80/dav/1&2.mp4` 
I checked the log and found that kodi will replace the video address `http://192.168.1.2:80/dav/1&2.mp4` to `http://192.168.1.2:80/dav/1&amp%3b2.mp4`, then access the video from this non-existent address

I also found the access log from my web server,It shows that kodi accessed the video from a non-existent address and webserver returns 404 
`192.168.1.3 - - [Time] "GET /dav/1&amp%3b2.mp4 HTTP/1.1" 404 196 "-" "Kodi/19.3 (Windows NT 10.0; Win64; x64) App_Bitness/64 Version/19.3-(19.3.0)-Git:20211024-49a04cd6a7"`

### To Reproduce
1. Setup an webserver(apache2 or nginx) and enable its autoindex
2. Put a file name `1&2.mp4` to webserver's autoindex folder
3. Add network location with protocol server directory (https) or server directory (http)
4. Try to play video `1&2.mp4`

### Debuglog
```log
DEBUG <general>: ------ Window Init (MyVideoNav.xml) ------
INFO <general>: Loading skin file: MyVideoNav.xml, load type: KEEP_IN_MEMORY
DEBUG <general>: CGUIMediaWindow::GetDirectory (http://192.168.1.2:80/dav/)
DEBUG <general>:   ParentPath = []
DEBUG <general>: CurlFile::Open(0xcad08f51a0) http://192.168.1.2:80/dav/
DEBUG <general>: Thread BackgroundLoader start, auto delete: false
DEBUG <general>: CThumbExtractor::DoWork - trying to extract thumb from video file http://192.168.1.2:80/dav/1&amp%3b2.mp4
DEBUG <general>: CFileCache::XFILE::CFileCache::Open - <http://192.168.1.2:80/dav/1&amp%3b2.mp4> opening
DEBUG <general>: CurlFile::Open(0x23840c90ff0) http://192.168.1.2:80/dav/1&amp%3b2.mp4
DEBUG <general>: XCURL::DllLibCurlGlobal::easy_acquire - Created session to http://192.168.1.2
ERROR <general>: CCurlFile::Open failed with code 404 for http://192.168.1.2:80/dav/1&amp%3b2.mp4:
                                                   
ERROR <general>: CFileCache::XFILE::CFileCache::Open - <http://192.168.1.2:80/dav/1&amp%3b2.mp4> failed to open
ERROR <general>: InputStream: Error opening, http://192.168.1.2:80/dav/1&amp%3b2.mp4
DEBUG <general>: Thread BackgroundLoader 4548 terminating
DEBUG <general>: Version Check: Version installed {'major': 19, 'minor': 3, 'revision': '20211024-49a04cd6a7', 'tag': 'stable'}
DEBUG <general>: Version Check: Version available  {'major': '19', 'minor': '3', 'tag': 'stable', 'tagversion': '', 'revision': '20211024-49a04cd6a7', 'extrainfo': 'final', 'addon_support': 'yes'}
DEBUG <general>: Version Check: There is no newer stable available
INFO <general>: CPythonInvoker(0, userdata\addons\service.xbmc.versioncheck\resources\lib\runner.py): script successfully run
DEBUG <general>: CPythonInvoker::onExecutionDone(0, userdata\App\Kodi\portable_data\addons\service.xbmc.versioncheck\resources\lib\runner.py)
INFO <general>: Python interpreter stopped
DEBUG <general>: Thread LanguageInvoker 6724 terminating
DEBUG <general>: CInputManager::ProcessMouse: trying mouse action leftclick
DEBUG <general>: CGUIWindowVideoBase::OnPlayMedia http://192.168.1.2:80/dav/1&amp%3b2.mp4
DEBUG <general>: CCurlFile::GetMimeType - http://192.168.1.2:80/dav/1&amp%3b2.mp4 -> failed
DEBUG <general>: CPlayerCoreFactory::GetPlayers(http://192.168.1.2:80/dav/1&amp%3b2.mp4)
DEBUG <general>: CPlayerSelectionRule::GetPlayers: considering rule: system rules
DEBUG <general>: CPlayerSelectionRule::GetPlayers: matches rule: system rules
DEBUG <general>: CPlayerSelectionRule::GetPlayers: considering rule: mms/udp
DEBUG <general>: CPlayerSelectionRule::GetPlayers: considering rule: lastfm/shout
DEBUG <general>: CPlayerSelectionRule::GetPlayers: considering rule: rtmp
DEBUG <general>: CPlayerSelectionRule::GetPlayers: considering rule: rtsp
DEBUG <general>: CPlayerSelectionRule::GetPlayers: considering rule: streams
DEBUG <general>: CPlayerSelectionRule::GetPlayers: considering rule: dvd
DEBUG <general>: CPlayerSelectionRule::GetPlayers: considering rule: discimage
DEBUG <general>: CPlayerSelectionRule::GetPlayers: considering rule: sdp/asf
DEBUG <general>: CPlayerSelectionRule::GetPlayers: considering rule: nsv
DEBUG <general>: CPlayerSelectionRule::GetPlayers: considering rule: radio
DEBUG <general>: CPlayerCoreFactory::GetPlayers: matched 0 rules with players
DEBUG <general>: CPlayerCoreFactory::GetPlayers: adding videodefaultplayer (VideoPlayer)
DEBUG <general>: CPlayerCoreFactory::GetPlayers: for video=1, audio=0
DEBUG <general>: CPlayerCoreFactory::GetPlayers: for video=1, audio=1
DEBUG <general>: CPlayerCoreFactory::GetPlayers: added 1 players
DEBUG <general>: Radio UECP (RDS) Processor - new CDVDRadioRDSData::CDVDRadioRDSData
INFO <general>: VideoPlayer::OpenFile: http://192.168.1.2:80/dav/1&amp%3b2.mp4
DEBUG <general>: Thread VideoPlayer start, auto delete: false
DEBUG <general>: CApplication::OnPlayBackStarted: CApplication::OnPlayBackStarted
DEBUG <general>: Thread BackgroundLoader start, auto delete: false
INFO <general>: Creating InputStream
DEBUG <general>: CFileCache::XFILE::CFileCache::Open - <http://192.168.1.2:80/dav/1&amp%3b2.mp4> opening
DEBUG <general>: CurlFile::Open(0x23840c90ff0) http://192.168.1.2:80/dav/1&amp%3b2.mp4
ERROR <general>: CCurlFile::Open failed with code 404 for http://192.168.1.2:80/dav/1&amp%3b2.mp4:
                                                   
ERROR <general>: CFileCache::XFILE::CFileCache::Open - <http://192.168.1.2:80/dav/1&amp%3b2.mp4> failed to open
ERROR <general>: CVideoPlayer::OpenInputStream - error opening [http://192.168.1.2:80/dav/1&amp%3b2.mp4]
INFO <general>: CVideoPlayer::OnExit()
DEBUG <general>: Thread VideoPlayer 852 terminating
DEBUG <general>: CVideoGUIInfo::InitCurrentItem(http://192.168.1.2:80/dav/1&amp%3b2.mp4)
DEBUG <general>: Loading settings for http://192.168.1.2:80/dav/1&amp%3b2.mp4
DEBUG <general>: CApplication::OnPlayBackStopped: CApplication::OnPlayBackStopped
DEBUG <general>: Thread BackgroundLoader 1132 terminating
```

### Screenshots 
![example.png](https://s2.loli.net/2021/12/18/yJ3uoThlifrI7P2.png)

### Your Environment
Used Operating system:
 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [x] OSX
 - [x] Windows
 - [ ] Windows UWP

Not tested on OS X, but I think this bug also exists on it.

 - Operating system version/name:Windows 10, ubuntu 21.10, Android 11
 - Kodi version:19.3

**Comment by wagnerch** [comment] 2021-12-19 11:54
FYI, same as #18413, personally I moved on to using NFS.  Also, I believe Unicode support is also broken with http/https.

**Comment by arnova** [comment] 2021-12-19 16:11
This is a known issue. The problem is different http servers (eg. Apache, nginx, iis) have different ways of URL-encoding stuff. This can only be fixed by either URL-encoding all of Kodi's internal paths or detect the http server and handling it differently for the various server types.

**Closed** 2021-12-28 12:47 UTC
