### ISSUE TITLE
Bug, keep device Alive and send low volume noise broken in Kodi 19

### ISSUE THREAD

**Issue by JesseNtaylor** [xbmc/xbmc#21317] opened 2022-04-26 23:07 UTC
BUG KODI 19

Having consulted the forums it seems confirmed that kodi no longer works to "keep audio devices alive" and "send low volume audio"..  my soundbar times out and switches off regardless of both settings being enabled..

Other users users have confirmed Kodi isn't sending low volume audio for them either..

Running latest Kodi 19 .4.0 on Ubuntu 20.04.4 LTS

I have good normal working sound output via HDMI (using pulse audio from my Caicos HDMI audio (Radeon HD 7450), but even setting it directly to alsa or direct to HDMI Caicos changes nothing..

I'm using ARC to send the sound through TV to my Panasonic soundbar, nothing has changed with my hardware or TV soindbar setup since Kodi 17..

I'm no longer able to keep the soundbar alive with the "Keep audio device alive option" on always, and/or ticking "the send low volume sound" option..

 it used to be fine with kodi 18... Now if I leave a video paused or am in the home screen doors more than about 10 minutes, the soundbar goes into standby...

If I turn the soundbar to max volume when paused I can hear no faint whistle, though maybe it's out of my human ears audible hrtz range?

I've checked my hardware setting in Ubuntu and my pulse logs and the Caicos is still alive and not going to sleep..

Both pulse and ALSA seems to be affected.

Please investigate and fix bug?

**Comment by a1rwulf** [comment] 2022-04-28 06:02
>If I turn the soundbar to max volume when paused I can hear no faint whistle, though maybe it's out of my human ears audible hrtz range?

Afaik this is the case, so you shouldn't hear anything even if your setup is on max volume.

**Comment by fritsch** [comment] 2022-04-28 11:42
I shortly tested it yesterday night but in master. Output Silence is never called and pulseaudio goes into idle state right away. Same for ALSA. Something got borked on the way. Will recheck with Matrix over the weekend as there are many Literals changes in master which might or might not have timer influences.

**Comment by JesseNtaylor** [comment] 2022-04-28 11:53
Thank you for confirming, hopefully it's an easy fix..

**Comment by fritsch** [comment] 2022-04-29 18:51
Could you please post a debuglog and I cannot reproduce with latest stable version (Matrix).

I verified the following:
Current master: broken, stops sending silence packages immediately.
Matrix: Working - pulseaudio does not go into standby by itself

20.0.4 is ver old and I can't remember how pulseaudio needed to be set to debugging. On modern Ubuntu it's driven by a user session and you can set it to debug in /etc/pulse/daemon.conf and use journalctl --user -a -u pulseaudio

@lrusak  Could you please have another look at your "Lexical" changes. I have the feeling that the timers inside ActiveAESink don't work anymore as they should. I cannot spot another. You will see the sink-input even disappearing right away (pactl list sink-inputs). It stay active on Matrix and immediately times out on Nexus. I did not follow the development recently, but as the OutputSilence is not called anymore I don't expect the culprit being the generation of silence packages but rather a timer not working anymore.

**Comment by JesseNtaylor** [comment] 2022-04-30 16:04
[pulseverbose.log](https://github.com/xbmc/xbmc/files/8597281/pulseverbose.log)

Pulselog verbose as requested.  I hope this is right thing, if not someone might have to walk me though getting the right one..

**Comment by fritsch** [comment] 2022-04-30 16:15
Please post the kodi.log - the one you posted now sadly does not show kodi running / opening a stream ...
The pulse.log only makes sense when kodi was actually running in parallel and the IDLE behaviour was visible - as then pulse log will tell that the stream was marked idle with a timeout. Non of this is visible in your log.

**Comment by JesseNtaylor** [comment] 2022-04-30 16:32
Ok I'll do a full log later

**Comment by JesseNtaylor** [comment] 2022-04-30 22:14
[pulseverbose.log](https://github.com/xbmc/xbmc/files/8597890/pulseverbose.log)
[kodi.log](https://github.com/xbmc/xbmc/files/8597891/kodi.log)

ok heres a NEW pulseaudio veerbose log while running kodi and playing a stream, i also first toggled on the settings for keep alive and send low volume first if that helps.

also my kodi.log as requested , if this is not what you need, someone wil have to walk me through the exaact steps i should take?

**Comment by JesseNtaylor** [comment] 2022-04-30 22:42
[kodi.log](https://github.com/xbmc/xbmc/files/8597930/kodi.log)
[pulseverbose.log](https://github.com/xbmc/xbmc/files/8597932/pulseverbose.log)

Ok new pulseaudio debug log and kodi.log

did this while setting the keep audio alive and the send low volume off and back on, and then running a kodi stream (trailer) pausing it, playing it, stopping it..

If this still doesnt show what you need, someone will have to walk me through step by step what is required//

**Comment by JesseNtaylor** [comment] 2022-04-30 22:45
[pulseverbose.log](https://github.com/xbmc/xbmc/files/8597936/pulseverbose.log)

seemed upload bugged first time

**Comment by fritsch** [comment] 2022-05-01 06:50
For that you said, you changed the settings, everything looks good. In kodi.log there is only one time of sink reconfigure (when you swapped the keep alive setting) and in pulse I see that there appears a corresponding idle, which is also okay.

So - in order to properly see what is happening, please do:
Open kodi, set "keep alive to always" and also enable "send low volume noise" (this setting was exactly done cause modern AVRs smelled the zeroes and turned off never the less).

Now - scroll through the menus, with menu sound enabled, so that you actually hear the menu clicks - now wait 15 seconds without doing anything. Now play a menu sound again by moving up / down.

Afterwards please post the pulseverbose.log and the kodi.log, we should see IDLE transition in this break and we should see sink reconfigure right away when you press the very latest time up / down after the break.

**Comment by fritsch** [comment] 2022-05-01 07:03
I can show you what I mean. Here with "keep alive off" in kodi 19.4:
Mai 01 08:55:53 L380 pulseaudio[249384]: Drain acknowledged of 'kodi audio stream'
Mai 01 08:55:53 L380 pulseaudio[249384]: Requesting rewind due to corking
Mai 01 08:55:53 L380 pulseaudio[249384]: Requested to rewind 0 bytes.
Mai 01 08:55:53 L380 pulseaudio[249384]: alsa_output.pci-0000_00_1f.3.analog-stereo: state: RUNNING -> IDLE
Mai 01 08:55:53 L380 pulseaudio[249384]: Sink alsa_output.pci-0000_00_1f.3.analog-stereo becomes idle, timeout in 5 seconds.

Keep alive on:
Mai 01 08:59:29 L380 pulseaudio[249384]: alsa_output.pci-0000_00_1f.3.analog-stereo: state: IDLE -> RUNNING
Mai 01 08:59:29 L380 pulseaudio[249384]: Requesting rewind due to end of underrun.
Mai 01 08:59:29 L380 pulseaudio[249384]: Requested to rewind 8820 bytes.
Mai 01 08:59:29 L380 pulseaudio[249384]: Limited to 8468 bytes.
Mai 01 08:59:29 L380 pulseaudio[249384]: before: 2117
Mai 01 08:59:29 L380 pulseaudio[249384]: after: 2117
Mai 01 08:59:29 L380 pulseaudio[249384]: Rewound 8468 bytes.
Mai 01 08:59:29 L380 pulseaudio[249384]: Processing rewind...
Mai 01 08:59:29 L380 pulseaudio[249384]: latency = 2383
Mai 01 08:59:29 L380 pulseaudio[249384]: Have to rewind 8468 bytes on render memblockq.
Mai 01 08:59:29 L380 pulseaudio[249384]: Processing rewind...
Mai 01 08:59:39 L380 pulseaudio[249384]: Synced.

If you see the time stamps, you see that above kodi drains immediately and PA becomes idle, while below "nothing" happens for 10 seconds as you see. Means: keep alive works as it should.

For v20 nightlies it drains it always, no matter the setting - but this I cannot reproduce (as you see with 19.4).

**Comment by JesseNtaylor** [comment] 2022-05-01 17:26
[kodi.log](https://github.com/xbmc/xbmc/files/8599394/kodi.log)
[pulseverbose.log](https://github.com/xbmc/xbmc/files/8599395/pulseverbose.log)

Ok as requesed, start  logging, start kodi, set audio alway and low volume ON, then move in menu, stop moving, wait 15 secs, start moving in menu, hear sounds, stop logging.

hopefuly this is as needed!!

**Comment by fritsch** [comment] 2022-05-01 18:06
In fact it looks good. kodi's stream survives all the time until your pulse gets stopped.
The non-working situation would look like this:

Mai 01 19:59:57 L380 pulseaudio[249384]: Hmm, no streams around, trying to vacuum.
Mai 01 19:59:57 L380 pulseaudio[249384]: Freeing input 109 "kodi audio stream"
Mai 01 19:59:57 L380 pulseaudio[249384]: Freed 109 "KodiSink"
Mai 01 19:59:57 L380 pulseaudio[249384]: Connection died.

This you can see when you turn off "noise / always" setting.

Two things come to my mind:
Could it be that your AMD HDMI audio has issues with: suspend-on-idle setting?
https://wiki.archlinux.org/title/PulseAudio/Troubleshooting
You can try to unload that suspend-on-idle. Does that change anything?

I don't expect that to change anything as kodi's stream stays active.
Did your device receive a FW update? So that it ignores the noise?

If you can build kodi from source, you could change the "volume" in GenerateNoise to crossverify.

**Comment by fritsch** [comment] 2022-05-01 18:09
```
diff --git a/xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAESink.cpp b/xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAESink.cpp
index 1739357b6a..fb8c051eb7 100644
--- a/xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAESink.cpp
+++ b/xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAESink.cpp
@@ -1117,7 +1117,7 @@ void CActiveAESink::GenerateNoise()
       }
       while(R1 == 0.0f);
 
-      noise[i] = sqrt( -2.0f * log( R1 )) * cos( 2.0f * PI * R2 ) * 0.00001f;
+      noise[i] = sqrt( -2.0f * log( R1 )) * cos( 2.0f * PI * R2 ) * 0.01f;
     }
   }
 ```

**Comment by JesseNtaylor** [comment] 2022-05-01 21:34
Oops I had commented out the suspend-on-idle in the pulse default. pa, but I didn't realise it was doubled up in the system.pa as well... BOTH are now commented..

Hopefully that'll solve my issue..

At least maybe we caught the issue with Kodi 20 early, if nothing else.. 

Many thanks for all your help .

**Comment by bacon-cheeseburger** [comment] 2022-05-05 00:43
I'm having this problem too. Using Linux, alsa only, and Kodi compiled from git. For example, if I start Kodi and let the gui idle for about 2 seconds, my AVR loses audio (the little channel icons turn off). If I press a button the remote, I can see in the log that the audio device is re-initialized. I won't hear any sounds until I press a button again. But then if I idle the gui for a second or two, the AVR loses audio again. It certainly seems like the `keep audio device alive` is broken. Has there been any progress on this? I can create a debug log if it would help.

**Comment by fritsch** [comment] 2022-05-05 10:46
Yes. Git master is broken. If you can bisect be my guest. I sadly don't have time in foreseeable future.

Stable version works for me. Master only sends noice right before a menu click, which we want to for warm up and then not anymore at all, which is the bug.

Seems to me the idle, silence timer got broken, sink directly unloads again, no matter the alive menu setting.

**Comment by bacon-cheeseburger** [comment] 2022-05-05 16:06
I'd gladly bisect but is there a specific dir I can bisect to help it along? xbmx/cores/AudioEngine maybe?

**Comment by fritsch** [comment] 2022-05-05 17:40
Jep, if you want, you can do that. Even ActiveAESink would most likely be enough.

**Comment by bacon-cheeseburger** [comment] 2022-05-06 17:10
> Jep, if you want, you can do that. Even ActiveAESink would most likely be enough.
> 
> Edit: ./xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAESink.cpp <- this one.

I bisected that, had to skip a couple times due to compile errors. Results are:

There are only 'skip'ped commits left to test.
The first bad commit could be any of:
07d579e643503ad7ead066b6abda6ba4b7bb8636
d880bc46165f43e47961720ae2f00c94e56e2da3
ed51cd2245a87236ec603a2faf0530d34ebddedd
We cannot bisect more!

Please let me know if I can help further.

**Comment by fritsch** [comment] 2022-05-06 18:28
Hehe - thanks much. You just landed on the assumption I posted in my very first reply here. I already pinged the author of all the three patches you found.

**Comment by dreamcat4** [comment] 2022-06-05 14:33
+1 am also affected

pretty bad over here since it then triggers these other bug:

https://github.com/xbmc/xbmc/issues/21213
https://github.com/xbmc/xbmc/issues/20870

**Comment by thexai** [comment] 2023-01-11 10:54
Unfortunately is not fixed yet in ARM64 at least (Shield) with keep alive setting = "Always"

It would be nice if someone else could confirm it on other ARM or ARM64 devices/platforms

**Comment by bacon-cheeseburger** [comment] 2023-01-12 14:10
@thexai I don't think it was ever fixed. I grabbed a clean master (Kodi 21, Alpha 1) the other day and the problem was still there.

**Closed** 2023-01-14 10:12 UTC
Labels: Component: Audio, Triage: Confirmed, v20 Nexus
