### ISSUE TITLE
Kodi crashes silently on Android if you put 50+ different playlists into userdata/playlists

### ISSUE THREAD

**Issue by steftirol** [xbmc/xbmc#20680] opened 2021-12-14 22:06 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:
Kodi closes himself after starting within 10 seconds, I reproduced the error with a clean installation without any database just putting playlists into the playlists folder. Using Windows Kodi doesn't crash with 50+ playlists.
I'm using an Amazon Fire TV 4K MAX Stick but Error was reported over the last 2 years on different Android Devices:
https://www.reddit.com/r/kodi/comments/gfg58m/shield_smart_playlists_make_kodi_crash_but_not_on/

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
Kodi should run and not close himself suddenly

## Actual Behavior
Kodi crashes about 10 Seconds after Start
In Crashlog following Exception occurs: java.lang.IllegalStateException: Apps may not schedule more than 100 distinct jobs

## Possible Fix
Put less than 50 playlists into Kodi Playlist Folders when using Kodi within Android

### To Reproduce
1. Install latest nightly from ARM folder on an Android Device like the Amazon Fire TV Stick 4K Max and start it once
2. Close Kodi and put 50 or more different Playlists into a Playlist folder like userdata/playlists/video with adbLink
3. Format of the Playlist is like
https://pastebin.com/xSQEehhh
Notice that the playlist name tag is different in all of your playlist files!
Or use my playlists from 
https://www.file2send.eu/de/download/AXJundiXWTUZ40TprK8LBVZsm5TkEyTem4k1Bhm3tYxyVp0pDS4RqfeApXLxOsJf

4. Restart the whole Stick (Disconnecting from Power) before entering Kodi
5. Kodi crashes within seconds

### Debuglog
The debuglog can be found here:
https://pastebin.com/wJAM5y2Z
crashlog
https://pastebin.com/uvQ9ndee

### Screenshots 
Here are some links or screenshots to help explain the problem:
-

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:
I have a playlist for each folder to sort my movies on my own categories. I have about 70 playlists.

### Your Environment
Used Operating system:
 - [X] Android 
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Amazon AFTKA with Android 9.0.0 API level 28, kernel: Linux ARM 32-bit version 4.14.87+
 - Kodi version: Kodi (19.3 (19.3.0) Git:20211211-0c84de629a). Platform: Android ARM 32-bit

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by matthuisman** [comment] 2021-12-15 20:05
looks like for every channel, 2x jobs are queued to sync programs for that channel:
https://github.com/xbmc/xbmc/blob/master/tools/android/packaging/xbmc/src/channels/SyncChannelJobService.java.in#L201
1) seems to run immediately
2) seems to run every 1800000ms (30 mins)

im not sure why we it is not a single job that loops the channels and updates the programs (instead of one for every channel)

**Comment by enen92** [comment] 2021-12-15 22:19
Nice find. All those channels will be disabled by default unless the user has explicitly enabled them in the ATV interface so ideally it should only run for enabled channels. Unfortunately as far as I could see TvContractChannels do not provide any way to check if the channel is enabled.

IMHO since Kodi only runs this while open (i.e. unlike mrmc that implements part of it as an android service) and, as a result, the user is not using the leanback interface your proposed solution seems a good first approach to mitigate the issue.

**Comment by matthuisman** [comment] 2021-12-15 22:31
is there anyway we can check if Kodi has been setup as a channels provider?
If not - all of this could be skipped

**Comment by enen92** [comment] 2021-12-15 22:59
This is only used if running Android TV, see: https://github.com/xbmc/xbmc/blob/a80d1293b0579bbed7dd7d20304ba34a20519f78/tools/android/packaging/xbmc/src/Main.java.in#L138. "android.software.leanback" is one of the ways to check for Android TV. 

As for the feature itself it refers to Android Tv channels, those items you see on the android tv leanback interface as recommendations. See first post here for a bird's eye view:
https://forum.kodi.tv/showthread.php?tid=332589

By default playlists in Kodi are defined as android TV channels (so a row in the android tv leanback interface). Every item in that row (channel) is called a program (corresponds to a movie, episode, etc with art and other stuff)

**Comment by matthuisman** [comment] 2021-12-15 23:12
right, because there is another thing called Android Live Channels which is just live channels.
so was getting confused with that :)

**Comment by matthuisman** [comment] 2021-12-15 23:48
so it seems one of the JobScheduler is to respond to a trigger of URI change...

I'm guessing this is so if the playlist is changed inside Kodi, the channel in android gets updated with the new content?

Not sure how we could keep this behaviour without having a trigger for every playlist.
maybe user just has to wait 30mins after any changes?
Unless we can make Kodi trigger the update somehow when changes are made

**Comment by kiboy6** [comment] 2023-04-15 07:47
Hi,

Just discovered this issue to be the cause of the mystifying Kodi crashes I had been experiencing both on Matrix and Nexus on Android.
Any hope of a solution in the future? (other than keeping to under 50 playlists) 

Cheers!

**Comment by kiboy6** [comment] 2023-04-16 11:11
Thanks! - great to see this is being fixed :)

I don't suppose there is any temporary xml edit I could do at my end that would apply this fix to Matrix / Nexus builds?

**Comment by joseluismarti** [comment] 2023-04-18 10:23
So far it has been fixed in v21, can you test this version ([v21 pre-release builds](https://kodi.tv/download/android/)) and confirm that it works correctly?

**Closed** 2023-04-18 19:10 UTC
