### ISSUE TITLE
[JSON-RPC] Player.GetProperties failed when other player is active

### ISSUE THREAD

**Issue by regseb** [xbmc/xbmc#17897] opened 2020-05-19 16:22 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

In JSON-RPC API, the method [`Player.GetProperties`](https://kodi.wiki/view/JSON-RPC_API/v10#Player.GetProperties) returns *Failed to execute method* when a other player is active.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should return properties of player asked.
```json
{"id":1,"jsonrpc":"2.0","result":{"position":-1}}
```

## Actual Behavior

Kodi returns an error.
```json
{"error":{"code":-32100,"message":"Failed to execute method."},"id":1,"jsonrpc":"2.0"}
```

## Possible Fix

Remove the condition that verifies that the asked player is equal to the active playlist (in [`CPlayerOperations::GetPlayer()`](https://github.com/xbmc/xbmc/blob/654c1471a62deeec8a6c6b485f7bb2e1969924ea/xbmc/interfaces/json-rpc/PlayerOperations.cpp#L1262)).

```cpp
PlayerType CPlayerOperations::GetPlayer(const CVariant &player)
{
  int iPlayer = (int)player.asInteger();
  PlayerType playerID;

  switch (iPlayer)
  {
    // ...
  }

  return playerID;
}
```

### To Reproduce

1. In Kodi, *Allow remote control via HTTP* (*Settings* / *Services* / *Control*).
2. Stop all player.
3. Execute (by changing the IP address) : `curl -d '{ "jsonrpc": "2.0", "method": "Player.GetProperties", "params": { "playerid": 1, "properties": ["position"] }, "id": 1 }' -H 'Content-type: application/json' -X POST 127.0.0.1:8080/jsonrpc`
4. Kodi returns `"position":-1`.
5. Play a music (with audio player).
6. Re-execute `curl`.
7. Kodi returns an error `"Failed to execute method`.

### Debuglog

The debuglog can be found here:

Kodi log nothing.

### Screenshots 
Here are some links or screenshots to help explain the problem:

NA

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

NA

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: OSMC 2020.03-1
 - Kodi version: 18.6

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment] 2020-05-20 05:11
>Kodi should return properties of player asked.

That's correct. But you have to ask the correct player. Hence, you have to change the playerID to "2". Try it with:

`curl -d '{ "jsonrpc": "2.0", "method": "Player.GetProperties", "params": { "playerid": 2, "properties": ["position"] }, "id": 1 }' -H 'Content-type: application/json' -X POST 192.168.1.2:8080/jsonrpc`

And you will get the correct and expected result.

So, this is not a bug, this is by design.

**Comment by regseb** [comment] 2020-05-20 06:11
@DaVukovic I don't want the properties of the current player, I want the properties of the video player.

The `Player.GetProperties` method should have the same behavior:

- when it is called for player A and no player is active;
- when it is called for player A and player B is active.

I updated the issue by adding a possibel fix: *Remove the condition that verifies that the asked player is equal to the active playlist (in [`CPlayerOperations::GetPlayer()`](https://github.com/xbmc/xbmc/blob/master/xbmc/interfaces/json-rpc/PlayerOperations.cpp#L1262)).*

**Comment by DaVukovic** [comment] 2020-05-20 06:15
Re-opened that one as I might have misunderstood it. 

Anyway, could you please open a PR so that devs could discuss your suggestion. I highly guess it won't be discussed in here.

**Comment by malard** [comment] 2024-01-28 13:30
I'm closing this as a by design. If you want to Get the properties of a non active player then maintain this state locally and not expect kodi to do it for you. Because the state is essentially 'undefined' when not active and cannot be accurately relied on when not active. If you have lost state or dont know the state when querying a non active player the caller should assume the state is 'undefined'

**Closed by malard** 2024-01-28 13:30 UTC
Labels: v19 Matrix, Component: JSON-RPC

**Comment by regseb** [comment] 2024-01-29 08:15
> If you want to Get the properties of a non active player then maintain this state locally and not expect kodi to do it for you.

Kodi has information about an non active player:

- Open _Movies_ list.
- Add a movie to playlist with _Queue item_ in context menu.
- Open _Options_ sidebar and _Go to playlist_.
- Open _Options_ sidebar, active _Shuffle_ and set _Repeat_ to _All_.
- _Clear_ playlist.
- Return to home page.
- Open _Movies_ list.
- Add a movie to playlist with _Queue item_ in context menu.
- Open _Options_ sidebar and _Go to playlist_.
- Open _Options_ sidebar: _Shuffle_ is still active and _Repeat_ is still at _All_.

It's the JSON-RPC API that doesn't provide a route to get this information.

**Comment by malard** [comment] 2024-01-29 08:57
As I say, you get/can get this state information when the player starts, why do you need it while the player is not active?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by regseb** [comment] 2024-01-29 09:52
I'm developing the [Cast Kodi](https://chromewebstore.google.com/detail/cast-kodi/gojlijimdlgjlliggedhakpefimkedmb) extension for browsers. It provides a remote control to interact with Kodi. I'm trying to integrate the features (including _Shuffle_ and _Repeat_) of Kodi into the remote control.

- Non active player:
  ![inactive](https://github.com/xbmc/xbmc/assets/1262990/0ce2808e-ec7d-4491-a482-bc17f3fa4e8a)
- Active player:
  ![active](https://github.com/xbmc/xbmc/assets/1262990/60e81ac9-54f9-4c8d-8635-71180d37b87a)
- Active player with _Shuffle_ and _Repeat_:
  ![active_shuffle](https://github.com/xbmc/xbmc/assets/1262990/a220eabf-911d-4082-9686-1a5acfce60e5)

The user can open the remote while the video player isn't active. In that case, I need to retrieve the status in Kodi to display the icon in white or blue. And I need the routes to change _Shuffle_ and _Repeat_.

I can't store the information in my extension, because the user can change the _Shuffle_ and _Repeat_ directly in Kodi when the player isn't active.
