### ISSUE TITLE
Kodi crashing when accessing library

### ISSUE THREAD

**Issue by vaLentiin0** [xbmc/xbmc#15488] opened 2019-02-11 09:42 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

With the release of the stable 18.0 I have decided to make the leap (partially forced by an auto update). Unfortunately I am now running into various issues that I haven't seen before.

First off what i've done so far:
1. Reset everything: no luck
2. Clean install using the 64bit installer (Kodi v18.0 "Leia") with various addons: no luck
3. Another clean install without any addons other than rar support and archive support.

My setup:
1. Custom HTPC running Kodi V18.0 64 Bit on Windows 10 pro 64 bit, version 10.0.17763.
2. Linux built custom fileserver, using SMB to share the various disks across the network. No user/password restrictions.

The issues I'm running into:
1. I am able to mount my SMB shares (4 folders) and content scraping works at first, however as soon as I want to update my library again Kodi crashes.
2. For the files already scraped as soon as I want to watch any media it says that the file is no longer available. This only applies to my tv series, as for movies: see point 3.
3. Whenever I open my movie library, Kodi crashes instantly. I am not even able to browse or head back to the files overview.

Hereby the log which does state some errors at the end ("XFILE::CDirectory::GetDirectory - Error getting"). https://paste.kodi.tv/alayitosod.kodi

After some tips on the Kodi forum i started testing with/without addons.

First disabled the archive addon, while keeping rar archive active. This resulted in the same crashes.

After that I disabled the  rar archive addon and enabled the regular archive addon. Surprisingly it now let me populate the library and it is showing the correct meta data without crashing. However, whenever I now want to directly play a file it says the file is no longer available. Surprisingly though, it does let me play the file if I head into the file menu and select play instead of directly playing it.

Link to Kodi forum thread: 
https://forum.kodi.tv/showthread.php?tid=340347

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I expected Kodi to populate my library in full, allowing me to browse through my movies and series, even though they are still in archives on my server. Obviously I expect Kodi to play them whenever needed.

## Actual Behavior

Kodi only populates half the library and when heading back to the library it often crashes. If it doesn't, selecting a movie to play from the library results in an error saying "the file is no longer available".

## Possible Fix

Not entirely sure, but accessing the movies through the file manager and playing from there does work.

### To Reproduce

1. Launch Kodi.
2. Populate the library
3. Head to the library.

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/alayitosod.kodi

If needed I can create a new log per test with the addons enabled/disabled.

### Screenshots 
Here are some links or screenshots to help explain the problem:

NA

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Addons used:
- Archive support
- Rar archive support

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

- Operating system version/name: Windows 10 pro 64 bit, version 10.0.17763
- Kodi version: Kodi V18.0 64 Bit (stable version)
- Server specs: https://tweakers.net/gallery/228544/inventaris/?inv_id=789948
- HTPC specs: https://tweakers.net/gallery/228544/inventaris/?inv_id=1502625

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ender1598** [comment] 2019-02-22 20:57
This looks very similar to a problem I submitted almost a month ago. I also have files on shares and in an archive the same way you describe. Never had problems in previous version.
[https://github.com/xbmc/xbmc/issues/15349](https://github.com/xbmc/xbmc/issues/15349)

**Comment by holde** [comment] 2019-03-10 12:11
I have the same problem :(

**Comment by ender1598** [comment] 2019-04-16 19:40
Have you tried the latest version of Kodi? I attached logs in my ticket and I'm getting the same behavior. Since you're running Windows 10 I think that my Windows 7 isn't the cause of the problem.

**Comment by noybman** [comment] 2019-05-04 18:24
I have the same, or nearly simular issue. I'm on Windows 8.1. I cannot open the files in the file browser anymore than I can do them from the library. It crashes as soon as I open them. There are two VFS addons, I've used both exclusive or'd:
https://forum.kodi.tv/showthread.php?tid=329320&page=5

Posts 44 and 45

**Comment by vaLentiin0** [comment] 2019-05-08 09:14
@ender1598 I have tried the latest version but still had issues.

Weird but true: after a few days of trying all seems to now work correctly without any issues (although my library is now duplicated). I am going to dive into this issue over the weekend to see if I can resolve it without getting back to the initial issue.

**Comment by wiske80** [comment] 2019-07-12 18:27
same problem here. Win10 Kodi leia 18.3 , cannot scrape into library.. Enables VFS and rar support addon, but kodi crashes... 

anyone?

**Comment by GenericITMonkey** [comment] 2019-08-05 18:45
I had the exact same issue but went in and disabled Archive support and SFTP support and left RAR support enabled. 


This fixed the issue and I am able to read from multi-part .rar files again.

**Comment by jockef3000** [comment] 2019-08-18 18:29
I only experience the problem when I use a MariaDB database.
If I only use RAR support and a local database then I have no problem.

**Comment by KarellenX** [comment] 2019-08-28 10:36
More reports here... https://forum.kodi.tv/showthread.php?tid=346703

**Comment by arnova** [comment] 2019-08-29 06:08
What really would help here if someone could provide a stacktrace.

**Comment by ender1598** [comment] 2019-08-29 12:48
> What really would help here if someone could provide a stacktrace.

I have a stacktrace in my submission which is pretty similar.
https://github.com/xbmc/xbmc/issues/15349

**Comment by arnova** [comment] 2019-08-30 14:49
> > What really would help here if someone could provide a stacktrace.
> 
> I have a stacktrace in my submission which is pretty similar.
> #15349

I have no idea. Without a stacktrace no can tell whether it's the same issue, could be a totally different one.

**Comment by AlwinEsch** [comment] 2020-07-24 21:00
Can confirmed that this fault is fixed?

**Comment by noybman** [comment] 2020-07-25 01:08
Yes, as long as you are using the latest archive supported plugin and only one of the two, it is fixed with the latest current release.



On July 24, 2020 5:01:06 PM EDT, Alwin Esch <notifications@github.com> wrote:
>Can confirmed that this fault is fixed?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/xbmc/xbmc/issues/15488#issuecomment-663732229

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Closed** 2022-08-24 15:31 UTC
Labels: Issue Cleanup: Obsolete
