### ISSUE TITLE
Kodi 19 Beta 1 crashes when some video streams end or are manually stopped

### ISSUE THREAD

**Issue by berkhornet** [xbmc/xbmc#18831] opened 2020-11-21 14:14 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

When playing some videos (for example from YouTube, as in this bug report), Kodi crashes. This happens when the video reaches the end or is manually stopped (for example by the 'X' keyboard shortcut. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should return to the previous menu when playback terminates

## Actual Behavior

Kodi crashes

## Possible Fix

Not known

### To Reproduce

1.  Start Youtube addon
2.  Select a video to play
3.

### Debuglog

The debuglog can be found here:

https://1drv.ms/u/s!AnvH8xK_L6PjjN4pM-0jfWcZMf_PHQ?e=Ud6kk6

I suspect the related error is 2020-11-21 14:00:23.735 T:5912    ERROR <general>: Got MSGQ_ABORT or MSGO_IS_ERROR return true, at line 6100 in the debug log

I checked, but no other logs were created. 

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [X ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 20H2
 - Kodi version: Kodi 19 Beta 1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaveTBlake** [comment] 2020-11-21 15:46
A brief look at the log there are multiple errors raised by an addon or script - probably skin.helper.service ListItemMonitor but I'm not sure. On thread 5840, and it is possible that these eventually cause the cash.

` ERROR : Got MSGQ_ABORT or MSGO_IS_ERROR` is common and generally insignificant. 

The streaming addon itself plugin.video.youtube (6.8.7+matrix.1) seems to be error free, but maybe someone more familiar should check that.  

> When playing some videos (for example from YouTube, as in this bug report), Kodi crashes

@berkhornet are the crashes always when using plugins to play streams e.g. youtube? Does playback of local media have any issues?

**Comment by berkhornet** [comment] 2020-11-21 17:18
Thanks for response. Local playback and Live TV are fine. It's only when using addons like Youtube and Netflix the problem happens. I've done some more investigation. Firstly, I copied my Kodi installation to another Windows PC (a laptop rather than HTPC where the errors occur). The errors didn't happen. Then, I changed the skin on the HTPC and the errors didn't occur there also. So now I'm more confused than ever!

**Comment by DaveTBlake** [comment] 2020-11-21 17:32
My fellow team members suspect that you are encountering a known error where there is an attempt, probably triggered by addons,  to display a second busy dialog when one is already being displayed. This is an issue introduced in v18 while making other necessary improvements that we have not been able to resolve yet. It is also difficult to reproduce consistently.

Your successful experience with changing skin does support this hypothesis. I am guessing (no proof whatsoever) that the old skin setup was using skin helper service that was erroring and tried to display a busy dialog when returning to the video nav screen after playback stopped, but the nav screen also could display a busy dialog and so crash. I repeat just a guess, but I hope makes the behaviour a little less mysterious.

**Comment by berkhornet** [comment] 2020-11-21 18:47
Thanks for your response. I investigated further and disabled Skin Helper Service. I thought for a while this had stopped the error happening but after a while the error did reoccur. As you say, its difficult to reproduce consistently

**Comment by berkhornet** [comment] 2020-11-21 22:08
I've now done a clean install of Kodi 19 Beta 1, and Youtube. Kodi still crashes. I've posted a new debug log at: https://1drv.ms/u/s!AnvH8xK_L6PjjPIP4Au42iWS-8Y8Kg?e=GhDcr1

Also, a crash log at https://1drv.ms/u/s!AnvH8xK_L6PjjPIQC5EgnC-W5kgxfw?e=f2dxHS and a stack trace at https://1drv.ms/t/s!AnvH8xK_L6PjjPIOzyhvTlBfESbbuA?e=skxdt3

Hope this helps

**Comment by rikardfries** [comment] 2020-11-22 09:35
Hi!
I am also on windows 10 feature 2004.
On latest daily matrix 2020-Nov-21 03:38.
with latest Inputstream Adaptive 2.6.6
Kodi crashing instantly every time I start anything that runs IA.
Sample addons include retrospect, netflix, hgo et.c.
Running Estuary.
Could this be the same error..
Should I supply a debug log?

**Comment by berkhornet** [comment] 2020-11-22 10:20
Hi. i don’t think this is the same error. My error only happens when a video I’m watching ends or if I stop it. It plays ok.

Regards Mick

________________________________

**Comment by DaveTBlake** [comment] 2020-11-22 10:41
@rikardfries you are experiencing a different issue - inputstream.adaptive and changes to API in master got slightly out of step. This will be fixed in the next nightly (along with newest inputstream.adaptive version), dated Nov 23

**Comment by DaveTBlake** [comment] 2020-11-22 10:47
Thanks for the new logs @berkhornet I'll try to get someone else to take a look. 
@anxdpanic could youtube addon be causing this?

**Comment by berkhornet** [comment] 2020-11-22 11:13
@DaveTBlake I have had the problem with at least one other video addon (Netflix). But for the latest logs I stripped Kodi down to the bare minimum to recreate (and hopefully isolate) the problem using Youtube. Thanks for your help.

**Comment by rikardfries** [comment] 2020-11-22 14:10
> @rikardfries you are experiencing a different issue - inputstream.adaptive and changes to API in master got slightly out of step. This will be fixed in the next nightly (along with newest inputstream.adaptive version), dated Nov 23

ok, 
@DaveTBlake Thank you for info. 
@berkhornet   sorry for interrupting your case.

**Comment by quixote23** [comment] 2021-02-22 04:59
I'm having this problem with the officially released Kodi 19.0 Matrix and I can consistently replicate it - it's happening every time a video ends naturally or if I press Stop in the final 5-10%. 

I'm using PlexKodiConnect, which I suspect might be related? Also using the Amber skin although I've tried with a few different skins (Aeon Tajo, Rapier) and the problem persists.

Debugging Kodi Log:
http://bit.ly/3sfLTrP

Other Details:
Windows 10.0.19042
Audio Output: WASAPI Default
Amber skin 3 2.4.13
PlexKodiConnect 3.0.11

If the logs indicate that this is a PKC problem please let me know so I can take this issue over to them. Otherwise if this is a competing add-on notification can anyone identity the problem add-on? I don't have the Skin Helper Service installed.

**Closed** 2022-08-24 15:37 UTC
Labels: v19 Matrix, Triage: Needed, Issue Cleanup: Obsolete
