### ISSUE TITLE
Transition from photo to video in Photo album gives black screen

### ISSUE THREAD

**Issue by brjhaverkamp** [xbmc/xbmc#16912] opened 2019-11-14 10:30 UTC
#16509 6851  Bug report
### Describe the bug
Here is a clear and concise description of what the problem is:
Transitioning with right button through a photo album in Kodi results in wrong playback of videos. The screen is black while audio plays correctly.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
When viewing photos in the kodi photo/picture album, I browse forward with the right button on my tv remote control.  There are also short videos taken by my phone  in the album. The transition from a photo to a photo goes well. The transition from a photo to a video results in a black screen, while the audio plays fine. Stopping the video is still possible. When starting a video by clicking on it (so not using the right button, but clicking play on the video) works OK. The video plays correctly in that case.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
When transitioning from a photo to a video should result in the video playing correctly, just like when clicking on it directly.

## Actual Behavior
Actual behavior when transitioning from a photo to a video is a black screen with audio.

## Possible Fix
I assume there is a difference in initialization of the video between using the right button during browsing the album and using the play button when in the album. It might be a simple onliner fix.

### To Reproduce
1 Have a picture/photo album available in Kodi with a mix of photos and videos (e.g. taken by your smartphone.
2 Click on the first photo to view it full screen
3 Use the right button to transition through the photos till you hit a video.
4 The video does not show, but only the sound is audible.

### Debuglog

The debuglog can be found here:

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [x ] Linux
 - [ ] OSX
 - [ x] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
OSMC
 - Kodi version:
18.3

Happy to provide more info, debug logs, feedback on resolutions, etc. when required.

Bert Haverkamp

**Comment by DaVukovic** [comment] 2019-11-14 12:09
duplicate of: #16288

**Closed by DaVukovic** 2019-11-14 12:09 UTC
Labels: Ignored rules, Triage: Needed

**Comment by brjhaverkamp** [comment] 2019-11-14 12:26
Hi DaVukovic,

That was quick:-) But please give me 24 hours or so to fix the report. I think the only leftover deviation from the template is the logfile. Although I don't think it is relevant in this case, I will add it tonight.

Could you please reopen it again?

Bert

**Comment by brjhaverkamp** [comment] 2019-11-14 12:28
Apologies, it is indeed a duplicate.

**Comment by DaVukovic** [comment] 2019-11-14 12:42
I would have left it open for about 7 days, if it wouldn't have been a duplicate ;)

And there's nothing to apologize. It's just a note that this issue already exists and we don't need to have multiple tickets for the same problem. So all fine ;)

Generally I wouldn't even call this an issue. I would call it "done by design" because photos and video are using a different kind of player inside Kodi. I guess (and that's really only a guess) the same will happen for a mixed playlist which has audio files (mp3) and video files in it. Except you are configuring the default player for audio is the videoplayer. Then it should work as Kodi doesn't need to switch the player then. 

See: https://kodi.wiki/view/Advancedsettings.xml#audio

**Comment by brjhaverkamp** [comment] 2019-11-14 13:37
Hi,

Well, the apologies were for not reading. I missed that you marked it a duplicate, as I (too proactively) assumed it was due to not following the template:-)

Well, it is definitely an issue. whether to call it a bug or "by design" you can indeed debate. But for simplicity I call it a bug. From a user perspective, everyone these days makes pictures and short video clips of their children, dogs and cats. If you browse through your photos in Kodi, the currnet behavior is that when you transition from a photo to a video, it is a black screen with soundtrack. That is clearly not the intended behavior. 
But  with your explanation, I see that the solution might be a bit more tricky than I assumed. I thought it would be an initialization issue for the video player. But if there is an underlying framework where it is hard to switch players on the fly, that might need a more elaborate fix. (And I am also just guessing here).

Most photo management tools (e.g. digikam) can work with a mix of photos and videos, so it would be great if in kodi we could fix this as well. Although I noticed the picture add-on doesn't have a lot of development. So here is for hoping! :-)

Thanks again for your feedback.

Bert

**Comment by FernetMenta** [comment] 2019-11-14 14:00
> Generally I wouldn't even call this an issue. I would call it "done by design" because photos and video are using a different kind of player inside Kodi.

Is is totally wrong. Picture viewer can play videos fine and this works on platforms like X11.  Other platforms may have implementation issues.

**Comment by DaVukovic** [comment] 2019-11-14 14:10
@FernetMenta ok, wasn't aware. Thanks for explaining.
