### ISSUE TITLE
Kodi switches off HDMI display after 10mins playing audio. Works for movies / nothing playing

### ISSUE THREAD

**Issue by matbon108** [xbmc/xbmc#17149] opened 2020-01-07 09:07 UTC
<!--- Read the following link before you create a new problem report: https://kodi.wiki/view/HOW-
## Bug report
As Screen goes off
2020-01-07 10:47:10.151 T:140208653719296   DEBUG: Sink removed
2020-01-07 10:47:10.151 T:140208653719296   DEBUG: Sink changed
2020-01-07 10:47:10.151 T:140208670504704   DEBUG: CActiveAE - device change event
2020-01-07 10:47:10.371 T:140208670504704   DEBUG: PulseAudio: Context authorizing
2020-01-07 10:47:10.372 T:140208670504704   DEBUG: PulseAudio: Context setting name
2020-01-07 10:47:10.372 T:140208670504704   DEBUG: PulseAudio: Context ready
2020-01-07 10:47:10.372 T:140208670504704 WARNING: Pulseaudio module module-allow-passthrough not loaded - opening PT devices might fail
2020-01-07 10:47:10.373 T:140208653719296   DEBUG: PulseAudio: Found Family 17h (Models 10h-1fh) HD Audio Controller Analog Stereo with devicestring alsa_output.pci-0000_38_00.6.analog-stereo
2020-01-07 10:47:10.373 T:140208670504704  NOTICE: Found 1 Lists of Devices
2020-01-07 10:47:10.373 T:140208670504704  NOTICE: Enumerated PULSE devices:
2020-01-07 10:47:10.373 T:140208670504704  NOTICE:     Device 1
2020-01-07 10:47:10.373 T:140208670504704  NOTICE:         m_deviceName      : Default
2020-01-07 10:47:10.373 T:140208670504704  NOTICE:         m_displayName     : Default
2020-01-07 10:47:10.373 T:140208670504704  NOTICE:         m_displayNameExtra: Default Output Device (PULSEAUDIO)
2020-01-07 10:47:10.373 T:140208670504704  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
2020-01-07 10:47:10.373 T:140208670504704  NOTICE:         m_channels        : FL, FR
2020-01-07 10:47:10.373 T:140208670504704  NOTICE:         m_sampleRates     : 5512,8000,11025,16000,22050,32000,44100,48000,64000,88200,96000,176400,192000,384000
2020-01-07 10:47:10.373 T:140208670504704  NOTICE:         m_dataFormats     : AE_FMT_U8,AE_FMT_S16NE,AE_FMT_S24NE3,AE_FMT_S24NE4,AE_FMT_S32NE,AE_FMT_FLOAT
2020-01-07 10:47:10.373 T:140208670504704  NOTICE:         m_streamTypes     : No passthrough capabilities
2020-01-07 10:47:10.373 T:140208670504704  NOTICE:     Device 2
2020-01-07 10:47:10.373 T:140208670504704  NOTICE:         m_deviceName      : alsa_output.pci-0000_38_00.6.analog-stereo
2020-01-07 10:47:10.373 T:140208670504704  NOTICE:         m_displayName     : Family 17h (Models 10h-1fh) HD Audio Controller Analog Stereo
2020-01-07 10:47:10.373 T:140208670504704  NOTICE:         m_displayNameExtra: Speakers (PULSEAUDIO)
2020-01-07 10:47:10.373 T:140208670504704  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
2020-01-07 10:47:10.373 T:140208670504704  NOTICE:         m_channels        : FL, FR
2020-01-07 10:47:10.373 T:140208670504704  NOTICE:         m_sampleRates     : 5512,8000,11025,16000,22050,32000,44100,48000,64000,88200,96000,176400,192000,384000
2020-01-07 10:47:10.373 T:140208670504704  NOTICE:         m_dataFormats     : AE_FMT_U8,AE_FMT_S16NE,AE_FMT_S24NE3,AE_FMT_S24NE4,AE_FMT_S32NE,AE_FMT_FLOAT
2020-01-07 10:47:10.373 T:140208670504704  NOTICE:         m_streamTypes     : No passthrough capabilities
2020-01-07 10:47:10.373 T:140208662112000    INFO: CActiveAESink::OpenSink - initialize sink
2020-01-07 10:47:10.373 T:140208662112000   DEBUG: CActiveAESink::OpenSink - trying to open device PULSE:alsa_output.pci-0000_38_00.1.hdmi-stereo-extra1
2020-01-07 10:47:10.373 T:140208662112000   DEBUG: PulseAudio: Context authorizing
2020-01-07 10:47:10.374 T:140208662112000   DEBUG: PulseAudio: Context setting name
2020-01-07 10:47:10.374 T:140208662112000   DEBUG: PulseAudio: Context ready
2020-01-07 10:47:10.374 T:140208662112000   ERROR: PulseAudio: Sink alsa_output.pci-0000_38_00.1.hdmi-stereo-extra1 not found
2020-01-07 10:47:10.374 T:140208662112000   DEBUG: CActiveAESink::OpenSink - trying to open device PULSE:Default
2020-01-07 10:47:10.375 T:140208662112000   DEBUG: PulseAudio: Context authorizing
2020-01-07 10:47:10.375 T:140208662112000   DEBUG: PulseAudio: Context setting name
2020-01-07 10:47:10.375 T:140208662112000   DEBUG: PulseAudio: Context ready
2020-01-07 10:47:10.376 T:140208662112000   DEBUG: PulseAudio: Stream ready
2020-01-07 10:47:10.376 T:140208662112000  NOTICE: PulseAudio: Opened device Default in pcm mode with Buffersize 200 ms
2020-01-07 10:47:10.376 T:140208662112000   DEBUG: CActiveAESink::OpenSink - PULSE Initialized:
2020-01-07 10:47:10.376 T:140208653719296   DEBUG: Sink changed
2020-01-07 10:47:10.376 T:140208662112000   DEBUG:   Output Device : Default
2020-01-07 10:47:10.376 T:140208662112000   DEBUG:   Sample Rate   : 44100
2020-01-07 10:47:10.376 T:140208662112000   DEBUG:   Sample Format : AE_FMT_FLOAT
2020-01-07 10:47:10.376 T:140208662112000   DEBUG:   Channel Count : 2
2020-01-07 10:47:10.376 T:140208662112000   DEBUG:   Channel Layout: FL, FR
2020-01-07 10:47:10.376 T:140208662112000   DEBUG:   Frames        : 2205
2020-01-07 10:47:10.376 T:140208662112000   DEBUG:   Frame Size    : 8
2020-01-07 10:47:10.376 T:140208653719296   DEBUG: Sink changed
2020-01-07 10:47:10.376 T:140208670504704   DEBUG: CActiveAE::ClearDiscardedBuffers - buffer pool deleted

As Screen switches on
2020-01-07 10:49:03.635 T:140208746711744   DEBUG: Previous line repeats 2 times.
2020-01-07 10:49:03.635 T:140208746711744   DEBUG: NotifyXRREvent - notify display reset event
2020-01-07 10:49:03.640 T:140208746711744   ERROR: WinSystemX11::RefreshWindow - failed to query xrandr
2020-01-07 10:49:03.640 T:140208670504704   DEBUG: CActiveAE - device change event
2020-01-07 10:49:04.015 T:140208670504704   DEBUG: PulseAudio: Context authorizing
2020-01-07 10:49:04.016 T:140208670504704   DEBUG: PulseAudio: Context setting name
2020-01-07 10:49:04.016 T:140208670504704   DEBUG: PulseAudio: Context ready
2020-01-07 10:49:04.017 T:140208670504704 WARNING: Pulseaudio module module-allow-passthrough not loaded - opening PT devices might fail
2020-01-07 10:49:04.017 T:140208653719296   DEBUG: PulseAudio: Found Family 17h (Models 10h-1fh) HD Audio Controller Analog Stereo with devicestring alsa_output.pci-0000_38_00.6.analog-stereo
2020-01-07 10:49:04.017 T:140208670504704  NOTICE: Found 1 Lists of Devices
2020-01-07 10:49:04.017 T:140208670504704  NOTICE: Enumerated PULSE devices:
2020-01-07 10:49:04.017 T:140208670504704  NOTICE:     Device 1
2020-01-07 10:49:04.017 T:140208670504704  NOTICE:         m_deviceName      : Default
2020-01-07 10:49:04.017 T:140208670504704  NOTICE:         m_displayName     : Default
2020-01-07 10:49:04.017 T:140208670504704  NOTICE:         m_displayNameExtra: Default Output Device (PULSEAUDIO)
2020-01-07 10:49:04.017 T:140208670504704  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
2020-01-07 10:49:04.017 T:140208670504704  NOTICE:         m_channels        : FL, FR
2020-01-07 10:49:04.017 T:140208670504704  NOTICE:         m_sampleRates     : 5512,8000,11025,16000,22050,32000,44100,48000,64000,88200,96000,176400,192000,384000
2020-01-07 10:49:04.017 T:140208670504704  NOTICE:         m_dataFormats     : AE_FMT_U8,AE_FMT_S16NE,AE_FMT_S24NE3,AE_FMT_S24NE4,AE_FMT_S32NE,AE_FMT_FLOAT
2020-01-07 10:49:04.017 T:140208670504704  NOTICE:         m_streamTypes     : No passthrough capabilities
2020-01-07 10:49:04.017 T:140208670504704  NOTICE:     Device 2
2020-01-07 10:49:04.017 T:140208670504704  NOTICE:         m_deviceName      : alsa_output.pci-0000_38_00.6.analog-stereo
2020-01-07 10:49:04.017 T:140208670504704  NOTICE:         m_displayName     : Family 17h (Models 10h-1fh) HD Audio Controller Analog Stereo
2020-01-07 10:49:04.017 T:140208670504704  NOTICE:         m_displayNameExtra: Speakers (PULSEAUDIO)
2020-01-07 10:49:04.017 T:140208670504704  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
2020-01-07 10:49:04.017 T:140208670504704  NOTICE:         m_channels        : FL, FR
2020-01-07 10:49:04.017 T:140208670504704  NOTICE:         m_sampleRates     : 5512,8000,11025,16000,22050,32000,44100,48000,64000,88200,96000,176400,192000,384000
2020-01-07 10:49:04.017 T:140208670504704  NOTICE:         m_dataFormats     : AE_FMT_U8,AE_FMT_S16NE,AE_FMT_S24NE3,AE_FMT_S24NE4,AE_FMT_S32NE,AE_FMT_FLOAT
2020-01-07 10:49:04.017 T:140208670504704  NOTICE:         m_streamTypes     : No passthrough capabilities
2020-01-07 10:49:04.017 T:140208662112000    INFO: CActiveAESink::OpenSink - initialize sink
2020-01-07 10:49:04.017 T:140208662112000   DEBUG: CActiveAESink::OpenSink - trying to open device PULSE:alsa_output.pci-0000_38_00.1.hdmi-stereo-extra1
[kodi.log](https://github.com/xbmc/xbmc/files/4029703/kodi.log)
2020-01-07 10:49:04.018 T:140208662112000   DEBUG: PulseAudio: Context authorizing
2020-01-07 10:49:04.018 T:140208662112000   DEBUG: PulseAudio: Context setting name
2020-01-07 10:49:04.018 T:140208662112000   DEBUG: PulseAudio: Context ready
2020-01-07 10:49:04.018 T:140208662112000   ERROR: PulseAudio: Sink alsa_output.pci-0000_38_00.1.hdmi-stereo-extra1 not found
2020-01-07 10:49:04.019 T:140208662112000   DEBUG: CActiveAESink::OpenSink - trying to open device PULSE:Default
2020-01-07 10:49:04.019 T:140208662112000   DEBUG: PulseAudio: Context authorizing
2020-01-07 10:49:04.019 T:140208662112000   DEBUG: PulseAudio: Context setting name
2020-01-07 10:49:04.020 T:140208662112000   DEBUG: PulseAudio: Context ready
2020-01-07 10:49:04.020 T:140208662112000   DEBUG: PulseAudio: Stream ready
2020-01-07 10:49:04.020 T:140208662112000  NOTICE: PulseAudio: Opened device Default in pcm mode with Buffersize 200 ms
2020-01-07 10:49:04.021 T:140208662112000   DEBUG: CActiveAESink::OpenSink - PULSE Initialized:
2020-01-07 10:49:04.021 T:140208662112000   DEBUG:   Output Device : Default
2020-01-07 10:49:04.021 T:140208662112000   DEBUG:   Sample Rate   : 44100
2020-01-07 10:49:04.021 T:140208662112000   DEBUG:   Sample Format : AE_FMT_FLOAT
2020-01-07 10:49:04.021 T:140208662112000   DEBUG:   Channel Count : 2
2020-01-07 10:49:04.021 T:140208662112000   DEBUG:   Channel Layout: FL, FR
2020-01-07 10:49:04.021 T:140208662112000   DEBUG:   Frames        : 2205
2020-01-07 10:49:04.021 T:140208662112000   DEBUG:   Frame Size    : 8
2020-01-07 10:49:04.021 T:140208670504704   DEBUG: CActiveAE::ClearDiscardedBuffers - buffer pool deleted
2020-01-07 10:49:04.021 T:140208653719296   DEBUG: Previous line repeats 2 times.
2020-01-07 10:49:04.021 T:140208653719296   DEBUG: Sink changed
2020-01-07 10:49:05.634 T:140208746711744   DEBUG: NotifyXRREvent - notify display reset event
2020-01-07 10:49:05.651 T:140208746711744    INFO: Available videomodes (xrandr):
2020-01-07 10:49:05.651 T:140208746711744    INFO: Output 'HDMI-A-0' has 35 modes
2020-01-07 10:49:05.651 T:140208746711744    INFO: ID:0x58 Name:1920x1080 Refresh:60.000000 Width:1920 Height:1080
2020-01-07 10:49:05.651 T:140208746711744    INFO: Pixel Ratio: 0.997875
2020-01-07 10:49:05.651 T:140208746711744    INFO: ID:0x59 Name:1920x1080 Refresh:50.000000 Width:1920 Height:1080
2020-01-07 10:49:05.651 T:140208746711744    INFO: Pixel Ratio: 0.997875
2020-01-07 10:49:05.651 T:140208746711744    INFO: ID:0x5a Name:1920x1080 Refresh:59.940201 Width:1920 Height:1080
2020-01-07 10:49:05.651 T:140208746711744    INFO: Pixel Ratio: 0.997875
2020-01-07 10:49:05.651 T:140208746711744    INFO: ID:0x5b Name:1920x1080 Refresh:30.000000 Width:1920 Height:1080
2020-01-07 10:49:05.651 T:140208746711744    INFO: Pixel Ratio: 0.997875
2020-01-07 10:49:05.651 T:140208746711744    INFO: ID:0x5c Name:1920x1080 Refresh:25.000000 Width:1920 Height:1080
2020-01-07 10:49:05.651 T:140208746711744    INFO: Pixel Ratio: 0.997875
2020-01-07 10:49:05.651 T:140208746711744    INFO: ID:0x5d Name:1920x1080 Refresh:24.000000 Width:1920 Height:1080
2020-01-07 10:49:05.651 T:140208746711744    INFO: Pixel Ratio: 0.997875
2020-01-07 10:49:05.651 T:140208746711744    INFO: ID:0x5e Name:1920x1080 Refresh:29.970100 Width:1920 Height:1080
2020-01-07 10:49:05.651 T:140208746711744    INFO: Pixel Ratio: 0.997875
2020-01-07 10:49:05.651 T:140208746711744    INFO: ID:0x5f Name:1920x1080 Refresh:23.976080 Width:1920 Height:1080
2020-01-07 10:49:05.651 T:140208746711744    INFO: Pixel Ratio: 0.997875
2020-01-07 10:49:05.651 T:140208746711744    INFO: ID:0x60 Name:1680x1050 Refresh:59.883251 Width:1680 Height:1050
2020-01-07 10:49:05.651 T:140208746711744    INFO: Pixel Ratio: 1.108750
2020-01-07 10:49:05.651 T:140208746711744    INFO: ID:0x61 Name:1600x900 Refresh:60.000000 Width:1600 Height:900
2020-01-07 10:49:05.651 T:140208746711744    INFO: Pixel Ratio: 0.997875
2020-01-07 10:49:05.651 T:140208746711744    INFO: ID:0x62 Name:1280x1024 Refresh:75.024673 Width:1280 Height:1024
2020-01-07 10:49:05.651 T:140208746711744    INFO: Pixel Ratio: 1.419200
2020-01-07 10:49:05.651 T:140208746711744    INFO: ID:0x63 Name:1280x1024 Refresh:60.019741 Width:1280 Height:1024
2020-01-07 10:49:05.651 T:140208746711744    INFO: Pixel Ratio: 1.419200
2020-01-07 10:49:05.651 T:140208746711744    INFO: ID:0x64 Name:1440x900 Refresh:59.901459 Width:1440 Height:900
2020-01-07 10:49:05.651 T:140208746711744    INFO: Pixel Ratio: 1.108750
2020-01-07 10:49:05.651 T:140208746711744    INFO: ID:0x65 Name:1366x768 Refresh:59.789539 Width:1366 Height:768
2020-01-07 10:49:05.651 T:140208746711744    INFO: Pixel Ratio: 0.997388
2020-01-07 10:49:05.651 T:140208746711744    INFO: ID:0x66 Name:1280x800 Refresh:59.909550 Width:1280 Height:800
2020-01-07 10:49:05.651 T:140208746711744    INFO: Pixel Ratio: 1.108750
2020-01-07 10:49:05.651 T:140208746711744    INFO: ID:0x67 Name:1152x864 Refresh:75.000000 Width:1152 Height:864
2020-01-07 10:49:05.651 T:140208746711744    INFO: Pixel Ratio: 1.330500
2020-01-07 10:49:05.651 T:140208746711744    INFO: ID:0x68 Name:1280x720 Refresh:60.000000 Width:1280 Height:720
2020-01-07 10:49:05.651 T:140208746711744    INFO: Pixel Ratio: 0.997875
2020-01-07 10:49:05.651 T:140208746711744    INFO: ID:0x69 Name:1280x720 Refresh:50.000000 Width:1280 Height:720
2020-01-07 10:49:05.651 T:140208746711744    INFO: Pixel Ratio: 0.997875
2020-01-07 10:49:05.651 T:140208746711744    INFO: ID:0x6a Name:1280x720 Refresh:59.940201 Width:1280 Height:720
2020-01-07 10:49:05.651 T:140208746711744    INFO: Pixel Ratio: 0.997875
2020-01-07 10:49:05.651 T:140208746711744    INFO: ID:0x6b Name:1024x768 Refresh:75.028580 Width:1024 Height:768
2020-01-07 10:49:05.651 T:140208746711744    INFO: Pixel Ratio: 1.330500
2020-01-07 10:49:05.651 T:140208746711744    INFO: ID:0x6c Name:1024x768 Refresh:70.069359 Width:1024 Height:768
2020-01-07 10:49:05.651 T:140208746711744    INFO: Pixel Ratio: 1.330500
2020-01-07 10:49:05.651 T:140208746711744    INFO: ID:0x6d Name:1024x768 Refresh:60.003841 Width:1024 Height:768
2020-01-07 10:49:05.651 T:140208746711744    INFO: Pixel Ratio: 1.330500
2020-01-07 10:49:05.652 T:140208746711744    INFO: ID:0x6e Name:832x624 Refresh:74.551270 Width:832 Height:624
2020-01-07 10:49:05.652 T:140208746711744    INFO: Pixel Ratio: 1.330500
2020-01-07 10:49:05.652 T:140208746711744    INFO: ID:0x6f Name:800x600 Refresh:72.187569 Width:800 Height:600
2020-01-07 10:49:05.652 T:140208746711744    INFO: Pixel Ratio: 1.330500
2020-01-07 10:49:05.652 T:140208746711744    INFO: ID:0x70 Name:800x600 Refresh:75.000000 Width:800 Height:600
2020-01-07 10:49:05.652 T:140208746711744    INFO: Pixel Ratio: 1.330500
2020-01-07 10:49:05.652 T:140208746711744    INFO: ID:0x71 Name:800x600 Refresh:60.316540 Width:800 Height:600
2020-01-07 10:49:05.652 T:140208746711744    INFO: Pixel Ratio: 1.330500
2020-01-07 10:49:05.652 T:140208746711744    INFO: ID:0x72 Name:720x576 Refresh:50.000000 Width:720 Height:576
2020-01-07 10:49:05.652 T:140208746711744    INFO: Pixel Ratio: 1.419200
2020-01-07 10:49:05.652 T:140208746711744    INFO: ID:0x73 Name:720x480 Refresh:60.000000 Width:720 Height:480
2020-01-07 10:49:05.652 T:140208746711744    INFO: Pixel Ratio: 1.182667
2020-01-07 10:49:05.652 T:140208746711744    INFO: ID:0x74 Name:720x480 Refresh:59.940060 Width:720 Height:480
2020-01-07 10:49:05.652 T:140208746711744    INFO: Pixel Ratio: 1.182667
2020-01-07 10:49:05.652 T:140208746711744    INFO: ID:0x75 Name:640x480 Refresh:75.000000 Width:640 Height:480
2020-01-07 10:49:05.652 T:140208746711744    INFO: Pixel Ratio: 1.330500
2020-01-07 10:49:05.652 T:140208746711744    INFO: ID:0x76 Name:640x480 Refresh:72.808800 Width:640 Height:480
2020-01-07 10:49:05.652 T:140208746711744    INFO: Pixel Ratio: 1.330500
2020-01-07 10:49:05.652 T:140208746711744    INFO: ID:0x77 Name:640x480 Refresh:66.666672 Width:640 Height:480
2020-01-07 10:49:05.652 T:140208746711744    INFO: Pixel Ratio: 1.330500
2020-01-07 10:49:05.652 T:140208746711744    INFO: ID:0x78 Name:640x480 Refresh:60.000000 Width:640 Height:480
2020-01-07 10:49:05.652 T:140208746711744    INFO: Pixel Ratio: 1.330500
2020-01-07 10:49:05.652 T:140208746711744    INFO: ID:0x79 Name:640x480 Refresh:59.940479 Width:640 Height:480
2020-01-07 10:49:05.652 T:140208746711744    INFO: Pixel Ratio: 1.330500
2020-01-07 10:49:05.652 T:140208746711744    INFO: ID:0x7a Name:720x400 Refresh:70.081657 Width:720 Height:400
2020-01-07 10:49:05.652 T:140208746711744    INFO: Pixel Ratio: 0.985556
2020-01-07 10:49:05.652 T:140208746711744   DEBUG: RecreateWindow - current output: HDMI-A-0, mode: 0x58, refresh: 60.000
2020-01-07 10:49:05.652 T:140208746711744   DEBUG: OnLostDevice - notify display change event
2020-01-07 10:49:05.728 T:140208746711744   DEBUG: CWinSystemX11::RefreshEGLContext: refreshing context
2020-01-07 10:49:05.729 T:140208653719296   DEBUG: Sink changed
2020-01-07 10:49:05.729 T:140208653719296   DEBUG: Sink appeared
2020-01-07 10:49:05.729 T:140208670504704   DEBUG: CActiveAE - device change event
2020-01-07 10:49:05.731 T:140208746711744    INFO: GL: Maximum texture width: 16384
2020-01-07 10:49:05.733 T:140208746711744    INFO: GL: Enabling VSYNC
2020-01-07 10:49:06.083 T:140208670504704   DEBUG: PulseAudio: Context authorizing
2020-01-07 10:49:06.084 T:140208670504704   DEBUG: PulseAudio: Context setting name
2020-01-07 10:49:06.084 T:140208670504704   DEBUG: PulseAudio: Context ready
2020-01-07 10:49:06.084 T:140208670504704 WARNING: Pulseaudio module module-allow-passthrough not loaded - opening PT devices might fail
2020-01-07 10:49:06.085 T:140208653719296   DEBUG: PulseAudio: Found Family 17h (Models 10h-1fh) HD Audio Controller Analog Stereo with devicestring alsa_output.pci-0000_38_00.6.analog-stereo
2020-01-07 10:49:06.085 T:140208653719296   DEBUG: PulseAudio: Found Raven/Raven2/Fenghuang HDMI/DP Audio Controller Digital Stereo (HDMI 2) with devicestring alsa_output.pci-0000_38_00.1.hdmi-stereo-extra1
2020-01-07 10:49:06.085 T:140208670504704  NOTICE: Found 1 Lists of Devices
2020-01-07 10:49:06.085 T:140208670504704  NOTICE: Enumerated PULSE devices:
2020-01-07 10:49:06.085 T:140208670504704  NOTICE:     Device 1
2020-01-07 10:49:06.085 T:140208670504704  NOTICE:         m_deviceName      : Default
2020-01-07 10:49:06.085 T:140208670504704  NOTICE:         m_displayName     : Default
2020-01-07 10:49:06.085 T:140208670504704  NOTICE:         m_displayNameExtra: Default Output Device (PULSEAUDIO)
2020-01-07 10:49:06.085 T:140208670504704  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
2020-01-07 10:49:06.085 T:140208670504704  NOTICE:         m_channels        : FL, FR
2020-01-07 10:49:06.085 T:140208670504704  NOTICE:         m_sampleRates     : 5512,8000,11025,16000,22050,32000,44100,48000,64000,88200,96000,176400,192000,384000
2020-01-07 10:49:06.085 T:140208670504704  NOTICE:         m_dataFormats     : AE_FMT_U8,AE_FMT_S16NE,AE_FMT_S24NE3,AE_FMT_S24NE4,AE_FMT_S32NE,AE_FMT_FLOAT
2020-01-07 10:49:06.085 T:140208670504704  NOTICE:         m_streamTypes     : No passthrough capabilities
2020-01-07 10:49:06.085 T:140208670504704  NOTICE:     Device 2
2020-01-07 10:49:06.085 T:140208670504704  NOTICE:         m_deviceName      : alsa_output.pci-0000_38_00.6.analog-stereo
2020-01-07 10:49:06.085 T:140208670504704  NOTICE:         m_displayName     : Family 17h (Models 10h-1fh) HD Audio Controller Analog Stereo
2020-01-07 10:49:06.085 T:140208670504704  NOTICE:         m_displayNameExtra: Speakers (PULSEAUDIO)
2020-01-07 10:49:06.085 T:140208670504704  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
2020-01-07 10:49:06.085 T:140208670504704  NOTICE:         m_channels        : FL, FR
2020-01-07 10:49:06.085 T:140208670504704  NOTICE:         m_sampleRates     : 5512,8000,11025,16000,22050,32000,44100,48000,64000,88200,96000,176400,192000,384000
2020-01-07 10:49:06.085 T:140208670504704  NOTICE:         m_dataFormats     : AE_FMT_U8,AE_FMT_S16NE,AE_FMT_S24NE3,AE_FMT_S24NE4,AE_FMT_S32NE,AE_FMT_FLOAT
2020-01-07 10:49:06.085 T:140208670504704  NOTICE:         m_streamTypes     : No passthrough capabilities
2020-01-07 10:49:06.085 T:140208670504704  NOTICE:     Device 3
2020-01-07 10:49:06.085 T:140208670504704  NOTICE:         m_deviceName      : alsa_output.pci-0000_38_00.1.hdmi-stereo-extra1
2020-01-07 10:49:06.085 T:140208670504704  NOTICE:         m_displayName     : Raven/Raven2/Fenghuang HDMI/DP Audio Controller Digital Stereo (HDMI 2)
2020-01-07 10:49:06.085 T:140208670504704  NOTICE:         m_displayNameExtra: HDMI / DisplayPort 2 (PULSEAUDIO)
2020-01-07 10:49:06.085 T:140208670504704  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
2020-01-07 10:49:06.085 T:140208670504704  NOTICE:         m_channels        : FL, FR
2020-01-07 10:49:06.085 T:140208670504704  NOTICE:         m_sampleRates     : 5512,8000,11025,16000,22050,32000,44100,48000,64000,88200,96000,176400,192000,384000
2020-01-07 10:49:06.085 T:140208670504704  NOTICE:         m_dataFormats     : AE_FMT_U8,AE_FMT_S16NE,AE_FMT_S24NE3,AE_FMT_S24NE4,AE_FMT_S32NE,AE_FMT_FLOAT
2020-01-07 10:49:06.085 T:140208670504704  NOTICE:         m_streamTypes     : No passthrough capabilities
2020-01-07 10:49:06.085 T:140208662112000    INFO: CActiveAESink::OpenSink - initialize sink
2020-01-07 10:49:06.085 T:140208662112000   DEBUG: CActiveAESink::OpenSink - trying to open device PULSE:alsa_output.pci-0000_38_00.1.hdmi-stereo-extra1
2020-01-07 10:49:06.085 T:140208662112000   DEBUG: PulseAudio: Context authorizing
2020-01-07 10:49:06.086 T:140208662112000   DEBUG: PulseAudio: Context setting name
2020-01-07 10:49:06.086 T:140208662112000   DEBUG: PulseAudio: Context ready
2020-01-07 10:49:06.086 T:140208662112000   DEBUG: PulseAudio: Stream ready
2020-01-07 10:49:06.087 T:140208662112000  NOTICE: PulseAudio: Opened device alsa_output.pci-0000_38_00.1.hdmi-stereo-extra1 in pcm mode with Buffersize 150 ms
2020-01-07 10:49:06.087 T:140208662112000   DEBUG: CActiveAESink::OpenSink - PULSE Initialized:
2020-01-07 10:49:06.087 T:140208662112000   DEBUG:   Output Device : Raven/Raven2/Fenghuang HDMI/DP Audio Controller Digital Stereo (HDMI 2)
2020-01-07 10:49:06.087 T:140208653719296   DEBUG: Sink changed
2020-01-07 10:49:06.087 T:140208662112000   DEBUG:   Sample Rate   : 44100
2020-01-07 10:49:06.087 T:140208662112000   DEBUG:   Sample Format : AE_FMT_FLOAT
2020-01-07 10:49:06.087 T:140208662112000   DEBUG:   Channel Count : 2
2020-01-07 10:49:06.087 T:140208662112000   DEBUG:   Channel Layout: FL, FR
2020-01-07 10:49:06.087 T:140208662112000   DEBUG:   Frames        : 2205
2020-01-07 10:49:06.087 T:140208662112000   DEBUG:   Frame Size    : 8
2020-01-07 10:49:06.087 T:140208670504704   DEBUG: CActiveAE::ClearDiscardedBuffers - buffer pool deleted
2020-01-07 10:49:06.087 T:140208653719296   DEBUG: Previous line repeats 2 times.
2020-01-07 10:49:06.087 T:140208653719296   DEBUG: Sink changed
### Describe the bug
When playing any music after 10 mins Kodi cuts the HDMI signal. The TV shows "No input". There are no screen savers and power saving is disabled. Only happens with Kodi 18. Using Kodi 17 no issues, upgraded to 18 and has this issue. Clean install of Linux and 18 does the same.

Even if I load and loop pictures while playing music it will switch off after 10 mins. Leaving nothing playing on the Kodi menu the screen stays on indefinitely so this proves no screen saver etc.

I consider this a bug as it does it on both a clean install and existing installation and not on Kodi 17. Movies, Pictures etc all play past 10 mins without switching off the HDMI signal. I have attached the debug log and in this message just prior to screen switch off and when I thereafter manually switch the TV off and on again.

## Expected Behavior
I expect the audio to play until end of song / playlist without switching off HDMI.

## Actual Behavior
Switches off HDMI signal after 10 mins.
## Possible Fix
Something happening with the audio sink?
### To Reproduce
1. Play music
2. Wait 10mins
3. Music stops as TV loses signal
### Your Environment
Used Operating system:

 - Operating system version/name: Manjaro - 4.19.91-1-MANJARO
- CPU: AMD Ryzen 3 2200G (4) @ 3.500GHz
- GPU: AMD ATI Radeon Vega Series / Radeon Vega Mobile Series

 - Kodi version: 18.5 Git:20191116-nogitfound

**Comment by ronie** [comment] 2020-01-07 20:31
dupe of https://github.com/xbmc/xbmc/issues/17150

**Closed by ronie** 2020-01-07 20:31 UTC
Labels: Ignored rules, Triage: Needed
