### ISSUE TITLE
Kodi segfaults on exit

### ISSUE THREAD

**Issue by bacon-cheeseburger** [xbmc/xbmc#17754] opened 2020-04-25 21:50 UTC
### Describe the bug

Kodi segfaults on exit. Tested using Application.Quit via json rpc, kodi-send.py --action="Quit", and kill -SIGTERM.

## Expected Behavior

I expected Kodi to shut down clean, no crashing.

## Actual Behavior

Kodi segfaults when exiting. After taking a quick look at the backtrace, lrusak mentioned the cause may be spdlog related.

### To Reproduce

1. Start Kodi using the provided shell script.
2. Once Kodi is running, stop it: kodi-send.py -a quit

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/ovojayunib.kodi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Debian Sid Linux
 - Kodi version: 19.0-ALPHA1-git+cdb887b088

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment] 2020-04-25 22:02
assigning @Montellese as it seems to be spdlog related. I'm not sure what is trying to log during shutdown that is causing the SEGV.

@bacon-cheeseburger can you possibly run kodi in gdb (if using gbm you'll need to do it over a remote ssh session) and try to get a full backtrace?

**Comment by bacon-cheeseburger** [comment] 2020-04-25 22:35
Full backtrace available at https://paste.kodi.tv/unujenaqux

**Comment by MilhouseVH** [comment] 2020-04-25 22:39
Try testing with #17718

**Comment by bacon-cheeseburger** [comment] 2020-04-26 00:26
@MilhouseVH I can confirm that #17718 fixes the crash here.

**Comment by enen92** [comment] 2020-05-12 11:02
Confirmed fixed by #17718

**Closed by enen92** 2020-05-12 11:02 UTC
Labels: Resolution: Fixed, Triage: Confirmed, v19 Matrix
