### ISSUE TITLE
Android - Seeking causes video freeze

### ISSUE THREAD

**Issue by aenima99x** [xbmc/xbmc#19713] opened 2021-05-10 02:33 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

When trying a seek during video playback, the video freezes in-place and stays stuck. Sometimes it will skip to correct place, but can be up to a 20+ second delay. Other times the skip doesn't complete and Kodi must be force-closed.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Seeking should not freeze video and should advance to correct place in video.

## Actual Behavior

Video freezes, seeking sometimes completes but after a 20+ second delay.

## Possible Fix

Unknown 

### To Reproduce

1. Navigate through file manager to nfs share and play video
2. Let video play
3. Press up on remote (mapped to long-seek) or press right on remote several times for longer skip

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/irelucimaj.kodi

### Screenshots
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Possible errors

2021-05-09 19:06:24.048 T:25152   ERROR <general>: CMediaCodecVideoBuffer::ReleaseOutputBuffer error in render(0)
2021-05-09 19:06:25.470 T:25315   DEBUG <general>: CDVDClock::ErrorAdjust - CVideoPlayerAudio::OutputPacket - error:89913.155352, adjusted:33366.666667
2021-05-09 19:06:25.490 T:25315   DEBUG <general>: CDVDClock::ErrorAdjust - CVideoPlayerAudio::OutputPacket - error:56546.488685, adjusted:33366.666667
2021-05-09 19:06:25.509 T:25315   DEBUG <general>: CDVDClock::ErrorAdjust - CVideoPlayerAudio::OutputPacket - error:23179.822018, adjusted:33366.666667

### Your Environment
Used Operating system:

 - [ X ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Have tired Matrix 19.0, Matrix 19.1 and Matrix nightly (kodi-20210509-6234ab30-Matrix-arm64-v8a)
 - Multiple Nvidia Shields (Also tried on Jetstream Android device)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Mariusz89B** [comment] 2021-05-12 07:31
Yup same problem that I reported couple of days ago.
https://github.com/xbmc/xbmc/issues/19562

**Comment by toby11** [comment] 2021-05-30 11:48
yes since 19.1 fast forward causes the video to freeze. Pretty major issue with useability!

**Comment by phunkyfish** [comment] 2021-05-30 11:52
Please try using the default skin and uninstall UnpauseJumpback completely and see if it makes any difference.

**Comment by popy2k14** [comment] 2021-08-29 08:13
Had the same issue on an shield rv pro 2019 with kodi 19.1 and not installed those add-ons. Seeking in pvr zattoo freezed the picture,always.

Any news on this?

**Comment by Mariusz89B** [comment] 2021-08-29 08:40
@popy2k14 maybe this will help:
https://github.com/xbmc/xbmc/issues/19562#issuecomment-873368068

**Comment by popy2k14** [comment] 2021-08-29 10:11
@Mariusz89B 
Thanks a lot for the hint.
When I got you right it's an android (shield?) only bug.
I can tell that the issue is Not present on my philips Android TV, seeking works.

So the workaround has to implemented into the PVR addon?

But wouldn't it be good to fix the issue in kodi?

Can't get my hands on this now, can you please get an debug log on your shield?

**Comment by Mariusz89B** [comment] 2021-08-29 10:27
@popy2k14 Yes, seeking problem was related to my Nvidia Shield, I did not test this issue on different Android systems.

Instead of using seek.Time tbh not a good solution,  implementing timeshift_buffer to playlist item to play catchup streams resolved my problem.

               https://github.com/Mariusz89B/script.mtvguide/blob/db03ded01347abd906ceefb4e9ec97f98561bc50/playService.py#L1033

**Comment by phunkyfish** [comment] 2021-08-29 11:36
@popy2k14, pvr.zattoo uses adaptive so likely it’s related so would make sense to raise it there.

@glennguy just for awareness.

**Comment by glennguy** [comment] 2021-08-29 12:07
> So the workaround has to implemented into the PVR addon?

IMO it's not a 'workaround' that @Mariusz89B speaks of. No idea if anything has been changed in the zattoo add-on yet but you should consider opening an issue on their repository and linking back here.

**Comment by popy2k14** [comment] 2021-08-29 15:26
Thanks guys.
Have raised an issue there: https://github.com/rbuehlma/pvr.zattoo/issues/126

As stated in the issue:
There's a difference between an phyton & pvr binary addon.
Sadly i am not so deep in kodi PVR addon development,
Can you please check if the issue can be fixed in the addon or has to be in kodi itself?

I get my shield back in a few days and can provide logs if needed.

**Comment by Mariusz89B** [comment] 2021-08-29 15:46
@popy2k14 You will have to change the inputstream adaptive property in the addon itself, as I only read Python I'm not able to help you as the addon is written in C+.

**Comment by popy2k14** [comment] 2021-08-29 16:25
@Mariusz89B 
Thanks, i think it's complete different story because as you said, different languages & entry point's from/to kodi.

@glennguy 
I can provide a new debug log in a few days when i got my shield. My initial test's was on 19.1 a few week's ago.

**Comment by popy2k14** [comment] 2021-08-29 17:49
Guys, we have an answer from @rbuehlma on the ticket, stating:

```
This addon does not handle the stream (it only delegates an URL to play to inputstream.adaptive) and it also does not do any seek on the streem except of providing a commercial skip of 5 minutes in case of recordings and replay. I guess the right place to open this ticket against would be inputstream.adaptive.
```

Will try to get an debug log when i can get my hands on my shield again.
And will post it here.

**Comment by Mariusz89B** [comment] 2021-08-29 17:55
> Guys, we have an answer from @rbuehlma on the ticket, stating:
> 
> ```
> This addon does not handle the stream (it only delegates an URL to play to inputstream.adaptive) and it also does not do any seek on the streem except of providing a commercial skip of 5 minutes in case of recordings and replay. I guess the right place to open this ticket against would be inputstream.adaptive.
> ```
> 
> Will try to get an debug log when i can get my hands on my shield again.
> And will post it here.

The issue is when he delegating the url for inputstream, he need to add timeshift_buffer property.

**Comment by mrfixit2001** [comment] 2021-11-05 15:04
This isn't limited to Android. I have been experiencing this ever since Matrix was first released on Linux. I've tried multiple releases as well as my own custom compiles. It's not specific to any addon, as playing local videos also will not seek. Same behavior described, when seeking it buffers for a moment and then just stops playback completely.

There are other issues all titled differently that are likely all linked to this same problem. Some folks were able to resolve the issue inside addons themselves by programatically activating "play_timeshift_buffer" in inputstream.adaptive but in my cases (and many others) it's an issue playing locally as well regardless of addon. I don't believe local playback is related to inputstream.adaptive at all.

It's possible the following issues are actually all the same root cause:
https://github.com/xbmc/xbmc/issues/19562
https://github.com/xbmc/inputstream.adaptive/issues/785
https://github.com/xbmc/xbmc/issues/17053
https://github.com/xbmc/xbmc/issues/19454
https://github.com/xbmc/xbmc/issues/17064

Will be following this thread carefully for future thoughts and solutions.

**Comment by phunkyfish** [comment] 2021-11-05 20:03
Most of those bugs/PRs are from Kodi 18 and lower so should not be relevant as you said your issues began in Matrix.

I believe this issue was specific to inputstream.adaptive.

**Comment by mrfixit2001** [comment] 2021-11-16 14:00
If this was inputstream.adaptive, then I would think the following kodi patch would address the issue, but it does not have any affect :( Local playback and stream playback do not allow me to seek forward or backwards.
Oddly - Netflix DOES?! I can seek and resume playback in netflix (with and without the below patch)... (* *scratches head* *)

```--- a/xbmc/cores/VideoPlayer/DVDInputStreams/InputStreamAddon.cpp
+++ b/xbmc/cores/VideoPlayer/DVDInputStreams/InputStreamAddon.cpp
@@ -149,6 +149,9 @@
     propsMap[key] = m_item.GetProperty(key).asString();
   }
 
+  if(propsMap.find("inputstream.adaptive.play_timeshift_buffer") == propsMap.end())
+    propsMap["inputstream.adaptive.play_timeshift_buffer"] = "true";
+
   props.m_nCountInfoValues = 0;
   for (auto &pair : propsMap)
   {
```

**Comment by phunkyfish** [comment] 2021-11-16 18:03
> If this was inputstream.adaptive, then I would think the following kodi patch would address the issue, but it does not have any affect :( Local playback and stream playback do not allow me to seek forward or backwards. Oddly - Netflix DOES?! I can seek and resume playback in netflix (with and without the below patch)... (* _scratches head_ *)
> 
> ```
> +++ b/xbmc/cores/VideoPlayer/DVDInputStreams/InputStreamAddon.cpp
> @@ -149,6 +149,9 @@
>      propsMap[key] = m_item.GetProperty(key).asString();
>    }
>  
> +  if(propsMap.find("inputstream.adaptive.play_timeshift_buffer") == propsMap.end())
> +    propsMap["inputstream.adaptive.play_timeshift_buffer"] = "true";
> +
>    props.m_nCountInfoValues = 0;
>    for (auto &pair : propsMap)
>    {
> ```

You don’t mention what platform you are using. Let’s start there. Have you tried other platforms to see if the behaviour is different. My guess is that your issue is unrelated to the problem described in this issue and is something else.

**Comment by mrfixit2001** [comment] 2021-11-16 18:53
@phunkyfish I want to thank you for your continued responses and feedback! I'm using a custom build, and I've heavily patched KODI. I did, however, finally solve my issue today... It was related to ffmpeg itself and the hardware acceleration code. I actually patched ffmpeg to correct that a couple weeks ago but it didn't solve my seek issue.... but I had forgotten to remove an older attempted fix that I had patched in kodi that I borrowed from LE that kwiboo had authored (which resolved seeking an amlogic boards). With that patch removed, along with my ffmpeg patch, I'm looking good :) 

Sorry for the noise, and thanks again for wanting to help. I'll probably leave this timeshift buffer patch in place in my build anyways (for now), as clearly some addons need this enabled.

**Comment by nunojsa** [comment] 2021-11-29 13:14
Is there any conclusions on this? I see that there some spread threads around different plugins for what seems to be the same problem, so I will post here my issues...

@phunkyfish, I'm actually having issues with this on the pvr iptv simple client addon and honestly I'm not sure if the problem is in the simple client, in the ffmpegdirect or nothing to do with it. My issue seems to be related with #19436 since all my streams using AAC don't play nicely (the other ones worḱ fine): I see 2 different results:

1. Timeshift + catchup enabled and the faulty streams just lag a lot. At the OSD, I can see that the show duration is completly wrong (just some strange value like 596523:14:07/120:01:12).
2. Timeshift + catchup disabled and  sometimes the faulty streams just start with a huge delay between audio and video (i.e, videos comes after audio).

Any inputs would be highly appreciated (BTW, I'm running kodi (osmc) on an ARM based device)...

**Comment by GottemHams** [comment] 2021-11-29 23:30
I've experiencing something similar on my Raspberry Pi running OSMC (which is based on Debian). It definitely started occurring with Matrix, since it never once exhibited this behaviour on older versions of Kodi. It doesn't seem to be limited to just AAC audio streams as people said in the [forum thread](https://forum.kodi.tv/showthread.php?tid=362500), it also happens for AC3 and HE-AAC (which is quite different from "standard" AAC). Plus, audio actually starts playing again if I wait long enough (20+ seconds) while video keeps being frozen. All my videos are h264 because my particular Pi doesn't handle h265 very well. You don't even have to seek with a remote, even with a physical keyboard (pressing arrow left/right) this frequently occurs. When it does, CPU usage goes through the roof and usually I just force kill Kodi. Sometimes seeking again a couple of times, or pausing/playing about a dozen times might work too. The problem doesn't always happen, but I'd say it's about 90% of the time.

I'm not using any video plugins besides the ones that already come with Kodi, I actually barely use any plugins at all. I don't know how to get a list of user-installed plugins but if I remember correctly it's just some subtitles, screensaver and web interface stuff. I'm also using the default skin.

I would get a debug log but since the RPI runs off an SD card it doesn't survive for very long under the massive amount of logging (I've actually had to replace 2 SD cards within a few weeks before I turned off logging altogether and it never died again). If I could write the log to a share over SMB then maybe it's possible, but I don't see a way to change the log path. I could use a bind mount to force it but I'm sure Kodi doesn't expect the overhead of writing to somewhere on the network, so it likely won't handle that very well (like, what if the share disappears for whatever reason)?

**Comment by phunkyfish** [comment] 2021-11-29 23:37
Are you playing back videos via PVR or something else?

I just want to point out that if you are running OSMC you need to raise the issue there. OSMC and similarly LibreElec are based on Kodi but have many customisations especially around video/audio codecs on arm devices.

**Comment by GottemHams** [comment] 2021-11-29 23:54
My videos are just hosted on a good old SMB share. I get where you're coming from about the customisations, but I've been using OSMC since around v11 of Kodi and not once did I get this behaviour so I honestly doubt it's on their end. I also __did__ see this was originally reported for Android, but users of other Linux-based OSes reported the same behaviour:
> This isn't limited to Android. I have been experiencing this ever since Matrix was first released on Linux. I've tried multiple releases as well as my own custom compiles. It's not specific to any addon, as playing local videos also will not seek. Same behavior described, when seeking it buffers for a moment and then just stops playback completely.

I don't see an actual fix for Android though. And just because it was reported for Android doesn't mean we can't chime in with other (Linux-based) stuff, because if the issue is more widespread than just Android they might not know about it (since they might not have access to a different system).

If there's a way to generate a debug log outside of the SD card then we can tell if it's OSMC-specific or actually something with Kodi.

**Comment by mrfixit2001** [comment] 2021-11-30 00:35
Just my 2-cents, but i would bet the issue is more on the ffmpeg side than the xbmc side.

**Comment by popy2k14** [comment] 2021-11-30 07:10
> Are you playing back videos via PVR or something else?
> 
> I just want to point out that if you are running OSMC you need to raise the issue there. OSMC and similarly LibreElec are based on Kodi but have many customisations especially around video/audio codecs on arm devices. They have their own support channels.
> 
> This issue was opened for Android but everyone appears to have ignored this now. I think for Android this issue is resolved.
> 
> So I propose closing this issue.

no it's not solved.
I was quite in here because dont use kodi anymore as my main system.
BUT i tested 19.3 and latest nightly (around when 19.3 dropped) and the issue is still here on shield tv pro 2019 with latest experience updates and pvr.zattoo addon.

Do not close this!

**Comment by phunkyfish** [comment] 2021-11-30 08:54
The issue started as an Android specific issue, likely with inputstream.adaptive but hard to tell as the original reporter has not chimed in since and the log has now expired. Luckily @popy2k14 appears to have the same issue using adaptive via pvr.zattoo. Note that @popy2k14 has no local playback problems with AAC.

Then @mrfixit2001 reported it was more widespread than Android but then later reported it was a mistake in his custom builds.

For those of you running OSMC or LibreElec you need to start there for support and rule out your specific platforms causing an issue before raising here (other questions like how do I create a log on my platform should also be asked there). If you still believe the issue is within Kodi then open another issue and reference this one with a link.

I’m not trying to give anyone the run around but I honestly believe this is an Android specific problem.

@popy2k14 lets follow up on the adaptive issue you opened as it just went cold. I still believe the issue is related to that as local playback works ok.

**Comment by phunkyfish** [comment] 2021-11-30 09:10
> Is there any conclusions on this? I see that there are some spread threads around different plugins for what seems to be the same problem, so I will post here my issues...
> 
> @phunkyfish, I'm actually having issues with this on the pvr iptv simple client addon and honestly I'm not sure if the problem is in the simple client, in the ffmpegdirect or nothing to do with it. My issue seems to be related with #19436 since all my streams using AAC don't play nicely (the other ones worḱ fine): I see 2 different results:
> 
> 1. Timeshift + catchup enabled and the faulty streams just lag a lot. At the OSD, I can see that the show duration is completly wrong (just some strange value like 596523:14:07/120:01:12).
> 2. Timeshift + catchup disabled and  sometimes the faulty streams just start with a huge delay between audio and video (i.e, videos comes after audio).
> 
> Any inputs would be highly appreciated (BTW, I'm running kodi (osmc) on an ARM based device)...

I’d recommend you create an issue on the pvr.iptvsimple GitHub and I can look into it.

**Comment by nunojsa** [comment] 2021-11-30 11:21
> I’d recommend you create an issue on the pvr.iptvsimple GitHub and I can look into it.

Will do that...

> For those of you running OSMC or LibreElec you need to start there for support and rule out your specific platforms causing an issue before raising here 

Already did that. I actually started there and then came across these issues and that made me think that it could be an issue with plain kodi. Anyways, before opening the issue in the pvr addon, I will do some more tests with this...

**Comment by mrfixit2001** [comment] 2021-11-30 13:48
Just to clarify @phunkyfish, this is a real existing issue and is not related to my custom builds. The fact that I resolved the issue myself doesn't negate that it is an issue. 
In my case, I needed to resolve an underlying issue with the rockchip driver in FFMPEG. 
To be fair, I've also extensively patched xbmc to resolve a number of issues which I've encountered, although it's unlikely most are related to this issue. Just wanted to call out that fixing ffmpeg might not be the only required fix. 
I should also point out that in my builds I'm rendering using GLES+GBM directly to DRM. It will be important to identify these details for those that are experiencing the issue, as there may be more involved in those fixes.

**Comment by nunojsa** [comment] 2021-11-30 14:51
> Ok, but if the issue in the other cases is that ffmpeg drivers need fixing that is up to OSMC and LibreElec teams to fix. It’s not something we can ever hope to fix here.

Well, I can confirm that (for my iptv related issues) for x86 things work well with HW acceleration. On my arm system it doesn't. Well, if I disable HW acceleration then things seem to be ok but the performance makes it a no go (for a temporary workaround). Anyways, I will have do some more testing and then and then open an issue in pvr.iptvsimple if applicable...

> It’s not something we can ever hope to fix here.

I'm curious here... what about raspberry pie? I think kodi as a release for it as well, right? So, it should be possible to use upstream kodi without any of OSMC/Libreelec patches...

**Comment by popy2k14** [comment] 2021-11-30 15:09
@mrfixit2001 Do you have own android builds to test? Do you plan to commit those changes via PR, so everyone can profit?

@ all
What does this message mean:
`2021-08-31 20:33:34.343 T:11513   ERROR <general>: CMediaCodecVideoBuffer::ReleaseOutputBuffer error in render(0)`

That line i always have on the issue. But it could be just an consequential failure of the underlaying issue.

**Comment by nunojsa** [comment] 2021-11-30 15:18
To me, something that might be related with my issue is:

```
2021-09-05 00:29:20.565 T:3064    DEBUG <general>: CVideoPlayer::CheckContinuity - resync forward :1, prev:18442241078923337728.000000, curr:36884481552954867712.000000, diff:18442240474031403008.000000
2021-09-05 00:29:20.565 T:2901  WARNING <general>: ActiveAE - large audio sync error: -18446744073705928.000000
```

**Comment by phunkyfish** [comment] 2021-11-30 16:00
@glennguy FYI. ^^*

**Comment by phunkyfish** [comment] 2021-11-30 16:01
@nunojsa raspberry pi was removed from kodi.

**Comment by GottemHams** [comment] 2021-11-30 16:08
@phunkyfish Apparently a bind mount works fine for (temporarily) redirecting the log to an SMB share (just FYI). When the problem occurs a __massive__ amount of the following line appears in the logs (with a decrementing number at the end, until I get it unstuck or kill Kodi):
`2021-11-30 16:29:06.268 T:4092  WARNING <general>: ActiveAE - large audio sync error: 72323.081789`

Does that seem like it could even be related to OSMC? Otherwise #19436 might actually be the issue I'm having.

**Comment by phunkyfish** [comment] 2021-11-30 16:36
> @phunkyfish Apparently a bind mount works fine for (temporarily) redirecting the log to an SMB share (just FYI). When the problem occurs a **massive** amount of the following line appears in the logs (with a decrementing number at the end, until I get it unstuck or kill Kodi): `2021-11-30 16:29:06.268 T:4092 WARNING <general>: ActiveAE - large audio sync error: 72323.081789`
> 
> Does that seem like it could even be related to OSMC? Otherwise #19436 might actually be the issue I'm having.

If it’s a problem with local playback that appears to be a more likely issue. But please check with OSMC first. If it is a driver issue they should may be able to fix this easily.

**Comment by timakaze** [comment] 2021-12-01 23:30
I have the same problem on windows 10 Kodi 19.3 and Kodi 18. Using the chapter skip function will 90% of the time cause the video to freeze and loose audio. Shutting down Kodi and restarting is the only way to get the audio back. This is with local files on an internal HDD. 4k files mostly.

**Comment by phunkyfish** [comment] 2021-12-02 11:39
> I have the same problem on windows 10 Kodi 19.3 and Kodi 18. Using the chapter skip function will 90% of the time cause the video to freeze and loose audio. Shutting down Kodi and restarting is the only way to get the audio back. This is with local files on an internal HDD. 4k files mostly.

Please open a new issue for this please and supply a full debug log.

**Comment by mrfixit2001** [comment] 2021-12-10 01:19
Additional piece of detail... the piece I fixed is technically "skipping" - hitting left or right to jump forward intervals of time. Whereas "seeking", which temporarily changes the playback or reverse speed, works but when I return to normal speed again playback is always choppy afterwards. Weird.

**Comment by phunkyfish** [comment] 2021-12-10 07:08
Skipping and seeking should be the same thing. Jumping to a point in time.

Tempo controls are like fast-forward and rewind as they adjust the pace at which you move through a stream.

**Comment by matthuisman** [comment] 2021-12-30 17:30
Maybe the below will help with this issue?
https://github.com/xbmc/xbmc/issues/19436#issuecomment-1002958894

**Comment by mrfixit2001** [comment] 2021-12-30 17:55
Excited to give this patch a try tonight.

**Comment by mrfixit2001** [comment] 2022-01-03 14:26
As a follow-up - that commit should definitely be backported to matrix - it fixes fast forward for me :)

**Comment by popy2k14** [comment] 2022-01-08 16:26
@ anyone with this issue not solved, please try the arm64 android build from glenguy here: https://github.com/xbmc/inputstream.adaptive/issues/785#issuecomment-1007993335

At least it fixed my issue here: https://github.com/xbmc/inputstream.adaptive/issues/785
Please be aware thats an testbuild with other signing keys, so backup your data, uninstall matrix, install testbuild and restore data. A smiple rename of the Android/data/com.kodi... folder also works.

I already have done an backport to matrix: https://github.com/xbmc/xbmc/pull/20819

So should be soon available on nightly builds too.

**Closed** 2022-01-09 14:20 UTC
Labels: Platform: Android, v19 Matrix, Triage: Confirmed, v20 Nexus
