### ISSUE TITLE
audio glitch with multiple AAC audio track since 20.1 

### ISSUE THREAD

**Issue by pat147** [xbmc/xbmc#24827] opened 2024-03-09 13:29 UTC
### Describe the bug
Hello,

this pb is linked to https://forum.kodi.tv/showthread.php?tid=376539&pid=3187300#pid3187300
and was confirmed by CrystalP.

Detail : 
Audio has some glitch (some very small stop / start).
Basically i'm muxing in a mkv file both french and english audio, both are coming from video : Pal for french (25 fps) and ntsc for english (23.976 fps)
The original file is a mkv with x65 video (23.976 fps) and AAC english audio.

i'm using mkvtoolnix (latest version also) to add the french audio (and to use delay and time stretching to align with the video).
The result is some very small stop / start in the audio which appears in the muxed audio French track.

## Expected Behavior
no glitch in audio

## Actual Behavior
glitch in audio

## Possible Fix
i have made further test ... indeed the option "Sync playback to display" help a lots ... but after some time, the pb appears again .. but not so fast, and not so obvious.

### To Reproduce
this pb is linked to https://forum.kodi.tv/showthread.php?tid=376539&pid=3187300#pid3187300

### Your Environment
currentlly on Debian, but same pb with ubuntu / windows 
evertyhing is working correctly with Kodi BEFORE 20.1

**Comment by CrystalP** [comment] 2024-03-09 15:01
Please attach a debug log (turn on debugging, restart Kodi, play the file, upload the kodi.log of the user data folder to paste.kodi.tv and add the link here) so that the non-compliance tag can be removed

**Comment by pat147** [comment] 2024-03-09 16:18
https://paste.kodi.tv/hajadarezo.kodi without the sync activated
https://paste.kodi.tv/utufigikoc.kodi with the sync activated

**Comment by CrystalP** [comment] 2024-03-09 16:30
Comes from #22796 later backported as #22870 to nexus

**Comment by thexai** [comment] 2024-03-10 12:07
> Basically i'm muxing in a mkv file both french and english audio, both are coming from video : Pal for french (25 fps) and ntsc for english (23.976 fps)
> The original file is a mkv with x65 video (23.976 fps) and AAC english audio.

You can not take an audio of 25.0 fps video and remux (add) to other 23.976 fps video because time stamps not match.

You need use some tool like eac3to to convert audio first:
https://forum.doom9.org/showthread.php?t=125966

> -slowdown          convert 25.000 and 24.000 content to 23.976 fps
> -speedup           convert 23.976 and 24.000 content to 25.000 fps

That Kodi works poorly with a file that is incorrect is not a bug.

**Comment by thexai** [comment] 2024-03-10 12:30
To disable a/v sync "self-learning" algo you can use this in `advancedsettings.xml`

```xml
<advancedsettings>
  <audio>
    <maxpassthroughoffsyncduration>11</maxpassthroughoffsyncduration>
  </audio>
</advancedsettings>
```

This should result in almost same behavior that older Kodi versions.

Or even try other fixed values up to 100 (if you not want Kodi try to fix a/v sync errors up to 100 ms)

**Comment by thexai** [comment] 2024-03-10 13:15
Closed as this file is bad: 
https://forum.kodi.tv/showthread.php?tid=376539&pid=3186962#pid3186962

**Closed by thexai** 2024-03-10 13:15 UTC
Labels: Component: Video, Triage: Needed, Component: Players, v21 Omega

**Comment by pat147** [comment] 2024-03-10 15:24
Hi, i try with the advancedsettings.xml but don't works.

>You can not take an audio of 25.0 fps video and remux (add) to other 23.976 fps video because time stamps not match
As explained, even if the audio file has not the right side, it's not a pb : if the video is longer : the video continue with sound, if the video is shorter : the player stops the file.

>This is not possible to fix at the remux level (i.e. adding a delay).
was working perfectly before kodi 20.1.
and you can do both : strecth the audio and add a delay with Mkvtoolnix in the audio track.

>https://forum.doom9.org/showthread.php?t=125966
i was using this before but then i found what I explain above.

anyway, i found a player doing the trick perfectly : smplayer on debian. and on windows MPC-BE

**Comment by CrystalP** [comment] 2024-03-10 15:26
As far as I know mkvtoolnix alters the timestamps when using the delay/stretch parameters so the file is probably not "incorrect".
But that would put the burden on the player to maintain a/v sync either by stretching/shrinking the audio (sync playback to display ON) or by skipping/duplicating video frames here and there (sync playback to display OFF).
VLC has the same problem as Kodi, mpv does a good job with the sample it seems.

**Comment by thexai** [comment] 2024-03-10 16:18
Google is your friend:
https://forum.videohelp.com/threads/312812-25fps-source-Ac3-to-23-976fps

**Comment by CrystalP** [comment] 2024-03-10 18:29
See https://gitlab.com/mbunkus/mkvtoolnix/-/wikis/Stretch-or-shrink-audio-tracks
It does scale the timecodes. Adjusting the video stream is recommended instead.
