### ISSUE TITLE
KODI Ignores -trailer when .nfo has a web url trailer

### ISSUE THREAD

**Issue by C4Wiz** [xbmc/xbmc#16920] opened 2019-11-16 02:05 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

nfo file has a url to a trailer on youtube, added a local trailer named the same as the movie with -trailer added, kodi does not use the local trailer until i remove the trailer url from the .nfo file

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

kodi should use the local trailer instead of the web url

## Actual Behavior

KODI Ignores -trailer when .nfo has a web url trailer

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: OSMC 2019-10-1
 - Kodi version: 18.4

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment] 2019-11-16 02:13
Issue confirmed.

Kodi ignores a local <movie>-trailer.ext file in favour of a URL that was present in an nfo file or when the trailer option is enabled in the scraper settings .

Kodi should prefer local trailer files first, the same way it prefers local artwork and local metadata.

**Comment by iammarco11** [comment] 2019-11-16 13:12
@C4Wiz Could you put the link having the screenshots of the issue #16920.

**Comment by C4Wiz** [comment] 2019-11-16 13:17
> @C4Wiz Could you put the link having the screenshots of the issue #16920.

screenshots of what exactly?

this is simply kodi favoring the .nfo over the local file, when in fact for trailers it should be the other way around.

**Comment by KarellenX** [comment] 2019-11-16 17:31
Screenshots are of no use in this case.

**Comment by ladislavbalaz1977** [comment] 2020-03-11 04:50
QUALITY BEST&PRICE ALL PRODUCT!

**Comment by GiannisProkopiou** [comment] 2020-03-14 17:53
Greetings,this is still open right? I am already trying to fix this!
Let me know if there is anything i need to know other than what i see here.
Thanks in advance!

**Comment by C4Wiz** [comment] 2020-03-14 17:58
Fixed a while ago

**Comment by DaveTBlake** [comment] 2020-03-14 18:02
Any chance you know the PR that fixed it  @C4Wiz

**Comment by C4Wiz** [comment] 2020-03-14 18:49
No clue, it was a while ago

**Comment by DaveTBlake** [comment] 2020-03-14 18:58
Looks like this was resolved by https://github.com/xbmc/xbmc/pull/13566

**Closed by DaveTBlake** 2020-03-14 18:58 UTC
Labels: Component: Video, Resolution: Fixed, Triage: Confirmed, v18 Leia
