### ISSUE TITLE
Episode thumbs still showing Spoiler Overlay after being watched

### ISSUE THREAD

**Issue by HitcherUK** [xbmc/xbmc#15296] opened 2019-01-20 11:56 UTC
### Describe the bug

With 'Show information for unwatched items' set to only show Movie plot and Episode plot but not Episode thumbs - after a library update a new episode's image shows the Spoiler Overlay as expected but when marked as watched the image does not update to the episode thumb.

## Expected Behavior

After an episode is watched the image is changed to the episode thumb.

## Actual Behavior

After an episode is watched the image is still Spoiler Overlay.

## Possible Fix

A refresh of information (either episode or TV show) or manually changing the current thumb to the remote one fixes the problem.

### To Reproduce

1. Set 'Show information for unwatched items' to hide episode thumbs
2. Add a new episode to a TV show
3. Update library
4. Select new episode and mark as watched

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/ikuxufacog.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

Newly added episode marked as watched -
![screenshot006](https://user-images.githubusercontent.com/133808/51438765-17bf3080-1ca8-11e9-8f70-6f3951c59e05.png)

Choose Art -
![screenshot007](https://user-images.githubusercontent.com/133808/51438766-17bf3080-1ca8-11e9-88fe-a4ab562812f5.png)

Thumbnail -
![screenshot008](https://user-images.githubusercontent.com/133808/51438767-1857c700-1ca8-11e9-8f6e-49c1a7b2e7de.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: 18.0 RC5.2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment] 2019-01-20 12:37
After some talk to @HitcherUK and various tests on my side, I could not reproduce that issue at all on Linux using Ubuntu 16.04 or 18.04. 

The following logfile will show a completely vanilla Kodi (deleted .kodi before). After the start of Kodi, I set Kodi to *not* display episode thumbs or plots. Then I set Kodi to windowed mode and added a source and let Kodi scrape some dummy files (0-byte files created with `touch S01e{01..10}.mkv` for example). The log will also show the scraping. 

I get the following as the result: 

Here's an episode (S01E02) marked as unwatched directly after the scraping:
![unwatched](https://user-images.githubusercontent.com/7235787/51439262-d9317200-1cb7-11e9-9dfc-c8c861bc966e.png)

Here's the above episode (S01E01) marked as watched:

![watched](https://user-images.githubusercontent.com/7235787/51439283-29103900-1cb8-11e9-8732-96c8d81dd4b1.png)

I don't use NFOs or any thumbs stored into the folders. See the listing of my folders:
https://paste.ubuntu.com/p/G463bjxDB2/

**Comment by DaVukovic** [comment] 2019-01-21 05:37
This log show the same, but with another scraper: http://paste.ubuntu.com/p/Xxd4VFnxFJ/

Still no problems with it.

**Comment by HitcherUK** [comment] 2019-01-21 06:02
Can you try using only one episode for a show you've never had in your library and then updating your library. Once that is done add the next episode and update again please.

**Comment by DaVukovic** [comment] 2019-01-21 14:02
I did that before by removing the .kodi folder which is a completely vanilla Kodi. 

But I also tried it now here with my laptop at work:

- no TV shows ever existed on that laptop
- created dummy files for the Show "Modern Family". That show has 22 episodes and I only added 21
- let Kodi scrape
- added episode 22
- let Kodi update

Screenshots:
21 Episodes listed and have been scanned with "Show thumbs" disabled":
![scan1](https://user-images.githubusercontent.com/7235787/51478709-84136000-1d8c-11e9-8fa5-82e721b81c20.png)
Marked episode 21 as watched. Thumb is visible:
![scan2](https://user-images.githubusercontent.com/7235787/51478714-883f7d80-1d8c-11e9-9d4e-fbe8dc0a3800.png)
Created dummy file for episode 22 and was scanned with "Show thumbs" disabled:
![scan3](https://user-images.githubusercontent.com/7235787/51478720-8aa1d780-1d8c-11e9-8c76-2053f8277002.png)
Marked episode 22 as watched, thumb is visible:
![scan4](https://user-images.githubusercontent.com/7235787/51478723-8d9cc800-1d8c-11e9-8b65-6eb93ea1090d.png)

¯\_(ツ)_/¯

Maybe you could try with a vanilla Kodi. I'm not sure if that's important or not, but for some reason the `embuary.helper` script is somehow involved on your system: 

```
11:35:21.574 T:20664  NOTICE: script.embuary.helper: Service started
11:35:21.575 T:20664  NOTICE: script.embuary.helper: Start new fanart grabber process
11:35:21.671 T:20664  NOTICE: script.embuary.helper: Backgrounds: No movie artworks found.
```
For me it's plain vanilla Kodi. Maybe some addon is causing it.

**Comment by HitcherUK** [comment] 2019-01-21 15:34
Totally vanilla Kodi, exact same results.

https://paste.kodi.tv/gayabuluke.kodi

**Comment by DaVukovic** [comment] 2019-01-21 18:19
ok, I can also reproduce now. But it only happens with real video files. For whatever reason, even if the playcount is `1`, the image stored at the db under `episode`-table at the field `c06` isn't shown

**Comment by therealcodlord** [comment] 2021-09-04 08:56
I know this is a very old issue, but I would like to fix it.

I recently raised this same issue on the [Kodi Forum here](https://forum.kodi.tv/showthread.php?tid=361502) and discussed with @DaVukovic. It still seems to be an outstanding bug. There was a proposal to revert the change [here](https://github.com/xbmc/xbmc/pull/15317) which is marked as closed as well as a revert commit [here](https://github.com/DaVukovic/xbmc/commit/871327548b26ba087ea9bc4ed27ed24c4dfe1a36). The changes were never reverted.

I just spent the last few days building Kodi (nightly) and examining the code and I believe I have built a fix for this bug, but as I have not done this sort of development before I could do with some help/support to go the next step (commit changes and have them reviewed etc). I am a past programmer (now retired) so I understand the concepts, just not the actual use of GitHub for commits/discussion etc.

I think the code in [VideoThumbLoader.cpp](https://github.com/xbmc/xbmc/blob/68bf07ee4fab9f844a9bef3ddeeb443be45d9453/xbmc/video/VideoThumbLoader.cpp#L386) to show the OverlaySpoiler.png for unwatched TV episodes exhibits the bug due to the fact that the code is executed on a media scraper run as well as when the thumbs are shown. And the database is actually updated with the spoiler artwork, so when a refresh/media scraper is run the thumb is set to the OverlaySpoiler.png. This means when it is subsequently marked as watched it still shows the OverlaySpoiler.png (until another refresh/scrape is executed). 

I believe that the code should never change anything in the database to set the OverlaySpoiler.png artwork thumb. Scanners/scrapers or the user manual thumb preferences should always be set/honoured. It should be the interface display which should simply be showing either the defined thumb artwork (if its a watched TV episode) or the OverlaySpoiler.png if it's an unwatched TV episode. Hence my fix proposes to move the code from VideoThumbLoader.cpp to [GUIInfoManager.cpp](https://github.com/xbmc/xbmc/blob/1186fac7317888c467fcee358e3776eb33ee0ba9/xbmc/GUIInfoManager.cpp#L10847) where it returns thumb artwork to the front end. In two places (case LISTITEM_THUMB and case LISTITEM_ICON).

Note: The current nightly code has has an update somewhere along the line to use Fanart artwork instead of OverlaySpoiler.png if Fanart is available. I just kept my descriptions above simple mentioning only OverlaySpoiler.png.

**Closed** 2021-11-01 19:53 UTC
Labels: v18 Leia, v19 Matrix, Resolution: Fixed, Triage: Confirmed
