### ISSUE TITLE
Subtitle Size in KODI Alpha widely vary in size and format efffected by video file format.

### ISSUE THREAD

**Issue by kleczerx** [xbmc/xbmc#21718] opened 2022-07-30 23:56 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

- Subtitles take size of the video format being played at the time. Subtitle size should conform to the KODI's (Versions Alpha 1 & 2) setup selected.
- Subtiles, whether sources internally, from the video file, OR external subtitles, vary in size effect directly by the video's format being played. In previous versions of KODI, the subtitles were set or fixed in size based on manual setup selected by the user.
- This is a bug because subtitles vary in size from extremely large to extrememly small. OTHER PROBLEM: In most cases, each line of the subtitle text does not recogize double or triple line setting and display the line a a single line displayed from the extreme left to the right edge of the screen; better said, subtitles generally display 2 or 3 lines at a time but now only as a single line.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
 

The subtitles should conform to the selected setting in Kodi Setup > settings > Player > Subtitles > Size.. 

## Actual Behavior

Rather, the size of the subtitles conform to the video format played at the time. The size of subtitles may vary/change from one video format to another, large or small size.

## Possible Fix

Disassociate video format effects on subtitle format.

### To Reproduce

1. Play 2160p or 1080p video after setting subtitles size to (e.g) 30.
2. Play, with subtitles, one format then the other format. If all is well, the subtitles should remain similar; otherwise different sizes.
3. Playing two similary formats (both 1080p for example) will also differ subtitle size view because rarely do video formats maintain similar standards. 

### Debuglog

The debuglog can be found here:

### Screenshots
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I suffer viewing generally extrememly large texted subtitles.

### Your Environment
Used Operating system:

 - [x] Android Version 20 ARM64-v8a.apk
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows Windows 11, all upgrades
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Kodi Alpha 1 and 2, effected.  Version 20 ARM64-v8a.apk
- Android Media Player: Nvidea Shield (latest firmware upgraded)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment] 2022-08-01 08:12
the situation is not full clear, so is needed:
- the full debug log
- to know if you are playing on 4k or 1080p resolution tv/monitor
- to know the subtitles format type of your videos, if you dont know you can use a software like MediaInfo to get details

i tried replicate by using 1080p monitor, by trying to compare 640p movie with a 4k movie but i see always same text size
i tried to replicate by emulating 4k monitor (i dont have 4k monitor) and i dont see differences in text size between 4k movie/srt and 1080p movie/srt
so for now i have no idea whats happens to you

> OTHER PROBLEM: In most cases, each line of the subtitle text does not recogize double or triple line setting and display the line a a single line displayed from the extreme left to the right edge of the screen; better said, subtitles generally display 2 or 3 lines at a time but now only as a single line.

for this "other problem", you must provide a subtitle file on which to test

we will see after we have all the info

**Comment by kleczerx** [comment] 2022-08-08 21:36
From: Kleczek - Toronto
Sent: Wednesday, 3 August, 2022 18:01
To: xbmc/xbmc ***@***.***>
Subject: RE: [xbmc/xbmc] Subtitle Size in KODI Alpha widely vary in size and format efffected by video file format. (Issue #21718)

Subtitles vary in size.

Overall, the best way to observe subtitles font sizes and positioning changes is to use the keyboard “Z” key to change video format. This key will give a number of video formats, for the one video played at the time, to simulate format changes from one video file to another. Previous Kodi version had the subtitle remain a standard size (standard meaning that chosen in Kodi settings) dispite the video format or the use of the Z key to effect the video format.

Bug Log: I have nothing to show.

My configuration:
TV Samsung 900t QLED 8K  (my desktop PC Windows 11 with 4K monitor)
Media Player: Nvidea Shield | Kodi Alpha2 ARMV8A (64Bit)
Windows 11 Kodi Alpha2 (x64)

Tried to send photo samples of subtitles shown based on format. The email was constantly rejected. So no photo samples shown..:



Many thanks for emailing me direct.

Richard Kleczek
Toronto, Canada.

====================================================================================

**Comment by CastagnaIT** [comment] 2022-08-09 06:33
i have not sent to you an e-mail, what you are receiving are automated GitHub notifications e-mail messages

in order to attach files you have to go to where you opened the Issue by using the browser,
i not suggest to reply by using e-mail because add a lot of junk to the messages

"Z" shortcut force change the "view" format and currently affect subtitles this is already know
from my part i havent found no valid solution to avoid this influence

**Comment by bunker2045** [comment] 2022-08-14 11:59
I also observe different subtitles size on different videos, although all videos are 4K and I do not switch resolution or any settings.

After doing some tests I noticed that video aspect ratio has an effect on subtitles size. 
With 2.40:1 videos (3840x1600) subtitles are much smaller that with 1.78:1 videos (3840x2160).

This issue is always reproducible. I use Fire TV Stick 4K running kodinerds build of Kodi. The stick is connected to a 4K TV.

Just for a test I installed Kodi on my old MacBook (nightly build kodi-20220813-61f7ea86-master-26619-x86_64.dmg) and tried the same video files. The subtitles size was the same for all videos!

**Comment by CastagnaIT** [comment] 2022-08-17 12:24
Here we do not provide support to custom kodi builds like kodinerd

so please install official kodi builds or we dont spend futher time on this Issue

i have done another test on android with NVIDIA Shield and 4k tv
following use cases:
- full 4k video 3840x2160
- cropped 4k video 3840x1608
- full 1080p video
with screen resolution as first set as 4k, and after set to 1080p
all videos have SRT subtitles

the results are that subtitles text is rendered with same size with all type of videos and resolutions

again if you have View mode setting (screenshot below), set different than "normal", please set it again to "normal"
![immagine](https://user-images.githubusercontent.com/3257156/185113607-b2533ca8-296d-47a1-b8b5-fa55f420200e.png)
this setting is know to influence the text size
if not, it is more likely a kodinerd bug or something related to not mentioned changed setting which i am not aware of, or advancedsettings

**Comment by bunker2045** [comment] 2022-08-17 15:54
Thank you very much for looking into this.

I did more testing using official Kofi Android build and I was able to reproduce the issue on both my systems: Fire TV 4K Max with Android (official build) and Mac (official build).

The issue occurs only when **Position on screen** (under **Settings/Player**) is set to **Below video** or **Above video**.

It doesn't happen with the default **Bottom of video**. That's why I couldn't reproduce this on Mac in my first test.

**Comment by CastagnaIT** [comment] 2022-08-17 16:13
oh ok could have sense in my tests i never changed position but atm i cannot test again,
this PR #21680 could have already fixed your problem but is in waiting to be merged,
i think the best is i will provide you some test builds with this change
so you can give a feedback

**Comment by kleczerx** [comment] 2022-08-17 17:17
***********************
Richard K – I have two Shield Nvidea units (using Kodi Android Kodi V20-arm64-v8a  ) on an 8K and 4K TV and I always set my subtitles to “below video” so you may found something…. Great!
***********************

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by kleczerx** [comment] 2022-08-17 17:28
As I said before I have always set my subtitles to “below video”.

My Build information:
Screen resolution: 3840x2160 @ 59.94 Hz – Full Screen
Operating System: Android TV 11.0.0 API Level 30 (kernel: Linux 4.9.141-tegra…)
KODI build: 20.0 ALPHA2 (19.90.705)

I will test the subtitle sizing issue by using the Settings for Kodi and positioning the subtitles to different parts of the screen.

Richard K
Toronto, ON


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by CastagnaIT** [comment] 2022-08-17 17:33
These are test builds, choose what you prefeer:
Android arm: http://mirrors.kodi.tv/test-builds/android/arm/kodi-20220817-81cffbd5-subtitle_pos-26330-armeabi-v7a.apk
Android arm64: http://mirrors.kodi.tv/test-builds/android/arm64-v8a/kodi-20220817-81cffbd5-subtitle_pos-23835-arm64-v8a.apk
Window 64bit: http://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20220810-81cffbd5-subtitle_pos-x64.exe
i cannot provide macos build atm

**Comment by bunker2045** [comment] 2022-08-17 19:13
I've tried the Android v7a build and can confirm the issue is fixed there.
Thank you very much!

----
BTW what is the best way to ask questions or feature requests about subtitles? I would think it's Kodi forum but I'm not sure which sub-forum it should be. There are so many.

**Comment by CastagnaIT** [comment] 2022-08-18 06:46
@bunker2045 for questions you can ask in "general support" by choosing the preferred OS:
https://forum.kodi.tv/forumdisplay.php?fid=111
for feature requests this section:
https://forum.kodi.tv/forumdisplay.php?fid=9

**Comment by CastagnaIT** [comment] 2022-08-19 12:11
@kleczerx i see that you still use email notification to read the Issue discussion
if you miss, some message above i attached the test builds links, here:
https://github.com/xbmc/xbmc/issues/21718#issuecomment-1218307880
so if you can please do a test and report a feedback thanks

**Closed** 2022-08-27 07:38 UTC
Labels: Need more information

**Comment by CastagnaIT** [comment] 2022-08-27 07:45
Since there are no more replies for the test build and the fix has been just merged this will be marked as fixed
for the:

> OTHER PROBLEM: ...

suggest you if needed to post your problem in the forum or open another issue by providing the subtitle file that raise the problem
