### ISSUE TITLE
no audio payback after sleep then video stops

### ISSUE THREAD

**Issue by markslyman** [xbmc/xbmc#25167] opened 2024-05-08 22:08 UTC
### Describe the bug 
Here is a clear and concise description of what the problem is:   
 Since upgraded to 21 running hdmi-cec connected Androidtv box, i get no audio output from kodi after i turn off and on the tv. So it appears, the tv signals the androidtv box to go into a sleep/standby mode when i turn it off tv. Then when i turn on the tv, the androidtv resumes from sleep mode. Kodi resumes also and when i play a movie, for example, there is no audio send to tv/soundbar.    

## Expected Behavior 
Here is a clear and concise description of what was expected to happen:  

 After android returns from sleep caused by powering off and on the tv, the audio should not be effected  after return from sleep/standby.    

## Actual Behavior   

After tv returns the androidtv from sleep/standby to powered on mode, the audio should continue to.work as before the restart.  

## Possible Fix   

The workaround is to enter into the media player audio settings and turn on or turn off "allow passthrough" then audio returns  

### To Reproduce Steps to reproduce the behavior:    

1. Power on tv and hdmi-cec connected androidtv ensuring that androidtv is a freshly booting. 
2. Play a movie and ensure that audio is playing. 
3. Turn off the tv and this will cause the androidtv to go into standby. 
4. Now, turn the tv back on and the androidtv and kodi will resume. Try to play the movie and there will be no audio and video stop playing 
### Debuglog 
 

https://paste.kodi.tv/mileqasehi

 ### Screenshots  Here are some links or screenshots to help explain the problem:

**Comment by neo1973** [comment] 2024-05-08 22:15
Piracy addons, therefor no support. And likely a duplicate of #24950 anyway.

**Closed by neo1973** 2024-05-08 22:15 UTC
Labels: Triage: Needed

**Comment by markslyman** [comment] 2024-05-08 22:32
> Piracy addons, therefor no support. And likely a duplicate of #24950 anyway.

Sorry ... updated the psstebin from.clean install. Looks like a duplicate, alright. Thanks

**Comment by markslyman** [comment] 2024-05-08 22:43
Tested the latest nightly and ir solved the problem. 🤞
