### ISSUE TITLE
Issue with nodes editing

### ISSUE THREAD

**Issue by Neelix57** [xbmc/xbmc#17765] opened 2020-04-27 06:42 UTC
Running Leia under Xubuntu Focal, the TV Show nodes filtered by a rule applied on the Title are not working anymore. But with applying rules on genre or path, for example works fine.

Tried under Confluence and Estuary skin.

[kodi.log](https://github.com/xbmc/xbmc/files/4537878/kodi.log)

**Comment by DaVukovic** [comment] 2020-04-28 06:42
Not a debuglog

Also please share more info how you exactly created those nodes. Please share screenshots from your settings for those nodes

**Comment by Neelix57** [comment] 2020-04-30 17:14
I created the nodes with Library Node Editor plugin.
Goes to TV shows node > Title.
Created a rule :  Title > does not contain > Star Trek                

Or created a new Parent Node : Star Trek
Added Content :+1: TV shows
Added Order : by title (ascending)
Created a rule : Title > contains > Star Trek

**Comment by enen92** [comment] 2020-05-01 09:27
@Neelix57 the library node editor was updated to python3 and suffered a major re-write which fixed a lot of bugs but also introduced a few more. My suggestion before making sure this is in fact kodi-related is to remove the node, rollback the addon to version 1.0.6 and check if the issue persists. If not, we'll know the issue is in the addon.

**Comment by DaVukovic** [comment] 2020-05-10 08:38
@Neelix57 any comments?

If not, we will close this in the next few days

**Closed** 2020-06-12 12:05 UTC
Labels: Ignored rules, Issue Cleanup: Ask Reporter, Triage: Needed
