### ISSUE TITLE
Stacked bluray ISO play causes crash to desktop

### ISSUE THREAD

**Issue by lharms** [xbmc/xbmc#15627] opened 2019-02-26 23:35 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

With trying to play stacked bluray ISOs a crash to desktop occurs.

Non stacked and stacked DVDs ISOs play correctly.
Non stacked blurays ISOs also play correctly.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

movie plays

## Actual Behavior

crash to desktop on playback after picking title or show bluray menu.

## Possible Fix

I can cause the crash pretty much every time in a debugger.

It looks like it starts on line 3042 in Application.cpp

I changed 
if (m_stackHelper.IsPlayingISOStack() || m_stackHelper.IsPlayingRegularStack())
to if (m_stackHelper.IsPlayingRegularStack())

Basically I am skipping this line m_itemCurrentFile.reset(new CFileItem(*m_stackHelper.GetRegisteredStack(file)));

For some reason GetRegisteredStack seems to return a null object which causes the constructor of CFileItem to fail out as it tries to de-reference a null object.

I am unclear on what the expected behavior is.  It seems as if in this case OnPlayBackStarted already has the correct object?

The debug log is a bit misleading as the crash is in a copy constructor.

### To Reproduce

1.  create stacked bluray iso using naming convention from https://kodi.wiki/view/Naming_video_files/Movies modifying with advanced settings does not change behavior of crashing.
2. I am using the style "Movie (1999) bluray disc1.iso" and "Movie (1999) bluray disc2.iso". 
3. both are in a folder named "Movie (1999)"
4. pick movie to play
3. pick either play title or show bluray menu, either will cause crash

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/ewoyajoxug.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: windows 10
 - Kodi version: 18.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lharms** [comment] 2019-04-26 02:53
So looks like it still does this in 18.2.  I think CGUIDialogSimpleMenu::ShowPlaySelection is doing something odd.  I think this would only happen if the bluray is an ISO.  This method seems to reset the m_strPath back to the original stacked string that had already been decoded.  I am unclear why it is resting it.

**Comment by lharms** [comment] 2019-09-04 01:03
Tried something slightly different.  But I do not like it.  In 
CFileItem::operator=(const CFileItem& item)
I changed the bail out to this.
if ((this == &item) || (&item == nullptr))

Ideally it would not pass in null at all.  Oddly it seems to work.  Probably should have an assert here, but at least not crash.

**Comment by lharms** [comment] 2022-03-05 21:15
This appears to be fixed in 19.4 was still broken in 19.3

**Comment by enen92** [comment] 2022-03-05 21:23
Marked the issue as obsolete and will be probably closed in the next days. It was not clear if you can't reproduce the issue anymore, if so please close it.

**Closed** 2022-03-06 01:53 UTC
Labels: Issue Cleanup: Obsolete
