### ISSUE TITLE
Samsung Smart TV (from 2017) can see kodi-20.3-nexus DLNA, but wont see any content.

### ISSUE THREAD

**Issue by misanthropos** [xbmc/xbmc#22828] opened 2023-02-19 21:14 UTC
## Bug report or rather regression?
Samsung Smart TV sees DLNA on kodi-20.3 but can not retrieve any lists (content).
### Describe the bug
Here is a clear and concise description of what the problem is:
While other devices can see and stream from kodis DLNA, the Samsung TV does not retrieve any content lists (latest Firmware is from 2022).
The same Samsung TV however can see and stream content from a miniDLNA server, as well as from kodi-19.5. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The TV should receive DLNA media and in return be able to stream them.

## Actual Behavior

The TV sees the DLNA-server but wont get any media entries (content)

## Possible Fix
It seems legacy folders have been dropped.
So the solution would seem to reenable legacy folders.

The problems seems to affect other OSes too. See: 
[on reddit](https://www.reddit.com/r/kodi/comments/113qeki/updated_to_kodi_20_and_now_my_samsung_tv_shows_no/)

Somewhere between kodi-19.5 and kodi-20.3 has been changes made to the DLNA server, which in turn made streaming impossible.

### Debuglog
at:
http://sprunge.us/HexijV

with upnp component and libcurl enabled..
```

### Your Environment
Used Operating system:
Kodi-20.3 runs on self built LibreELEC devel-20230206105220-6783302 (RPi4.arm).
Samsung Smart TV from 2017 (probably Tizen)
Kodi-19.5 runs on a Gentoo machine, same for minidlna-1.3.2-r1

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

**Comment by enen92** [comment] 2023-02-19 21:27
Provide a full debug log with upnp component and libcurl enabled...

**Comment by misanthropos** [comment] 2023-02-20 08:19
> Provide a full debug log with upnp component and libcurl enabled...

Thank you for that information. It was unclear to me before, what you needed. I have updated the report with a full log.

**Comment by enen92** [comment] 2023-02-20 11:09
Thanks. It looks you hit some really old code path :)
I'd like to help but without some similar client device where I could debug this it's pretty much shooting in the dark.

**Comment by enen92** [comment] 2023-02-20 11:12
Maybe you can use tcpdump to intercept packets on your Linux box while trying to list directory contents on your TV. That hopefully can help mimic the same requests your TV is doing on any Kodi device

**Comment by misanthropos** [comment] 2023-02-20 13:41
Thank you for picking this up. 
Here you go:
[tizen.zip DLNA pcap requests](https://github.com/xbmc/xbmc/files/10784943/tizen.zip)

**Comment by enen92** [comment] 2023-02-20 16:00
@misanthropos sorry, leading nowhere since your tv does not issue any other requests. Can you possibly provide a debug log file (and a pcap capture) of this working in 19.5?

**Comment by misanthropos** [comment] 2023-02-20 17:14
@enen92 you bet I can :-), hopefully you can find something useful in here.
[kodi-19.5.zip](https://github.com/xbmc/xbmc/files/10786583/kodi-19.5.zip)

**Comment by misanthropos** [comment] 2023-02-20 17:30
@enen92, sorry, second attempt. Forgot to filter per host.
[kodi-19.5.zip](https://github.com/xbmc/xbmc/files/10786697/kodi-19.5.zip)

**Comment by enen92** [comment] 2023-02-20 23:47
@misanthropos comparing the pcaps I think [this change](https://github.com/enen92/xbmc/commit/0a7eaf90eb1b7acc3d7636894503cc7e0070240e) might fix the issue.

**Testbuilds (android):**

Android ARM: https://jenkins.kodi.tv/view/All/job/android-arm-docker/lastSuccessfulBuild/artifact/kodi-20230220-0a7eaf90-upnp_tizen-armeabi-v7a.apk
Android ARM64: https://jenkins.kodi.tv/view/All/job/android-arm64-docker/lastSuccessfulBuild/artifact/kodi-20230220-0a7eaf90-upnp_tizen-arm64-v8a.apk

If you could give it a spin (any will do) it's appreciated.
Cheers

**Comment by misanthropos** [comment] 2023-02-21 06:16
@enen92 It looked very good.... at first glance :-)

Music Library and Video Library are shown now and can be entered and does show for e.g.: Upper Folder, TV Shows, Playlists, Movies, Files. But entering any of listed Entries comes up empty. I rechecked with VLC on a mobile and it does work there.

Here are the logs for kodi with your patch:
[upnproot-kodi-20.zip](https://github.com/xbmc/xbmc/files/10790067/upnproot-kodi-20.zip)

**Comment by enen92** [comment] 2023-02-21 10:39
Thanks for the "sort of" good news. Unfortunately it looks like the pcap you provided for 19.5 does not contain any entry where you try to browse one of the inner folders (while it seems in your last pcap - using my patch - you have an attempt to browse the Movies Folder).
Ideally we need 2 pcaps of the exact same procedure on a working version vs non-working version (ideally my patch since it fixes part of the problem already). Would you be kind to get those?

root-> Video Library -> Movies : should be sufficient

**Comment by misanthropos** [comment] 2023-02-21 10:59
Hey @enen92 you bet I will provide that :-)

I went as far as starting a movie. If you would give me a hint on what to look for I`d be happy to assist.
[kodi-19.5-movie.zip](https://github.com/xbmc/xbmc/files/10792775/kodi-19.5-movie.zip)

**Comment by enen92** [comment] 2023-02-21 22:03
@misanthropos thanks! I guess this is a fallback from (cc @ksooo) changes regarding which items are folders and which not. I think the issue will get solved with https://github.com/enen92/xbmc/commit/c5c1682fcf1203845ccfc41121d017eeacc6e736

**Testbuilds:**

**Android ARM:** https://jenkins.kodi.tv/view/All/job/android-arm-docker/lastSuccessfulBuild/artifact/kodi-20230221-c5c1682f-upnp_samsung-armeabi-v7a.apk

**Android ARM64:** https://jenkins.kodi.tv/view/All/job/android-arm64-docker/lastSuccessfulBuild/artifact/kodi-20230221-c5c1682f-upnp_samsung-arm64-v8a.apk

If possible please test both video and audio library (might have missed something since I'm simulating the same type of requests).

**Comment by misanthropos** [comment] 2023-02-22 14:25
@enen92 thank you for your patch. It does make it work.... partially. Still... kudos to you :-) we are on the right track!

As you suspected there still are some problems:

- Music Library: will show Artists, Year, Albums, Top 100 etc... but all of those entries are empty, when selected.

[music-top-100.zip](https://github.com/xbmc/xbmc/files/10804722/music-top-100.zip)

- Video Library: I can see movies and stream them.
  There are still some problems though.
  - Video Library -> Files is empty
  - Any Video Library -> series -> TV Shows -> Titles -> NameOfShow -> Season x
    will show as many empty leaves, as the show has for that season. Trying to
    navigate to those leaves will crash the TV dlna client.
  - Same goes for any other attempt to watch a TV show.

**Comment by enen92** [comment] 2023-02-22 14:43
Care to explain what you mean with:

>> Any Video Library -> series -> TV Shows -> Titles -> NameOfShow -> Season x
will show as many empty leaves, as the show has for that season.

What does this look like? You mean you get listed as many folders as the number of episodes on that season? How are those "leaves" (folders) named?

**Comment by misanthropos** [comment] 2023-02-22 14:48
> 

![photo_2023-02-22_15-47-16](https://user-images.githubusercontent.com/1692172/220658032-cbf20e62-f1cf-4839-9311-cafed17a04e8.jpg)

**Comment by enen92** [comment] 2023-02-22 20:18
>> And some other oddity is this: Top 100 Albums renders empty for both 19.5 and 20 for any DLNA client, while Top 100 Songs works (except for the Samsung of course). 

This is likely a different issue not related to upnp. Can you confirm the top100 albums library node lists anything on the kodi gui itself?

**Comment by misanthropos** [comment] 2023-02-22 21:03
> > > And some other oddity is this: Top 100 Albums renders empty for both 19.5 and 20 for any DLNA client, while Top 100 Songs works (except for the Samsung of course).
> 
> This is likely a different issue not related to upnp. Can you confirm the top100 albums library node lists anything on the kodi gui itself? It doesn't for me

You are right! It does´nt for me either. Sorry for distracting.

**Comment by enen92** [comment] 2023-02-22 22:47
The issue for the music library should be fixed by updating the old commit with [this commit](https://github.com/enen92/xbmc/commit/6f0d96b128668d8b7b38997eec92a0bc4a04b6c0)

Regarding the TVShow/Episode issue I am getting the impression the samsung app just supports basic types as shown in the spec:
<img width="450" alt="image" src="https://user-images.githubusercontent.com/7375276/220774756-b7cf3585-9d6f-4e70-b4bb-b33bf1b7e841.png">
Kodi uses a few other types to represent seasons/shows/episodes such as `object.container.album.videoAlbum.videoBroadcastShow` or `object.container.album.videoAlbum.videoBroadcastSeason`. I think those can be considered "vendor" defined. The fact the recently added episodes work but under seasons/shows doesn't backup the idea.
As a result I added the samsung user agent to the list of quirks [in this commit](https://github.com/enen92/xbmc/commit/7f5c291395d1245a2c10b776cc784083b21e11e4)

Branch with the two commits: https://github.com/enen92/xbmc/commits/upnp_samsung

Please report back :)

------

**Testbuilds:**
https://jenkins.kodi.tv/view/All/job/android-arm-docker/lastSuccessfulBuild/artifact/kodi-20230222-7f5c2913-upnp_samsung-armeabi-v7a.apk

https://jenkins.kodi.tv/view/All/job/android-arm64-docker/lastSuccessfulBuild/artifact/kodi-20230222-7d476794-PR22841-arm64-v8a.apk

**Comment by misanthropos** [comment] 2023-02-23 09:06
@enen92 this is quite a mixed bag I daresay.

Regarding Music Library:
working:
- Music Lib -> Songs
- Music Lib -> Top 100 -> Songs
- Music Lib -> Albums -> Album x
- Music Lib -> Recently played -> Albums -> Album x

NOT working (empty entries - like photo of blackmirror season 3):
- Music Lib -> Playlists
- Music Lib -> Original year -> year x -> album x
- Music Lib -> Compilations -> album x
- Muisc Lib -> Genres -> genre x -> artist x -> album x

working:
- Video Lib -> Movies -> Titles
- Video Lib -> Movies -> Recenty added
- Video Lib -> Movies -> Genre -> genre x
- Video Lib -> Movies -> Years -> year x

Here is an interesting observation:
Going to Video Lib -> Files some Directories work while others have empty entries.
I have made a case for 12 angry men (+me) :-)

- Video Lib -> Movies - Years - 1957 - 12 angry men WORKS
- Video Lib -> Files -> movies -> Directory of 12 angry men: EMPTY entry

[12angrymen.zip](https://github.com/xbmc/xbmc/files/10811915/12angrymen.zip)

- Video Lib -> TV Shows still only works for recently added.

Summary: We are improving!!

**Comment by misanthropos** [comment] 2023-02-23 13:08
> Sorry, getting a bit lost. Which of the above issues works flawlessly in v19.5 and are broken in v20+current patchset? 

No wonder! Sorry, I did not recheck functionality on 19.5. I never bothered to use kodis DLNA until recently on LibreELEC because of some locally downloaded files on LibreELEC which I wanted to see on the TV.

- TV Shows does not work for 19.5 either, except for recently added.
- Movie Lib -> files just shows "movies" in 19.5 and that contains no entries at all. So your patch is a BIG improvement :-)

Since I only get the first 200 Albums and no Compilation is within, I got to one though recently added.
Here are the pcaps:
[purefitness.zip](https://github.com/xbmc/xbmc/files/10813733/purefitness.zip)


12 Angry Men resides in: '12 Angry Men (1957) [BluRay] [1080p]/' - so the brakes might be the issue here. Time to file a sperate issue then ;-)

Cheers.

**Comment by misanthropos** [comment] 2023-02-24 06:58
Thanks a bundle, @enen92!!! This makes me really happy.

**Comment by enen92** [comment] 2023-02-24 09:48
@misanthropos I did a few tests last night and manage the reproduce all issues on my TV as well (Philips) ...facepalm.

I have code that fixes them, the root cause of the issues is precisely the way we use object IDs/parent IDs. We use the Kodi vfs URLs directly (sometimes with a bunch of options, sort methods, etc) and I assume most of the parsers don't really like that. I solved it by using base64 for all paths.
Code is PoC ATM and needs to be properly done for submission, it will take me a bit of time to implement and submit.

Please keep the issue open in the meanwhile. Also there's no need for the Samsung quirk in the last patch set. Not also that usually libreelec consume directly from this repo, so the usual workflow is getting into Kodi and then libreelec syncs.

**Comment by misanthropos** [comment] 2023-02-25 08:20
> I solved it by using base64 for all paths. Code is PoC ATM and needs to be properly done for submission, it will take me a bit of time to implement and submit.

@enen92 sure thing! Please do not hesitate to ask me for some tests if needed.
In the meantime - could you share your base64 approach somewhere?

**Comment by enen92** [comment] 2023-02-25 13:14
@misanthropos found some time to cleanup my PoC. Please use: https://github.com/enen92/xbmc/commit/225a62601e3d705d17c6c5d156164c7bf91c563e for b64 encoded object ids.

Note you also need the other commit from the other pull request: https://github.com/enen92/xbmc/commit/6dd79a8c49f19c6fca40c3504d0cfd599abf41d9

Branch with the 2 commits: https://github.com/enen92/xbmc/commits/upnp_base64

Please let me know any feedback :) Hopefully fixes all the pending issues you've reported. At least it does for me :)

**Comment by misanthropos** [comment] 2023-02-25 20:10
> Please let me know any feedback :) Hopefully fixes all the pending issues you've reported. At least it does for me :)

@enen92 this is awesome! Not only did you fix those issues but now even cover art for video and music are shown!

**Comment by enen92** [comment] 2023-02-25 21:20
Great! Regarding artwork Kodi seems to be sending the artwork in duplicate (one entry with localhost and another with the LAN IP address). Doesn't cause any harm but might be a bug somewhere (not introduced here).
I'll push the changes at some point tonight. Thanks for the help debugging and providing the info in this thread. Appreciated.

**Closed** 2023-03-20 20:04 UTC
Labels: Triage: Confirmed, Triage: Has proposed fix, v20 Nexus, Component: UPnP, v21 Omega

**Comment by dmig** [comment] 2023-04-20 17:34
Sorry for resurrecting this,
but I just installed version 21.0+git20230413.0301-53001491bc-0~kinetic from nightly PPA and tried streaming to my old Samsung TV.

Got results similar to [mentioned in comment](https://github.com/xbmc/xbmc/issues/22828#issuecomment-1440115681):
- TV can see Kodi
- selecting _Videos_/_Music_ on TV shows following empty folders
  - Music Library
  - Video Library
- selecting _Photos_ displays also _Discs_ and _Playlists_ in _Music Library_, also empty
- navigating up/back from _Video Library_ causes TV to show error "Request cannot be completed. MEDIA PLAY will return to the main screen." (a crash?)

I believe, this should be a similar or same bug.

**Comment by misanthropos** [comment] 2023-04-25 17:40
@dmig - I tried to reproduce your findings but it works both on a Samsung TV from 2017 and a Philips TV from 2018.
I have an older Philips TV which generally works with kodis DLNA but I found a glitch: 
   Video Library -> Series -> Titles ->  Title x -> No playable files in that folder!!!
The TV in questions is a 42PFL6075K12 from 2012.

**Comment by enen92** [comment] 2023-04-25 18:16
@dmig sure help is appreciated. 
Did it work before? (E.g Kodi 20)
My guess is that your TV doesn't really support rich metadata from UPnP (or simply has a limited object type support). Do "Movies" get listed and play fine?

**Comment by dmig** [comment] 2023-04-25 18:37
Can't test on Kodi 20.1 from PPA, because of broken dependencies -- only nightly installs properly. Rygel and Serviio working fine -- some media is accessible.

> "Movies" get listed and play fine?
Movies is empty. Pressing 'up' or back causes TV to show error message (see previous comment).

**Comment by dmig** [comment] 2023-04-25 18:46
One interesting detail: a lot of whitespace around folders (look at scrollbars)
![IMG_20230425_203408_25](https://user-images.githubusercontent.com/388564/234373531-43e12f8f-80b1-40a8-820e-d75786e63352.jpg)
