### ISSUE TITLE
Crashing Kodi everytime Internet Game Archive Launcher IGAL

### ISSUE THREAD

**Issue by BullShark** [xbmc/xbmc#18062] opened 2020-06-15 06:09 UTC
### Describe the bug

Trying to launch any Nintendo 64 game from IAGL add-on in Kodi results in Kodi crashing.

## Expected Behavior

Launch the game in mupen64 emulator after downloading the game.

## Actual Behavior

Crashes Kodi with a seg fault

## Possible Fix

I suspect that the addons work without crashing Kodi in older versions of Kodi.

### To Reproduce
Here's the steps I took.

Install all of these using yay.

Install kodi-x11
Install kodi-addon-game-libretro
Install kodi-addon-game-libretro-mupen64plus

Download the IAGL zipfile

In Kodi:

Add the zipfile to get the repo.
Install IAGL from the new repo.
Install Nintendo 64 Controller
Nintendo - Nintendo 64 (Muphen64Plus)
Install IAGL - Internet Archive Game Launcher

In Kodi:

IAGL -> Browse All Lists -> Internet Archives Best Of N64 -> The Legend of Zelda - Ocarina of Time or 007

It seems to happen with every Nintendo 64 game.

Results:
Crashes Kodi every time.

```
$ kodi --debug
/usr/bin/kodi: line 219: 349385 Segmentation fault      (core dumped) ${KODI_BINARY} $SAVED_ARGS
Crash report available at /home/bullshark/kodi_crashlog-20200615_004443.log
```

Is the save file being opened before checking if it exists? And a save file is expected the first time a game is ran when there has been no saves.

> 2020-06-15 00:44:38.748 T:140704015163264   ERROR: Failed to open savestate file /home/bullshark/.kodi/userdata/addon_data/plugin.program.iagl/temp_iagl/Legend of Zelda, The - Ocarina of Time (USA) (Rev B).sav
> kodi_crashlog-20200615_004443.log

Edit:

Here's another crash log after I installed gdb.
kodi_crashlog-20200615_005007.log

http://odin.root.sx/kodi_crashlog-20200615_005007.log

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

Just before the crash:

![Screenshot_20200615_072724](https://user-images.githubusercontent.com/1526595/84657534-09476980-aeda-11ea-8d63-356ae3cb6bb2.png)

The crash happens immediately after the download for any N64 game.

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment

Used Operating system:
Manjaro Linux with KDE latest.

```
$ uname -a
Linux plasma 5.7.0-3-MANJARO #1 SMP PREEMPT Wed Jun 3 03:15:33 UTC 2020 x86_64 GNU/Linux
```

 - Operating system version/name:
 - Kodi version:

```
$ kodi --version
18.7 Git:20200603-nogitfound Media Center Kodi
Copyright (C) 2005-2020 Team Kodi - http://kodi.tv
$ pacman -Q | grep kodi
kodi 18.7.1-3
kodi-addon-game-libretro 1.1.1-5
kodi-addon-game-libretro-mupen64plus 2.5.0.6-14
kodi-addon-visualization-projectm 1:2.2.0-15
kodi-platform 20190726.809c5e9-10
kodi-x11 18.7.1-3
$ 
```

**Comment by BullShark** [comment] 2020-06-15 12:36
Please remove the ignored rules. I updated the bug report to use the template.

**Comment by DaVukovic** [comment] 2020-06-15 19:04
You have banned add-ons installed. Please remove them first and provide a new log if the issue still exists

**Comment by BullShark** [comment] 2020-06-15 21:52
![Screenshot_20200615_165024](https://user-images.githubusercontent.com/1526595/84709851-94e7e700-af28-11ea-8f33-81703ff16cea.png)

**Comment by flubshi** [comment] 2020-06-16 22:19
N64 / mupen64 requires OpenGL context, which is not (yet) implemented in Kodi. 

Duplicate of https://github.com/xbmc/xbmc/issues/15874

**Comment by BullShark** [comment] 2020-06-17 04:35
Is it possible to launch retroarch externally for N64 / mupen64? I've been trying. I even made a wrapper script for Kodi to call so the -L option is passed to retroarch. But the debug lines never get printed like the script was never called. I tried calling on retroarch directly from Kodi too with no luck.

```
$ cat bin/retroarchw 
#!/bin/bash
# retroarchw - retroarch wrapper
#
# Used by Kodi with IAGL external launcher
#
# Determine the file-type and load the libretro library
# Example:
#   Load mupen64plus_next_libretro.so or parallel_n64_libretro.so when the filetype is n64

# libretro libraries
#desmume_libretro.so  
#dolphin_libretro.so  
#mednafen_psx_libretro.so  
#melonds_libretro.so       
#mupen64plus_next_libretro.so
#parallel_n64_libretro.so

echo "args: $@" >> ~/kodi-retroarch.log
echo "date: $(date)" >> ~/kodi-retroarch.log
echo "command: retroarch -f -L /usr/lib/libretro/parallel_n64_libretro.so $@" >> ~/kodi-retroarch.log

retroarch -f -L /usr/lib/libretro/parallel_n64_libretro.so "$@"
```

**Comment by DaVukovic** [comment] 2020-06-17 05:38
As this is a duplicate (thanks @flubshi ), I will close this issue. 

Please use the forums for further discussion.

**Closed by DaVukovic** 2020-06-17 05:38 UTC
Labels: Ignored rules, Triage: Needed
