### ISSUE TITLE
"back" action also exits fullscreen video intead of just closing "Info" window

### ISSUE THREAD

**Issue by bam80** [xbmc/xbmc#16876] opened 2019-11-06 18:09 UTC
### Describe the bug

If `Info` action invoked while in Fullscreen video mode, `Back` action seem handled incorrectly - instead of just closing the "Info" window, it exits Fullscreen video too.

## Expected Behavior

"Info" window should just be closed.

## Actual Behavior

Both "Info" window and Fullscreen windows are closed.

## Possible Fix

The possible cause of this is `Back` seems handled in underneath Fullscreen window instead of Info window.

### To Reproduce

1. Run fullscreen video
2. Open Info (`i` key)
3. Try to close Info with `Back` button. Note you'll leave Fullscreen mode.

### Debuglog

http://ix.io/2101

### Screenshots 

"Info" is opened:
![screenshot000](https://user-images.githubusercontent.com/233979/68324614-c8cc7580-00d8-11ea-9990-c4e706892066.png)

`Back` button pressed:
![screenshot001](https://user-images.githubusercontent.com/233979/68324693-f0234280-00d8-11ea-8851-b69072a7d66a.png)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: CoreELEC
 - Kodi version: 18.4

**Comment by ronie** [comment] 2019-11-07 22:35
i can confirm the behavior you're seeing, though it's not really a bug.
the reason why `back` exits the fullscreen is that Estuary doesn't use the Info dialog.

it has moved the code that is responsible for showing the info stuff to SeekBar dialog instead.
since the SeekBar is a non-modal dialog, it cannot be closed by a `back` command.
therefor the `back` action indeed falls through to the fullscreen window.

so while technically everything does work as it should, i reckon it's not what a user would expect,
certainly not as the `back` action works fine in most other skins that do use the Info dialog.

**Comment by ronie** [comment] 2019-11-09 19:49
fixed by https://github.com/xbmc/xbmc/pull/16878

**Closed by ronie** 2019-11-09 19:49 UTC
Labels: Triage: Confirmed

**Comment by bam80** [comment] 2019-11-09 20:10
@ronie Thank you very much!
