### ISSUE TITLE
Wrong mime type for m2ts video in Kodi UPNP server

### ISSUE THREAD

**Issue by vip5912** [xbmc/xbmc#22994] opened 2023-03-17 10:20 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

Wrong mime type for m2ts video in Kodi UPNP server: video/m2ts.
Correct mime type: video/vnd.dlna.mpeg-tts.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I want to play m2ts video by BD player (Sony UBR-X700) from Kodi UPNP server.

## Actual Behavior

BD player (Sony UBR-X700) does not see this video but sees and plays mkv video from Kodi UPNP server.

## Possible Fix

Correct mime type for m2ts video in Kodi UPNP server: video/vnd.dlna.mpeg-tts.

Media Type 'video/vnd.dlna.mpeg-tts' Details:
This media type identifies audiovisual streams multiplexed using an extended MPEG-2 Transport Stream packet format.

I made the tests with the same m2ts video from Kodi, Plex and Emby UPNP servers.

Kodi UPNP server XML:

< res duration="0:47:12.000" resolution="1920x1080" protocolInfo="http-get:*:video/m2ts:*" > http : // 192.168.1.5:1782/%25/d29d7c1164e2eb9852f723f494204d15/file.m2ts < /res >

BD player does not see this video.

Plex UPNP server XML (the same from Emby):

< res duration="0:47:12.000" size="1389533184" resolution="1920x1080" bitrate="490500" nrAudioChannels="2" protocolInfo="http-get:*:video/vnd.dlna.mpeg-tts: DLNA.ORG_OP=01;DLNA.ORG_CI=0;DLNA.ORG_FLAGS=01500000000000000000000000000000" > http : // 192.168.1.5:32469/object/6ff06b80f68469b60739/file.ts < /res >

BD player sees and plays this video

Only Kodi UPNP client can see m2ts videos from Kodi UPNP server.

### To Reproduce

1. Add m2ts video to Library.
2. Try look and play this m2ts video by some UPNP player (not Kodi)

### Debuglog

The debuglog can be found here:
The problem is on non-Kodi players. No debuglog.

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
Ubuntu 22.04, Linux desktop 5.15.0-57-generic # 63-Ubuntu SMP Thu Nov 24 13:43:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
Kodi (20.1 (20.1.0) Git:20230312-289ec664e3). Platform: Linux x86 64-bit

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment] 2023-03-17 18:17
Thanks for reporting, should be fixed by the PR above.

**Comment by vip5912** [comment] 2023-03-17 18:33
> Thanks for reporting, should be fixed by the PR above.
Thanks for patch, I will test it later.

**Comment by jbinkley60** [comment] 2023-03-18 08:34
I have been researching this issue a bit and trying to follow the libplatinum mimetypes code but it's been awhile since I've done C++ coding and I haven't been able to totally follow the code.  I was trying to determine what the associated mime type will be after the PR for .ts and .m2ts file types (i.e. video/vnd.dlna.mpeg-tts or video/mpeg ) ?   I ask this because I have a listing of almost 400 DLNA device type profile mappings, of which 70 are for various Sony devices)  and the majority map ,ts and .m2ts to video/mpeg.  I don't know if Plex or Emby that were quoted attempt to match device types for DLNA or have a fixed response.  Looking at my Plex instance I tend to believe it is fixed.   Anyway, my point is that for maximum DLNA compatibility a video/mpeg might be the most appropriate, if the Kodi response is fixed and the libplatinum mimetypes framework doesn't attempt to match the DLNA source.  My apologies in advance, if this isn't the place for this discussion.  Just trying to help.

**Comment by enen92** [comment] 2023-03-18 10:43
@jbinkley60 after PR we:

1st) Look into our overrides map: https://github.com/xbmc/xbmc/pull/22996/files#diff-90b84f7909dc11c8e754b4ed6c61eebc9ed6b81b9e78a377ab89ce423a0c3f82R66

2nd) If not found we look into platinum dlna mimetype definitions (which is quite a small map if not using some "quirky" client like xbox/sonos, etc): https://github.com/xbmc/xbmc/blob/master/lib/libUPnP/Platinum/Source/Core/PltMimeType.cpp#L47-L55

3rd) If not found here we use kodi global mimetypes: https://github.com/xbmc/xbmc/blob/master/xbmc/utils/Mime.cpp#L21-L515

4th) If at this point it is not found we return "video/ + extension", "image/+extension", "audio/+extension": https://github.com/xbmc/xbmc/blob/master/xbmc/network/upnp/UPnPInternal.cpp#L159-L168

----

So, after PR:
- For m2ts we return `video/vnd.dlna.mpeg-tts` (we hit 1st node)
- For ts we return `video/mp2t` (we hit 3rd node)

I've tested both cases with my tv client and both work fine.

**Comment by jbinkley60** [comment] 2023-03-18 12:13
Thanks for the detailed explanation.  You answered my questions about whether this is a global setting (i.e. fixed) or if you attempt to identify the requesting source device type (i.e. signature code in in 2nd check).  I don't expect you'll have many issues with the change.  There may be some older clients which would prefer  video/mpeg vs.  video/vnd.dlna.mpeg-tts.  

My reference point for the discussion is Mezzmo's DLNA server which leverages external (not hard coded) XML profile files which are read in by the server and attempts to match all of the client attributes (i.e. mime type, when to transcode, bitrates, buffering, and much more) for maximum compatibility.  You can assign a specific profile to a client, if the automatic discovery doesn't find a desirable match.  It has almost 400 device profile files but only one for Kodi clients !!!   (70 for various Sony devices <sigh>)  I looked through a bunch of them and saw the mime type for .ts and .m2ts was video/mpeg but a lot of the profiles are for older devices which have less audio /  video codec support vs. major mime type issues.  A few of the newer profiles had video/vnd.dlna.mpeg-tts.

I have a few other DLNA clients and can test the PR.

**Comment by enen92** [comment] 2023-03-18 12:35
Yeap, on an ideal world our quirks would also be treated that way, with profiles for clients. Maybe we can later improve this too.
Testing the PR with your old clients would be nice.

**Comment by jbinkley60** [comment] 2023-03-18 14:16
The best way to get them is to pull down a [version of Mezzmo](http://www.conceiva.com/downloads/default.asp), install it on a Windows machine and then grab the profile directory (\ProgramData\Conceiva\Mezzmo\DeviceProfiles )  which has all 370+ profiles.  You can always uninstall Mezzmo afterwards.  The profile files are in XML format.  

I have a Samsung TV where I can reproduce the UPnP m2ts issue with Kodi.  I tested with Kodi 18.9 and see the issue.  But I also  have Kodi 19, 20 and 21 running that I can test with too.  Is the PR fix for 20 or 21 and where is it located ?

Jeff

**Comment by vip5912** [comment] 2023-03-18 15:07
@enen92
I tested your PR #22997.
I appled your patch (f2290777cb5b78c4454dfbdbfdaa4b64706d2d72) to Kodi 20.1 (20.1-Nexus),
built test Kodi 20.1 (on VM based Ubuntu 22.04, Wayland) and tested m2ts video.
It's working well with my BD player (Sony UBR-X700). I can see this video and play it.
Thank you.

**Comment by enen92** [comment] 2023-03-18 15:11
@jbinkley60 http://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20230318-1d91f074-upnp_mime-x64.exe

**Comment by jbinkley60** [comment] 2023-03-18 18:24
@enen92 I tested 2 Samsung TV clients with Kodi 20.1 and 20.1 with the mime patch and m2ts files.  Both are 10 year old TVs:

```
Model                       UN46F6300AF                           UN65F9000AF
Kodi 20.1                      Yes                                     No
20.1 patched                   Yes                                     Yes
```

As you can see one of them played fine before and after.  The other displayed and played the m2ts file after the mime patch.


Jeff

**Comment by vip5912** [comment] 2023-03-19 09:57
@enen92
As an option you can (in future) make user custom UPnP mime types like
[https://github.com/xbmc/xbmc/pull/6179](url)

**Closed** 2023-03-19 10:24 UTC
Labels: Triage: Confirmed, Triage: Has proposed fix, v20 Nexus, Component: UPnP, v21 Omega
