### ISSUE TITLE
[Linux] Two cursors are visible on KDE Plasma Wayland session

### ISSUE THREAD

**Issue by glaubersm** [xbmc/xbmc#15002] opened 2018-12-06 11:48 UTC
### Describe the bug

two cursors are visible when I hover over kodi running natively under Wayland on KDE Plasma desktop environment, see the screenshot please. Such problem does not occur under Gnome Wayland session.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

only one cursor should be visible.

## Actual Behavior

two cursors are visible when I hover over kodi running natively under Wayland on KDE Plasma desktop environment, see the screenshot please.

### To Reproduce

1. use any linux distribution running KDE Plasma desktop environment on Wayland (I tested both Arch Linux and Neon developer unstable and got the same results)
2.  install kodi 18 RC2 via flatpak/flathub
3.  open kodi, mouseover its window

### Debuglog

The debuglog can be found here:
http://paste.kodi.tv/acojusiluz

### Screenshots 
Here are some links or screenshots to help explain the problem:

![kodi](https://user-images.githubusercontent.com/15967631/49581336-b41bb680-f938-11e8-8d8b-56b99dccecb1.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Arch Linux and Neon developer unstable.
 - Kodi version: 18 RC2 installed via flatpak/flathub

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by pkerling** [comment] 2018-12-06 12:18
Verified.

Probable cause: Kodi uses two pointer objects (extra one for decoration handling) and KDE handles this case differently from GNOME.
Not sure what the best action is. Maybe long-term it might be better to only use one pointer object.

**Comment by FernetMenta** [comment] 2018-12-06 15:40
@pkerling I saw a similar report for X11. Slightly different though, OS pointer shows but Kodi's pointer not. There was not even a mouse attached to the system.

Are you sure that it is no Kodi issue? Maybe some component calls ShowOSMouse from other than main thread. Most related changes were in InputManager and peripherals.

**Comment by pkerling** [comment] 2018-12-08 11:50
@FernetMenta Yes, I'm positive it's a Wayland/KDE issue. Not to say that the input handling on the Kodi side is completely correct either (for example it still shows the Kodi cursor even after leaving the window, which was not the case when I implemented the Wayland integration), but it's unrelated to this bug.

@glaubersm The two pointer objects are not the problem, I tested by disabling one of them. Wayland debug logs show that the cursor image is set to null, which according to the specification means that the cursor has to be hidden. KWin does not do this for whatever reason - it works on GNOME and Weston. I recommend you to retry with the latest possible version of KWin (preferably built from Git master) and if your problem persists report it to the KDE people.

**Comment by glaubersm** [comment] 2018-12-09 22:06
it's not a kde software bug
https://bugs.kde.org/show_bug.cgi?id=401921#c5

**Comment by fritsch** [comment] 2018-12-10 05:20
Read again :-)

**Comment by pkerling** [comment] 2018-12-10 09:47
@glaubersm For me the problem was only with nested mode (running KWin on top of another compositor). With a full session I can now confirm that fixing the double wl_pointer makes the cursor disappear. So I'll try to get that done in Kodi.

**Comment by pkerling** [comment] 2018-12-13 12:42
@glaubersm Please try #15052

**Comment by glaubersm** [comment] 2018-12-19 10:55
I have just updated kodi from flathub.
Cursor is still duplicated, now I see a cursor in edit mode and an arrow.

**Comment by pkerling** [comment] 2018-12-19 11:09
You have to build from source

**Comment by pkerling** [comment] 2018-12-19 11:12
@wsnipex I guess there's no easy possibility to have flatpak test-builds atm?

**Comment by wsnipex** [comment] 2018-12-19 11:16
not for kodi PRs. You'd have to PR that patch against the flathub repo, then the flathub bot could build it.

**Comment by pkerling** [comment] 2018-12-23 18:03
Should be fixed in rc4

**Closed** 2018-12-23 18:03 UTC
Labels: Linux, v18 Leia

**Comment by glaubersm** [comment] 2019-01-06 12:53
I can confirm that the bug is fixed in RC4. Thank you guys.
However cursor movements are not smooth, cursor lags a lot under KDE Plasma wayland session.
Should I open a new bug or it's a known bug?

**Comment by pkerling** [comment] 2019-01-06 13:00
It should definitely not lag "a lot", not more than on X11 anyway. Can you compare?

**Comment by glaubersm** [comment] 2019-01-06 13:11
Cursor movements are correct under X11.
Under Wayland cursor takes some miliseconds to move itself when I move my mouse.

**Comment by pkerling** [comment] 2019-01-06 13:12
Can you reproduce with other compositors (weston, mutter)? (Running on gbm, not nested)

**Comment by glaubersm** [comment] 2019-01-06 13:33
No. Cursor movements are correct with both mutter (Gnome Wayland session) and weston.

**Comment by pkerling** [comment] 2019-01-06 13:48
Hmmm. That's curious. Martin Flöser (KWin developer) pointed out to use some other protocols for interaction, which I haven't gotten around to thoroughly investigate yet, so I don't know whether that would solve your problem. Before we get there, two more tests:

* Can you reproduce when the debug overlay is enabled in Kodi? (That actually causes drawing at maximum frame rate as side-effect)
* Can you reproduce with any other native Wayland application that has a custom cursor, such as a GLFW-based game? I can search for one if you're not sure.

**Comment by glaubersm** [comment] 2019-01-06 14:20
The problem is not as noticeable when the debug overlay is enabled, but it persists.

Please indicate some GLFW-based game for me. I do not know any.

**Comment by pkerling** [comment] 2019-01-07 10:45
Hm, on a quick search I also did not find much, and the examples do not have a custom cursor. I suggested GLFW because I know it implements the relative-pointer protocol. Anyway, then let's try SDL2. For example SuperTux. Start it with `SDL_VIDEODRIVER=wayland` env var set and verify that it's using Wayland.

**Comment by glaubersm** [comment] 2019-01-07 13:12
Unfortunately I can't run supertuxkart natively under Wayland even after set the environment variable.
I tried on two different distributions.

**Comment by pkerling** [comment] 2019-01-07 21:35
> Unfortunately I can't run supertuxkart natively under Wayland

I was talking about SuperTux :-) https://www.supertux.org/

**Comment by glaubersm** [comment] 2019-01-07 21:51
Sorry lol
Cursor is duplicated when I run supertux natively on Wayland, cursor movements are correct.

**Comment by pkerling** [comment] 2019-01-07 22:00
> Cursor is duplicated when I run supertux natively on Wayland

Hngngng :-/ This is problematic since I don't really want to start debugging SDL now :-D You're using the latest SDL2 version 2.0.9 I assume?

**Comment by glaubersm** [comment] 2019-01-07 22:22
Yes, SDL2 version 2.0.9.

**Comment by pkerling** [comment] 2019-03-25 10:07
I can't really reproduce this. For me, there is no discernible difference between running Kodi/X11 in a Plasma X11 session and running Kodi/Wayland in a Plasma Wayland session. The cursor in SuperTux2 on Wayland feels super snappy and it does not use the relative pointer protocol, so I don't think that would help. (I have to add that also on my laptop with newest Fedora, Plasma/Wayland is borderline usable. Subcompositing is not supported properly, you can't even move or resize the Kodi window and I get tons of graphical glitches)

I do feel that compared to SuperTux2, the Kodi cursor is a lot more sluggish (irrespective of the windowing system). That is probably rooted in our rendering having more delay between the event retrieval and its processing/rendering. Anyway, I think the way forward is probably to stop drawing the cursor ourselves. That will allow for the snappiest experience. At least if that doesn't gather significant opposition from skinners - @ronie @phil65 @MartijnKaijser what do you think about just using the OS cursor?

**Comment by ronie** [comment] 2019-03-25 10:21
i don't think skinners would mind.
there's generally little interest in adding mouse support to a skin in the first place.

so imo it's more important to find out what the user-base thinks about this.
two things that could be considered:
- the OS cursor is much smaller than the Kodi cursor, this might be less convenient when operating Kodi from a 'large' distance. 
- the Kodi cursor auto-hides after a few seconds of inactivity, can the same be accomplished with the OS cursor?

**Comment by pkerling** [comment] 2019-03-27 09:30
> the OS cursor is much smaller than the Kodi cursor, this might be less convenient when operating Kodi from a 'large' distance.

Maybe I should mention this: On most OSes (the ones I would make the switch on anyway), we actually can modify the cursor image, just not as a "skin window" like it is now. It'd have to be just a plain image. Easiest would of course be to just ship it with Kodi and not make it part of the skin.

> the Kodi cursor auto-hides after a few seconds of inactivity, can the same be accomplished with the OS cursor?

Yes.

**Comment by glaubersm** [comment] 2019-03-28 12:20
Here cursor movements are still problematic on KDE Plasma Wayland session.
It remais frozen during some milliseconds before it starts to move.
I use Kodi 18.1 installed on neon dev unstable distribution via flatpak/flathub.

**Comment by pkerling** [comment] 2019-03-28 14:45
Can't really reproduce here, at least not to a satisfying degree. I'll try with neon and the flatpak app, maybe the problem is somewhere else entirely. I was always trying with directly installed Kodi (no flatpak). Did you also try that?

Sidenote: you won't notice "some milliseconds" lag - one frame is already 17 ms at 60 Hz ;-)
On X11 the Kodi cursor should lag by around 3 frames (educated guess - it needs at least one round trip from X server to application plus you might have triple-buffering), so I don't think you would really be able to find a pronounced difference if it were only one frame of additional delay. I could be wrong though.

**Comment by glaubersm** [comment] 2019-03-28 17:40
I use Kodi on two computers.

Computer A is a laptop running Neon dev unstable. Kodi 18.1 installed from flathub was already mentioned, Kodi from neon repos is old, version 17.6, and I did not test it.

On computer B I have Arch Linux installed running KDE Plasma 5.15.3 desktop environment
and Kodi 18.1 installed from both Arch repos and flathub.
Kodi from Arch repos runs on Xwayland, not natively on Wayland and it is not affected by the problem with cursor movements. Kodi from flathub (running natively on Wayland) is affected
but the problem is less noticeable than on computer A.

**Comment by pkerling** [comment] 2019-03-28 17:50
> Kodi from Arch repos runs on Xwayland, not natively on Wayland and it is not affected by the problem with cursor movements. Kodi from flathub (running natively on Wayland) is affected
but the problem is less noticeable than on computer A.

The interesting comparison would be native Wayland vs. flatpak on that computer

**Comment by glaubersm** [comment] 2019-03-28 18:02
Yes, I know. But Wayland build is not available in Arch repos and unfortunately I do not know as compile source code and enable Wayland support.

**Comment by pkerling** [comment] 2019-03-28 18:16
I installed the Flatpak version on my dev machine. I clearly see the delay. So it's really a flatpak-specific problem.

@glaubersm Can you open a new issue so we don't continue hijacking this one? :-)

**Comment by glaubersm** [comment] 2019-03-28 18:21
neon is based on ubuntu 18.04, I have just installed kodi 18.1 via ppa repo
https://launchpad.net/~team-xbmc/+archive/ubuntu/ppa?field.series_filter=bionic

The same problem with cursor occurs despite kodi from such ppa runs on Xwayland.

**Comment by pkerling** [comment] 2019-03-28 18:34
Sorry, must have been imagining things. Can't reproduce on desktop. It seems to be a neon thing, I get the problem with both flatpak and native Wayland on neon.

> The same problem with cursor occurs despite kodi from such ppa runs on Xwayland.

It depends what you install. You have to look into the log to tell whether it's running X11 or Wayland.

**Comment by pkerling** [comment] 2019-03-28 18:45
> The same problem with cursor occurs despite kodi from such ppa runs on Xwayland.

Can you upload a debug log of that?

**Comment by glaubersm** [comment] 2019-03-28 19:11
The problem is less noticeable with Xwayland build from the ppa repo, but it exists.
I think you are right, it's a neon thing because it uses an old version of Xwayland.

I have just installed kodi-wayland from ppa repo, it is also affected by the problem with cursor movements.

**Comment by pkerling** [comment] 2019-03-28 19:19
> I think you are right, it's a neon thing because it uses an old version of Xwayland.

The Xwayland version should not affect the native Wayland Kodi though?

**Comment by glaubersm** [comment] 2019-03-28 19:35
I meant that the problem with Xwayland build from ppa repo is a neon thing because neon runs an old Xwayland version. Xwayland build works fine on Arch Linux running the latest Xwayland version. : )

**Comment by pkerling** [comment] 2019-03-29 07:27
I'm not sure it is. Since I see the same problem in all 3 variants on Neon (flatpak/via Xwayland/native), I think it is a general problem.

**Comment by wsnipex** [comment] 2019-03-29 08:18
install kodi-wayland from the ppa for a wayland native build

**Comment by glaubersm** [comment] 2019-04-30 14:37
Problem with cursor movements persists after update to Kodi 18.2 on Arch Linux.

**Comment by fritsch** [comment] 2019-04-30 18:09
Would it help you if we officially state that we don't support it?

**Comment by pkerling** [comment] 2019-05-01 06:29
> Problem with cursor movements on Plasma Wayland persists after update to Kodi 18.2 on Arch Linux.

What do you mean with "persists"? I thought you did not have this problem on Arch Linux before?

**Comment by glaubersm** [comment] 2019-05-01 18:45
The problem was already present on Arch running Kodi 18.1 from flathub natively on Wayland.
A Wayland build of Kodi 18.1 was not available in Arch official repos,
but now Kodi 18.2 also has a Wayland build
https://www.archlinux.org/packages/community/x86_64/kodi-wayland/
Both flathub and Arch builds of Kodi 18.2 run natively on Wayland and are affected by the problem with cursor.
