### ISSUE TITLE
TV Shows cannot be scraped from two separate folders at different resolutions

### ISSUE THREAD

**Issue by BRTPOB** [xbmc/xbmc#19956] opened 2021-07-09 10:06 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

When a user has two different quality versions of a TV show, such as 1080p or 720p and 2160p, only one of those will be scraped properly and added to the DB to be allows to be viewed. This leads to frustration if the user has both qualities and wants to split the qualities apart, while showing both in their respective libraries/playlists.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Expected both the 2160p and 1080p versions of the TV shows to show up in their respective Smart Playlists.

## Actual Behavior

Only the first TV show quality scraped will show up.

### To Reproduce

1. Create two TV Show folders: 2160p and 1080p.
2. Copy content from one show into both folders.
3. Attempt to scrape both versions of the show.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/isifegexur.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

https://vision.shovelbeating.com/s/qTD6YA7kkkio37B

With these screenshots, this is what I'm highlighting (in order):

1.     11.22.63 and 12 Deadly Days both missing from the 4K TV Shows list.
2.     The Mandalorian missing from the 4K TV Shows list.
3.     The Mandalorian mixing both 4K and HD episodes in the HD/SD TV Shows list.
4.     11.22.63 and 12 Deadly Days showing as not imported into the 4K TV Shows list, but showing in the Files structure list.
5.     Same with The Mandalorian as above.
6.     Ditto Queens Gambit.
7.     1983, A Discovery of Witches showing as not imported into the HD/SD TV Shows list, but showing under tv shows Files structure list, while they are properly showing in the 4K TV Shows list.
8.     Same with Absentia.
9.     Same with Alex Rider.
10.     Same with American Gods.
11.     Same with The Bad Batch.
12.     Highlighted Big Shot and Billions, as they're also affected.

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Linux Mint 20.1
 - Kodi version: 19.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by HitcherUK** [comment] 2021-07-09 11:28
Kodi doesn’t support multiple version of the same TV show.

**Comment by BRTPOB** [comment] 2021-07-09 11:30
OK, but it supports multiple versions of the same movie, so why is that disconnect in existence? That's the basis of this bug.

**Comment by KarellenX** [comment] 2021-07-09 21:05
Because TV Shows has been designed to find every episode of the tv show in a users folder structure and add them to the correct tv show. 

This is required for split folders. eg, you might progressively save The Big Bang Theory to one hard drive, but over a course of 12 years that hard drive is full, so you have added new episodes to another hard drive. Kodi finds those split episodes and combines them. It is _designed_ to do that, which is why you are having trouble splitting them.

1. If you want to split them into **two separate tv shows** then follow this post...
https://forum.kodi.tv/showthread.php?tid=349163&pid=2899429#pid2899429

2. If you want one tv show with duplicated episodes (which seems silly to me) then nothing special is required. Just scrape them as per normal.

It's not clear to me which one you want. Either way, this is not a bug so I will close this report.

Head over to the forum if you need help splitting.

**Closed by KarellenX** 2021-07-09 21:05 UTC
