### ISSUE TITLE
sys.executable returns /usr/bin/python on linux and C:\kodi\kodi.exe on windows

### ISSUE THREAD

**Issue by Cyber1000** [xbmc/xbmc#17228] opened 2020-01-20 00:22 UTC
### Describe the bug
Linux: sys.executable returns /usr/bin/python -> ok
Windows 10: C:\kodi\kodi.exe (the kodi.exe is returned) -> not ok

## Expected Behavior
I would expect to get the current python-interpreter with sys.executable, on linux this doesn't to seem a problem, on windows though I'm getting the kodi.exe itself.

For example I'm using ptvsd from microsoft to debug with vscode (https://github.com/microsoft/ptvsd). I can include this without problems in kodi, the only "problem" is it uses sys.executable.
Following gets executed (you have to read that as if it where in one line - C:\\kodi\\kodi.exe is read from sys.executable and is the program that gets called, the other lines are the parameters):

                 "C:\\kodi\\kodi.exe", 
                 "C:\\kodi\\portable_data\\addons\\script.module.ptvsd\\lib\\ptvsd\\adapter", 
                 "--for-server", 
                 "55569", 
                 "--host", 
                 "127.0.0.1", 
                 "--port", 
                 "5678", 
                 "--server-access-token", 
                 "805ca4eb629664f79d96aec76d654f43f0dd07fadf7927081392c900053a4562", 
                 "--log-dir", 
                 "C:\\kodi"

If I change C:\\kodi\\kodi.exe to C:\python38\python.exe and adjust PYTHONHOME/PYTHONPATH by hardcoding it in ptvsd, everything works fine on windows too.

## Possible Fixes
- let sys.executable output the path to python on a windows-pc, instead of kodi.exe (don't know if that is possible)
- if kodi.exe is called with a python script (actually C:\\kodi\\portable_data\\addons\\script.module.ptvsd\\lib\\ptvsd\\adapter contains a __main__.py) it should behave like python is called itself (with return values, ...) For now it seems as if just kodi gets it's focus again but not doing anything on the file.

### To Reproduce
On windows (and on linux, to see the difference): log.info(sys.executable)

### Debuglog
Windows 10 just outputs C:\kodi\kodi.exe as sys.executable, which doesn't seem right, don't know if I can provide a "real" debuglog for this case.

### Your Environment
Used Operating system:
- Windows 10 (Version 1903)
 - Kodi version: 18.5

**Comment by DaVukovic** [comment] 2020-01-20 06:09
Not a developer myself, but I guess it's due to the reason that Windows doesn't come with python pre-installed like Linux does. For that reason Kodi has it's own python interpreter on Windows. And that's what I guess where `sys.executable` returns the Kodi.exe on Windows.

So my guess is, if you want to debug an add-on with some additional tool, you have to make those changes on your own or use another OS. 

But I would like to hear a python-dev to confirm it.

**Comment by romanvm** [comment] 2020-01-20 10:57
@DaVukovic is correct. On Windows Kodi is statically linked with libpython and works regardless if there is any system Python interpreter present, so pointing `sys.executable` to some other Python interpreter makes no sense because there may be none or one of a different version. This is not to mention the fact that a system Python has no access to `xbmc*` modules.

Bottom line: it is an expected behavior.

**Comment by DaVukovic** [comment] 2020-01-20 11:16
Ok. So we can easily close this. 

Thanks @romanvm

**Closed by DaVukovic** 2020-01-20 11:16 UTC

**Comment by Cyber1000** [comment] 2020-01-20 17:40
Ok thanks for clarification
