### ISSUE TITLE
Unable to clean music library in Matrix

### ISSUE THREAD

**Issue by Neelix57** [xbmc/xbmc#19759] opened 2021-05-17 17:34 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

The clean library for music library function "Setttings > Media > Library > Music Library > Clean Library" doesn't work.
With Leia and below, "Clean Library" cleaned the albums, artists and titles from files I deleted from Library. In Matrix, the artists remains in the artists node.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Artists should be deleted from artists node.

## Actual Behavior

If I delete an album or a track, the artists remains in the artists node, when I use de clean library function and update my music library.

### To Reproduce

1. Add music in library, the song title, artist and album appears in the library.
2. Delete the added music.
3. Click clean library in media > music library settings and / or update library.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/erowinohaj.kodi

### Screenshots
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux - Xubuntu 18.04
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Matrix 19.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by eku** [comment] 2021-05-18 13:45
Same for me.

```
ERROR <general>: Process error processing job MusicLibraryCleaningJob
WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
INFO <general>: Cleanup: Starting musicdatabase cleanup ..
ERROR <general>: SQL: [MyMusic82.db] SQLite error SQLITE_ERROR (no such trigger: tgrDeleteSongArtist)
                               Query: DROP TRIGGER tgrDeleteSongArtist (no such trigger: tgrDeleteSongArtist)
ERROR <general>: Process error processing job MusicLibraryCleaningJob

```

**Comment by VelvetKev** [comment] 2021-06-26 11:02
i just registered to comment here, same for me with Matrix.
Happens often, but not with every library cleanup.

I'm currently replacing music i ripped to mp3 with FLAC rips.
So most have the same library names, but different file names
(e.g. 01-ac_dc-hells_bells.flac instead of 01-ac_dc-hells_bells.mp3).

`2021-06-26 12:32:37.310 T:8756     INFO <general>: Cleanup: Starting musicdatabase cleanup ..
2021-06-26 12:32:37.317 T:8756    ERROR <general>: SQL: [MyMusic82.db] SQLite error SQLITE_ERROR (no such trigger: tgrDeleteSongArtist)
                                                   Query: DROP TRIGGER tgrDeleteSongArtist (no such trigger: tgrDeleteSongArtist)
2021-06-26 12:32:37.343 T:8756    ERROR <general>: Process error processing job MusicLibraryCleaningJob`

**Comment by DaveTBlake** [comment] 2021-06-26 11:32
@VelvetKev @eku the log snippets you both provide show that there problem with your your music database schema (and that you are using local SQLite databases). The database trigger `tgrDeleteSongArtist` is missing. I can only guess that something interupted either database migration from a previous version, or perhaps the cleaning process previously and caused this trigger to be lost. It is not a general issue with Matrix.

I can guide you on how to repair your database, but is probably best to do so on the forum where a lot more users can see it and benefit should they ever get the same problem. Start a thread in Music Support and I will reply.

The original poster @Neelix57 does not have this issue, their log actually shows music database working without any error but a lot of non-music related errors instead. It is useless for triage, and further more cleaning works perfectly when tested.

**Comment by DaveTBlake** [comment] 2021-06-26 11:41
User specific fixes for db corruption to be provided via forum.

Original issue is not captured in log, and I can not reproduce - cleaning works fine (providing music database schema not corrupted). Also not raise against Matrix, hence closing issue.

I suggest that if @Neelix57 still has an problem they come and discuss it on the Music Support forum first because it looks like it will be user specifc and not a bug in Kodi.

**Comment by VelvetKev** [comment] 2021-06-26 11:42
done:
https://forum.kodi.tv/showthread.php?tid=363270

**Comment by eku** [comment] 2021-06-26 16:22
Hi Dave,

@DaveTBlake wrote
> the log snippets you both provide show that there problem with your your music database schema (and that you are using local SQLite databases). The database trigger `tgrDeleteSongArtist` is missing. I can only guess that something interupted either database migration from a previous version, or perhaps the cleaning process previously and caused this trigger to be lost. It is not a general issue with Leia or Matrix.

A little more usability at this point would certainly do Kodi good. Inconsistencies in the DB schema only manifest themselves in the logs and are not reported to the user. The way suggested in the forum to fix the error (export, rebuild, etc.) could surely offer the software itself?

**Comment by DaveTBlake** [comment] 2021-06-26 16:38
> A little more usability at this point would certainly do Kodi good...

@eku please take further discussion of this matter onto the forum thread rather , feature requests are not handled on Github issues.

**Closed** 2022-09-06 20:07 UTC
Labels: Component: Music, Resolution: Not reproducible
