### ISSUE TITLE
Profile auto-login not working right (and other profile problems)

### ISSUE THREAD

**Issue by annomatik** [xbmc/xbmc#16466] opened 2019-08-09 12:33 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

I updated from Kodi 17.6 to 18.2 last weekend, as support for 17.6 was running out. After the initial problems of getting a working Arctic Zephyr skin, I'm now trying to tackle the new profile problems which didn't occur in 17.6

1) the "profile auto-login" does not seem to work anymore. Instead of automatically starting with the master profile, I only either manage a) to get the login screen, without auto-login or b) no "logoff" function in the menu, thus completely disabling the profile functionality

2) I have described the second, more annoying behavior in the Kodi forums here:

https://forum.kodi.tv/showthread.php?tid=345975

In a nutshell, the "auto-login" seems to be deferred. When I start Kodi first, I get the login screen, I start a profile, the strings don't load right. When I log out and in back again, the translation strings load right and everything is fine.  Then I log out again and get -- automatically -- logged in into the master profile, again with the translation strings not loading right. Then I log out again and back in and most of the time, it's working fine, rinse and repeat.

Throw in the occasional complete freeze and the whole Kodi experience is no where near as smooth as it was in Kodi 17.6 (where it also had its problems, but still).

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I understand that profiles in Kodi have always been problematic (I've been Kodi user since v14) but as this is a very useful feature to me, maybe there's a chance of at least getting it to work in 18.x as good as it was working in 17.6.

1) I'd like to be able to specify a profile which I would be logged in into automatically during Kodi start. And it should load with all the right translations ( it always loads the right skins but sometimes with missing translation strings and/or the wrong highlight color ).
2) I'd like to be able to log-off of the master profile without getting the login screen first.
3) And, if possible, I'd like to be asked for a numeric password only for my Adult profile, not for the others. It's not just annoying to enter the master-code all the time, there'S also the problem that at times I can enter the code with the remote, at other times only with my wireless USB keyboard, at yet other times not at all.

## Actual Behavior

see description

## Possible Fix

couldn't find any, lots of new manual work that takes away from the Kodi experience.

### To Reproduce

see description

### Debuglog

The debuglog can be found here: https://paste.ubuntu.com/p/QNhTSDvnVD/

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Kodi 18.2 on Raspbian Stretch (Retropie 4.4) on Raspberry Pi 3b+ and also Windows 7 and 10 with Kodi 18.3 64bit
 - Kodi version: 18.2 (on RPi) and 18.3 (on Windows 7/10)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment] 2019-08-09 19:55
Tbh, I can't reproduce your issue neither with Kodi 18.3 nor with current Kodi master. 

I created a profile (named it "testing") and logged into it once. Then I changed back to the "Master user" profile, entered the settings -> profiles and set the autologin to "testing". Then I closed Kodi and restarted it. Profile "testing" was loaded fine. Then, while at "testing" I changed the setting back to "Master user", closed and restarted Kodi, and "Master user" was loaded fine. 

This was all done while "Show login screen on startup" was **disabled**! It would also make no sense to have that setting enabled if I choose to use to be auto logged in into a specific profile. Enabling that settings only makes sense if I **don't** want to be automatically logged in into a specific profile. Hence you can't select a auto-login profile while that setting is enabled. See: 

![grafik](https://user-images.githubusercontent.com/7235787/62805154-75558600-baef-11e9-9cdc-40e0d90c0737.png)


While logging out from a session, I see the existing profiles and I'm able to select one of them without any problems. 

The workaround you tried doesn't have anything to do with your problem explained here (also mentioned at the thread you linked to). 

The only thing I could imagine is, that raspbian probably patched something which causes that behavior. Or that probably something was broken in Kodi 18.**2** which might already be fixed in Kodi 18.**3** as I tested on 18.3 and 19 alpha 1 only. 

I'm not saying that I don't believe you, but I can't reproduce. Maybe you have done different settings to those profiles which might cause the problem. But as long as we can't reproduce, then we can't help unfortunately. Please tell us the exact steps to reproduce. Also please mention every setting you have done. Also please share your guisettings.xml and a log while using Kodi 18.3

Thanks in advance

**Comment by DaVukovic** [comment] 2019-08-09 20:13
something additionally: 

>I'd like to be able to log-off of the master profile without getting the login screen first.

this is something I don't understand. If you have multiple profiles at Kodi and you log off of one of them, you will be pointed to the login screen. That's normal and expected behavior and that was also the case in Kodi 17.6 (I just installed Kodi 17.6 on Ubuntu to confirm). By selecting "Log of <profile name>" you are actually logged off and all you then get is the login screen to select another profile to which you would like to login. 
Maybe I don't get your problem, so please explain a bit more. 

>I'd like to be able to specify a profile which I would be logged in into automatically during Kodi start. And it should load with all the right translations ( it always loads the right skins but sometimes with missing translation strings and/or the wrong highlight color ).

For this issue, you need to use my explained workaroung. Please be aware that you have to put the autoexec.py directly into your userdata folder and ALSO into **any** existing profile folder. 

>And, if possible, I'd like to be asked for a numeric password only for my Adult profile, not for the others. It's not just annoying to enter the master-code all the time, there'S also the problem that at times I can enter the code with the remote, at other times only with my wireless USB keyboard, at yet other times not at all.

Simply change the usage for the master profile. You can rename it to whatever you want. If you rename your master profile to "Adult" and select a password for it, then you have the exact behavior you are asking for. Profile names are only semantics. You can (ab)use them in any way you can imagine. Having an individual password for each profile you created would be a feature request anyway which has to be posted here: https://forum.kodi.tv/forumdisplay.php?fid=9

**Closed** 2022-08-25 16:36 UTC
Labels: Issue Cleanup: Obsolete
