### ISSUE TITLE
Garbled sound with DD+/EAC3 passthrough and official Dolby DD+ 7.1 sample

### ISSUE THREAD

**Issue by HiassofT** [xbmc/xbmc#19182] opened 2021-02-06 15:02 UTC
### Describe the bug
When playing the Dolby Digital Plus 7.1 sample file [MP4_HPL40_30fps_channel_id_71.mp4](http://media.developer.dolby.com/DDP/MP4_HPL40_30fps_channel_id_71.mp4) from the [Dolby website](https://developer.dolby.com/tools-media/sample-media/video-streams/hd-video-streams/) audio output is garbled - it sounds like sound on/off in quick succession or stuttering - and kodi logs tons of "large audio sync error"s.

## Expected Behavior
Kodi is able to pass through official Dolby samples.

### Debuglog
The debuglog can be found here: http://ix.io/2OvU

## Additional context or screenshots (if appropriate)
The 5.1 DD+ sample [MP4_HPL40_30fps_channel_id_51.mp4](http://media.developer.dolby.com/DDP/MP4_HPL40_30fps_channel_id_51.mp4) from the webpage plays fine with passthrough enabled.

When disabling DD+/EAC3 passthrough the 7.1 sample plays fine with software decode (tested with downmix to 2.0)

### Your Environment
Used Operating system:
 - [X] Linux
 - Operating system version/name: LibreELEC master, RPi4
 - Kodi version: master, githash 1e6f7347ec56233923d176825f0ccdc6a60d76d3

**Comment by DaVukovic** [comment] 2021-02-07 15:46
I can confirm this issue with Kodi 19 RC1 on Ubuntu as well

https://paste.ubuntu.com/p/DbG9n6nZNn/

the 5.1 file plays fine, the 7.1 does not. I'm also seeing video stuttering as well while playing the 7.1 file.

**Comment by BergerBlancSuisse** [comment] 2021-02-12 22:55
in my case i use a firetv cube (dolby-digital-plus audio configured) with kodi 19.x-> nightly, and as a server a windows server 2019 (connection via wlan-> fritzbox 7590), and as an av receiver a denon avr-x4500h (connection via hdmi cable).

my audio settings in kodi: passthrough, plus the settings "hd-sounds ac3 / eac3 / dts / dts-ht receiver decoding, and without receiver decoding.

Both settings lead to an error in kodi when playing h.264 / h.265 encoded videos.

the videos are played briefly and then stop with a stuttering image until the controls freeze briefly and you land in the playlist.

when playing videos with different audio formats, e.g. first pvr-enigma2 video, and then h.265 video, the audio output stutters, my av receiver can no longer decode the hdmi sound -> the firetv must be restarted.

I hope there will be a solution.

**Comment by fritsch** [comment] 2021-02-13 06:22
This sample basically never worked. Either disable dd+ passthrough or passthrough in general. Then it is decoded.

Our passthrough syncers and parsers are not maintained anymore. I can shortest look at Christmas 2021.

**Comment by BergerBlancSuisse** [comment] 2021-02-13 06:43
hi fritsch,

christmas 2021? you are optimistic ;-))
what does the "exoplayer" do better in plex, the plex works?
could one integrate the "exoplayer" in kodi?
maybe my log can provide information: https://paste.kodi.tv/vujilonuri.kodi

lg

**Comment by BergerBlancSuisse** [comment] 2021-02-13 07:07
i have completely deactivated passthrough, but the video still breaks off as I described above.
log: https://paste.kodi.tv/piricorimo.kodi

**Comment by fritsch** [comment] 2021-02-13 07:16
Concerning exoplayer: Yes, go head. Sounds like a good idea.

**Comment by BergerBlancSuisse** [comment] 2021-02-13 07:33
i agree!

**Comment by BergerBlancSuisse** [comment] 2021-02-13 07:34
here is another log, broken off almost at the same place in the video: https://paste.kodi.tv/xokoceqili.kodi

**Comment by BergerBlancSuisse** [comment] 2021-02-13 07:38
would it be a good idea to use your kodi 18.9 firetv build until christmas?
maybe you'll be able to integrate the exoplayer into kodi by then?
the dream player tv app on the fire tv also uses the exoplayer and works very well.

**Comment by fuzzard** [comment] 2021-02-13 07:42
Sarcasm doesn't play well, so to put you out of your misery, Fritsch has no intention to do that. If you think it's a great idea, he is saying you (or anyone else with that great idea) should implement it.

**Comment by BergerBlancSuisse** [comment] 2021-02-13 07:51
Unfortunately I can't rhyme that well, and I can't program either ...

**Comment by BergerBlancSuisse** [comment] 2021-02-13 18:31
last working build which works on the firetv cube with hd video / sound without problems for me is "kodi-20201001-5c717b66-fritschfiretv-armeabi-v7a"

**Comment by Ryushin** [comment] 2021-03-06 15:09
I have a 2019 Shield running Matrix (tried the latest nightly as well) and I'm having problems with all my 4K files that have 7.1 TrueHD+Atmos audio files when I try to passthrough audio.  If I start the video with 7.1 or select it while playing the video, it plays fine until I try to skip forward or backward then the audio just cuts in and out.  Turning off "TrueHD capable receiver" in the audio passthrough menu allows the audio to play fine when skipping forward or back (no Atmos of course).

Audio passthrough worked fine with Leia.  Reading this thread, is the earliest they think this will be fixed is at the end of this year, or was that sarcasm?

[kodi.log](https://github.com/xbmc/xbmc/files/6095541/kodi.log)

**Comment by FKOV** [comment] 2021-04-11 13:28
I get the same error and the error persists even if I disable all audio pass-through,  any uptades concerning this issue since it's very frustrating

**Comment by Krobar** [comment] 2021-11-28 18:43
I think this sample is weird because it contains dependant EAC3 frames. These are part of the EAC3 spec but rare and I dont think the code even exists within Kodi to deal with them as of right now.

The sample seems to have this frame ordering@
EAC3 Frame - 920byte
EAC3 dependent Frame - 616byte

I'm no expert but I imagine adding support for this would be quite alot of work.

**Comment by Krobar** [comment] 2021-11-28 20:09
I think I can see the problem. Kodi only checks for an EAC3 extension frame if the first frame is legacy AC3 (BSID <= 10):
https://github.com/xbmc/xbmc/blob/49a04cd6a7f49ea9a0f05c492b11a3ba7c542a99/xbmc/cores/AudioEngine/Utils/AEStreamInfo.cpp#L373

This sample is EAC3 with an EAC3 extension frame.

**Comment by TylerDurden2019** [comment] 2022-02-17 02:25
Will this be fixed in the next Matrix release?

**Comment by iipamonkey** [comment] 2022-03-15 22:05
> Will this be fixed in the next Matrix release?

I reported this issue over 1.5 years ago on the kodi.tv forum and this 'official' bug is over a year old. Fritsch has indicated the relevant parts of the codebase are no longer maintained (??), so if I were a betting sort, I'd say this is not going to be fixed.

**Comment by TheJayPi** [comment] 2022-10-04 15:16
Guys, I am opening this up because it seems it is more than up to date. There is trouble with Kodi playing E-AC3 files that have 7.1 channels. They dont play via passthrough. More details here: https://discourse.osmc.tv/t/no-audio-on-dd-with-8-channels-on-vero4k/93643

@fritsch suggested to use ffmpeg to implement the parsers since they are more advanced now. Is there anyone who could do that ?

**Comment by LauraTaylorUK** [comment] 2022-12-03 18:16
I posted about this issue at bug #19888. 

I can't play any TrueHD 7.1 audio, I've been testing the tracks available here: https://thedigitaltheater.com/dolby-trailers/

**Comment by Ramalama2** [comment] 2023-04-20 08:09
Hi, im having exactly the same issue on the Shield Pro 2019 with Kodi 20.1 ARMv8a. (Latest Kodi)

But others mention issues with ThueHD Atmos etc, i can't confirm that on the Shield, as far i remember TrueHD Atmos works here.
Only DD+ 7.1 is an issue, like described in the first post.

Cheers

**Comment by CursedDevelopment** [comment] 2023-04-20 09:19
And there I was thinking the problem was my 5.1 Yamaha receiver just not properly supporting those 7.1 streams without a fallback. Also believed "passthrough" implied no processing had to be done on the software side. When playing these types of streams I did notice the audio stream info on the receiver jumping between formats as if it couldn't decide what it's actually receiving.
Atmos is no issue here (Shield Pro 2019 with Kodi 20.1), just pure 7.1 DD+ streams from what I've seen.

**Comment by fritsch** [comment] 2023-04-20 14:25
Things are not so easy. The raw stuff needs to be packed in so called IEC frames. Whenever the parsing of the raw payload fails, e.g. no sync on them, packing fails and signal is lost. The issue at hand is a problem with kodi`s syncer and packer. You can check if android does it properly by switching over to Android packer as the audio device.

**Comment by Ramalama2** [comment] 2023-04-20 20:23
> Things are not so easy. The raw stuff needs to be packed in so called IEC frames. Whenever the parsing of the raw payload fails, e.g. no sync on them, packing fails and signal is lost. The issue at hand is a problem with kodi`s syncer and packer. You can check if android does it properly by switching over to Android packer as the audio device.

I tryed the android packer!
- While The Kodi IEC Packer doesn't output any DD+ 7.1 audio,
- The Android IEC Packer does output the DD+ 7.1 audio, but it's laggy/Stuttering

Strangely Plex/Exoplayer does output DD+ 7.1 perfectly fine without any issues.

So the workaround that i have for me right now with the Shield 2019, is to use Plex simply for that Movies with DD+ 7.1

----
However, i find it very strange that DD+ 5.1 and even some DD+ 7.1 plays fine on Kodi, every other Format like Atmos/DTS-HD/MA and everything else possibly imaginable is working correctly.

For me that somehow sounds like something easy to fix, but it definitively isn't if that bug report exists of course since 2 Years :-)

However, thanks to everyone who is investigating into this.
Cheers!

**Comment by fritsch** [comment] 2023-04-21 04:54
Why do you find it strange? I explained it properly. Kodi's packer was never adjusted to support these new 7.1 files.

Nice that Plex works, so you have an alternative until someone with the knowledge and free time can fix it for Kodi.

**Comment by TheJayPi** [comment] 2023-04-21 05:16
Peter, there was a suggestion to switch to ffmpeg parsers instead of fixing the existing code. Would that be something that you would be able to do ? Am 21.04.2023 um 06:55 schrieb Peter Frühberger ***@***.***>:﻿
Why do you find it strange? I explained it properly. Kodi's packer was never adjusted to support these new 7.1 files.
Nice that Plex works, so you have an alternative until someone with the knowledge and free time can fix it for Kodi.

**Comment by fritsch** [comment] 2023-04-21 05:28
I have no time for that. Maybe next Christmas. I have a 60 hours real life job. If you have the time, please step in. Also if you are below age 90, learning c++ is still an option if time is available.

**Comment by Ramalama2** [comment] 2023-04-27 18:33
@popcornmix 
You are amazing!
Dd+ 7.1 eac3 is finally working now!
After 1,5 years 😂

Could you maybe just make an PR to the official Kodi repo? 🙈

Thank you 👌😘!
For everyone else, Maven builds already include this commit either in his Nexus branch.

Cheers!

**Comment by fritsch** [comment] 2023-04-27 18:39
Jep - that's really great. Thanks @popcornmix - please PR when you feel ready. Short glance at the code: looks good.

**Comment by TheJayPi** [comment] 2023-04-27 18:46
@popcornmix Thank you sooooo much !!! I am sooooo keen on trying it out...

**Comment by LauraTaylorUK** [comment] 2023-04-27 19:26
Is this fix included in the latest kodi nightly build? thank you.

**Closed** 2023-05-10 04:55 UTC
Labels: Component: Audio, v19 Matrix, Triage: Confirmed
