### ISSUE TITLE
Kodi deleting Unique ID's from database after first scrape.

### ISSUE THREAD

**Issue by KarellenX** [xbmc/xbmc#17444] opened 2020-03-06 08:56 UTC
### Describe the bug

Unique ID's are scraped into the UniqueID table. These UniqueID's can consist of IMDB, TVDB and TheMovieDB ID's with one of them set as default depending on which scraper is used.

When scraping a title into the Video Library for the first time, all these ID's (when available) are scraped and added into the UniqueID table, but Kodi then goes back and deletes all the Unique ID's and replaces them with only the ID's marked as `default="true"` and all other ID's are discarded.

This occurs in v18.x through numerous fresh starts. It also occurs in v19. All TV Show scrapers are affected even @Razzeee new Python scraper.

This only happens on **first** scrape of the tv show or movie. If you delete the show from the library and scrape it again, the issue does not manifest itself and all UniqueID's are scraped correctly.

## Expected Behavior

When Kodi scrapes the UniqueID's, they remain in the UniqueID table of the video database.

## Actual Behavior

The UniqueID's are scraped and added to the database, then deleted and only the default ID's are added back.

### To Reproduce
Steps to reproduce the behaviour for TV Shows as an example:

This is a real tricky one to reproduce and it sounds pretty bonkers but it is the only way I can replicate the issue
1. Find a tv show that you have never previously scraped. Ensure the show has a full compliment of ID's at the scraper site by checking their edit screens. Try "Homeland" or "Doctor Who"
2. Ensure you use actual video files. Dummy files don't seem to manifest the problem
3. Scrape the tv show from Videos>Files using the "Information" method
4. Exit back to the Main menu when the scrape completes
5. Check the UniqueID's by either checking the DB or exporting to NFO files
6. You should notice the only UniqueID available is the default one, or if you check the DB table, you will see gaps in the record numbering. See images below.

### Debuglog
The debuglog can be found here:

https://paste.kodi.tv/jomececara.kodi

### Screenshots 

The following image is taken immediately after the scrape and a full compliment of ID's are available
![UniqueID10](https://user-images.githubusercontent.com/44626605/76067109-f374ff00-5fe2-11ea-90be-f0a2f15c490a.JPG)

This image is taken only a few seconds after the previous image and it looks like all the ID's are added. Then all the Id's are deleted, then the default ID's are added back
![UniqueID11](https://user-images.githubusercontent.com/44626605/76067201-1acbcc00-5fe3-11ea-8b2b-eb49c3e7e313.JPG)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: v18.x and v19

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by HeresJonny** [comment] 2020-03-07 19:56
Possibly related https://forum.kodi.tv/showthread.php?tid=164652&pid=2846827#pid2846827

**Comment by Razzeee** [comment] 2020-03-08 18:16
I guess the easiest would be to log all commands that get executed on the uniqueid table and then check tho log.

**Comment by Montellese** [comment] 2020-05-24 17:41
The most likely case is that for some reason `CVideoDatabase::UpdateUniqueIDs()` is executed again for the tvshow but with only the default values loaded. This could happen if some code loads a tvshow without any extra properties (ratings, unique IDs, ...) and then saves it to the database again. Then we only load the default unique ID, delete all unique IDs in `CVideoDatabase::UpdateUniqueIDs()` and only save the default unique ID.

**Comment by Montellese** [comment] 2020-05-24 20:57
I was able to reproduce this and as expected the bad guy is https://github.com/xbmc/xbmc/blob/master/xbmc/video/VideoThumbLoader.cpp#L167 which is updating all details of an item without having loaded all the extra properties. So this probably shouldn't affect only unique IDs but that depends on the code calling `CThumbExtractor` or rather `CVideoThumbLoader::LoadItem()` but I'll have to look into that another time.

**Comment by KarellenX** [comment] 2020-05-24 21:33
Great. Thank you @Montellese

**Comment by Montellese** [comment] 2020-05-25 09:28
Wow our code is ugly... I've tried to trace back the call stack but since multiple threads are involved it's not so easy. This is what I got:
* if a skin tries to access an info label of an item which doesn't have a `"thumb"` artwork assigned it creates a `CVideoThumbLoader` background job to load the item (in `CVideoGUIInfo::InitCurrentItem()`)
* `CVideoThumbLoader::LoadItem()` tries to load additional details
  * `CVideoThumbLoader::LoadItemCached()` tries to
    * load existing stream details from the database
    * load existing artwork from the database
    * if there is no existing artwork it tries to retrieve it locally
  * `CVideoThumbLoader::LoadItemLookup()` tries to
    * set some properties on the `CFileItem`
    * download missing artwork
    * start CThumbExtractor as a background job
* `CThumbExtractor::DoWork()` tries to
  * extract a thumb image from the video file (if not present)
  * extract stream details from the file (if not present)
  * save the stream details in the database
  * save the video item's duration in the database

The very last step is what is causing this issue because it uses `CVideoDatabase::SetDetailsForItem()` which overwrites ALL properties of the video item in the database and not just the video item's duration.

Combining this with the fact that we don't load the full details of video items as long as the user doesn't open the info dialog for an item or starts playback this results in loss of data.

It only affects unique IDs because there we first delete all existing unique IDs from the database and then add all "new" ones. For ratings, cast etc. we only add new ones without deleting the old ones. Obviously this might also result in unexpected data (in other parts of the code) because we don't properly cleanup old cast, ratings etc.

**Comment by Montellese** [comment] 2020-05-25 11:09
Maybe fdd41c73882e3634a642045cb17c9be022056c77 will solve this issue but might introduce other issues... With this change we don't purge "old" unique IDs and only add new ones so if for some reason a movie suddenly wouldn't have a TMBD or IMDB ID anymore it would still remain in our database (until the movie is deleted). The same applies to tvshows and episodes. For tvshows it's even a bit worse because there we use the exactly same code for `SetDetailsForTvShow()` as for `UpdateDetailsForTvShow()`. But unique IDs should now behave exactly the same as ratings where we also only add and never purge / cleanup.

**Comment by KarellenX** [comment] 2021-01-15 03:08
In case some one is looking for a quick workaround. 

To work around the issue is quite simple and only takes a few seconds per movie or tv show

1. Do not scrape your movie or tv show after adding them to your Source.
2. Navigate to Videos>Files>Your Source and browse for your movie
3. This forces Kodi to extract the thumb **before** the scrape. It will also read the streamdetails at the same time.
4. You can then update your library by pressing **i** on your keyboard, or in your normal manner

It is the thumb extraction **after** the scrape that causes this problem. Performing the extraction before the scrape avoids the issue.

**Comment by KarellenX** [comment] 2021-04-05 19:46
@Montellese Do you think your patch https://github.com/xbmc/xbmc/commit/fdd41c73882e3634a642045cb17c9be022056c77 is stable enough to PR into main and maybe backport to v19.2?

**Comment by Montellese** [comment] 2021-04-06 04:57
Well I haven't used it myself but it still looks sane under the conditions I described above i.e. it will behave exactly like ratings. Removing old / outdated unique IDs won't be possible.

**Comment by KarellenX** [comment] 2021-04-06 05:10
thanks @Montellese 
But they would be removed in the event you delete a movie/tv show/episode. Will a Refresh also remove it? I guess it would as ratings are also removed and refreshed that way.

I can test if a build is available, or if you think it is safe enough to PR, that would be great.

**Comment by Montellese** [comment] 2021-04-06 06:35
Yes they should be removed when the media item is removed. I can create a PR later today.

**Comment by Montellese** [comment] 2021-04-06 06:42
See #19527.

**Comment by KarellenX** [comment] 2021-04-06 07:11
Thank you :)

**Closed** 2021-04-26 11:40 UTC
Labels: Component: Database, Component: Video, Triage: Confirmed, v18 Leia, v19 Matrix
