### ISSUE TITLE
Can't use live TV on Android as http2 fails whereas http 1.1 worked previously

### ISSUE THREAD

**Issue by Rihy** [xbmc/xbmc#16730] opened 2019-10-06 20:40 UTC
### Describe the bug
Can't use live TV on Android.
Add-on : IPTV Simple Client

It works on a pc and android 18 rc-1 under.

## Expected Behavior
It works normally up to 18.1RC-1.

## Actual Behavior
Even channels after 18.1 will not be displayed.

### Debuglog

Kodi PC https://pastebin.com/MqeZXphg
Kodi Android https://pastebin.com/CW7TWb4d

### Screenshots 
Krypton-Leia RC-1 working https://i.imgur.com/yF5HReu.png

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 9.0
 - Kodi version: Kodi 18.1-

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment] 2019-10-07 04:11
I would probably suggest to seek assistance at the forums. 

Seems Kodi either can't read/find the file or it's empty: 

2019-10-04 08:30:08.061 T:17840   ERROR: AddOnLog: PVR IPTV Simple Client: pvr.iptvsimple - LoadPlayList - Unable to load playlist cache file 'http://192.168.1.101:8888/api/iptv/channel.m3u8?mode=2':  file is missing or empty.

That IP seems to be different from the one you are using for your device, as that seems to be: 

2019-10-06 15:06:01.892 T:11994  NOTICE: Local hostname: 192.168.2.66

So those are different networks and it's pretty obvious (if there's no routing device in between), that this won't work. Sp best is to ask at the forums how to solve that.

**Comment by Rihy** [comment] 2019-10-07 04:19
It's like this on Kodi ...
https://i.imgur.com/itDU4TZ.png
It ’s in the same network.

It is not solved in the forum.
I asked the same question here, but I realized that it was due to Kodi's core.
https://github.com/kodi-pvr/pvr.iptvsimple/issues/287

**Comment by Rihy** [comment] 2019-10-09 22:14
Same issue.

https://forum.kodi.tv/showthread.php?tid=343010

**Comment by ksooo** [comment] 2019-10-29 07:32
@phunkyfish any idea?

**Comment by Rihy** [comment] 2019-10-29 08:51
I investigated it myself.
It is not written in the commit.

I found that the version of kodi.json has changed and the curl h file has changed.

**Comment by ksooo** [comment] 2019-10-29 09:31
> It is not written in the commit. I found that the version of kodi.json has changed and the curl h file has changed.

 Sorry? I have no idea what you are talking about. Culd you please explain your findings a bit more in detail?

**Comment by Rihy** [comment] 2019-10-29 09:35
I'm sorry.  I want you to see here.
https://forum.kodi.tv/showthread.php?tid=348381

**Comment by phunkyfish** [comment] 2019-10-29 13:14
This one had me stumped. 

The latest addon version worked ok on Leia 18.0/18.1rc1 but failed on 18.1. So I don’t believe the cause is the addon.

Looking at the commit list for both I can’t put my finger on the cause.

**Comment by phunkyfish** [comment] 2019-10-29 18:33
@Rihy what is the curl.h change?

**Comment by Rihy** [comment] 2019-10-29 20:13
I do not know in detail.

Certainly there was a difference when downloading and comparing the Kodi source code.

**Comment by phunkyfish** [comment] 2019-10-29 21:31
There is nothing that stands out as curl related when running: `git diff 18.1rc1-Leia 18.1-Leia`

**Comment by Rihy** [comment] 2019-11-17 12:43
Is there anything you can do?

**Comment by Rihy** [comment] 2019-11-19 10:22
When I talked to the live tv server depelopment that I use, it seems that http2 is not supported.

It seems to be able to respond by inserting a reverse proxy.

**Comment by phunkyfish** [comment] 2019-11-19 10:25
Can you explain a bit further?

Do you mean you have a solution?

**Comment by Rihy** [comment] 2019-11-19 10:36
I'm not a developer either, so I don't know the details.
It works normally on Windows.
In Android, it works by going through nginx reverse proxy.
It looks like Android Kodi will only work with http/2.

I will attach an issue with the problem in Japanese.
https://github.com/Harekaze/pvr.chinachu/issues/30

**Comment by phunkyfish** [comment] 2019-11-19 14:10
Ok, so this appears to happen since this commit: https://github.com/xbmc/xbmc/commit/8839957437f2c1557c5810aff2af820e50826370

But it only affects Android (that you know of). It appears that with certain versions of curl you proxy solution has issues.

The work around is to use tinyproxy, so something like:

```
apt install tinyproxy
```

/etc/tinyproxy/tinyproxy.conf:

```
User tinyproxy
Group tinyproxy
Port 8888
Timeout 600
DefaultErrorFile "/usr/share/tinyproxy/default.html"
StatFile "/usr/share/tinyproxy/stats.html"
LogFile "/var/log/tinyproxy/tinyproxy.log"
LogLevel Info
PidFile "/run/tinyproxy/tinyproxy.pid"
MaxClients 100
MinSpareServers 5
MaxSpareServers 20
StartServers 10
MaxRequestsPerChild 0
ViaProxyName "tinyproxy"
ReversePath "/" "http://localhost:20772"
ReverseOnly Yes
```

Then to start tinyproxy:

```
sudo /etc/init.d/tinyproxy restart
```

Bear in mind I just pulled this from the japanese post using google translate so no guarantees.

**Comment by phunkyfish** [comment] 2019-11-19 14:16
I think what is going wrong is that kodi is trying to connect using http2 but not using https. Which from what I am reading is generally unsupported. Can you run your server using https?

@peak3d any idea why http2 is used? If the above commit is reverted connecting of http1.1 works just fine.

**Comment by Rihy** [comment] 2019-11-19 14:18
I'm trying and using nginx for the Windows environment.
Do you have a fix on Kodi side?
Do I have to avoid this in the future?

**Comment by phunkyfish** [comment] 2019-11-19 14:21
There is a patch for your server to fix this: https://github.com/Harekaze/pvr.chinachu/issues/30#issuecomment-502425448

This is NOT a kodi issue. Instead a bug in your server.

**Comment by Rihy** [comment] 2019-11-19 14:28
Since it is here that I am using, it seems that it will not be solved.
https://github.com/l3tnun/EPGStation/issues/279

**Comment by phunkyfish** [comment] 2019-11-19 14:42
It is fixed in the issue you reference here: https://github.com/l3tnun/EPGStation/issues/279

You just need to upgrade your server.

**Comment by phunkyfish** [comment] 2019-11-19 14:46
Or apply this patch:

```
diff --git a/app-wui.js b/app-wui.js
index 51bd2ca..3407f12 100644
--- a/app-wui.js
+++ b/app-wui.js
@@ -805,6 +805,7 @@ function iosAddEventListner(io, eventName) {
 }
 
 function ioAddListener(server, isOpen) {
+       return;
        var io = socketio(server);
 
        io.on('connection', isOpen ? ioOpenServer : ioServer);
```

Find the `app-wui.js` file on your server and add the `return;` statement on the correct line.

That appears to be all that is needed.

**Comment by Rihy** [comment] 2019-11-19 23:03
It seemed that it was not able to be done though it was going to update.
It was successfully resolved.  Thank you very much.
Should I close this issue?

**Comment by phunkyfish** [comment] 2019-11-19 23:18
Great, yes, please close this and any related issues you opened.

If you have any forum posts please also mark them as solved.

**Closed** 2019-11-19 23:19 UTC
Labels: Triage: Needed
