### ISSUE TITLE
Nightly 6/22/22 19.4 Broke file Manager connecting to Web server, nightly 6/8/22 works fine.

### ISSUE THREAD

**Issue by EvilOneIsMe** [xbmc/xbmc#21590] opened 2022-06-23 11:04 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

Bug report
Used nightly June 22 2022 Added a path to my web server Apache 2.4 PHP 7.4 with http://mywebsite.org/repo and it says remote share couldn't connect to network sharecontent. If I go back to nightly dated June 8 2022 it works fine.

## Expected Behavior

It should have shown files in my repo folder.:

## Actual Behavior

it says remote share couldn't connect to network sharecontent

## Possible Fix

Went back to nightly June 8 2022

### To Reproduce

1. Installed the latest Nightly.
2. Went back to older nightly
3. Did this several times, also checked my paths several times.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by howie-f** [comment] 2022-06-23 13:26
looks like there is a regression caused by https://github.com/xbmc/xbmc/pull/21503 ?
ping @enen92 

@EvilOneIsMe post a debuglog please

**Comment by enen92** [comment] 2022-06-23 22:49
Would be great if you could post the headers returned by your server (enabling libcurl component logging should be enough)

**Comment by matthuisman** [comment] 2022-06-23 23:52
I suspect the code should also check for empty content-type.

**Comment by EvilOneIsMe** [comment] 2022-06-24 10:04
[kodi.log](https://github.com/xbmc/xbmc/files/8975271/kodi.log)
Log file The repo does have files in the repo. And again works fine on every release but the last one.

**Comment by arnova** [comment] 2022-06-24 10:14
Why did you close this? Furthermore the provided log file does not have curl-component logging enabled....

**Comment by EvilOneIsMe** [comment] 2022-06-24 10:53
Sorry I didn't mean to close it. Is there a way to reopen it? Also I don't know how to do the curl-component loging.

**Comment by the-black-eagle** [comment] 2022-06-24 11:11
You do it in Kodi.  Settings->system->logging  Enable debug logging and underneath enable component-specific logging. Click on specify component-specific logging and choose the libcurl library.  Restart Kodi, reproduce your issue and upload the resulting log.

**Comment by howie-f** [comment] 2022-06-24 11:13
![screenshot00000](https://user-images.githubusercontent.com/58829855/175523601-b345df04-ca2c-488c-bf3f-59a4dee179e5.png)

**Comment by EvilOneIsMe** [comment] 2022-06-24 11:26
[kodi.log](https://github.com/xbmc/xbmc/files/8975787/kodi.log)
Ok got it done, hope this helps.

**Comment by EvilOneIsMe** [comment] 2022-06-24 11:46
> Would be great if you could post the headers returned by your server (enabling libcurl component logging should be enough)

If your talking about my Apache 2.4 server I'm not sure how to do that. I used to do a LOT of server work but Its been a long time ago. I'm 75 now and kind of supprised I got it installed and working (Grin)

**Comment by howie-f** [comment] 2022-06-24 11:57
> Ok got it done, hope this helps.

sorry, it is not a debug log.
you need to turn on both settings in the gui.
`Enable debug logging -> ON`
`Enable component specific logging -> ON` …. and
`- Specify component-specific logging… -> enable libcURL (see screenshot)`

**Comment by EvilOneIsMe** [comment] 2022-06-24 12:13
[kodi.log](https://github.com/xbmc/xbmc/files/8976010/kodi.log)
OK 3'd times a charm?

**Comment by howie-f** [comment] 2022-06-24 12:21
yup, thanks. i think this contains what we need

**Comment by EvilOneIsMe** [comment] 2022-06-24 12:40
> `HEADER_IN: Content-Type: text/html;charset=UTF-8` this certainly fails as we are checking for text/html alone (and not considering the possible charsets).

Not sure if I should add this in here but I'm having the same problem with the new ver 20 alpha.  Thanks. does this mean I don't need to add anything else?

**Comment by enen92** [comment] 2022-06-24 12:52
No, it's a Kodi bug. It'll get fixed soon

**Comment by EvilOneIsMe** [comment] 2022-06-24 13:37
> http://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20220624-0a0f2a8f-v19-contenttype-x64.exe

Worked just fine. When I clicked on the path it showed me the files in the repo. !!!! (Grin!)

**Closed** 2022-06-24 18:40 UTC
Labels: Triage: Confirmed, Component: Content, v20 Nexus
