### ISSUE TITLE
Samba client doesn't work on Android version

### ISSUE THREAD

**Issue by Barabba11** [xbmc/xbmc#25500] opened 2024-07-17 11:35 UTC
### Describe the bug
Sending by JSON with command {"method": "Player.Open", "args": { "item": { "file": "smb://192.168.101.100/log/1.jpg" } } } produces a black screen, the same comamnd on Kodo for Windows works. It looks Kodi 21 doesn't support correctly samba, I've enabled on Windows Samba 1 support, removed password connection, enabled all permissions to everyone. forced Kodi to work with v1, v2, v3 but no results. Also I've tried in Kodi to add manually the shared folder, type server name (IP address), shard folder name and leaving blank user and passw works on Windows into a PC placed in LAN but not with my Android phone, it returns error "invalid argument".

## Expected Behavior
Expect to open by JSON an smb://LAN/path/file, expecting to add manually an smb://LAN/path/

## Actual Behavior
With JSON a black screen, adding manually "invalid argumet error"

## Possible Fix
I've tried with samba 1,2,3. Program like Fotoo works on the same android TV using samba protocol, so it doesn't depend on tv itself

### To Reproduce
add a Windows network path on Android

### Debuglog
Where the log file is store under android?

### Screenshots 
needed?

### Your Environment
Kodi 21 on Android 11 (and google TV, the same), and Kodi21 on WIndows10

**Comment by thexai** [comment] 2024-07-19 17:33
Samba works for sure on Android, otherwise we would have hundreds of complaints in the forums... But you must provide user / password, which you are not doing.

There is a known issue in Android: SMB does not work without providing authentication, anyway SMB 1 is deprecated... you should upgrade to SMB 2/3 and provide user / password.

Duplicate of https://github.com/xbmc/xbmc/issues/18832

**Closed by thexai** 2024-07-19 17:33 UTC
Labels: Ignored rules, Triage: Needed
