### ISSUE TITLE
log's get spammed with "error <general>: CCurlFile::Open - <http://127.0.0.1:9981/imagecache/27> Failed with code 404:"

### ISSUE THREAD

**Issue by eldersixpack13** [xbmc/xbmc#25538] opened 2024-07-22 22:06 UTC
### Describe the bug
On LE12 and now on LE13 (both nighties) each time kodi starts or a channel is switched I get the above errors in the kodi.log and in TVH's service.log too.

## Expected Behavior
no errors

## Actual Behavior
see above

## Possible Fix
if I had one, this bug report didn't exist !
right ?   ;-)

### To Reproduce

1.  setup LE, install TVH, Tvheadend HTSP, config TV channels in TVH
2. restart
3. view kodi.log, esp. after channel switching and maybe TVH log 

### Debuglog
[kodi.log](https://github.com/user-attachments/files/16340051/kodi.log)
[service.log](https://github.com/user-attachments/files/16340054/service.log)

## Additional context or screenshots (if appropriate)

I tried a lot to fix this, but without success, so far, e.g.:

- freshen the picons in TVH    
- cleaned the database for PVR (Settings => "PVR & Live TV")   
- deleted the DB's under Kodi and reboot
- cleaned under TVH the directory (/.kodi/userdata/addon_data/service.tvheadend43/imagecache), what wasn't empty.
- configured the PVR with/with out user and password
- de- and new-installed TVH and PVR and left the config defaults
- setup up a clean box since the issue first appeared serveral times and lastly today
- ...

I'm not alone:
https://forum.libreelec.tv/thread/26351-kodi-is-not-loading-channel-icons-from-tvheadend-server/?postID=174588&highlight=imagecache#post174588

### Your Environment
Used Operating system:

 - [ x] Linux
 
 - Operating system version/name: LE13 (nightly-20240719-ab27426), but the error was in LE12 too 
  - Kodi version: currently: 22.0-ALPHA1 (21.90.700) Git:060417ccfa5b21939669d404b9a223c3004ba132 

this is a fresh/clean installed LE13 on an NUC13.
I've read about the need of installing additional icons... . 
if so: I didn't.

**Comment by malvinas2** [comment] 2024-07-23 07:56
This behaviour is caused by TVHeadend, not by Kodi, e.g.: 
[https://tvheadend.org/d/4217-plenty-of-tvheadend-pid-http-192-168-xxx-yyy-http-1-1-head-imagecache-72-404](https://tvheadend.org/d/4217-plenty-of-tvheadend-pid-http-192-168-xxx-yyy-http-1-1-head-imagecache-72-404)

**Comment by ksooo** [comment] 2024-07-23 09:08
Question is, why Kodi has outdated image cache URLs. We need to find out where these URLs come from. 
Some Kodi cache / db entries not updated properly? 
Tvheadend sending (through pvr.hts) outdated URLs?
Needs to be analysed...

**Comment by eldersixpack13** [comment] 2024-07-23 12:42
> This behaviour is caused by TVHeadend, not by Kodi, e.g.: https://tvheadend.org/d/4217-plenty-of-tvheadend-pid-http-192-168-xxx-yyy-http-1-1-head-imagecache-72-404

if so I would see this error in services.log (TVH directory), when I (only) restart TVH. 
But I don't (at least not with TVH 4.3)

info:
before I opened the bug here, I was at pvr.hts:
https://github.com/kodi-pvr/pvr.hts/issues/667

**Comment by ksooo** [comment] 2024-07-23 12:49
> if so I would see this error in services.log (TVH directory), when I (only) restart TVH.
But I don't (at least not with TVH 4.3)

According to kodi.log, Kodi sends HTTP requests to tvheadend backend (directly, not via pvr.hts), and response from tvheadend for this requests is 404 (page not found). Whether tvheadend writes this to its logs (or changed something recently here), is completely up to tvheadend. we cannot derive from this what the actual fault / cause is.

**Comment by eldersixpack13** [comment] 2024-07-23 12:56
My bad: I saved my previous comment to soon.

After double checking TVH restart behaviour I need to correct "TVH fills it's log's with the error too". 
Although I yesterday have seen it didn't.

Sorry !

**Comment by eldersixpack13** [comment] 2024-07-24 17:33
could *I* to help fixing this or should I provide more info's ?

anyway:
did two runs
1. kodi debug on and component logging for some parts 
2. kodi debug on and debug on on TVH and PVR

I didn't really find something usefull, apart (what jumps to my eyes [maybe irrelevant]):
after the Curlfile error message (Failed ...404) in the log's or debug-traces appeared something like a http-page header [ I'm not an expert of http] like "doctype"-$Something and one or more lines - to me - like garbage, the repeating sign "@"

what got my attention was: both lines were ending with an "^M"

edititor was the MC buildin editor on LE13  

let me know if could do something !

**Comment by Flole998** [comment] 2024-08-02 20:23
@ksooo I have seen something similar, at least in Tvheadends logs. I think I can give a quick explanation on what is happening: Tvheadend seems to send a channelIcon link/path, even if there is no channelIcon, at least in certain cases (I guess if one is defined but not found). I will see if there is any way to prevent that.

**Comment by ksooo** [comment] 2024-08-02 20:30
> Tvheadend seems to send a channelIcon link/path, even if there is no channelIcon, at least in certain cases (I guess if one is defined but not found). I will see if there is any way to prevent that.

Thanks for the explanation. So, closing this issue as it needs to be fixed by tvheadend.

**Closed by ksooo** 2024-08-02 20:30 UTC
Labels: Triage: Needed

**Comment by Flole998** [comment] 2024-08-02 20:36
Actually this seems to be "intended", there are 4 iterations here:
https://github.com/tvheadend/tvheadend/blob/b774bdd25351e51eba0282ccf7c65904dc1b5655/src/channels.c#L1086

So I would rather say, that this is a configuration error: An invalid channel icon is specified for a channel. Tvheadends behavior seems to be a little weird though (we send a picon link even though we know, that it does not exist??)

**Comment by eldersixpack13** [comment] 2024-08-04 13:32
configuration error

on my end ?

**Comment by Flole998** [comment] 2024-08-04 14:05
There isn't really a way to specify "this channel has no icon", so it is a little bit of both: A channel icon that doesnt exist is specified (and there is no way to say "no icon"), and Tvheadend presents the channel icon to clients, even though it knows (or could know) it doesn't exist,

**Comment by eldersixpack13** [comment] 2024-08-04 16:09
if TVH knows or could know he/she/it is doing wrong, TVH should prevent doing so !

**Comment by ksooo** [comment] 2024-08-04 17:16
Can you guys move this discussion to somewhere else, please. This is a closed issue and every time you post here lot of people get a ping.
