### ISSUE TITLE
It doesn't sort the library correctly

### ISSUE THREAD

**Issue by Marioteli** [xbmc/xbmc#21165] opened 2022-03-22 08:37 UTC
### Describe the error

Here is a clear and concise description of what the problem is:

Well, I really don't know if it's a mistake or not, but I would like to create a universe of Marvel movies with my movies, and searching the internet I found this guide.

https://kodi.wiki/view/HOW-TO:Movie_universe

To create universes in kodi, well, as the guide says.

"It does not interfere with movie sets and library listings and their classification orders"

Then I decided to follow the step-by-step guide and when scraping my entire library in Kodi I realized that in the general library it does not sort the movies that are in the universe by name.

Example: Marcel universe / UCM001-Captain America sees in kodi with the nomenclatures "UCM001" and therefore it is ordered in the U and not in the C

## Expected behavior

Here is a clear and concise description of what was expected to happen:

Well, if in the guide it says that the nomenclature does not interfere, I expected that "UCM001" would not have to read kodi as the beginning of the letter to order and that it would only be a reference to order within the universe.

## Real behavior

The real behavior is that kodi if it reads it as the beginning of the letter and therefore "UCM" is ordered as such in the "U"

## Possible solution

The solution I think would be for Kodi not to read because it is a nomenclature.

### To Play

1.

2.

3.

### Debuglog

The debugging log can be found here:

### Screenshots

Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if applicable)

Here is an additional context or explanation that could help:

Try to order my entire library so that the saga or universe does not interfere with the general library.

### Your environment

Operating system used:

- [x] Android

- [ ] iOS

- [ ] tvOS

- [ ] Linux

- [ ] OSX

- [ ] Windows

- [ ] Windows UWP

- Operating system version/name:

- Kodi version:

Kodi matrix 19.3

*Note: Once the problem is made, we ask you to update it with new information or versions of Kodi if necessary.

The Kodi team will consider your problem report, however, we will not make any promise that the problem will be solved.

**Comment by KarellenX** [comment] 2022-03-22 17:50
@Marioteli 

This is not a bug report. I will close this report.
Please ask your question on the forum... https://forum.kodi.tv/index.php

Have you scraped the movies into your library? 
"UCM" is a part of the filename. Library listings use scraped titles. Somewhere you have gone wrong in your setup.
Provide a screenshot of the listing that shows the wrong order.
Also provide a debuglog that captures an Update library.

Thanks.

**Closed by KarellenX** 2022-03-22 17:50 UTC
Labels: Ignored rules, Triage: Needed
