### ISSUE TITLE
Japanese plot is distorted in "Movie" at 21.1

### ISSUE THREAD

**Issue by london-saito** [xbmc/xbmc#25674] opened 2024-08-28 01:46 UTC
Japanese plot is distorted in "Movie" at 21.1
Characters disappear at line break

21.0 is No problem

**Comment by neo1973** [comment] 2024-08-28 14:33
This refers to https://forum.kodi.tv/showthread.php?tid=378515&pid=3207736#pid3207736 I believe.

**Comment by scott967** [comment] 2024-08-29 23:39
Looks to be due to PR#25001 backport of PR#24905

Japanese/Chinese generally don't use whitespace between words so word wrap rules vary, eg. Kinsoku Shori.  Looking at a textbox control with <align>justify</align> when Japanese line is broken, the first codepoint after the break is not rendered on the following line.

**Comment by fuzzard** [comment] 2024-08-31 05:19
Will close this as duplicate of #25684 as it has more info/images displaying the issue

**Closed by fuzzard** 2024-08-31 05:19 UTC
Labels: Ignored rules, Triage: Needed
