### ISSUE TITLE
Kodi 21.1 crashes on Remote Desktop launch - Windows 11

### ISSUE THREAD

**Issue by btankwart** [xbmc/xbmc#25777] opened 2024-10-01 14:29 UTC
### Describe the bug
Kodi version 21.1 does not start completely when I'm connected to my PC via Remote Desktop Connection. The application closes after displaying the splash screen, without showing the main menu.

## Expected Behavior
Kodi version 21.1 should start completely and display the main menu, even when I'm connected to my PC via Remote Desktop Connection, as it does with version 20.0.

## Actual Behavior
Kodi version 21.1 initially shows the splash screen, but then abruptly terminates without loading the main menu or allowing any further interaction.

## Possible Fix
A possible solution could be to investigate the changes between version 20.0 and 20.1 regarding graphics processing or remote connections. There might be an issue with graphics initialization under certain remote conditions.

### To Reproduce
1. Connect to the PC via Remote Desktop Connection.
2. Launch Kodi version 21.1.
3. Observe the splash screen appearing.
4. The application closes before the main menu loads.

### Debuglog
The debuglog can be found here:
[kodi.log](https://github.com/user-attachments/files/17211255/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:
[You could insert screenshots of the splash screen or error message here, if available]

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:
- Kodi version 21.0 works flawlessly under the same conditions (Remote Desktop Connection).
- The problem only occurs with version 21.1.
- Local execution of Kodi 21.1 (without Remote Desktop Connection) has not been tested.

### Your Environment
Used Operating system:
 - [ ] Windows
 - Operating system version/name: Windows 11 Pro, Version 23H2 (Build 22631.4249)
 - Kodi version: 21.1 (problem) / 20.0 (works)

**Comment by thexai** [comment] 2024-10-02 14:25
This is already fixed on Omega and master nightlies:

Please use a recent build from here:
https://mirrors.kodi.tv/nightlies/windows/win64/Omega/

You can install it on top of Omega 21.1

See: https://github.com/xbmc/xbmc/pull/25648

Duplicate of https://github.com/xbmc/xbmc/issues/25635

**Closed by thexai** 2024-10-02 14:25 UTC
Labels: Platform: Windows, Triage: Needed, v21 Omega
