### ISSUE TITLE
Kodi mistakenly believed that the monitor still supports HDR

### ISSUE THREAD

**Issue by TianZerL** [xbmc/xbmc#24615] opened 2024-02-01 10:38 UTC
### Describe the bug
My monitor has a switch (an option in OSD) to control HDR, once it disabled, Windows will treat it as a monitor without HDR support.

If I enable HDR on my monitor and then use Kodi to play some HDR videos, everything works fine. But next time, I disabled HDR on my monitor, kodi will still treat my monitor to support HDR, and use the wrong tone mapping to play HDR content in SDR mode.

## Expected Behavior
Kodi should correctly identify whether the current monitor supports HDR.

### To Reproduce

1. Run Kodi with monitor's HDR enabled.
2. Disable HDR on monitor and run kodi again.

### Debuglog

The debuglog can be found here:
[kodi.log](https://github.com/xbmc/xbmc/files/14123694/kodi.log) 
(HDR disabled on my monitor, and windows11 report there is no HDR support)

### Screenshots 
Here are some links or screenshots to help explain the problem:

Already disabled HDR on my monitor but kodi still report it support:
![屏幕截图 2024-02-01 182647](https://github.com/xbmc/xbmc/assets/41182852/dbf743f1-b30d-4bc6-99d7-c725ee6b9f6c)

Wrong tone mapping:
![屏幕截图 2024-02-01 182730](https://github.com/xbmc/xbmc/assets/41182852/6f15f124-97df-47b4-aa9c-7bb7bbbfe223)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 11 23H2
 - Kodi version: kodi 21 beta 2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CrystalP** [comment] 2024-02-03 07:55
There are curious things happening in the log, Kodi successfully makes Windows switch the screen to HDR even if you wrote that it is not possible in Windows display settings screen.
I suspect your screen reports wide color gamut even with HDR capabilities turned off and this is not detected correctly.

Please try this test build, it will log additional information about the screen.
https://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20240203-7c53c95e-log-additional-screeninfo-x64.exe

Try once with screen osd HDR setting off and and a second execution with the setting on for comparison. Restart Kodi in between. That will produce 2 log files to upload please.

**Comment by TianZerL** [comment] 2024-02-03 09:50
@CrystalP

> There are curious things happening in the log, Kodi successfully makes Windows switch the screen to HDR even if you wrote that it is not possible in Windows display settings screen.

I suspect that the wrong tone mapping I saw is because kodi beveiled that HDR switch is successful and passthrough HDR to SDR monitor, making the image appear overexposed.

[kodi_hdr_off.log](https://github.com/xbmc/xbmc/files/14150896/kodi_hdr_off.log)
[kodi_hdr_on.log](https://github.com/xbmc/xbmc/files/14150897/kodi_hdr_on.log)

**Comment by CrystalP** [comment] 2024-02-04 16:57
OK there is a way to distinguish that type of monitor, but I'm not sure about the fix.
There are known AMD driver issues with color spaces and it could be one of them. With no information about Intel and NVIDIA GPU with a similar screen it's not possible to know...

Does the same thing happen with 20.2 and 21alpha3? (alpha still here https://mirrors.kodi.tv/snapshots/windows/win64/)

As a work around, turning off "Adjust display HDR mode" should give you normal playback.

**Comment by TianZerL** [comment] 2024-02-04 17:16
@CrystalP

I do have tried to turn off auto switch HDR, and it makes the image very dark, tone mapping still not work properly.

**Comment by CrystalP** [comment] 2024-02-04 19:28
The Shield is Android-based and cannot be compared. Most of the HDR support is platform specific.

It's normal for Kodi on Windows to report the monitor as HDR.

I asked specifically about 21a3 and 20.2 because they included a change for an AMD color space problems. Older or more recent versions don't have it. Please try them on the Windows computer.

Would you have a laptop (Intel) that could be connected to the same monitor or an NVIDIA gpu to see what happens.

With HDR auto switch off in Kodi and the dark picture, could you provide a screenshot of the video debug screen (press Alt-O while playing)

**Comment by TianZerL** [comment] 2024-02-05 05:39
@CrystalP 

> I asked specifically about 21a3 and 20.2 because they included a change for an AMD color space problems. Older or more recent versions don't have it. Please try them on the Windows computer.

I did try them on 5700XT Win11 PC, both of them not work.

> Would you have a laptop (Intel) that could be connected to the same monitor or an NVIDIA gpu to see what happens.

I used my Ryzen 3500U with Vega8 laptop connected to same monitor via HDMI (DP for 5700XT) to test and got interesting result. The laptop has old version driver (23.9.2) and windows update (Sep 2023).

I tried different variables:
- driver 23.9.2(GCN), Windows 11 updated to September 2023
- driver 24.1.1(GCN), Windows 11 updated to September 2023
- driver 24.1.1(GCN), Windows 11 updated to Latest

All of them can report HDR support properly in Kodi.

So, I think this is related to drivers, GCN and RDNA drivers are different things.

> With HDR auto switch off in Kodi and the dark picture, could you provide a screenshot of the video debug screen (press Alt-O while playing)

![屏幕截图 2024-02-05 133740](https://github.com/xbmc/xbmc/assets/41182852/60d016aa-284a-40df-888a-2b9c868d828a)

**Comment by CrystalP** [comment] 2024-02-06 17:01
This test build will detect the screen as HDR or not depending on the screen switch. Please provide a debug log of playing with switch off (SDR mode) and advise if picture is normal.
https://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20240206-9129de8d-log-additional-screeninfo-x64.exe

If you get a "normal" tone mapped picture then something strange is going on and I'd also need a debug log with beta2 or later nightly for comparison.

Did you try cycling through the tone mapping algorithms just in case?
Did you try the pixel shaders render method?

**Comment by TianZerL** [comment] 2024-02-06 18:08
@CrystalP 

> Did you try cycling through the tone mapping algorithms just in case?

I don't find any option that I can change tone mapping algorithms in kodi.

Test results:
|Kodi Version|OSD HDR|Render method|Tone mapping works properly|Log|
|---|---|---|---|---|
|21 Beta2|OFF|DXVA|No (dark)|[kodi_21beta2_HDR_off_dxva.log](https://github.com/xbmc/xbmc/files/14184399/kodi_21beta2_HDR_off_dxva.log)|
|21 Beta2|OFF|Pixel shader|Yes|[kodi_21beta2_HDR_off_pixelshader.log](https://github.com/xbmc/xbmc/files/14184401/kodi_21beta2_HDR_off_pixelshader.log)|
|21 Test-build|OFF|DXVA|No (dark)|[kodi_21test_HDR_off_dxva.log](https://github.com/xbmc/xbmc/files/14184402/kodi_21test_HDR_off_dxva.log)|
|21 Test-build|OFF|Pixel shader|Yes|[kodi_21test_HDR_off_pixelshader.log](https://github.com/xbmc/xbmc/files/14184403/kodi_21test_HDR_off_pixelshader.log)|

**Comment by CrystalP** [comment] 2024-02-07 02:20
Thanks. This shows clearly that AMD did something to the dxva color conversion YCBCR_STUDIO_G22_TOPLEFT_P2020 to RGB_FULL_G22_NONE_P709 used by Kodi.

If not done already, just in case, please reset the driver settings to default.
Did things ever work correctly with the 5700XT? It would mean that earlier versions of the RDNA driver were fine because Kodi 20 and 21 do tone mapping the same way (not sure about 19, I wasn't around).

Selection of tone mapping algorithm: during playback press Enter to bring up the OSD, navigate to settings > video settings. Tone mapping is close to the bottom.

I can think of two other things to try.

- Set Settings > Player > Use high precision processing to OFF and set Settings > System > Display > Use 10 bit for SDR to Never. It ensures that the dxva processor outputs 8 bit data. Please provide a debug log.
- Please try with tone mapping off (see above access to tone mapping algo/off), in case there is "double" tone mapping. No need for debug log.

**Comment by TianZerL** [comment] 2024-02-07 04:30
@CrystalP 

> Did things ever work correctly with the 5700XT? It would mean that earlier versions of the RDNA driver were fine because Kodi 20 and 21 do tone mapping the same way (not sure about 19, I wasn't around).

Yes, 5700XT used to work fine. Not sure the driver version it use to work, recently I have updated my driver to 24.1.1. 

> Set Settings > Player > Use high precision processing to OFF and set Settings > System > Display > Use 10 bit for SDR to Never. It ensures that the dxva processor outputs 8 bit data. Please provide a debug log.

It is not work, picture just keeps dark. [kodi_ensure_8bit_DXVA.log](https://github.com/xbmc/xbmc/files/14189045/kodi_ensure_8bit_DXVA.log)


> Please try with tone mapping off (see above access to tone mapping algo/off), in case there is "double" tone mapping. No need for debug log.

All of the tone mapping methods not work, including off, picture is dark. 
I also tried to change output settings in AMD driver: 10bit to 8bit, FULL RGB to YCbCr444, and nothing helped.

**Comment by CrystalP** [comment] 2024-02-10 18:00
Thanks for your testing.

The hdr detection can be fixed in v21.

However the dim picture is caused by newer driver versions breaking the color conversion by the dxva processor and the workaround for now is to use the "Pixel Shaders" render method.

**Comment by CrystalP** [comment] 2024-02-10 21:24
If you had a chance to figure out when drivers started having the issue it would help decide what to do in the next dev cycle (as you may know v21 is almost finished).

**Closed** 2024-06-22 22:58 UTC
Labels: Platform: Windows, Triage: Has proposed fix

**Comment by CrystalP** [comment] 2024-12-16 19:32
@TianZerL does v22 fix the issue that your screen was detected as HDR capable even with the switch off?
Please try a nightly v22.
