### ISSUE TITLE
Build is broken with fmt 10.0.0

### ISSUE THREAD

**Issue by bkuhls** [xbmc/xbmc#23389] opened 2023-06-11 12:03 UTC
### Describe the bug
Build is broken with fmt 10.0.0 (also tested with https://github.com/fmtlib/fmt/commit/de0757b578244e0bf7ac50007fb5e25fcc899c7c):
```
/home/buildroot/kodi/output/build/kodi-912343ba35f1bff8ed66b882c97ba948fd3f1169/xbmc/filesystem/CurlFile.cpp:1381:14:   required from here
/home/buildroot/kodi/output/per-package/kodi/host/x86_64-buildroot-linux-gnu/sysroot/usr/include/fmt/core.h:1691:7: error: static assertion failed: Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt
 1691 |       formattable,
      |       ^~~~~~~~~~~
```

### Your Environment
Used Operating system:

 - [x] Linux

 - Operating system version/name: buildroot
 - Kodi version: https://github.com/xbmc/xbmc/tree/5bf464cbc6c518601a00fdfce27261ecba594e26

**Comment by thexai** [comment] 2023-06-27 13:23
Duplicate of https://github.com/xbmc/xbmc/issues/23451  (keep the other as seems more complete report)

**Closed by thexai** 2023-06-27 13:23 UTC
Labels: Ignored rules, Triage: Needed
