### ISSUE TITLE
Subtitle color is not taken into account when playing DoVi files (Dobly Vision)

### ISSUE THREAD

**Issue by guilamu** [xbmc/xbmc#20519] opened 2021-11-14 17:55 UTC
### Describe the bug

Subtitle color is not taken into account when playing DoVi files (Dobly Vision). Tested on Nvidia Shield TV Pro with Android 11.

## Expected Behavior

Subtitle color setup in the expert menu should be taken into account when playing DoVi files (Dobly Vision).

## Actual Behavior

Subtitle color setup in the expert menu is not taken into account when playing DoVi files (Dobly Vision).

### To Reproduce

1. Go into the advanced setup of the subtitles. Choose anything but white (light grey, or yellow for example)
2. Open a DoVi file with emebed subtitles
3. Subtitles are white.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 11
 - Kodi version: 19.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment] 2021-11-14 19:31
@guilamu subtitles have seen a huge refactoring in v20 and it includes a new render. Any way you can give a try to a nightly build and check if the issue is still there?
I mean, to be honest there's little chance anyone will care anymore for the state of subtitles in v19. However, it'd be nice to know if we fixed this in the upcoming v20.

**Comment by guilamu** [comment] 2021-11-14 19:34
@enen92 Thank you very much for your reply and the amazing work made on Kodi. I'll report back as soon as I have a minute to try a nighty build of v20.

**Comment by thexai** [comment] 2021-11-14 21:55
> 2. Open a DoVi file with emebed subtitles

A small detail to take into account is the format of the subtitles: that is, if they are PGS (graphics) it makes no sense to consider changing the color...

**Comment by guilamu** [comment] 2021-11-15 07:54
> 
> 
> > 1. Open a DoVi file with emebed subtitles
> 
> A small detail to take into account is the format of the subtitles: that is, if they are PGS (graphics) it makes no sense to consider changing the color...
> 
> MediaInfo of source is helpful here

Obvisouly a good point, but the subtitles are not PGS of course:

`General
Format                                   : MPEG-4
Format profile                           : Base Media / Version 2
Codec ID                                 : mp42 (isom/mp42/dby1)
File size                                : 1.07 GiB
Duration                                 : 6 min 40 s
Overall bit rate mode                    : Variable
Overall bit rate                         : 22.9 Mb/s
Encoded date                             : UTC 2021-11-11 20:43:05
Tagged date                              : UTC 2021-11-11 20:43:05
Writing application                      : GPAC-1.1.0-DEV-rev1248-g3e4a34873-master

Video
ID                                       : 1
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L5.2@Main
HDR format                               : Dolby Vision, Version 1.0, dvhe.05.06, BL+RPU
Codec ID                                 : dvhe
Codec ID/Info                            : High Efficiency Video Coding with Dolby Vision
Duration                                 : 6 min 37 s
Bit rate                                 : 22.3 Mb/s
Width                                    : 3 840 pixels
Height                                   : 2 160 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0 (Type 0)
Bit depth                                : 10 bits
Bits/(Pixel*Frame)                       : 0.112
Stream size                              : 1.03 GiB (97%)
Default                                  : Yes
Alternate group                          : 1
Encoded date                             : UTC 2021-11-11 20:43:02
Tagged date                              : UTC 2021-11-11 20:52:45
Color range                              : Full
Codec configuration box                  : hvcC+dvcC

Audio
ID                                       : 2
Format                                   : E-AC-3 JOC
Format/Info                              : Enhanced AC-3 with Joint Object Coding
Commercial name                          : Dolby Digital Plus with Dolby Atmos
Codec ID                                 : ec-3
Duration                                 : 6 min 40 s
Source duration                          : 6 min 37 s
Bit rate mode                            : Constant
Bit rate                                 : 768 kb/s
Maximum bit rate                         : 811 kb/s
Channel(s)                               : 6 channels
Channel layout                           : L R C LFE Ls Rs
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Compression mode                         : Lossy
Stream size                              : 36.6 MiB (3%)
Source stream size                       : 36.4 MiB (3%)
Language                                 : English
Service kind                             : Complete Main
Default                                  : Yes
Alternate group                          : 1
Tagged date                              : UTC 2021-11-11 20:52:45
Complexity index                         : Not present / 16
Number of dynamic objects                : 15
Bed channel count                        : 1 channel
Bed channel configuration                : LFE

Text #1
ID                                       : 4
Format                                   : Timed Text
Codec ID                                 : tx3g
Duration                                 : 5 min 46 s
Bit rate mode                            : Variable
Bit rate                                 : 50 b/s
Stream size                              : 2.13 KiB (0%)
Language                                 : English
Forced                                   : No
Encoded date                             : UTC 2021-11-11 20:43:06
Tagged date                              : UTC 2021-11-11 20:52:45

Text #2
ID                                       : 5
Format                                   : Timed Text
Codec ID                                 : tx3g
Duration                                 : 5 min 54 s
Bit rate mode                            : Variable
Bit rate                                 : 65 b/s
Stream size                              : 2.83 KiB (0%)
Title                                    : SDH
Language                                 : English
Forced                                   : No
Encoded date                             : UTC 2021-11-11 20:43:06
Tagged date                              : UTC 2021-11-11 20:52:45

Text #3
ID                                       : 6
Format                                   : Timed Text
Codec ID                                 : tx3g
Duration                                 : 6 min 35 s
Bit rate mode                            : Variable
Bit rate                                 : 40 b/s
Stream size                              : 1.95 KiB (0%)
Language                                 : Danish
Forced                                   : No
Encoded date                             : UTC 2021-11-11 20:43:06
Tagged date                              : UTC 2021-11-11 20:52:45

Text #4
ID                                       : 7
Format                                   : Timed Text
Codec ID                                 : tx3g
Duration                                 : 6 min 35 s
Bit rate mode                            : Variable
Bit rate                                 : 43 b/s
Stream size                              : 2.08 KiB (0%)
Language                                 : German
Forced                                   : No
Encoded date                             : UTC 2021-11-11 20:43:06
Tagged date                              : UTC 2021-11-11 20:52:45

Text #5
ID                                       : 8
Format                                   : Timed Text
Codec ID                                 : tx3g
Duration                                 : 6 min 35 s
Bit rate mode                            : Variable
Bit rate                                 : 45 b/s
Stream size                              : 2.20 KiB (0%)
Title                                    : Latin American
Language                                 : Spanish
Forced                                   : No
Encoded date                             : UTC 2021-11-11 20:43:06
Tagged date                              : UTC 2021-11-11 20:52:45

Text #6
ID                                       : 9
Format                                   : Timed Text
Codec ID                                 : tx3g
Duration                                 : 6 min 35 s
Bit rate mode                            : Variable
Bit rate                                 : 44 b/s
Stream size                              : 2.14 KiB (0%)
Language                                 : Spanish
Forced                                   : No
Encoded date                             : UTC 2021-11-11 20:43:06
Tagged date                              : UTC 2021-11-11 20:52:45

Text #7
ID                                       : 10
Format                                   : Timed Text
Codec ID                                 : tx3g
Duration                                 : 6 min 35 s
Bit rate mode                            : Variable
Bit rate                                 : 43 b/s
Stream size                              : 2.06 KiB (0%)
Language                                 : Finnish
Forced                                   : No
Encoded date                             : UTC 2021-11-11 20:43:06
Tagged date                              : UTC 2021-11-11 20:52:45

Text #8
ID                                       : 11
Format                                   : Timed Text
Codec ID                                 : tx3g
Duration                                 : 6 min 35 s
Bit rate mode                            : Variable
Bit rate                                 : 44 b/s
Stream size                              : 2.13 KiB (0%)
Language                                 : French
Forced                                   : No
Encoded date                             : UTC 2021-11-11 20:43:06
Tagged date                              : UTC 2021-11-11 20:52:45

Text #9
ID                                       : 12
Format                                   : Timed Text
Codec ID                                 : tx3g
Duration                                 : 6 min 35 s
Bit rate mode                            : Variable
Bit rate                                 : 45 b/s
Stream size                              : 2.17 KiB (0%)
Language                                 : Indonesian
Forced                                   : No
Encoded date                             : UTC 2021-11-11 20:43:06
Tagged date                              : UTC 2021-11-11 20:52:45

Text #10
ID                                       : 13
Format                                   : Timed Text
Codec ID                                 : tx3g
Duration                                 : 6 min 35 s
Bit rate mode                            : Variable
Bit rate                                 : 43 b/s
Stream size                              : 2.07 KiB (0%)
Language                                 : Italian
Forced                                   : No
Encoded date                             : UTC 2021-11-11 20:43:06
Tagged date                              : UTC 2021-11-11 20:52:45

Text #11
ID                                       : 14
Format                                   : Timed Text
Codec ID                                 : tx3g
Duration                                 : 6 min 35 s
Bit rate mode                            : Variable
Bit rate                                 : 42 b/s
Stream size                              : 2.05 KiB (0%)
Language                                 : Japanese
Forced                                   : No
Encoded date                             : UTC 2021-11-11 20:43:06
Tagged date                              : UTC 2021-11-11 20:52:45

Text #12
ID                                       : 15
Format                                   : Timed Text
Codec ID                                 : tx3g
Duration                                 : 6 min 35 s
Bit rate mode                            : Variable
Bit rate                                 : 54 b/s
Stream size                              : 2.60 KiB (0%)
Language                                 : Korean
Forced                                   : No
Encoded date                             : UTC 2021-11-11 20:43:06
Tagged date                              : UTC 2021-11-11 20:52:45

Text #13
ID                                       : 16
Format                                   : Timed Text
Codec ID                                 : tx3g
Duration                                 : 6 min 35 s
Bit rate mode                            : Variable
Bit rate                                 : 45 b/s
Stream size                              : 2.18 KiB (0%)
Language                                 : Malay
Forced                                   : No
Encoded date                             : UTC 2021-11-11 20:43:06
Tagged date                              : UTC 2021-11-11 20:52:45

Text #14
ID                                       : 17
Format                                   : Timed Text
Codec ID                                 : tx3g
Duration                                 : 6 min 35 s
Bit rate mode                            : Variable
Bit rate                                 : 41 b/s
Stream size                              : 1.96 KiB (0%)
Language                                 : Norwegian Bokmal
Forced                                   : No
Encoded date                             : UTC 2021-11-11 20:43:06
Tagged date                              : UTC 2021-11-11 20:52:45

Text #15
ID                                       : 18
Format                                   : Timed Text
Codec ID                                 : tx3g
Duration                                 : 6 min 35 s
Bit rate mode                            : Variable
Bit rate                                 : 42 b/s
Stream size                              : 2.04 KiB (0%)
Language                                 : Dutch
Forced                                   : No
Encoded date                             : UTC 2021-11-11 20:43:06
Tagged date                              : UTC 2021-11-11 20:52:45

Text #16
ID                                       : 19
Format                                   : Timed Text
Codec ID                                 : tx3g
Duration                                 : 6 min 35 s
Bit rate mode                            : Variable
Bit rate                                 : 42 b/s
Stream size                              : 2.02 KiB (0%)
Language                                 : Polish
Forced                                   : No
Encoded date                             : UTC 2021-11-11 20:43:06
Tagged date                              : UTC 2021-11-11 20:52:45

Text #17
ID                                       : 20
Format                                   : Timed Text
Codec ID                                 : tx3g
Duration                                 : 6 min 35 s
Bit rate mode                            : Variable
Bit rate                                 : 45 b/s
Stream size                              : 2.18 KiB (0%)
Title                                    : Brazilian
Language                                 : Portuguese
Forced                                   : No
Encoded date                             : UTC 2021-11-11 20:43:06
Tagged date                              : UTC 2021-11-11 20:52:45

Text #18
ID                                       : 21
Format                                   : Timed Text
Codec ID                                 : tx3g
Duration                                 : 5 min 54 s
Bit rate mode                            : Variable
Bit rate                                 : 78 b/s
Stream size                              : 3.39 KiB (0%)
Language                                 : Portuguese
Forced                                   : No
Encoded date                             : UTC 2021-11-11 20:43:06
Tagged date                              : UTC 2021-11-11 20:52:45

Text #19
ID                                       : 22
Format                                   : Timed Text
Codec ID                                 : tx3g
Duration                                 : 6 min 35 s
Bit rate mode                            : Variable
Bit rate                                 : 44 b/s
Stream size                              : 2.12 KiB (0%)
Language                                 : Portuguese
Forced                                   : No
Encoded date                             : UTC 2021-11-11 20:43:06
Tagged date                              : UTC 2021-11-11 20:52:45

Text #20
ID                                       : 23
Format                                   : Timed Text
Codec ID                                 : tx3g
Duration                                 : 6 min 35 s
Bit rate mode                            : Variable
Bit rate                                 : 42 b/s
Stream size                              : 2.04 KiB (0%)
Language                                 : Swedish
Forced                                   : No
Encoded date                             : UTC 2021-11-11 20:43:06
Tagged date                              : UTC 2021-11-11 20:52:45

Text #21
ID                                       : 24
Format                                   : Timed Text
Codec ID                                 : tx3g
Duration                                 : 6 min 35 s
Bit rate mode                            : Variable
Bit rate                                 : 100 b/s
Stream size                              : 4.85 KiB (0%)
Language                                 : Thai
Forced                                   : No
Encoded date                             : UTC 2021-11-11 20:43:06
Tagged date                              : UTC 2021-11-11 20:52:45

Text #22
ID                                       : 25
Format                                   : Timed Text
Codec ID                                 : tx3g
Duration                                 : 6 min 35 s
Bit rate mode                            : Variable
Bit rate                                 : 41 b/s
Stream size                              : 1.98 KiB (0%)
Title                                    : Traditional
Language                                 : Chinese
Forced                                   : No
Encoded date                             : UTC 2021-11-11 20:43:06
Tagged date                              : UTC 2021-11-11 20:52:45

Text #23
ID                                       : 26
Format                                   : Timed Text
Codec ID                                 : tx3g
Duration                                 : 6 min 35 s
Bit rate mode                            : Variable
Bit rate                                 : 43 b/s
Stream size                              : 2.07 KiB (0%)
Title                                    : Traditional (Hong Kong)
Language                                 : Chinese
Forced                                   : No
Encoded date                             : UTC 2021-11-11 20:43:06
Tagged date                              : UTC 2021-11-11 20:52:45

Menu
00:06:38.607                             : Credits

`

**Comment by CastagnaIT** [comment] 2021-11-15 16:47
tx3g colors in Kodi 19 are broken, has been fixed on Kodi 20
good to know if you can confirm

**Comment by guilamu** [comment] 2021-11-16 21:12
I can confirm this is not working on Kodi 20 alpha either.

I tested with this version : org.xbmc.kodi_20.0-ALPHA1-1990102_minAPI21(arm64-v8a)(nodpi).com

**Comment by enen92** [comment] 2021-11-16 21:38
Thanks for testing master. Any chance you can get a short sample of the file? Or at least extract one of the subs where the issue can be seen?

**Comment by guilamu** [comment] 2021-11-17 09:26
Sure, here's a DV with embed subtitles file for testing (only 5 min short movie, I guess we're safe copyright wise): https://mega.nz/file/jVdVTajL#KG1ulzqowYSaYZUl1na8rooQVdLhysr9pw0hj7UDPSo

I'll try your version as soon as possible.

**Comment by CastagnaIT** [comment] 2021-11-17 10:00
thanks for the sample, i have done a quick test on Windows only:

Kodi 19:
Change colors works only if you change it when the video is stopped, if you change color while in playing the color not change (from my part is a know Kodi issue)

Kodi 20:
No problems, change colors works also when in playing

**Comment by guilamu** [comment] 2021-11-17 10:07
> Change colors works only if you change it when the video is stopped

What do you mean? I've setup the color of subtitles for all videos in Kodi settings.

So it may be an Android only issue, I'll report back as soon as I've tried the latest version linked by @enen92

**Comment by quietvoid** [comment] 2021-11-18 14:57
Colors are working for me in Dolby Vision, on the FireTV Stick 4K Max.
Tested with `kodi-20211116-3f0508c0-master-armeabi-v7a`.

**Comment by enen92** [comment] 2021-11-19 20:58
Tested your sample in android tv (latest nightly) and colors work as expected.

**Comment by enen92** [comment] 2021-12-04 11:41
Closing as stalled and not reproducible. Not clear if OP has actually tested a master version.

**Closed by enen92** 2021-12-04 11:41 UTC
Labels: v19 Matrix, Issue Cleanup: Ask Reporter, Component: Subtitles, Triage: Tested and not reproduced

**Comment by guilamu** [comment] 2023-11-13 15:51
Hello,

No idea why this has been closed, this bug is still there and more than ever.

Whatever your subtitles settings are, any DOVI video with srt subtitles (emebed or not into the mkv) will be displayed with 1500 nits white burning your eyes alive for the whole movie/tv show.

Tested on the latest KODI 21 (same bug on 20).
