### ISSUE TITLE
[Kodi 21] [Android] DVDs won't start anymore

### ISSUE THREAD

**Issue by Kraxelhuber** [xbmc/xbmc#24955] opened 2024-04-07 18:51 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

On Android DVDs won't start anymore when Kodi 21 stable is installed.
This is true for ISO and folder structure (IFO) DVDs.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Opening the file would start the DVD and jump tho the first title to be played.

## Actual Behavior

Opening the file results in an error message, that there was a problem and referr to the log.

### To Reproduce

1. Install Kodi 21 on any Android Device
2. Open DVD ISO or structure
3. fail

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/rilinisomo.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

While scrolling through the logs I found the following error message

Unable to load /data/app/~~21tKzYJHPqm5dSVt4v_75w==/org.xbmc.kodi--RnuPO4K2pQyUUtbeV22LQ==/lib/arm64/libdvdnav-aarch64.so, reason: dlopen failed: cannot locate symbol "dll_fstatvfs64" referenced by "/data/app/~~21tKzYJHPqm5dSVt4v_75w==/org.xbmc.kodi--RnuPO4K2pQyUUtbeV22LQ==/lib/arm64/libdvdnav-aarch64.so"

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 21

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment] 2024-04-07 21:32
Omega nightlies should start today (fingers crossed) https://mirrors.kodi.tv/nightlies/android/, so if you could try one i believe this may have inadvertently been fixed already by https://github.com/xbmc/xbmc/pull/24894

**Comment by Kraxelhuber** [comment] 2024-04-08 07:46
RC2 did not work, too.
Seems to be a problem since beta 1?
https://forum.kodi.tv/showthread.php?tid=374761

**Comment by xiaogtw** [comment] 2024-04-08 12:39
I've tried the RC2, stable, and night versions, all with the same issue. However, if the ISO file is located in the /files/.kodi directory, it plays fine.

**Comment by DuebelWalter** [comment] 2024-04-08 19:14
## Bug report
### Describe the bug
Here is a clear and concise description of what the problem is:
Since I don't want to clutter up the bug report, I'll post my error as a comment.
Since my bug is almost the same.
If this is wrong, I will gladly post the error again separately.

I have the same problem when I try to play a real DVD. 
I try to start the DVD and get an error message: General error



I try to start the DVD and get an error message: General error. Please referr to the log.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:


Clicking on "Disk" in Kodi starts the DVD in the drive and loads the DVD menu or starts the movie

## Actual Behavior


I try to start the DVD and get an error message: General error. Please referr to the log.

## Possible Fix





### To Reproduce
Steps to reproduce the behavior:



1. Start Kodi 21 on Linux Mint 21.3 (Cinnamon)
2. Click on "Disk" - Symbol in Kodi
3. The DVD doesn't start and instead you get the following error: General error. Please referr to the log.


### Debuglog


The debuglog can be found here:
https://pastebin.com/f95xQ367

### Your Environment
Used Operating system:


 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Linux Mint 21.3
 - Kodi version: Kodi 21




*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by joseluismarti** [comment] 2024-04-10 17:49
@Kraxelhuber try [this build](https://jenkins.kodi.tv/job/android-arm64-docker/5911/artifact/kodi-20240410-0a5092e5-PR24968-arm64-v8a.apk) should work correctly

**Comment by Kraxelhuber** [comment] 2024-04-11 16:20
> @Kraxelhuber try [this build](https://jenkins.kodi.tv/job/android-arm64-docker/5911/artifact/kodi-20240410-0a5092e5-PR24968-arm64-v8a.apk) should work correctly

Tested on Samsung Galaxy Tab 5S with Android and both ISO and IFO worked.
Thanks

**Comment by ksooo** [comment] 2024-04-15 11:13
Fix merged for master (v22) and Omega. Closing this issue.

**Closed by ksooo** 2024-04-15 11:13 UTC
Labels: Platform: Android, Triage: Needed, v21 Omega
