### ISSUE TITLE
watched status not set, resp. advancedsettings is ignored

### ISSUE THREAD

**Issue by freuli0815** [xbmc/xbmc#15331] opened 2019-01-25 10:36 UTC
## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I set in advancedsettings, that a video shall be marked as watched automatically after having 80% of the video seen. 

## Actual Behavior

Even after 90% the video is not marked as watched

### To Reproduce

1. starting video
2.watch 80% or fast forward
3.go back to start screen

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/roduwoxubu.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 64bit
 - Kodi **version:RC5.2**

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by freuli0815** [comment] 2019-01-25 12:06
as you can see on that screenshot. I started the movie on the main screen. And after 90% watching, it remains in started movies and the mark on the bottom shows partly watched.
![inkedscreenshot000_li](https://user-images.githubusercontent.com/47027675/51745031-ee384780-20a1-11e9-8f63-3d18fd4e318d.jpg)

**Comment by arnova** [comment] 2019-01-27 08:37
I've also seen this happen but it looks like a GUI problem because navigating away and back to the window fixes it for me. Did you try reentering the window when this occurred?

**Comment by MartijnKaijser** [comment] 2019-02-10 18:55
My guess this is the GUI simply not updating when it needs to. Navigating away and going back makes the GUI reload the list

**Comment by arnova** [comment] 2019-02-11 10:04
> My guess this is the GUI simply not updating when it needs to. Navigating away and going back makes the GUI reload the list

It's not as simple as that. When it occurs (in my case) the watched-flag for all files in the current folder disappear, not just for the one that was just played. Since it's hard to reproduce I already reviewed the code responsible for this but I'm unable to pinpoint where this is coming from. Do note that I always play videos from the files section so I'm not sure whether this also happens from the various video db sections.

**Comment by freuli0815** [comment] 2019-03-06 16:48
Hello,
any update on this topic. I have still the problem.
Thanks
Markus

**Comment by arnova** [comment] 2019-03-07 07:45
> I've also seen this happen but it looks like a GUI problem because navigating away and back to the window fixes it for me. Did you try reentering the window when this occurred?

@freuli0815 : Please reply to my previous question.

**Comment by freuli0815** [comment] 2019-03-08 16:53
Hello,

sorry for late answer. No, changing the window doesn't help. Even restarting Kodi doesn't change anything. I found out something starnge. I have the same version on my nuc in the sleeping room. Also windows on it. The only difference, I have Windows home in sleeping room and Pro in living room. In sleeping room everything runs fine. Only the one in living room is not updating seen status. Any idea?
Fresh Kodi installation I tried already.
Thanks
Markus

**Comment by arnova** [comment] 2019-03-08 17:01
> Hello,
> 
> sorry for late answer. No, changing the window doesn't help. Even restarting Kodi doesn't change anything. I found out something starnge. I have the same version on my nuc in the sleeping room. Also windows on it. The only difference, I have Windows home in sleeping room and Pro in living room. In sleeping room everything runs fine. Only the one in living room is not updating seen status. Any idea?
> Fresh Kodi installation I tried already.
> Thanks
> Markus

Sounds like a skin problem. Did you try another skin (eg. Confluence) ?

**Comment by freuli0815** [comment] 2019-03-08 17:19
The other Skin I tried already. Same behaviour. Could it be windows setting related?

**Comment by freuli0815** [comment] 2019-03-08 17:24
I have to correct myself. With Confluence it ist working. But in the sleeping room it is working with Kodi 18 Skin.

**Comment by freuli0815** [comment] 2019-03-10 13:24
again an update. I tested more in sleeping room. There it is the same. The ski Estuary isn't updating the watched status mentioned in advancedsettings. Confluence is working properply.

**Comment by freuli0815** [comment] 2019-05-14 19:40
Hi, in the current Version it is still existing. Can anyone help?
Thanks

**Comment by DaVukovic** [comment] 2019-05-15 05:38
@ronie if you find he time, could you please have a look if it's a skin problem

**Comment by ronie** [comment] 2019-05-15 20:59
should be fixed by: https://github.com/xbmc/xbmc/pull/16140

**Comment by rmrector** [comment] 2019-05-16 02:29
The log is no longer available so I can't say for certain, but did you also modify `ignorepercentatend` to match? That setting is responsible for defining when resume points are created. See the wiki page [HOW-TO:Modify automatic watch and resume points](https://kodi.wiki/view/HOW-TO:Modify_automatic_watch_and_resume_points).

**Comment by DaVukovic** [comment] 2019-05-16 04:53
@rmrector `ignorepercentatend` is also already set to a default value of `8%`. See:

https://github.com/xbmc/xbmc/blob/master/xbmc/settings/AdvancedSettings.cpp#L161

@ronie tested and now if I use an advancedsettings like this: 

```
<advancedsettings>
  <video>
    <playcountminimumpercent>50.0</playcountminimumpercent>
  </video>
</advancedsettings>
```

I can confirm that the video is being marked as watched. So I can confirm this fixes this issue. Will comment on the PR for another thing.

**Comment by freuli0815** [comment] 2019-05-16 19:50
Hi guys,
thanks for fixing IT.
Stupid question. How can I geht this fix?

Regards
Markus

**Comment by rmrector** [comment] 2019-05-17 13:35
Yes, ignorepercentatend is set at 8% in the code, and not changing that in AS.xml clearly explains why the resume point exists when watching to 90%. This is a configuration issue, no code or skin changes necessary.

**Comment by DaVukovic** [comment] 2019-05-17 13:53
@rmrector 

`ignorepercentatend` means that at this percentage no resume is set anymore and a video is being marked as watched. 
`playcountminimumpercent` means that a video is being marked as watched if that percentage is reached. 

So, tbh, I don't see where `ignorepercentatend` is related for a video NOT being marked as watched if I manually set `playcountminimumpercent` in advancedsettings to 50%. Both settings can be used independently. At least that's how I understand it.

**Comment by rmrector** [comment] 2019-05-17 14:20
The problem here is that a resume point exists when the user does not expect it to, but Kodi most assuredly does mark the video as watched. That's EXACTLY what that missing setting is for.

The PR does not address any behavior, just display in a single skin. Fix the individual configuration, don't break useful display for all users of the skin.

At least try it before the PR is accepted, we can't keep smashing in uninformed hacks.

**Comment by ronie** [comment] 2019-05-17 17:25
uninformed hacks? 

well thank you!

**Comment by rmrector** [comment] 2019-05-17 22:34
@freuli0815 After you've watched an item to at least 80% and it is marked as watched, do you still want Kodi to create a resume point so you can later watch it from the end?

If not, then add `<ignorepercentatend>20</ignorepercentatend>` right next to `<playcountminimumpercent>80</playcountminimumpercent>`. That works right now.

**Comment by freuli0815** [comment] 2019-05-18 12:22
Hi,
no the resume Point isn't my Problem. The movies are not marked as watched in the GUI.
Regards
Markus

**Comment by rmrector** [comment] 2019-05-18 12:43
If a resume point is not created then the GUI WILL show the movie as watched.

If you don't want the movie to still be considered as "in progress" after you've watched it, then the resume point IS your problem, just try it.

**Comment by freuli0815** [comment] 2019-05-18 18:26
Hey guy, you are right. It worked.

Thanks!

**Comment by ronie** [comment] 2019-05-18 18:35
thanx for the confirmation!
issue can be closed.

**Closed by ronie** 2019-05-18 18:35 UTC
Labels: Component: Skin, v18 Leia
