### ISSUE TITLE
Android: Kodi18 PVR channel order issue

### ISSUE THREAD

**Issue by paulccs** [xbmc/xbmc#14854] opened 2018-11-11 15:48 UTC
### Describe the bug

Despite choosing use channels number from backend and use channel order from backend, channel 18.1 appears between channels 180 and 181.

## Expected Behavior

If channel numbers contain all numbers and a period, evaluate as a decimal.

## Actual Behavior

Currently, evaluating channel numbers as a string.

## Additional context or screenshots (if appropriate)

Kodi 17.6 against same tvheadend version/server works as expected.

### Your Environment
Used Operating system:

 - [*] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18 beta 5

 - Tvheadend version: 4.3-1529~gc8bbae504

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment] 2018-11-11 19:41
Not sure I understand this right. You tick "use channel order from backend" and expect Kodi to resort the channels?

**Comment by kevin71246** [comment] 2018-11-11 20:30
I'm confirming I see this issue as well in Android kodi-18.0-Leia_beta5-arm64-v8a.apk.  I'm using NextPVR in case that's relevant. Regardless of selecting or unselecting "Use channel order from backend" in Main settings->PVR Settings, channel order is incorrect as OP indicated.  And I also confirm this worked fine on kodi-17.6-Krypton-arm64-v8a.apk.  I agree the issue appears to be that the decimal is being ignored. Note: OTA (antenna channels) come in with decimals, like: 2.1, 2.5, 5.1, 7.1, 7.2, etc, see below on how this is relevant.  In my example below, "11.1" is being "seen" (& sorted), as if it is "111".  This happens with every channel with a decimal.

Channel Order in TV Guide from kodi-18.0-Leia_beta5-arm64-v8a.apk: (incorrect)
1.1, 1.2, 2.1, 5.1, 7.1, 7.2, 9.1, 9.2, 101, 102, 103, 11.1, 120

Channel Order in TV Guide from kodi-17.6-Krypton-arm64-v8a.apk: (Correct & expected)
1.1, 1.2, 2.1, 5.1, 7.1, 7.2, 9.1, 9.2, 11.1, 101, 102, 103, 120

**Comment by ksooo** [comment] 2018-11-12 07:13
Are you sure you sorted the channels in guide window by number? This is a new feature in Leia...

<img width="463" alt="screenshot 2018-11-12 at 08 10 28" src="https://user-images.githubusercontent.com/3226626/48332028-aa14d980-e652-11e8-84f0-0c2084df6f54.png">

**Comment by kevin71246** [comment] 2018-11-12 07:43
Yes.

**Comment by ksooo** [comment] 2018-11-12 08:06
Cannot reproduce, sorry. It works for me:

<img width="685" alt="screenshot 2018-11-12 at 08 10 13" src="https://user-images.githubusercontent.com/3226626/48334157-f1529880-e659-11e8-9c5d-6e60683b3ce5.png">

Does it really not make a difference if you untick "use backend channel numbers"? In this case, Kodi generates the channel numbers - all without dots / subchannel numbers. How can you see the "dot-issue" if you do  not use backend channel numbers?

**Comment by ksooo** [comment] 2018-11-12 08:10
As you guys both use Android, I fear this could be something Android specific (I only checked on Linux and macOS, don't have an Android dev environment). OMG.

**Comment by ksooo** [comment] 2018-11-12 08:18
YES, it is Android-specific: https://github.com/xbmc/xbmc/blob/master/xbmc/utils/SortUtils.cpp#L723 ff. plus https://github.com/xbmc/xbmc/blob/master/xbmc/utils/SortUtils.cpp#L773 ff.

There, every not-alphanumeric char (except blank) is removed from the items to sort... Don't ask me why. No idea. @peak3d do you have an advise?

**Comment by ksooo** [comment] 2018-11-12 08:21
@koying any idea?

**Comment by koying** [comment] 2018-11-12 08:43
Long story ;)
Android NDK doesn't (or at least didn't) support c++ locale, so that was a problem when sorting international chars.

What I did is to use iconv "//TRANSLIT" (http://man7.org/linux/man-pages/man1/iconv.1.html) to approximate.
Now, that translates, e.g. "é" to 2 ascii chars, something like "e'". Obviously, that's not great for sorting either, so I filtered on alphanum and blank for sorting.

The filtering done on https://github.com/xbmc/xbmc/blob/master/xbmc/utils/SortUtils.cpp#L779 can be made smarter, ofc (eg accept any chars after a numeric) but will hardly ever be perfect...

**Comment by ksooo** [comment] 2018-11-12 08:53
@koying so, adding "." to the accepted chars would be okay?

**Comment by koying** [comment] 2018-11-12 09:02
If and only if no utf8 character is translated by iconv TRANSLIT into 1 char + "." (don't ask, I have no clue ;) )

**Comment by paulccs** [comment] 2018-11-12 13:47
When I tick 'use channel order from backend', I expect Kodi to use the 
same channel order as tvheadend: 18.1, 18.2, 18.3, 27.1, ... 181, 182, 183.
Instead, it makes the order 181, 18.1, 182 .

Either way I tick the option, I can't get a true numerical sort.

Thank you!

**Comment by ksooo** [comment] 2018-11-12 19:50
I will fix it the other way round and create "proper" sort item strings.

**Comment by ksooo** [comment] 2018-11-13 06:48
Fixed in RC1.

**Closed** 2018-11-13 06:48 UTC
Labels: Android, v18 Leia

**Comment by kevin71246** [comment] 2018-11-16 02:54
Thank you!!

**Comment by vbuell** [comment] 2018-12-02 16:09
@koying 
> Android NDK doesn't (or at least didn't) support c++ locale, so that was a problem when sorting international chars.

But the sorting worked ok for previous versions of kodi. 17.6 doesn't have any issues with sorting unicode chars - tested on multiple android devices - so it's a regression.
