### ISSUE TITLE
Text-based (non-PGS) Subtitles Display at Wrong Aspect Ratio on Videos with a "Display Aspect Ratio" Flag

### ISSUE THREAD

**Issue by VicBond007** [xbmc/xbmc#20738] opened 2021-12-28 18:28 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

Plain/formatted text (SSA, ASS, etc.) subtitles (embedded or external) are displayed at the wrong aspect ratio if the video itself has a Display Aspect Ratio flag that resizes the video.  This is common for DVD rips that were ripped at 720x480, which isn't any "correct" aspect ratio but is the resolution of video stored on the DVD.  The 720x480 video carries a flag that tells the player to resize the video to conform either to a 4:3 (1.33 AR) or 16:9 (1.77 AR) aspect.  The resized video appears to be how Kodi interprets the videos "original size" (in terms of "View Mode") which is great since this is how the video is intended to be viewed, but text-based subtitles seem to be rendered using an aspect ratio calculated from the video's actual pre-scaled dimensions (720x480) and are resized when Kodi processes the Display Aspect Ratio flag.  This results in squished (4:3) or fat (16:9) subtitle text since the subtitles are being drawn, but then told to increase or decrease their width based on the aspect flag.

This does not appear to happen with image-based (PGS) subtitles.

Kodi's display window dimensions are irrelevant, so this is somewhat different than issue #14866.

I tested this with Kodi 19.1, 19.2, and 19.3.  I did not go further back than 19.1.

Screenshot comparing Kodi (left) to MPC-HC (right):
![image](https://user-images.githubusercontent.com/42912814/147594913-5cbd5349-5e05-4849-89d6-f10fb8f8d2d4.png)

Kodi is displaying video at "original size" which IS applying a 1.33 AR flag to 720x480 video, resizing it to 640x480 (same as MPC-HC).  Video is correct, and subtitles are displayed at the proper height for the point size, but the Kodi subtitles are displayed too thin (look at where the period in "horrorscope." stops as opposed to MPC-HC) since the AR flag is also being incorrectly applied to the text in Kodi.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Text-based subtitles should always render on-screen with a 1:1 aspect ratio.
Screenshot of correctly scaled video with correctly sized subs (from MPC-HC):
![image](https://user-images.githubusercontent.com/42912814/147594945-44161146-ba0f-49a9-8fe8-631900a3a529.png)

## Actual Behavior

Text-based subtitles are either squished or stretched unless the video's AR is 1.0 (1:1).
Screenshot of correctly scaled video with incorrectly scaled subs (from Kodi):
![image](https://user-images.githubusercontent.com/42912814/147594961-f10c14ca-d659-4be5-a955-c2de3775750e.png)

**Proof that Kodi is scaling subs based on the original, unscaled video dimensions:**
Screenshot of incorrectly scaled video (MPC-HC ignoring Display Aspect Ratio and playing the same video at 720x480 1:1 instead of 4:3):
![image](https://user-images.githubusercontent.com/42912814/147594985-bcd88eb6-52b3-4360-a2ae-0c68969be177.png)
In the above screenshot, you can see that the subs are still rendered at 1:1 and look perfectly fine (because the player is being told to assume that 1:1 is the correct display aspect ratio instead of 4:3), but stop at the same point as Kodi (the period is in the leftmost eyeball instead of the right one) due to the fact that the video underneath is "wider" than the flag-resized (640x480) version.  **If you resize that screenshot to 640x480, it looks exactly the same as Kodi (correct video aspect, thin, incorrect, sub aspect).**

## Possible Fix

Always display text-based subtitles at 1:1 relative to the display window.
If that's not possible (maybe the original video dimensions necessary to calculate subtitle position/relative size or whatnot), then calculate the video dimensions (for the purpose of scaling text-based subtitles) by taking the Display Aspect Ratio in account (IE: 720x480 @ 1.33 AR = 640x480 as far as subs should be concerned).

### To Reproduce

1. Play any video with a Display Aspect Ratio flag that alters the video's original resolution:
![image](https://user-images.githubusercontent.com/42912814/147595030-c2878f52-3e58-42f9-809a-62311d001b84.png)
2. Enable text-based (ASS, etc.) subtitles
3. notice that the subtitles are either thinner or fatter than they would appear in any word processor at that px size.

### Debuglog

[kodi.log](https://github.com/xbmc/xbmc/files/7785974/kodi.log)

### Screenshots
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 Pro 21H2, and also Windows 7 Pro x64
 - Kodi version: 19.x (tested 19.1 through 19.3 release versions)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by VicBond007** [comment] 2021-12-28 18:38
Not sure why this is "Ignored rules" flag.  Maybe my formatting screwed up the template...

**Comment by enen92** [comment] 2021-12-28 21:28
@VicBond007 can you provide a short sample of a video where this can be verified/tested? It would improve the chances of fixing the bug.
Thanks

**Comment by VicBond007** [comment] 2021-12-29 06:00
Here is a sample: https://drive.google.com/file/d/1taiOMKqNVEUw9l5eSfIZf6_exY0TueaS/view?usp=sharing
You'll have to download it to get the subs to show.
It is 720x480 with a 4:3 Display Aspect Ratio flag.

The file is just a clip with no audio, but I modified the subs to just show "oooooooooo" in arial bold with no outlines or shadows (so they don't throw off any measurements).  The letter "o" in arial **bold**, when displayed correctly, is a perfect circle (same height and width) so if rendered correctly, there should be a bunch of perfect circles (not eggs) at the bottom of the screen.  There are also plenty of circles in the video clip (like the Planet Hollywood sign) so you'll know if the video is scaled correctly.

The embedded sub has the lines:
PlayResX: 720
PlayResY: 480
and doesn't have the Aspect variable set (and scaleX and scaleY are both 100).  This is consistent with several (10) other SD DVD rips that I checked.  I'm also pretty sure most players ignore the PlayResX and PlayResY variables anyways.

Raw sub script:
[Script Info]
; Script generated by Aegisub 3.2.2
; http://www.aegisub.org/
ScriptType: v4.00+
PlayResX: 720
PlayResY: 480
Timer: 100.0
WrapStyle: 0

[Aegisub Project Garbage]
Last Style Storage: Default
Active Line: 4

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,60,&H00FFFFFF,&H00FFFFFF,&H000F0F0F,&H000F0F0F,-1,0,0,0,100,100,0,0,1,0,0,2,20,20,20,0

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:01.00,0:00:11.00,Default,,0,0,0,,oooooooooo
Dialogue: 0,0:00:12.00,0:00:22.00,Default,,0,0,0,,oooooooooo
Dialogue: 0,0:00:23.00,0:00:33.00,Default,,0,0,0,,oooooooooo
Dialogue: 0,0:00:34.00,0:00:44.00,Default,,0,0,0,,oooooooooo
Dialogue: 0,0:00:45.00,0:00:55.00,Default,,0,0,0,,oooooooooo
Dialogue: 0,0:00:56.00,0:01:00.00,Default,,0,0,0,,oooooooooo

**Comment by CastagnaIT** [comment] 2021-12-30 15:22
i can confirm that can be reproduced with any 4:3 video and ass/ssa subtitle (also external file),
if the sar/dar values passed to libass are not wrong (not verified) could be a bug in the old libass library used with Matrix
because on Kodi 20 i see the text rendered correctly

> I'm also pretty sure most players ignore the PlayResX and PlayResY variables anyways.

only for info these values are important for various Style parameters and coordinates, if not set not means ignored but always fallback to 288x384

**Comment by enen92** [comment] 2021-12-30 16:00
Yeap, I also cannot reproduce this on Nexus. 
Since Nexus includes a completely new subtitle renderer I won't think it's worth investing time into fix this for matrix. Changes for libass/subtitles in Nexus are too drastic for a backport.
I'll close this as won't fix and advise you to use Kodi v20 (unstable) or wait for the new release.
Thanks a lot for reporting and providing the required info.

**Closed by enen92** 2021-12-30 16:00 UTC
Labels: Triage: Needed, Component: Subtitles
