### ISSUE TITLE
Unexplainable exceptions and big red dialogue from scraper TMDB Tv Shows

### ISSUE THREAD

**Issue by bowanner** [xbmc/xbmc#25236] opened 2024-05-20 07:37 UTC
### Describe the bug
During scanning of TV Shows I frequently get a big red ugly exception warning from the TMDB Tv Shows scraper, but with no information about what actually went wrong. I have studied the log files but can't figure out other than that an episode is not identified. 

That an episode (or a movie) is not identified is of course a message to me to change something like another file name, link in the tvshow.nfo filer, etc. It would really be a user help to get a condensed and human readable (!) log o after a scan over which movies/tv shows that were problematic. 

And in my mind a scraper should not throw up such a warning dialogue just because it can't identify a file. And certainly not without explaining details. Only "Error" does not help solving the problem.

## Expected Behavior
If the problem now is that a file can't be identified (?), I would like a clear message in the standard user interface on WHAT file that is troublesome. And if I may wish, I would like a persistant (!) list in the user interface (not in a technical log) over troublesome files.

If the problem now is that a file can't be identified, there should NOT be a big red dialogue for this quite common problem. Such error messages should be reserved for real problems.

## Actual Behavior
Big red dialogue just saying "The TMDb  shows error. Check the log for more information" and nothing more. Not user friendly!

## Possible Fix
A persistant list in the user interface over files that can't be identified. Save big red error dialogues for real system errors.

### To Reproduce
Scanning any file that does not meet identification format. In a specific case I had the series "Spartacus.Blood.and.Sand" with a troublesome season setup. The cronological second season is a "prequel" to what both IMDB and TMDb has marked as "season 2", and this prequel season should perhaps not be included in the ordinary seasons. I marked it as season 00 just for test, and the scraper went bananas.

Content of tvshow.nfo:
https://www.themoviedb.org/tv/46296-spartacus/seasons

Failing (?) file:
Spartacus.Specials.s00e01.mp4

### Debuglog
Log in OneDrive: https://1drv.ms/u/s!AvdDCalEHnW-oZ48Ygxsz-Z-HQmQhg?e=deMq2q

### Screenshots 
The error dialogue vanishes so quickly that I can't catch a screenshot.

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [X ] Windows 
 - [ ] Windows UWP

 - Operating system version/name: Windows 11 Pro/64/Swedish
 - Kodi version: 21.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by MikeSiLVO** [comment] 2024-05-20 13:44
Doesn't the Event Log window show the scanner errors and which show/movie caused it?

**Comment by bowanner** [comment] 2024-05-20 14:06
Yes, the event log gives some advice. BUT having to go to the more or less hidden event log every time the scraper can't identify a file is not user friendly. Besides, if you install Kodi on Chromecast with Android TV, you have quite an adventure to first find the log, then view it. The log is also quite "talkative" and technical, and there is some effort trying to find the exceptions in the huge mass of text,

I still propose a function where I  can see a list of files that can't be identified in the user interface! Then I don't have to go into the OS and application data folders and fire up some text editor to search for "exception".

**Comment by MikeSiLVO** [comment] 2024-05-20 14:08
Sound like your talking about a log file and not the Event Log

[https://kodi.wiki/view/Event_Log](https://kodi.wiki/view/Event_Log)

**Comment by bowanner** [comment] 2024-05-20 14:34
THANK YOU very much for directing me to this gem that I have missed. Sorry!

"The Movie Database Scanner Python" is well behaved and reports to the event log. 

BUT "The TMDb TV Shows" does NOT report to the event log. Just the big red popup dialogues  with "error" and a reference to "the logfile" for every missed file. In the Kodi logfile I have to find "exceptions".

As I favor The Movie Database, I wanted to use their scrapers. Should I change?

Thanks for your advice!

**Comment by Hitcher** [comment] 2024-05-20 19:52
Got a screenshot of the big red box?

**Comment by bowanner** [comment] 2024-05-20 20:22
Sorry for the lousy quality, I had to use a camera and the dialogue is up for only a few seconds each time.

![TMDbShowsError](https://github.com/xbmc/xbmc/assets/102598393/e434c89f-394c-435e-9181-85825c93a1cb)

Or OneDrive https://1drv.ms/i/s!AvdDCalEHnW-oZ5iqHhfB2eibMMaQQ?e=ku7Yka

**Comment by Hitcher** [comment] 2024-05-20 23:47
Thanks, it's just the (small) notification dialog then:

[img]https://i.imgur.com/tXORaYo.png[/img]

From your description I thought it was something else.

**Comment by KarellenX** [comment] 2024-05-21 04:41
@bowanner 

In future, please seek assistance on the forum, and not github. I have closed this report as it is not a bug.

The error is on line 375 and repeated numerous times through the log
```No TMDb TV show id found in episode guide, this show should be refreshed or rescraped ***```

I guess you are using nfo files, and the nfo file has an invalid `<episodeguide>` and you are trying to add more episodes.
Read my post here... https://forum.kodi.tv/showthread.php?tid=370489
And follow the images at the end of the first post.

**Closed by KarellenX** 2024-05-21 04:41 UTC
Labels: Triage: Needed
