### ISSUE TITLE
Issues with interlaced MPEG2 with DXVA

### ISSUE THREAD

**Issue by yeahme49** [xbmc/xbmc#17521] opened 2020-03-19 17:11 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

When seeking forward in an interlaced MPEG2 video (1080i recorded TV show with TVHeadend) while using DXVA render, it will not seek, it just freezes and buffers. If I switch to pixel shader render, it works fine. Progressive MPEG2 recordings (720p recorded show with TVHeadend) work fine.

I don't have any issues with Kodi 18, the issues started with Kodi 19.
Another issue was opened for the same issue but was closed due to user not providing logs. Maybe he can provide his logs as well. https://github.com/xbmc/xbmc/issues/16837

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Seek forward in video without freezing

## Actual Behavior

Freeze and buffers

### To Reproduce

1. Play interlaced MPEG2 using DXVA rendering
2. Seek forward
3.

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/kicinapepe.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 64-bit
 - Kodi version: Latest nightly 19.0-ALPHA1 Git:20200318-809e36a24c

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by yeahme49** [comment] 2020-04-11 22:04
I just did some testing. I compiled https://github.com/xbmc/xbmc/commit/41964f1f925263f255767699b9f63442f9b11717 which is the commit right before the one you linked where WinRendere was refactored. Interlaced MPEG2 played fine. I then compiled https://github.com/xbmc/xbmc/commit/f47c959f0defe4e6157981cfda3023509f48ef18 and Interlaced MPEG2 does not play fine, unable to skip. So something in that commit is causing the issue, I just don't know what.

**Comment by yol** [comment] 2020-04-15 19:06
@afedchin

**Comment by thexai** [comment] 2020-04-16 09:10
I tested and seems specific Nvidia driver related bug (with Intel NUC8i3BEK works fine MPEG2 interlaced in DXVA).

However, a possible workaround is defaults to PixelShaders render for this type of interlaced content.

On RenderDXVA.cpp line 70 replace

https://github.com/xbmc/xbmc/blob/cb815b08a8995bfed42f77f3e8be6b8ba985084e/xbmc/cores/VideoPlayer/VideoRenderers/windows/RendererDXVA.cpp#L70

with

`weight -= 500;`

Is not a best solution because changes in all systems even on Intel that it works.

**Comment by djp952** [comment] 2020-04-16 14:06
Not sure it's nVidia specific; I have the problem on Intel Graphics. Easily reproduced on NUC7i7BNH (Intel Iris Plus Graphics 650) and laptop with Core i7-10510 CPU (Intel HD Graphics).  Also have other Intel systems available I can test on but have not done so.  I can try on Intel HD Graphics 4600, HD Graphics 520, and HD Graphics 615 if requested.

**Comment by thexai** [comment] 2020-04-16 15:35
If it is true that it affects the majority of HW and afedchin can not fix it (fix is the best solution) then can make sense workaround I proposed.

This only defaults to pixel shaders if render method in Settings / Player is configured in AUTO.

Not tested really in PVR or recordings only local playing MPEG2 interlaced content.

**Comment by djp952** [comment] 2020-04-25 16:29
I figured out basically what's happening here.  It appears the the DXVA renderer isn't reporting any buffers as free, so the RenderManager times out waiting for them.  While this wouldn't be the correct solution, of course, you can make the problem go away by changing this function to just return false:

bool CRendererDXVA::NeedBuffer(int idx)
{
  if (m_renderBuffers[idx]->IsLoaded())
  {
    const int numPast = m_processor->PastRefs();
    if (m_renderBuffers[idx]->pictureFlags & DVP_FLAG_INTERLACED &&
      m_renderBuffers[idx]->frameIdx + numPast * 2 >=
      m_renderBuffers[m_iBufferIndex]->frameIdx)
      return true;
  }
  return false;
}

My guess at this point is that when the renderer is reset/flushed/whatever after the seek operation, the in-use buffers aren't being marked as free properly, so this function is returning true when it shouldn't be.

I'll spend some time looking into an actual fix this weekend if I can, but perhaps this would be enough info for @afedchin or somebody else to have an "aha moment".  Probably going to be a simple fix in the end.

**Comment by thexai** [comment] 2020-04-25 18:21
Good found :)

I believe "NeedBuffer" function means "I need save the buffer to use it later" or "need keep frame buffer".

Since interlaced image needs two (partial) frames to obtain one picture this function (I guess) try to ensure that the last two frames are (*)preserved as a minimum in case of interlaced content. For the rest of cases is safe return false.

* Preserved for posterior image processing.

There is probably some error in `* 2` and it doesn't work as it should... maybe replace `* 2` with `+ 1`  or `>=`  to `>`  

I'm just speculating... I haven't tried anything.

As last resort return always false for sure fix this bug but maybe introduce others if some post processing is in use (is need previous partial frame for apply some filter). Still it would be an improvement respect actual condition.

**Comment by afedchin** [comment] 2020-04-25 19:26
> There is probably some error in `* 2` and it doesn't work as it should... maybe replace `* 2` with `+ 1` or `>=` to `>`

`* 2` is not an error it must be here because index increment is `2`, see https://github.com/xbmc/xbmc/blob/master/xbmc/cores/VideoPlayer/VideoRenderers/windows/RendererBase.cpp#L174

`CRendererDXVA::NeedBuffer` tells render manager that a past frame still required for interlaced material because DXVA processor on some hardware requires a couple (`m_processor->PastRefs()`) of past frames for proper deinterlacing.

**Comment by djp952** [comment] 2020-04-25 19:53
@afedchin, I looked a little harder, and what seems to be the case after a seek on interlaced content is that all of the buffered frames are being flagged as necessary.  I added some variables to watch the frame indexes, and here is an example of what I am seeing after a seek:

m_iBufferIndex = 3

buffer[0]->frameIdx = 10
buffer[1]->frameIdx = 12
buffer[2]->frameIdx = 2
buffer[3]->frameIdx = 4
buffer[4]->frameIdx = 6
buffer[5]->frameIdx = 8

All of the buffered frame indexes are being flagged as necessary relative to frameIdx 4 as they are either 2 in the past or all in the future.  I don't think the logic to keep them is faulty, but it is why playback will stop as RenderManager can't get a free buffer.

I wasn't thinking that NeedsBuffer() is broken in and of itself, but there is definitely something amiss.  Didn't look yet, but is it perhaps loading one too many future frames? Given the frame indexes above, if the current frame is 4 is it necessary to have frame 12 already loaded?

**Comment by afedchin** [comment] 2020-04-25 20:13
after seek all buffers must be released.

**Comment by djp952** [comment] 2020-04-26 02:23
@afedchin, agreed.  Any actual insight how to fix the problem with the refactored Windows DXVA renderer?

**Comment by afedchin** [comment] 2020-04-26 08:19
the issue isn't related to DXVA renderer but to render manager. one past frame in queue shouldn't freeze pipeline. you can try to watch what's going on in `CRenderManager::FrameMove()` after seek. there is `m_discard` queue which indicates which buffer must be released. after seek `m_discard` must contains all in [0..5] range, so after first call `FrameMove` after seek only one past frame can left in buffers.

@FernetMenta can you please confirm my assumption?

**Comment by djp952** [comment] 2020-04-26 23:18
I'll start looking at how Leia handles it as well, I know the renderer is different now, but I don't see any attempts to flush the buffers after the seek operation happening in the current code.  I also thought I saw some problem with de-interlacing after a seek using Pixel Shaders as a comparison point, but it was an afterthought.

I'll keep playing around as time allows, I sincerely appreciate the commentary.  Hopefully I can help in some way that isn't just wasting people's time!

**Comment by FernetMenta** [comment] 2020-04-27 06:14
@afedchin 

> after seek m_discard must contains all in [0..5] range

wrong. only the queued pics go to m_discard. the question is why renderer marks them as needed.  since queued hasn't been rendered, those should not be flagged as needed.

**Comment by thexai** [comment] 2020-04-27 08:54
If it helps I added detailed log code to `CRendererDXVA::NeedBuffer`:

```
CLog::LogF(LOGINFO,
       "idx = {}, frameIdx[idx] = {}, m_iBufferIndex = {}, frameIdx[m_iBufferIndex] = "
       "{}, numPast = {}, return = true",
        idx, m_renderBuffers[idx]->frameIdx, m_iBufferIndex,
        m_renderBuffers[m_iBufferIndex]->frameIdx, numPast);
```

And this is log obtained:

```
2020-04-27 10:29:48.437 T:12712    INFO <general>: CRendererDXVA::NeedBuffer: idx = 1, frameIdx[idx] = 0, m_iBufferIndex = 2, frameIdx[m_iBufferIndex] = 2, numPast = 2, return = true
2020-04-27 10:29:48.450 T:12712    INFO <general>: CRendererDXVA::NeedBuffer: idx = 1, frameIdx[idx] = 0, m_iBufferIndex = 2, frameIdx[m_iBufferIndex] = 2, numPast = 2, return = true
2020-04-27 10:29:48.450 T:12712    INFO <general>: CRendererDXVA::NeedBuffer: idx = 2, frameIdx[idx] = 2, m_iBufferIndex = 2, frameIdx[m_iBufferIndex] = 2, numPast = 2, return = true
2020-04-27 10:29:48.467 T:12712    INFO <general>: CRendererDXVA::NeedBuffer: idx = 1, frameIdx[idx] = 0, m_iBufferIndex = 3, frameIdx[m_iBufferIndex] = 4, numPast = 2, return = true
2020-04-27 10:29:48.467 T:12712    INFO <general>: CRendererDXVA::NeedBuffer: idx = 2, frameIdx[idx] = 2, m_iBufferIndex = 3, frameIdx[m_iBufferIndex] = 4, numPast = 2, return = true
2020-04-27 10:29:48.485 T:12712    INFO <general>: CRendererDXVA::NeedBuffer: idx = 1, frameIdx[idx] = 0, m_iBufferIndex = 3, frameIdx[m_iBufferIndex] = 4, numPast = 2, return = true
2020-04-27 10:29:48.485 T:12712    INFO <general>: CRendererDXVA::NeedBuffer: idx = 2, frameIdx[idx] = 2, m_iBufferIndex = 3, frameIdx[m_iBufferIndex] = 4, numPast = 2, return = true
2020-04-27 10:29:48.485 T:12712    INFO <general>: CRendererDXVA::NeedBuffer: idx = 3, frameIdx[idx] = 4, m_iBufferIndex = 3, frameIdx[m_iBufferIndex] = 4, numPast = 2, return = true
2020-04-27 10:29:48.504 T:12712    INFO <general>: CRendererDXVA::NeedBuffer: idx = 1, frameIdx[idx] = 0, m_iBufferIndex = 4, frameIdx[m_iBufferIndex] = 6, numPast = 2, return = false
2020-04-27 10:29:48.504 T:12712    INFO <general>: CRendererDXVA::NeedBuffer: idx = 2, frameIdx[idx] = 2, m_iBufferIndex = 4, frameIdx[m_iBufferIndex] = 6, numPast = 2, return = true
2020-04-27 10:29:48.505 T:12712    INFO <general>: CRendererDXVA::NeedBuffer: idx = 3, frameIdx[idx] = 4, m_iBufferIndex = 4, frameIdx[m_iBufferIndex] = 6, numPast = 2, return = true
2020-04-27 10:29:48.537 T:12712    INFO <general>: CRendererDXVA::NeedBuffer: idx = 2, frameIdx[idx] = 2, m_iBufferIndex = 4, frameIdx[m_iBufferIndex] = 6, numPast = 2, return = true
2020-04-27 10:29:48.537 T:12712    INFO <general>: CRendererDXVA::NeedBuffer: idx = 3, frameIdx[idx] = 4, m_iBufferIndex = 4, frameIdx[m_iBufferIndex] = 6, numPast = 2, return = true
2020-04-27 10:29:48.537 T:12712    INFO <general>: CRendererDXVA::NeedBuffer: idx = 4, frameIdx[idx] = 6, m_iBufferIndex = 4, frameIdx[m_iBufferIndex] = 6, numPast = 2, return = true
2020-04-27 10:29:48.551 T:12712    INFO <general>: CRendererDXVA::NeedBuffer: idx = 2, frameIdx[idx] = 2, m_iBufferIndex = 5, frameIdx[m_iBufferIndex] = 8, numPast = 2, return = false
2020-04-27 10:29:48.551 T:12712    INFO <general>: CRendererDXVA::NeedBuffer: idx = 3, frameIdx[idx] = 4, m_iBufferIndex = 5, frameIdx[m_iBufferIndex] = 8, numPast = 2, return = true
2020-04-27 10:29:48.552 T:12712    INFO <general>: CRendererDXVA::NeedBuffer: idx = 4, frameIdx[idx] = 6, m_iBufferIndex = 5, frameIdx[m_iBufferIndex] = 8, numPast = 2, return = true
2020-04-27 10:29:48.568 T:12712    INFO <general>: CRendererDXVA::NeedBuffer: idx = 3, frameIdx[idx] = 4, m_iBufferIndex = 5, frameIdx[m_iBufferIndex] = 8, numPast = 2, return = true
2020-04-27 10:29:48.568 T:12712    INFO <general>: CRendererDXVA::NeedBuffer: idx = 4, frameIdx[idx] = 6, m_iBufferIndex = 5, frameIdx[m_iBufferIndex] = 8, numPast = 2, return = true
2020-04-27 10:29:48.568 T:12712    INFO <general>: CRendererDXVA::NeedBuffer: idx = 5, frameIdx[idx] = 8, m_iBufferIndex = 5, frameIdx[m_iBufferIndex] = 8, numPast = 2, return = true
2020-04-27 10:29:48.582 T:12712    INFO <general>: CRendererDXVA::NeedBuffer: idx = 3, frameIdx[idx] = 4, m_iBufferIndex = 0, frameIdx[m_iBufferIndex] = 10, numPast = 2, return = false
2020-04-27 10:29:48.582 T:12712    INFO <general>: CRendererDXVA::NeedBuffer: idx = 4, frameIdx[idx] = 6, m_iBufferIndex = 0, frameIdx[m_iBufferIndex] = 10, numPast = 2, return = true
2020-04-27 10:29:48.582 T:12712    INFO <general>: CRendererDXVA::NeedBuffer: idx = 5, frameIdx[idx] = 8, m_iBufferIndex = 0, frameIdx[m_iBufferIndex] = 10, numPast = 2, return = true
2020-04-27 10:29:48.598 T:12712    INFO <general>: CRendererDXVA::NeedBuffer: idx = 4, frameIdx[idx] = 6, m_iBufferIndex = 0, frameIdx[m_iBufferIndex] = 10, numPast = 2, return = true
2020-04-27 10:29:48.599 T:12712    INFO <general>: CRendererDXVA::NeedBuffer: idx = 5, frameIdx[idx] = 8, m_iBufferIndex = 0, frameIdx[m_iBufferIndex] = 10, numPast = 2, return = true
2020-04-27 10:29:48.599 T:12712    INFO <general>: CRendererDXVA::NeedBuffer: idx = 0, frameIdx[idx] = 10, m_iBufferIndex = 0, frameIdx[m_iBufferIndex] = 10, numPast = 2, return = true
2020-04-27 10:29:48.620 T:12712    INFO <general>: CRendererDXVA::NeedBuffer: idx = 4, frameIdx[idx] = 6, m_iBufferIndex = 1, frameIdx[m_iBufferIndex] = 12, numPast = 2, return = false
2020-04-27 10:29:48.620 T:12712    INFO <general>: CRendererDXVA::NeedBuffer: idx = 5, frameIdx[idx] = 8, m_iBufferIndex = 1, frameIdx[m_iBufferIndex] = 12, numPast = 2, return = true
2020-04-27 10:29:48.620 T:12712    INFO <general>: CRendererDXVA::NeedBuffer: idx = 0, frameIdx[idx] = 10, m_iBufferIndex = 1, frameIdx[m_iBufferIndex] = 12, numPast = 2, return = true
```

Full log: 
[kodi.log](https://github.com/xbmc/xbmc/files/4538436/kodi.log)

The last part of log is after seek and returns always true:

```
2020-04-27 10:30:25.885 T:7232  WARNING <general>: CRenderManager::WaitForBuffer - timeout waiting for buffer
2020-04-27 10:30:25.901 T:12712    INFO <general>: CRendererDXVA::NeedBuffer: idx = 5, frameIdx[idx] = 1220, m_iBufferIndex = 1, frameIdx[m_iBufferIndex] = 1224, numPast = 2, return = true
2020-04-27 10:30:25.901 T:12712    INFO <general>: CRendererDXVA::NeedBuffer: idx = 0, frameIdx[idx] = 1222, m_iBufferIndex = 1, frameIdx[m_iBufferIndex] = 1224, numPast = 2, return = true
2020-04-27 10:30:25.901 T:12712    INFO <general>: CRendererDXVA::NeedBuffer: idx = 2, frameIdx[idx] = 1226, m_iBufferIndex = 1, frameIdx[m_iBufferIndex] = 1224, numPast = 2, return = true
2020-04-27 10:30:25.901 T:12712    INFO <general>: CRendererDXVA::NeedBuffer: idx = 3, frameIdx[idx] = 1228, m_iBufferIndex = 1, frameIdx[m_iBufferIndex] = 1224, numPast = 2, return = true
2020-04-27 10:30:25.902 T:12712    INFO <general>: CRendererDXVA::NeedBuffer: idx = 4, frameIdx[idx] = 1230, m_iBufferIndex = 1, frameIdx[m_iBufferIndex] = 1224, numPast = 2, return = true
2020-04-27 10:30:25.917 T:12712    INFO <general>: CRendererDXVA::NeedBuffer: idx = 5, frameIdx[idx] = 1220, m_iBufferIndex = 1, frameIdx[m_iBufferIndex] = 1224, numPast = 2, return = true
2020-04-27 10:30:25.918 T:12712    INFO <general>: CRendererDXVA::NeedBuffer: idx = 0, frameIdx[idx] = 1222, m_iBufferIndex = 1, frameIdx[m_iBufferIndex] = 1224, numPast = 2, return = true
2020-04-27 10:30:25.918 T:12712    INFO <general>: CRendererDXVA::NeedBuffer: idx = 2, frameIdx[idx] = 1226, m_iBufferIndex = 1, frameIdx[m_iBufferIndex] = 1224, numPast = 2, return = true
2020-04-27 10:30:25.918 T:12712    INFO <general>: CRendererDXVA::NeedBuffer: idx = 3, frameIdx[idx] = 1228, m_iBufferIndex = 1, frameIdx[m_iBufferIndex] = 1224, numPast = 2, return = true
2020-04-27 10:30:25.918 T:12712    INFO <general>: CRendererDXVA::NeedBuffer: idx = 4, frameIdx[idx] = 1230, m_iBufferIndex = 1, frameIdx[m_iBufferIndex] = 1224, numPast = 2, return = true
2020-04-27 10:30:25.934 T:12712    INFO <general>: CRendererDXVA::NeedBuffer: idx = 5, frameIdx[idx] = 1220, m_iBufferIndex = 1, frameIdx[m_iBufferIndex] = 1224, numPast = 2, return = true
2020-04-27 10:30:25.934 T:12712    INFO <general>: CRendererDXVA::NeedBuffer: idx = 0, frameIdx[idx] = 1222, m_iBufferIndex = 1, frameIdx[m_iBufferIndex] = 1224, numPast = 2, return = true
2020-04-27 10:30:25.934 T:12712    INFO <general>: CRendererDXVA::NeedBuffer: idx = 2, frameIdx[idx] = 1226, m_iBufferIndex = 1, frameIdx[m_iBufferIndex] = 1224, numPast = 2, return = true
2020-04-27 10:30:25.935 T:12712    INFO <general>: CRendererDXVA::NeedBuffer: idx = 3, frameIdx[idx] = 1228, m_iBufferIndex = 1, frameIdx[m_iBufferIndex] = 1224, numPast = 2, return = true
2020-04-27 10:30:25.935 T:12712    INFO <general>: CRendererDXVA::NeedBuffer: idx = 4, frameIdx[idx] = 1230, m_iBufferIndex = 1, frameIdx[m_iBufferIndex] = 1224, numPast = 2, return = true
2020-04-27 10:30:25.951 T:12712    INFO <general>: CRendererDXVA::NeedBuffer: idx = 5, frameIdx[idx] = 1220, m_iBufferIndex = 1, frameIdx[m_iBufferIndex] = 1224, numPast = 2, return = true
2020-04-27 10:30:25.951 T:12712    INFO <general>: CRendererDXVA::NeedBuffer: idx = 0, frameIdx[idx] = 1222, m_iBufferIndex = 1, frameIdx[m_iBufferIndex] = 1224, numPast = 2, return = true
2020-04-27 10:30:25.952 T:12712    INFO <general>: CRendererDXVA::NeedBuffer: idx = 2, frameIdx[idx] = 1226, m_iBufferIndex = 1, frameIdx[m_iBufferIndex] = 1224, numPast = 2, return = true
2020-04-27 10:30:25.952 T:12712    INFO <general>: CRendererDXVA::NeedBuffer: idx = 3, frameIdx[idx] = 1228, m_iBufferIndex = 1, frameIdx[m_iBufferIndex] = 1224, numPast = 2, return = true
2020-04-27 10:30:25.952 T:12712    INFO <general>: CRendererDXVA::NeedBuffer: idx = 4, frameIdx[idx] = 1230, m_iBufferIndex = 1, frameIdx[m_iBufferIndex] = 1224, numPast = 2, return = true
2020-04-27 10:30:25.953 T:7232  WARNING <general>: CRenderManager::WaitForBuffer - timeout waiting for buffer
```

**Comment by thexai** [comment] 2020-04-27 09:23
Possible workaround:

```
bool CRendererDXVA::NeedBuffer(int idx)
{
  if (m_renderBuffers[idx]->IsLoaded())
  {
    if (m_renderBuffers[idx]->pictureFlags & DVP_FLAG_INTERLACED &&
        std::llabs(m_renderBuffers[idx]->frameIdx - m_renderBuffers[m_iBufferIndex]->frameIdx) <=
            (m_processor->PastRefs() * 2))
    {
      CLog::LogF(LOGINFO,
                 "idx = {}, frameIdx[idx] = {}, m_iBufferIndex = {}, frameIdx[m_iBufferIndex] = "
                 "{}, numPast = {}, return = true",
                 idx, m_renderBuffers[idx]->frameIdx, m_iBufferIndex,
                 m_renderBuffers[m_iBufferIndex]->frameIdx, m_processor->PastRefs());
      return true;
    }
    CLog::LogF(LOGINFO,
               "idx = {}, frameIdx[idx] = {}, m_iBufferIndex = {}, frameIdx[m_iBufferIndex] = "
               "{}, numPast = {}, return = false",
               idx, m_renderBuffers[idx]->frameIdx, m_iBufferIndex,
               m_renderBuffers[m_iBufferIndex]->frameIdx, m_processor->PastRefs());
  }

  return false;
}
```

With these modification seems is maintained same behaviour as original code but not blocking after seek.

Full second log:
[kodi2.log](https://github.com/xbmc/xbmc/files/4538672/kodi2.log)

**Comment by yeahme49** [comment] 2020-04-27 14:04
I tested your NeedBuffer code and it appears to be working for me as well. No seeking issues with Interlaced MPEG2 from TVHeadEnd.

**Comment by djp952** [comment] 2020-04-27 20:19
Not sure using llabs() is correct, as it will flag frames both before and after the current instead of just before.  Example: buffer[idx] frame is 6, current frame is 4, numPast is 2.  This will return true when it should be false.  (6 - 4) <= 2.  I also think you need to watch out for the current frame index being zero.

The version I made is **much** less elegant looking but seems to function within that constraint.  If the only frame(s) that really need to be kept are the ones immediately prior to the current one, of course.

```
bool CRendererDXVA::NeedBuffer(int idx)
{
  if (m_renderBuffers[idx]->IsLoaded() && m_renderBuffers[idx]->pictureFlags & DVP_FLAG_INTERLACED)
  {
    const uint64_t currentFrameIndex = m_renderBuffers[m_iBufferIndex]->frameIdx;
    if (currentFrameIndex > 0)
    {
      const uint64_t bufferFrameIndex = m_renderBuffers[idx]->frameIdx;
      const int framesNeeded = m_processor->PastRefs() * 2;

      return bufferFrameIndex < currentFrameIndex &&
             bufferFrameIndex + framesNeeded >= currentFrameIndex;
    }
  }

  return false;
}
```

Thoughts?  Really appreciate everyone looking at this.

**Comment by thexai** [comment] 2020-04-28 08:39
For me it's OK.

I didn't really like llabs too much either (I'd put it on so I didn't have to think too much).

Go ahead with PR :)

**Comment by djp952** [comment] 2020-04-28 13:11
Will do, thank you @thexai!

**Closed** 2020-04-30 08:04 UTC
Labels: Component: Video, Platform: Windows, v19 Matrix
