### ISSUE TITLE
WebVTT files not regonized with vtt extension

### ISSUE THREAD

**Issue by garion84** [xbmc/xbmc#19550] opened 2021-04-10 03:07 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

When playing a video file with an external WebVTT subtitle file, named with the `vtt` file extension, this subtitle file is not recognized by Kodi.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

An external WebVTT subtitle file, named with the `vtt` file extension, should be recognized and used by Kodi.

## Actual Behavior

If the external WebVTT subtitle file has the `vtt` file extension, Kodi does not load this file while playing the related movie.

## Possible Fix

If the external WebVTT subtitle file is renamed with the `txt` file extension, Kodi uses the external WebVTT subtitle file without any issue.

According to the [W3C recommendation](https://www.w3.org/TR/webvtt1/#iana-text-vtt), the `vtt` file extension can be used for this files type.

### To Reproduce

1. Copy a video file with an external WebVTT subtitle file, named with the `vtt` file extension in the video library. A sample can be downloaded from [this repository ](https://github.com/brenopolanski/html5-video-webvtt-example) for example.
2. Play the video: there is not subtitle loaded.
3. Rename the subtitle file with the `txt` file extension. The subtitle is loaded.

### Debuglog

The debuglog can be found here:

https://paste.chapril.org/?fc61df7da25d195b#E5srqcv1N763rHXRnmZG94A3sAjDpGWehJPSYwi3yeJV

### Screenshots
Here are some links or screenshots to help explain the problem:

While playing a movie with the external WebVTT subtitle file with the `vtt` file extension:

![with-vtt](https://user-images.githubusercontent.com/51873865/114256515-07dfb400-99ba-11eb-8697-6c66476ff58f.png)

While playing a movie with the external WebVTT subtitle file with the `txt` file extension:

![with-txt](https://user-images.githubusercontent.com/51873865/114256540-3bbad980-99ba-11eb-9908-ffa836e045ed.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

N./A.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP
 - Operating system version/name:  LibreELEC (official): 9.2.6 (Generic.x86_64)
 - Kodi version: Kodi 18.9

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment] 2021-04-10 03:19
Unfortunately it's just not a supported format. Not a bug. As it's a feature request, I'll close this, as GitHub is just for bug issues.

As an aside, two team members have done varying degrees of an implementation for vtt (both internal/external), so it might come in eventually.

**Closed by fuzzard** 2021-04-10 03:19 UTC
Labels: Triage: Needed
