### ISSUE TITLE
ListItem setInfo - year can't be before 1900 - defaults to Unix epoch (1969)

### ISSUE THREAD

**Issue by FraserChapman** [xbmc/xbmc#16427] opened 2019-08-01 09:30 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

If you create a ListItem for types that support the info label "year" (video, music, game)  and try to set the year to a value earlier than **1900** then the year defaults to **1969**. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I would expect to be able to set a valid year for items and it be displayed correctly

## Actual Behavior

When the year is set to a value below 1900 the year defaults to 1969

## Possible Fix

Would imagine that somewhere that values below 1900 are being treated as 0 seconds (i.e. the Unix Epoch) and as such are returning the value 1969.

### To Reproduce

1. Create a ListItem
2. Call setInfo on the item with command name "video" and a year Info label with a year before 1900
3. view the list item in Kodi

e.g.

```
list_item = ListItem("year 1980")
list_item.setInfo("video", {"year": 1980})  # displays as 1980

list_item = ListItem("year 1900")
list_item.setInfo("video", {"year": 1900})  # displays as 1900

list_item = ListItem("year 1899")
list_item.setInfo("video", {"year": 1899})  # displays as 1969

list_item = ListItem("year 1853")
list_item.setInfo("video", {"year": 1853})  # displays as 1969
```

### Debuglog

The debuglog can be found here: https://paste.kodi.tv/giquciduno.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

https://drive.google.com/uc?id=1mdlGquZaOGiBEcNusjHnmOerHgpreKfa

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Trying to display movies that date between 1850 and 1899

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [x] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: macOS Mojave 10.14.6
 - Kodi version:  Kodi (18.2 Git:20190422-f2643566d0)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment] 2020-03-13 20:35
The reasoning for this has come to light recently with some date test updates. OSX doesn't support dates < ~1901. I forget the specific date it fails at. It's a bug in OSX library.
With current date/time methods, we have no way around this.

**Comment by fuzzard** [comment] 2020-03-14 04:35
As this is a fault in macos itself, we'll close this.
We have unit tests now in place that can be run to verify if we are able to get a resolution down the line.

Just for reference, this stackoverflow post has some background on the cause with macos mktime implementation
https://stackoverflow.com/questions/46333829/how-to-get-range-of-dates-that-are-representable-accepted-by-date1-mktime3

Below is a small test program to illlustrate the issue. Run on linux, you get times back to year 1, run on mac os, you get -1 below 1900

```
#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

void do_time(int year)
{
  time_t utc;
  struct tm tp;

  memset(&tp, 0, sizeof(tp));

  tp.tm_sec = 0;
  tp.tm_min = 0;
  tp.tm_hour = 0;
  tp.tm_mday = 1;
  tp.tm_mon = 0;
  tp.tm_year = year - 1900;
  tp.tm_wday = 1;
  tp.tm_yday = 0;
  tp.tm_isdst = -1;

  printf("%d %ld\n",year, mktime(&tp));
}

int main(){
  printf("time_t is %lu bits\n",sizeof(time_t)*CHAR_BIT);
  for (int i = 1; i<1971; i++)
    do_time(i);
  exit(0);
}
```

**Closed by fuzzard** 2020-03-14 04:35 UTC
Labels: Resolution: External, Triage: Confirmed
