### ISSUE TITLE
FFmpeg has a memory leak in raspberry pi 4-based OSs

### ISSUE THREAD

**Issue by Minauras** [xbmc/xbmc#20908] opened 2022-01-27 10:30 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

When playing videos with Kodi in either OSMC or Xbian on a Raspberry Pi CM4, a small amount of allocated heap memory is not freed when the video ends. These leaks build up and cause Kodi to crash after playing several videos.

Changing the allocated heap size with the cma option in either `/boot/config.txt` or `/boot/cmdline.txt` does not solve the problem, it only changes when it happens.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

When Kodi is done playing a video, the consumed heap memory should be freed.

## Actual Behavior

When Kodi is done playing a video, the consumed heap memory is not completely freed, and the leaks build up until Kodi crashes.

## Possible Fix

This behavior is not present on LibreELEC. On [this forum thread](https://forum.kodi.tv/showthread.php?tid=366631&pid=3082917#pid3082917), Team-Kodi member popcornmix mentions an [ffmpeg patch](https://github.com/LibreELEC/LibreELEC.tv/tree/libreelec-10.0/packages/multimedia/ffmpeg/patches/rpi) that is present on LibreELEC. Maybe it could be applied to other OSs.

### To Reproduce

Setup: Raspberry Pi CM4 on TOFU carrier board, with either OSMC or Xbian.

Run a video playlist on loop and monitor the RAM or heap. Each time a video starts, the available memory drops. When the available memory reaches a critical state, Kodi crashes and restarts.

Or:

Run a video and stop it, then do it again on loop. Monitor the RAM or heap. Each time the video starts, the available memory drops. When the available memory reaches a critical state, Kodi crashes and restarts.

### Debuglog

The debuglog can be found here:
[Here is a full log from a run with this bug.](https://gist.github.com/Minauras/bf71b945abc4acd3b299fbc2d68c9591)
The error is the following:
```
2022-01-21 14:34:33.951 T:1510     INFO <general>: ffmpeg[(nil)X]: Failed to alloc 12533760 from dma-heap(fd=176): 12 (Cannot allocate memory)
2022-01-21 14:34:33.951 T:1510    ERROR <general>: ffmpeg[(nil)X]: [hevc] v4l2_request_hevc_start_frame: Failed to get dst buffer
```

### Screenshots
Here are some links or screenshots to help explain the problem:

None

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I am playing 4k24fps videos, I have not tried with other video formats.

I first reported this issue on the [Kodi forum](https://forum.kodi.tv/showthread.php?tid=366631&pid=3082917#pid3082917) and the [OSMC forum](https://discourse.osmc.tv/t/playling-playlist-dies-after-about-7-minutes-possible-memory-leak/92347).

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Either OSMC 2021.12-1 or Xbian 1.0 2021-11-22
 - Kodi version: 19.3.0
 - Hardware: Raspberry Pi CM4 on TOFU carrier board

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by popcornmix** [comment] 2022-01-27 11:47
I'll close this as it's not a kodi issue. It sounds like the issue is fixed in ffmpeg tree LE uses, but OSMC and Xbian don't have a new enough version.
In either case it's not something that can be fixed in kodi tree.

**Closed by popcornmix** 2022-01-27 11:47 UTC
Labels: Ignored rules, Triage: Needed
