### ISSUE TITLE
Scroll EPG when powering on with remote

### ISSUE THREAD

**Issue by svenbieg** [xbmc/xbmc#15656] opened 2019-03-03 12:12 UTC
No way? Ain't there a signal from HDMI?

**Comment by DaVukovic** [comment] 2019-03-04 05:44
Please follow our issue template and provide at least a debuglog

I'll mark this as invalid for the time being

Thanks in advance

**Comment by ksooo** [comment] 2019-03-11 19:07
Do you have a clue what you are doing here? What do you think closing and re-opening the issue is good for?

**Comment by svenbieg** [comment] 2019-03-11 19:12
The point is powering on Your TV and getting EPG of two days ago. I've found myself two times looking through.


---- Kai Sommerfeld schrieb ----


Do you have a clue what you are doing here? What do you think closing and re-opening the issue is good for?

**Comment by svenbieg** [comment] 2019-03-11 19:17
I don't think my Rpi3 is streaming video even without a display.

**Comment by svenbieg** [comment] 2019-03-11 19:33
It ain't a bug, so there is no bug-report. It is more a question, if this ain't possible. Maybe someone in Your team has time for this issue.

**Comment by ksooo** [comment] 2019-03-11 19:43
If It's no bug report or or feature request, ask your question in the forum, please.

**Closed by ksooo** 2019-03-11 19:43 UTC
Labels: INVALID

**Comment by svenbieg** [comment] 2019-03-11 19:45
I'm a hobby-programmer. Maybe You get a Power-Off and Power-On Event. It ain't my problem. Best regards, Sven Bieg.
