### ISSUE TITLE
Music-playlists don't use discart/fanart ... in Kodi

### ISSUE THREAD

**Issue by MakeitWORK33** [xbmc/xbmc#24665] opened 2024-02-07 12:03 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

Dear supporters, 

I have tried to create new music-playlists in Kodi. The lists are played, but extras like discart, fanart, banners etc. are ignored. (Using Kodi 20.2 on a Windows PC and Kodi 20.3 on a HTPC) Strange thing is, that older playlists work - they show the spinning cd, background-fanart and so on. 

Have searched everywhere but can't find a solution. I have also tried to create a path for the missing elements manually - clicking right on the songtitle - choosing "information" and adding for example discart there. This works for one song but after finishing the track, all informations are gone again. Same behaviour in different skins. 

My music-library is sorted the way it is recommended - Artist (fanrt, thumb etc.) Albums (cover, cdart) - There are no issues, everything is tagged correctly.
Have been looking for help in several forums and the experts there asked me to report the problem. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The goal is a way to create musik-playlists without loosing all informations. The playlists should be able to use the same extras as the "album-player". This was obviously possible in earlier versions of Kodi.

## Actual Behavior

As described before you can create a new music-playlist but it won't read or use your fanart-stuff. 

### To Reproduce

1. Open music - enter playlist - create new playlist - choose tracks - name and save it
2. Play the playlist - covers are there - everthing else is missing 
3. Leave fullscreen-playback - click on track and information - select for example a disart for the track and go bakc to fullscreen-playback - the cd ist there 
4. Choose another track and everything is gone

### Debuglog

The debuglog can be found here:

[kodi.log](https://github.com/xbmc/xbmc/files/14193470/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 11 (both systems) 
 - Kodi version: 20.2 and 20.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by the-black-eagle** [comment] 2024-02-07 16:18
I can confirm this.  Rather bizarrely, it's caused by saving the correct duration into the playlist.  A quick fix would be to edit your playlist so that the durations are all zero.  All the art will work then. 

I need to dig through the code to establish exactly why this is (not loading the duration seems wrong as a fix) but a quick guess is that if there is a duration then the fileitem properties are getting lost / reset / overwritten somehow.

**Comment by MakeitWORK33** [comment] 2024-02-07 18:30
Hello black eagle and thanks for your fast response and your explanation which is understandable even for a noob like me. 

Just to be sure - I open a playlist in editor and it looks like that: 
#EXTINF:224,04. Better Oblivion Community Center - Service Road
smb://RABENNEST/music/A NEW WORLD/Better Oblivion Community Center/Better Oblivion Community Center/04 Service Road.flac

The numbers at the beginning are the duration in seconds, I guess. Shall I just set it to zero? 

I am asking because a playlist that works shows for example: 
#EXTINF:0,11. Bonnie "Prince" Billy - Grand Dark Feeling of Emptiness
smb://RABENNEST/music/A NEW WORLD/Bonnie Prince Billy/Ease Down the Road/11 Grand Dark Feeling of Emptiness.flac

Maybe the numbers behind the comma don't count. 

However I am very thankful for your response - is there a virtual-tip-box for Team Kodi? 

Best regards

**Comment by the-black-eagle** [comment] 2024-02-07 18:40
Yes, the number at the beginning, after the `#EXTINF`, is the duration.  If you set all of those to zero, then discart, banners, fanart etc will all work.  The second number, after the `,` is the track number.

As I said, I don't yet know why this is, but as it's the only difference I can see between my old playlists and a newly created one (and I must admit, I don't really use playlists other than smartplaylists occasionally) and changing it fixes the issue, then it clearly is the underlying problem - even if I don't yet know why exactly.

**Comment by the-black-eagle** [comment] 2024-02-09 08:15
Just to update this, I have figured out what is going on and will PR a fix later today, once I'm 110% convinced it's right.

**Comment by MakeitWORK33** [comment] 2024-02-09 15:24
Thanks, black eagle for your fast reaction, finding the problem and solving it so fast. 

I see you have added the fix to Kodi 21 Omega - is 21 already working stable so I can install it? 

Best regards

**Comment by the-black-eagle** [comment] 2024-02-09 15:47
> I see you have added the fix to Kodi 21 Omega - is 21 already working stable so I can install it?

Steady on!!  It has to be merged first.  But yeah, V21 is stable.

**Closed** 2024-02-10 04:56 UTC
Labels: Triage: Has proposed fix
