### ISSUE TITLE
Highlight colors and other colors replaced to white after update making fonts unreadable

### ISSUE THREAD

**Issue by cg00001** [xbmc/xbmc#22863] opened 2023-02-25 18:33 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Before previous and today's update all color themes when I used Titan MOD skin worked fine.

## Actual Behavior

Now several colors are replaced with white and fonts are unreadable. This issue remains even if I change color themes.

### To Reproduce

1. Install Kodi, install Titan MOD skin, the issue is there now.
2.
3.

### Debuglog

The debuglog can be found here:
[kodi.log](https://github.com/xbmc/xbmc/files/10831985/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

![1](https://user-images.githubusercontent.com/38960370/221373800-e08b5c16-55ce-4932-92e5-83c07eaaf752.jpg)
![2](https://user-images.githubusercontent.com/38960370/221373801-e0a4dbab-c9c8-4145-a36b-c30bcaff06b3.jpg)
![3](https://user-images.githubusercontent.com/38960370/221373802-a5fde01c-9757-4688-98e5-7eaaf089ec39.jpg)
![4](https://user-images.githubusercontent.com/38960370/221373803-d2966d16-5155-4b0c-bff8-b95085abec33.jpg)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
  - [x] Arch Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
Arch Linux
Kodi Nexus v20.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment] 2023-02-25 19:24
@cg00001 

This needs to be reported to the skin author, not to Kodi core.

https://forum.kodi.tv/forumdisplay.php?fid=21

**Comment by cg00001** [comment] 2023-02-25 19:31
> @cg00001
> 
> This needs to be reported to the skin author, not to Kodi core.
> 
> https://forum.kodi.tv/forumdisplay.php?fid=21

This happened after a Kodi Nexus update...
But I'll contact the skin author, btw your link is wrong.

**Comment by KarellenX** [comment] 2023-02-25 19:41
Oops. Fixed.

**Comment by cg00001** [comment] 2023-02-25 23:45
Skin author sugested:

> Switch off Kodi and delete "\userdata\addon_data\skin.titan.mod.beta.matrix\".
> And then restart kodi. 
>See if you still have the wrong colours.

I did that and colors are still wrong.
I noticed when I move up and down from a menu to a submenu, colors are corrected until I move to another submenu or menu.
Again, I believe this is a Kodi issue, not a skin issue, it appeared on the previous Kodi Nexus update, and today's update didn't fix it.
Maybe a Kodi dev can pinpoint the update change(s) that lead to this issue.

Pics and video are after doing what skin author suggested:
![1](https://user-images.githubusercontent.com/38960370/221384673-6ce7a8ea-5b42-45b2-9c89-eb70f8fac810.jpg)
![2](https://user-images.githubusercontent.com/38960370/221384678-f50a1436-b994-47b4-8844-f34f439ebf25.jpg)
Video:
https://user-images.githubusercontent.com/38960370/221384689-d75816de-3d3a-4c60-a66a-d1c6b4d78867.mp4

**Comment by enen92** [comment] 2023-02-26 10:56
wondering what version you're using to pinpoint this in time (not clear from this bug report what you are using..). Are you using the master branch of Nexus?

It could be https://github.com/xbmc/xbmc/pull/22848 but this only went in 3 days ago..

**Comment by cg00001** [comment] 2023-02-26 12:03
> wondering what version you're using to pinpoint this in time (not clear from this bug report what you are using..). Are you using the master branch of Nexus?
> 
> It could be #22848 but this only went in 3 days ago..

Ι'm using kodi-nexus-git from AUR in Arch linux which gets frequent updates:
https://aur.archlinux.org/packages/kodi-nexus-git

**Comment by enen92** [comment] 2023-02-26 12:17
ok then the source of the issue is the PR I linked. Wondering if the skin is not abusing the colordiffuse property and used to work just by "luck".

I'll take a look. Either way there's no point in causing breakages in point releases (even in the case the issue is actually in the skin) so the commit should be reverted for Nexus.

**Comment by enen92** [comment] 2023-02-26 13:01
Sorry @cg00001 I can't even figure out how to install the skin in nexus to have a look...
Either provide concrete instructions or this issue will be closed. I won't be reading 174 pages of that forum thread to figure out how to install a skin.

**Comment by cg00001** [comment] 2023-02-26 13:14
> Sorry @cg00001 I can't even figure out how to install the skin in nexus to have a look... Either provide concrete instructions or this issue will be closed. I won't be reading 174 pages of that forum thread to figure out how to install a skin.

https://github.com/Fuchs246/repository.fuchs246

**Comment by enen92** [comment] 2023-02-26 13:15
That's for matrix, and after installing the skin via that repo the menu items don't even show for me..
Looks totally broken to be honest.

**Comment by cg00001** [comment] 2023-02-26 13:16
> That's for matrix, and after installing the skin via that repo the menu items don't even show for me.. Looks totally broken to be honest.

Restarting Kodi should show the skin work properly. Press S for power menu.

**Comment by cg00001** [comment] 2023-02-26 13:19
Managed to fix colors show kind of better in folders, but the white highlight background color and white highlight font color  can not be changed to another color and that's what causes words to disappear .

**Comment by cg00001** [comment] 2023-02-26 13:26
> ok then the source of the issue is the PR I linked. Wondering if the skin is not abusing the colordiffuse property and used to work just by "luck".
> 
> I'll take a look. Either way there's no point in causing breakages in point releases (even in the case the issue is actually in the skin) so the commit should be reverted for Nexus.

You're probably right it's the PR, and for whatever reason it isn't fixed yet in current kodi-nexus-git for Arch.

**Comment by cg00001** [comment] 2023-02-26 13:53
I just tried Kodi 21 Alpha 1 and this issue is present too. The color theme highlight background color is light blue, but Kodi replaces it with white.
![omega](https://user-images.githubusercontent.com/38960370/221414623-16cc6e08-39a2-4f8e-8fef-50a7cd32bb17.jpg)

**Comment by enen92** [comment] 2023-02-26 16:50
@cg00001 thanks for reporting this quite early in the v20.1 release cycle. Should be fixed by the PR above.
If you want to give it a spin before considering merging it's appreciated.

**Comment by matke-84** [comment] 2023-02-27 13:21
The same thing happens with my skin, titan bingie mod. I hope this solves the problem.

**Closed** 2023-02-27 14:21 UTC
Labels: Component: GUI engine, Triage: Confirmed, Triage: Has proposed fix, v20 Nexus, v21 Omega

**Comment by cg00001** [comment] 2023-02-28 14:01
Just tried update, works fine.
Thank you.
