### ISSUE TITLE
Select first unseen episode of a season not working on addons only to library

### ISSUE THREAD

**Issue by CastagnaIT** [xbmc/xbmc#16171] opened 2019-05-19 13:08 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

Activating the kodi option:
Select first unwatched TV show season / episode
By selecting: "Always"

In the kodi library when you browse the folder is selected correctly the first one not seen,
if i try to do the same thing inside the Netflix addon the kodi option does not work.

I'm working on Netflix addon, and i set the setContent to:
xbmcplugin.setContent('episodes')
but when i open the list, do not select the first not seen

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

when you open a episode list, (inside an addon), select the first episode not seen

## Actual Behavior

when you open a episode list (inside an addon), do not select the first episode not seen

### To Reproduce

1. Run Netflix addon
2. Go to an Tv Series season
3. Mark first 3 episode as seen
4. Reboot kodi
5. Return in the Netflix addon and go to the Tv Series season
6. Nothing is selected

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/qokatigovi.kodi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 / Libreelec
 - Kodi version: 19.0-ALPHA1 Git:20190517-f5636182c0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by HitcherUK** [comment] 2019-05-19 16:23
Setting is only applicable to the library.

![screenshot000](https://user-images.githubusercontent.com/133808/57985087-c149df00-7a5a-11e9-8b73-5289f0b873af.png)

**Comment by CastagnaIT** [comment] 2019-05-19 18:53
so there's no chance of extending it also to addons

**Comment by enen92** [comment] 2019-05-19 18:57
That's a feature request and not a bug. Please use the forum as the place for feature requests: https://forum.kodi.tv/forumdisplay.php?fid=9

I'll close the issue

**Closed by enen92** 2019-05-19 18:57 UTC
Labels: Resolution: Not applicable
