### ISSUE TITLE
Kodi for Mac list all videos on WebDav as 1969-12-31

### ISSUE THREAD

**Issue by kirbyzhou** [xbmc/xbmc#18645] opened 2020-10-26 01:58 UTC
### Describe the bug

Kodi for Mac list all videos on WebDav as 1969-12-31 as As screenshot below.

Kodi for Mac version through 18.0~18.9 have the same bug.
The data in db is correct, you can see in the rightbottom corner, "2016-04-28" is the correct data.
Only the display and sorting order in list is incorrect.

## Expected Behavior
Display the correct date of videos.

## Actual Behavior
Date of files on WebDav is incorrect.
Date of files on local or SMBFS are OK.

### To Reproduce
macOS 10.14.6
Kodi 18.x
Use apache2 along with MacOS to provide WebDAV services using conf files like below

```
DavLockDB "/var/lib/apache2/DavLock"

Alias /dav/ComicVideos  "/Volumes/Drobo/ComicVideos"
Alias /dav/Movies       "/Volumes/Drobo/Movies"

<Location /dav>
    Dav On
    Options +Indexes
    IndexOptions +FoldersFirst +NameWidth=100
</Location>

<DirectoryMatch "/Volumes/Drobo/(Movies|ComicVideos)">
</DirectoryMatch>

```

Use kodi to browse the DAV directory.

### Screenshots 
![image](https://user-images.githubusercontent.com/3401630/97126003-a8c21600-1770-11eb-8a20-59c31853aae2.jpeg)

### Your Environment
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [x] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
macOS 10.14.6
 - Kodi version:
Kodi 18.9

**Comment by kirbyzhou** [comment] 2020-10-26 02:02
I think I have fixed message to follow the template.

**Comment by KarellenX** [comment] 2020-10-26 08:54
Duplicate of this issue which the OP is already aware of... https://github.com/xbmc/xbmc/issues/17309

**Closed by KarellenX** 2020-10-26 08:54 UTC
Labels: Component: Database, Platform: macOS, v18 Leia
