### ISSUE TITLE
Kodi Flatpak release date 14 April 2024 -Video hangs, Jellyfin Server.

### ISSUE THREAD

**Issue by oomPhilip** [xbmc/xbmc#25061] opened 2024-04-24 17:52 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

On Flatpak version dated 7 April 2024, Kodi plays from Jellyfin server plugin perfectly.
After updating to version 14 April 2024, the video will play a few seconds and then freez.
Audio is missing. 
Same video works on different Kodi / Jellyfin combinations on Android, Windows and Ubuntu Kodi versions.
Downgrading to 7 April version, It works again.
http://paste.kodi.tv,ejafegewul log upload, shows the same show episode played on both the Kodi versions.
Issue on any other video as well. 
PC was reloaded as part of fault finding and on latest Ubuntu 2204 version and updates.
Jellyfin server ver 10.8.13 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

## Actual Behavior

No audio on playback and video hang after a few seconds.

### To Reproduce

1. Kodi Version downgraded, issue resolved 
2. Update to latest Kodi, issue back.
3.

### Debuglog

The debuglog can be found here:

http://paste.kodi.tv,ejafegewul

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ X] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu 22.04.4 LTS 64 bit
 - Kodi version: 21

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Martii** [comment] 2024-04-24 19:19
Seems to be a duplicate of #25002

**Comment by neo1973** [comment] 2024-04-24 23:32
Duplicate of #25002. Resolved by #25019 that will be part of Kodi 21.1. Until then stick to the working Flatpak or launch Kodi with the `--audio-backend=pulseaudio` parameter.

**Closed by neo1973** 2024-04-24 23:32 UTC
Labels: Triage: Needed
