### ISSUE TITLE
Kodi search broken, searching wrong database column

### ISSUE THREAD

**Issue by ioogithub** [xbmc/xbmc#18871] opened 2020-11-27 00:55 UTC
### Describe the bug
Kodi's search is broken out of the box.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
The search will work.

## Actual Behavior

No Results found.

## Possible Fix

1. The query needs to be fixed so that it is searching for the proper database column.
2. The fixed version of the "Global Search" add-on needs to be updated in the respository so users can use it.

### To Reproduce

1. Click on the search icon
2. Kodi will ask to install the Global Search add-on
3. The global search add-on is installed successfully
4. Click on the search icon
5. Enter a search term for a movie that is in the database
6. No Results found
7. Inspect the log. Query is searching for a column in the database that does not exist: musicvideo_view.c0 when it should be searching for musicvideo_view.c00

### Debuglog

The debuglog can be found here:
From the log:
````
Query: select * from episode_view  WHERE ((episode_view.c0 LIKE '%2001%'))
2020-11-26 19:46:09.638 T:140305701529344   ERROR: GetEpisodesByWhere failed
2020-11-26 19:46:09.647 T:140305701529344   ERROR: SQL: [MyVideos116.db] SQLite error SQLITE_ERROR (no such column: musicvideo_view.c0)
                                            Query: select * from musicvideo_view  WHERE ((musicvideo_view.c0 LIKE '%2001%'))
2020-11-26 19:46:09.647 T:140305701529344   ERROR: GetMusicVideosByWhere failed
````

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Kodi for Debian 18.6

### Additional information:

There doesn't seem to be anyway on Linux or Raspberry Pi to update Kodi. The website download page is also broken. It reports "Download started" however it never serves the file. Even though Kodi gives a nag to upgrade there isn't anyway to do it on these platforms. The Windows binary however is downloadable.

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment] 2020-11-27 01:08
Do you need global search? You can just search for movies by going into movies, opening the side pane, and selecting search

**Comment by KarellenX** [comment] 2020-11-27 06:09
I could not replicate this issue using Global Search.

Please provide the full debug log.

**Comment by ronie** [comment] 2020-11-28 12:10
duplicate of https://github.com/xbmc/xbmc/issues/18213

afaik this issue was fixed in both 18.8 and current master.

**Comment by DaveTBlake** [comment] 2020-11-28 12:28
> Kodi version: Kodi for Debian 18.6
> There doesn't seem to be anyway on Linux or Raspberry Pi to update Kodi. The website download page is also broken. It reports "Download started" however it never serves the file. 

Which downloads page? Kodi does not directly offer downloads for Debian (for Ubuntu use sudo see https://kodi.wiki/view/HOW-TO:Install_Kodi_for_Linux) or Raspberry Pi. You need to contact the third party repo owner, or compile from source.

**Comment by ronie** [comment] 2020-12-08 21:42
no debuglog, not reproducible and no response from OP.
closing.

**Closed by ronie** 2020-12-08 21:42 UTC
Labels: Resolution: Not reproducible
