### ISSUE TITLE
Kodi 19 "SMB" network function not work (APK / Android TV)

### ISSUE THREAD

**Issue by yentailin** [xbmc/xbmc#19360] opened 2021-03-08 04:50 UTC
Kodi 19 "SMB" network function got big problem , fail to access existing SMB folder and create new network folder by SMB

 - [V ] Android
 - Operating system version/name: Android 9 
 - Kodi version: 19

**Comment by lrusak** [comment] 2021-03-08 05:15
Duplicate of #19279

**Closed** 2021-03-08 05:15 UTC
