### ISSUE TITLE
Playlist issue after upgrade to v20 KODI

### ISSUE THREAD

**Issue by liquidchild101** [xbmc/xbmc#22580] opened 2023-01-24 10:49 UTC
### Describe the bug

Short version: Shuffle ~~and continued~~ playlist doesn't work after upgrade to v20

long version: I've been a user of KODI since the XBMC days, so i know my way around this program. whats happened is after the Google TV (android) update to v20. My playlists don't work anymore. at least the way i had them set up. 

Ive got a collection of old cartoons set up on random to emulate cartoon network. this playlist is continuous in a shuffled format. this has worked great for years but after the update this function doesn't work anymore.

all the videos in the playlist are now in order ~~and stop playing after the first video~~.

i'm guessing there has been a change with the new update but after playing around with the smart/playlist i haven't been able to find a solution. 

the main issue i see if that that saved preferences of the playlist are not being applied to the playlist when opened. so its going to default when being used from a fresh bootup.

has anyone had this issue or know what has changed so i can setup a similar playlist. play one after another in a shuffled format.

cheers

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

a previously saved playlist should continuously play collection of videos in a shuffled format.

## Actual Behavior

playlist is in added order (not shuffled) ~~and stops after a video is finished~~.

## Possible Fix

unsure, like i said above. I dont think its a problem with the save function of the playlist. because my playlists have been fine up until v20. Now the old playlist are the same and newly created playlist - in order ~~and stops after the first video~~.

so it looks like its the open feature not grabbing the right info? im not a programmer so this is all coming out my ass

### To Reproduce

1. make a playlist with at least 10 videos.
2. save with shuffle enabled.
3. try to play the playlist  - might need a cold boot
4. look at the order and see that the playlist stops after the first video. **[EDIT] stop after first video was a configuration error, setting for video autoplay items needs to include "uncatagorised"**

### Debuglog

The debuglog can be found here:
How would i download it from my google tv to another location? doesnt seem to be a guide online.

### Screenshots 
Here are some links or screenshots to help explain the problem:

im at work at the moment but i can add some later if anyone needs any. i think the description should be enough. theres no visual issues.

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: google tv ( i can find out which version when i get home)
 - Kodi version: v20 (newly upgraded)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment] 2023-01-24 14:35
I tried to reproduce, following the steps you provided. No luck. Playback order is different every time I start playback of the list and it does not stop after the first video.

BTW: You are aware that the "shuffle" status is not saved along with the playlist, so nothing that can be toggled on and of per playlist, but is  a playback state that is active/not active for all playlists.

**Comment by ksooo** [comment] 2023-01-24 21:57
@liquidchild101 there are several ways to start playback of a playlist. How exactly did you do? Using play the context menu item of the playlist?

**Comment by ksooo** [comment] 2023-01-25 07:34
@liquidchild101 
* What does Settings->Player->Videos->Play next video automatically value look like?
* Do you start playback of the list after browsing into the playlist and selecting play in the context menu of one of the videos?

**Comment by liquidchild101** [comment] 2023-01-26 09:58
Hi, thank you for the reply. ( and sorry for the late reply)

I should have done this before but ive made a video of my issue

https://www.dropbox.com/s/qg0x5ahq4dt2yew/VID_20230126_093630874.mp4?dl=0

@ksooo Maybe I should have added this before but because i wanted to separate my anime and old cartoons from my other media. I use the file explorer to add them. I then save them to my favourites so i can access them easily. Maybe that has something to do with it. Like I said in the OG post. it used to work fine. its only after the upgrade its changed.

- settings are set up to automatically play
- the way i had it set up before is a saved playlist and then i click on any video in the list, it plays them one after another.
- I noticed on the video that the files got duplicated as well - weird

**Comment by ksooo** [comment] 2023-01-26 10:23
> settings are set up to automatically play

The setting is not a simple yes/no. Which content types are enabled, should be all of them, especially "uncategorised" seems important according to my latest tests (this was also needed for Matrix, btw.)

> it used to work fine

What is the latest Kodi version you can say for sure that it worked?

**Comment by ksooo** [comment] 2023-01-26 10:32
> I should have done this before but ive made a video of my issue

Honestly, not sure that helps. So many steps, done so fast, ... unable to fully follow and to see the actual problem.

**Comment by liquidchild101** [comment] 2023-01-26 11:36
settings are set up to automatically play: sorry, i should have checked but i assumed that it was correct. my bad. I've fixed that issue now. i added the uncategorised videos to auto play.

it used to work fine: 19.3

then i click on any video in the list: KODI on the Google tv only has one button for enter. either enter, back or direction. nothing else.

I should have done this before but ive made a video of my issue: sorry about that. Ive created another 2 videos showing the old 19.3 version i have in the bedroom and what i have downstairs with v20

ive made up some video showing the difference -  What it looks like is the file version of a playlist and the "playlist view" version are two different entities. the file explore version is in alphabetical order but the playlist view (when opened from the side panel) is the correct shuffled version.

this problem is so unique to me i doubt this'll be fixed so im guessing the best thing i can do is downgrade my version by uninstalling what i have currently and installing the older version.

please still take a look at my video just incase you might know a solution.

Part 1: https://www.dropbox.com/s/jt1v2s6g38kqnw5/part%201.mp4?dl=0
Part 2: https://www.dropbox.com/s/9xut5b1z7x55a6b/part%202.mp4?dl=0

**Comment by ksooo** [comment] 2023-01-26 11:39
> i added the uncategorised videos to auto play.

And does it make a difference? There are chances that this is important.

**Comment by liquidchild101** [comment] 2023-01-26 11:55
Auto play is fixed  - the only thing i didnt check is that it would auto play for all file explore version. not just the playlist versions. the biggest issue is the playlist not keeping the shuffle. Like i explained/found out (in the videos) i think the playlist and file explore are two different entities that i used to use as a playlist.

have you got any comments on the video? sorry if i was going to fast

**Comment by ksooo** [comment] 2023-01-26 12:04
Thanks for the new videos. I will have a look later today.

**Comment by AshleyAshes** [comment] 2023-01-26 14:44
Hi, I was about to write a bug report but this apparently has already been reported but I think the OP has not quite worded it well.  Part of it is leveraged on this description of random orders.  But this issue would apply if you just manually queued a few items, in no particular order, and saved the playlist.

The issue appears that upon loading of an M3U playlist, the order of that playlist is discarded and it is instead sorted alphabetically.  If you have Kodi save an M3U playlist and the order of that playlist is:

E, A, B, C, D

Upon later playing or queue that M3U, regardless of the order of entries in the M3U itself, Kodi will sort them alphabetically, resulting in this order:

A, B, C, D, E

Kodi is entirely discarding the order in the M3U playlist itself and instead sorting the entries on the playlist.  This kinda undermines the entire point of an M3U playlist, it's supposed to be a list in a specific order, not a collection of entries to be sorted in a new order.

To reproduce this, simply build a queue/playlist in Kodi of a few items that are def NOT already in alphabetical order, save that as an M3U, clear the current playlist, load that M3U, and see that the order of the M3U playlist has been sorted.

If you need some screenshots and a log, let me know.

**Comment by ksooo** [comment] 2023-01-26 14:51
What I see as a difference between the two videos is that where it works (Matrix) the sort method for the content of the m3u is by "Playlist" (upper left corner of the videos window) and in the Nexus videos it shows sort by "Name". What if you just change the sort method to by "Playlist"? You can do this in the side blade of the window.

**Comment by AshleyAshes** [comment] 2023-01-26 14:59
> What if you just change the sort method to by "Playlist"? 

I think you just accidently figured it out. :)  There IS no 'Playlist' sort option in v20.  See this screenshot:

https://i.imgur.com/CTNlQqj.png

**Comment by liquidchild101** [comment] 2023-01-26 15:29
Looks like AshleyAshes is correct. There is no "Playlist" in the v20 sort options. 

in v19.3 there is, plus a load of others
https://www.dropbox.com/s/dnr4h24vrtjr3j3/325032553_2097800867078048_2137716345330551312_n.jpg?dl=0

**Comment by ksooo** [comment] 2023-01-26 18:28
Strange. Is this sort option available in 19.3? I had a look at 19.5 and can’t find it there either.

**Comment by ksooo** [comment] 2023-01-26 18:50
The "Playlist" sort method got lost from 19.4 to 19.5 - this is at least a starting point for investigations...

**Comment by AshleyAshes** [comment] 2023-01-26 18:57
You're right.  My mistake.  This didn't start with v20, it started with v19.5.  19.5 did drop Christmas Eve, so I was barely touching playlists for a few weeks there and likely just never noticed.  But yeah, the behavior starts in v19.5.  In 19.5 if I load an M3U playlist, it seems to be 'missing' the Playlist sort option (And a bunch of others it seems), which also means using the 'play' or 'queue item' from the context menu and means it can't add it to Kodi's own playlist in the default sorting of 'Playlist' so it goes falls back to going by name.

**Comment by ksooo** [comment] 2023-01-26 19:07
@CastagnaIT for the playlist sort order/method regressions discussed here, i feel the following PR of you is the root cause: https://github.com/xbmc/xbmc/pull/21667

**Comment by ksooo** [comment] 2023-01-26 19:16
@CastagnaIT confirming that reverting #21667 brings back sort method "Playlist" - runtime-tested it on master.

**Comment by liquidchild101** [comment] 2023-01-26 20:45
Im glad i wasnt going mad. i know i dont really have any say in this but what would be the next step?

Will this be a fix that is pushed out quickly or is this more of wait for the next update in a month or two?

If its latter i think the best option for me is to downgrade for the moment till its fixed.

thanks for picking this up and all the work you guys do. your the best xxx

**Comment by AshleyAshes** [comment] 2023-01-26 21:17
Another playlist issue I spotted and pointed out, refusing to even properly play M3U playlists, was fixed in a matter of days and was already in the v20 nightly as of this morning.  ...It's just that this morning is where I then realized that this was an issue with M3U playlists as well.  So if they're also able to push out a fix, you could run the necessary nightly.  ...which hopefully doesn't have any other new issues, it's a nightly afterall.

**Comment by ksooo** [comment] 2023-01-26 22:44
@CastagnaIT fix could be as simple as this:

```diff
diff --git a/xbmc/video/GUIViewStateVideo.cpp b/xbmc/video/GUIViewStateVideo.cpp
index 79e4f4b43f..ab56582c34 100644
--- a/xbmc/video/GUIViewStateVideo.cpp
+++ b/xbmc/video/GUIViewStateVideo.cpp
@@ -614,14 +614,15 @@ CGUIViewStateVideoPlaylist::CGUIViewStateVideoPlaylist(const CFileItemList& item
           CSettings::SETTING_FILELISTS_IGNORETHEWHENSORTING))
     sortAttributes = SortAttributeIgnoreArticle;
 
+  AddSortMethod(SortByPlaylistOrder, 559, LABEL_MASKS("%L", "")); // Label, empty
   AddSortMethod(SortByLabel, sortAttributes, 551,
                 LABEL_MASKS("%L", "%I", "%L", "")); // Label, Size | Label, empty
   AddSortMethod(SortBySize, 553, LABEL_MASKS("%L", "%I", "%L", "%I")); // Label, Size | Label, Size
   AddSortMethod(SortByDate, 552, LABEL_MASKS("%L", "%J", "%L", "%J")); // Label, Date | Label, Date
   AddSortMethod(SortByFile, 561, LABEL_MASKS("%L", "%I", "%L", "")); // Label, Size | Label, empty
 
+  SetSortMethod(SortByPlaylistOrder);
   const CViewState* viewState = CViewStateSettings::GetInstance().Get("videofiles");
-  SetSortMethod(viewState->m_sortDescription);
   SetViewAsControl(viewState->m_viewMode);
   SetSortOrder(viewState->m_sortDescription.sortOrder);
 
```

**Comment by CastagnaIT** [comment] 2023-01-27 08:19
@ksooo thanks for the tip look like the right way
completely missed from my last changes

**Comment by liquidchild101** [comment] 2023-01-27 09:44
> Another playlist issue I spotted and pointed out, refusing to even properly play M3U playlists, was fixed in a matter of days and was already in the v20 nightly as of this morning. ...It's just that this morning is where I then realized that this was an issue with M3U playlists as well. So if they're also able to push out a fix, you could run the necessary nightly. ...which hopefully doesn't have any other new issues, it's a nightly afterall.

Cool cool, im on Google TV ( Android) so ill keep on seeing if theres an update, i guess? otherwise ill downgrade for the moment.

**Comment by CastagnaIT** [comment] 2023-01-27 09:48
if someone want give a feedback
these are android test builds of kodi 21:
https://jenkins.kodi.tv/job/android-arm-docker/350/artifact/kodi-20230127-db7eed16-PR22598-armeabi-v7a.apk
https://jenkins.kodi.tv/job/android-arm64-docker/419/artifact/kodi-20230127-db7eed16-PR22598-arm64-v8a.apk

**Comment by AshleyAshes** [comment] 2023-01-27 14:06
My clients are all Windows here, if you have a Windows build with that fix I'll test it.

**Comment by CastagnaIT** [comment] 2023-01-27 18:19
Windows64 test build http://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20230127-7a0c7b28-viewstate_fix-x64.exe

**Comment by AshleyAshes** [comment] 2023-01-27 21:35
So, I think this fixes it.  When I 'browse into' an M3U playlist it has the 'Playlist' as the default order on Windows 10 x64.

**Closed** 2023-01-28 12:37 UTC
Labels: Triage: Confirmed, v20 Nexus, v21 Omega
