### ISSUE TITLE
Estuary - Movie watched checkmark on white poster not visible

### ISSUE THREAD

**Issue by theshimonmor** [xbmc/xbmc#24144] opened 2023-11-25 15:35 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

On Estuary skin, a couple of updates ago, the "watched" check mark moved from next to the movie name to the lower left corner of the poster.  But now, when the poster is white in that lower corner, you can't see the check mark.  As shown below (each movie has a check mark and some are barely visible while others are not visible at all) in the attached screenshot linked below.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The check mark should be visible on all poster colors or moved back to appear next to movie title.

## Actual Behavior

The white check mark to indicate movie has been watched is invisible on posters that are white in the lower left hand corner.

## Possible Fix

The white check mark can be moved back to appear next to the movie title below the poster.  Or the white check mark can have a black outline to provide contrast against white posters.  Or the white check mark can have an "outer glow" (like in Photoshop blending options). 

### To Reproduce

1.  Go to "Movies" and have them displayed as posters.
2.  Toggle a movie "as watched" on a poster with a light or white background.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

  <img  src="https://shimonmor.com/TEMP/kodimoviewatched.png"/>

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
 - 
20.2 CoreELEC on an Odroid N2 with Estuary skin

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by jjd-uk** [comment] 2023-11-25 18:02
Duplicate of https://github.com/xbmc/xbmc/issues/22765

**Closed** 2023-11-25 18:02 UTC
Labels: Triage: Needed

**Comment by jjd-uk** [comment] 2023-11-25 18:06
Thanks for report, as mentioned this is a known issue. A fix has been attempted but it's not so easy. We probably to redo these icons so they don't require a background which is beyond my skill.

**Comment by jjd-uk** [comment] 2023-11-25 18:15
Because we want consistency through the skin, and in all other places the check mark is placed on the poster. In addition we want consistency between icon types, so it's not just the Watched check mark that needs to be considered, there's other icons such as the one for Movie Sets.

**Comment by b-jesch** [comment] 2023-11-25 19:13
Assign this to @HitcherUK as proposed here: https://forum.kodi.tv/showthread.php?tid=375142&pid=3173281#pid3173281
A possible solution I've already posted in my issue report: #24145

**Comment by jjd-uk** [comment] 2023-11-25 21:39
I tried something similar to that before and it didn't work out. However your suggestion looks to be slightly different in the grouping, so I'll take another look at this.

**Comment by b-jesch** [comment] 2023-11-25 22:38
My suggestion is to make an include for those condition marks. Put this somewhere into Includes.xml
```
<include name="ConditionMarker">
    <param name="left" value="37" /> 
    <param name="top" value="155" />
    <param name="visible" value="String.StartsWith(Container.FolderPath,plugin://plugin.video) + !Container.Content(artists) + [ListItem.IsRecording | ListItem.HasReminder | ListItem.HasTimer | ListItem.IsCollection | ListItem.IsPlaying | ListItem.IsResumable | Integer.IsGreater(ListItem.Playcount,0) | ListItem.HasArchive]" />
    <definition>
    <control type="group">
        <left>$PARAM[left]</left>
        <top>$PARAM[top]</top>
        <visible>$PARAM[visible]</visible>
        <control type="image">
            <width>70</width>
            <height>70</height>
            <texture>overlays/overlay-bg.png</texture>
        </control>
        <control type="image">
            <left>3</left>
            <top>37</top>
            <width>32</width>
            <height>32</height>
           <texture>$VAR[WallWatchedIconVar]</texture>
        </control>
    </definition>
</include>
```
Calling this include is simply. Position for left is almost the same so you don't need do redefine it. Same for visibility. Only top has to modify for several views. Search for `$VAR[WallWatchedIcon]` and replace the entire image control with

```
<include content="ConditionMarker">
     <param name="top" value="300" />    <!-- modify this for the different views -->
</include>
```
Don't forget to remove the image control above which contains the `overlays/overlay-bg.png` texture
