### ISSUE TITLE
Kodi Nexus crashes when running the pvr.enigma addon on Android 

### ISSUE THREAD

**Issue by forsajd1** [xbmc/xbmc#22501] opened 2023-01-17 11:48 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:  Kodi crashes when trying to start with a PVR Enigma addon enabled. Edit: Plugin PVR Enigma cannot be run on any android, TV android, Android Box, Smartphone with Android

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

Install a pvr addon enigma
Configure account in addon
Kodi crashes when trying to start the addon

### Debuglog

The debuglog can be found here: https://paste.kodi.tv/yidapejube.kodi    https://paste.kodi.tv/doduxocuxa.kodi 

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android TV  9
 - Kodi version: Nexus 20 

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by outkastm** [comment] 2023-01-18 19:01
Same issue here

**Comment by ksooo** [comment] 2023-01-19 21:07
@phunkyfish same root cause as https://github.com/xbmc/xbmc/issues/22495 ? If so, add-on needs to be fixed.

**Comment by phunkyfish** [comment] 2023-01-19 21:47
Probably but I have no enigma2 currently to test this with. I guess I can just try it with no device and see if it crashes.

**Comment by forsajd1** [comment] 2023-01-19 23:13
it can be installed, only when you enter the IP address of the satellite box and confirm, the pvr client starts loading programs, only then does the entire kodi fall into android

**Comment by phunkyfish** [comment] 2023-01-20 22:49
Finally got an enigma2 box up and running and I could not reproduce. So the root cause is something else.

**Comment by phunkyfish** [comment] 2023-01-20 23:00
From your log the crash looks to happen when trying to load recordings.

**Comment by forsajd1** [comment] 2023-01-20 23:54
exactly

**Comment by phunkyfish** [comment] 2023-01-21 12:57
But I really need a debugger trace or something to be able to dig in further.

**Comment by forsajd1** [comment] 2023-01-21 14:03
as for logs, they have debugging enabled

**Comment by lagos911** [comment] 2023-01-23 08:32
I own a toshiba android tv with android 9.
The app crash when the enigma 2 pvr addon its trying to update the guide for the channels...
I am able to stream for my receiver for 2 minutes then the app crash after a specific time.
I try to find at the settings of the addon an option to disable updating the guide but i dont find it.
I enable the log but I cant find any information about it.
I install 19.5 and now its working fine!

**Comment by outkastm** [comment] 2023-01-23 09:29
here what is happenning when it crash on Android TV. On my Android phone is working fine
Do you need more info from ADB ?

`
01-23 10:27:28.972 18341 18417 D Kodi    : 2023-01-23 10:27:28.972 T:18417   debug <general>: CurlFile::Open - <http://192.168.25.8:87/web/epgservice?sRef=1%3A0%3A1%3A55C%3A4%3A1%3AE080000%3A0%3A0%3A0%3A>
01-23 10:27:29.543 18341 18416 D Kodi    : 2023-01-23 10:27:29.543 T:18416   debug <general>: AddOnLog: pvr.vuplus: pvr.vuplus - GetHttp Got result. Length: 1482
01-23 10:27:29.545 18341 18416 D Kodi    : 2023-01-23 10:27:29.545 T:18416   debug <general>: AddOnLog: pvr.vuplus: pvr.vuplus - GetDriveSpace Space Total: 488426700, Used 278606643
01-23 10:27:29.568 18341 18417 D Kodi    : 2023-01-23 10:27:29.568 T:18417   debug <general>: AddOnLog: pvr.vuplus: pvr.vuplus - GetHttp Got result. Length: 45549
01-23 10:27:29.594 18341 18417 D Kodi    : 2023-01-23 10:27:29.594 T:18417   debug <general>: AddOnLog: pvr.vuplus: pvr.vuplus - GetEPGForChannel Loaded 51 EPG Entries for channel 'ACASA'
01-23 10:27:29.600 18341 18417 D Kodi    : 2023-01-23 10:27:29.600 T:18417   debug <general>: UpdateFromScraper: Updating EPG for channel 'ACASA GOLD' from client '1513173921'
01-23 10:27:29.600 18341 18417 D Kodi    : 2023-01-23 10:27:29.600 T:18417   debug <general>: AddOnLog: pvr.vuplus: pvr.vuplus - GetEPGForChannel Getting EPG for channel 'ACASA GOLD'
01-23 10:27:29.600 18341 18417 D Kodi    : 2023-01-23 10:27:29.600 T:18417   debug <general>: AddOnLog: pvr.vuplus: pvr.vuplus - GetHttp Open webAPI with URL: 'http://USERNAME:PASSWORD@192.168.25.8:87/web/epgservice?sRef=1%3A0%3A1%3A55A%3A4%3A1%3AE080000%3A0%3A0%3A0%3A'
01-23 10:27:29.609 18341 18417 D Kodi    : 2023-01-23 10:27:29.609 T:18417   debug <general>: CurlFile::Open - <http://192.168.25.8:87/web/epgservice?sRef=1%3A0%3A1%3A55A%3A4%3A1%3AE080000%3A0%3A0%3A0%3A>
01-23 10:27:29.883 18341 18410 D Kodi    : 2023-01-23 10:27:29.882 T:18410   debug <general>: UpdateInProgressSize: Updating recordings size
01-23 10:27:30.349 18341 18359 D Kodi    : stack corruption detected (-fstack-protector)
01-23 10:27:30.883 18341 18410 D Kodi    : 2023-01-23 10:27:30.883 T:18410   debug <general>: UpdateInProgressSize: Updating recordings size
01-23 10:27:31.525 18341 18409 D Kodi    : 2023-01-23 10:27:31.524 T:18409   debug <general>: CurlFile::Open - <http://192.168.25.8:87/web/currenttime>
01-23 10:27:31.555 18341 18360 V Kodi    : virtual void CXBMCApp::onPause():
01-23 10:27:31.555 18341 18360 V Kodi    : bool CXBMCApp::EnableWakeLock(bool): false
`

**Comment by phunkyfish** [comment] 2023-01-23 20:22
@outkastm can you try a build from here first: https://jenkins.kodi.tv/job/BuildMulti-PR/24994/ ?

Then I will give you another to try tomorrow.

**Comment by outkastm** [comment] 2023-01-23 21:12
@phunkyfish, correct. Android TV is 32bit ARM and phone is 64bit (aarch64). I will give it a try to the test build

**Comment by outkastm** [comment] 2023-01-23 21:33
still crash, here the log file [https://paste.kodi.tv/afafonajaw.kodi](url)

**Comment by forsajd1** [comment] 2023-01-23 21:34
mobile works well great job, I will try it tomorrow on Android TV

**Comment by phunkyfish** [comment] 2023-01-23 22:14
> mobile works well great job, I will try it tomorrow on Android TV

Are you saying the testbuild fixed the issue on your mobile?

**Comment by phunkyfish** [comment] 2023-01-23 22:16
> still crash, here the log file [log](https://paste.kodi.tv/afafonajaw.kodi)

Ok, I will give you another build to try tomorrow.

**Comment by forsajd1** [comment] 2023-01-23 22:42
> Are you saying the testbuild fixed the issue on your mobile?

yes

**Comment by outkastm** [comment] 2023-01-23 22:59
ok, fyi, my previous log was from a nightbuild (wrongly installed the nightbuild instead of PR24994)
but PR24994 also crash and even faster than the official build.
here the [log](https://paste.kodi.tv/ogeyenupak.kodi)

**Comment by forsajd1** [comment] 2023-01-24 06:54
I confirm that it will crash in Android TV

**Comment by phunkyfish** [comment] 2023-01-24 08:31
Ok, here is another slightly different build: https://jenkins.kodi.tv/job/BuildMulti-PR/25019/

It looks like there might be multiple different reasons why this is crashing, as one of @forsajd1 devices is now working.

**Comment by forsajd1** [comment] 2023-01-24 09:17
phone 64bit

**Comment by forsajd1** [comment] 2023-01-24 09:38
Android TV 32bit  kodi-20230123-68b79252-PR22559-armeabi-v7a.apk  also crash, https://paste.kodi.tv/dayulanige.kodi

**Comment by forsajd1** [comment] 2023-01-24 09:55
old log  https://paste.kodi.tv/xahayixobu.kodi

**Comment by lagos911** [comment] 2023-01-24 09:57
the funny thing is the cpu of my television is 64bit but the android version is 32bit!
Most of the smartphone running 64bit
This why its not crashing at smartphone.

**Comment by phunkyfish** [comment] 2023-01-24 13:17
> the funny thing is the cpu of my television is 64bit but the android version is 32bit!
> Most of the smartphone running 64bit
> This why its not crashing at smartphone.

Yes, SRM processors are weird.

**Comment by outkastm** [comment] 2023-01-24 21:05
confirmed, latest provided test build crash. here the log with debugdump if it helps [log](https://paste.kodi.tv/yofohehecu.kodi)

**Comment by phunkyfish** [comment] 2023-01-24 22:25
> confirmed, latest provided test build crash. here the log with debugdump if it helps [log](https://paste.kodi.tv/yofohehecu.kodi)

What I really need now is a way to get you a debug build of the addon so it will tell us exactly what line of code is causing the problem in the addon.

**Comment by phunkyfish** [comment] 2023-01-24 23:12
@outkastm can you try https://mirrors.kodi.tv/test-builds/android/arm/kodi-20230124-61572496-fix-limits-kodi-vfs-readline-27978-armeabi-v7a.apk

Hopefully it is kodi with pvr.vuplus preinstalled. I'm not sure if it will be a debug build but let's try it and see.

**Comment by phunkyfish** [comment] 2023-01-25 08:30
@outkastm, ok, this is the build with DEBUG enabled. It should include `pvr.vuplus` as part of the add-on build, meaning the stack trace show the affected lines in the add-on (hopefully).

https://mirrors.kodi.tv/test-builds/android/arm/kodi-20230124-61572496-fix-limits-kodi-vfs-readline-27979-armeabi-v7a.apk

**Comment by forsajd1** [comment] 2023-01-25 08:49
the pre-installed PVR enigma is already working fine

**Comment by phunkyfish** [comment] 2023-01-25 08:56
> the pre-installed PVR enigma is already working fine

On Android TV?

**Comment by forsajd1** [comment] 2023-01-25 09:03
Yes Android TV

**Comment by phunkyfish** [comment] 2023-01-25 09:48
👍

**Comment by outkastm** [comment] 2023-01-25 20:49
Installing PR27979 over the previous build, Kodi crashed with the log file below
````
--------- beginning of crash
01-25 21:14:10.857 26878 27269 F libc    : stack corruption detected (-fstack-protector)
01-25 21:14:10.857 26878 27269 F libc    : Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 27269 (Thread-13), pid 26878 (org.xbmc.kodi)
01-25 21:14:11.018 27303 27303 I crash_dump32: obtaining output fd from tombstoned, type: kDebuggerdTombstone
01-25 21:14:11.026  2457  2457 I /system/bin/tombstoned: received crash request for pid 27269
01-25 21:14:11.028 27303 27303 I crash_dump32: performing dump of process 26878 (target tid = 27269)
01-25 21:14:11.064 27303 27303 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
01-25 21:14:11.064 27303 27303 F DEBUG   : Build fingerprint: 'Philips/PH9M_EA_5599/PH9M_EA_5599:9/PTT1.181130.001/2950:user/release-keys'
01-25 21:14:11.064 27303 27303 F DEBUG   : Revision: '0'
01-25 21:14:11.064 27303 27303 F DEBUG   : ABI: 'arm'
01-25 21:14:11.064 27303 27303 F DEBUG   : pid: 26878, tid: 27269, name: Thread-13  >>> org.xbmc.kodi <<<
01-25 21:14:11.064 27303 27303 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
01-25 21:14:11.064 27303 27303 F DEBUG   : Abort message: 'stack corruption detected (-fstack-protector)'
01-25 21:14:11.064 27303 27303 F DEBUG   :     r0  00000000  r1  00006a85  r2  00000006  r3  efb5f830
01-25 21:14:11.065 27303 27303 F DEBUG   :     r4  000068fe  r5  00006a85  r6  be7fee1c  r7  0000010c
01-25 21:14:11.065 27303 27303 F DEBUG   :     r8  efb71d8c  r9  efb71d8c  r10 c3e7eb24  r11 be7ff258
01-25 21:14:11.065 27303 27303 F DEBUG   :     ip  00000041  sp  be7fee08  lr  efaeb105  pc  efae2e92
01-25 21:14:11.066 27303 27303 I unwind  : Malformed section header found, ignoring...
01-25 21:14:11.145 27303 27303 F DEBUG   : 
01-25 21:14:11.145 27303 27303 F DEBUG   : backtrace:
01-25 21:14:11.145 27303 27303 F DEBUG   :     #00 pc 0001ce92  /system/lib/libc.so (abort+62)
01-25 21:14:11.145 27303 27303 F DEBUG   :     #01 pc 00053bfb  /system/lib/libc.so (__stack_chk_fail+10)
01-25 21:14:11.145 27303 27303 F DEBUG   :     #02 pc 000a3fd8  /data/data/org.xbmc.kodi/cache/lib/libpvr.vuplus.so
01-25 21:14:11.145 27303 27303 F DEBUG   :     #03 pc 000a39b0  /data/data/org.xbmc.kodi/cache/lib/libpvr.vuplus.so
01-25 21:14:11.145 27303 27303 F DEBUG   :     #04 pc 000a7bd0  /data/data/org.xbmc.kodi/cache/lib/libpvr.vuplus.so
01-25 21:14:11.145 27303 27303 F DEBUG   :     #05 pc 000a7ccc  /data/data/org.xbmc.kodi/cache/lib/libpvr.vuplus.so
01-25 21:14:11.145 27303 27303 F DEBUG   :     #06 pc 0006c6b0  /data/data/org.xbmc.kodi/cache/lib/libpvr.vuplus.so
01-25 21:14:11.145 27303 27303 F DEBUG   :     #07 pc 00038740  /data/data/org.xbmc.kodi/cache/lib/libpvr.vuplus.so
01-25 21:14:11.145 27303 27303 F DEBUG   :     #08 pc 0003cdd0  /data/data/org.xbmc.kodi/cache/lib/libpvr.vuplus.so
01-25 21:14:11.145 27303 27303 F DEBUG   :     #09 pc 018ed268  /data/app/org.xbmc.kodi-1QNBDc554WFz3A1-1XmsqA==/lib/arm/libkodi.so
01-25 21:14:11.145 27303 27303 F DEBUG   :     #10 pc 01923d20  /data/app/org.xbmc.kodi-1QNBDc554WFz3A1-1XmsqA==/lib/arm/libkodi.so (std::__ndk1::function<PVR_ERROR (AddonInstance_PVR const*)>::operator()(AddonInstance_PVR const*) const+52)
01-25 21:14:11.145 27303 27303 F DEBUG   :     #11 pc 018df2c0  /data/app/org.xbmc.kodi-1QNBDc554WFz3A1-1XmsqA==/lib/arm/libkodi.so (PVR::CPVRClient::DoAddonCall(char const*, std::__ndk1::function<PVR_ERROR (AddonInstance_PVR const*)> const&, bool, bool) const+280)
01-25 21:14:11.145 27303 27303 F DEBUG   :     #12 pc 018dfd78  /data/app/org.xbmc.kodi-1QNBDc554WFz3A1-1XmsqA==/lib/arm/libkodi.so (PVR::CPVRClient::GetEPGForChannel(int, PVR::CPVREpg*, long, long)+108)
01-25 21:14:11.145 27303 27303 F DEBUG   :     #13 pc 0187db58  /data/app/org.xbmc.kodi-1QNBDc554WFz3A1-1XmsqA==/lib/arm/libkodi.so (PVR::CPVREpg::UpdateFromScraper(long, long, bool)+444)
01-25 21:14:11.145 27303 27303 F DEBUG   :     #14 pc 0187e38c  /data/app/org.xbmc.kodi-1QNBDc554WFz3A1-1XmsqA==/lib/arm/libkodi.so (PVR::CPVREpg::Update(long, long, int, int, std::__ndk1::shared_ptr<PVR::CPVREpgDatabase> const&, bool)+468)
01-25 21:14:11.145 27303 27303 F DEBUG   :     #15 pc 01873198  /data/app/org.xbmc.kodi-1QNBDc554WFz3A1-1XmsqA==/lib/arm/libkodi.so (PVR::CPVREpgContainer::UpdateEPG(bool)+956)
01-25 21:14:11.145 27303 27303 F DEBUG   :     #16 pc 018728c8  /data/app/org.xbmc.kodi-1QNBDc554WFz3A1-1XmsqA==/lib/arm/libkodi.so (PVR::CPVREpgContainer::Process()+356)
01-25 21:14:11.145 27303 27303 F DEBUG   :     #17 pc 013978f0  /data/app/org.xbmc.kodi-1QNBDc554WFz3A1-1XmsqA==/lib/arm/libkodi.so (CThread::Action()+40)
01-25 21:14:11.145 27303 27303 F DEBUG   :     #18 pc 01397e0c  /data/app/org.xbmc.kodi-1QNBDc554WFz3A1-1XmsqA==/lib/arm/libkodi.so
01-25 21:14:11.145 27303 27303 F DEBUG   :     #19 pc 01397c94  /data/app/org.xbmc.kodi-1QNBDc554WFz3A1-1XmsqA==/lib/arm/libkodi.so
01-25 21:14:11.145 27303 27303 F DEBUG   :     #20 pc 01397ac8  /data/app/org.xbmc.kodi-1QNBDc554WFz3A1-1XmsqA==/lib/arm/libkodi.so
01-25 21:14:11.145 27303 27303 F DEBUG   :     #21 pc 00063c85  /system/lib/libc.so (__pthread_start(void*)+22)
01-25 21:14:11.145 27303 27303 F DEBUG   :     #22 pc 0001e085  /system/lib/libc.so (__start_thread+22)
````

Removing and installing again PR27979 and reconfigure the addon, no more crash on AndroidTV.
Thanks for the fix !

**Comment by phunkyfish** [comment] 2023-01-25 21:15
Android 32bit: https://mirrors.kodi.tv/test-builds/android/arm/kodi-20230125-6e4d1923-fix-limits-kodi-vfs-readline-27983-armeabi-v7a.apk
Android 64bit: https://mirrors.kodi.tv/test-builds/android/arm64-v8a/kodi-20230125-07df1389-fix-fileread-mem-overflow-25756-arm64-v8a.apk

**Comment by phunkyfish** [comment] 2023-01-25 22:14
Here is an alternative fix for the same problem for Android 32bit. @forsajd1 if you could also check this that would be great. I'm not sure it will but might be a simpler solution overall.

https://mirrors.kodi.tv/test-builds/android/arm/kodi-20230125-375ec9f4-fix-limits-kodi-vfs-readline-simple-27984-armeabi-v7a.apk

**Comment by forsajd1** [comment] 2023-01-26 06:56
this build 27984 also works

**Comment by didoux85** [comment] 2023-01-26 12:53
Hello, i installed build 27984 on my xiaomi mi box s 4k and i still have the problem

**Comment by phunkyfish** [comment] 2023-01-26 15:30
> Hello, i installed build 27984 on my xiaomi mi box s 4k and i still have the problem

Do you have a crashlog?

**Comment by lagos911** [comment] 2023-01-27 07:31
@didoux85 are you sure xiaomi box needs a 32bit version?

27984 running fine at my android tv with android 9 of 2020

Can I ask something off topic... my tv is with 4K resolution if i go to the kodi settings the resolution is 1080p and I cant change it... why?

**Comment by phunkyfish** [comment] 2023-01-27 08:31
Fixed by: https://github.com/xbmc/xbmc/pull/22592 and https://github.com/kodi-pvr/pvr.vuplus/pull/418

Addons should be available in 24-48 hours

**Closed** 2023-01-27 08:31 UTC

**Comment by phunkyfish** [comment] 2023-01-27 13:26
> Can I ask something off topic... my tv is with 4K resolution if i go to the kodi settings the resolution is 1080p and I cant change it... why?

GitHub is for bugs. Support questions on the kodi forum only please.

**Comment by vatlach** [comment] 2023-01-29 15:14
@phunkyfish

I need use your fix or only update pvr.vuplus addon at Kodi 20.0?

**Comment by phunkyfish** [comment] 2023-01-29 15:45
> @phunkyfish
> 
> I need use your fix or only update pvr.vuplus addon at Kodi 20.0? And possible add option to enable/disable recording list from client? I have many records and when start vuplus addon then spinner runs at my enigma2 receiver for cca 20s

You need version 20.4.2, updating normally should work.

No plans to provide an option to disable recordings. Please don’t use this issue to ask unrelated questions or make feature requests.

**Comment by muech011** [comment] 2023-02-01 17:16
Maybe I understood something wrong, but on my Android TV devices (got 2 of them) KODI is not updating to 20.4.2. It is still at 20.0 and the play store told me everything is up to date. Or do I just have to update the add-on???

**Comment by phunkyfish** [comment] 2023-02-01 18:15
> Maybe I understood something wrong, but on my Android TV devices (got 2 of them) KODI is not updating to 20.4.2. It is still at 20.0 and the play store told me everything is up to date. Or do I just have to update the add-on???

You need to update the addon. The kodi verison will not change.

**Comment by muech011** [comment] 2023-02-01 21:13
Jep. Works. Thanks again.
