### ISSUE TITLE
Kodi fails to play UPnP streams from Panasonic devices with an error code 503 on HTTP.

### ISSUE THREAD

**Issue by pepie34** [xbmc/xbmc#19947] opened 2021-07-07 07:49 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi is not able to play UPnP streams from Panasonic devices (TV and BluRay/DVB-t video recorder).

I have a new Panasonic TV that can record DVB-T programs and then streams them by UPnP.
Kodi correctly discovers the UPnP TV but failed to play any stream from it.

Same behaviour on a Panasonic BluRay/DVB-t video recorder.
Same behaviour on different Kodi versions (Leia and Matrix) on different OS (Linux / macOS / Android / Raspbian).

VLC correctly plays these UPnP streams on all the combination devices / OS I can try.

Apparently it is an old bug and a regression from older Kodi version:

- https://forum.kodi.tv/showthread.php?tid=282934

Same debug log as me: error code 503 on HTTP when fetching the stream.

## Expected Behavior

Kodi should correctly play UPnP streams from Panasonic devices.

## Actual Behavior

Kodi fails to play UPnP streams from Panasonic devices with an error code 503 on HTTP.

## Possible Fix

Unknown

### To Reproduce

1. Explore a Panasonic device with UPnP
2. Try to play a stream
3. It fails

### Debuglog

```
2021-07-07 09:40:24.750 T:1001925   ERROR <general>: CCurlFile::FillBuffer - Failed: HTTP returned error 503
2021-07-07 09:40:24.751 T:1001925   ERROR <general>: CCurlFile::Open failed with code 503 for http://192.168.119.105:7501/VIDEO-H8e6f1a7857b61b9378471a91b54e638a00ecf4108f63767636e8803b133a05bd-e6862c516fc53abf04f50d8b6c977e1f0000000c:
2021-07-07 09:40:25.045 T:1000951    INFO <general>: VideoPlayer::OpenFile: upnp://4D454930-0000-1000-8001-B46C4793B837/12-fullseg-s2/
2021-07-07 09:40:29.769 T:1001925   ERROR <general>: CCurlFile::FillBuffer - Failed: HTTP returned error 503
2021-07-07 09:40:29.769 T:1001925   ERROR <general>: CCurlFile::Open failed with code 503 for http://192.168.119.105:7501/VIDEO-H8e6f1a7857b61b9378471a91b54e638a00ecf4108f63767636e8803b133a05bd-e6862c516fc53abf04f50d8b6c977e1f0000000c:

2021-07-07 09:40:29.770 T:1001925   ERROR <general>: CFileCache::Open - <http://192.168.119.105:7501/VIDEO-H8e6f1a7857b61b9378471a91b54e638a00ecf4108f63767636e8803b133a05bd-e6862c516fc53abf04f50d8b6c977e1f0000000c> failed to open
2021-07-07 09:40:29.770 T:1001925   ERROR <general>: CVideoPlayer::OpenInputStream - error opening [upnp://4D454930-0000-1000-8001-B46C4793B837/12-fullseg-s2/]
2021-07-07 09:40:29.772 T:1001925    INFO <general>: CVideoPlayer::OnExit()
2021-07-07 09:40:35.081 T:1000951   ERROR <general>: CCurlFile::Stat - Failed: HTTP response code said error(22) for http://192.168.119.105:7501/VIDEO-H8e6f1a7857b61b9378471a91b54e638a00ecf4108f63767636e8803b133a05bd-e6862c516fc53abf04f50d8b6c977e1f0000000c
```

### Your Environment
Used Operating system:

 - [ V] Android
 - [ ] iOS
 - [ ] tvOS
 - [ V] Linux
 - [ V] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu / Raspbian / macOS / Android
 - Kodi version: Leia , Matrix

**Comment by malard** [comment] 2024-01-28 13:54
closing as no-one has touched this ticket in 3 years

**Closed by malard** 2024-01-28 13:54 UTC

**Comment by BadIDMan** [comment] 2024-08-08 11:02
Why has no one touched this?
VLC can play TV recorded video files available via UPnP.
Kodi developers can't handle and fix this? Lack of knowledge?

**Comment by enen92** [comment] 2024-08-08 12:13
Yes we're all dumb

**Comment by BadIDMan** [comment] 2024-08-08 12:23
> Yes we're all dumb

Found this: https://forum.kodi.tv/showthread.php?tid=282934
Almost 10 years not able to fix.
Yeah, indeed you are all dumb.
What a pity. LOL

**Comment by ksooo** [comment] 2024-08-08 12:31
Looking at this URL 
`http://192.168.119.105:7501/VIDEO-H8e6f1a7857b61b9378471a91b54e638a00ecf4108f63767636e8803b133a05bd-e6862c516fc53abf04f50d8b6c977e1f0000000c:` esp. the ':' at the end, I tend to say, blame Panasonic to be dumb because they provide syntactically incorrect URLs. But as you said, Kodi devs are all dumb.

**Comment by BadIDMan** [comment] 2024-08-08 13:14
No. Panasonic's syntax is correct.
If I run on my PC the following command:
"C:\Program Files\VideoLAN\VLC\vlc.exe" http://192.168.1.116:7501/VIDEO-H881241d44d46f8744154b38245775b0beb9ee063b0ff6b2e02f7acad79ebf487-e9d7ee9e9f96a4b7e00e2d138724d8c7000000f0

it opens video file from my Panasonic TV:
![image](https://github.com/user-attachments/assets/3ae39234-f9a9-41c9-9196-8aee4707c62a)

but Kodi Player is unable to play this video generating error that I pasted in Kodi forum:
https://forum.kodi.tv/showthread.php?tid=282934&pid=3206155#pid3206155

Of course it's possible to use "external player" by using playercorefactory.xml file:
```
<playercorefactory>
<players>
   <player name="VLC" type="ExternalPlayer" audio="false" video="true">
     <filename>C:\Program Files\VideoLAN\VLC\vlc.exe</filename>
     <args>"{1}" /fullscreen /close</args>
     <hidexbmc>false</hidexbmc>
     <hideconsole>false</hideconsole>
     <warpcursor>none</warpcursor>
   </player>
</players>
<rules action="prepend">
   <rule filename=".*:7501/*." player="VLC"/>
</rules>
</playercorefactory>
```
but this is clear evidence that the built-in Kodi player cannot handle/play Panasonic TV's files, while VLC can.

**Comment by ksooo** [comment] 2024-08-08 14:24
Okay, I was wrong. The ':' gets added by the log message, and is not part of the URL provided by your TV.

```
    CLog::Log(LOGERROR, "CCurlFile::{} - <{}> Failed with code {}:\n{}", __FUNCTION__,
              redactPath, m_httpresponse, error);
```

**Comment by BadIDMan** [comment] 2024-08-08 15:00
I'm available to check your test builds if you decide to start working on this issue.

**Comment by enen92** [comment] 2024-08-08 17:53
Provide a pcap of your Kodi device while trying to play the file

**Comment by BadIDMan** [comment] 2024-08-08 19:20
I'm available to check your test builds if you decide to start working on this issue.

> Provide a pcap of your Kodi device while trying to play the file. Also afterwards try to play it with vlc so that the pcap contains both requests

Would it be better for you to analyze network traffic if it will be two separate pcap files?

**Comment by enen92** [comment] 2024-08-08 20:00
Any option will do, as long as we can compare both requests

**Comment by BadIDMan** [comment] 2024-08-08 20:23
> Any option will do, as long as we can compare both requests

OK, uploading two files. Names of files explain in which scenario network traffic had been captured.
[pcap-Kodi.vs.VLC-UPnP.zip](https://github.com/user-attachments/files/16553083/pcap-Kodi.vs.VLC-UPnP.zip)

**Comment by enen92** [comment] 2024-08-08 21:31
Seems like the panasonic device doesn't like some of the headers kodi passes. I'd try to debug it using curl to find out the offending one (likely the accept-encoding or the charset since the options request doesn't return any content-type).

request 1:
`curl -v --header "User-Agent: Kodi/21.0 (Windows NT 10.0.22631.3880; Win64; x64) App_Bitness/64 Version/21.0-(21.0.0)-Git:20240406-60c4500054" --header "Accept: */*" --header "Accept-Encoding: deflate, gzip, br" --header "Accept-Charset: UTF-8,*;q=0.8" --header "Range: bytes=0-" http://192.168.1.116:7501/VIDEO-H881241d44d46f8744154b38245775b0beb9ee063b0ff6b2e02f7acad79ebf487-5b7892b3fa66889bb9dac663b0f5cd2300000050`

request 2:
`curl -v --header "User-Agent: Kodi/21.0 (Windows NT 10.0.22631.3880; Win64; x64) App_Bitness/64 Version/21.0-(21.0.0)-Git:20240406-60c4500054" --header "Accept: */*" --header "Accept-Charset: UTF-8,*;q=0.8" --header "Range: bytes=0-" http://192.168.1.116:7501/VIDEO-H881241d44d46f8744154b38245775b0beb9ee063b0ff6b2e02f7acad79ebf487-5b7892b3fa66889bb9dac663b0f5cd2300000050`

request 3:
`curl -v --header "User-Agent: Kodi/21.0 (Windows NT 10.0.22631.3880; Win64; x64) App_Bitness/64 Version/21.0-(21.0.0)-Git:20240406-60c4500054" --header "Accept: */*" --header "Range: bytes=0-" http://192.168.1.116:7501/VIDEO-H881241d44d46f8744154b38245775b0beb9ee063b0ff6b2e02f7acad79ebf487-5b7892b3fa66889bb9dac663b0f5cd2300000050`

request 4:
`curl -v --header "User-Agent: Kodi/21.0 (Windows NT 10.0.22631.3880; Win64; x64) App_Bitness/64 Version/21.0-(21.0.0)-Git:20240406-60c4500054" --header "Accept: */*" --header "Accept-Encoding: deflate, gzip, br" --header "Range: bytes=0-" http://192.168.1.116:7501/VIDEO-H881241d44d46f8744154b38245775b0beb9ee063b0ff6b2e02f7acad79ebf487-5b7892b3fa66889bb9dac663b0f5cd2300000050`

Check if any of the requests return a status code different from 503. Not sure if the syntax for curl on windows is different.

**Comment by BadIDMan** [comment] 2024-08-09 06:21
Responses for requests are as follow:

Request #1:
*   Trying 192.168.1.116:7501...
* Connected to 192.168.1.116 (192.168.1.116) port 7501
> GET /VIDEO-H881241d44d46f8744154b38245775b0beb9ee063b0ff6b2e02f7acad79ebf487-5b7892b3fa66889bb9dac663b0f5cd2300000050 HTTP/1.1
> Host: 192.168.1.116:7501
> User-Agent: Kodi/21.0 (Windows NT 10.0.22631.3880; Win64; x64) App_Bitness/64 Version/21.0-(21.0.0)-Git:20240406-60c4500054
> Accept: */*
> Accept-Encoding: deflate, gzip, br
> Accept-Charset: UTF-8,*;q=0.8
> Range: bytes=0-
>
< HTTP/1.1 406 Not Acceptable
< Date: Fri, 09 Aug 2024 06:16:32 GMT
< Server: Panasonic MIL-SV/1.0
< Error.pxni.panasonic.com: 9999
<
* no chunk, no close, no size. Assume close to signal end
* Request completely sent off
* Closing connection




Request #2:
*   Trying 192.168.1.116:7501...
* Connected to 192.168.1.116 (192.168.1.116) port 7501
> GET /VIDEO-H881241d44d46f8744154b38245775b0beb9ee063b0ff6b2e02f7acad79ebf487-5b7892b3fa66889bb9dac663b0f5cd2300000050 HTTP/1.1
> Host: 192.168.1.116:7501
> User-Agent: Kodi/21.0 (Windows NT 10.0.22631.3880; Win64; x64) App_Bitness/64 Version/21.0-(21.0.0)-Git:20240406-60c4500054
> Accept: */*
> Accept-Charset: UTF-8,*;q=0.8
> Range: bytes=0-
>
< HTTP/1.1 406 Not Acceptable
< Date: Fri, 09 Aug 2024 06:17:22 GMT
< Server: Panasonic MIL-SV/1.0
< Error.pxni.panasonic.com: 9999
<
* no chunk, no close, no size. Assume close to signal end
* we are done reading and this is set to close, stop send
* Request completely sent off
* Closing connection




Request #3:
*   Trying 192.168.1.116:7501...
* Connected to 192.168.1.116 (192.168.1.116) port 7501
> GET /VIDEO-H881241d44d46f8744154b38245775b0beb9ee063b0ff6b2e02f7acad79ebf487-5b7892b3fa66889bb9dac663b0f5cd2300000050 HTTP/1.1
> Host: 192.168.1.116:7501
> User-Agent: Kodi/21.0 (Windows NT 10.0.22631.3880; Win64; x64) App_Bitness/64 Version/21.0-(21.0.0)-Git:20240406-60c4500054
> Accept: */*
> Range: bytes=0-
>
< HTTP/1.1 406 Not Acceptable
< Date: Fri, 09 Aug 2024 06:18:57 GMT
< Server: Panasonic MIL-SV/1.0
< Error.pxni.panasonic.com: 9999
<
* no chunk, no close, no size. Assume close to signal end
* we are done reading and this is set to close, stop send
* Request completely sent off
* Closing connection



Request #4:
*   Trying 192.168.1.116:7501...
* Connected to 192.168.1.116 (192.168.1.116) port 7501
> GET /VIDEO-H881241d44d46f8744154b38245775b0beb9ee063b0ff6b2e02f7acad79ebf487-5b7892b3fa66889bb9dac663b0f5cd2300000050 HTTP/1.1
> Host: 192.168.1.116:7501
> User-Agent: Kodi/21.0 (Windows NT 10.0.22631.3880; Win64; x64) App_Bitness/64 Version/21.0-(21.0.0)-Git:20240406-60c4500054
> Accept: */*
> Accept-Encoding: deflate, gzip, br
> Range: bytes=0-
>
< HTTP/1.1 406 Not Acceptable
< Date: Fri, 09 Aug 2024 06:19:48 GMT
< Server: Panasonic MIL-SV/1.0
< Error.pxni.panasonic.com: 9999
<
* no chunk, no close, no size. Assume close to signal end
* we are done reading and this is set to close, stop send
* Request completely sent off
* Closing connection

**Comment by BadIDMan** [comment] 2024-08-26 06:02
Any update for this?

**Comment by BadIDMan** [comment] 2024-09-26 16:32
Seems it is abandoned.
Sad.
I was willing to help in troubleshooting...

**Comment by CrystalP** [comment] 2024-10-09 02:40
The problem is that all curl requests returned in error, even #3, which was most likely to succeed due to fewer headers. Maybe it needs even less headers... or a specific agent.

It's also "interesting" that request #1, identical to Kodi's request in the pcap received a different error from the server.

HTTP/1.1 503 Service Unavailable
Error.pxni.panasonic.com: 9201

vs

HTTP/1.1 406 Not Acceptable
Error.pxni.panasonic.com: 9999

In the VLC capture, VLC also receives 406 failures for a couple attempts with http 1.1 and some variations of headers, then receives a success for http 1.0 (but http 1.1 reply... see frames 67and 76)
request:
```
GET /VIDEO-H881241d44d46f8744154b38245775b0beb9ee063b0ff6b2e02f7acad79ebf487-5b7892b3fa66889bb9dac663b0f5cd2300000050 HTTP/1.0
Host: 192.168.1.116:7501
User-Agent: VLC/4.0.0-dev LibVLC/4.0.0-dev
Icy-MetaData: 1
```
reply:
```
HTTP/1.1 200 OK
Date: Thu, 08 Aug 2024 20:21:28 GMT
Server: Panasonic MIL-SV/1.0
Content-Type: video/vnd.dlna.mpeg-tts
transferMode.dlna.org: Streaming
PRAGMA: no-cache
```

**Comment by pepie34** [comment] 2024-10-12 07:50
If it can help, `wget` is able to handle the stream with its default configuration.

**Comment by enen92** [comment] 2024-10-12 09:36
Post the output with the -v option

**Comment by BadIDMan** [comment] 2025-01-31 07:19
Hmmm, again seems to be forgotten bug :-(
