### ISSUE TITLE
UPNP (client) not working in Kodi v18.x

### ISSUE THREAD

**Issue by 150d** [xbmc/xbmc#16335] opened 2019-07-01 09:01 UTC
### Describe the bug

Kodi v18.x (tested: .0, .1, .2) does not see UPNP servers. If the server IP is manually specified as a "source", no connection can be established.

All devices were working fine with Kodi v17.6, UPNP servers (tested: ServiIO) were perfectly accessible.

## Expected Behavior
- in settings, enable UPNP server and client
- in "sources", select UPNP and "browse" -> UPNP server should be found and displayed for selection

## Actual Behavior
- no UPNP server is found (list stays empty)
- if server IP is manually specified, no connection can be established.

## Possible Fix
- downgrade Kodi to v17.6.

### Your Environment
this does not happen on every device:

WORKING:
- Amazon FireTV Stick 4k

NOT working:
- Amazon FireTV (1st gen.)
- Amazon FireTV Stick (1st. gen)

All devices work with Kodi v17.6 (UPNP server is detected.)

see also forum thread
https://forum.kodi.tv/showthread.php?tid=339904

**Comment by 150d** [comment] 2019-07-01 09:03
> This is an automatically generated message. If you believe it was sent in error, please say so and a team member will remove the "Ignored rules" label.

The automatic message is in error.

**Comment by Rechi** [comment] 2019-07-01 09:05
No automatic message is correct, you removed the Debuglog section from the template.

**Comment by 150d** [comment] 2019-07-01 09:26
The automatic message is not correct: I do not have a debug log. I'm a user, if I were a developer, I would be able to debug the code myself.

**Comment by hudokkow** [comment] 2019-07-01 09:36
No, you need to provide a debug log so we can understand what's going on.

See https://kodi.wiki/view/Log_file/Easy

**Comment by 150d** [comment] 2019-07-02 16:11
Debug log is attached. For me there's zilch in there; I'm very curious whether it'll be of help to you.
[kodi.zip](https://github.com/xbmc/xbmc/files/3350947/kodi.zip)

**Comment by EricV2** [comment] 2019-07-03 07:18
Note that I reported a similar bug sometimes ago but reason may be different. 18.3 does not work better on my faulty device (works on other). Side note : A Matrix network patch to select an interface with a gateway has not been backported AFAIKT.

**Comment by hudokkow** [comment] 2019-07-05 20:17
Thanks.

It's a bad practice to open **unknown** compressed files. For future reference, always use a paste site to upload the log. Unless it is so big paste sites politely decline. ;)

Log is at https://paste.kodi.tv/eyezidudar.kodi

**Comment by EricV2** [comment] 2019-07-07 09:53
Checked your log. Error is the same than on mine. Different device, different android version.  Same place, same error code.

**Comment by kapoios** [comment] 2019-07-18 14:29
Just to add some devices that the devs may be able to test this on. The upnp client does not work in any of my v18.* Kodi installations. Including Pixel 2 XL (official firmware), a Lineage OS 16 Tab S2 as well as Libreelec running on Raspberry Pi. All the devices work using v17 and I have enabled everything under the UPnP/DLNA options menu.

**Comment by wsnipex** [comment] 2019-07-22 08:40
did anyone try a v19 build on those devices yet?

**Comment by EricV2** [comment] 2019-08-15 18:16
@kapoios In your case the kodi server was faulty not the client. In my case the server is OK and is not kodi (minidlna). I have updated the tablet to 18.3 no change.

**Comment by kapoios** [comment] 2019-08-15 18:46
@EricV2

It definitely looked like the client side was at fault, the server was working fine with my smart TV and VLC and a 17.6 client. Not sure what caused it and why it's gone now. The client was not working for me for months in multiple versions of the 18.* branch. I updated everything before gathering logs to upload here but it was gone, so I have nothing to contribute unfortunately.

**Comment by EricV2** [comment] 2019-08-20 16:52
@wsnipex Just tested 19 alpha today. Same behavior.

**Comment by EricV2** [comment] 2019-08-20 17:00
@kapoios Unlike you, all my other 18.3 installations (PC, orther tablet and phone) do work with the same server

**Comment by TomasA** [comment] 2019-11-04 22:49
Same problem here with Raspberry 4B and libreelec (Kodi 18.4). UPnP server can be browsed only when an address of a server is edited. In this case Kodi restart itself and then UPnP works for a while, but still not properly.

**Comment by gggirlgeek** [comment] 2020-01-16 02:34
Is anybody working on this? Is it projected for v19?

**Comment by rbbrtail** [comment] 2020-01-16 10:59
I found it is working for me in Kodi 18.5.

**Comment by elbloom** [comment] 2020-01-19 14:29
Kodi 18.5, all upnp features activated - not seeing server anymore. Worked on 17.6 on Firetvstick 2nd gen. SMB browsing stopped working, too.
VLC seeing everything and plays everything.

Kodi Leia 32bit broke core functionality. Unusable. Pile of trash.

**Comment by m-svo** [comment] 2020-01-19 16:39
Same network, same PC.
Ubuntu 19.10, Kodi 17.6: discovers server, connects, plays videos
Arch Linux, Kodi 18.5.1: does not discover server, does not connect when IP is manually entered

**Comment by Paden** [comment] 2020-02-09 17:48
Server: Nvidia Shield running Kodi 18.5
Client: Fire TV running Kodi 18.5
Does not discover server; does not connect when IP is entered manually.

**Comment by EricV2** [comment] 2020-02-09 18:13
Time to move to vlc where UPnP does work correctly...

**Comment by Jean85** [comment] 2020-03-25 23:14
I'm affected by this same bug too, with OSMC/Kodi 18.6 on Raspberry 3.

**Comment by Jean85** [comment] 2020-03-26 07:02
Is it possible that this is the root of the issue? https://github.com/xbmc/xbmc/issues/14743#issuecomment-452435806

This other user says that on Fire Stick 2, the UPnP is announced in on the first interface only. In my case I have two interfaces on my RPi3 (LAN and WLAN) and I'm using the Ethernet cable, WLAN is disabled. Maybe the UPnP is trying to announce itself there, even if the interface is down?

**Comment by Jean85** [comment] 2020-03-26 09:43
Downgrading to Kodi 17.6 didn't work. I did a clean install with OSMC and got this logs when trying to discover UPnP clients from my laptop using Chrome:

```
10:40:05.167 T:1658319616    INFO: Platinum [neptune.threads.posix]: NPT_PosixThread::NPT_PosixThread
10:40:22.852 T:1925614080    INFO: Previous line repeats 4 times.
10:40:22.853 T:1925614080   DEBUG: -------------Keyboard keyevent----------------
[...]
10:40:22.934 T:1925614080   DEBUG: OnKey: escape (0xf01b) pressed, screen saver/dpms woken up
[...]
10:40:23.938 T:1925614080   DEBUG: ------ Window Deinit () ------
10:40:33.962 T:1649931008    INFO: Platinum [neptune.http]: NPT_CHECK failed, result=-20014 (NPT_ERROR_TIMEOUT) [(result)]
10:40:33.963 T:1658319616    INFO: Platinum [neptune.threads.posix]: NPT_PosixThread::NPT_PosixThread
10:40:36.967 T:1572336384    INFO: Previous line repeats 1 times.
10:40:36.968 T:1572336384    INFO: Platinum [platinum.core.devicehost]: Responding to a M-SEARCH request for upnp:rootdevice
10:40:36.968 T:1649931008    INFO: Platinum [platinum.core.ctrlpoint]: CtrlPoint received a search response from ourselves (56988b1a-0618-2fb7-a3a8-a2e9a2904c6a)
10:40:37.967 T:1438192384    INFO: Platinum [platinum.core.devicehost]: Responding to a M-SEARCH request for upnp:rootdevice
10:40:37.968 T:1649931008    INFO: Platinum [platinum.core.ctrlpoint]: CtrlPoint received a search response from ourselves (56988b1a-0618-2fb7-a3a8-a2e9a2904c6a)
```
`NPT_ERROR_TIMEOUT` seems to indicate no response from Kodi? Also why Kodi sees response from itself? UPnP server was not enabled, only client.

**Comment by gautamkrishnar** [comment] 2020-04-14 21:21
Any fix for this yet? My mac app just crashed on adding a source :smile:

**Comment by ShaheedLegion** [comment] 2020-05-19 10:54
It would be nice if kodi could just ask which interface i'd like to use as a default. Or at least add an override setting or something - if left blank, do whatever it's currently doing, but if the user changes it, then try to use that - and then fall back to whatever the default behaviour is if the user-selected IP isn't available / valid.

**Comment by d-a-v** [comment] 2020-09-04 09:49
Hello,
Here is a UPNP as client crash with `Kodi (18.8 (18.8.0) Git:leia_pi4_18.8-Leia). Platform: Linux ARM 32-bit` on a fresh RPi4/LibreElec installation.

Host logs: http://ix.io/2w6g (generated with `pastekodi`)
Kodi crash: http://ix.io/2w6i (generated with `curl -F 'f:1=<-' ix.io < /storage/.kodi/temp/kodi_crashlog_20200904092940.log`) 

What led to the crash:
- library empty > enter files section
- Add videos > Browse
- upnp:// > OK
- edit upnp:// => `upnp://10.0.1.8` => OK => (screen frozen for some seconds) => BOOM
  10.0.1.8 is UPNP provided by minidlna on a linux server, root container of type `B` which is "Browse Directory", working for ages including with some previous versions of LibreElec (I don't remember when since I have been using samba as workaround for a while) and  commercial clients like a LG TV

I hope this help a dev to reproduce the issue. DLNA directory browsing is faster than SAMBA/CIFS browsing on large volumes.

Thanks !

**Comment by enen92** [comment] 2024-02-13 19:06
Status of this on recent nightlies?

**Comment by enen92** [comment] 2024-02-25 12:50
Closing due to no feedback.

**Closed by enen92** 2024-02-25 12:50 UTC
Labels: v18 Leia, Component: Network, Issue Cleanup: Obsolete
