### ISSUE TITLE
Unable to Open TV Shows from TV Shows Menu

### ISSUE THREAD

**Issue by brogahn** [xbmc/xbmc#15230] opened 2019-01-11 00:48 UTC
I installed Kodi on both my Windows 10 laptop and my Xbox and synced the  same TV Shows data sources. Tonight, when I got home from work. I am able to watch TV shows from the TV Shows menu on the laptop, but not  on the Xbox. I have experienced this before, removed the libraries and re added them. I figured I should determine if this is an issue with UWP in general or on the Xbox. 

This is similar behaviour to  #15210: and #15217: 

## Expected Behaviour
Highlighting TV shows on the menu, and then moving the the right panel and selecting any of the available options should be present with a list of shows to watch.

Selecting TV Shows on the menu and pressing enter to go to the sub-menu, using any of the available links should also present a list of shows to watch. Selecting any options on the right hand panel should open a sub menu with a list of shows

## Actual Behaviour
Selecting TV shows on the menu, and then going to in progress shows and selecting one, the screen drops me in to the "videos" folder. If I select Files from there, I am able to open the videos.
Clicking on TV Shows in the menu, selecting Titles and then a TV show, leaves me on the TV Shows/Titles form. The only options on the TV Shows form that work are Years and Titles. I am able to get to the shows that are listed in each year, but I am not able to actually open the file from that point. I have uploaded the log from following these steps to paste.kodi.tv/opoxohahaw

### To Reproduce
Steps to reproduce the behaviour:

Selecting TV shows on the menu, and then going to in progress shows, the screen drops me in to the "videos" folder. If I select Files from there, I am able to open the videos.
Clicking on TV Shows in the menu, selecting Titles and then a tv show, leaves me on the TV Shows/Titles form. The only options on the TV Shows form that work are Years and Titles. I am able to get to the shows that are listed in each year, but I am not able to actually open the file from that point. I have uploaded the log from following these steps to paste.kodi.tv/opoxohahaw

### Debuglog
I have two logs from when I closed and reopened the app after I was unable to watch the TV shows. http://paste.kodi.tv/ejogosiger and then I ran a clean on the database to see if that would help. Same Issue. https://paste.kodi.tv/umimadibay

I have attached the debug log from both the Xbox
[1st crash.zip](https://github.com/xbmc/xbmc/files/2747579/1st.crash.zip)

 and the Windows 10 installation.
[Windows10-.zip](https://github.com/xbmc/xbmc/files/2747589/Windows10-.zip)
  Both are pointing to the NFS share on my NAS. and SMB share on my laptop

## Additional context or screenshots (if appropriate)
To confirm that there isn't an issue with the database, I copied it from my Xbox and opened it using DB Browse for SQL Lite. It opened fine and I am able to run the queries that are in the log files as causing issues. 

SELECT studio.studio_id, studio.name FROM studio JOIN studio_link ON studio.studio_id = studio_link.studio_id JOIN tvshow_view ON studio_link.media_id = tvshow_view.idShow AND studio_link.media_type='tvshow' GROUP BY studio.studio_id

80 rows returned in 6549ms from: SELECT studio.studio_id, studio.name FROM studio JOIN studio_link ON studio.studio_id = studio_link.studio_id JOIN tvshow_view ON studio_link.media_id = tvshow_view.idShow AND studio_link.media_type='tvshow' GROUP BY studio.studio_id

I was able to copy the database folder off  of the XBOX and have attached that.
[Uploading Database.zip…]()

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows - No Issues that I noticed
 - [X] Windows UWP on Xbox 1- Experiencing the problem

 - Operating system version/name:
 - Kodi version: 
18 RC-5  Jan 3rd build - xbox
18 RC-5 Jan 6th build - windows

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by pkerling** [comment] 2019-01-11 08:41
Can you reproduce with the UWP build on desktop Windows? That would make it incredibly easier to debug...

And please link related forum threads in the future :-)

**Comment by pkerling** [comment] 2019-01-11 08:44
For reference:

#15210 may be related or not, impossible to say due to the missing info
#15217 is completely unrelated, it was specific to MySQL and caused by a misbehaving server

**Comment by pkerling** [comment] 2019-01-11 10:33
> Can you reproduce with the UWP build on desktop Windows? That would make it incredibly easier to debug...

After talking to @afedchin it seems that your log already is UWP/Desktop, so disregard

**Comment by pkerling** [comment] 2019-01-12 10:12
We need the store account email of someone encountering this problem and willing to test other builds - @brogahn ?

**Comment by afedchin** [comment] 2019-01-14 14:01
from your logs I see that you use different versions on xbox and desktop. 

desktop: 20190105-2c44a6a4c1
xbox: 20190103-c5c8532632

the are using different MyVideos db versions.

**Comment by afedchin** [comment] 2019-01-14 14:02
you have to backup your `userdata\Database` folder before replacing it with from xbox.

**Comment by brogahn** [comment] 2019-01-18 00:11
> We need the store account email of someone encountering this problem and willing to test other builds - @brogahn ?

I have no problems doing this.  I was notified in kodi that there was an update on the xbox, but the store does not provide the option to update it.

**Comment by brogahn** [comment] 2019-01-19 00:52
This was the version that was experiencing the issue

23:57:20.737 T:2652  NOTICE: -----------------------------------------------------------------------
23:57:20.737 T:2652  NOTICE: Starting Kodi (18.0-RC5 Git:20190103-c5c8532632). Platform: Windows NT x86 64-bit
23:57:20.737 T:2652  NOTICE: Using Release Kodi x64 build
23:57:20.737 T:2652  NOTICE: Kodi compiled 2019-01-03 by MSVC 191627023 for Windows NT x86 64-bit version 10.0 (0x0A000004)
23:57:20.738 T:2652  NOTICE: Running on Microsoft Xbox One with WINDOWS 10.0.17763, kernel: WINDOWS x86 64-bit version 10.0.17763
23:57:20.738 T:2652  NOTICE: FFmpeg version/source: 4.0.3-Kodi
23:57:20.738 T:2652  NOTICE: Host CPU: Unknown, 8 cores available
23:57:20.741 T:2652  NOTICE: Desktop Resolution: 1920x1080
23:57:20.741 T:2652  NOTICE: Running with restricted rights
23:57:20.741 T:2652  NOTICE: Aero is disabled
23:57:20.741 T:2652  NOTICE: special://xbmc/ is mapped to: S:\Program Files\WindowsApps\XBMCFoundation.Kodi_17.9.140.70_x64__4n2hpmxwrvr6p
23:57:20.741 T:2652  NOTICE: special://xbmcbin/ is mapped to: S:\Program Files\WindowsApps\XBMCFoundation.Kodi_17.9.140.70_x64__4n2hpmxwrvr6p
23:57:20.741 T:2652  NOTICE: special://xbmcbinaddons/ is mapped to: S:\Program Files\WindowsApps\XBMCFoundation.Kodi_17.9.140.70_x64__4n2hpmxwrvr6p/addons
23:57:20.741 T:2652  NOTICE: special://masterprofile/ is mapped to: U:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\userdata
23:57:20.741 T:2652  NOTICE: special://home/ is mapped to: U:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState
23:57:20.741 T:2652  NOTICE: special://temp/ is mapped to: U:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\cache
23:57:20.741 T:2652  NOTICE: special://logpath/ is mapped to: U:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState
23:57:20.742 T:2652  NOTICE: The executable running is: S:\Program Files\WindowsApps\XBMCFoundation.Kodi_17.9.140.70_x64__4n2hpmxwrvr6p\kodi.exe
23:57:20.745 T:2652  NOTICE: Local hostname: XboxOne
23:57:20.745 T:2652  NOTICE: Log File is located: U:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\kodi.log

Kodi on xbox has been upgraded to the version below.

﻿﻿19:37:19.472 T:5628  NOTICE: -----------------------------------------------------------------------
19:37:19.472 T:5628  NOTICE: Starting Kodi (18.0-RC5 Git:20190114-384acdd529). Platform: Windows NT x86 64-bit
19:37:19.472 T:5628  NOTICE: Using Release Kodi x64 build
19:37:19.472 T:5628  NOTICE: Kodi compiled 2019-01-14 by MSVC 191627023 for Windows NT x86 64-bit version 10.0 (0x0A000004)
19:37:19.473 T:5628  NOTICE: Running on Microsoft Xbox One with WINDOWS 10.0.17763, kernel: WINDOWS x86 64-bit version 10.0.17763
19:37:19.473 T:5628  NOTICE: FFmpeg version/source: 4.0.3-Kodi
19:37:19.473 T:5628  NOTICE: Host CPU: Unknown, 8 cores available
19:37:19.476 T:5628  NOTICE: Desktop Resolution: 1920x1080
19:37:19.477 T:5628  NOTICE: Running with restricted rights
19:37:19.477 T:5628  NOTICE: Aero is disabled
19:37:19.477 T:5628  NOTICE: special://xbmc/ is mapped to: S:\Program Files\WindowsApps\XBMCFoundation.Kodi_17.9.142.70_x64__4n2hpmxwrvr6p
19:37:19.477 T:5628  NOTICE: special://xbmcbin/ is mapped to: S:\Program Files\WindowsApps\XBMCFoundation.Kodi_17.9.142.70_x64__4n2hpmxwrvr6p
19:37:19.477 T:5628  NOTICE: special://xbmcbinaddons/ is mapped to: S:\Program Files\WindowsApps\XBMCFoundation.Kodi_17.9.142.70_x64__4n2hpmxwrvr6p/addons
19:37:19.477 T:5628  NOTICE: special://masterprofile/ is mapped to: U:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\userdata
19:37:19.477 T:5628  NOTICE: special://home/ is mapped to: U:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState
19:37:19.477 T:5628  NOTICE: special://temp/ is mapped to: U:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\cache
19:37:19.477 T:5628  NOTICE: special://logpath/ is mapped to: U:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState
19:37:19.477 T:5628  NOTICE: The executable running is: S:\Program Files\WindowsApps\XBMCFoundation.Kodi_17.9.142.70_x64__4n2hpmxwrvr6p\kodi.exe
19:37:19.481 T:5628  NOTICE: Local hostname: XboxOne
19:37:19.481 T:5628  NOTICE: Log File is located: U:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\kodi.log

I uploaded the log file here, debug logging is not enabled.
http://paste.kodi.tv/heziboheke

**Comment by pkerling** [comment] 2019-01-19 08:40
@MartijnKaijser What are those commits in the log referring to? I can't find them in this repository.

@brogahn Between those dates there is nothing in particular that should have this effect, but I'm out of ideas. If it works for you now, I'll just be happy about it :-)

Issue solved, closing

**Closed by pkerling** 2019-01-19 08:40 UTC
Labels: Database, WindowsStore, v18 Leia

**Comment by MartijnKaijser** [comment] 2019-01-19 08:58
@pkerling see the UWP ones https://github.com/MartijnKaijser/xbmc/branches
