### ISSUE TITLE
Video stop randomly on Kodi 19

### ISSUE THREAD

**Issue by Musicbox1965** [xbmc/xbmc#19554] opened 2021-04-10 11:32 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

problems with unexpected video stops being played, regardless of the format of the videos stored on my server.
Play stops are very random; they can happen after 2-3 minutes or stick around and crash only after 15-20 minutes.
I have tried settings in the advancesetting.xml file by increasing the cache memory but nothing has changed.
I also deported the Thumbnails folder, which was getting so big that it filled the small disk space capacity of my TV, there too, no improvement for playback cuts.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Uninstalled-Reinstalled and tried some cache settings in advancedsettings.xml

## Possible Fix

I think this problem comes from ffmpeg component or memory leak

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here: (zipped debug-log Kodi, downloadable for 30 days)

https://www.swisstransfer.com/d/042c8b04-f013-4e62-ad6f-f663de2e8983

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [[X]] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Running on Philips TPM191E with Android 9.0.0 API level 28, kernel: Linux ARM 32-bit version 4.9.125 Using Release Kodi x32
 - Kodi version: Kodi (19.0 (19.0.0) Git:20210218-f44fdfbf67). 

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*[](url)

**Comment by arnova** [comment] 2021-04-10 12:38
Probably same issue as in #19429

**Comment by rainman74** [comment] 2021-04-10 18:26
The problem is already fixed in the current nightly.

**Closed** 2022-08-23 16:41 UTC
Labels: Triage: Needed, Issue Cleanup: Obsolete
