### ISSUE TITLE
HTTPS (HTTP?) source username/password exposed in log

### ISSUE THREAD

**Issue by Goblinlordx** [xbmc/xbmc#15160] opened 2018-12-30 14:41 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

When scanning with debug log enabled, username and password is exposed in log when encountering excluded folder/files.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Username and password should be hidden when printed to log (`https://USERNAME:PASSWORD@mediasite.com`)

## Actual Behavior

Actual log output:
`ExcludeFileOrFolder: File 'https://realusername:realpassword@mediasite.com:443/Movies/SomeMovie/Subs/' excluded. (Matches exclude rule RegExp:'[\/](proof|subs)[\/]')`

## Possible Fix

filter username/password before source url passed to logging for exclude?  Filter as done in normal log messages.

### To Reproduce

1. Add HTTPS source which requires http basic auth
2. Have a folder which matches an excluded pattern (`/subs/` for example)
3. Enable debug logging
4. Start scan

### Debuglog

The debuglog can be found here:
Only relevant line:
```
ExcludeFileOrFolder: File 'https://realusername:realpassword@mediasite.com:443/Movies/SomeMovie/Subs/' excluded. (Matches exclude rule RegExp:'[\/](proof|subs)[\/]')
```

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC (official): 8.95.001 (Linux 4.19.8)
 - Kodi version: 18.0-RC3 Git:newclock5_18.0rc3-Leia

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by pkerling** [comment] 2018-12-30 16:47
Fixed in next release. Thanks for reporting!

**Comment by pkerling** [comment] 2019-01-10 09:37
@Goblinlordx can't find that for `ExcludeFileOrFolder` but found some other places where it is done wrong. Please check #15228.

**Comment by Goblinlordx** [comment] 2019-01-11 01:54
Cool~ thanks for the update~ honestly would dig more into these myself but C++ is one of the languages I am least proficient in T_T.

**Comment by pkerling** [comment] 2019-01-11 08:32
Can you confirm whether it fixes your problem?

**Closed** 2019-01-11 14:19 UTC
Labels: Logging, Solved, v18 Leia

**Comment by prog-amateur** [comment] 2019-03-02 23:33
> Can you confirm whether it fixes your problem?

Hello, I am on Linux Flatpak version (18.1), because Debianś Kodi version is still v17. The issue (in 18.1) is still there. To reproduce it : 
Add webdav (HTTPS) location, then edit the source and enter in the URL : the editable link contains ID & PASSWORD. Moreover, the webdav is not reachable in the flatpak version.

**Comment by pkerling** [comment] 2019-03-03 07:14
@prog-amateur This is not related at all. Please open a new issue.
