### ISSUE TITLE
SFTP show scraping broken

### ISSUE THREAD

**Issue by uotw** [xbmc/xbmc#15542] opened 2019-02-17 19:45 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

I have a library set up using an SFTP source for shows (named **shows**), using the recommended folder structure:

shows
->Cheers
->->Cheers.S01E01.mp4
->->Cheers.S01E02.mp4
->->Cheers.S01E03.mp4
->Good.Eats
->->Good.Eats.S01E01.mp4
->->Good.Eats.S01E02.mp4
->->Good.Eats.S01E03.mp4
->Seinfeld
->->Seinfeld.S01E01.mp4
->->Seinfeld.S01E02.mp4
->->Seinfeld.S01E03.mp4

Although the video files are being found recursively, the subfolders in this instance are completely ignored (no Cheers/Good Eats/Seinfeld episodes are found). Kodi scrapes this source to the title "**shows**," placing the files under _The Armando Iannucci **Shows**_.  Worked properly using Kodi 17.6.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

TV Show episodes should be scraped as one show per folder, using the folder name to look up info and episode descriptions from the selected information provider.

## Actual Behavior
TV Show are imported into the library under a single show name, searched from the source parent folder name. 

## Possible Fix
Change to smb protocol instead, or revert to Kodi 17.6.

### To Reproduce

1. Add video source using an sftp source.
2. Set content of a subfolder to "TV Show" using any information provider.
3. Scan for new content.

### Debuglog
The debuglog can be found here:
https://pastebin.com/n9Mn2u4n

### Screenshots
Here are some links or screenshots to help explain the problem:
![screen shot 2019-02-17 at 2 32 23 pm](https://user-images.githubusercontent.com/14109479/52918132-b64bab00-32c1-11e9-99a5-81b4561a24ed.jpg)
![screen shot 2019-02-17 at 2 32 36 pm](https://user-images.githubusercontent.com/14109479/52918133-b64bab00-32c1-11e9-8ad8-dda5a21bbee7.jpg)
![screen shot 2019-02-17 at 2 32 44 pm](https://user-images.githubusercontent.com/14109479/52918134-b64bab00-32c1-11e9-9075-ce20a0be4da5.jpg)
![screen shot 2019-02-17 at 2 32 57 pm](https://user-images.githubusercontent.com/14109479/52918135-b64bab00-32c1-11e9-907d-aa05e3421567.jpg)
![screen shot 2019-02-17 at 2 33 29 pm](https://user-images.githubusercontent.com/14109479/52918136-b64bab00-32c1-11e9-87b5-9069f83b4100.jpg)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Files are hosted on a debian linux server. This issue persists on Android TV as well as the latest basic Android build on my dev environment.  There's a [similar issue](https://github.com/xbmc/xbmc/issues/15481#issuecomment-464417967) using an HTTP source that has been fixed in the latest nightly, but as of kodi-20190217 the problem persists for SFTP. 

### Your Environment
Used Operating system:

* [X ]  Android
* [ ]  iOS
* [ ]  Linux
* [ ]  OSX
* [ ]  Raspberry-Pi
* [ ] Windows
* [ ]  Windows UWP
* Operating system version/name: Android TV
* Kodi version: 18

**Comment by KarellenX** [comment] 2019-02-18 03:12
Original fault finding thread in forum...
https://forum.kodi.tv/showthread.php?tid=340375

**Comment by DaVukovic** [comment] 2019-02-18 05:29
The fix #15492 was merged 3 days ago 

It's simply currently not included in the Kodi version you are using. 

> 11:52:05.611 T:13717  NOTICE: Starting Kodi (18.0 Git:20190128-d81c34c). Platform: Android ARM 32-bit

I would suggest to download Kodi 18.1 and see if it's fixed in that version.

https://kodi.tv/download

**Comment by arnova** [comment] 2019-02-18 07:52
Seems like a duplicate of #15404

**Comment by uotw** [comment] 2019-02-18 11:10
@DavuKovic I've downloaded and installed the latest version and I'm seeing the same bug.  That's why I mentioned '...as of kodi-20190217.' 

@arnova this behavior may be related to the same issue, but differs in that my SFTP seems to be pulling some shows, whereas the other issue comes up nil. I submit that his may be specifically because I've named my source folder something that matched the information provider.

**Comment by arucard21** [comment] 2019-02-19 07:03
I noticed in the debug log that you also had an SFTP source for the path `/home/ben/shows/` instead `~/shows` as shown in the screenshots. Is it possible that that source is configured as containing a single tv show? Also, can you verify that "The Armando Iannucci Shows" comes from the path the tilde (`~/shows`) and not the full path (`/home/ben/shows`)? You may want to produce another debug log with the SFTP source using the full path, if that behaves any differently.

I don't really know what the problem is but maybe this bit of extra troubleshooting can help.

**Comment by uotw** [comment] 2019-02-19 14:20
Good idea.  Here's some logs with various iterations and results:

[SFTP Source ~/shows](https://pastebin.com/rSMM4ASG)
This results in scraping all files into The Armando Iannucci **Shows**

[SFTP Source /home/ben/shows](https://pastebin.com/dWn69dgt)
This results in nothing being scraped

[SFTP Source ~/files](https://pastebin.com/C4fwRTTi)
This results in scraping all files into The X-**Files**

**Comment by uotw** [comment] 2019-03-12 13:15
This remains broken.  I've switch all my sources over to NFS, which works as expected.

**Comment by arnova** [comment] 2019-03-12 14:02
@notspiff : Ideas?

**Comment by arnova** [comment] 2019-08-05 07:20
https://github.com/xbmc/vfs.sftp/pull/33 takes care of this.

**Comment by HPMSGEN8** [comment] 2019-08-06 12:41
Hi All,

I am having the same issues with CoreElec & LibreElec on the latest versions.

How do i update this to fix the issues please.

Thanks

**Comment by enen92** [comment] 2019-08-06 13:03
@HPMSGEN8 fix is not yet merged, you'll have to wait.

**Comment by HPMSGEN8** [comment] 2019-08-06 13:13
Thanks @enen92

**Comment by arnova** [comment] 2019-08-31 10:52
Fixed with https://github.com/xbmc/xbmc/pull/16438

**Closed by arnova** 2019-08-31 10:52 UTC
Labels: Component: Network, v18 Leia
