### ISSUE TITLE
OutputPicture - timeout waiting for buffer

### ISSUE THREAD

**Issue by Kupo91** [xbmc/xbmc#25042] opened 2024-04-21 19:52 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:
At one of my videos the screen turns black, always at the same spot. The sound keeps going. I have to turn off the TV and turn on again to get a picture. Log file says "OutputPicture - timeout waiting for buffer". 
It's the first time that this happens to me. However I don't have this problem, if I use the VLC player instead.

## Expected Behavior
Video plays without problems.

## Actual Behavior
What I described above

### To Reproduce

I attach the log file

### Debuglog

The debuglog can be found here: 
[kodi.log](https://github.com/xbmc/xbmc/files/15053325/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu 22.04.4 LTS
 - Kodi version: 20.2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by neo1973** [comment] 2024-04-21 20:26
Kodi 20 is end of live and won't get updates anymore. Try with Kodi 21. Also the attached log isn't a debug log, see https://kodi.wiki/view/Log_file on how to obtain one.

**Comment by neo1973** [comment] 2024-04-28 20:37
No update from reporter, closing.

**Closed by neo1973** 2024-04-28 20:37 UTC
Labels: Triage: Needed

**Comment by AerYareli** [comment] 2024-05-31 17:12
Heya! I'm also having this issue with no fixes from google search after about an hour. Here is my debug log, at least I think its a debug log: https://paste.kodi.tv/hikayeqevi.kodi

**Comment by neo1973** [comment] 2024-05-31 21:05
@AerYareli: Due to the usage of [banned piracy add-ons](https://kodi.wiki/view/Official:Forum_rules/Banned_add-ons) we won't look into your case. Pleas reproduce with a clean Kodi installation to get support.

**Comment by angelmixu** [comment] 2025-01-05 23:11
Hi! it just happens the same to me, I'm on a NixOs linux, and after watching some minutes a film, image is frozen but audio continues. I can restart kodi, change vaapi acceleration, buffers, etc. and keepps happppening until I reboot the computer.
when the issue happens I can use vlc to play the movie with no issue.

I have attached the log, in this case I just oppened kodi and resumed the movie, image was frozen, I skipped forward, and hit stop. Kodi hung up in this moment.

Thanks! :)

https://paste.kodi.tv/orogixaduj.kodi

**Comment by neo1973** [comment] 2025-01-05 23:26
My guess is that the problem is [nvidia-vaapi-driver](https://github.com/elFarto/nvidia-vaapi-driver). As the GitHub page says, it may misbehaves with everything but Firefox. Launch Kodi with the environment variable `LIBVA_DRIVER_NAME=dummy` to suppress usage of VAAPI. Kodi may uses VDPAU instead but I can't test this because I don't have compatible hardware.

**Comment by angelmixu** [comment] 2025-01-06 00:01
oh wow!
such a fast response!
lots of thanks !

tested with that env variable and I can confirm it"s working fine! :O
I had problems in archlinux with that same library some time ago :/

I can see vdpau being mentioned in the new log, so I guess it's being used.
Sooo... is it better to use vdpau than vaappi?

**Comment by neo1973** [comment] 2025-01-06 00:18
With the proprietary NVIDIA driver VDPAU is the only hardware acceleration method Kodi supports. NVDEC isn't supported by Kodi and and the the VAAPI adapter driver you were using is problematic.

**Comment by angelmixu** [comment] 2025-01-06 00:47
ah I see! got it, thanks again! :)
