### ISSUE TITLE
Kodi 19.2 (from Google Play) doesn't run on Android 11 (Galaxy Fold 3) -- black screen

### ISSUE THREAD

**Issue by Technologov** [xbmc/xbmc#20399] opened 2021-10-26 04:20 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi 19.2 (from Google Play) doesn't run on Android 11 (Samsung Galaxy Fold 3, foldable Android)

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

## Actual Behavior

It start as "black screen" and stays that way.

### To Reproduce

Device: Samsung Galaxy Fold 3 with Android 11
1. install Kodi 19.2 from Google Play
2. run it
3.

### Debuglog

The debuglog can be found here:

### Screenshots
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 11
 - Kodi version:
19.2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Formedras** [comment] 2021-11-09 00:24
The Galaxy Z Fold 3 uses a 120Hz display and Kodi as yet doesn't work with refresh rates higher than 60Hz.

I recommending closing this issue as a duplicate of #15872.

**Closed** 2021-11-09 01:58 UTC
Labels: Resolution: Duplicate
