### ISSUE TITLE
Video rendering regression from 17.6 to 18.5 and AMD radeon HD 8570, linux platform

### ISSUE THREAD

**Issue by Enigma7-new** [xbmc/xbmc#17314] opened 2020-02-02 22:26 UTC
#16851  Bug report
### Describe the bug

I have upgraded from Kodi 17.6 to 18.5 in less than 2 hours without changing Radeon drivers.
With kodi 17.6, video rendering was perfect.

## Expected Behavior
The defaut vaapi-bob gives picture compressed on half top screen, vaapi adaptive works but crappy image when movings and normal bob crashes kodi!

## Possible Fix
When debuging same content with Vlc, Vdpau is takenand picture is ok . Forcing vaapi in VLC gives same result as kodi 18.5 . Seems kodi 17.6 was using vdpau ?
Fix would be same rendering as Kodi 17.6

### files attached - debug log
kodi_vaapi_bob_half_topscreen.log  : playing half screen compressed , no crash (vaapi-bob)
kodi_crash.log : playing, then change interlacing via gui to bob (no vaapi) and finally crash

[kodi_vaapi_bob_half_topscreen.log](https://github.com/xbmc/xbmc/files/4145618/kodi_vaapi_bob_half_topscreen.log)
[kodi_crash.log](https://github.com/xbmc/xbmc/files/4145625/kodi_crash.log)

### To Reproduce
1. play a H.264 video 1920 interlaced on AMD GPU from broadcast
2. look at the picture for vaapi- bob
3. change deinterlace method to bob --> gives crash

### Your Environment

Used Operating system: linux mint 19.3
Kodi version: 18.5 leia  (from ppa)

**Comment by fritsch** [comment] 2020-02-03 05:06
The real fix is to fix your broken video drivers, that announce vaapi and especially deinterlacing, but don't work reliable.
 
To force vdpau on 18.5 use:
https://kodi.wiki/view/Supported_hardware

here you can expose the render interface via environment variable.

**Comment by lrusak** [comment] 2020-02-03 05:53
With the same concern as @fritsch I'm worried if you just update from Kodi 17 which is over 2 years old that your video drivers (and the rest of your system) hasn't been updated at all. I'd recommend updating to the latest available version of the kernel, mesa and libva to make sure that something else isn't broken then please report back.

**Comment by yol** [comment] 2020-02-03 12:55
@fritsch I thought you could reproduce?

@lrusak it's mesa 20 master from 2020-01-27 ;-) I don't think it will get much more recent. But yeah more recent kernel would be nice.

**Comment by Enigma7-new** [comment] 2020-02-03 17:32
@ Irusack 
my drivers comes from : https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers
and are up to date
My Mint is 19.3 , latest and up to date

i have set variable KODI_GL_INTERFACE  to GLX in variable file, reboot computer , check printenv variable is set.
Then lunch kodi 18.5, i have VDAPU now great.
But Vdpau bob gives same result, half screen picture . 

I have now new options, including normal bob that not chashed . fine
I diden't find preformance differences between them, is it normal ? not sure...

VLC have correct output with VDPAU and bob deinterlace, same computer, same driver etc.

I will now look more in details Kodi 17.6 on my hardware, i need to build a usb live stick and take kodi from built in repo (not from ppa)

**Comment by Enigma7-new** [comment] 2020-02-03 18:06
here are the logs
From live Mint 19.3 usb stick
[kodi17.6 .log](https://github.com/xbmc/xbmc/files/4149324/kodi17.6.log)

From installed Mint 19.3 with VDPAU variable set ( same file playing, same computer) 
[kodi18.5.log](https://github.com/xbmc/xbmc/files/4149342/kodi18.5.log)

**Comment by fritsch** [comment] 2020-02-03 18:23
@yol found a user on IRC that could reproduce with non-bleeding edge mesa, which does not include the code I outlined on the forum. 

To be more exact: He could reproduce the wrong bob size.

**Comment by Enigma7-new** [comment] 2020-02-04 17:53
I have made more tests today on 18.5.
I have found my maximal performance for interlaced video playing under kodi.
It's VDPAU - temp , (vdpau bob has still half screen default)
Here a capture
![Kodi18_5_Radeon_Vdpau](https://user-images.githubusercontent.com/60585079/73771532-d8626580-477e-11ea-8057-c29ac94f4753.png)
Compared to VLC's VDPAU + bob, performance are less ( VLC use ffmpeg also for video decompression) , here a capture
![VLC](https://user-images.githubusercontent.com/60585079/73771698-1cee0100-477f-11ea-91c4-b80f8fc4b9da.png)
As you can see, VLC use only 8 % of cpu and Kodi above 20 % for same video clip
So I am not sure kodi use really Vdpau at 100 %.
Perhap a combined problem whit bob problem ?

**Comment by lrusak** [comment] 2020-02-04 18:01
If you want to make that comparison then you need to look at the CPU usage from just the VideoPlayer thread in Kodi not the entire application. Kodi being a multithreaded beast spawns 30 or more threads to run all the tasks that it manages. To compare Kodi to VLC isn't really apples to apples.

**Comment by Enigma7-new** [comment] 2020-02-04 18:20
Ok for Cpu, you're prehaps right ;)

And finally a capture with the main problem with VDPAU - bob :
![Vdpau_bob_radeon](https://user-images.githubusercontent.com/60585079/73773901-4f016200-4783-11ea-9a27-968029c3d516.png)

**Comment by Enigma7-new** [comment] 2020-02-09 14:33
Some news: 
I've just tested Kodi 19 alpha 2020 02 09 on mint 19.3 live, without environment variable  .. and it works !
So the bug is concentrated on kodi 18.5 (haven't test 18.1 and others 18.x versions)
Kodi version : 
![Kodi19version](https://user-images.githubusercontent.com/60585079/74104010-f817d600-4b50-11ea-9598-d3a1381c911c.png)
VAAPI - bob in action : 
![Kodi19_vaapi_bob](https://user-images.githubusercontent.com/60585079/74104041-2dbcbf00-4b51-11ea-8b51-0c70f7a6391d.png)
cpu ressources are growing dow from 22-25 % to 18 %

**Comment by fritsch** [comment] 2020-02-09 14:40
As I told you in the very first reply to your bugreport. Old mesa is no affected. The bug hit mesa in new versions.

**Comment by Enigma7-new** [comment] 2020-02-09 15:17
Shame on me …
You're right.
On usb live all versions of kodi are working, 17.6 18.5 and 19 alpha.
The main difference in mesa driver , 19 on usb live and 20 on hard disk 18.5 installed Kodi.
First step for me is to revert to 19 for mesa ans installed Mint.

**Comment by fritsch** [comment] 2020-02-09 15:19
I have told that to you after your very first forum post - but you did not believe me and ignored it. I even linked you the bugreport and you still did not believe me :-)

So, finally the message made it.

**Comment by yol** [comment] 2020-02-09 20:13
Taking over from the forums...

> Edit: and looks totlaly wrong to me - why deinterlace NV12 in vlVaDeriveImage() ?

@asavah The memory layout of interlaced frames on AMD is not supported by VAImage. vaDeriveImage on AMD just cannot export the buffer directly. That is why it failed so far on AMD, which we have been relying on to detect that we cannot use ffmpeg deinterlacing. Now that vaDeriveImage succeeds and magically deinterlaces the frame, we think we can also give the frame data to ffmpeg for deinterlacing (which we can't because, again, it is now - magically - deinterlaced). So I think you are correct that this breaks quite some things.

I'm not sure though why vaapi-bob does not work. It might be that the vaDeriveImage call we do when checking for supported already fucks up the surfaces enough (I think once the surface is progressive there's no going back - the AMD driver is doing quite some magic to work around the different buffer layouts). If someone has some time on their hands, you can try commenting out the following lines: 

https://github.com/xbmc/xbmc/blob/master/xbmc/cores/VideoPlayer/DVDCodecs/Video/VAAPI.cpp#L1844-L1846

**Comment by Enigma7-new** [comment] 2020-02-09 20:49
Test result with usb live stick and mint 19.3
Kernel 5 and Mesa 19.0.8 -> VAAPI - bob is ok

Test now result with usb live stick and mint 19.2 
Kernel is 4.15.0-54
With original mesa (19.0.2) VAAPI - bob  is fine.
I've upgraded (with packet manager) only mesa to 19.2.8  and bingo VAAPI - bob = half screen picture
So the frontier between working and non working mesa driver is between 19.0.28 and 19.2.8.
So i have to revert mesa to before 19.2.8 if i can.

Mint is based on ubuntu's drivers
https://www.ubuntuupdates.org/package/co...an-drivers
Driver is growing from 19.0.8 to 19.2.1 to 19.2.8

**Comment by FernetMenta** [comment] 2020-02-09 20:56
@yol keep in mind that vdpau has the same issue. I doubt that this is caused by the change in deriveImage

**Comment by yol** [comment] 2020-02-09 21:33
@FernetMenta Yes, I tested removing the `vaDeriveImage` calls and same problem. It's still true that `vaDeriveImage` not failing on AMD will cause problems, but there seem to be other issues even before that.

**Comment by yol** [comment] 2020-02-13 16:28
Confirmed to be a mesa bug by AMD here: https://gitlab.freedesktop.org/mesa/mesa/issues/2454#note_409314 - so closing. It will work in Kodi again once the mesa fix is in.

Thanks for reporting @Enigma7-new

**Closed by yol** 2020-02-13 16:28 UTC
