### ISSUE TITLE
Kodi version 19 or later no longer opens images via the file manager

### ISSUE THREAD

**Issue by NathanielDemerest** [xbmc/xbmc#20329] opened 2021-10-17 06:03 UTC
Kodi from version 19 can no longer display images via the file manager for some unknown reason.

If you want to open an image file such as .jpg or .png, a window opens asking you to select an emulator for the image file to be opened.

If you select the only emulator that exists there, Kodi crashes after its installation and when you restart it later and load an image file via the file manager.

Recently everything worked.  The phenomenon also occurs after a fresh installation of Kodi from version 19.0 to 20.0 (Alpha).

**Comment by KarellenX** [comment] 2021-10-17 07:04
That Rick Dangerous seems to be coming up a bit recently.
 
Maybe @garbear might know why that keeps popping up.

**Comment by KarellenX** [comment] 2021-10-17 20:37
also reported on forum here... https://forum.kodi.tv/showthread.php?tid=364902

**Comment by Ronny-nerd** [comment] 2021-10-20 11:27
Hello Kodi Team...with a freshly installed Kodi Matrix or Nexus version and used skin = Estuary ...even then this bug is present with my mentioned operating systems.
Or maybe this is different with you guys?

**Comment by garbear** [comment] 2021-10-31 04:43
OK, I merged the patches and pushed new versions to the mirrors. Try refreshing you add-on repos in a few hours and see if the problem is fixed.

**Comment by garbear** [comment] 2021-10-31 06:25
Also, I figured the underlying segfaults should be fixed, so I also submitted PRs that will prevent crashing even if attempting to open a core with a PNG/JPG:

* 3dengine - https://github.com/kodi-game/game.libretro/pull/80
* xrick - https://github.com/libretro/xrick-libretro/pull/14

**Comment by NathanielDemerest** [comment] 2021-10-31 16:55
Ok the pictures are displayed again.  Thanks for the quick fix garbear.

**Comment by Ronny-nerd** [comment] 2021-10-31 19:30
Thanks for your help... garbear.

Test: Nvidia Shield TV - Android 9 
Kodi 19 Matrix
.jpg and .png files = OK

Kodi 20 Nexus Alpha
.jpg files = OK
.png files = comes Emulator = PICO8 (Retro8) = Not OK

Test: PC - Windows 10 Pro 
Kodi 19 Matrix
.jpg files = comes emulator = Rick Dangerous (XRick) = Not OK
.png files = comes emulator = Rick Dangerous (XRick) = Not OK

Kodi 20 Nexus Alpha
.jpg files = comes emulator = Rick Dangerous (XRick) = Not OK
.png files = coming emulator = Rick Dangerous (XRick) and PICO8 (Retro8) = Not OK

**Comment by garbear** [comment] 2021-11-02 03:00
Our Jenkins build server [doesn't like](https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-game%2Fgame.libretro.xrick/detail/master/40/pipeline/270) the line endings of the patches:

```
[ 48%] Performing patch step for 'xrick'
patching file libretro/core/libretro-core.c
Hunk #1 FAILED at 155 (different line endings).
1 out of 1 hunk FAILED -- saving rejects to file libretro/core/libretro-core.c.rej
```

I'll look into it.

**Comment by Ronny-nerd** [comment] 2021-11-05 13:00
Are there already new findings in the direction of Kodi Matrix and Nexus ... PC - Windows 10 Pro ... garbear ... to then turn off the emulators because of this problem?

**Comment by garbear** [comment] 2021-11-05 20:36
I'll try to fix it this weekend.

**Comment by garbear** [comment] 2021-11-08 17:18
I merged https://github.com/kodi-game/game.libretro.xrick/pull/5 and it seems to have fixed the problem. After an update, xrick should no longer show up in both jpg/png. @AlwinEsch Can you update the patches for 3dengine and retro3?

**Comment by Ronny-nerd** [comment] 2021-11-09 19:24
Test from today after installing your patch ... garbear.

[https://jenkins.kodi.tv/job/kodi-game/job/game.libretro.xrick/job/master/44/](url)

Rick Dangerous (XRick) = OK 

Test: Nvidia Shield TV - Android 9

Kodi 19 Matrix
.jpg and .png files = OK

Kodi 20 Nexus Alpha
.jpg files = OK
.png files = comes Emulator = PICO8 (Retro8) = Not OK


Test: PC - Windows 10 Pro

Kodi 19 Matrix
.jpg files and .png files = OK

Kodi 20 Nexus Alpha
.jpg files = OK
.png files = comes Emulator = PICO8 (Retro8) = Not OK

**Comment by Ronny-nerd** [comment] 2021-11-14 10:59
Hello @garbear ... are there already new findings for this problem in the direction of emulator = PICO8 (Retro8)?

**Comment by garbear** [comment] 2021-11-14 21:01
I haven't heard from @AlwinEsch how he made the windows patch. I got a windows box so I'll sit down and figure it out when I get a chance

**Comment by AlwinEsch** [comment] 2021-11-15 17:06
For where you mean? Not sure, you mean related to https://github.com/kodi-game/game.libretro.xrick/pull/5?

**Comment by garbear** [comment] 2021-11-15 17:50
Right, doing the same thing for 3dengine and retro8. I assume to make the patch you fired up a windows box, which checked out the LF files as CRLF, then created a new patch?

**Comment by AlwinEsch** [comment] 2021-11-15 19:54
No, for there it not needed, the CRLF only becomes needed to change if on patched code them is used. If them not on 3dengine and retro8 then also not needed.

**Comment by garbear** [comment] 2021-11-16 00:30
Merged https://github.com/kodi-game/game.libretro.retro8/pull/3. @Ronny-nerd Can you retest? All platforms should be fixed now

**Comment by Ronny-nerd** [comment] 2021-11-16 11:06
Would like to thank you very much ... @garbear and @AlwinEsch for your good work on this problem.

Test Today

Kodi 19 Matrix and Kodi 20 Nexus 

There are no more problems to output .jpg files and .png files over my operating system and the Kodi file manager ... even if they are additionally packed in a .rar file.

Also a thank you to the Kodi team.

**Closed** 2021-11-16 15:28 UTC
Labels: v19 Matrix, Triage: Confirmed, v20 Nexus

**Comment by NathanielDemerest** [comment] 2021-11-16 15:32
I agree with him.

The issue has been resolved and that is why I am closing here.

**Comment by wastedfish** [comment] 2022-11-29 00:11
> Workaround:
> 
> Please disconnect from the Internet and delete the "Addons33.db" file in the userdata / Database directory of the Kodi installation. Then start Kodi offline and the picture display works again. Then re-establish the internet connection.

beautiful catch!
