### ISSUE TITLE
Incorrect free space for sdcard1 in Leia

### ISSUE THREAD

**Issue by mrpegleg** [xbmc/xbmc#15409] opened 2019-02-02 22:18 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

The file manager in Kodi 18 Leia is reporting an inaccurate amount of free space on sdcard1. Such as, 345mb free when I have 28.3gb free on the card. Similar behaviour on both my Fire TV 2 and Sony Z2 phone.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I expected the free space shown in file manager to correspond with the true free space. It worked fine in Kodi 17. 

## Actual Behavior

The system information page in Kodi 18 does show the true amount of available space on the sdcard1 device. But the file manager does not. The debug log provided is related to an exfat formatted microsd. The same behaviour observed on my Amazon Fire TV was with a FAT32 formatted microsd. Additional note is that I am able to both read and write the whole capacity of the cards, but the free space on file manager is showing significantly less free space than it has ever since updating to Leia.

### To Reproduce

1. Add sdcard1 path to file manager
2. View the free space shown beside it
3. Compare to the actual free space known to be on the sd card 

### Debuglog

The debuglog can be found here: 
https://paste.kodi.tv/suhitohuzo.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

https://ibb.co/q0GVL3n
https://ibb.co/QbVRTDW
https://ibb.co/vj9tT7k

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ x] Android 
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: 5.1.1
 - Kodi version: 18.0 stable

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment] 2019-02-03 05:55
> I do not have a debuglog to post

That's true. But you should as we ask for it and it might be necessary in that case. If you do not provide a full debuglog, your issue will be closed in 3 days. 

It would also be helpful if you share some screenshots and also share more informations about how you format the sd card. 

Note: I'll mark this as invalid for the time you need to provide a full debuglog.

**Comment by mrpegleg** [comment] 2019-02-03 12:40
Thanks for the prompt response. This is the first time I have ever submitted a bug so apologies for the omissions. I trust that the information relating formatting and the debuglog which I now have added to my initial report will be sufficient.

**Comment by mrpegleg** [comment] 2019-02-03 14:46
I have also added screenshots now. Thanks

**Comment by DaVukovic** [comment] 2019-02-03 14:55
Seen at your log, that you are using an outdated Kodi version. Kodi 18 RC1 is pretty old and we recently released Kodi 18.0 as a stable version. So please update to the recent Kodi version first to see if that fixes something. 

If not, provide a new logfile, please. Also please do me a favour and try the default Skin (Estuary). I doubt it's a skin issue, but I want to be sure. 

Thanks in advance

**Comment by mrpegleg** [comment] 2019-02-03 15:32
I also updated screenshots for 18.0 stable / estuary skin. As you can see the free space is not visible in system information on estuary skin, but the used and total can be seen. I'm not sure why as my display is 1080p but this bit I can live with happily.

I also provided a screenshot of third party app SD Maid to corroborate the values for total and used space because of this.

Many thanks.

**Comment by DaVukovic** [comment] 2019-02-03 15:47
Thanks. I tried with a few USB sticks and I can't reproduce your problem. All info about the space in use, or the available space is correct for me. 

It might be Android or MicroSD specific. I don't have spare SD cards left currently. So I can't test that. 

Thanks for all the info.

**Comment by mrpegleg** [comment] 2019-02-03 16:02
Much appreciate your looking into this for me. If I am able to pinpoint the issue more accurately I will update the thread accordingly. 

My intentions are to try a USB drive via the OTG function of my phone, and also try a microsd on my pc on the Windows build. 

That way we can surely narrow the culprit down to microsd or to Android.

I am not at home at present and thus don't have access to any of the relevant equipment to do this.

**Closed** 2022-08-31 15:35 UTC
Labels: Platform: Android, v18 Leia, Issue Cleanup: Obsolete
