### ISSUE TITLE
Web Service - Failed to start  when u uses a laucher for launch kodi at boot

### ISSUE THREAD

**Issue by teamonce** [xbmc/xbmc#16418] opened 2019-07-30 19:18 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

The problem is the next, when we use any launcher to start kodi at boot, as for example launcher xbmc, we have the problem starting web service (http 8080 in my case), because kodi start too fast than the app cant recognise the networks up.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Web service at boot doesnt start, needing restart the app

## Actual Behavior

Web service at boot doesnt start, needing restart the app

## Possible Fix

Put a delay to start web service as libreelec/coreelec, for example 5-10sec

### To Reproduce

1. Get a tvbox with root or with the posibility to change the launcher
2. Install a launcher or use any app for autostart kodi at boot
3. Enable Web service with for example default port 8080
4. Reboot (that issue only can be do when you boot the tvbox, if you closes the app and start again, works well)

### Debuglog

The debuglog can be found here:

No shows nothing error

### Screenshots 
Here are some links or screenshots to help explain the problem:

No shows nothing error

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I cant use web server http 8080 needing restart app every time boot the app

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android any version
 - Kodi version: 18.3 Playstore

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by teamonce** [comment] 2019-07-30 19:34
I reedited the post thanks

**Comment by KarellenX** [comment] 2019-07-30 23:18
Please also provide the debug log which captures the startup and error.

**Comment by wsnipex** [comment] 2019-07-31 09:39
Go to Settings - System - Power saving and enable "Maximum wait time for network"
You have to set the settings level o at least advanced to see this setting.

If it still does not work, provide a full debug log

**Comment by teamonce** [comment] 2019-08-01 21:01
Added kodi log and video starting, if i close the app and start again works well, and no, the power saving enable dont do nothing

[kodi.log](https://github.com/xbmc/xbmc/files/3458608/kodi.log)

https://www.youtube.com/watch?v=oe1wBVU8D48

**Comment by teamonce** [comment] 2019-08-02 19:49
Any news? u need more info? 

Thanks

**Comment by teamonce** [comment] 2019-08-06 16:31
No comment? i dont understand why you dont say any ok, we are investigating it or any word

**Comment by KarellenX** [comment] 2019-08-06 19:51
@teamonce 

As you can see there are almost 400 open issues here. Some valid, most are not.

When a developer has time to look into your issue, then you they will respond, as has already happened once.. Please don't expect an immediate fix of an issue that is reported by a single user.

**Comment by teamonce** [comment] 2019-08-06 20:54
Ok

**Comment by gmantonz** [comment] 2019-08-07 03:11
I can confirm I am seeing this issue on a Windows machine and on Nvidia Shield TV. Did not have any issues prior to upgrading to 18.3. Krypton launched the same way and never had this issue. Unfortunately this issue causes the link between Kodi and Home Assistant to break as well as HA will no longer receive any pushes from Kodi until you restart, which messes up home automation scripts based on whether Kodi is idle/playing/off.

**Comment by DaVukovic** [comment] 2019-08-07 04:40
> No comment? i dont understand why you dont say any ok, we are investigating it or any word

We did...well not personally, but the bot was triggered and the bot says: 

>A full debug log is always mandatory. 

So...from your log above

2019-08-01 23:04:33.281 T:7294  NOTICE: Disabled debug logging due to GUI setting. Level 0.

probably it would be best to start to provide what we ask for, then we could at least remove the "Ignored rules" label

If that: `You can reproduce it, on any device, changing the launcher to the launcher XBCM from blunden` is the case and you can only reproduce it while using that launcher, have you thought about reporting it to the guy who develops this launcher?!

**Comment by DaVukovic** [comment] 2019-10-12 07:28
Ok, For the reason there's no further reaction from the reporter for the last 2 month and there's also no debug log (the provided logfile has debugging enabled) I'm going to close this one.

**Closed by DaVukovic** 2019-10-12 07:28 UTC
Labels: Ignored rules, Triage: Needed
