### ISSUE TITLE
Leia: PVR (Live TV) Next/Previous Channel (Buttons) are not working

### ISSUE THREAD

**Issue by godoll** [xbmc/xbmc#15715] opened 2019-03-10 17:54 UTC
Noticed it first on my FireTV 4k Stick, but issue seems to be present with Windows as well.
(Think issue is present since some time, but tested it with today's nightlies (18.2 RC1))

## Expected Behavior
Pressing Next / Previous should skip to next / previous TV channnel

## Actual Behavior
When on Tvheadend channel, playback freezes for short time, but playback resumes on same channel
When on Simple TV (m3u) channel, pressing Next / Previous has no effect at all.

## Possible Fix
unkown

### To Reproduce
Issue is present for me out of the box

### Debuglog
[kodi.log](https://github.com/xbmc/xbmc/files/2949841/kodi.log)

### Screenshots
Short video shjowing the issue (Kodi on Windows)
https://youtu.be/p4AdvxSFtQU

### Your Environment
Used Operating system:

 - [x] Android
 - [x] Windows
 - not tested on Pi / LE (but could do if needed)

 - Operating system version/name:
 - Kodi version: 18.2 RC1

**Comment by emveepee** [comment] 2019-03-11 03:13
For me (with pvr.nextpvr) prev and next work to navigate the time shift buffer.  Left once to beginning of show left twice to beginning of timeshift Next to once end of show next again to end of buffer.  Up and Down change channels.

**Comment by godoll** [comment] 2019-03-11 12:26
I ment n/p to skip to another (TV) channel (updated title).
Maybe it's an issue of the Xonfluence skin with Leia? I switched to the default skin for a test, but I even can't find those controls there ...

**Comment by emveepee** [comment] 2019-03-11 13:14
For me the Up/Down OSD in Xonfluence work like Prev/Next in Estuary like I described for navigating timeshift.  Remote or Keyboard Up/Down changes channels.   Is this a problem because you want to use the mouse?

**Comment by godoll** [comment] 2019-03-11 13:56
For me it's the same issue if I use a remote to push the the OSD p/n buttons.
The FireTV remote has no n/p buttons and I'm using an IR Logitech Harmony Remote to control the (Kodi on my) fTV4k stick in my living room. (It's a long time but  think I set the latter to an MCE profile.)
Anyhow, as you said; "pressing" the n/p channel OSD buttons seem to act like time-shift for me, but not switching channels.

**Comment by ksooo** [comment] 2019-03-11 14:42
This is unneeded behavior, not a bug. 

Please ask in the forum how to create custom key mappings. 

Closing this issue as this is no support channel.

**Closed** 2019-03-11 14:42 UTC
