### ISSUE TITLE
Kodi crashes on Android with 120Hz screen refresh rate

### ISSUE THREAD

**Issue by loztcf** [xbmc/xbmc#15872] opened 2019-04-07 08:13 UTC
### Describe the bug
Kodi freezes and then closes with 120Hz/90Hz refresh rate on Android

## Expected Behavior

Kodi starts as usual, as with 60Hz screen refresh rate enabled.

## Actual Behavior

Kodi starts, but after the loading screen it remains black for 0.5sec and then closes.

## Possible Fix

Force it being run at 60Hz or make it compatible with 120Hz screens on Android.

### To Reproduce

1. Set screen to 120Hz refresh rate
2. start Kodi
3. Kodi crashes

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/ajerewucik.kodi

Possible debug informations about the crash - as I can see - starts at line 356

### Your Environment
Used Operating system: Android 9.0/Android 8.1

Used Hardware: Razer Phone 2 w/ 120Hz screen enabled.

 - Operating system version/name:
 - Kodi version: Stable release, various nightlies - latest 06 Apr 2019

**Comment by bckspc** [comment] 2019-06-04 10:55
Same problem with OnePlus 7 Pro (90Hz)
Changing refresh rate to 60Hz shows kodi normally, at 90Hz only get a blank screen.

On Whitelisted resolutions only shows 60Hz too

**Comment by blunden** [comment] 2019-06-15 22:01
On the OnePlus 7 Pro, it displays fine on first launch and then a black screen on any subsequent launches.

**Comment by blunden** [comment] 2019-07-28 19:52
The issue seems to be because of how the OnePlus 7 Pro adjusts the refresh rate down in some cases. When forced to a constant 60 or 90 Hz refresh rate, Kodi works fine.

**Comment by Fordwrench** [comment] 2019-11-11 16:06
Does the same for me on Pixel 4 XL, even lowering the screen brightness doesnt work...

**Comment by brandonw1987tn** [comment] 2019-11-11 16:19
> Does the same for me on Pixel 4 XL, even lowering the screen brightness doesnt work...

I turned off the "smooth display" in the display settings, that worked. But of course that disables the 90 hertz display.

**Comment by kfirfer** [comment] 2020-06-06 10:19
same for me with galaxy s20 and configured display as 120hz

**Comment by monarc83** [comment] 2020-07-01 16:48
I have the same problem with my Oppo Find X2 Pro when choosing 120Hz or automatic

**Comment by jmbooth2000** [comment] 2020-07-25 16:37
same problem for me. Any updates from Kodi - Turning the whole phone down to 60Hz doesn't seem like a good option. Rumor has it that the Pixel 4 has a black list of apps that only run at 60Hz unfortunately it seems they didn't put Kodi on it.

**Comment by ingomc** [comment] 2020-10-07 13:04
Same Problem with my Galaxy S20, as soon as i turn down to 60hz it works again. Plz fix it

**Comment by magsom** [comment] 2021-01-10 13:15
Look "CAndroidUtils" in log, if screen is in 120Hz:
```
CAndroidUtils: Current resolution: 2327x1080 2327x1080 @ 60.000000 - Full Screen
CAndroidUtils: SetNativeResolution: : 1280x720 1280x720@0.000000
```
It detected a wrong refresh rate 60Hz, but set a 0Hz display mode.

If in 48Hz, no problem:
```
CAndroidUtils: Current resolution: 2327x1080 2327x1080 @ 48.000000 - Full Screen
CAndroidUtils: SetNativeResolution: -1: 2327x1080 2327x1080@48.000000
```

Look at [source](https://github.com/xbmc/xbmc/blob/5230b683323ca58c62459a371c1306a6cb4d4644/xbmc/windowing/android/AndroidUtils.cpp#L46), seems there is a weird limit, if refresh rate isn't between 20-70Hz it will force use 60Hz.

**Comment by fritsch** [comment] 2021-01-10 14:33
I made a testbuild weeks ago, exactly working around what you pointed out - sadly, no one on the forum came back testing it :-(.

Could you give me a logfile with that one: http://mirrors.kodi.tv/test-builds/android/arm/kodi-20201227-32db13c0-120-armeabi-v7a.apk

**Comment by fritsch** [comment] 2021-01-10 14:47
Also please turn on debuglogging and then restart with display being set at 120 hz. Thanks much.

**Comment by magsom** [comment] 2021-01-10 14:58
Unfortunately it crashes.
Log: https://paste.kodi.tv/paxamaguba.kodi

Log still contains "CAndroidUtils: SetNativeResolution: : 1280x720 1280x720@0.000000"

**Comment by fritsch** [comment] 2021-01-10 15:05
Okay, it starts here, way earlier:
2021-01-10 22:50:04.737 T:21656   DEBUG <general>: CAndroidUtils: maximum/current resolution: 0x0
2021-01-10 22:50:04.737 T:21656   DEBUG <general>: CAndroidUtils: selected resolution: 0x0

**Comment by fritsch** [comment] 2021-01-10 15:07
It fails here:
displaySize = CJNISystemProperties::get("sys.display-size", "");

And then it continues being zero - while modes have not yet been fetched.

**Comment by fritsch** [comment] 2021-01-10 15:17
I think the following happens:
The window is not yet there and we don't get a refreshrate nor window size from there. This happens as the GUI limit is queried too early, which relies on the native Window which not yet exists.

Build in progress. I will link it here.

**Comment by fritsch** [comment] 2021-01-10 15:38
What happens here: http://mirrors.kodi.tv/test-builds/android/arm/kodi-20210110-6bd4e551-120-armeabi-v7a.apk (wait a bit until the mirror is synced).

**Comment by magsom** [comment] 2021-01-11 04:19
Hello @fritsch,
I tried the newest 20210110 build, it still crashes.
AndroidUtils log here:
 ```
2021-01-11 11:58:39.690 T:29201   DEBUG <general>: CAndroidUtils: maximum/current resolution: 1280x720
kodi.log(294)
2021-01-11 11:58:39.690 T:29201   DEBUG <general>: CAndroidUtils: selected resolution: 1280x720
kodi.log(358)
2021-01-11 11:58:39.730 T:29201    INFO <general>: CAndroidUtils: Current display refresh rate: 120.000008
kodi.log(359)
2021-01-11 11:58:39.730 T:29201    INFO <general>: CAndroidUtils: Current resolution: 1280x720 1280x720 @ 120.000008 - Full Screen
kodi.log(360)
2021-01-11 11:58:39.730 T:29201   DEBUG <general>: CAndroidUtils: ProbeResolutions: 1280x720
kodi.log(361)
2021-01-11 11:58:39.731 T:29201    INFO <general>: CAndroidUtils: Current display refresh rate: 120.000008
kodi.log(362)
2021-01-11 11:58:39.731 T:29201    INFO <general>: CAndroidUtils: Current resolution: 1280x720 1280x720 @ 120.000008 - Full Screen
kodi.log(436)
2021-01-11 11:58:39.736 T:29201    INFO <general>: CAndroidUtils: SetNativeResolution: : 1280x720 1280x720@0.000000
kodi.log(442)
2021-01-11 11:58:39.819 T:29201    INFO <general>: CAndroidUtils: SetNativeResolution: : 1280x720 1280x720@0.000000
```

While kodi stable release normally boots at 48Hz, that log also contains "maximum/current resolution:0x0"

Where I can see your code changes?

**Comment by fritsch** [comment] 2021-01-11 17:50
In my fork of xbmc on github, branch is 120. I am just toying around as I have no idea to thoroughly test that stuff here.

I will be afk at least until next weekend.

**Comment by Poci** [comment] 2021-04-13 09:41
Something new here?

**Comment by a1rwulf** [comment] 2021-04-13 18:27
I have a OnePlus 8 that can do 90Hz, whenever I start kodi it immediately switches to 60Hz anyway and thus kodi doesn't crash.
Any idea how I'd be able to reproduce it?

**Comment by gradha** [comment] 2021-08-18 10:42
Kodi on Poco F3 doesn't startup when 120hz. When it's 60hz everything works, and after having opened once, changing to 120hz and going back works. But after killing the app and opening again the black screen comes and nothing more happens. Also, changing to 60hz doesn't work any more, the app has to be cleared of all data before it starts working again at 60hz.

I did enter 60hz and turn on logging but I see no files anywhere on the device.

**Comment by Technologov** [comment] 2021-11-14 01:52
Any status update?
This is a grave bug, because newest Android, the Galaxy Fold 3, refuses to work with Kodi

**Comment by J4gQBqqR** [comment] 2021-12-20 15:49
It has been like 2.5 years. 
The only difference between the time this ticket was opened and today is that nowadays most new Android phones will show Kodi with a black screen. 
I wonder if the Kodi team treats this issue as a serious bug, since it is labeled as "triage" in its tags.
I don't see it being resolved anytime soon. Maybe switch to Jellyfin is better choice.

**Comment by Ulrar** [comment] 2022-02-21 12:00
So what's the way to get an issue looked at, is there a way to "vote" for issues to let the devs know that something is impacting users maybe ?
Or assuming PRs do get merged if they look good, maybe we could get a bounty started on this issue to try and motivate an Android developer to work on this, although I don't know what platform is preferred for this.

Most newer phones and tablet now have adaptive refresh rate displays so this is likely going to start impacting more and more people, I don't imagine it'll just go away.

**Comment by kenzoka24** [comment] 2022-04-16 22:16
@thexai MrMc Lite which is fork of kodi works with 120hz android device without any judder or lag whereas kodi shows black screen

is there way to "borrow" code from https://github.com/MrMC/mrmc to fix this?

**Comment by nRaecheR** [comment] 2022-04-25 07:58
It seems the problem vanished with the latest update for my Samsung Galaxy Tab S7 (T870XXU2CVCD, Android 12, Security Level 1.April 2022). Maybe there's some kind of application-specific override of the adaptive screen refresh rate functionality now.

**Comment by kenzoka24** [comment] 2022-04-25 08:00
> It seems the problem vanished with the latest update for my Samsung Galaxy Tab S7 (T870XXU2CVCD, Android 12, Security Level 1.April 2022). Maybe there's some kind of application-specific override of the adaptive screen refresh rate functionality now.

nope still happens on my 120hz and 90hz devices

**Comment by nRaecheR** [comment] 2022-04-25 08:07
It was fixed/worked around with a firmware update from Samsung.

**Comment by kenzoka24** [comment] 2022-04-25 08:25
> It was fixed/worked around with a firmware update from Samsung.


too bad samsung doesn't make every device then



this issue doesn't happen with ltpo panels either

cause they can lower refresh rate than 60hz

**Comment by ColdThunder11** [comment] 2022-05-01 15:39
It seems that kodi works well on my Xiaomi Pad 5 with 120Hz by just change the weird limit, if anyone need a debug build, [here](https://github.com/ColdThunder11/xbmc/releases/tag/test-build) is the apk.

**Comment by kenzoka24** [comment] 2022-05-01 16:26
> It seems that kodi works well on my Xiaomi Pad 5 with 120Hz by just change the weird limit, if anyone need a debug build, [here](https://github.com/ColdThunder11/xbmc/releases/tag/test-build) is the apk.

IT WORKS!

bro, I would kiss you through the screen if I could 😂



I have a Redmi Note 11 with 90hz display
the build you shared works
1. no black screen on startup
2. playback works correctly




nice work man

**Comment by DoomSlayer10K** [comment] 2022-05-01 16:34
> It seems that kodi works well on my Xiaomi Pad 5 with 120Hz by just change the weird limit, if anyone need a debug build, [here](https://github.com/ColdThunder11/xbmc/releases/tag/test-build) is the apk.

what was the weird limit behaviour that previously existed?

**Comment by ColdThunder11** [comment] 2022-05-02 06:59
> > It seems that kodi works well on my Xiaomi Pad 5 with 120Hz by just change the weird limit, if anyone need a debug build, [here](https://github.com/ColdThunder11/xbmc/releases/tag/test-build) is the apk.
> 
> what was the weird limit behaviour that previously existed?

In source code, seems that it only accept refreshrate between 20Hz and 70Hz in [AndroidUtils.cpp](https://github.com/xbmc/xbmc/blob/master/xbmc/windowing/android/AndroidUtils.cpp). It exsists in first commit and no comment leave here. Maybe that time kodi dose not support refreshrate out of that range? I'll make a pr later, hope for futher discuss.

**Comment by DoomSlayer10K** [comment] 2022-05-02 07:01
> > > It seems that kodi works well on my Xiaomi Pad 5 with 120Hz by just change the weird limit, if anyone need a debug build, [here](https://github.com/ColdThunder11/xbmc/releases/tag/test-build) is the apk.
> > 
> > what was the weird limit behaviour that previously existed?
> 
> In source code, seems that it only accept refreshrate between 20Hz and 70Hz in [AndroidUtils.cpp](https://github.com/xbmc/xbmc/blob/master/xbmc/windowing/android/AndroidUtils.cpp). It exsists in first commit and no comment leave here. Maybe that time kodi dose not support refreshrate out of that range? I'll make a pr later, hope for futher discuss.

maybe because kodi didn't have an active developer for android for a long time

just as 90/120hz devices started showing up
it became a problem

**Comment by DoomSlayer10K** [comment] 2022-05-03 23:13
@thexai @enen92 @CastagnaIT

**Comment by CastagnaIT** [comment] 2022-05-04 06:43
IMO i think that your PR is a first step
I can't judge precisely because i don't have a suitable android device where to test

but i also see that `getpreferredRefreshRate` called here
https://github.com/xbmc/xbmc/blob/master/xbmc/windowing/android/AndroidUtils.cpp#L48
referred to this API call method:
https://github.com/xbmc/libandroidjni/blob/e00d271b5dbfa050fb9876df73b617cfe33326b1/src/WindowManager.cpp#L34-L40
is deprecated in Android docs:
https://developer.android.com/reference/kotlin/android/view/WindowManager.LayoutParams#preferredrefreshrate

i think that also this part will need to be reworked
and looking at the git history blame i have not found an explanation because the author have set that limit

**Comment by DoomSlayer10K** [comment] 2022-05-04 07:08
@ColdThunder11

**Comment by ColdThunder11** [comment] 2022-05-04 08:41
> IMO i think that your PR is a first step I can't judge precisely because i don't have a suitable android device where to test
> 
> but i also see that `getpreferredRefreshRate` called here https://github.com/xbmc/xbmc/blob/master/xbmc/windowing/android/AndroidUtils.cpp#L48 referred to this API call method: https://github.com/xbmc/libandroidjni/blob/e00d271b5dbfa050fb9876df73b617cfe33326b1/src/WindowManager.cpp#L34-L40 is deprecated in Android docs: https://developer.android.com/reference/kotlin/android/view/WindowManager.LayoutParams#preferredrefreshrate
> 
> i think that also this part will need to be reworked and looking at the git history blame i have not found an explanation because the author have set that limit so for me PR ok but i prefer leave last word to the most experienced devs

I'm not so familar with android too, lol.   
The PR is only temporary way to fix this problem, it's obviously that more work should be done. I'll try my best to do this in spare time.

**Comment by MajorMurphy** [comment] 2022-05-07 05:52
> > It seems that kodi works well on my Xiaomi Pad 5 with 120Hz by just change the weird limit, if anyone need a debug build, [here](https://github.com/ColdThunder11/xbmc/releases/tag/test-build) is the apk.
> 
> IT WORKS!

Also confirmed fixed on Samsung Galaxy S21+

Thanks!

**Comment by CastagnaIT** [comment] 2022-05-07 09:43
fixed by #21346

**Closed by CastagnaIT** 2022-05-07 09:43 UTC
Labels: Platform: Android, Resolution: Fixed, Triage: Confirmed

**Comment by Ulrar** [comment] 2022-05-07 09:46
Out of curiosity, when can we expect the fix in the play store, with v20 ?

**Comment by CastagnaIT** [comment] 2022-05-07 09:49
yes if there are no regressions that require some more deep rework

**Comment by Ulrar** [comment] 2022-05-07 10:09
That's great news, thanks for the work !
Let's hope there's no regressions :)

**Comment by fritsch** [comment] 2022-05-07 12:51
Thanks to everyone. You might ask the question: Why wasn't this "simple fix" be included for so long as it was available even on this bugtracker bevore. The reason is simple: Back at that time, it did not work :-) - there were still devices that behaved this badly when we opened the OpenGL context with 120 hz. So, let's see if someone comes out with the device of the 90s :P and points the finger at us, that we have broken his kodi.

**Comment by Ulrar** [comment] 2022-05-07 12:52
Presumably a device that old wouldn't run an Android recent enough to get v20 anyway, it'll probably be fine

**Comment by fritsch** [comment] 2022-05-07 14:30
Don't underestimate the users with FireTV first edition - I have a PR here somewhere to drop backwards compatibility ... it was never merged cause of: "my 5 dollar 20 cents device would not work anymore ..."

I could care less :-) - means: fine that someone merged it.

**Comment by DoomSlayer10K** [comment] 2022-05-07 15:19
> Thanks to everyone. You might ask the question: Why wasn't this "simple fix" be included for so long as it was available even on this bugtracker bevore. The reason is simple: Back at that time, it did not work :-) - there were still devices that behaved this badly when we opened the OpenGL context with 120 hz. So, let's see if someone comes out with the device of the 90s :P and points the finger at us, that we have broken his kodi.

my god 🤦


seriously?!

**Comment by fritsch** [comment] 2022-05-07 15:30
Partly :-). If team kodi would take kodi too seriously ... we could whine every single day. Let's move on and hopefully someone (besides you guys) is also happy now around the globe.

**Comment by DoomSlayer10K** [comment] 2022-05-07 15:33
> 
I most certainly could not be any happier that this works now

**Comment by Emulover2555** [comment] 2022-05-18 17:21
> It seems that kodi works well on my Xiaomi Pad 5 with 120Hz by just change the weird limit, if anyone need a debug build, [here](https://github.com/ColdThunder11/xbmc/releases/tag/test-build) is the apk.

Hello, I attempted to follow that link but it gave me a 404 error. Can you provide an updated link so that I can access the debug build?

**Comment by DoomSlayer10K** [comment] 2022-05-18 17:23
> > It seems that kodi works well on my Xiaomi Pad 5 with 120Hz by just change the weird limit, if anyone need a debug build, [here](https://github.com/ColdThunder11/xbmc/releases/tag/test-build) is the apk.
> 
> Hello, I attempted to follow that link but it gave me a 404 error. Can you provide an updated link so that I can access the debug build?

it's already been merged

use the latest kodi 20 alpha

**Comment by aindriu80** [comment] 2022-09-15 11:49
> > > It seems that kodi works well on my Xiaomi Pad 5 with 120Hz by just change the weird limit, if anyone need a debug build, [here](https://github.com/ColdThunder11/xbmc/releases/tag/test-build) is the apk.
> > 
> > 
> > Hello, I attempted to follow that link but it gave me a 404 error. Can you provide an updated link so that I can access the debug build?
> 
> it's already been merged
> 
> use the latest kodi 20 alpha

Thanks, I've got it working on a Redmi Note 10 Pro (120hz) with the Alpha2 but not the Alpha1 ->

Kodi 20.0-ALPHA2 (arm64-v8a) (Android 5.0+)
https://www.apkmirror.com/apk/xbmc-foundation/kodi/kodi-20-0-alpha2-release/kodi-20-0-alpha2-2-android-apk-download/download/?key=4f1e4d1fe1a6647021f7b5b1dd06d9017091b767
