### ISSUE TITLE
Kodi does not preserve "Repeat: One" setting between restarts

### ISSUE THREAD

**Issue by DVDos** [xbmc/xbmc#19268] opened 2021-02-23 17:26 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

If music player is set to 'Repeat: One' song, after application restart the setting is reset to 'Repeat: Off'. However, if set to 'Repeat: All', or 'Repeat: Off', the setting **_is_** preserved after restart.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

When music player is set to 'Repeat: One' song, after application restart the setting should be 'Repeat: One'.

## Actual Behavior

When music player is set to 'Repeat: One' song, after application restart the setting is reset to 'Repeat: Off'.

### To Reproduce

1. Start playback of Music
2. Go to playlist
3. Set 'Repeat' to 'One'
4. Restart Kodi

### Debuglog
Sorry, but my Android TV seems to be locked out of writing to external storages...

### Screenshots
Sorry, but my Android TV seems to be locked out of writing to external storages...

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 8.0.0 TV
 - Kodi version: 18.9, 19.0

**Comment by DaveTBlake** [comment] 2021-02-23 17:36
I am sure this has come up before on the forum, always good to search there before raisning an issue on Github.

The current behaviour is by design so closing. Repeat once needs something queued to repeat, when Kodi is off and then started the queue is empty.

**Closed** 2021-02-23 17:36 UTC
