### ISSUE TITLE
Watched items not hidden when using mysql, NAS, and large library.

### ISSUE THREAD

**Issue by WizardKnight** [xbmc/xbmc#16357] opened 2019-07-06 22:09 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

[Here is a video clip of the issue in action](https://drive.google.com/open?id=16ZAvk8WY4Ce1RLgBQol-mnGdmGvax_20). (Captured on a Win10 box running stock Kodi other than the skin, MariaDB 10.4.6 hosted by Ubuntu 18.04).
1. First time entering Movies.
2. Back out.
3. Re-enter Movies
4. Note the showing of items marked as watched.
[Here is the same issue in the Estuary skin as it looks a little different, but has the same net result.](https://drive.google.com/open?id=1fYj4Dx1tSdk6begO2i8BylxvfvztTjiu)

[See this video](https://drive.google.com/open?id=1Th6QFrmOPn1l4uRLyo3KQsGVZ5wf-foa) showing Kodi working fine with just my tiny, 15 movie, 4K movie collection.
As soon as I add and scrape my 1800+ HD/SD movie collection I see the odd behavior.

After this you have to do something like marking something as watched or going to TV shows to force a reload of the database.

I took my win10 box, and rolled back to kodi-18.0-Leia_beta1-x64, and I was not able to reproduce the issue.
Upgraded to kodi-18.0-Leia_beta3-x64, no issues.
Upgraded to kodi-18.0-Leia_beta4-x64, no issues.
Upgraded to kodi-18.0-Leia_beta5-x64, no issues.

I then tried kodi-18.0-Leia_rc1-x64, and I was able to see the issue again.
So something happened between beta 5, and RC1 that causes this issue.
I can produce this issue on Kodi 18.1, 18.2, 18.3, and 19.

Thread with as much detail as I could put in one place:
https://forum.kodi.tv/showthread.php?tid=345208
Additional thread:
https://forum.kodi.tv/showthread.php?tid=339773

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I would expect that if the watched hidden flag is toggled on, that all videos marked as watched would not appear in the media listing

## Actual Behavior

After watching a movie, or after entering and leaving the Movies area all movies are shown regardless of the watched flag.

### To Reproduce

Create NAS with 1800 movie titles for scraping.
Create Mysql server.
Connect both to Kodi and scrape to mysql media database.

[Here is a video clip of the issue in action](https://drive.google.com/open?id=16ZAvk8WY4Ce1RLgBQol-mnGdmGvax_20). (Captured on a Win10 box running stock Kodi other than the skin, MariaDB 10.4.6 hosted by Ubuntu 18.04).
1. First time entering Movies.
2. Back out.
3. Re-enter Movies
4. Note the showing of items marked as watched.

I have seen this bug regardless of what skin I use. 

### Debuglog

The debuglog can be found here:
[Log files from one of my devices.](http://ix.io/1NRY)

### Screenshots 
Here are some links or screenshots to help explain the problem:

https://i.imgur.com/kL9NDPO.jpg

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I can reproduce this issue all day long with completly fresh/new builds/installs of Kodi on Windows or Ubuntu, Fresh builds of the Mysql server, and a fresh NAS build using NFS or SMB.
At least two other users have confirmed that they are seeing the same behavior.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Win 10, ubuntu 18.04, 19.04, Coreelec, Libreelec.
 - Kodi version:18rc1 and newer

I can reproduce this issue all day long with completly fresh/new builds/installs of Kodi on Windows or Ubuntu, Fresh builds of the Mysql server, and a fresh NAS build using NFS or SMB. 

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment] 2019-07-07 08:32
If you know it working for any other platform (what I guess you have actively tested) could you please get us a log from a supported platform which shows the same issue?

Thanks in advance.

**Comment by WizardKnight** [comment] 2019-07-07 16:20
It is not working on any platform I have tested, so I can not provide logs from where it works as expected.
Here is another set of logs from where it does not work.  https://pastebin.com/g3BErpcd

**Comment by DaVukovic** [comment] 2019-07-07 21:18
Sorry for the confusion. I spelled it wrong ;)

I rather meant: "if you know it *not* working....."

So thanks for the log. Can't help much in that regard, but probably one of our devs might see something.

**Comment by WizardKnight** [comment] 2019-07-10 04:41
> 
> 
> Sorry for the confusion. I spelled it wrong ;)
> 
> I rather meant: "if you know it _not_ working....."
> 
> So thanks for the log. Can't help much in that regard, but probably one of our devs might see something.

Is there anything else I can do?

**Comment by 5-star** [comment] 2019-08-04 14:50
I also have a large mysql Db with the same issue.

It's happenning at least since V18
https://github.com/xbmc/xbmc/issues/15251

**Comment by toxwa** [comment] 2019-08-07 07:09
Check this pull request which caused the problems: [https://github.com/xbmc/xbmc/pull/14810](url)

**Comment by WizardKnight** [comment] 2019-08-07 07:44
That would be the correct time frame. Now how do we get it reverted, or modified to deal with MySQL databases correctly?

**Comment by toxwa** [comment] 2019-08-07 08:16
I don't know, I'm not a programmer. I found the pull request because you said it happened between beta 5 and rc1. Maybe @mkreisl can help as he was the one to mention this behaviour in the last comment on the pull request.

**Comment by jjd-uk** [comment] 2019-08-08 11:26
@peak3d can you look at this since it seems your https://github.com/xbmc/xbmc/pull/14810 may have introduced a problem.

**Comment by WizardKnight** [comment] 2019-08-08 17:44
I am happy to test a Win10 version with my database if/when you have a code change.

**Comment by 5-star** [comment] 2019-08-08 18:39
I can do the same, both windows and android

**Comment by JoshDi** [comment] 2019-08-12 23:28
I can test as well with windows 7 x64. I am experiencing this issue now as well.

**Comment by JoshDi** [comment] 2019-08-13 03:07
> I can test as well with windows 7 x64. I am experiencing this issue now as well.

I actually just dropped my video and music mysql databases, added **<cacheslowqueries>false</cacheslowqueries>** to my advancedsettings file and rescanned my library. 

The issue seems to have gone away after I restored my watched lists from trackt/local watched DB

**Comment by WizardKnight** [comment] 2019-08-13 05:21
> 
> 
> > I can test as well with windows 7 x64. I am experiencing this issue now as well.
> 
> I actually just dropped my video and music mysql databases, added **`<cacheslowqueries>false</cacheslowqueries>`** to my advancedsettings file and rescanned my library.
> 
> The issue seems to have gone away after I restored my watched lists from trackt/local watched DB
> 
> I am using one of the nightly builds: [KodiSetup-20190810-5330b749-Leia-x64.exe](http://mirrors.kodi.tv/nightlies/windows/win64/Leia/KodiSetup-20190810-5330b749-Leia-x64.exe)

Where in advancesetting.xml did you add <cacheslowqueries>false</cacheslowqueries>
I can't find any documentation on that option.

**Comment by toxwa** [comment] 2019-08-13 08:57
cacheslowqueries is added with this pull request: [https://github.com/xbmc/xbmc/pull/15916](https://github.com/xbmc/xbmc/pull/15916). But it needs a rebase and I think it's not included in the nightlies. This pull request does confirm that the problems only happen with a larger database. It starts to chache if a query is too slow, and querying a large database over a netwerk can become too slow.

**Comment by toxwa** [comment] 2019-08-13 09:28
The more I read about it, it seems that [this](https://github.com/xbmc/xbmc/pull/15916#issuecomment-485869611) could be a solution. I think a GUI_MSG_UPDATE_ITEM to update the watched state would be cleaner solution than [https://github.com/xbmc/xbmc/pull/14810](https://github.com/xbmc/xbmc/pull/14810) which caused the problems with cached database querries. So reverting #14810 and implementing the the GUI_MSG_UPDATE_ITEM messages in the "mark as watched" process could solve the problems, but I am not familiar enough with C++ or the kodi source code to know how/where to add the necessary code to test this.

**Comment by toxwa** [comment] 2019-08-13 09:28
The more I read about it, it seems that [this](https://github.com/xbmc/xbmc/pull/15916#issuecomment-485869611) could be a solution. I think a GUI_MSG_UPDATE_ITEM to update the watched state would be cleaner solution than [https://github.com/xbmc/xbmc/pull/14810](https://github.com/xbmc/xbmc/pull/14810) which caused the problems with cached database querries. So reverting #14810 and implementing the the GUI_MSG_UPDATE_ITEM messages in the "mark as watched" process could solve the problems, but I am not familiar enough with C++ or the kodi source code to know how/where to add the necessary code to test this.

**Comment by 5-star** [comment] 2019-08-13 09:49
I tried <cacheslowqueries>, without reloading the library. The problem persisted and I started to have issues with movies/episodes not being marked as watched, so i removed it.

@WizardKnight see this
https://github.com/xbmc/xbmc/pull/15916

**Comment by Mange** [comment] 2019-08-27 17:40
I have the same issue, which is driving my family slowly insane. :laughing: 

Is there some way to improve this before the root cause has been fixed?

**Comment by 5-star** [comment] 2019-09-21 13:24
Has anyone tried Kodi19 alpha?

If streaming is evil, would it be possible to prioritize this bug, since it really affects the kodi library users, over the streaming users which dont care about it.

This was reported first in January, but is older than that
https://github.com/xbmc/xbmc/issues/15251

Thank you for any help!

**Comment by WizardKnight** [comment] 2019-09-29 01:45
> 
> 
> Has anyone tried Kodi19 alpha?
> 
> If streaming is evil, would it be possible to prioritize this bug, since it really affects the kodi library users, over the streaming users which dont care about it.
> 
> This was reported first in January, but is older than that
> #15251
> 
> Thank you for any help!

I tried a Kodi 19 alpha several months ago, and there was no difference.

**Comment by DaveTBlake** [comment] 2019-10-15 11:00
Sorry for the long delay in anyone looking at this, it is not about ignoring users but there just isn't a team member with spare time and, an interest in and knowledge of the video library. My thing is the music lib (I don't even have a video lib to test with) but I will see if I can progress it. 
>So reverting #14810 and implementing the the GUI_MSG_UPDATE_ITEM messages in the "mark as watched" process could solve the problems,

I agree with @toxwa that seems very likely. It is not about the database, but the caching and item update notification and refreshing. If I put up a v19 test build with #14810 reverted will some of you be able to test if that does improve things.

**Comment by WizardKnight** [comment] 2019-10-15 12:41
> 
> 
> Sorry for the long delay in anyone looking at this, it is not about ignoring users but there just isn't a team member with spare time and, an interest in and knowledge of the video library. My thing is the music lib (I don't even have a video lib to test with) but I will see if I can progress it.
> 
> > So reverting #14810 and implementing the the GUI_MSG_UPDATE_ITEM messages in the "mark as watched" process could solve the problems,
> 
> I agree with @toxwa that seems very likely. It is not about the database, but the caching and item update notification and refreshing.
> 
> There is a Win64 test build v19 test build with #14810 reverted here
> http://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20191015-7f499191-Revert14810-x64.exe could someone test if that does improve things (although more will be needed to fix without other issues reoccuring)

I will start a test tonight, but it will probably take a day to rebuild the database with the new install. It will probably be two days before I can say if it works or not.

**Comment by 5-star** [comment] 2019-10-15 20:32
Would it be possible to build the android version?

On my android boxes it's happening all the time so it will be easy to check.

On the PC, i knew it worked better. I tried now and I can not make it happen, so I wont be able to say whether is fixed or not.

Thanks DaveTBlake, for coming out of your way to help us out.

**Comment by WizardKnight** [comment] 2019-10-17 02:38
> 
> 
> Sorry for the long delay in anyone looking at this, it is not about ignoring users but there just isn't a team member with spare time and, an interest in and knowledge of the video library. My thing is the music lib (I don't even have a video lib to test with) but I will see if I can progress it.
> 
> > So reverting #14810 and implementing the the GUI_MSG_UPDATE_ITEM messages in the "mark as watched" process could solve the problems,
> 
> I agree with @toxwa that seems very likely. It is not about the database, but the caching and item update notification and refreshing.
> 
> There is a Win64 test build v19 test build with #14810 reverted here
> http://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20191015-7f499191-Revert14810-x64.exe could someone test if that does improve things (although more will be needed to fix without other issues reoccuring)

I tried your test build, and I no longer see the issue. 
It looks like you nailed it down.  🥇

**Comment by theone11** [comment] 2019-10-17 21:33
Good news.
I see that the change is for KODI 19. I use AMLOGIC devices using CoreElec, which is still on 18 (could be a long time till until the move to 19 if at all...).

Can the change be implemented also for KODI 18?

**Comment by DaveTBlake** [comment] 2019-10-18 18:39
There is a v18 test build for win64 here http://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20191018-fc596118-Revert14810_Leia-x64.exe with variants for all the other platforms I can trigger  in the similar test build folders. 

This also has a fix for the issue #14810 was intended to fix, and testing that as well would be helpful. Watch for the playcount (watched state) being updated correctly when playback finishes - listing items by playcount may make this more obvious. Previously any cached lists would not have shown the change to play count.

**Comment by WizardKnight** [comment] 2019-10-19 17:07
> This also has a fix for the issue #14810 was intended to fix, and testing that as well would be helpful. Watch for the playcount (watched state) being updated correctly when playback finishes - listing items by playcount may make this more obvious. Previously any cached lists would not have shown the change to play count.

So here is my testing observations when looking at play count. As never use this feature, I do not know what the expected results should be.

If I start a movie, and let it play all the way to the end the play count is shown as correct in the movie listing page after exiting the movie playback.
If I start a movie and stop it a few seconds before the end, it is marked as watched but the play count is not incremented until I refresh the view. 

If the goal is to increment when playback finishes vs stopped near the end (as noted in your post) then I would say you have succeeded. 
Otherwise I would compare the code from when a movie exits near the end vs 100% at the end to see if a play count variable is cashed/refreshed. Or maybe if the whole list is refreshed.

**Comment by DaveTBlake** [comment] 2019-10-31 13:31
Unfortunately I had to rework my fix to this issue because of unexpected consequneces for other behaviour.  I would appreciate if anyone could re-test that the original issue reported here is fixed by my second attempt.

There is a v18 test build for win64 here http://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20191030-90a7c73a-PR16806-merge-x64.exe with variants for all the other platforms I can trigger in the similar test build folders.

**Comment by WizardKnight** [comment] 2019-10-31 22:35
It looks good to me.
I am seeing the expected behavior of watched movies being hidden
consistently.

**Comment by 5-star** [comment] 2019-10-31 23:31
Results are good for me too. Watched items stay hidden.

So good that I will use this version until this is included into the distribution one.

**Comment by WizardKnight** [comment] 2019-11-04 20:31
Any chance this fix can be pushed out to the nightlies?

-Sent from Android.

**Comment by 5-star** [comment] 2019-11-04 21:09
I'm hoping that it will be in v18.5, any day now

https://github.com/xbmc/xbmc/milestone/128

fingers crossed

**Comment by WizardKnight** [comment] 2019-11-04 21:38
Is there a bug number I can reference? I want to get this pulled into a
build by another group, and my knowledge of git is poor.

-Sent from Android.

**Comment by DaveTBlake** [comment] 2019-11-04 22:41
Since I'm leading the release 18.5 will be delayed until this fix is merged. Delay in merging into Leia

**Comment by DaveTBlake** [comment] 2019-11-04 22:55
@WizardKnight the PRs to master that fix this issue are https://github.com/xbmc/xbmc/pull/16804 (that reverts 14810), and  https://github.com/xbmc/xbmc/pull/16848 (which corrects https://github.com/xbmc/xbmc/pull/16805 should their build alreday have that).

Because of other non-related build issues with master which means we are not getting "green lights" for Windows/OSX builds, I am holding back from merging 16848 so no it won't be in the nightlies yet. Frustrating, but worth being patient for build integrity down the line. Consequently not merging the backport to v18 either, PR to master should be merged first.

Since I'm also taking lead on v18.5 release I will delay that until this fix can be included.

So a sequence of events to happen. but you have been waiting months and so a few days/weeks is no big deal. Meanwhile thanks for doing your part in testing.

**Comment by Mange** [comment] 2019-11-05 07:00
@DaveTBlake thank you for the update.

We're all rooting for you guys! Thank you for all your time and passion added to this project over the years!

**Comment by 5-star** [comment] 2019-11-07 02:41
I also would like to thank DaveTBlake again. This issue was really annoying, and it was almost ignored for almost one year, until Dave same along.

Glad to see this already merged in 18.5 :)

**Comment by WizardKnight** [comment] 2019-11-07 02:45
Seconded!


-Sent from Android.

**Comment by DaveTBlake** [comment] 2019-11-08 14:00
The PRs fixing this issue have all now been merged, and will be in the next nightly build for v19, and in the point release of 18.5 that will happen within the next week (or so).

**Closed by DaveTBlake** 2019-11-08 14:00 UTC
Labels: Component: Video, v18 Leia

**Comment by jjd-uk** [comment] 2019-11-08 15:16
It will also be the pre-18.5 Leia nightlies e.g. 64 bit builds at http://mirrors.kodi.tv/nightlies/windows/win64/Leia/

**Comment by WizardKnight** [comment] 2019-11-08 16:29
Nice.

-Sent from Android.
