### ISSUE TITLE
Problem with subtitles in Hebrew on Kodi 19

### ISSUE THREAD

**Issue by ShmuelRonen** [xbmc/xbmc#19351] opened 2021-03-07 12:17 UTC
In version 19, when watching a movie with Hebrew subtitles, the punctuation marks, which in Hebrew are on the left, appear on the right.
This is a problem that was not present in previous versions. This happens on both Windows and Android.

**Comment by enen92** [comment] 2021-03-07 12:31
Duplicate of https://github.com/xbmc/xbmc/issues/18648

**Closed by enen92** 2021-03-07 12:31 UTC
