### ISSUE TITLE
ListItem.Icon does not fallback to the default icon

### ISSUE THREAD

**Issue by ronie** [xbmc/xbmc#17034] opened 2019-12-12 22:40 UTC
when no thumbnail is available, ListItem.Icon should fallback to the default icon (ie. DefaultVideo.png)
this is currently broken for all video items (movies/tvshows/seasons/episodes/musicvideos).
most likely due to the same issue, ListItem.ActualIcon returns empty as well.

it works fine for music items.

Leia:
![leia](https://user-images.githubusercontent.com/687265/70754582-d7d9bf80-1d37-11ea-8772-9f67706688ef.jpg)

Matrix:
![matrix](https://user-images.githubusercontent.com/687265/70754587-db6d4680-1d37-11ea-9989-8f942b156955.jpg)

pinging @enen92 / @DaveTBlake , iirc you have been making code changes in this area..

**Comment by DaveTBlake** [comment] 2019-12-14 11:53
This could be a consequence of https://github.com/xbmc/xbmc/pull/16444 moving the default icon into art array. I did a follow-up fix for music as there were regressions where Kodi was using an empty art test, and art was now not empty. But video was not effected in the same way so I didn't touch that. 

Is this change to Estuary https://github.com/xbmc/xbmc/pull/17035 intended as a fix for this, or just a work around, or something else?

**Comment by ronie** [comment] 2019-12-14 12:38
thanx for looking into it.
the Estuary change is unrelated to this issue.

**Comment by ronie** [comment] 2020-01-02 23:44
@enen92  any ideas?

**Comment by enen92** [comment] 2020-01-03 12:38
@ronie can you provide some info on how to easily reproduce the issue? I'll definitely try to fix it if caused by my PR.

Added a .strm file to the library (The Social Network) and removed the items from the art table in MyVideos116.db but default icon is correctly filled:

![alt text](https://i.imgur.com/vjVXeJ0.png "Item")
![alt text](https://i.imgur.com/3vO12SR.png "Item")

Sorry for the delay, I need to enable email notifications for mentions.

Maybe send me a database where this issue is verified and let me know the item?

**Comment by ronie** [comment] 2020-01-04 00:32
here's the database, it has just 1 tv show:
[MyVideos116.db.zip](https://github.com/xbmc/xbmc/files/4021326/MyVideos116.db.zip)

as mentioned on slack, the issue is noticeable in the 'widelist' view of estuary.
![widelist](https://user-images.githubusercontent.com/687265/71756660-2e4aa180-2e91-11ea-8ce9-7b65d5a52a30.jpg)

**Comment by enen92** [comment] 2020-01-04 12:02
Ok I confirm the issue. I was not able to reproduce before because I removed all art items in the library specific to the tvshow or movie. In your case you have an empty thumb/poster but still have a valid fanart.
I'll come up with a fix.

**Closed** 2020-01-26 10:28 UTC
Labels: Component: GUI engine, Triage: Confirmed, v19 Matrix
