### ISSUE TITLE
All text disapear from user interface when starting video play

### ISSUE THREAD

**Issue by sjuk** [xbmc/xbmc#19254] opened 2021-02-21 01:30 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

When starting to play any video all text disappear from user interface.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Text in user interface is visible.

## Actual Behavior

Text in user interface is not visible.

## Possible Fix

- Switch between full screen and window mode (keyboard shortcut: "\") **[NEW]**
- Turn off TV and turn it on again
- Restart Kodi
- Restart PC

### To Reproduce

The issue occurs randomly. But when it starts it keeps reproducible for an unknown time.
1. Start playing any video (press return/enter)
2. Show info (press i) to get info without text
3. Stop playing video (press x) to get back to user interface without text

### Debuglog

The debuglog can be found here: [https://paste.kodi.tv/fenurucona.kodi](https://paste.kodi.tv/fenurucona.kodi) **[NEW: Rule conform log]**

### Screenshots 
Here are some links or screenshots to help explain the problem:

![screenshot00000](https://user-images.githubusercontent.com/5033784/108612717-101c6980-73e3-11eb-82d6-a323286019ee.png)
![screenshot00001](https://user-images.githubusercontent.com/5033784/108612720-16124a80-73e3-11eb-907f-dcc06cd263e9.png)
![screenshot00002](https://user-images.githubusercontent.com/5033784/108612722-1a3e6800-73e3-11eb-90d1-f534ce7daad3.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I was able to reproduce it from: PVR add-on

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu 20.04.2 LTS (Focal Fossa)
 - Kodi version: 19

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment] 2021-02-21 07:53
Thanks for the report. 

Unfortunately you have banned add-ons/repos installed. Please remove them first, then reproduce your issue and get us a new log. I'll label this issue as "ignored rules" for the time being. I will remove that label again after you have provided a new log.

Furthermore your log is way too long. As you are saying it's for any video, please follow the instruction below to create a new log after you have removed the banned add-ons:

- enable debug logging
- disable everything which is unrelated to the issue (automatic DB updates on startup for example)
- restart kodi
- try to reproduce your issue and don't do anything else.
- - as you said it's for any video, the log should show the playback of a single video only
- get us the log

**Comment by sjuk** [comment] 2021-02-21 10:00
This is not an easy task. The issue is not reproducible at will. It occurs randomly.

Challenge accepted. I disabled all unofficial repositories and add-ons and enabled debug logging. And apologies if the log will be huge.

By the way, if you are interested about the issue here is the row around where you will likely find more information in the currently pasted log. 

**02:02:10.392 T:1334    DEBUG <general>: AddOnLog: pvr.hts: Getting play position 0 for recording Die Simpsons**

**Comment by FernetMenta** [comment] 2021-02-21 10:43
> By the way, if you are interested about the issue here

I doubt that this is the case. I already showed how to fix but nobody showed interest https://forum.kodi.tv/showthread.php?tid=344992&pid=2870337#pid2870337

**Comment by ksooo** [comment] 2021-02-21 10:52
I don't think that nobody is interested. Patches posted in the forum can easily be overlooked. Why don't you open a PR? That would really be appreciated. I know you know how to do this. 😉

**Comment by fritsch** [comment] 2021-02-21 11:42
I had some minutes. I took it over and adjusted VDPAU (OP's issue). Here: https://github.com/xbmc/xbmc/pull/19258

**Comment by sjuk** [comment] 2021-02-21 15:21
The error occurred again. I had to cut out the EGP update part from PVR add-on.
The debuglog can be found here: [https://paste.kodi.tv/fenurucona.kodi](https://paste.kodi.tv/fenurucona.kodi)
Please let me know if you need more information.

**Comment by sjuk** [comment] 2021-02-21 15:35
The bug report was edited to stick to the real known facts without any assumptions and adding some new insights (lookout for **[NEW]**). Now there is only a rule conform debuglog in this report. Please be so kind to remove the ignored rules flag. Thanks.

**Comment by fritsch** [comment] 2021-02-21 15:36
Try to build the PR I linked above and report back if that fixes your issue, please.

**Comment by fritsch** [comment] 2021-02-21 15:38
We will wait for your feedback with the possible code fix.

**Comment by sjuk** [comment] 2021-02-21 15:43
> Try to build the PR I linked above and report back if that fixes your issue, please.

I want to help but need more information on how to do it. What is meant by PR and how can I build it?

**Comment by sjuk** [comment] 2021-02-21 16:22
I found some information on how to prepare the build environment on Ubuntu, get the latest source code and build it.
- [https://github.com/xbmc/xbmc/blob/master/docs/README.Ubuntu.md](https://github.com/xbmc/xbmc/blob/master/docs/README.Ubuntu.md)
- [https://github.com/xbmc/xbmc/blob/master/docs/README.Linux.md](https://github.com/xbmc/xbmc/blob/master/docs/README.Linux.md)

And I guess PR stands for pull request. But I don't know how to get your special PR into the local source code.
Could please give me someone a hand on that step?

**Comment by fritsch** [comment] 2021-02-21 16:36
After you have cloned kodi, do in the cloned folder:

# making my kodi fork known to your checked out kodi
git remote add fritsch https://github.com/fritsch/xbmc.git
# fetching all the bits I have (will need a long time)
git fetch fritsch
# Reset to my branch (it's easiest)
git reset --hard fritsch/restore

Now follow the build instructions. Thanks very much in advance.

**Comment by sjuk** [comment] 2021-02-21 19:36
This is what I did.
- git clone https://github.com/xbmc/xbmc kodi
- cd kodi
- git remote add fritsch https://github.com/fritsch/xbmc.git
- git fetch fritsch
- git reset --hard fritsch/restore
- mkdir $HOME/kodi-build
- cd $HOME/kodi-build
- cmake ../kodi -DCMAKE_INSTALL_PREFIX=/usr/local -DCORE_PLATFORM_NAME="x11 wayland gbm" -DAPP_RENDER_SYSTEM=gl
- cmake --build . -- VERBOSE=1 -j$(getconf _NPROCESSORS_ONLN)

This is what I get.

`[ 13%] Linking CXX static library windowing_WAYLAND.a
cd /home/sjuk/kodi-build/build/windowing/wayland && /usr/bin/cmake -P CMakeFiles/windowing_WAYLAND.dir/cmake_clean_target.cmake
cd /home/sjuk/kodi-build/build/windowing/wayland && /usr/bin/cmake -E cmake_link_script CMakeFiles/windowing_WAYLAND.dir/link.txt --verbose=1
/usr/bin/ar qc windowing_WAYLAND.a  CMakeFiles/windowing_WAYLAND.dir/Connection.cpp.o CMakeFiles/windowing_WAYLAND.dir/OptionalsReg.cpp.o CMakeFiles/windowing_WAYLAND.dir/Output.cpp.o CMakeFiles/windowing_WAYLAND.dir/OSScreenSaverIdleInhibitUnstableV1.cpp.o CMakeFiles/windowing_WAYLAND.dir/Registry.cpp.o CMakeFiles/windowing_WAYLAND.dir/Seat.cpp.o CMakeFiles/windowing_WAYLAND.dir/SeatInputProcessing.cpp.o CMakeFiles/windowing_WAYLAND.dir/SeatSelection.cpp.o CMakeFiles/windowing_WAYLAND.dir/ShellSurface.cpp.o CMakeFiles/windowing_WAYLAND.dir/ShellSurfaceWlShell.cpp.o CMakeFiles/windowing_WAYLAND.dir/ShellSurfaceXdgShell.cpp.o CMakeFiles/windowing_WAYLAND.dir/ShellSurfaceXdgShellUnstableV6.cpp.o CMakeFiles/windowing_WAYLAND.dir/Util.cpp.o CMakeFiles/windowing_WAYLAND.dir/VideoSyncWpPresentation.cpp.o CMakeFiles/windowing_WAYLAND.dir/__/__/__/wayland-extra-protocols.cpp.o CMakeFiles/windowing_WAYLAND.dir/WindowDecorator.cpp.o CMakeFiles/windowing_WAYLAND.dir/WinEventsWayland.cpp.o CMakeFiles/windowing_WAYLAND.dir/WinSystemWayland.cpp.o CMakeFiles/windowing_WAYLAND.dir/XkbcommonKeymap.cpp.o CMakeFiles/windowing_WAYLAND.dir/WinSystemWaylandEGLContext.cpp.o CMakeFiles/windowing_WAYLAND.dir/WinSystemWaylandEGLContextGL.cpp.o CMakeFiles/windowing_WAYLAND.dir/InputProcessorKeyboard.cpp.o CMakeFiles/windowing_WAYLAND.dir/InputProcessorPointer.cpp.o CMakeFiles/windowing_WAYLAND.dir/InputProcessorTouch.cpp.o
/usr/bin/ranlib windowing_WAYLAND.a
make[2]: Leaving directory '/home/sjuk/kodi-build'
[ 13%] Built target windowing_WAYLAND
make[1]: Leaving directory '/home/sjuk/kodi-build'
make: *** [Makefile:141: all] Error 2`

**Comment by fritsch** [comment] 2021-02-21 19:54
Sadly that part does not show the error. Could you paste the entire compile log / including CMakeCache.txt to a pastebin near you?

**Comment by sjuk** [comment] 2021-02-21 20:04
Sure, here you are CMakeCache.txt: [https://paste.kodi.tv/iciyesujex.kodi](https://paste.kodi.tv/iciyesujex.kodi).
Where can I find the "entire compile log"?

**Comment by fritsch** [comment] 2021-02-22 06:11
Just all the bits you have in your "terminal". Just run "make" again in the directory where you executed cmake.
For your example: 
cd ~/kodi-build
make

And see what you get in this terminal.

**Comment by sjuk** [comment] 2021-02-22 22:34
> Just all the bits you have in your "terminal". Just run "make" again in the directory where you executed cmake.
> For your example:
> cd ~/kodi-build
> make
> 
> And see what you get in this terminal.

https://paste.kodi.tv/ilomowubak.kodi

**Comment by fritsch** [comment] 2021-02-23 05:12
Okay. My fault. Update will come. I will report back. After that:

git fetch fritsch 
git reset --hard fritsch/restore 

again and then just make in your existing folder should be enough.

I'll ping after I updated the PR.

**Comment by fritsch** [comment] 2021-02-23 05:31
Pushed. You can proceed.

**Comment by inf0rmix** [comment] 2021-02-23 07:30
I just want to mention that I have the same problem on my ubuntu 2004 with latest kodi matrix release. HArdware is Thinkpad T560 with intel 915 gfx card.

**Comment by fritsch** [comment] 2021-02-23 08:04
That's nice to hear. I just wanted to ask: does the linked PR helps fixing it?

**Comment by sjuk** [comment] 2021-02-23 15:59
> Okay. My fault. Update will come. I will report back. After that:
> 
> git fetch fritsch
> git reset --hard fritsch/restore
> 
> again and then just make in your existing folder should be enough.

Make stopped at 61%. Please see log. [https://paste.kodi.tv/hevixokixi.kodi](https://paste.kodi.tv/hevixokixi.kodi)

Hint: This time I used another terminal with restriction of row-buffer. But I guess it will be enough rows to find the error.

**Comment by fritsch** [comment] 2021-02-23 18:18
Thanks for testing again :-) Let me set this jenkins "sharp" here. When it's green, please fetch and reset --hard again followed by make.

**Comment by fritsch** [comment] 2021-02-23 18:46
Now, please try again. I had the time to build it locally, it built. If it's working I can't say, as I am not affected

**Comment by inf0rmix** [comment] 2021-02-24 11:22
I hope i have time to build it this evening and test it.

**Comment by sjuk** [comment] 2021-02-24 16:57
> Now, please try again. I had the time to build it locally, it built. If it's working I can't say, as I am not affected

OK then. Kodi + all add-ons successfully built and installed. From now on /usr/local/bin/kodi-standalone will be started on startup. Logging was enabled. Now there is nothing we can do as waiting if the issue occurs again (or not)...

**Comment by inf0rmix** [comment] 2021-02-27 19:31
I did not do any rebuild now, but since yesterday, the bug did not appear again. I didnt change anything apart from reconfiguring my gamepads

**Comment by the-black-eagle** [comment] 2021-02-27 20:27
@fritsch I can test this but it won't be until Monday at the earliest. :)

**Comment by sjuk** [comment] 2021-02-27 23:26
> > Now, please try again. I had the time to build it locally, it built. If it's working I can't say, as I am not affected
> 
> OK then. Kodi + all add-ons successfully built and installed. From now on /usr/local/bin/kodi-standalone will be started on startup. Logging was enabled. Now there is nothing we can do as waiting if the issue occurs again (or not)...

@fritsch The issue did not occur again. Do you need more information?

**Comment by fritsch** [comment] 2021-02-28 06:34
Can you please post a debuglog? I have the feeling you disabled VDPAU support while compiling.

Just so that we can make sure, that was still in use.

**Comment by sjuk** [comment] 2021-02-28 11:53
I would. But paste.kodi.tv (alias: hastebin) always says "document exceeds maximum length" when I try to save debug log with about 29K rows. Is there any information available how many rows it can take. I did not find much information about that on the internet. :-(
Feedback: To be honest, it should be much easier to report issues and help testing a pull request. And if it is needed to manually turn on VDPAU (I am note aware turning it off) you could have told me to before the start of configure and make. ;-)

**Comment by fritsch** [comment] 2021-02-28 13:15
Jep, it should be. Though - the issue you have is in part of kodi which is not at all maintained by anyone on this planet anymore. The only reason I stepped up and tried to help was: That you asked very politely and I though: that guy deserves it, that he gets some help.

**Comment by fritsch** [comment] 2021-02-28 13:15
And before you reconfigure, please do another fetch please.

**Comment by sjuk** [comment] 2021-02-28 16:56
Many thanks for your helpfulness. Please follow the link to the debug log. [https://paste.kodi.tv/heqivekavi.kodi](https://paste.kodi.tv/heqivekavi.kodi) I removed the EPG update part (which added about 27K rows).
I hope that VDPAU was enabled, but I guess not. If not I can compile once again. But I fear I don't know how to enable VDPAU and would be happy if you can share your knowledge with me.

**Comment by fritsch** [comment] 2021-02-28 17:29
Hi, sadly not. you can run cmake again and specifying: 
From kodi directory:
mkdir -p build
cd build
cmake -DENABLE_VDPAU=ON -DAPP_RENDER_SYSTEM=gl ../

You should now see VDPAU enabled in the list (it's quite down in the list).

**Comment by sjuk** [comment] 2021-02-28 18:24
After make uninstall and setting .xinintrc back using /usr/bin/kodi-standalone it turned out I already enabled nighly builds. Perhaps this is already a version of kodi with your code enabled? If not I should try to use the same build instructions used in the regular builds.
![screenshot00000](https://user-images.githubusercontent.com/5033784/109429062-38ffb880-79fa-11eb-852a-9322a280f072.png)

**Comment by fritsch** [comment] 2021-02-28 18:38
For sure not. As the code was never merged into the official kodi repository. We are waiting for your results :-)

With the nightly build your issue should persist.

**Comment by sjuk** [comment] 2021-02-28 18:42
By the way. The uninstall left all kodi add-ons in /usr/local. Is there any chance to "make uninstall" them? I tried that already from kodi and kodi-build folder, but without success.

**Comment by sjuk** [comment] 2021-02-28 19:48
OK, I want to build it once more. But first I need more information to be able do it the one and only right way.

- How do I uninstall the add-ons from /usr/local for cleaning up?
- How do I get all the needed configure and make options to match the ubuntu/debian package?

**Comment by sjuk** [comment] 2021-03-04 22:39
I did some research on how to uninstall the add-ons from /usr/local. I have to use `xargs rm < install_manifest.txt` for every single add-on. This will take some time. On the next try I will only compile really needed add-ons (pvr.hts). If you are interested in where I found the information, here you are.
[https://stackoverflow.com/questions/41471620/cmake-support-make-uninstall](https://stackoverflow.com/questions/41471620/cmake-support-make-uninstall)

**Comment by sjuk** [comment] 2021-03-04 23:32
This clean up took much too long. I did it with two commands in one shot.
`~/kodi/tools/depends/target/binary-addons/native$ find -name install_manifest.txt -exec cat {} >> /home/sjuk/install_manifest_all_add-ons.txt \`

`$ sudo xargs rm < /home/sjuk/install_manifest_all_add-ons.txt`

**Comment by sjuk** [comment] 2021-03-04 23:34
But this only affected the files. I have to find empty directories in the next step...

**Comment by sjuk** [comment] 2021-03-04 23:41
OK then. I removed the following folders.

`/usr/local/share/kodi`

`/usr/local/lib/addons`

`/usr/local/lib/kodi`

I guess it's cleaned up now and I can start with another try to compile.

**Comment by sjuk** [comment] 2021-03-05 00:05
Please follow the link to see the first part including "configure" for informational purpose.
[https://paste.kodi.tv/kifuxejara](https://paste.kodi.tv/kifuxejara)
Next step will be 
`cmake --build . -- VERBOSE=1 -j$(getconf _NPROCESSORS_ONLN)`
and going to sleep. Hopefully tomorrow it was build successfully.

**Comment by sjuk** [comment] 2021-03-05 07:27
kodi and pvr.hts complied successfully. I will test a few days and publish the results here...

**Comment by sjuk** [comment] 2021-03-07 16:36
@fritsch The issue did not occur again. Please follow the link to an kodi.log for more details. [https://paste.kodi.tv/amogetewuh.kodi](https://paste.kodi.tv/amogetewuh.kodi). Please let me know if more information is needed?

**Comment by fritsch** [comment] 2021-03-07 16:41
Thanks very much. We got positive internal reports as well. Therefore I pushed the fix. It will be part of 19.1 and is also part of nightlies already.

Fixed by: https://github.com/xbmc/xbmc/pull/19258

**Closed by fritsch** 2021-03-07 16:41 UTC
Labels: Need more information
