### ISSUE TITLE
[Kodi20] Subtitles not showing after kodi restarts on android devices since recent update

### ISSUE THREAD

**Issue by monsoons** [xbmc/xbmc#21439] opened 2022-05-23 00:23 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

Subtitles(smi and srt type I tested) not visible after restart kodi on android devices.
I should kill kodi app(force stop) before launch kodi to show the subtitles.
I think this is related to the recent update.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Subtitles should be showing.

## Actual Behavior

Subtitles not showing after restart.

### To Reproduce

1. Exit kodi on android devices.
2. Just run kodi again. (Do not kill kodi app before run kodi)
3. Check if subtitles visible.

tested on amazon fire stick tv 4k max and nvidia shield tv pro.

### Debuglog

The debuglog can be found here:
https://github.com/xbmc/xbmc/issues/21439#issuecomment-1134516156

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: android 9 , 11
 - Kodi version: Kodi 20 Nexus

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment] 2022-05-23 00:24
@ksooo maybe some more fallout from the reuse PR?

**Comment by fuzzard** [comment] 2022-05-23 00:32
@monsoons could you try this nightly http://mirrors.kodi.tv/nightlies/android/arm64-v8a/master/kodi-20220511-c19e162b-master-22770-arm64-v8a.apk and let us know if it works as intended?

Thats the nightly before #21385 was merged

**Comment by monsoons** [comment] 2022-05-23 01:32
That build works fine. Tested with smi file again. That's why I mentioned the recent update.

I'll provide debug log later. Thank you.

**Comment by monsoons** [comment] 2022-05-23 01:36
@fuzzard 
That build works fine. Tested with smi file again. That's why I mentioned the recent update.

I'll provide debug log later. I thought you can reproduce easily. Thank you for ur comment.

**Comment by fuzzard** [comment] 2022-05-23 01:41
Thanks for testing. If you could try this nightly as well http://mirrors.kodi.tv/nightlies/android/arm64-v8a/master/kodi-20220513-99a4d44e-master-22791-arm64-v8a.apk
the expectation is that will fail.

Essentially im trying to confirm its fallout from a specific commit for how android handles dylibs. The update you linked has nothing to do with the failure. Different authors, so need to contact different people depending on the fault.

**Comment by monsoons** [comment] 2022-05-23 01:53
> Thanks for testing. If you could try this nightly as well http://mirrors.kodi.tv/nightlies/android/arm64-v8a/master/kodi-20220513-99a4d44e-master-22791-arm64-v8a.apk the expectation is that will fail.
> 
> Essentially im trying to confirm its fallout from a specific commit for how android handles dylibs. The update you linked has nothing to do with the failure. Different authors, so need to contact different people depending on the fault.

Thank you. I have deleted the link to avoid confusion. I'm outside so I cannot test right now. I'll test that build and give yoy feedback later.

**Comment by monsoons** [comment] 2022-05-23 10:19
@fuzzard 220513 build works fine. I found this issue begins at 220515 build.

I've tested many subtitles and I found ass type subtitles visible while srt and smi subtitles are not visible until force stop kodi before restart.

**Comment by monsoons** [comment] 2022-05-23 10:48
@fuzzard Here is a log file of 220515 build. The test file name is "test1.mkv" and subtitles are "test1.smi" and "test1.srt".

I killed kodi app and started and open test file. Subtitles worked fine. Then exited kodi, restarted without killing kodi(forced stop) and opened same test file. But this time subtitles not visible.

**Comment by ksooo** [comment] 2022-05-25 12:36
@thexai is reverting https://github.com/xbmc/xbmc/commit/196c11defca96e0f7819a5f1d7c7a05e2dcda0fe necessary to fix the issues above or is reverting only  https://github.com/xbmc/xbmc/commit/086ea08740bdf8427c7ee590425f462ab701c92a sufficient?

**Comment by thexai** [comment] 2022-05-25 12:48
The two commits since https://github.com/xbmc/xbmc/commit/196c11defca96e0f7819a5f1d7c7a05e2dcda0fe have caused other side effects afterwards. 
In any case, if https://github.com/xbmc/xbmc/commit/086ea08740bdf8427c7ee590425f462ab701c92a is reverted, https://github.com/xbmc/xbmc/commit/196c11defca96e0f7819a5f1d7c7a05e2dcda0fe is no longer needed.

**Comment by ksooo** [comment] 2022-05-25 12:50
> since https://github.com/xbmc/xbmc/commit/196c11defca96e0f7819a5f1d7c7a05e2dcda0fe have caused other side effects afterwards.

 @thexai can you say which ones exactly?

**Comment by thexai** [comment] 2022-05-25 12:50
Micro-stuttering when OSD is visible and more perceptible effect in the transitions OSD off --> on / on --> off

**Comment by ksooo** [comment] 2022-05-25 13:43
@Fuzzard I will not have the time to debug / fix this during the next days. My feeling is, that reason for the stuttering is something related to OpenGL reinit not working properly - something I have no clue how to debug/fix this, if even possible for us to fix.

So, fine by me if we revert the two above mentioned commits before we release Alpha 2.

**Comment by ksooo** [comment] 2022-05-25 16:02
@thexai I tried hard, but cannot reproduce any stuttering issues. Can you provide step-by-step instructions how to reproduce, please? I assume you tested on Nvidia Shield? Which hardware exactly, which Android version? Do you have a log proofing the stuttering issue?

**Comment by fuzzard** [comment] 2022-05-25 17:08
> @fuzzard I will not have the time to debug / fix this during the next days. My feeling is, that reason for the stuttering is something related to OpenGL reinit not working properly - something I have no clue how to debug/fix this, if even possible for us to fix.
> 
> So, fine by me if we revert the two above mentioned commits before we release Alpha 2.

No worries, I'll prepare a revert PR for those 2 commits. Maybe some day down the line we revisit this again and see if we can work out a solution

**Comment by ksooo** [comment] 2022-05-25 18:20
> Why all issues go away by reverting those two commits?

You could help to answer this. Log files for both cases, with and without the commits could possibly tell. As I said; i cannot reproduce any stutter, very similar setup here. I asked you for step-by-step instructions for reproduction of the issues.

**Comment by ksooo** [comment] 2022-05-25 18:23
@fuzzard please revert only https://github.com/xbmc/xbmc/commit/086ea08740bdf8427c7ee590425f462ab701c92a, until there is proof that  https://github.com/xbmc/xbmc/commit/196c11defca96e0f7819a5f1d7c7a05e2dcda0fe alone causes any regression. I want some proof for this.

**Comment by thexai** [comment] 2022-05-25 18:33
I'm sorry but until the weekend I don't have time to do all this. Anyway sooner or later someone will open another issue for stuttering.

**Comment by ksooo** [comment] 2022-05-25 22:43
@monsoons I can reproduce the problem with subtitles not rendered on Kodi "warm" boot (second+ start without force quit). So far, I don't have a clue what exactly causes the issue.

**Comment by ksooo** [comment] 2022-05-26 22:37
Update: I found the root cause for the subtitles bug. Now I can think about the right fix.

**Closed** 2022-05-27 19:58 UTC
Labels: Platform: Android, Triage: Confirmed, v20 Nexus, Component: Subtitles
