### ISSUE TITLE
Cannot remove Audiobook from Kodi

### ISSUE THREAD

**Issue by NoralK** [xbmc/xbmc#25618] opened 2024-08-15 21:33 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

There is no way to remove an Audiobook once scanned into the music library.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

There should be a menu choice for "Manage" then "Remove from Library"

## Actual Behavior

No way to remove

## Possible Fix

New menu choice for "Manage" then "Remove from Library"

### To Reproduce

1.  Scan an Audiobook
2.  Bring up submenu
3.  Only information for playing and information

### Debuglog

The debuglog can be found here:
N/A

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ X ] Linux
 - [ ] macOS
 - [ X ] Windows
 - [ ] Windows UWP

 - Operating system version/name:  LibreELEC v12.0 and Windows 11
 - Kodi version: v21.0 Omega

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment] 2024-08-16 05:00
Closing as not a bug. 

Music library works differently to the Video library. 
See... https://kodi.wiki/view/Update_Music_Library#Remove_Music

**Closed by KarellenX** 2024-08-16 05:00 UTC
Labels: Triage: Needed
