### ISSUE TITLE
Skin Shortcuts menu cannot be created

### ISSUE THREAD

**Issue by sulfatchlorid** [xbmc/xbmc#20576] opened 2021-11-24 13:52 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

Soon after starting kodi a popup appears with the error message "Skin Shortcuts menu can't be created".
I use the Amber skin so i thought maybe if i switch to another skin (Estuary) it would work but the error messaage appears again.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

No error message should appear after starting kodi

## Actual Behavior

Error Message appears

### To Reproduce

1. start kodi
2.
3.

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/aciwesirov

### Screenshots 
Here are some links or screenshots to help explain the problem:

I can't make a screenshot with the remote control

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I have to click on ok very often and send or not send a bug report...

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Coreelec 19.3
 - Kodi version: 19.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by bartolomesoriano** [comment] 2021-11-24 14:27
@sulfatchlorid , there is a known issue with skinshortcuts and Amber.  Until the issue is fixed in skinshortcuts, please revert back to version 1.1.5.  Thanks

**Comment by sulfatchlorid** [comment] 2021-11-24 15:09
Thanks you very much for the quick help

**Comment by enen92** [comment] 2021-11-24 16:22
Please keep python add-on issues in the forum or bring them to the developer of the add-on. This repo is for tracking Kodi core issues

**Closed by enen92** 2021-11-24 16:22 UTC
