### ISSUE TITLE
SMB 3 Encryption

### ISSUE THREAD

**Issue by sgreiner** [xbmc/xbmc#20383] opened 2021-10-24 06:46 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

I am running Kodi on Nvidia Shield TV which is an Android TV. There I am mounting a SMB 3 Share from my QNAP (QTS 5) and I am using SMB 3 as minimal version. When I enable SMB 3 Encryption on the share I can no longer watch a movie without it stuttering every view seconds. Basically every video stream over 2 MB/s will stutter. When not forcing the SMB 3 Encryption the video is played back normal, event with material with 25 MB/s works normal. 
My Windows 11 can upload and download data to this share with ~115 MB/s when SMB encryption is enabled/forced.

Apart from that thank you all for the great work on the project.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I expect to enable SMB 3 Encryption and have a video played without lags and stuttering and waiting for it to load.

## Actual Behavior

The video stops every 5 seconds and buffers for 10 seconds.

## Possible Fix

Use a modern smb library which is using AES-NI hardware acceleration.

### To Reproduce

1. mount SMB 3 Share
2. make sure to enforce SMB Encryption
3. make sure to use 5Ghz WLAN or 1gbit LAN to not have a bottleneck here
4. playback a 4k video from that network share

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: ShieldTV 8.2.3
 - Kodi version: 19.2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by jkommeren** [comment] 2021-11-15 17:18
Having similar problems, connected via LAN. 4k is buffer fest. 

Only fix for me was downgrading back to 18.9

Perhaps this is fixed in 19.3 though?

**Comment by DaVukovic** [comment] 2021-11-16 01:04
Would be interesting to see the CPU load while the movie is playing and SMB3 encryption is enabled. Decryption is always done in CPU and I highly guess the CPU is at 100% during the playback with SMB3 encryption enabled. 

Also the 4k movie might not use hardware acceleration. So if both is done in CPU, then I would expect stutters as well. 

@sgreiner can you please try to play a non-4k movie with encryption enabled and confirm if this works. Also please share logfiles for both (4k and non-4k playback) circumstances. We will need logs to help you

**Comment by CaseyBakey** [comment] 2021-12-07 07:49
Hello there, I can confirm the same issue there.

I was streaming a quite heavy 4K HDR mkv file (~5Go for 30min playback) from my NAS to Nvidia Shield Pro 2019.

Only ethernet 1Gb/s between the two, no WiFi.

I never encountered such stuttering during streaming/playback so at first I thought that was the issue was the HDR (noob thoughts).

After reading many different forums, I wanted to directly mount the share to Android system (there is such an option on Nvidia Shield), and play "locally" with other apps than Kodi, like Just Player. People said that could work.

The smb implementation of the Shield is quite shitty, you can't just give IP, name of the share, user & pass. The smb client WILL reverse Netbios the IP to confirm share before mounting. I didn't have netbios enabled on my NAS.

Fast forward: I enable Netbios/nmbd, try to mount share, and nothing can mount (but I see that the Shield is talking to my NAS, via tcpdump).

After few thoughts, I disabled SMBv3 signing/encryption on my NAS, and the Shield was able to mount the share.

So I did some "local" playback test of the incrimining files:
- Just Player: perfect playback, no stutter
- Kodi on the locally mounted share (by Shield smb client): perfect playback, no stutter
- Kodi using its smb client: perfect playback, no stutter ?!?!?!

So I undestood the culprit was SMBv3 encryption.

I did connect to shield with ADB and checked 
CPU usage with top, while playing the file via Kodi and its smb client:
- when no encryption: 10~15% CPU
- when encryption is enabled: 95~115% CPU !

So yes, I think the SMBv3 traffic decryption on Kodi could take advantages of the hardware accelerated instructions (AES-NI for x86/x86_64 and equivalent for the ARMv8-A architecture).

I'll leave encryption disabled for now ;-)

**Comment by zaltysz** [comment] 2021-12-12 19:27
My phone and tablet max out at around 1MB/s while using encrypted SMB in Kodi. However, they reach 30MB/s over HTTPS.

Problem might be Kodi currently is using library from Samba 4.11. Samba was kinda bad with crypto perf (especially where hw acceleration mattered) until 4.12 when it fully switched to GnuTLS for crypto.

**Comment by fonic** [comment] 2022-02-26 17:14
Man, I'm glad I found this issue! I was on the verge of throwing my network equipment in the trash as I just couldn't figure out why my NVIDIA Shield TV would max out at ~2MB/s throughput. I would've never guessed this is caused by Samba encryption. 

Hope this gets fixed in the future. Until then, I kinda feel there should be a warning message when Kodi notices Samba encryption is enabled when accessing shares.

**Comment by sgreiner** [comment] 2022-06-17 16:28
@DaVukovic unfortunately I don't have access to the log files, but I am 100% sure https://github.com/xbmc/xbmc/issues/20383#issuecomment-987657020 describes the problem perfectly.
"So yes, I think the SMBv3 traffic decryption on Kodi could take advantages of the hardware accelerated instructions (AES-NI for x86/x86_64 and equivalent for the ARMv8-A architecture)."

**Comment by fonic** [comment] 2022-08-12 14:44
@DaVukovic:
Since the OP doesn't seem to be able to provide the requested logs I'll offer my assistance as I'd really like to see this fixed.

**I performed two runs:**

1. Samba encryption disabled
2. Samba encryption enabled

In each run, I let Kodi play the same part of the same video for about 60s, then I randomly seek through the video for another 60s.

Client: NVidia Shield TV Pro (2019), Android 11, Kodi 19.3 (installed from Google Play Store)
Server: Linux, Kernel 5.10, Samba 4.15.7
Video: ~22GB size, 3840x1600, 24 fps, HEVC

---

**Run 1: Samba encryption disabled**

Client CPU load during playback:
![run1_no_enc_client_cpu_load_playback](https://user-images.githubusercontent.com/14027079/184377457-b88acafd-7493-4c5e-ac74-16f82ee01b5b.png)

Client CPU load during random seek:
![run1_no_enc_client_cpu_load_seek](https://user-images.githubusercontent.com/14027079/184377468-b6ddcf93-6520-41c9-9ba8-bd68a1bcf566.png)

Server network load (first peak = start of playback, following peaks = seeking):
![run1_no_enc_server_network_load](https://user-images.githubusercontent.com/14027079/184377483-7cb732d5-f69f-4436-9ba6-6bc4a9d16c14.png)

Client `kodi.log`:
[run1_no_enc_client_kodi.log](https://github.com/xbmc/xbmc/files/9319414/run1_no_enc_client_kodi.log)

---

**Run 2: Samba encryption enabled**

Client CPU load during playback:
![run2_enc_client_cpu_load_playback](https://user-images.githubusercontent.com/14027079/184377485-e0e2e206-e4f8-46ff-b679-5ad5136c18b8.png)

Client CPU load during random seek:
![run2_enc_client_cpu_load_seek](https://user-images.githubusercontent.com/14027079/184377487-9ed9f94d-5d27-463e-945d-08f682a2e18d.png)

Server network load:
![run2_enc_server_network_load](https://user-images.githubusercontent.com/14027079/184377489-2af6a01a-2e83-4dd4-9c98-2ead739a29cd.png)

Client `kodi.log`:
[run2_enc_client_kodi.log](https://github.com/xbmc/xbmc/files/9319429/run2_enc_client_kodi.log)

**Comment by fonic** [comment] 2022-08-17 14:53
I just noticed that this has been fixed in Kodi v20 Nexus. Would have been great to have gotten feedback on that here, then I wouldn't have bothered testing and supplying logs. What a gigantic waste of time.

**Comment by lrusak** [comment] 2022-08-17 15:24
> I just noticed that this has been fixed in Kodi v20 Nexus. Would have been great to have gotten feedback on that here, then I wouldn't have bothered testing and supplying logs. What a gigantic waste of time.

What exactly do you think got fixed? And what fixed it?

**Comment by fonic** [comment] 2022-08-17 15:36
> What exactly do you think got fixed? And what fixed it?

This issue got fixed in Kodi v20 Nexus. Meaning that SMB3 encryption no longer maxes out at ~2 MB/s on the NVIDIA Shield TV. And I don't just _think_ that, I tested it.

As to _what_ it fixed, only Kodi developers can answer that. I'd say v20 uses a newer Samba version (see this [comment](https://github.com/xbmc/xbmc/issues/20383#issuecomment-991956263)).

**Comment by lrusak** [comment] 2022-08-17 16:16
> > What exactly do you think got fixed? And what fixed it?
> 
> 
> 
> This issue got fixed in Kodi v20 Nexus. Meaning that SMB3 encryption no longer maxes out at ~2 MB/s on the NVIDIA Shield TV. And I don't just _think_ that, I tested it.
> 
> 
> 
> As to _what_ it fixed, only Kodi developers can answer that. I'd say v20 uses a newer Samba version (see this [comment](https://github.com/xbmc/xbmc/issues/20383#issuecomment-991956263)).

Ok, well what likely fixed it was a version bump to the samba library. It's not really possible to know (and it wasn't bumped in response to a bug).

So good news that the issue is fixed for you.

Possible commits where it got fixed:
321b8da96fc08da2236819a3f0cae3e3f5834c28
b8813fbc885ccda592247f621091eac995ad56c4
0229bac8d9ab2b26d4ef4d572f9c9abc8c493b4b

**Comment by fonic** [comment] 2022-08-17 16:26
> Ok, well what likely fixed it was a version bump to the samba library. It's not really possible to know (and it wasn't bumped in response to a bug).
> 
> So good news that the issue is fixed for you.
> 
> Possible commits where it got fixed: [321b8da](https://github.com/xbmc/xbmc/commit/321b8da96fc08da2236819a3f0cae3e3f5834c28) [b8813fb](https://github.com/xbmc/xbmc/commit/b8813fbc885ccda592247f621091eac995ad56c4) [0229bac](https://github.com/xbmc/xbmc/commit/0229bac8d9ab2b26d4ef4d572f9c9abc8c493b4b)

It should be b8813fbc885ccda592247f621091eac995ad56c4 then (Samba 4.11.x -> 4.12.x) judging from [this news piece](https://www.phoronix.com/news/SMB3-Faster-Encryption-Samba).

While it is good news, Kodi v20 is still alpha, so the issue will remain until it is stabilized. But it's good to know that it's just a matter of time now.

Well, it would seem the time spent wasn't entirely wasted in the end since we were now able to clear things up a bit.

**Closed** 2023-04-04 11:39 UTC
