### ISSUE TITLE
Kodi hangs at splash screen

### ISSUE THREAD

**Issue by candrews** [xbmc/xbmc#16058] opened 2019-05-04 01:10 UTC
### Describe the bug
Starting Kodi with a clean profile (no `~/.kodi` directory exists) results in Kodi hanging at the splash screen. The Kodi logo just stays on there, never progressing to the Kodi UI.

I'm not sure what changed; nothing sticks out to me. Kodi used to work, and now it doesn't. As previously mentioned, I tried with a clean profile and the behavior did not change.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should proceed from the splash screen to the UI.

## Actual Behavior

Kodi hangs on the splash screen forever. I left it for 4 hours on the splash screen and it never changed.

### To Reproduce

1. Start kodi

### Debuglog

The debuglog can be found here:

https://pastebin.com/eujmMinX

### Screenshots 
Here are some links or screenshots to help explain the problem:

It's just the Kodi "v19.0 M*****-alpha" splash screen that we all know and love :)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Linux
X Windows
Intel graphics

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Gentoo Linux
 - Kodi version: master, ae31c4f

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by candrews** [comment] 2019-05-04 02:55
I just made an important discovery - this only happens if peripheral.joystick is installed.
With peripheral.joystick, it hangs.
Without peripheral.joystick, it works fine.

I also noticed that this issue has been reported at https://github.com/xbmc/peripheral.joystick/issues/168

**Comment by DaVukovic** [comment] 2019-05-04 07:16
I can confirm the issue. 

I'll llet this one open until the issue is fixed at the binary add-on.

**Comment by Paulemann** [comment] 2019-05-04 08:21
I was the one who reported the issue at [xbmc/peripheral.joystick#168](url) and can confirm it also occurs with latest build of kodi 18 Leia on Ubuntu 18.04. I can eventually start kodi after removing peripheral.joystick from /usr/local/lib/kodi/addons directory. Here is my debug log
[https://paste.kodi.tv/raw/ibiqaqezas](url)

**Comment by iz8mbw** [comment] 2019-05-04 10:59
On Android (Nvidia Shield) happens also that Kodi does not close correctly and after confirming the exit it remains freezed. Always I'm forced to close by killing app in Android. With Kodi v19 20190502 the problem is not there.

**Comment by ksooo** [comment] 2019-05-04 11:41
> On Android (Nvidia Shield) happens also that Kodi does not close correctly and after confirming the exit it remains frozen.

 Same here. 100% reproducible.

**Comment by DaVukovic** [comment] 2019-05-04 14:38
fixed by: https://github.com/xbmc/peripheral.joystick/pull/169

**Closed by DaVukovic** 2019-05-04 14:38 UTC
Labels: Component: Binary add-ons, Triage: Confirmed, v19 Matrix

**Comment by ksooo** [comment] 2019-05-04 15:24
Confirming that https://github.com/xbmc/peripheral.joystick/pull/169 also fixes the freeze on exit.

**Comment by iz8mbw** [comment] 2019-05-04 15:25
Yes

**Comment by ksooo** [comment] 2019-05-04 15:30
I was not asking, I was stating.

**Comment by iz8mbw** [comment] 2019-05-04 15:33
I was also confirming
