### ISSUE TITLE
/usr/bin/kodi: line 219: 61779 Segmentation fault (core dumped) ${KODI_BINARY} $SAVED_ARGS

### ISSUE THREAD

**Issue by homocomputeris** [xbmc/xbmc#17483] opened 2020-03-11 19:29 UTC
### Describe the bug
Segfault when playing a HEVC video

## Expected Behavior
Play the video

## Actual Behavior
Segfault

### To Reproduce

1. Play a file

### Debuglog

The debuglog can be found here: https://paste.kodi.tv/gihetojone.kodi

Crash log: https://paste.kodi.tv/otodevecel.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 Arch: x86_64
 Kernel: Linux 5.5.8-zen1-1-zen #1 ZEN SMP PREEMPT Fri, 06 Mar 2020 00:57:35 +0000
 Release: Arch Linux
 - Kodi version: 18.6 Git:20200229-nogitfound Media Center Kodi

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment] 2020-03-11 19:31
Would be nice if you could provide a stack trace otherwise it's impossible to know where it crashes.

**Comment by lrusak** [comment] 2020-03-11 19:32
You should also test against Kodi master to see if the issue is still there

**Comment by lrusak** [comment] 2020-03-11 19:32
It looks to me like it might have to do with cms which I believe was fixed in Kodi master

**Comment by homocomputeris** [comment] 2020-03-11 19:35
> Would be nice if you could provide a stack trace otherwise it's impossible to know where it crashes.

How do I force Kodi to write stacktrace? I've got gdb but the stacktrace doesn't appear.

**Comment by lrusak** [comment] 2020-03-11 19:41
if you run Kodi in gdb
```
gdb --args kodi
thread apply all bt
run

<make Kodi crash>

bt
```


seems like it's not git master
> 2020-03-11 22:23:11.333 T:139621904893312  NOTICE: Starting Kodi (18.6 Git:20200229-nogitfound). Platform: Linux x86 64-bit

**Comment by homocomputeris** [comment] 2020-03-11 19:55
In gdb it does not crash, rather freezes
https://paste.kodi.tv/itivejikeg

**Comment by lrusak** [comment] 2020-03-11 19:57
Try building git master and see if it still crashes (or try disabling cms in Kodi and it shouldn't crash)

**Comment by homocomputeris** [comment] 2020-03-12 07:02
I've built e366adc3726. It does not crash, but also does not show any video, only sound.

**Closed** 2020-03-12 08:58 UTC
Labels: Triage: Needed
