### ISSUE TITLE
Washed out colors when playing UHD HDR content on non-HDR 1080p TV with FireTV Stick 4k Max

### ISSUE THREAD

**Issue by ksa-real** [xbmc/xbmc#20695] opened 2021-12-17 23:33 UTC
### Describe the bug
I have a video in mkv container: UHD/4k, 24hz, BT2020. An example is here: https://4kmedia.org/the-world-in-hdr-uhd-4k-demo/. If I try to play it with Kodi 19.3 sideloaded onto Amazon 'Fire TV Stick 4k Max' on Samsung UN65F7100 (1080p, non-HDR), then colors look washed out / bleak, like overexposed. I think HDR tone mapping doesn't work.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Colors should approximately like non-hdr version of the same content.

## Actual Behavior

Washed out colors on non-HDR equipment.

### To Reproduce

1. Just open a sample video in Kodi in similar to mentioned setup.

### Debug log

Will add a bit later

### Screenshots 
Here are some links or screenshots to help explain the problem:

Common "washed out colors" looks. I don't have pictures but the link demonstrates the issue: https://forum.videolan.org/viewtopic.php?t=146582

Firestick HDR content on HDR TV (TV switches to HDR10 as expected):
![Firestick HDR content on HDR TV](https://user-images.githubusercontent.com/8188774/146630074-a6d02ae6-a41d-49cc-8ff1-3db6c9c271c0.jpg)

Firestick SDR content on SDR TV:
![Firestick SDR content on SDR TV](https://user-images.githubusercontent.com/8188774/146630081-8113c8c1-f436-4f9c-b829-f0bb8545ecb3.jpg)

Firestick HDR content on SDR TV:
![Firestick HDR content on SDR TV](https://user-images.githubusercontent.com/8188774/146630079-26bda726-59d7-4a0a-8832-47fa8de80a37.jpg)

Chromecast HDR content on SDR TV:
![Chromecast HDR content on SDR TV](https://user-images.githubusercontent.com/8188774/146630076-e4d6e443-3c4f-4608-81df-5223a3719ac9.jpg)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I have found likely related discussion for Plex here: https://www.reddit.com/r/fireTV/comments/qjstho/stick_4k_max_disable_hdr_option/. 

The ask is to check if this may be controlled on Kodi side.

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Fire OS 7.2.5.5 (PS7255/2465)
 - Kodi version: 19.3

**Comment by quietvoid** [comment] 2021-12-17 23:56
This is expected, the FireTV Stick 4K is not recognized as HDR capable because it's missing the EGL extensions.

**Comment by ksa-real** [comment] 2021-12-17 23:58
Both FireTV Stick 4k and FireTV Stick 4k Max?

**Comment by ksa-real** [comment] 2021-12-18 00:00
Also please note that HDR content is played correctly with Kodi on HDR-TV.

**Comment by quietvoid** [comment] 2021-12-18 00:01
The FireTV Stick 4K Max should pass the HDR test, but it only advertises support for one of the 2 required extensions.
A workaround has been added in Kodi 20 to recognize the new model as HDR capable.

However I'm not sure tonemapping is supported because of the still missing extension.

**Comment by ksa-real** [comment] 2021-12-18 00:19
I tried to check the Firestick media info on-screen display (DevTools Menu -> Advanced Option ON). It shows Hardware Accelerated hevc, 4k, BT2020. Colors are washed out with both Adaptive and Disabled HDR. Am I right, that this means the content is passed through to Firestick and the way it is mapped from HDR to SDR is out of Kodi control and totally in control of FireOS/Driver? Effectively nothing can be done on Kodi side.

**Comment by quietvoid** [comment] 2021-12-18 00:36
On the 4K Max, the MediaCodec info does show BT2020 but the content definitely looks like it is tonemapped to SDR.

**Comment by ksa-real** [comment] 2021-12-18 00:38
Do you mean you see it correctly tone-mapped to SDR?

**Comment by quietvoid** [comment] 2021-12-18 00:39
Yes.

**Comment by ksa-real** [comment] 2021-12-18 05:33
I've added screenshots demonstrating the issue. I have 2 samples: low quality SDR, and high quality HDR. I've played them with Kodi 19.3 on Firestick 4k Max and Chromecast with Google TV. Both Chromecast and Firestick played HDR on SDR with visually incorrect colors: red is pretty washed out on pictures.

**Comment by mdrbill** [comment] 2021-12-27 12:23
I have also the same issue it's even worse green, see image, this image is supposed 
to be blue and HDR is disabled on 1080P tv wiht 4K max

![image](https://user-images.githubusercontent.com/44754079/147471412-e75820e9-098d-42cc-b1ee-e3ddb0ce13a3.png)

**Comment by krahl** [comment] 2021-12-30 22:45
Just wanted to add that I have both the Fire TV Stick 4k and 4k Max. I am currently not using the 4k Max because of this issue. The 4k does not have this tone mapping issues and is converting HDR to SDR properly.

Debug Info one can display shows BT2020_8_HD10 on the 4k but BT2020 on the 4k Max. Hope Amazon fixes this!

**Comment by McFL7** [comment] 2022-01-25 23:48
Hi, 

I have same issue with washed out colors on my new FireStick 4K Max on Kodi with 4k UHD contents. I don't have that issue on my old Firestick 4k. Tried all settings, Always HDR, Adaptive, No HDR, RGB, YCbCr. 
It appears to be present only on Kodi not on Netflix or other streaming apps i use.

Anyone find out a solution or a workaround to that issue, will be helpful or else i will have to return back the 4K MAX and keep my old Firestick 4K even if it is slower.

Thanks for help

**Comment by fritsch** [comment] 2022-01-26 18:23
Disable Mediacodec Surface (keep only mediacodec) and hope that our GL color converting works performant enough. Other than that: really open a ticket with amazon. MediaCodec Surface is a black box ... we just enable it and let it do all the rest (simplified spoken).

**Comment by ksa-real** [comment] 2022-01-27 14:35
> Disable Mediacodec Surface (keep only mediacodec) and hope that our GL color converting works performant enough. Other than that: really open a ticket with amazon. MediaCodec Surface is a black box ... we just enable it and let it do all the rest (simplified spoken).

Do you have an idea where I can file that, by any chance? So far I've reported to Amazon Customer support but don't have faith in them filing the actual ticket against the Fire Stick Team.

**Comment by McFL7** [comment] 2022-01-30 06:08
I have also called Amazon support for that issue on Kodi, VLC,...and the guy told me that this is a known problem of 4K to SDR colors tone mapping, also that my case will be linked to the current bugreport. We need to wait for the next upcoming FireTV update(s?). 

The only thing is that they don't give much details, what is the updates roadmap, hotfixes of Fire TV OS ? I don't they don't release updates so often, is there a beta program we can register to get that fix quickly ?

**Comment by fritsch** [comment] 2022-01-30 07:53
We are not amazon and have no idea about what they are doing. Keep in mind: kodi is definitely not the use-case they designed their device for. It's meant to play amazon content, best content that you buy on top.

Good thing here: Their own content might be affected as well.

**Comment by Gri61** [comment] 2022-02-07 11:12
Maybe someone will help! i use 4k max
and I have the same problem with displaying color on SDR TV.
Vimu player helps me! turn off HDR on the stick and set the display to 10 bits, and in Vimu select engine v.2 + tunneling ! will work))

**Comment by McFL7** [comment] 2022-02-07 15:49
Do the fix apply only on videos played on Vimu or will it apply these settings to other players like Kodi ? Kodi has lot more features, custom skins, streaming TV, ... Is same fix possible in some hidden Kodi settings ?

**Comment by McFL7** [comment] 2022-06-17 20:29
Hi guys,

Just to inform you that latest firmware release 7.2.8.5 of Firestick 4K Max (firestick 4k don't have that issue), that i got just today has totally fixed the HDR Tone mapping issue on kodi and other pplayers. The colors are no more washed out when playing HDR contents on FullHD SDR TVs or Projectors (like in my case). thanks Amazon Devs. You heard our complains... after many support cases, including mine, i guess.

Guys, force an update on your Firesticks and tell us if it fixed the issue too on your devices.


![IMG_20220617_222249](https://user-images.githubusercontent.com/98433855/174396964-b0ed2a65-cb9c-4b1a-976b-b1ffe44c9d69.jpg)

Regards

**Comment by krahl** [comment] 2022-06-18 08:23
Thanks for the update, @McFL7! Just updated my Fire TV 4K Max to 7.2.8.5. Unfortunately it still looks washed out to me. And it also still shows BT2020_10_HDR10 as color standard in developer menu. While it is BT709_8_SDR for SDR content.

Can you check what it displays for you?

**Comment by McFL7** [comment] 2022-06-18 11:23
Hi,

I saw that change too about BT2020 changed to BT2020_10_HDR however i noticed that thing was already changed in previous firmware 7.2.7.9 but it never fixed the washed colors issue.

However, I noticed that even with that last version 7.2.8.5, the colors are not so vivid as on Firestick 4K (my comparaison reference) also the image is a bit darker even if not with washed out colors. The solution i have found to get almost same result as the old Firestick 4K is to force the HDR in the FireOS settings and increas the color depth to 12bits. Also, i don't know if it matters, but in my case i am also using an HDMI 4K 2x4 Matrix switch between the firestick and the FullHd projector (it support 4k input), so it tricks the firestick 4k max as if it is plugged to a 4K and HDCP compatible TV. Below a picture of my current firestick settings.

If you could also share a picture of your TV paused on the Guepard of the reference video "The World in HDR 4k Demo" i used here, so we will have a common reference image to compare.on.

![IMG_20220618_132149](https://user-images.githubusercontent.com/98433855/174435387-116e1f85-ab5d-4a66-9da4-020711dfdf90.jpg)

**Comment by ksa-real** [comment] 2022-06-18 11:33
The issue is definitely still available. I cannot tell if the colors were somewhat fixed, but they are definitely more bleak compared to the SD variant.

**Comment by McFL7** [comment] 2022-06-18 11:50
Sadely for me too, i just rebooted my Firestick, the issue is back again, colors are again washed out, i don't understand what is happening with that device 🤯🤬

![Uploading IMG_20220618_135019.jpg…]()

**Comment by ksa-real** [comment] 2022-06-18 11:57
I wonder what the abbreviation means: BT2020_**10**_HDR10. Should it be BT2020_8_HDR10 ??? I don't have non-max Firestick 4k anymore to check...

**Comment by McFL7** [comment] 2022-06-18 12:13
I don't have it too anymore to compare. Sold it.

**Comment by McFL7** [comment] 2022-06-18 15:19
i was happy too fast 😭 after a reboot of the Firestick 4K Max the washed colors are back again, can't explain how an update to 7.2.8.5 without rebooting fixed it temporarely. i was able able last night to see a whole 4K HDR movie from my disk without issue. After a reboot today, the issue is back again. I suspect some HDMI HDR compatibility detection problem.

**Comment by Gri61** [comment] 2022-06-18 23:07
What kind of projector do you have? Maybe the projector does not support HDR? On Fire TV Max, you forced to display the picture in HDR! Put in the setting up to 10 bits and adaptive! 12 bit is Dolby Vision!

**Comment by Gri61** [comment] 2022-06-18 23:07
What kind of projector do you have? Maybe the projector does not support HDR? On Fire TV Max, you forced to display the picture in HDR! Put in the setting up to 10 bits and adaptive! 12 bit is Dolby Vision!

**Comment by Gri61** [comment] 2022-06-18 23:22
I solved all my issues related to Amazon fire tv max! I just bought a Nvidia Shield tv pro)))))

**Comment by ksa-real** [comment] 2022-06-18 23:24
@Gri61 Projector is obviously non-HDR. This whole issue is about being able to correctly play the HDR content on a non-HDR display. I think @McFL7 was trying to make a tone mapping on an external device rather than on Firestick. I don't think it worked that way though. I'd expect 'Always HDR' to be ignored during destination capabilities negotiation. 'Always HDR' makes sense when you have SD content and HDR sink, so you can allow SD to be  "upcolored" by the stick or by the display.

**Comment by Gri61** [comment] 2022-06-18 23:31
Understood! It's funny that Amazon max does not know how to convert HDR to SDR. But for that, Dolby Vision in SDR I did it))))

**Comment by Gri61** [comment] 2022-06-18 23:51
![IMG_20220619_023734](https://user-images.githubusercontent.com/97137693/174460427-89a389aa-f3ad-418d-bff2-835847db3a54.jpg)
![IMG_20220619_024143](https://user-images.githubusercontent.com/97137693/174460430-4a3cf2cb-a82f-4c77-b302-742686c17a58.jpg)
![IMG_20220619_024423](https://user-images.githubusercontent.com/97137693/174460432-2f3bfc74-cebf-4f59-8f5c-e3cbaf8a5c8e.jpg)
![IMG_20220619_024355](https://user-images.githubusercontent.com/97137693/174460433-358745d1-b08c-4394-a518-5511624c8771.jpg)
![IMG_20220619_024315](https://user-images.githubusercontent.com/97137693/174460435-a723048b-0465-40aa-b5f3-db2c6e6efd63.jpg)
![IMG_20220619_024219](https://user-images.githubusercontent.com/97137693/174460436-2f494925-4a2f-4bdf-9e86-f4abfa2e4d27.jpg)

**Comment by McFL7** [comment] 2022-06-19 15:44
@Gri61 thanks for the update and pictures. vimu player is not an option for me as i use kodi with few addons for 4k content streaming, which most of time is with HDR metadatas, also i don't want to implement a remote server for vimu app. So the HDR ToneMapping need to be on Kodi player.

Also, i am not trying to do Tone Mapping on an external device. the hdmi Switch i use to route signal to both my FullHD TV and video projector is not the cause of that issue. Even with a direct connect of the Firestick to the Videoprojector or TV gives me same results, HDR contents with washed out colors. 

I am guessing that VIMU player fixed the issue because of some transcoding or HDR metadatas deleted by the Vimu server at first.

**Comment by McFL7** [comment] 2022-06-19 16:14
This is a call to @kodi devs,

I know the vidéo decoding is completley hardware dependent and not related to Kodi, but could you implement on Kodi the same trick Vimu player uses on (Engine2+Tunneling) to do HDR Tone Mapping for those with SDR/1080p TVs or Projectors ?

**Comment by Gri61** [comment] 2022-06-19 18:31
I'll try it on Kodi. If I find out something, I'll definitely write to you! And so I started using Nvidia)))
![IMG_20220619_212418](https://user-images.githubusercontent.com/97137693/174495380-91b869ca-b82a-4b3e-9df3-629d328bc2b5.jpg)

**Comment by ANONIMNIQ** [comment] 2023-03-30 11:53
Hi guys. What is the best tv box/dongle with HDR to SDR tone-mapping? I know bout Nvidia Shield but it's beyond my budget. What about Chromecast with Google TV? Firestick 4K (non MAX version)? Recommend me something, I have big 4K HDR library on my Plex server but I don't have plex pass to use HDR tone-mapping feature in Plex, so I need some other solution. I can stream movies on Kodi with plex addon to my 1080p projector.

**Comment by fjagerva** [comment] 2023-05-14 06:39
No solution yet since December 2021 for Kodi or Plex?

**Comment by fjagerva** [comment] 2023-05-16 07:07
Thank you for the info, @McFL7.  Which HDMI switch are you using between the FireTV and your videoprojector? Brand? Model? Available in Amazon?

**Comment by McFL7** [comment] 2023-05-16 08:17
> Thank you for the info, @McFL7. Which HDMI switch are you using between the FireTV and your videoprojector? Brand? Model? Available in Amazon?

Hi, here it is, best one i found for my needs, not especialy to fix HDR content. Any other brand/model may work too , i had some specific needs to have 4x HDMI inputs to 2xoutputs and also extract audio to my soundbar. However take care that it doesn't support forwarding HDMI CEC some more expensives brands do it. hence, to control my videoprojector and my soundbar i I.R feature of the FireTV Remote Control.

https://a.aliexpress.com/_Exy6t45

**Comment by Bigmoco** [comment] 2023-06-09 08:10
So, I have a fix, but it's very convoluted. One prerequisite, you need an HDR monitor/TV, which we all have laying around, right? Luckily, I'm a hoarder and had an "old" HDR TV in a spare room. 

Anyways, what you want to do is setup that HDR monitor/TV near your Fire Stick 4K Max. Whether that be a projector, non HDR monitor, etc. In my case it was a soundbar. 

Now listen carefully, at any point in this process you must NOT disconnect the Fire Stick from it's power source, doing so will result in failure. NO EXCEPTIONS!

With that ominous warning out of the way. 

First off, make sure your Fire Stick is set to "Always HDR", "Adaptive" may work, but this is how I did it. Now, disconnect the Fire Stick from the Non-HDR device. Then plug it into the HDR monitor/TV. 

Enter Kodi and play any HDR content, make sure that the HDR is displaying correctly. If it is, disconnect the Fire Stick and plug it back into the Non-HDR device.

If you've done this correctly HDR tonemapping should be working on the Non-HDR device. 

I told you it was convoluted, didn't I?

It's late so I haven't done any stress testing i.e.(Changing to "Adaptive" or "Disable HDR", Force stopping Kodi or clearing it's cache, the positive/negative affects on other apps, seeing if prolonged sleep mode resets it) but what I do know is if you restart/unplug your Fire Stick for any reason or god forbid your power goes out then you will have to repeat this process again.

I hope this helped and...Amazon, get your crap together and update your s***. Goodbye :)

**Comment by McFL7** [comment] 2023-06-10 18:28
Hi, this is somehow what i do with my HDMI switch. As i have two inputs and 4 outputs, i put one input to the videoprojector and the other one left empty. I switch on the matrix switch the input source to the one with not plugged and then start the Firestick Max in Adaptative HDR mode, it is tricked by the matrix switch (which support HDR) as if it is plugged to an real HDR TV, then it enables it internally, afterward i switch to the SDR Videoprojector with the Matrix switch remote controle (no unplug at all) without rebooting the Firestick, it keeps HDR settings internally but the HDR content is tonemapped, to adapt to SDR output, however the videos are somehow darker than normal, but when i switch to "always HDR" they become really vivid and HDR videos are shiny.

Hope this helps to simplify the process.

Keep me in touch if it worked for you too guys with a two input sources HDMI switch, like for me.

**Comment by MidnightWatcher** [comment] 2023-07-04 18:23
Any update on this? Just got a 4K MAX and noticed the washed out colors on my SDR projector with Kodi. Should I return it?

**Comment by fjagerva** [comment] 2023-07-07 06:08
Yes, return it and get the 4K non-MAX version instead... The non-MAX version works fine with HDR on SDR displays.

**Comment by Baronz23** [comment] 2023-07-23 21:44
> 

I confirm that this work. Vimu player Is the only player (set with engine2+tunneling) that does tone mapping locally on Fire Stick 4k max. I tried VLC, Kodi, MX player, Plex and Jellyfin without success. 1.5 euro for Vimu player really solved my problem with HDR movies stored on my Nas and player on a SDR screen.

**Comment by Bigmoco** [comment] 2023-07-24 05:34
I know this doesn't solve the issue but can confirm the Chromecast 4k w/Google TV does HDR tonemapping. Just saying.

**Comment by CastagnaIT** [comment] 2023-09-02 11:31
i can confirm the issue
i have a panasonic 1080p tv and with nvidia shield
happens randomly, when i start a MKV 4K HDR, colors are washed out, very noticeable also on kodi GUI
the only workaround (for me) is stop playback and start playback a second time

**Comment by fjagerva** [comment] 2023-10-15 11:05
It seems that HDR tone mapping has been fixed in the new 2023 version of the Fire TV Stick 4K Max. So bad news for the owners of the previous 4K MAX version, since it was probably a hardware related issue.

**Comment by McFL7** [comment] 2023-10-15 20:31
> It seems that HDR tone mapping has been fixed in the new 2023 version of the Fire TV Stick 4K Max. So bad news for the owners of the previous 4K MAX version, since it was probably a hardware related issue.

Hi, 

could you provide more details, what is the build version of this new Fire TV Stick 4K Max ? How to recognize it, and distinguish it from old version. Isn't just a firmware update released ? Could you provide firmware and build version screenshot from your FireTV MAX ?

Thanks

**Comment by fjagerva** [comment] 2023-10-22 10:23
It is a completely new device:
![71G8Z9GxGuL _AC_SL1500_](https://github.com/xbmc/xbmc/assets/8319363/2fa1413a-2a8e-4402-aff5-59ef129c8f07)

**Comment by ksa-real** [comment] 2023-10-22 19:58
Amazon is really bad at naming these devices :) So now it is "Amazon Fire TV Stick 4K Max (2nd)"

**Comment by dociouss** [comment] 2023-11-17 19:21
> It seems that HDR tone mapping has been fixed in the new 2023 version of the Fire TV Stick 4K Max. So bad news for the owners of the previous 4K MAX version, since it was probably a hardware related issue.

Are you confirming this from using your own 2023 4K Max?

**Comment by CSchuetz7** [comment] 2023-11-21 10:59
I can confirm that the new Fire TV Stick 4k Max Gen2 no longer has this problem.
My old 4k Max has the problem with the washed out colors.

**Comment by thexai** [comment] 2023-11-21 19:03
On Android, when is used hardware acceleration (Media Surface), tonemapping should be done by hardware. So this has always been a limitation of a device.

**Closed by thexai** 2023-11-21 19:03 UTC
Labels: Platform: Android, v19 Matrix, Triage: Confirmed, v20 Nexus, v21 Omega
