### ISSUE TITLE
Subtitle position offset after some playback time

### ISSUE THREAD

**Issue by LaurentAtJoes** [xbmc/xbmc#17160] opened 2020-01-09 14:12 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

When playing .mp4 or .m4v files (encoded in h264 using handbrake, latest 1.3.1, tx3g subtitles), after some time subtitles change position, from initial bottom of screen-centered to somewhat higher and to the left. (see screenshots)
The moment it occurs varies from under a minute to 5 or 10 minutes.
Stopping then resuming the playback brings subtitles back to correct position, but they move again a bit later. Same thing when stepping back/forward in time (using left/right arrows).

Subtitle position setting is "fixed", but same issue occurs with bottom / below video.

.mkv files with ASS subtitles , as well as files with external .srt sidecar files are playing without any problem. (of course with .mkv subtitles are always displayed at bottom of _video_ , but they do stay there.)
(and converting an existing mp4 file to mkv also fixes the issue, of course because subtitles are converted from tx3g to ASS)

I have the impression that this is somehow similar to the issue described in [this thread](https://forum.kodi.tv/showthread.php?tid=349592) from the kodi forum 
Although for this user, subtitles _disappear_ instead of just getting offset, the rest kind of matches.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Subtitles should stay in the correct position, as set in settings, and not move around.

## Actual Behavior

Subtitles shift position after some playback time.

### To Reproduce

1. Get a .m4v / .mp4 file with subtitles, or create one
2. play it, enabling subtitles
3. wait until subtitles move around.

### Debuglog

The debuglog can be found here:
[kodi.zip](http://lem.alpha.free.fr/misc/kodi.zip)

### Screenshots 
Here are some links or screenshots to help explain the problem:

http://lem.alpha.free.fr/SCRSHT/Position_OK.jpg
http://lem.alpha.free.fr/SCRSHT/Position_offset.jpg

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: OSMC 2019.11-1
 - Kodi version: 18.5

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment] 2021-09-30 09:39
We are currently making improvements in this area,
this situation is a bit abnormal it would be helpful if you could share a sample file that cause this behaviour
on which we can do tests

**Comment by CastagnaIT** [comment] 2021-11-26 08:15
I close it now because with the subtitle rendering rework in Kodi 20
the reworked TX3G parser do not have the ability to move text on screen
anyway not even before probably the cause was elsewhere
in my tests the TX3G works well, if the sample that causes this problem will be provided or other users report same thing the situation can be re-evaluated

**Closed by CastagnaIT** 2021-11-26 08:15 UTC
Labels: Issue Cleanup: Obsolete
