### ISSUE TITLE
Kodi doesn't honor <hosts> in advancedsettings.xml

### ISSUE THREAD

**Issue by andbo467** [xbmc/xbmc#15469] opened 2019-02-08 20:09 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

`<videodatabase>` and `<musicdatabase>` doesn't care about what is defined in previous `<hosts>` in advancedsettings.xml.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

If a host is defined in advancedsettings it should use it.

## Actual Behavior

It doesn't matter what is defined in `<hosts>`. Kodi doesn't use it anyway.

### To Reproduce

In advancedsettings.xml:
A1. Define a host with the actual/right hostname (in my case "SC-NAS") but wrong IP.
A2. Use the hostname above when defining a mysql database.
A3. Start Kodi.
A4. Kodi should not find the database because of the hostname points to the wrong IP, but it does.
 
B1. Define a host with the wrong hostname (lets say "TEST") but with the right IP.
B2. Use the hostname above when defining a mysql database.
B3. Start Kodi.
B4. Kodi should now find the database because of the hostname points to the right IP, but it doesn't.

### Debuglog

The debuglog can be found here:
Debug with right hostname and wrong IP: https://paste.kodi.tv/erusocarat.kodi
Debug with wrong hostname and right IP: https://paste.kodi.tv/quqokufupu.kodi

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Also when referring to a `smb://hostname` in sources.xml doesn't care about what is defined under `<hosts>`.

The problem was discovered when Windows 10 removed SMB1 by default and the hostname wasn't autodiscovered in Windows under a period, before it was fixed.

The same problem is in Kodi 17.x

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: 10 Education edition (10.0.17763.253)
 - Kodi version: 18.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by andbo467** [comment] 2019-03-29 21:06
noone?

**Comment by WulfmanGer** [comment] 2019-08-21 11:42
Same @ LibreElec 9.2 (Kodi **18.3**) @ Raspberry Pi4

KODI has a very aggressive handling of DNS.

(LibreElec, Pi4)
~ / .config / hosts.conf -> is completely ignored by Kodi. Only console works.

Workaround: delete resolv.conf, create new resolv.conf (at startup) with OWN DNS server wants to be rejected after some seconds (time enough to open to Netshare and cache this DNS).

DNS-push via VPN (openvpn via autostart.sh) is completely ignored. Routing into my LAN behind VPN works.

Apparently, it is fixed here defines how DNS resolution is allowed to work and with which server is spoken. Only resolv.conf -> nameserver x.y.z.a. If this fix were removed, then <hosts> or at least hosts.conf would work immediately.

**Comment by JoshDi** [comment] 2019-10-03 02:34
Im having the same issue

**Comment by mytril** [comment] 2020-10-14 17:40
The issue is also in version 18,8 and 19, On Windows 10, Kubuntu 20.04, Fire TV Stick and Android TV

**Comment by vagkap** [comment] 2021-01-08 08:24
Same here. Tested Kodi 18.9 on SONY Android TV, Android TV Box, and Windows 7. 
In the case of Android TVs there is no chance of editing hosts file so there is no other way to solve this problem.
With Android TV sales on the rise lots of people are going to face the same problem. Please fix it.

**Comment by arnova** [comment] 2021-01-08 12:04
as.xml <hosts> was never implemented for stuff like this. It simply adds host->ip entries inside Kodi's internal DNS-cache but the DNS cache is actually only used by the NFS client (and LAN-check). So it means it also doesn't work for other network filesystems: smb, http, webdav etc.

I also don't get why you need this? You might as well stick the IP directly in the database-sections. Or perhaps you could use Kodi's path substitution? This doesn't mean that <hosts> should be fixed or its comment should be improved, but perhaps it can offer a workaround for now?

**Comment by wsnipex** [comment] 2021-01-08 13:39
I suspect when you want to use SSL, you're better off with a hostname or you might have cert validation issues.
I've quickly looked into a fix, see PR linked above

**Comment by vagkap** [comment] 2021-01-08 14:53
Just to make my case clear: 
I use kodi with MariaDB(mysql) as the audio/video database which is running on a NAS. 
I have multiple clients running kodi on different platforms. 
In each client machine change only the (system) hosts file to point to my NAS IP (eg. HOME_NAS 192.168.1.101).

The audio/video files are stored in the same NAS.

my settings for the DB in advancedsettings.xml are 
    <videodatabase>
        <type>mysql</type>
        <host>HOME_NAS</host>
        <port>3306</port>
        <user>username</user>
        <pass>password</pass>
    </videodatabase> 
         
The sources.xml file has entries like this:
        <source>
            <name>documentaries</name>
            <path pathversion="1">smb://HOME_NAS/video/documentaries/</path>
            <allowsharing>true</allowsharing>
        </source>

The "problem" is that on a machine that you cannot edit the system hosts file
you cannot use the (shared) sql database because the file paths are stored as smb://HOME_NAS/.....

**Comment by arnova** [comment] 2021-01-08 15:13
> Just to make my case clear:
> I use kodi with MariaDB(mysql) as the audio/video database which is running on a NAS.
> I have multiple clients running kodi on different platforms.
> In each client machine change only the (system) hosts file to point to my NAS IP (eg. HOME_NAS 192.168.1.101).
> 
> The audio/video files are stored in the same NAS.
> 
> my settings for the DB in advancedsettings.xml are
> ` <videodatabase> <type>mysql</type> <host>HOME_NAS</host> <port>3306</port> <user>username</user> <pass>password</pass> </videodatabase>`
> 
> The sources.xml file has entries like this:
> ` <source> <name>documentaries</name> <path pathversion="1">smb://HOME_NAS/video/documentaries/</path> <allowsharing>true</allowsharing> </source>`
> 
> ```
> The "problem" is that on a machine that you cannot edit the system hosts file
> you cannot use the (shared) sql database because the file paths are stored as smb://HOME_NAS/.....
> ```

To be honest: I don't really see the problem. It's only for convenience that you can configure the hostname->IP mapping in a single place, right? But then the question comes to mind: How often do you change the host's IP? I suspect it's a one time thing, so that means setting an IP in 2 config files: advancedsettings.xml and sources.xml, no biggy imo.

**Comment by vagkap** [comment] 2021-01-08 15:30
You're correct but it's a little bit more complicated.
I sync the databases (and the files) between two different NASes in different locations with different  ip addresses [192.168.1.*  and 192.168.0.* ]

**Comment by wsnipex** [comment] 2021-01-08 15:39
are you able to test my proposed fix?

**Comment by mytril** [comment] 2021-01-08 15:41
I have a bit other setting, but the same problem. I have two nas systems on two locations with the same files. But to keep track of the view status of every file. I have created only one database on one of the nas systems. So the trick is to tell kodi that both systems are the same. Because if both nas systems have not the same name, they will be treated in the database as different file locations. 

So i use the <hosts> tag for the file server and the fixed ip for the db server. But because that don't function i have used my fritzbox to do the same...

**Comment by vagkap** [comment] 2021-01-08 16:23
> are you able to test my proposed fix?

Sorry but i cannot test it.

**Comment by mytril** [comment] 2021-01-08 18:09
@wsnipex No it doesn't seem to work. If a add a new Host in the file and want to access the files. He doesn't find the host. I hope i have the right version: Was "git fetch origin pull/19040/head:hosts" the right command?

**Comment by wsnipex** [comment] 2021-01-08 18:45
why is that?

**Comment by vagkap** [comment] 2021-01-08 20:54
> why is that?

Because i don't know what i have to do. How can i test it ? I suppose i need a new executable ?

**Comment by wsnipex** [comment] 2021-01-08 20:57
which OS and hardware do you use? We can provide test builds for most platforms, but linux

**Comment by mytril** [comment] 2021-01-08 21:00
I could test it on linux or windows. I have tried to compile it on kubuntu. After fetching your patch, kodi dont start anymore, only matrix screen...

**Comment by wsnipex** [comment] 2021-01-08 21:02
did you build this branch? https://github.com/wsnipex/xbmc/tree/hosts
please provide a debug log, by running kodi --debug from console

**Comment by mytril** [comment] 2021-01-08 21:15
Ok i have found the error. My fault was that i have written two entrys in the xml file, but with one entry it works:

  <hosts>
    <entry name="server">192.168.42.42</entry>
    <entry name="test123">192.168.42.42</entry>
  </hosts>

**Comment by vagkap** [comment] 2021-01-08 21:17
> which OS and hardware do you use? We can provide test builds for most platforms, but linux

@wsnipex
I use windows 7 64bit and android TV version 9.  Windows is much easier/faster to test.

**Comment by mytril** [comment] 2021-01-08 21:33
Thats strange if i add the msql database entrys from the older config. Kodi dont start anymore.

[advancedsettings.xml](https://paste.kodi.tv/ebosedemup)
[kodi.log](https://paste.kodi.tv/cowipesabo.kodi)

**Comment by howie-f** [comment] 2021-01-08 21:43
@mytril you‘re testing with an old commit, as your log reveals. the pr has been updated meanwhile and i can confirm it‘s working for mysql in its current state.
try again with https://github.com/wsnipex/xbmc/tree/hosts please

**Comment by mytril** [comment] 2021-01-08 21:47
@howie-f Ok will try it.

**Comment by mytril** [comment] 2021-01-08 23:23
@howie-f Yes now it works

**Comment by wsnipex** [comment] 2021-01-09 15:16
here some test builds:
arm64: https://mirrors.kodi.tv/test-builds/android/arm64-v8a/kodi-20210109-38daa994-PR19040-merge-arm64-v8a.apk
arm: https://mirrors.kodi.tv/test-builds/android/arm/kodi-20210109-38daa994-PR19040-merge-armeabi-v7a.apk
win64: https://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20210109-38daa994-PR19040-merge-x64.exe

**Comment by vagkap** [comment] 2021-01-09 16:27
Tested win64 version.
Entry for HOME_NAS deleted from windows hosts file and added to advancedsettings.xml 
``    <hosts>``
``      <entry name="HOME_NAS">192.168.1.201</entry>``
``    </hosts>``
RESULTS:
On first run DB migrated to new version.  Seems that HOME_NAS was correctly resolved to 192.168.1.201.
But none of the files in the database could be played.

In the log file there are entries for for every file/directory in the DB like the following:
"2021-01-09 18:07:20.690 T:2836  WARNING <general>: VIDEO::CVideoInfoScanner::Process directory 'smb://HOME_NAS/video/movies/' does not exist - skipping scan."

This message appeared on screen: "This file is no longer available. Would you like to remove from the library ?".
It seems that smb protocol cannot resolve the host.
Hope that helps.

**Comment by wsnipex** [comment] 2021-01-09 21:01
I kinda expected this. Contrary to curl (for http/ftp), there is no way to fake a DNS server for SMB and MySQL. Kodi is not a DNS server, the best we can do is replace the name with the IP. The resulting URL is smb://192.168.1.201/videos/movies
You might be able to combine this with path substitution to get it working.
It works for HTTP, because curl provides a method to fake DNS entries.

**Comment by mytril** [comment] 2021-01-09 21:08
On my setup with smb and mysql it works. All Videos play and a can resume them on other devices too. Maybe there are other problems with your setup like permission problems? Or have you a problem with lowercase or uppercase letters in your path?

**Comment by vagkap** [comment] 2021-01-09 21:33
@mytril I don't think it's an uppercase/lowercase issue because when the O/S does the resolving everything works fine. 
Did you reboot your system (or flushed the dns cache) ( `ipconfig /flushdns` on windows) after removing the entry from your hosts file?
I can't think of anything else why it is working in your case and not mine. I use win7 x64.

**Comment by mytril** [comment] 2021-01-09 21:39
I am on Linux and didn't need to reboot. But i can try it on windows 10.
Here are my entries:

`<advancedsettings>
  <hosts>
    <entry name="test">192.168.42.42</entry>
  </hosts>
  <videodatabase>
    <type>mysql</type>
    <host>test</host>
    <port>3306</port>
    <user>kodi</user>
    <pass>kodi</pass>
  </videodatabase> `

**Comment by vagkap** [comment] 2021-01-09 21:45
Maybe i wasn't clear enough. The DB works fine. The problem is that kodi cannot find the video files when i press play.

**Comment by mytril** [comment] 2021-01-09 21:53
Yes i can confirm it. On Linux it works but on Windows tell i get an error if i want to add the source. He cant find the Host.

**Comment by wsnipex** [comment] 2021-01-10 06:00
windows doesn't use samba, but windows native SMB. If it works in linux, it should work on all other platform but windows as well.
For windows: just use a hosts file entry and be done with it.

**Closed** 2021-01-12 08:55 UTC
Labels: Component: Settings, v18 Leia
