### ISSUE TITLE
Screensaver not going black when video is paused

### ISSUE THREAD

**Issue by Lostion1** [xbmc/xbmc#16123] opened 2019-05-13 23:42 UTC
### Describe the bug
The Blackscreener Server is not working when you pause a video even when the "Dimming when video is paused" option is disabled it dims down to 20 % not full black screen like it should.

It's an Kodi bug because its behave the same on OSMC/LibreELEC (Leia) 9.0.2 MR so it can't be an OSMC or LibreELEC bug.

## Expected Behavior
The Screenserver should be going to 100 % black and not dimming to 20 %

## Actual Behavior
Black Screensaver is dimming down to 20 %

## Possible Fix
Log in as “root” in Putty/Terminal/WinSCP etc.
Type in (or copy the folder via WinSCP):

cp -a /usr/share/kodi/addons/screensaver.xbmc.builtin.dim /home/osmc/.kodi/addons/

Then edit the settings file in
/home/osmc/.kodi/addons/screensaver.xbmc.builtin.dim/resources/settings.xml

change
range=“20,1,100”

to:
range=“0,1,100”

Then reboot then go to:
desktop -> Screensaver -> Select dim -> Settings -> change to 0 %
then you can let it in dimming mode OR use the black screensaver which
is now working (before the black screensaver did go to 20 % for no reason).

I don't know why the "Black" Screensaver is using the options from the "Dim" Screensaver, the easiest fix would be just to use "range=“0,1,100”" instead of "range=“20,1,100”" or the "Black" Screensaver must be fixxed in another way, not quiet sure why the "Dim" Screensaver has a lock at 20 % in the standard configuration you can't go to zero? Makes not much sense to me. On Windows 7/10 that problem is not there so it must be an ARM issue. On Windows 7/10 the "Black" Screensaver is working but the "Dim" Screensaver also has a lock at 20 %. 

### To Reproduce
Go to settings -> desktop
Change the screensaver to black
Waittime to one minute
Uncheck the option “Dimming if the video is paused”
Start a video over Network or usb -> pause the video and wait a minute
Screen is dimming down to 20 % and not going to black

### Debuglog
Debuglog is showing no error 

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: OSMC/LibreELEC (Leia) 9.0.2 MR
 - Kodi version: 18.2 and 18.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment] 2019-05-14 04:35
I was not able to reproduce this on GLES with kodi-gbm. So it must be specific to RPi windowing.

I'll include @MilhouseVH and @popcornmix in the loop to see if they can reproduce.

Also you can use kodi-send to test activating the screensaver from another system
```
$ kodi-send --action=ActivateScreenSaver
```

**Comment by vpeter4** [comment] 2019-05-14 06:59
I can reproduce this with LibreELEC (official): 9.0.2 (Generic.x86_64) on VMware Workstation 12. So it is not just RPi issue.

**Comment by Lostion1** [comment] 2019-05-14 12:08
$ kodi-send --action=ActivateScreenSaver 

activates the screensaver but in the standard config it dimms down to 20 % iam not quiet sure why "Dim" and "Black" are connected on the Pi or other devices like @vpeter4 tested.

**Comment by dagwieers** [comment] 2019-06-24 12:35
The same happens with other screensaver. I have written my own screensaver "Turn Off" which has the same issue. It appears that pausing playback simply uses the Dim screensaver instead of the configured screensaver.

**Comment by ksooo** [comment] 2019-09-17 18:29
There are some situations where Kodi ignores the screen saver set by the user and where it uses the "Dim" screensaver instead, for example if a modal dialog is open while the screen saver shall be activated. This is the case if you paused a video AND the player control buttons are visible (these buttons are technically a modal dialog). I guess this is what you are seeing as "black screen saver does not work as it only dims to 20%, not 0%".

@HitcherUK @DaveTBlake So, a valid fix for this scenario would be to fix Kodi not to use "Dim" in this situation, but the screensaver set by the user. Changing "Dim" screensaver settings ranges to allow to dim down to 0% is a workaround, at best.

**Closed** 2019-09-19 06:09 UTC
Labels: Platform: RPi, Triage: Needed

**Comment by dagwieers** [comment] 2019-09-19 15:22
Thanks !
