### ISSUE TITLE
[skin.estouchy] Recent Movies not showing the latest movies added

### ISSUE THREAD

**Issue by robertxgray** [xbmc/xbmc#14832] opened 2018-11-08 22:20 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

I tested the bug described in #14813 again, now running Ubuntu 18.04 and Kodi 18 provided by ppa:team-xbmc/unstable. To make it clearer I'm using a mock-up library with just 16 movies starting with every letter from **A** to **P**. The movies have been added to the library in alphabetical order: 1st **A**pocalypse Now, 2nd **B**raveheart... 16th **P**ulp Fiction.

When using the Estouchy skin, the "Recent Movies" list in the home screen includes just the first 10 movies in alphabetical order. When movies are added to my library, they're not included in the list unless they're in the top of the alphabetical order. (Screenshot 1)

The recent movies are listed as expected if I navigate to Movies -> Recently Added. (Screenshot 2)
I get the same expected behaviour if I navigate to Movies-> Titles and then sort by date added, descending. (Screenshot 3)

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Recent Movies should list the new movies in the library.

## Actual Behavior

Recent Movies is showing the top movies in alphabetical order.

## Possible Fix

I found a workaround by editing the line 110 in
addons/skin.estouchy/xml/IncludesHomeRecentlyAdded.xml

Original
`<content target="movies" sortby="date" limit="10">videodb://recentlyaddedmovies/</content>`

Possible Fix
`<content target="movies" sortby="dateadded" sortorder="descending" limit="10">videodb://recentlyaddedmovies/</content>`

### To Reproduce

1. Enter Kodi and navigate to Estouchy's home screen.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/vozomireka

### Screenshots 
Here are some links or screenshots to help explain the problem:

Screenshot 1: Recent movies in the home screen
![screenshot1](https://user-images.githubusercontent.com/9676118/48230765-6ac55f00-e3ac-11e8-9f7a-c6a2f1687d1d.png)

Screenshot 2: Movies -> Recently Added
![screenshot2](https://user-images.githubusercontent.com/9676118/48230795-7f095c00-e3ac-11e8-90df-9215481fffde.png)

Screenshot 3: Movies-> Titles sorted by date added, descending
![screenshot3](https://user-images.githubusercontent.com/9676118/48230817-95171c80-e3ac-11e8-8df9-625fbfacdae2.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

See #14813.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [X] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu 18.04
 - Kodi version: 18.0-BETA5

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment] 2018-11-09 08:30
That´s not a bug, but a limitation to the skin itself. 

Please see: https://github.com/xbmc/xbmc/blob/master/addons/skin.estouchy/xml/IncludesHomeRecentlyAdded.xml#L110

`<content target="movies" sortby="date" limit="10">videodb://recentlyaddedmovies/</content>`

If you change the limit to another value then more items are listed. 

The other category you mentioned, where all 16 movies are listed, is limited to 25 entries. So your test will fail if you scrape, let´s say, 30 items. 

See: https://kodi.wiki/view/Advancedsettings.xml#videolibrary

` <recentlyaddeditems>35</recentlyaddeditems> <!-- number of recently added items. **Defaults to 25** -->`

So, in the end that´s not a bug at all. Imagine there would not be any limition and you have 1500 movies you want to scrape **today**. Then any of those listings will contain 1500 entries which would make no sense at all. 

Feel free to customize that section in the way you want it to. But I would say there´s nothing to change on our side.

**Comment by Rechi** [comment] 2018-11-09 09:04
@robertxgray please submit a PR where you add `sortorder="descending"` which you described as possible fix.

**Comment by DaVukovic** [comment] 2018-11-09 11:48
Ah, sorry. My bad. My thought was that the topic was about the amount of entries in that widget. 

True, changing the sortorder to descending could fix that. 

I´ll reopen that ticket again.

**Comment by robertxgray** [comment] 2018-11-09 12:53
Okay, I'll try to submit a PR if I can remember how to do it. But first I'm going to test the other lists in the home screen. Thank you.

**Comment by robertxgray** [comment] 2018-11-09 17:10
No problem in Recent Episodes or Recent Albums. I also confirmed that an explicit order is not necessary for movies either, so the pull request is even smaller than expected:  #14837. It works in both Kodi 17 and Kodi 18.

Note that the original fix didn't change the sorting order only, it was also necessary to sort by dateadded instead of date.

**Comment by HitcherUK** [comment] 2018-11-11 12:38
Fixed with [#14837](https://github.com/xbmc/xbmc/pull/14837).

**Closed by HitcherUK** 2018-11-11 12:38 UTC
