### ISSUE TITLE
No Commercial Detection For PVR Recordings Played From TV Library Section

### ISSUE THREAD

**Issue by jsnj** [xbmc/xbmc#16570] opened 2019-09-04 19:21 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

PVR recordings added to the video library as a source don't skip commercials when played from the library section.

Possibly related:
#15512

Tested on nVidia Shield Android 8 & 9 and Ubuntu 19.04

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

PVR recordings added to the video library as a source SHOULD skip commercials when played from the library section.

## Actual Behavior

PVR recordings added to the video library as a source DON'T skip commercials when played from the library section.

### To Reproduce

1. Add PVR recordings as a source to the video library
2. Go to TV library section
3. Play PVR recording from the library section

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ X] Android 8 & 9
 - [ ] iOS
 - [ X] Linux Ubuntu 19.04
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment] 2019-09-04 21:30
duplicate of: #16564 

The mentioned PR isn't even merged and the debuglog is missing. 

Please keep the discussion at the other issue

Thanks ;)

**Closed by DaVukovic** 2019-09-04 21:30 UTC
Labels: Ignored rules, Triage: Needed
