### ISSUE TITLE
If 2 episodes 1 file kodi auto plays the file again when using auto play next episode

### ISSUE THREAD

**Issue by Dnkhatri** [xbmc/xbmc#17854] opened 2020-05-12 17:01 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

If 2 episodes are 1 file kodi auto plays the file again instead of going to episode 3. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Third episode should play

## Actual Behavior

same file is repeated

### To Reproduce

 These are the filenames if you guys want to test

S01E01E02 - Jeong Hoon’s Exposure + Ha Jin on Jeong Hoon’s Live News Show.mp4 
S01E03E04 - Find Me in Your Memory + Jeong Hoon and Ha Jin’s Deal.mp4
S01E05E06 - Ha Jin’s Lost Memory + Ha Jin’s Plan.mp4
2.
3.

### Debuglog
https://paste.kodi.tv/osilugomeg.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x ] Android
 - [ ] iOS
 - [x ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Linux Mint
 - Kodi version: latest 19 Alpha

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Dnkhatri** [comment] 2020-05-16 12:20
@DaVukovic 
I have added logs from my linux kodi 19 alpha install doing a clean install on android is too much of a hassle. Though weirdly for all double episodes now the same file is played again on a clean install. So I am not sure why it was working for some earlier

**Comment by DaVukovic** [comment] 2020-05-17 07:10
I kind of guess that you are missing episode bookmarks. Did you ever set those? 

Short how-to: 

* play a file
* pause at the section where the first episode ends and the 2nd episode starts
* navigate to the "Bookmarks" section
* set an episode bookmark

Do that for any episode which is contained in that file.

Multi-Episode files is nothing I would recommend generally. Because the library and the player are doing different things....

If you have a file called S01E01E02.mkv Kodi will scrape those perfectly fine as separated entries at the library. But, if you play Episode 1, Kodi will play that complete file (which contains 2 episodes). There will be no switch to episode 2 during playback. If you then start episode 2, Kodi will play from that bookmark you set earlier. 

So, let's say you have those episodes listed and you start watching from episode 2 and you will end that, episode 1 will be marked as watched as well, even if you never watched it. 

So I would really recommend to use separated files if you care about your watched states.

**Comment by DaVukovic** [comment] 2020-06-12 12:08
@Dnkhatri any comments?

**Comment by Dnkhatri** [comment] 2020-06-12 12:27
Episode bookmarks actually don't work as for the some asian shows there is no boundary of episode 1 and episode 2 It actually is a double episode. 
From what I can tell Kodi properly  changes from watched to unwatched for both episodes when we press w on any of the entries so it should go to episode 3 instead of repeating the same file. I am not a programer but have used kodi enough to guess Kodi is making a playlist so maybe a restriction of not repeating a file would work. My problem is the repeat playback of an episode rather than the watched unwatched status.

**Comment by DaVukovic** [comment] 2020-06-12 12:56
Yes, and I understand that and if you would set bookmarks that won't happen anymore as Kodi will start the playback for each episode at the specific bookmark inside that file. At your current state, you have 2 entries in your library which point to the same file without having an episode-bookmark. So you start to play episode 1 and Kodi will play the complete file which contains 2 episodes. Then that file ends and Kodi will start the playback of the next entry in your library. That's episode 2 then which points to the same file. As you didn't have set bookmarks, Kodi will simply play that file from the beginning again and therefore it seems that Kodi is repeating to play episode 1. If you would not stop the playback at this state then, Kodi will continue with episode 3. 

Let's make that more clear: 

bundled_episode.mkv = contains episode 1 and 2
episode3.mkv

in your library it will be shown as: 

episode 1
episode 2
episode 3

Note, that episode 1 and 2 will point to bundled_episode.mkv....

Now you start with the playback of "episode 1" (which points to bundled_episode.mkv) and therefore Kodi is playing the whole file which contains 2 episodes. Then that file ends and Kodi is thinking, "let's play the next episode", which then is "episode 2" which also!!!!! points to bundled_episode.mkv. and Kodi will play that file fine. But it will start at the beginning from that file. So generally you are watching the 1st episode again. If you continue the playback, Kodi will then switch to episode 3. 

If you would use bookmarks, and you would have ended the bundled_episode.mkv and Kodi starts the playback of episode 2 in your library, then Kodi would start at the bookmark you set. So it will repeat the episode 2 which you already watched while watching episode 1 and therefore the complete file "bundled_episode.mkv". After ending that playback, Kodi will switch to episode 3 fine

If it's a bundled episode, and it is scraped as 2 episodes, then we can't do anything against that, as it's listed as 2 episodes at TVDB: 
https://www.thetvdb.com/series/memoir-of-the-man/seasons/official/1

So this is not a Kodi bug. This is expected behavior if you don't use bookmarks and bundled files. There might be problems with Episodes which are stored in a single file and I mentioned that before (and explained above). Hence I can't recommend that feature at all. Episodes should always be stored as separated files if you care about continuous playback. 

So I'm going to close this and I would kindly ask you to continue this discussion at the Kodi forums. Maybe there will be a feature request in the end. But currently Kodi does what is expected.

**Closed by DaVukovic** 2020-06-12 12:56 UTC
Labels: Ignored rules, Issue Cleanup: Ask Reporter, Triage: Needed
