### ISSUE TITLE
Determining screen size on Kodi Android

### ISSUE THREAD

**Issue by ppongoo** [xbmc/xbmc#21787] opened 2022-08-28 11:34 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

I have a 1080p-display android TV which has 720p resolution settings whether intended or having a wrong firmware.
It limits Android UI resolution to 720p but it can reach to 1080p and render FHD video sources successfully. 
But it doesn't apply to Kodi.

If you see this firmware properties (link below), it would be easier to understand what's happening and what I'm gonna talk about.
https://pastebin.com/bMYYhs2p

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

UI : 720p (1080p if possible)
Display Resolution : 1080p

## Actual Behavior

UI : 720p 
Display Resolution : 720p ( Locked )

## Possible Fix

https://github.com/xbmc/xbmc/blob/e0520c14c5bf71177a763793987c36d916ab337c/xbmc/windowing/android/AndroidUtils.cpp#L65

https://github.com/xbmc/xbmc/blob/e0520c14c5bf71177a763793987c36d916ab337c/xbmc/windowing/android/AndroidUtils.cpp#L163

displaySize = CJNISystemProperties::get("sys.display-size", "");
    if (!displaySize.empty())

modes [{id=1, width=1280, height=720, fps=60.000004}, {id=2, width=1280, height=720, fps=50.0}]
[sys.display-size]: [1920x1080]

My Tv has "mode" properties, set to 720p and buid.prop's display size is 1080p.
So basically, Kodi gets the resolution from [modes] and stops the size check process. 
In my Kodi, video resolution is locked at 720p .

possible fix!
If sys.display-size is bigger than modes resolution, return sys.display-size as a screen resolution.
or
can we prioritize "sys,display-size" than "mode"?

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

opened kodi:
https://paste.kodi.tv/nihiqequle

played 1080p video:
https://paste.kodi.tv/dasatalomi

### Screenshots 
Here are some links or screenshots to help explain the problem:

https://imgur.com/EPChI9k
https://imgur.com/a/Nprbseo

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android

Android TV OS 11

 - Operating system version/name: 
 - Kodi version: v19.3 ~ v20 alpha2 (ARMv7-32)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment] 2022-08-28 12:45
in order that someone take in account this issue
will be needed that you attach a full kodi debug log

**Comment by ppongoo** [comment] 2022-08-28 13:07
> 

Thanks! I totally forgot about that.

**Comment by ppongoo** [comment] 2022-08-28 13:08
> in order that someone take in account this issue will be needed that you attach a full kodi debug log

Thank you! I attached it now

**Comment by CastagnaIT** [comment] 2022-08-28 13:19
thanks, look like your tv firmware give wrong values or limits app resolutions despite the panel resolution
i think @joseluismarti have more experience in this field can give his opinion

**Comment by ppongoo** [comment] 2022-08-28 13:32
my pleasure. I guess it happens frequently to the devices that have not enough hardware performance for smoother UI controls.
if it's accepted and a test needed, please @ at me anytime

**Comment by sarbes** [comment] 2022-08-28 15:38
Hey, if you need to crosspost, at least link to the forum thread were the cause of this has already been determined (https://forum.kodi.tv/showthread.php?tid=369094)! 

I still think it is a firmware bug, so this whole "issue" is a feature request to implement some device specific hack. If someone would address this, I think it is best to have an override as an advanced setting. Otherwise, we might break devices which have proper API behavior. Given that we want to avoid such hacks in the first place, I don't see that this gets implemented - but of course our Android guys would have to decide. 

I'm arguing to close the issue, as it is a feature request.

**Comment by ppongoo** [comment] 2022-08-28 16:14
sorry my bad. I thought this repo is a seperate place. I wanted to discuss futher since the last post in forum's thread but that 
 seemed to be literally closed. So I couldn't be patient.

All other apps except Kodi work normally playing video-wise. I kinda feel lost as of now.

**Comment by CastagnaIT** [comment] 2022-08-28 16:38
Kodi get the available device resolutions from official API `getSupportedModes`:
https://developer.android.com/reference/android/view/Display#getSupportedModes()

This android method provide the width/height info but also the compatible refresh rates
since do not return all resolutions that you think,
means that, despite the vendor claims, the manufacturer for some reason limited the resolution to all apps, so not Kodi only.

From android sources the `getSupportedModes`:
https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-main/core/core/src/main/java/androidx/core/view/DisplayCompat.java#249
already considering the checking of property `vendor.display-size`

this makes me think that, you think to display android apps at 1080p, because are upscaled from the display,
where instead all are running at 720p, and probably is verifiable with some utility app

**Comment by ppongoo** [comment] 2022-08-28 17:25
Thanks for the explanation.
But I'm still confused with what if it's upscaled and returning the fake 1080p.
somebody told me that
> No. UI resolution is separated from the video resolution. Video resolution is always equal to the physical resolution of the display.

https://i.imgur.com/wm10mTU.jpg
From the picture's viewport res, 720x1.5 equals to 1080
> https://twitter.com/teamyoutube/status/930277424323088384?lang=en Hi Alan, viewport refers to the dimensions of the playback area of the video. Both of them are not different if you notice, it's 1920 x 1080 * 2 on shield which is the same as 3840 x 2160 on your console. Hope this helps clarify!

And I'd been looking for a verification method of the actual playback size. I couldn't find one though.
In fact, it looks like legit 1080p from the naked eye I guess... 😭

I don't mean to bother devs by this issue. It looks adding a override command to advancedsettings.xml is the most practical solution. I was considering compiling my own build and gave it a try. But I failed at some step. 
I am assuming that this guide [https://github.com/xbmc/xbmc/blob/master/docs/README.md] is outdated years ago.

**Comment by joseluismarti** [comment] 2022-08-28 18:32
Use a utility such as [Device Info HW](https://play.google.com/store/apps/details?id=ru.andr7e.deviceinfohw) to see all modes supported by your Android device.

Kodi gets the supported video modes from the official API, as the maximum resolution of your device is 1280x720, it correctly scales the video from (1920,1080) -> (1280,720). 

With the other apps the same will be happening.

**Comment by CastagnaIT** [comment] 2022-08-28 18:33
> viewport refers to the dimensions of the playback area of the video

the playback area usually is the screen resolution currently used,
so viewport should be equal to the resolution, but can also change for example if you resize the app area

> Both of them are not different if you notice, it's 1920 x 1080 * 2 on shield which is the same as 3840 x 2160 on your console.

this is not well explained,
from your screenshot of youtube "Stats for nerd"
there is the Viewport that is `1280x720*1.5` this means that your app is running at the resolution of 720P
and the `*1.5` means that is currently downscale the current video stream of 1080p to 720P

the scaling factor `*x.y` should not appear if you display the 1080p stream video at full screen resolution of 1080p.
in this case your youtube app is working at 720p and the display are upscaling images to 1080p

**Closed** 2022-08-31 08:43 UTC
Labels: Platform: Android
