### ISSUE TITLE
skin.arctic.horizon.2 problem with RTL -Does not find results when searching in the Hebrew language

### ISSUE THREAD

**Issue by The-cpu-max** [xbmc/xbmc#23445] opened 2023-06-26 12:57 UTC
Hello everyone ,
I have a problem when I search for Jurial's Baskin movie in the Hebrew language through the search he created - I can't find anything
Only on the condition that I write in reverse script something that does not make sense
I am contacting you for a solution after I spoke with the developer and it was explained to me that the problem is not with the skin but with Kodi itself
This is how you write fast and furious in Hebrew - מהיר ועצבני
![image](https://github.com/xbmc/xbmc/assets/102416233/02204207-1cbe-4106-8496-38d69758a000)
And that's when you write in reverse Hebrew -ינבצעו ריהמ
![image](https://github.com/xbmc/xbmc/assets/102416233/8bc9391d-8e83-4d98-9997-991825bf58af)

---
name: Problem report
about: Create an extensive report to help us document a problem

---

### Describe the bug
Here is a clear and concise description of what the problem is:

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1.
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by The-cpu-max** [comment] 2023-06-27 17:42
help?

**Comment by scott967** [comment] 2023-07-01 01:53
At this point I think it is better to request support on the Kodi forum, as your usage problem seems to be at an intersection of an addon, a skin, and Kodi core.

**Comment by scott967** [comment] 2023-07-08 22:36
OK I have interest in properly handling RTL in Kodi, and since the issue originator failed to provide a debug log as requested/required I tried to duplicate a test environment by guessing what skin/addons are being used.  This skin I guess provides a custom search dialog window to implement an edit control and passes the entered text to addons to process.  From what I see it sets some filtered containers and in what gets logged the filter is properly constructed and matching results do get returned.  But in calling plugin.video.themoviedb.helper what is passed as the argument in sys,argv the Hebrew is reversed logical order.  I did a quick hack of the plugin to reverse the query argument viz:

```python
import unicodedata

def flip_rtl(arg_data:str) -> str:
    if unicodedata.bidirectional(arg_data[0]) == 'R':
        return arg_data[::-1]
    return arg_data
```

which is super hacky but as a quick and dirty it worked:

[Imgur](https://i.imgur.com/OgQ4cwq.png)

log here https://paste.kodi.tv/wojokagove.kodi

**Comment by The-cpu-max** [comment] 2023-07-09 09:01
> OK I have interest in properly handling RTL in Kodi, and since the issue originator failed to provide a debug log as requested/required I tried to duplicate a test environment by guessing what skin/addons are being used. This skin I guess provides a custom search dialog window to implement an edit control and passes the entered text to addons to process. From what I see it sets some filtered containers and in what gets logged the filter is properly constructed and matching results do get returned. But in calling plugin.video.themoviedb.helper what is passed as the argument in sys,argv the Hebrew is reversed logical order. I did a quick hack of the plugin to reverse the query argument viz:
> 
> ```python
> import unicodedata
> 
> def flip_rtl(arg_data:str) -> str:
>     if unicodedata.bidirectional(arg_data[0]) == 'R':
>         return arg_data[::-1]
>     return arg_data
> ```
> 
> which is super hacky but as a quick and dirty it worked:
> 
> [Imgur](https://i.imgur.com/OgQ4cwq.png)
> 
> log here https://paste.kodi.tv/wojokagove.kodi

What file do I need to change for this to work?
And what can happen if I use it?

**Comment by jurialmunkey** [comment] 2023-07-09 09:11
@scott967 

I think the crux of this issue is that there is no way for a skin to properly pass RTL text to a plugin:// content uri as `$INFO[Control.GetLabel(ID).index(1)]` is going to give the output label -- which is correctly reversed for display purposes but incorrect for the purposes of being a plugin path.

If I were to implement this workaround then I end up with the opposite problem - any internally constructed query param for RTL languages will be incorrectly reversed again when the plugin uri is parsed (e.g. when the user searches inside the plugin, the search path is saved as a history).

I guess I could add an additional flag to indicate a flip, but as you mention it's a hack -- and it really only solves it for my plugin but I'm still left with the same problem for plugins other than my own.

**Comment by scott967** [comment] 2023-07-09 23:30
Not sure why `$INFO[]` should ever return other than the logical text order?  But yes, if it's similar to `$ESCINFO[]` then there needs to be a way to get logical order.

**Comment by jurialmunkey** [comment] 2023-07-10 01:03
> Not sure why `$INFO[]` should ever return other than the logical text order? But yes, if it's similar to `$ESCINFO[]` then there needs to be a way to get logical order. 

The problem is that what is coming from plugin:// path via the edit control using `$INFO[Control.GetLabel(9099).index(1)]` is different to what it returned by the keyboard in python via `Dialog().input('', type=INPUT_ALPHANUM)`

So using the test string in the original issue `מהיר ועצבני` and pasting directly:

Edit control provides this paramstring from `sys.argv[2][1:]` (either directly into edit control or by clicking into keyboard).
`info=search&type=movie&query=ינבצעו ריהמ&nextpage=false&fanarttv=false&cacheonly=true`

Whereas internally the `Dialog().input()` keyboard returns the reverse (which works)
`QS מהיר ועצבני`

The internal version from `Dialog().input()` then gets percent encoded for saving to history cache:
`info=search&query=%d7%9e%d7%94%d7%99%d7%a8%20%d7%95%d7%a2%d7%a6%d7%91%d7%a0%d7%99&tmdb_id=None&tmdb_type=movie`

Which also works as it produces the same string when parsed:
`QS מהיר ועצבני`

> @jurialmunkey BTW, can you save me some time and advise where in the skin the plugin is getting called? Didn't see it at first glance.

It uses a skin shortcuts template to build each of the search options according to user customisation:
https://github.com/jurialmunkey/skin.arctic.horizon.2/blob/877032b993d9dcc453572acb57bde34bb8e524cd/shortcuts/template.xml#L772-L1005

Here is the path:
https://github.com/jurialmunkey/skin.arctic.horizon.2/blob/877032b993d9dcc453572acb57bde34bb8e524cd/shortcuts/template.xml#L985

```
<param name="content">$INFO[Control.GetLabel(9099).index(1),$SKINSHORTCUTS[widgetPath],$SKINSHORTCUTS[widgetPath2]]</param>
```

So for TMDbMovies for example those values are here:
https://github.com/jurialmunkey/skin.arctic.horizon.2/blob/877032b993d9dcc453572acb57bde34bb8e524cd/shortcuts/template.xml#L844-L845

So that generates:
```
$INFO[Control.GetLabel(9099).index(1),plugin://plugin.video.themoviedb.helper?info=search&amp;type=movie&amp;query=,&amp;nextpage=false&amp;fanarttv=false&amp;cacheonly=true]
```

i.e.
`plugin://plugin.video.themoviedb.helper?info=search&amp;type=movie&amp;query=$INFO[Control.GetLabel(9099).index(1)]&amp;nextpage=false&amp;fanarttv=false&amp;cacheonly=true`

**Comment by jurialmunkey** [comment] 2023-07-10 08:34
@scott967 - Further to the above, I think you might be right that it is something to do with how the skinning engine sets the `<content>` path to sys.argv

I didn't notice before but can see in the log it is correctly ordered when GetDirectory reports the path failed:
```
error <general>: XFILE::CDirectory::GetDirectory - Error getting 
plugin://plugin.video.themoviedb.helper/?info=search&type=movie&query=מהיר ועצבני&nextpage=false&fanarttv=false&cacheonly=true
```

But logging output of sys.argv[2][1:] that comes to plugin.py from that request it has been flipped somewhere between skin engine and plugin.
` info=search&type=movie&query=ינבצעו ריהמ&nextpage=false&fanarttv=false&cacheonly=true`

**Comment by scott967** [comment] 2023-07-19 03:58
At this point my operating theory is that Kodi is not properly forming sys,argv.  I note this seems to be the case even when literal strings are passed via runscript() built-in.  At least on Windows with Python 3.8, passing arguments from the command line via sys.argv does result in valid strings with unicode RTL chars so I don't think it is a windows or python issue.  I have to figure out/trace how Kodi sets sys.argv list of strings for python addons.

**Comment by scott967** [comment] 2023-07-20 23:56
OK the problem seems to be in the call to CPythonInvoker execute
At least for Runscript builtin, the parameters passed to the PythonInvoker are logical order utf-8 encoded as type char.  Here:
https://github.com/xbmc/xbmc/blob/50766b78cee5b3c602f677c8580f32e37dd5fad6/xbmc/interfaces/python/PythonInvoker.cpp#L127-L136

At least the string arguments passed into python as sys.argv must be in logical order. 
The problem is the call to 
```
g_charsetConverter.utf8ToW(argument, w_argument)
```
utf8ToW has argument `bool bVisualBiDiFlip ` which defaults to true.  Setting it to false in the call fixes this problem, though it might be better to only apply this to the arguments that are passed in for sys.argv -- not things like the pythonpath.  I have a PR for this, but it really needs some heavy duty testing IMO.  It could be considered for backport if this is the only change needed.

PR here:
https://github.com/xbmc/xbmc/pull/23532

Link to Windows x64 test build:
https://mega.nz/file/PPAxFLbb#Xp9c1Jo11yFSYOiAkIMTRQqw7Oq-QYe27lA-ZXPULuI

**Closed** 2023-07-26 16:11 UTC
Labels: Ignored rules, Triage: Needed

**Comment by test01203** [comment] 2023-08-02 05:25
> OK the problem seems to be in the call to CPythonInvoker execute At least for Runscript builtin, the parameters passed to the PythonInvoker are logical order utf-8 encoded as type char. Here:
> 
> https://github.com/xbmc/xbmc/blob/50766b78cee5b3c602f677c8580f32e37dd5fad6/xbmc/interfaces/python/PythonInvoker.cpp#L127-L136
> 
> At least the string arguments passed into python as sys.argv must be in logical order. The problem is the call to
> 
> ```
> g_charsetConverter.utf8ToW(argument, w_argument)
> ```
> 
> utf8ToW has argument `bool bVisualBiDiFlip ` which defaults to true. Setting it to false in the call fixes this problem, though it might be better to only apply this to the arguments that are passed in for sys.argv -- not things like the pythonpath. I have a PR for this, but it really needs some heavy duty testing IMO. It could be considered for backport if this is the only change needed.
> 
> PR here: #23532
> 
> Link to Windows x64 test build: https://mega.nz/file/PPAxFLbb#Xp9c1Jo11yFSYOiAkIMTRQqw7Oq-QYe27lA-ZXPULuI

Thank you very much, it works great
Just note that it doesn't work on the add-on
"script.module.autocompletion"
It's doing reverse there still

**Comment by scott967** [comment] 2023-08-03 23:04
Need link to your debug log showing the invocation of autocompletion that causes the error

**Comment by test01203** [comment] 2023-08-07 11:28
> Need link to your debug log showing the invocation of autocompletion that causes the error

[script.module.autocompletion.zip](https://github.com/xbmc/xbmc/files/12279121/script.module.autocompletion.zip)
It does not appear on the log

**Comment by scott967** [comment] 2023-08-07 22:05
I need to see from the log exactly how autocompletion is getting called otherwise I have to guess and experiment.

**Comment by test01203** [comment] 2023-08-08 05:01
> I need to see from the log exactly how autocompletion is getting called otherwise I have to guess and experiment.

This is when nothing related to this appears in the log
Harry Potter anyway
its הארי פוטר
The problem is that the name still needs to be written upside רטופ יראה
Install the add-on I uploaded and see

**Comment by scott967** [comment] 2023-08-10 23:02
Well aware of the module.  Typically driven by plugin plugin.program.autocompletion or imported into some other addon.  That's why I ask you humor me to post the log so I don't have to play hide and seek.
