### ISSUE TITLE
Local information provider does not consider local thumbnails for movies

### ISSUE THREAD

**Issue by RigacciOrg** [xbmc/xbmc#20937] opened 2022-02-01 16:19 UTC
### Describe the bug

I have several movies stored along with the related **.nfo** and **.tbn** files into a movie folder configured with **Local information only** provider. If I hit the **Update library** function (or the **Scan to library** over the single file), Kodi 19 will scan the .nfo file, but it does not consider the .tbn file.

If I provide the more modern **\<movie\>-poster.jpg** and **\<movie\>-fanart.jpg** files, Kodi find them, and update the artworks into the library. So I tried to provide **\<movie\>-thumb.jpg** or **\<movie\>-thumbnail.jpg**, but these are ingored.

However there is a way to let Kodi consider the .tbn file: from the movie's context menu choose **Information** => **Refresh**. It will find the .tbn artwork and it will use as thumbnail type. Another way to let Kodi find the .tbn file is calling the **VideoLibrary.RefreshMovie** function from the HTTP API.

With Kodi 18 I was used to automatically find the .tbn files after a mass upload, just executing the **Update library** function.

The problem is not quite visible at first time: if I upload a new file with .nfo and .tbn in Kodi, the thumbnail is correctly shown, but metadata from .nfo file are not loaded. As soon I update the library, the .nfo file is loaded and the thumbnail instead is lost: the default black/white movie icon is shown instead.

## Expected Behavior

I think that a **\<movie\>.tbn** file or a **\<movie\>-thumbnail.jpg** file should be added as thumbnail artwork when updating the library, when using local information only. This was the behavior of Kodi 18.

## Actual Behavior

Local thumbnail file is never searched during library update. It is found only on Information Refresh.

### To Reproduce

1. From Settings => Media => Videos => Artwork, disable the **Extract thumbnails from video files**.
2. Configure a video source with the info provider **Local information only**.
3. Upload to the video source a movie file, along with the .nfo and .tbn files.
4. Execute the **Update Library**.
5. The movie does not get its thumbnail, but the default movie icon.

### Debuglog

During Update Library no errors in kodi.log:

```
2022-02-01 17:36:20.426 T:1507     INFO <general>: VideoInfoScanner: Starting scan ..
2022-02-01 17:36:26.901 T:1507     INFO <general>: VideoInfoScanner: Finished scan. Scanning for video info took 00:06
```

### Screenshots

A new movie file is uploaded with .nfo and .tbn:
![01_new-movie-uploaded](https://user-images.githubusercontent.com/863803/152013783-addc046a-7668-49a9-838c-cc11652be75a.jpg)

Select Scan to library from Context menu:
![02_scan-to-library](https://user-images.githubusercontent.com/863803/152013839-fac3aa65-dad3-41af-b9e4-32963b8cf892.jpg)

Metadata are loaded from the .nfo file:
![03_nfo-file-loaded](https://user-images.githubusercontent.com/863803/152013855-c0cd5b3e-51d9-4b25-8635-62a0d217028c.jpg)

Thumbnail is lost:
![04_thumbnail-lost](https://user-images.githubusercontent.com/863803/152013871-ba5484a4-b73d-4f1c-83a8-77ce35dab97d.jpg)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Raspberry Pi with RaspiOS 11.2 Bullseye
 - Kodi version: 19.3

**Comment by KarellenX** [comment] 2022-02-01 19:54
@RigacciOrg 

Your report is not a bug and actually sounds like a feature request, so I will close this issue.

tbn is not used by Kodi and was deprecated a few versions ago. There is still some leftover code for tbn in amongst the spaghetti code, so it may work at times, but mostly not.

tbn will not be reinstated.

Adding an artwork type like `<movie>-thumbnail.jpg` does not mean it will automatically work. It is up to the skins to code the artwork type to display it. You can add `<movie>-bestartwork.jpg` images, Kodi will certainly cache it (with the correct artwork settings) but the skin has not been coded to display it, so it will never work.

In movies, thumb and thumbnail is a confusing artwork type. Is it landscape, portrait, square, other? Stick to the common artwork types Kodi uses as listed here... https://kodi.wiki/view/Artwork_types

**Closed by KarellenX** 2022-02-01 19:54 UTC
Labels: Ignored rules, Triage: Needed

**Comment by RigacciOrg** [comment] 2022-02-02 12:13
@KarellenX
many thanks for your clarification! I was confused due many left-over pages on the internet, talking about .tbn files. I started my Kodi library many years ago, using .tbn files and I missed the deprecation during the many Kodi upgraedes.

I recap here to help (may be) other users: to sovle the problem of .tbn files not properly used by Kodi:

- Rename all you existing **\<movie\>.tbn** files into **\<move\>-thumb.jpg**.
- Do an **Update Library**.

Just a thought: is the **\<file\>-thumb.jpg** artwork accepted in a stable manner? I read on the wiki that it is the "last option fallback", does it means that it will be deprecated in the foreseeable future?

**Comment by KarellenX** [comment] 2022-02-02 19:02
Hello @RigacciOrg 

Yes, the internet holds a lot of old or wrong instructions to use Kodi. Best to stick with the Kodi wiki pages or ask on the forum.

I stress again, it is best **not** to use -thumb for movies. It is a confusing artwork type, and different skins use it in different ways, so most times the image comes out squashed or stretched, which is not nice.

Decide which type of image the thumb actually is. 
If it is portrait then use **poster**
If it is landscape without text then use **fanart**
If it is landscape with text then use **landscape**

Check that artwork wiki page to understand the type of artwork used.

There are no plans to deprecate -thumb yet.
