### ISSUE TITLE
Power saving shutdown function minimize doesn't work on Nvidia Shield

### ISSUE THREAD

**Issue by VidgetGaming** [xbmc/xbmc#22589] opened 2023-01-25 22:24 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

Power saving shutdown function minimize doesn't work on Nvidia Shield

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

When I go to system settings and power saving and set the shutdown function timer to 30 minues and shutdown function to minimize I expect the Kodi application to minimize after 30 minutes and return me to my Nvidia Shield home screen.

## Actual Behavior

Kodi stays open. If I choose quit instead of minimize Kodi actually quits after 30 minutes but minimize does not work.

## Possible Fix

A solution was suggested in the bug report I sent in a year ago (https://github.com/xbmc/xbmc/issues/20848) but nothing was ever done about it.

### To Reproduce

1. Install Kodi on Nvidia Shield
2. Go to system settings and power saving
3. Set the shutdown function timer to 30 minutes, although I believe the error occurs at 5 minutes too
4. Set the shutdown function to minimize
5. Wait 30 minutes

### Debuglog

The debuglog can be found here:
I'm sorry I don't know how to create a debug log but I've tried on 4 different Nvidia Shield devices and the problem happens on every single one.

### Screenshots
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 11
 - Kodi version: 20

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by thexai** [comment] 2023-01-25 23:54
Duplicate of https://github.com/xbmc/xbmc/issues/20848

**Closed by thexai** 2023-01-25 23:54 UTC
