### ISSUE TITLE
Missing mediatype when setInfo used in xbmcplugin.setResolvedUrl

### ISSUE THREAD

**Issue by Dis90** [xbmc/xbmc#19378] opened 2021-03-09 20:57 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

When setInfo is used in xbmcplugin.setResolvedUrl() Kodi doesn't send mediatype to player. If setInfo is used when listing episodes to play then xbmc.Player.getVideoInfoTag().getMediaType() shows mediatype. While Kodi plays video it also doesn't display show name, season, episode etc. probably because it doesn't know it is playing episode. However it displays episode name, year and plot.

Why this is an issue? Because when using Up Next add-on we need to set video information in player and I don't know if it is bug in Kodi or Up Next but if next episode is partly or completely watched we run to this same issue.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi to set correct mediatype when using setInfo with xbmcplugin.setResolvedUrl()

## Actual Behavior

Mediatype is not send to player

### To Reproduce

_If you have discovery+ subscription you can use my add-on
https://github.com/Dis90/plugin.video.discoveryplus/blob/mediatype_issue/resources/lib/kodihelper.py
What I have done here is in line 167 I set not to use setInfo with listitem and from line 320 I set some debug logging to getVideoInfoTag()
You can change line 167 to use setInfo so you can see from log that Player videoinfo shows correct mediatype._

Edit. test add-on available https://github.com/Dis90/plugin.video.example
Uncomment lines 179-181 so you can see correct mediatype in Player videoinfo from log. When you comment those lines Player videoinfo mediatype is empty.

### Debuglog

The debuglog can be found here:
Log with listitem.setInfo('video', info): https://paste.kodi.tv/wikelisiye.kodi
Log with listitem.setInfo('video', {}) (only play_item sets info): https://paste.kodi.tv/kipedudase.kodi

Key parts of log can be find keywords 'Player videoinfo' and 'Listitem videoinfo'

### Screenshots 
Here are some links or screenshots to help explain the problem:

Listitem setInfo used
<img width="682" alt="img1" src="https://user-images.githubusercontent.com/1754572/110536180-d5783800-8129-11eb-9341-2664c4dba061.png">
SetInfo used in play_item
<img width="707" alt="img2" src="https://user-images.githubusercontent.com/1754572/110536202-db6e1900-8129-11eb-84bc-c1a21bb19ec9.png">

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [x] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Kodi 19

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Dis90** [comment] 2021-03-10 07:25
I think this PR is related to problem https://github.com/xbmc/xbmc/pull/17993
CVideoInfoTag::Merge doesn't have mediatype

**Comment by enen92** [comment] 2021-03-10 10:43
@Dis90 it'd be nice if you could provide a test addon or at least sample code to reproduce. The requirement to have a subscription to a premium service is not great for someone to take a look into this

**Comment by Dis90** [comment] 2021-03-10 13:31
Sorry. Issue can be tested with this https://github.com/Dis90/plugin.video.example
Uncomment lines 179-181 so you can see correct mediatype in Player videoinfo from log. When you comment those lines Player videoinfo mediatype is empty.

**Comment by CastagnaIT** [comment] 2021-03-11 08:48
When Kodi go in playback copy all info from the original listitem info to the player item
The merge method is used to override or add other info to the listitem
why you not set the mediatype to the directory listitems as usually be done?

**Comment by CastagnaIT** [comment] 2021-03-11 10:00
perhaps @MoojMidge can explains better something about what happen with UpNext?

**Comment by Dis90** [comment] 2021-03-11 10:02
> When Kodi go in playback copy all info from the original directory listitem info to the player listitem
The merge method is used to override (existing info to directory listitem) or add others info to the player listitem
why you not set the mediatype to the directory listitems as usually be done?

This is how add-on normally does it but for testing purposes I made player to add all info because that is what Up Next uses for already watched episodes. Why it handles watched episodes differently than unwatched, I don't know.

> I is more feasible that the problem is not in Kodi because the listitem have his info value, and this is never changed,
instead the UpNext behaviour in the last versions is changed, now manipulate the Kodi Playlist in order to play the next video.

I think this is partly Kodi problem because why setInfo doesn't add mediatype when used with setResolvedUrl ?
You can test infos with https://github.com/Dis90/plugin.video.example

> i think the listitems added by upnext to kodi playlist are without info this should be the cause (you can see by opening the playlist)
It's possible it is also Up Next bug.

**Comment by CastagnaIT** [comment] 2021-03-11 10:05
set the mediatype on setResolvedUrl is not needed because is set by the directory/playlist Listitem, if is missing should means that the directory/playlist Listitem is done in a wrong way...

**Comment by Dis90** [comment] 2021-03-11 10:12
Okay then it sounds like it's bug in Up Next add-on. Kodi devs can close this issue if mediatype doesn't need to work with setResolvedUrl.

**Comment by CastagnaIT** [comment] 2021-03-11 10:16
add an override for "mediatype" in setInfo seem not complex, but from my POV i see it as a wrong operation to do
i would like to wait for an answer from @MoojMidge before close this

**Comment by MoojMidge** [comment] 2021-03-11 11:06
To be honest I'm not too sure what is going on, but maybe I am misunderstanding the problem.

The previous method used for playback in UpNext was to use JSON-RPC Player.Open with a plugin:// url as the file parameter:
https://github.com/im85288/service.upnext/blob/b7efb9dc162db7c8d19f37bbb0ed0c5d78d85ace/resources/lib/api.py#L98

To me this should have resulted in exactly the same behaviour as using  JSON-RPC Playlist.Add with the same plugin:// url as the file parameter.

By the time the plugin url is access and routed to the playback handler method in the add-on where setResolvedUrl is called, UpNext has already completed its job and is no longer part of the equation. The listItem that is passed to the serResolvedUrl call should have setInfo called with appropriate infoLabels data, and this new listItem should be the one used to actually play the video and display its info, with the set video info, including mediatype.

**Comment by Dis90** [comment] 2021-03-11 11:36
> Do you actually mean to say that you are re-playing a video from a directory listing? In this instance I believe Kodi will not try and play the listing using the plugin url, but instead use the url (and listItem) that was previously resolved. This may be why you are not seeing the information displayed by UpNext, because your playback handler method is no longer being called and is therefore not sending anything to UpNext. Instead only the video info previously applied using setInfo will be able to be pulled from the listItem.

Scenario: I'm already watched episode 1 and completely or partly watched next episode (Episode 2). Then I start first episode again and Up Next popup shows up correctly at the end but when next episode (Episode 2) starts I'm missing mediatype information and Up Next doesn't show popup for Episode 3.

**Comment by CastagnaIT** [comment] 2021-03-11 11:42
i think there are more than one problem here...
i just tried the mentioned scenario above with Ntflx addon and also to me the third episode not show the upnext popup
I'll try to debug kodi later

**Comment by MoojMidge** [comment] 2021-03-11 13:10
I think there are certain conditions that always trigger the "caching" behaviour that explains what @Dis90 is seeing.

Try the following:

1. Create a list of playlist of plugin:// urls that get resolved using setResolvedUrl
2. Play playlist
3. Stop any episode half way through so that a resume point is created
4. Re-play the previously stopped episode
5. Episode will play using the resolved url, not the original plugin:// url

The reason I didn't see it before was because I was skipping through the episodes, either right to the end, or stopping them too soon for a resume point to be created.

**Comment by CastagnaIT** [comment] 2021-03-12 09:20
i have some problem
i cannot debug Kodi with nflx addon because the DRM make crashing the debugger

i have tried to integrate upnext roughly in the test addon above, but still say:
Error: no episode could be found to play next...exiting

and the popup is not shown, i not able to find the problem
if someone have time to fix it: [plugin.video.example.zip](https://github.com/xbmc/xbmc/files/6128875/plugin.video.example.zip)
and attach a working fixed version
so i will try debug kodi without DRM

**Comment by Dis90** [comment] 2021-03-12 14:42
@CastagnaIT try with this
[plugin.video.example.zip](https://github.com/xbmc/xbmc/files/6130691/plugin.video.example.zip)

**Comment by CastagnaIT** [comment] 2021-03-13 14:44
@Dis90 thanks, now i have debugged Kodi a bit, and i dug a little deeper to better understand

so basically when UpNext addon starts the next-video with:

```python
jsonrpc(method='Playlist.Add', id=0, params=dict(playlistid=1, item=next_item))
```

this cmd instruct Kodi to add to Kodi playlist a empty ListItem with only the video path to call,
this empty ListItem has no type, no info, no properties etc... (i thought there was a lookup on addon directory i remember wrongly...),
then every addon is forced to add the missing data (info/art etc...) to fill the gap in the callback,
therefore what you mentioned about the PR of the missing "type" override is right, but in theory could be avoided
by replacing the above Upnext code with

```python
playlist = xbmc.PlayList(xbmc.PLAYLIST_VIDEO)
listitem = xbmcgui.ListItem(video, offscreen=True)
listitem.setInfo(..)
listitem.setArt(..)
playlist.add(url=path, listitem=listitem)
```

this would add a ListItem to Kodi with all the info included (upnext basically has already requested them) and so avoid the addons to force refill again the data on play callback and then speed up the starts of playback itself,
but i don't know if it would work when playing with Kodi library, upnext is not my field.

I can create the PR to add the missing "type" parameter,
i have already tested it locally and of course works

**Comment by Dis90** [comment] 2021-03-13 15:39
Thanks for testing :)

> I can create the PR to add the missing "type" parameter,
i have already tested it locally and of course works

Please create PR. I think someone just forgot to add mediatype to listitem parameters when setInfo is used with setResolvedUrl.

**Comment by enen92** [comment] 2021-03-13 18:03
Sorry for having closed this one, I though the fix was for an addon. Reopening.

**Comment by MoojMidge** [comment] 2021-03-14 08:06
I don't think there is any issue with the proposed PR, but I don't think it will fully resolve the problem with UpNext, although it will fix the problem with mediatype getting discarded.

The following is a high level sequence of events when a typical video addon uses setResolvedUrl (I may be mistaken as I only have a very superficial knowledge of actual Kodi internals, which I am glossing over):

1. Addon creates a directory listing with a bunch of listItem entries
    - listItem entries have video info set using setInfo and setProperty
    - listItem path is set using setPath to a plugin://addonid/?param=val path
2. User clicks on an entry in the directory listing and the addon is called using the listItem path
3. Addon routes the call to its playback handler using the parameters in the listItem path
4. At this point the addon typically has no reference to the listItem that was clicked in Step 2 (noting that Steps 1 and 2 may not ever occur, the addon could instead be called using a playlist, skin shortcut, favourite, etc., so while Kodi may be keeping track of things internally, the addon will have no knowledge of this)
5. A new listItem is created
    - listItem entries have video info set using setInfo and setProperty
    - listItem path is set using setPath to the actual stream path
6. Addon calls setResolvedUrl
    - original_listitem_url is set to listItem path from Step 1 or equivalent
    - m_fileResult is set
    - Merge is called, here PR #19402 will take effect and the original set mediatype will no longer be discarded
7. Resolved url is used and all is good
8. Stuff happens
9. At some point cache file state gets reset and the effects of setResolvedUrl in Step 6 is reset
10. Goto Step 2

The problem is somewhere along the track Step 9 does not completely/successfully occur, and the effects of setResolvedUrl in Step 6 are not reset. An example of some such circumstance is as per https://github.com/xbmc/xbmc/issues/19378#issuecomment-796724532

When the effects of setResolvedUrl in Step 6 are not reverted, Steps 2, 3, 4, 5, and 6 will not occur, and instead when the listItem is clicked, Kodi will jump straight to Step 7, except this time all is not good anymore.

UpNext relies on the video addon telling it what video is playing, and what video is next, in Step 5. If this step is skipped then you see the behaviour where UpNext does nothing when resuming a previously stopped episode.

**Comment by CastagnaIT** [comment] 2021-03-14 08:50
> The problem is somewhere along the track Step 9 does not completely/successfully occur, and the effects of setResolvedUrl in Step 6 are not reset. An example of some such circumstance is as per #19378 (comment)
> 
> When the effects of setResolvedUrl in Step 6 are not reverted, Steps 2, 3, 4, 5, and 6 will not occur, and instead when the listItem is clicked, Kodi will jump straight to Step 7, except this time all is not good anymore.
> 
> UpNext relies on the video addon telling it what video is playing, and what video is next, in Step 5. If this step is skipped then you see the behaviour where UpNext does nothing when resuming a previously stopped episode.

I think I understand what you want to explain,
but this is OT from this Issue scope,
the add-on callback management with resume point is an different matter

but we can talk about it on "add-ons" slack,
maybe i could try debugging kodi with the test add-on above to find some more info

**Comment by MoojMidge** [comment] 2021-03-14 10:33
Technically yes, this issue is about mediatype being lost when VideoInfoTag was merged, but I'm pretty sure that is not what was actually causing this problem: https://github.com/xbmc/xbmc/issues/19378#issuecomment-796673440 it is just a symptom of the actual problem.

UpNext does not use mediatype except for library content, but I can intermittently replicate the problem when stopping and resuming plugin:// content

**Closed** 2021-03-21 10:29 UTC
Labels: Triage: Has proposed fix
