### ISSUE TITLE
Kodi v20 Crashes when scrolling through files

### ISSUE THREAD

**Issue by CurtisLeeBolin** [xbmc/xbmc#22697] opened 2023-02-05 03:59 UTC
### Describe the bug
Videos -> Files -> a directory with many files
Hold the down arrow
Kodi completely terminates

I can reproduce this on 3 computers with similar hardware.  I can not reproduce in a VM.  I have even tried renaming the setting directory so it creates fresh settings files on startup.

I have downgraded to kodi-19.5 with no further problems.

## Expected Behavior
Scroll through files

## Actual Behavior
Kodi crashes

### To Reproduce
Videos -> Files -> a directory with many files
Hold the down arrow
Kodi completely terminates

### Debuglog
[kodi_crashlog-20230204_142143.log](https://github.com/xbmc/xbmc/files/10610166/kodi_crashlog-20230204_142143.log)

[debug-kodi_crashlog-20230204_143904.log](https://github.com/xbmc/xbmc/files/10610167/debug-kodi_crashlog-20230204_143904.log)

[gdb.txt](https://github.com/xbmc/xbmc/files/10610168/gdb.txt)

### Your Environment
Used Operating system:

 - [X] Linux

Arch Linux
Kodi 20.0

**Comment by lrusak** [comment] 2023-02-05 04:30
duplicate of #22473 which has already been fixed.

**Closed by lrusak** 2023-02-05 04:30 UTC
