### ISSUE TITLE
Audio info not updated when replacing a video file with same name but different audio!

### ISSUE THREAD

**Issue by gate1975mlm** [xbmc/xbmc#15584] opened 2019-02-22 16:22 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

In Kodi 18 if you have a Movie for example "Rocky" that has Dolby Digital audio and then you replace it with a newer "Rocky" that has DTS audio. The movie information will remain showing Dolby Digital instead of DTS.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Audio info should be updated when replacing a movie with the same name but different audio!

## Actual Behavior

Audio info is never updated when replacing a Movie or TV Show with the same name but different audio!

## Possible Fix

Only fix would be to go back to Kodi 17 and use Metropolis Skin as the audio info always got updated after starting a movie with the new audio. However even in Kodi 17 the default Estuary Skin would not show the updated audio info.

### To Reproduce

1. Add a Movie with Dolby Digital
2. Replace same movie with DTS version
3. Check audio info for same Movie and it will still say Dolby Digital when it should now say DTS!

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by arnova** [comment] 2019-02-22 19:19
This is by design. Unfortunately there is no easy (except checking timestamps which is "costly") to fix your specific case. Only thing I can suggest is playing the item for a few seconds which should update its flags (possibly updating video info also triggers this, not sure).

**Comment by gate1975mlm** [comment] 2019-02-22 20:39
No matter how long I play the replacement the audio info does not chance.

It's just strange because it did update with Kodi 17 and  Metropolis Skin.

So what changed in Kodi 18?

**Comment by gate1975mlm** [comment] 2019-02-22 20:44
I just wanted to add that it does shoe the correct audio in the video overlay.

But not when highlighting the movie in the movie directory.

**Comment by KarellenX** [comment] 2019-02-22 22:01
@arnova 

A similar report here for Windows... https://forum.kodi.tv/showthread.php?tid=341100

The thread from the OP of this issue... https://forum.kodi.tv/showthread.php?tid=341177

**Comment by KarellenX** [comment] 2019-02-23 01:20
I can confirm this issue also.

Steps...

1. Scrape movie into library and view flags in library display
Log Line 972... https://paste.kodi.tv/oqepateyed.kodi
2. Exit Kodi
3. Replace video file with one of a different quality and start Kodi
4. Play upgraded video. Log Line 750... https://paste.kodi.tv/zihacozapi.kodi

Checking the flags before and after playing the new file, the codec flags do not change and are incorrect - Image 1
Checking the flags during playback in OSD, codec flags are correct.- Image 2
Checking streamdetails table, no changes recorded.

Image1:
![oldvideo](https://user-images.githubusercontent.com/44626605/53279452-93f3da80-3764-11e9-97e9-bcd5a92e8ee6.jpg)

Image 2:
![newvideo](https://user-images.githubusercontent.com/44626605/53279454-9a825200-3764-11e9-86ef-c1092d1cfd18.jpg)

**Comment by arnova** [comment] 2019-02-23 07:12
Ok, if my suggestions didn't update the info, it's a regression. I'll look into it, but I don't know when.

**Comment by arnova** [comment] 2019-02-23 08:31
#/15589 should fix this

**Comment by DaVukovic** [comment] 2019-02-23 09:11
Sounds like a duplicate of #15413 

Thanks for the fix @arnova  :+1:

**Closed** 2019-03-04 08:19 UTC
Labels: Database, v18 Leia
