### ISSUE TITLE
Scaling crop issue 18.7 on Firestick

### ISSUE THREAD

**Issue by Testato** [xbmc/xbmc#17973] opened 2020-05-31 09:41 UTC
With the new Kodi 18.7 on Firestick there is scaling problem.
I reinstalled the 18.6 version and there isn't problem.

The bug is reproducible using the La7/La7d addon from the official repository. On this addon all the On-Demand programs is at 720x576 px and all is cropped.
If on the same plugin you try the Live channels there isn't problem, the Live streaming is at 960x544 px.
On Ubuntu instead the problem is never present

So the scaling problem seems to be present on FireTV Stick and only at 720x576 resolution

**Comment by enen92** [comment] 2020-05-31 09:57
Duplicate of https://github.com/xbmc/xbmc/issues/17963 ?

**Comment by fritsch** [comment] 2020-05-31 13:41
Most likely. Please tonight's nightly Leia build (it's not yet there), it should have that fixed.

**Comment by Testato** [comment] 2020-05-31 16:19
This build solved the problem 
https://github.com/xbmc/xbmc/issues/17963#issuecomment-636312623

**Comment by Testato** [comment] 2020-06-21 19:36
I reopened this isdue becauwe with ver 18.7.200 the scaling problem is solved but on my addon the DRM protected Live Stream is brocken.

**Comment by fritsch** [comment] 2020-06-21 19:38
Please open a new that reflects the new bug and also update your logfiles, please.

**Closed by fritsch** 2020-06-21 19:38 UTC
Labels: Ignored rules, Triage: Needed
