### ISSUE TITLE
Kodi music library update causes songs to change userrating.

### ISSUE THREAD

**Issue by cmsimike** [xbmc/xbmc#14996] opened 2018-12-05 05:36 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

Throughout my time with Kodi, every so often I would notice random changes in certain metadata in my music library. This caused me to start taking before and after snapshots of the MySQL MyMusic60 database before and after each music library update to see if I can figure out what's going on.

Today I was able to catch a Kodi music library update that caused songs (that have been in my music library since 2017) to change userrating from a 0 to a 10. Oddly, this happened to one entire album (each track in the album), which was changed to a 10 userrrating, from a 0.

For what it's worth, this isn't the first time Kodi seemed to change an entire album to a new userrrating.
https://www.reddit.com/r/kodi/comments/9fb6wb/kodi_rating_songs_userrating_by_itself/
I looked throughout the mp3 metadata and nothing popped up. I thought maybe Kodi picked something up, as I've been migrating my music into Kodi. 

This instance I was finally able to see the userrating chang in action and capture a debug log. I was able to replicate it perfectly as well meaning:
1) I took a dump of the MySQL database
2) updated the music library
3) Checked the current MyMusic60 database vs the previous snapshot and noticed the changed userrating to one song
4) Restored the MyMusic60 database back to how it was before step 2. Confirmed the database metadata was now identical to when it was in step 1.
5) Re-ran the library update
6) Compared the result of this library update, and noticed the metadata had changed exactly as it did in step 4

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I think whenever Kodi updates the music library, it should not change userrating or iTimesPlayed (which I've also seen in similar situations, after a music library update). 

## Actual Behavior

Seemingly randomly, after a music library update, I will notice changed values in userrating or iTimesPlayed.

### To Reproduce

1. Take a snapshot of your MySQL database using this query:
`select strPath, strFileName, strArtists, strTitle, strAlbum, userrating, iTimesPlayed, dateAdded from songview where (iTimesPlayed > 0 or userrating > 0) order by strFileName;`
This query will return any song that has been played or rated, ordered by strFileName (which helps make diff-ing easy when dumped to CSV)
2. Update your music library
3. Repeat step 1, use a diff tool (I used meld) to see the differences in iTimesPlayed and userrating.

### Debuglog

The debuglog can be found here:

I have a debug log, taken from when Kodi started, through the entire library update, and right before I closed Kodi. It is about 8.3M, and does have some personal library info. I would love to send this to you if there is a way I can directly send it. 
Alternatively I will happily trim out whatever you want and paste it here.

### Screenshots 
Here are some links or screenshots to help explain the problem:

Here is a screen shot of the after CSV - note the green background, and the arrow pointing to the left. This indicates the line was added.

![image](https://user-images.githubusercontent.com/204378/49492198-2e025180-f80c-11e8-83a0-dd41ae4fdf07.png)
The ordering here is (Do It Again (RYXP Version), The Inevitable End, 10, 0)
10 is user rating in this case, and 0 is play count. I have 100% not rated this song, or the rest of the songs in the albums.

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu 18.04 using the PPA
 - Kodi version: 17.6

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaveTBlake** [comment] 2018-12-05 08:44
Thanks for this report. It is odd though and not something that has been reported before AFAIK.  I have not been able to repeat yet in Windows with SQLite so maybe MySQL/Linux related although I can't see why that would be the case. It is more likely to be specific to your music files, but we will see.

>I have a debug log... I would love to send this to you if there is a way I can directly send it.

You can upload it somewhere and email me a link.

But mostly I would like to know if you can reproduce this with your music files, maybe a small test set of them, using v18.

**Comment by cmsimike** [comment] 2018-12-05 16:35
@DaveTBlake Thank you for the reply. Can you point me to an email I can send this log to you at? Or if you'd rather not post it here, my email address is my github user name at gmail.com. If you send me something there, I can reply with the full log.

If I can duplicate what I'm finding tonight, I'll also trying with a clean .kodi dir (only having the needed files for sources and mysql) and see if the issues still persist.

I am very hopeful that it is something specific with my configuration. 

I've been waiting for v18 to officially come out so I can debug this. I've wanted to debug this issue for a long time, but have found building 17.6 (so I can have a debug version) pretty difficult, while building 18 was straight forward with the new build instructions. If you know how I can obtain a pre-built debug version of v17.6, maybe I can figure out what's going on with it before 18 comes out.

**Comment by DaveTBlake** [comment] 2018-12-05 17:32
>I've been waiting for v18 to officially come out so I can debug this. I've wanted to debug this issue for a long time, but have found building 17.6 (so I can have a debug version) pretty difficult, while building 18 was straight forward with the new build instructions. 

Not sure I understand, please try **v18 RC2**  - no need to wait for final release, and you say it is easy for you to build! None of the team are looking back at v17, and there has been 2 years of development and changes, so the first question is can this odd behaviour be reproduced in v18.

I could understand loosing song user rating and timesplayed during library update, it could happen if for some reason Kodi fails to recognise/fetch the original song data from the db when rescanning a changed music file (or one it thinks has changed when checking hash of file name and timestamp). I have not seen it happen or heard of it happening to other users but I can see a possible mechanism. Setting rating to 10 or timesplayed to a different (non zero) value is most odd. Is it repeatable for specific albums or songs?

I'll make contact by email for the log, but digging around with v17 is not going to be productive for either of us, so try v18.

**Comment by DaveTBlake** [comment] 2018-12-06 09:34
Thanks for the debug logs. I can see two issues:
1. Unchanged music files are being rescanned on library update. There is a known issue with Samba and the way Kodi makes hashes of filename, size  and timestamp that it checks to see if the file has changed. After clock change the hashes produced are different than before, and so files get unnecessarily rescanned. See https://forum.kodi.tv/showthread.php?tid=336982&pid=2793130#pid2793130

2. Tagging. Kodi is not matching the 2 song artists to the pair of mbids.  You gave example with 
    artist          : Röyksopp feat. Robyn
    Artists         : Röyksopp/Robyn
    MusicBrainz Artist Id: 1c70a3fc-fa3c-4be1-8b55-c3192db8a884/5a8e07d5-d932-4484-a7f7-e700793a9c94
There is an ARTISTS tag but if single frame value then it needs the slash-space-slash separator e.g.  "Röyksopp / Robyn". What tag format version are you using ID3 v2.3 or v2.4? Or is it mixed? 

But what I still have not determined is how either of that results in Kodi inserting a song into the db with user rating of 10 _and_ a different track Musicbrainz id from what the tag example shows.  I think there is either something in the tagging or an issue with the way they are being read. Not sure about what exactly ffprobe reports for multi-frame values , so can email me a link to the example music file and I can poke about.

**Comment by DaveTBlake** [comment] 2018-12-07 09:02
Yes the unnecessary rescan of music files on SMB drives after clock change probably goes way back. It is something I will look at for v19 but I don't want to start messing with how the hashes are created this late in the release cycle.

> I would love it if songIds didn't change thoughout the life of the song

The delete/insert approach to rescanned songs is fundamental to the process and part of the original implementation. I can see why it was done that way, but there are some disadvantages too and I have had ideas about refactoring this, just need to find the time to undertake such a major change and all the testing that will be needed.

Anyway, to the issue. 
Thanks for the music file, the reason that user rating is being set to 10 is because Kodi is simply reading that rating from the tags. Looking at the file using Mp3Tag it is tagged with a POPM (Mp3tag calls this RATING WMP) value of 5 (out of 5). Rating values found in tags are reapplied when the file is rescanned.

>I looked throughout the mp3 metadata and nothing popped up

You may not be seeing this tag using ffprobe, but it is there. The answer, as it is so often, is to correct your music file tagging.

That file is tagged with both ID3v1 and ID3v2.3 format metadata. That of itself is not an issue but could be if there are conflicting values, and not all tagging tools show the mixed format values. So I would encourage people to use one format (and clear the v1 tags) unless they have a good reason for them to be there. 

Also  ID3v2.3 does not support multiple-frame tags so instead individual values need to be indicated using a standard separator. The  ID3v2.3 standard suggests using "/", but that is a poor choice because of bands like "AC/DC" and thus it became common to use " / " (slash-space-slash) instead. This is the Kodi default separator. However it is better still to use a tag format like ID3v2.4 that does support multi-frame values. 

So my recommendation is that you clear the metadata and retag using ID3v2.4 format tags. You can use Musicbrainz Picard to do that. I would add `$setmulti(albumartists,%_albumartists%)` to the advanced scriping options first, just to handle collaboration albums (multiple album artists) nicely.

**Comment by cmsimike** [comment] 2018-12-07 18:02
First - I want to THANK YOU again for your time looking into this. I guess my understanding of MP3s, specifically tags, was no where near as complete as I thought. I had previously had issues with userratings seemingly popping up and when looking at (what I thought was a complete list of) tags, nothing was there.
I will double check these mp3s again now.

Thank you for your input on how to properly tag my files. I'll try my best to get any new tags (and see if I can rework some old tags) into better shape.

I guess my last question (maybe this was addressed and I missed it) is why would Kodi suddenly mark change the userrating now, when it's been in my library for about a year?
I went through my MySQL backup dumps and at least that file has been around since oct 1 '18. My expectation is that, if there was a tag that is read as userrating by Kodi, wouldn't Kodi have picked it up on the first scan when it was imported into my library?

**Comment by DaveTBlake** [comment] 2018-12-07 18:37
I think it is my mission to improve the world's music file metadata one person at at time :)

If you have not been manually setting user ratings then you can check for songs with ratings in your db for hints where tagging needs checking. Also check the artist table for combined artist names e.g. "Röyksopp/Robyn" rather than individuals, with the right tagging (check the forum where I have posted about it frequently) Kodi can identify the separate artists.

>I guess my last question (maybe this was addressed and I missed it) is why would Kodi suddenly mark change the userrating now, when it's been in my library for about a year?

I didn't dig that deep, I found the rating tag via Mp3tag and could see Kodi v18 reading it. I did notice that Musicbrainz Picard did not show it.  It has been in your library "about a year", but what version of Kodi did you use to scan it into the library the first time? Did you then migrate the db to a new version of Kodi without rescanning? Kodi uses Taglib library of routines to read the metadata, this too may have been updated over the period and found more tag data than before. Has anything else, another media player like WMP or Media Monkey that can add rating values (something Kodi does not do) modified the music file? I really can't be sure what happened without more historical details that you don't have.

Going to close this issue as solved. 
If you would like more tagging advise or have questions then post on the forum https://forum.kodi.tv/forumdisplay.php?fid=263 and I will happily respond.

**Comment by DaveTBlake** [comment] 2018-12-07 18:39
Was a tagging issue (unexpected rating tags in the music file that not all tag redaer show but Taglib can read)

**Closed by DaveTBlake** 2018-12-07 18:39 UTC
Labels: Music, Solved
