### ISSUE TITLE
Resume Transport Stream, SeekTime - unknown position after seek

### ISSUE THREAD

**Issue by Portisch** [xbmc/xbmc#23431] opened 2023-06-23 07:31 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

Transport stream media files can't be resumed.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Seek to resume position.

## Actual Behavior

It start again at beginning with wrong PTS.
Looks like a ffmpeg 6 issue.

### To Reproduce

1. start TS media file
2. seek forward like to 5 or 30min
3. stop playback
4. start same TS media file again and select resume from last position

### Debuglog

The debuglog can be found here:
[kodi.log](https://mega.nz/file/PXhTUQCT#D0gu0CJtzn4Un66jG3CN2oAL2UTYczUQNBiAB-HwADU)
At Megaupload as size > 1MB.

```
2023-06-23 09:23:53.431 T:1375630   debug <general>: ffmpeg[0x558125705f80]: [mpegts] read_seek: 0 -9223372036692000000
2023-06-23 09:23:53.431 T:1375630   debug <general>: ffmpeg[0x558125705f80]: [mpegts] gen_seek: 0 -9223372036692000000

2023-06-23 09:23:53.431 T:1375630   debug <general>: SeekTime - unknown position after seek

2023-06-23 09:23:54.902 T:1375630   debug <general>: VideoPlayer::Sync - Audio - pts: 18442240474082181120.000000, cache: 369858.642452, totalcache: 799958.348274
2023-06-23 09:23:54.902 T:1375630   debug <general>: VideoPlayer::Sync - Video - pts: 102481911536178249728.000000, cache: 50000.000000, totalcache: 100000.000000
```

### Screenshots 
Here are some links or screenshots to help explain the problem:

![Screenshot from 2023-06-23 09-12-40](https://github.com/xbmc/xbmc/assets/3938570/423ef761-8b9d-44aa-a521-6f71cc7d7d33)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
Ubuntu 20.04
CoreELEC 21

 - Kodi version:
21.0 Alpha 1

As it's a ffmpeg 6 issue all Platforms using it are affected.
Alpha 2 and nightly have same issue but I did not find a current install or nightly for Ubuntu.
So the log is from 21.0-alpha1.

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by rainman74** [comment] 2023-06-24 15:36
With every Android nightly build after 21.0-alpha2, resume and fast-forwarding and rewinding are no longer possible. Kodi then either crashes or hangs up.

Perhaps this is also related to this error.

**Comment by chucky88** [comment] 2023-06-24 16:27
> With every Android nightly build after 21.0-alpha2, resume and fast-forwarding and rewinding are no longer possible. Kodi then either crashes or hangs up.
> 
> Perhaps this is also related to this error.

same here, last several nightly builds cannot fast-forward or rewind (at least with MKV). Android TV 9.

**Comment by Portisch** [comment] 2023-06-26 07:43
As this ffmpeg 6 issue essential break Kodi Omega there is not interests by TK?
ffmpeg 6 makes Kodi unusable as daily used device.

**Comment by Portisch** [comment] 2023-06-26 09:21
I just did downgrade ffmpeg to 5.1.2:
`2023-06-26 11:15:20.889 T:937      info <general>: FFmpeg version/source: 5.1.2`

But the resume from last stopped position is still broken. So something else is really going wrong in Kodi Omega.

**Comment by popcornmix** [comment] 2023-06-26 10:35
This is a duplicate of https://github.com/xbmc/xbmc/issues/23199
(so also occurs on Pi)

**Comment by Portisch** [comment] 2023-06-26 10:37
So the issue is known already since months but no comment?

**Comment by Portisch** [comment] 2023-06-28 16:59
![IMG_20230628_185720](https://github.com/xbmc/xbmc/assets/3938570/80692077-a6a8-4b5c-8ad6-d9ba79420f36)
Right now Kodi Omega is not usable at all. It lock up and only a hard kill does help.

**Comment by rainman74** [comment] 2023-06-30 10:12
@ksooo Please take a look at this error. This is a serious error that also affects all video files (mkv, mp4,...) Fast-forwarding and rewinding is generally no longer possible in the Omega nightlies.

**Comment by ksooo** [comment] 2023-06-30 10:50
@rainman74 what makes you think I could be of help here? I have almost no knowledge about VideoPlayer

**Comment by vpeter4** [comment] 2023-06-30 15:06
Is there anyone who could fix this? 2 months and no progress doesn't look good in my opinion .....
Whoever bump the package should also take care of such issues or at least find a person with some deeper knowledge.

**Comment by lrusak** [comment] 2023-06-30 15:26
> Is there anyone who could fix this? 2 months and no progress doesn't look good in my opinion .....
> 
> Whoever bump the package should also take care of such issues or at least find a person with some deeper knowledge.

That's alpha baby

**Comment by vpeter4** [comment] 2023-06-30 15:29
You are the baby :)

Even if alpha after 2 months I would expect such core issues should been fixed. So Kodi 21 is just playground without any useful thing right now ...

**Comment by Portisch** [comment] 2023-06-30 15:30
> That's alpha baby

It does not look good for such project if the base get more worse by adding other not important changes instead keep some quality. And no comment of any dev for months isn't showing quality as well...

**Comment by lrusak** [comment] 2023-06-30 16:24
Closing as duplicate of #23199

**Closed** 2023-06-30 16:24 UTC
Labels: Triage: Needed

**Comment by ksooo** [comment] 2023-06-30 16:54
Well I think I need to shout at my team of 20 full time employed Kodi devs here that they should do their f*****g job! … Oh wait, there is nobody in the position here to shout at anybody and nobody with ANY obligations regarding how many time to spend on Kodi. Wochen to the world of open source projects driven 100% by unpaid volunteers, doing all this in their spare time after work.
