### ISSUE TITLE
ERROR: SQL: [MyVideos116.db] SQLite error SQLITE_ERROR (no such column: movie_view.c0)

### ISSUE THREAD

**Issue by elbowz** [xbmc/xbmc#18213] opened 2020-07-25 19:16 UTC
### Describe the bug

The error (in the issue title) appear after a **Global Search** and **Movie/Tv show filter**. 
In the reported results don't appear any movies and tv show.
I have tried to cancel the file *MyVideos116.db* and regenerating from scratch...kodi.log is referred to that attempt.

### To Reproduce

1. Search in the global search or filter in movies / tv show

### Debuglog

The debuglog can be found here:

https://pastebin.com/hnPG9xv2

### Your Environment
Used Operating system:

 - [x] Linux

 - Operating system version/name: Ubuntu 20.04 LTS, kernel: Linux x86 64-bit version 5.4.0-42-generic 
 - Kodi version: Kodi (18.7 Git:20200520-f14f7a84e3)

**Comment by KarellenX** [comment] 2020-07-25 20:35
Strange. I can see the error in the logs at line 1500, but I cannot replicate it on Windows using v18.7 and Global search v8.0.13

Maybe @ronie can see why.

**Comment by elbowz** [comment] 2020-07-25 20:41
line 1500 ? don't you talk about my kodi.log (on line 209*).
Anyway, If I can help, make me know

... thanks !

**Comment by ronie** [comment] 2020-07-25 21:30
> Maybe @ronie can see why.

i've seen it reported on the forum as well:
https://forum.kodi.tv/showthread.php?tid=224794&pid=2921033#pid2921033
apparently it has something to do with the version of fmt.

it was fixed in master:
https://github.com/xbmc/xbmc/pull/17351

**Comment by DaveTBlake** [comment] 2020-07-25 21:33
`select * from movie_view  WHERE ((movie_view.c0 LIKE '%c%'))` 
is not going to work as the column is call `c00`

**Comment by DaVukovic** [comment] 2020-07-25 22:31
Just to mention it: 
https://www.ubuntuupdates.org/package/core/focal/universe/base/libfmt-dev
seems Ubuntu 20.04 uses 6.1.2+ds-2
Not sure if that's the cause then

**Comment by elbowz** [comment] 2020-07-25 22:54
> Maybe it was self compiled rather than installed from our ppa and was compiled against this lib. I can test an Ubuntu 20.04 in a VM tomorrow to see if I can replicate

```
$ apt policy kodi            
kodi:
  Installed: 2:18.7+git20200520.1011-final-0focal
  Candidate: 2:18.7+git20200520.1011-final-0focal
  Version table:
 *** 2:18.7+git20200520.1011-final-0focal 500
        500 http://ppa.launchpad.net/team-xbmc/ppa/ubuntu focal/main amd64 Packages
        500 http://ppa.launchpad.net/team-xbmc/ppa/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status
     2:18.6+dfsg1-2ubuntu1 500
        500 http://it.archive.ubuntu.com/ubuntu focal/universe amd64 Packages
```

**Comment by DaveTBlake** [comment] 2020-07-26 15:58
The cause is that  Ubuntu 20.04 pulls in libfmt 6, and that causes problems explained here https://github.com/xbmc/xbmc/pull/17318/#issuecomment-583836881

Already fixed for v19 by https://github.com/xbmc/xbmc/pull/17351

Fix for v18 by https://github.com/xbmc/xbmc/pull/18216 (a backport but with C++11 code) and holding 18.8 release to be able to include it. Are you able to test that @elbowz?

**Comment by elbowz** [comment] 2020-07-26 16:04
Is there some PPA for 18.8? ...or alternative to compilation?

**Comment by wsnipex** [comment] 2020-07-26 16:26
I'll prepare test packages, will let you know.

**Comment by elbowz** [comment] 2020-07-26 16:31
It's not a critical bug. So, we can wait the official release of 18.8...

As you prefer

**Comment by DaveTBlake** [comment] 2020-07-26 16:52
@elbowz we are encouraging you to test _before_ we release

**Comment by wsnipex** [comment] 2020-07-26 17:11
packages are currently building in this ppa: https://launchpad.net/~wsnipex/+archive/ubuntu/kodi-stable
should be done in about an hour

**Comment by elbowz** [comment] 2020-07-26 17:12
> @elbowz we are encouraging you to test _before_ we release

I understand what you mean...I would like avoid extra work for you (to prepare the test package).

~~I'm trying to self compile~~ (no more need thanks to @wsnipex)

**Comment by elbowz** [comment] 2020-07-26 20:13
It works as expected with the last build installed from @wsnipex 's ppa.

Tested in **Global Search** and **movies Filters**.

The log to confirm: https://pastebin.com/eV129aaq
(missing the SQL query for the movies/tv show, idk why, but the results are there)

Thanks to all for your work!! :+1:

**Closed** 2020-07-27 22:44 UTC
Labels: Resolution: Fixed, v18 Leia, v19 Matrix
