### ISSUE TITLE
Screenshots causing kodi to crash and restart. In v19

### ISSUE THREAD

**Issue by heitbaum** [xbmc/xbmc#18552] opened 2020-10-11 07:04 UTC
### Describe the bug
Here is a clear and concise description of what the problem is: that using ctrl+s using matrix development kodi crashes

Please find attached the crash logs. It happened in various screens in kodi, both in the menu and whilst playing movies.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Screenshot to be completed and no crash.

## Actual Behavior

Crash when using Ctrl+s to generate a screenshot.

### To Reproduce

1. Use Ctrl+S on both the menu screens or in a move (both in pause and play)
2. Was reproducible (not every time) but every 2nd / third time)

### Debuglog

The crash logs can be found here:
http://ix.io/2AmE
http://ix.io/2AmH
http://ix.io/2AmJ
http://ix.io/2AmK

### Screenshots 
Here are some links or screenshots to help explain the problem:

NA

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

NA

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
LibreELEC (Milhouse): devel-20200718000045-#0717-g776b589 (Generic.x86_64)
Matrix Development

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by a1rwulf** [comment] 2020-10-11 08:27
Mhm crashlogs all point to `/usr/lib/dri/iris_dri.so`.
@fritsch would you think this is a driver issue?

**Comment by heitbaum** [comment] 2020-10-11 10:41
Given the potential to be a driver issue. I have shared the video details below.
Hope this helps.

A copy of the /var/log/Xorg.0.log 
http://ix.io/2Ano

The CPU is a Skylake - Intel(R) Core(TM) i5-6260U CPU @ 1.80GHz

Details of the Video card are:
lspci | grep -i vga
00:02.0 VGA compatible controller: Intel Corporation Iris Graphics 540 (rev 0a)

Driver details.
LibreELEC:~ # grep -iE 'vdpau | dri driver' /var/log/Xorg.0.log
[    11.516] (II) intel(0): [DRI2]   DRI driver: i965
[    11.516] (II) intel(0): [DRI2]   VDPAU driver: va_gl

LibreELEC:~ # vainfo
libva info: VA-API version 1.7.0
libva info: Trying to open /usr/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_7
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.7 (libva 2.7.1)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 20.1.1 (776b589)
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSliceLP
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSliceLP
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSliceLP
      VAProfileVP8Version0_3          : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointVLD

**Comment by fritsch** [comment] 2020-10-11 11:46
Yes, looks like a driver bug. ffmpeg calls something that makes it unhappy.

As we just call open - without doing anything I'd like to ask you to file the bug over at our ffmpeg friends, they might have more inside what is happening. At the end if the GPU crashes it's always a driver bug - it shall not happen :-)

**Comment by heitbaum** [comment] 2020-10-11 12:18
Ticket raised. https://trac.ffmpeg.org/ticket/8928#ticket

**Comment by fritsch** [comment] 2020-10-11 12:21
I think they will close it right away, as their requirements is: reproduce with either ffmpeg command / ffplay or something else. Therefore they cannot really do something with that bugreport.

**Comment by a1rwulf** [comment] 2020-10-11 12:33
@fritsch ffmpeg crash is only the first crash report, other crashes are inside gl calls in our screenshot method.

**Comment by fritsch** [comment] 2020-10-11 12:50
Yeah, now seen it.

If you look more in detail you can see that the VAAPI / VPP path failed. Therefore try the following:
Can you disable VAAPI in the settings and retry?

E.g. does it stop crashing if you play the videos without vaapi enabled?

**Comment by heitbaum** [comment] 2020-10-26 13:26
Sorry it has taken me a few days to test this out completely. Was working on getting some other Matrix issues cleared up.

This is using today’s nightly. nightly-20201026-9e9b97f (Generic.x86_64)

First is with VAAPI enabled, second is without.

LibreELEC:~/.kodi/temp # pastebinit kodi_crashlog_20201026235904.log
http://ix.io/2C6r
LibreELEC:~/.kodi/temp # pastebinit kodi_crashlog_20201027000112.log 
http://ix.io/2C6s

Here is the log of screen shots - 
-rw-r--r--    1 root     root       1366344 Oct 26 23:58 screenshot00007.png
-rw-r--r--    1 root     root       1366344 Oct 26 23:58 screenshot00008.png
-rw-r--r--    1 root     root       1366344 Oct 26 23:58 screenshot00009.png
-rw-r--r--    1 root     root       1366344 Oct 26 23:58 screenshot00010.png
-rw-r--r--    1 root     root       1366344 Oct 26 23:58 screenshot00011.png
-rw-r--r--    1 root     root       1366344 Oct 26 23:58 screenshot00012.png
-rw-r--r--    1 root     root       1168972 Oct 26 23:58 screenshot00013.png
-rw-r--r--    1 root     root       1184040 Oct 27 00:01 screenshot00014.png
-rw-r--r--    1 root     root       1156249 Oct 27 00:01 screenshot00015.png
-rw-r--r--    1 root     root        630633 Oct 27 00:01 screenshot00016.png

**Closed** 2022-08-24 15:40 UTC
Labels: Triage: Needed, Issue Cleanup: Obsolete
