### ISSUE TITLE
Movies -when played in picture mode - have no picture only audio

### ISSUE THREAD

**Issue by jaspov** [xbmc/xbmc#16288] opened 2019-06-19 20:34 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:
As posted here: https://forum.kodi.tv/showthread.php?tid=344643&pid=2862071#pid2862071

Concerns opening pictures to a folder with both images and videos
-what works: click a picture, it shows, stop displaying picture, click a video and it plays
-what doesnt work: click a picture, use navigation to go to next item. If it is a video I will get only sound playing and a black image

So technically system can play all files, just now in slideview mode, or when going from one displayed item to the next. 

Tested on both my vero 4k+ and a raspberry pi2 that both have the same issue.
Posted in link above (picture section on kodi forums is a bit slow) but had another user post the same

Log: https://paste.osmc.tv/peranitufe
What am I doing during the log: Log has me rebooting, going to picture folder, selecting and playing a movie (plays fine), then going to a picture before the movie (selecting and displaying fine), direction key to move to next file to play the movie and it only has audio no image. After a few seconds I press stop.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fritsch** [comment] 2019-06-20 08:05
Please turn off AML acceleration and retry.

**Comment by jaspov** [comment] 2019-06-21 08:06
Just tested:

OSMC Vero 4K+: disabled AML, first attempt when switching from pic to movie it crashed (all pics and movies from iPhone). Showed a play icon on a black screen and was frozen so unplugged an rebooted

Second attempt: movie played : video and audio but very choppy

Pi2: has no AML so disabled MMAL, still same isue: audio but no video

**Comment by brjhaverkamp** [comment] 2019-06-28 10:16
I can confirm this bug with Kodi 18. Running a Raspberry pi 3B with latest OSMC.

**Comment by Mati24** [comment] 2019-06-28 17:54
Hello,
I have the bug on Nvidia Shield TV and XIaomi Mibox S, it works if I disable hardware acceleration, but it doesn't play video well after that...

**Comment by jaspov** [comment] 2019-09-03 21:39
Update. From today this now crashes kodi. Running OSMC on Vero 4K+

Disabled video’s in picture view to work around the crashes.

**Comment by brjhaverkamp** [comment] 2019-09-20 19:07
I haven't seen the crashes here. But the issue is indeed still 100% reproducable. Stopping the playback ofthe slideshow and selecting the video by hand, shows the video correctly, so it is something in the slideshow code.

**Comment by brjhaverkamp** [comment] 2019-11-14 12:30
Is there any progress on this one?
I assume there is a difference in initialization of the video between using the right button during browsing the album and using the play button when in the album. It might be a simple onliner fix.
And it is the only "serious" bug I encounter w Kodi currently. (which underlines the quality of Kodi!!)

**Comment by Mati24** [comment] 2019-11-14 12:39
Hello, since a recent release, it works for me (tested on Android TV). The video plays well when I browse manually (with right button)

**Comment by brjhaverkamp** [comment] 2019-11-14 14:40
Great news. Which version is that? Any idea on the commit that solved it? Then we can close this one.
I noticed some action on github on an issue when skipping forward in a video in a photo library, a few weeks back. maybe it is related?

**Comment by Mati24** [comment] 2019-11-14 14:47
Maybe, I don't know :(
@jaspov can confirm if it's working for him ?

**Comment by brjhaverkamp** [comment] 2019-11-14 14:57
@Mati24, Can you share the version it is working in for you?

**Comment by Mati24** [comment] 2019-11-14 14:58
It's the last on the Play Store, I will check tonight

**Comment by ksooo** [comment] 2019-11-14 15:39
https://github.com/xbmc/xbmc/pull/16496

It was merged for 18.4

**Comment by brjhaverkamp** [comment] 2019-11-14 15:57
Wonderful. Then I only need to wait for the next OSMC version with 18.4. Thank you Ksooo!
I think you can close this bug now. Or do you wait for more feedback?

**Closed** 2019-11-14 16:50 UTC
Labels: Triage: Needed
