### ISSUE TITLE
Kodi "Buffer failed" crash playing movie on Netflix with plugin

### ISSUE THREAD

**Issue by MishaIsay** [xbmc/xbmc#23534] opened 2023-07-21 07:05 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:
Kodi crashes after attempting to start movie with [Netflix plugin](https://github.com/CastagnaIT/plugin.video.netflix) from the beginning at the highest 4k Dolby Vision quality (in this case I tried to play "Glass Onion", but I also had this issue with "Ocean's Twelve" and "Ocean's Thirteen").

I have InputStream Adaptive set to "manual OSD", after I start a movie, it opens successfully in highest 1080p quality. But when I change the quality to highest 4k stream (~18.4Mbps, Dolby Vision), then stop playing and start it again from the beginning, Kodi remembers the last chosen video track, attempts to play it, gets stuck on loading and crashes on stop button. Log has these 2 errors repeating:
error <general>: CDVDVideoCodecAndroidMediaCodec:GetOutputPicture dequeueOutputBuffer failed
error <general>: CDVDVideoCodecAndroidMediaCodec::GetPicture dequeueInputBuffer failed
Kodi does not crash if I try to start movie not from the beginning (e.g. continue watching at 0:00:23), or if the quality is set to a different video track (tried second to highest (4k ~9.2Mbps, Dolby Vision)). And if I start to play movie successfully, chose the best quality and rewind to the beginning, movie plays correctly (I did that with logging: https://paste.kodi.tv/akejoveyif.kodi). Issue is also present if InputStream Adaptive is set to "Ask quality", movie is started from the beginning, and I chose the best 4k stream.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi plays movie successfully.

## Actual Behavior

Kodi crashes.

### To Reproduce

1. Set InputStream Adaptive to "Ask quality"
2. Start playing "Glass Onion" on [Netflix plugin](https://github.com/CastagnaIT/plugin.video.netflix)
3. Choose highest available 4k Dolby Vision ~18.4Mbps video
4. Loading animation spins infinitely
5. Pressing stop button crashes Kodi

### Debuglog

The debuglog can be found here: https://paste.kodi.tv/wakidaxafo.kodi
Manifest file: 
[manifest_1689918945.fail.txt](https://github.com/xbmc/xbmc/files/12117144/manifest_1689918945.fail.txt)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android TV 11
 - Kodi version: kodi-20230721-f087be63-master-armeabi-v7a.apk

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.

**Comment by CastagnaIT** [comment] 2023-08-01 09:03
i think this problem has been fixed with last InputStream Adaptive addon release v21.1.3

**Comment by CastagnaIT** [comment] 2023-08-01 09:10
maybe provide android logcat there could be show something else to help

**Comment by MishaIsay** [comment] 2023-08-01 16:33
> on kodi 20 4k playback works or same problem?

I tried to test it quickly, installed [KodiNerds v20](https://repo.kodinerds.net/index.php?action=list&scope=cat&item=Binary%20(armeabi-v7a)) (it can be installed as second copy because it has a different package name), got Netflix plugin from repo, copied plugin data from current v21 installation, but could not start any video due to "Widevine CryptoSession encrypt failed!" error. Should I try it properly later (Netflix log in in plugin doesn't work, so I would have to generate auth key again) or would the results be the same?


> there is this particular log print that im not able to understand where come from
> `debug <general>: Could not acquire timestamp`

This string also appears on the log of successful attempt (only 7 times instead of 51 on fail though).

**Comment by CastagnaIT** [comment] 2023-08-02 06:03
please dont use Kodinerd builds, are often cause of problems due to custom changes
and this makes any attempt to analyze a problem really difficult

so use only official builds, and copy existing data from kodi 21 to 20 its a bad thing to do and can break things

**Comment by MishaIsay** [comment] 2023-08-02 10:16
Tested it on Kodi 20.2, no crashes there. Tried both continuing the movie (from around 10m40s) and restarting the movie from beginning.
Took 4 logs: [Kodi 20.2 + continue](https://paste.kodi.tv/ejafibarom.kodi), [Kodi 20.2 + restart](https://paste.kodi.tv/ebesoravuc.kodi), [Kodi 21 nightly + coninue](https://paste.kodi.tv/kawukafeti.kodi), [Kodi 21 nightly + restart + crash](https://paste.kodi.tv/muxavunopi.kodi).

**Comment by CastagnaIT** [comment] 2023-08-02 11:39
thank you

@joseluismarti can you help investigate on these android exceptions?
```
2023-08-02 13:06:47.080 T:26977   error <general>: CDVDVideoCodecAndroidMediaCodec::GetPicture dequeueInputBuffer failed
2023-08-02 13:06:47.081 T:26977   error <general>: CDVDVideoCodecAndroidMediaCodec:GetOutputPicture dequeueOutputBuffer failed
```

**Comment by joseluismarti** [comment] 2023-08-02 15:08
Both error messages are shown in the Kodi log because of an `Exception` during execution.

If possible, attach the output of the `adb logcat` command containing all the system messages to see the details of the exceptions. This may give us a clue as to the cause.

**Comment by MishaIsay** [comment] 2023-08-02 16:08
Used [that guide](https://academy.test.io/en/articles/6753409-crash-logs-on-streaming-devices), I hope, that's what you asked. https://paste.kodi.tv/qutexuhuri.kodi

**Comment by joseluismarti** [comment] 2023-08-02 16:40
This is the error:

```
E/MtkOmxVdec(  442): Decoder Reported an Error: VDEC_DEC_DECODE_CODEC_NOT_SUPPORT
E/MtkOmxVdec(  442): 0xe7545290: ## DECODE ERROR: VDEC_DRV_MRESULT_FATAL
E/ACodec  (11013): [OMX.dolby.vision.dvhe.stn.decoder.secure] ERROR(0x80001001)
E/ACodec  (11013): signalError(omxError 0x80001001, internalError -2147483648)
E/ACodec  (11013): [OMX.dolby.vision.dvhe.stn.decoder.secure] ERROR(0x80001005)
E/ACodec  (11013): signalError(omxError 0x80001005, internalError -2147483648)
E/MediaCodec(11013): Codec reported err 0x80001001, actionCode 0, while in state 6
D/MediaCodec(11013): flushMediametrics
W/System.err(11013): java.lang.IllegalStateException
W/System.err(11013): 	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
W/System.err(11013): 	at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3452)
```

Now it's time to find out what cause it fails ...

**Comment by CastagnaIT** [comment] 2023-08-03 16:01
comparing data of working Kodi 20 and 21 i dont see nothing rilevant
from ISAdaptive side the downloaded segments and his sizes are equal and also codec properties

**Comment by MishaIsay** [comment] 2023-08-07 09:55
I tested ISAdaptive [earlier versions](https://mirrors.kodi.tv/addons/omega/inputstream.adaptive+android-armv7/) on [latest nightly](https://mirrors.kodi.tv/nightlies/android/arm/master/kodi-20230807-c7b0b9a5-master-armeabi-v7a.apk) and found out, that ISAdaptive v21.1.2 works correctly, error appears on v21.1.3. So this error is caused by ISAdaptive. Should I close this issue and open another one in ISAdaptive repo?

**Comment by CastagnaIT** [comment] 2023-08-07 10:57
Please test also this ISA test build:
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/Omega/93/artifacts

**Comment by MishaIsay** [comment] 2023-08-07 12:36
> Please test also this ISA test build: https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/Omega/93/artifacts

It works!

**Comment by CastagnaIT** [comment] 2023-08-07 12:52
good to know
in next ISA release you will have the fix

**Closed by CastagnaIT** 2023-08-07 12:52 UTC
Labels: Triage: Needed

**Comment by joseluismarti** [comment] 2023-08-07 13:38
Good news :+1:  @CastagnaIT if you have identified the issue or the param that caused the failure, please leave a note in case a similar internal error appears in the future

**Comment by CastagnaIT** [comment] 2023-08-07 13:58
i think the problem has been fixed by this PR https://github.com/xbmc/inputstream.adaptive/pull/1346
i have dont have experience of crashes/errors like this
but on shield with n€tflix i dont have anymore some random video glitch
