### ISSUE TITLE
Kodi v19 videowindow in windowxml dialog can crash Kodi

### ISSUE THREAD

**Issue by zach-morris** [xbmc/xbmc#19304] opened 2021-02-28 17:59 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

Attempting to play certain video types (youtube plugin url most notably) in a videowindow within a xbmcgui.WindowXMLDialog can crash Kodi

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Playing all supported video types in a videowindow does not crash Kodi

## Actual Behavior

Playing certain video types (youtube plugin url most notably) in a videowindow within a xbmcgui.WindowXMLDialog crashes Kodi

## Possible Fix

I'm guessing there's an issue with visibility of the videowindow, but I can't identify the specific issue.  Logging for the problem cuts short so nothing I can find in the log provides specifics as to why.

### To Reproduce

See the [attached plugin example](https://github.com/anxdpanic/plugin.video.youtube/files/6047484/plugin.program.youtube_test.zip) I put together to reproduce the issue.

This opens a pretty simple windowxmldialog, with some buttons to play different media types.  They all seem to work except the youtube one, which hard crashes Kodi.

### Debuglog

The debuglog can be found here:
As I said above, the debug log ends prematurely, but here is a log after attempting to play the youtube video in the above example plugin.
[kodi.log](https://github.com/xbmc/xbmc/files/6057404/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

NA

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Additional context:
- This works in Kodi v18
- I'll also note that I'm trying in [my addons ](https://github.com/zach-morris/plugin.program.iagl/blob/main/resources/skins/Default/1080i/IAGL-infodialog.xml)windowxml, I'm attempting to control the visibility of the videowindow (so it doesn't obfuscate other stuff in the window when a video isn't playing).  Apparently this isn't possible in python.  When you attempt to do this in python, you get the error that the control type is unknown for use in python.  To get around this, I use a HOME window parameter to control the visibility.  This worked for Kodi v18. 
- In Kodi v19, that also no longer seems to work, again I believe due to some timing/race issue, but that's likely separate (but somewhat related) to this issue. Now it either plays the video in the background (not in the videowindow) if the video type is not youtube, and crashes if it is youtube.  The fact that it plays in the background makes me think there's some timing issue with the visibility of the control.  If I could set the visibility of the control in python, that might also be a fix (but thats currently not possible).

- I did open the same issue in the youtube plugin issues page [here](https://github.com/anxdpanic/plugin.video.youtube/issues/82), but the fact that Kodi hard crashes in this case seems like it should be a Kodi specific issue.

- I'll also note in [the forums](https://forum.kodi.tv/showthread.php?tid=332966) users have verified this also crashes in Android and Windows, so it doesn't seem to be OS specific.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [X] OSX
 - [ ] Windows
 - [ ] Windows UWP

```
2021-02-28 09:53:28.446 T:2818224    INFO <general>: Starting Kodi (19.0 (19.0.0) Git:20210218-f44fdfbf67). Platform: OS X x86 64-bit
2021-02-28 09:53:28.446 T:2818224    INFO <general>: Using Release Kodi x64
2021-02-28 09:53:28.446 T:2818224    INFO <general>: Kodi compiled 2021-02-18 by Clang 10.0.1 (clang-1001.0.46.4) for OS X x86 64-bit version 10.13 (101300)
2021-02-28 09:53:28.446 T:2818224    INFO <general>: Running on Apple Inc. MacBookPro12,1 with OS X 10.14.6, kernel: Darwin x86 64-bit version 18.7.0
2021-02-28 09:53:28.446 T:2818224    INFO <general>: FFmpeg version/source: 4.3.1-Kodi
```

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment] 2021-03-07 22:38
Duplicate of https://github.com/xbmc/xbmc/issues/16756

`throw std::logic_error("busy dialog already running");`

**Closed by enen92** 2021-03-07 22:38 UTC

**Comment by zach-morris** [comment] 2021-03-07 23:37
Thanks for pointing to this.  The workaround was to add:
```
<onclick>Dialog.Close(busydialog,true)</onclick>
```
Prior to playing the video
