### ISSUE TITLE
HE-AAC/SBR audio, stream not supported

### ISSUE THREAD

**Issue by skachr** [xbmc/xbmc#15087] opened 2018-12-19 01:17 UTC
I have upgraded my Raspberry Pi from OpenElec v6, Kodi 15, to LibreElec 8.2.5 Kodi 17, and later on to LE 8.90.009 Kodi 18.
In both instances HE-AAC/SBR audio within a TS container is now mute.
Video, subtitles, and any aac, Dolby, DTS, etc- audio formats are unaffected and works perfectly.
I had naturally expected to keep audio as it was handled by previous versions.

Below a link to a Kodilog, reporting: "WARNING: OpenStream - Unsupported stream 0. Stream disabled_"

Also link to a sample of a mediafile in order to reproduce the problem.

[8mm_sample_H264_HE-AAC-SBR.zip](https://github.com/xbmc/xbmc/files/2692870/8mm_sample_H264_HE-AAC-SBR.zip)
[kodi-log.txt](https://github.com/xbmc/xbmc/files/2692873/kodi-log.txt)

Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X ] Raspberri-Pi 3
 - [ ] Windows
 - [ ] Windows UWP

**Comment by DaVukovic** [comment] 2018-12-19 09:06
Please submit a full (neither edited nor cut) logfile with debugging enabled. The log snippet is useless unfortunately. 

After you submitted the log, the invalid-label will be removed.

**Comment by DaVukovic** [comment] 2018-12-19 14:01
>  logfile with debugging enabled

`13:11:55.115 T:1936842768  NOTICE: Disabled debug logging due to GUI setting. Level 0.`

Obviously I wasn't clear enough. 

Anyway, I'm able to reproduce the issue with the stream snippet you provided. I have audio while using VLC but not with Kodi:

My Log: http://termbin.com/8etw

Mediainfo for the file shared above: http://termbin.com/dsqd

**Comment by pkerling** [comment] 2018-12-20 07:35
@fritsch

**Comment by fuzzard** [comment] 2020-10-30 07:07
Testing in v19 Alpha 2, the provided sample plays correctly.
As there is no changes coming into 18, i'll close this off as fixed in v19

**Closed by fuzzard** 2020-10-30 07:07 UTC
