### ISSUE TITLE
IPv6 DNS Resolution Broken in Matrix

### ISSUE THREAD

**Issue by rlees85** [xbmc/xbmc#19442] opened 2021-03-18 09:15 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi will no longer resolve IPv6 DNS names. This seems apparent when using Samba shares as media sources. Only IPv4 lookup is attempted causing the DNS lookup to fail. This was working perfectly well in Leia, it was broken by: https://github.com/xbmc/xbmc/pull/19040

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

DNS lookups should query for IPv6 and IPv4, so that IPv6-only services are still able to work correctly.

## Actual Behavior

The connection to the Samba share fails due to no IPv6 DNS resolution.

## Possible Fix

- https://github.com/xbmc/xbmc/blob/Matrix/xbmc/network/DNSNameCache.cpp use getaddrinfo() instead.
- Do not do any kind of DNS resolution within Kodi and just let the operating system handle it which makes much more sense and is less maintenance for the developers.

### To Reproduce

1. Connect KODI to an IPv6 enabled network.
2. Setup a Samba share that only has an IPv6 address in DNS (an AAAA record).
3. Attempt to set up the Samba share as a media source.
4. Observe it fail.

### Debuglog

The debuglog can be found here: I do not know how to produce one but since I have identified the pull request and code that are the problems here.

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: CoreElec 19 for ODroid N2 with IPv6 ENABLED.
 - Kodi version: 19/Matrix

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by treysis** [comment] 2021-03-30 07:11
Can't believe somebody is still using `gethostbyname` in this day and age!

**Comment by ryao** [comment] 2021-09-08 01:44
This breaks more than Samba. If you setup PVR IPTV Simple Client and one of your sources only works with IPv6, but has a broken IPv4 A entry to a non-existent server, you will see this error in kodi.log:

`ERROR <general>: CCurlFile::FillBuffer - Failed: Timeout was reached(28)`

This is because this code sees the IPv4 entry, puts it in the cache and leaves libcurl thinking that there is no IPv6 server.

There is a very nice unmerged commit that would have almost fixed this:

https://github.com/xbmc/xbmc/commit/8e886438ad6eaf9045e1b8dbfac867df517d9f99

Unfortunately, it only adds a single IP address to the cache, rather than looping through all of the returned addresses. This means that libcurl isn't able to implement the Happy Eyeballs algorithm to simultaneously attempt to connect to IPv6 and IPv4 on dual stack systems:

https://en.wikipedia.org/wiki/Happy_Eyeballs

Letting the OS handle DNS resolution sounds nice, but that would reintroduce #15469. It might be best to fix the DNS cache code so that it grabs both IPv4 and IPv6 addresses. This should let the Happy Eyeballs Algorithm could do its job.

Interestingly, in the case of the PVR IPTV Simple Client (at least when using inputstream.adaptive), this code returning a failure won't break things if the domain only has an AAAA record or an IPv6 address is specified. The failure is logged, but it is suppressed as the DNSCache is bypassed by libcurl when it has no entry. This is a different behavior than the one that the original reporter described that affects Samba sources. 

Anyway, this bug was annoying to debug because Kodi will tell you on timeout to check the log for details. Upon seeing the details, you only see the URL that failed and upon using curl, you don't see a problem, because the DNSCache code is exclusive to Kodi. What is worse is that if you do a network capture, the only evidence of the problem will be the single IPv4 packet sent to try to start a 4 way handshake. That is incredibly easy to miss. I only spotted it after I had already found the root cause of the problem.

**Comment by rlees85** [comment] 2021-09-09 11:27
Maybe I am lazy but to prevent https://github.com/xbmc/xbmc/issues/15469 recurring my DNS code would be "is host in advancedsettings.xml ? then ask OS to resolve this name". All these complexities about IPv4, IPv6, fast fallback, etc, can then just be handled and maintained by the OS and keep Kodi doing what it is good at - being a media centre. Just my opinion. Would be nice if this was able to be resolved either way.

**Comment by ryao** [comment] 2021-09-22 02:44
> Maybe I am lazy but to prevent #15469 recurring my DNS code would be "is host in advancedsettings.xml ? then ask OS to resolve this name". All these complexities about IPv4, IPv6, fast fallback, etc, can then just be handled and maintained by the OS and keep Kodi doing what it is good at - being a media centre. Just my opinion. Would be nice if this was able to be resolved either way.

The OS doesn't have code to do fast fallback. libcurl does, but it needs to know both addresses to use it. Anyway, the mechanism by which a host is added through advancedsettings.xml is implemented by the code that you want to remove. The correct solution should be to just fix the code.

Also, not all parts of kodi handle DNS resolution failures the same way. inputstream.adaptive will just ignore the error and submit the domain name to curl anyway. Evidently, the samba code does not. Doing the same in the samba code would workaround the issue.

**Comment by treysis** [comment] 2021-09-22 14:45
There is still the option to use the results the way the OS returns them. If a destination has malconfigured IPv6, well, then it's gonna fail. Same as it would fail with a malconfigured IPv4 record, when there are IPv4 single stack hosts trying to access.

**Comment by rlees85** [comment] 2021-09-22 17:25
I'd still raise fast fallback as a feature request in glibc or musl or Windows (:smile:) rather than making the media centre have a fully managed DNS stack but its my last comment on the matter. I think we agree it would be nice if the issue was resolved either way.

Just throwing it at Samba following a failed Kodi DNS lookup would probably work fine and that would be great!

**Comment by wsnipex** [comment] 2021-09-23 06:08
The easiest fix would be to have curl only use pre-existing cache enties.

could you test if changing this line works for you?
https://github.com/xbmc/xbmc/blob/master/xbmc/filesystem/CurlFile.cpp#L743
to
`if (CDNSNameCache::GetCached(url2.GetHostName(), resolvedHost))`

**Comment by tiagogaspar8** [comment] 2022-01-04 01:30
Hi everyone,

I'm having this issue too, plus I found out that if there is no IPv4 enabled the web server fails to start.
@wsnipex is there a way I can test that without compiling a package? I don't know how to do that but would like to see this issue solved.

Thanks!

**Comment by wsnipex** [comment] 2022-01-04 05:23
I could provide test builds via jenkins, which OS do you need packages for?

**Comment by tiagogaspar8** [comment] 2022-01-04 10:13
I have replied to yo in the other issue, but now since this is going to master it can be backported right? so this issue could be closed (after the merge of course)

**Comment by wsnipex** [comment] 2022-01-04 11:31
I'll create a backport once it's merged in master

**Closed** 2022-01-07 11:31 UTC
