### ISSUE TITLE
Directors sorted by appearances - a problem

### ISSUE THREAD

**Issue by robertodan** [xbmc/xbmc#20133] opened 2021-09-11 10:58 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

When sorting Directors by appearances everything works (real number of movies) until you enter the movie list for one of them and then go back to the directors list (all directors have -1 in their appearances.)

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

When going back from a director's movie list to the directors list, the appearances should keep the real number.

## Actual Behavior

Unfortunately, when going back from a director's movie list to the directors list, all directors have -1 appearances.

### To Reproduce

1. Directors list, sorted by appearances.
2. Enter one of the directors' movie list.
3. Go back to the directors list.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

https://ibb.co/VY9GdX4

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [X] OSX
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Checked it on Windows 10, Mac OS and Android
 - Kodi version: 19.1 Matrix

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment] 2021-09-12 01:36
I am unable to replicate the issue. 

Selecting the Node on the movie home page, I select a director and view the movies. Back out and movie count remains correct.

Please provide more details, as well as a debuglog which captures the issue.

**Comment by DaVukovic** [comment] 2021-09-12 08:31
I'm also not able to reproduce this issue on Linux

**Comment by enen92** [comment] 2021-09-28 08:44
Not reproducible for me in v20 as well.

**Comment by enen92** [comment] 2022-01-17 11:40
Closing as stalled, please reopen if you can reproduce this on v20.

**Closed by enen92** 2022-01-17 11:40 UTC
Labels: Triage: Tested and not reproduced
