### ISSUE TITLE
lastPlayed date is filled in database table files even when video is not yet finished

### ISSUE THREAD

**Issue by Rouzax** [xbmc/xbmc#17717] opened 2020-04-21 14:34 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

When I start a video in Kodi 18.6 or any version and stop that video after 0.1 seconds the `lastPlayed` is registered in the database. This will have videos with `playCount` `[NULL]` and a valid `lastPlayed`

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Only register a `lastPlayed` when a video reaches the threshold to be marked watched.

## Actual Behavior

Here a few examples from my database
|idFile|idPath|strFilename|playCount|lastPlayed|dateAdded|
|------|------|-----------|---------|----------|---------|
|5332|900|El Camino A Breaking Bad Movie (2019) - [WEBDL-2160p][X265 HDR][EAC3 5.1][EN][TrollUHD].mkv||2020-01-11 19:58:47|2019-11-16 18:44:19|
|28|123|The Mule (2018) - [Remux-1080p][DTS-HD MA 5.1][H264]-iFT.mkv||2020-01-11 19:59:10|2019-03-27 16:15:41|
|6339|1061|DuckTales (2017) - S03E01 - [1080p WEB h264][walt].mkv||2020-04-13 20:26:22|2020-04-04 00:00:00|
|6331|1025|Altered Carbon - S02E01 - [2160p WEBRip x265][Chotab].mkv||2020-04-13 20:26:39|2020-04-04 13:32:46|
|5374|904|How to Get Away with Murder - S06E02 - [1080p WEB-DL h264][NTb].mkv|||2019-11-21 15:18:26|
|6142|1022|Better Call Saul - S05E04 - [1080p WEBRip x264][AJP69].mkv|||2020-03-10 15:50:51|
|6398|1083|Cosmos (2014) - S02E04 - [1080p WEBRip x264][CAFFEiNE].mkv|||2020-04-14 16:12:38|
|4351|186|Ray Donovan - S06E02 - [1080p WEB-DL h264][NTb].mkv|||2018-11-05 03:07:01|
|5119|865|Workin' Moms - S02E12 - [1080p WEB-DL x264][TrollHD].mkv|||2019-10-13 20:12:56|
|5375|905|How to Get Away with Murder - S05E01 - [1080p WEB-DL h264][NTb].mkv|||2019-11-21 16:11:59|
|5631|855|The Graham Norton Show - S26E12 - [720p HDTV x264][qpel].mkv|||2019-12-21 01:07:42|
|6399|979|Saturday Night Live - S45E16 - [1080p WEB-DL h264][monkee].mkv|||2020-04-14 16:39:59|

This results in weird behaviour when you are creating a Smart Playlist for instance to only include shows you are currently watching in the last x days. 
For instance a Smart Playlist like this:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<smartplaylist type="tvshows">
    <name>TV Shows In Progress</name>
    <match>all</match>
    <rule field="playlist" operator="is">
        <value>TV Shows</value>
    </rule>
    <rule field="inprogress" operator="true" />
    <rule field="lastplayed" operator="inthelast">
        <value>45</value>
    </rule>
</smartplaylist>
```
Shows that you accidentally have started and stopped within a second will be counted for `lastPlayed`

## Possible Fix

It would make much more sense to register a `lastPlayed` when an episode is counted as finished and the `playCount` is incremented 

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.6

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment] 2020-04-23 19:01
There's a difference between "last played" and "watched". Maybe you should consider changing the rules at your playlist, as AFAICS, "last played" behaves correctly. It adds a date when you started the playback of a specific file. It's not marked as "watched" at that time. 

Hence I would say, this is not a bug, but probably a wrong usage of a smart playlist?!

**Comment by DaVukovic** [comment] 2020-04-24 17:17
Ok, I'm going to close this now. 

Kodi behaves correctly in that regard. If you request a change in Kodi-behavior, then open a feature request at the forums.

**Closed by DaVukovic** 2020-04-24 17:17 UTC
Labels: Triage: Needed

**Comment by Rouzax** [comment] 2020-04-24 17:35
Thanks for your answer.
There is no watched date in the database
I fully understand it is working as designed but I cannot understand why it would be useful to have a last played without the condition that the episode is watched in full.
What use has the table column `lastPlayed` currently?

**Comment by DaVukovic** [comment] 2020-04-24 17:49
>There is no watched date in the database
True. But there's a "watched"-count in the database. So we can differ between videos which have been watched or not. For example "watched != 0" <- not the correct code, but I'm currently too lazy to search for that section ;)

Just that it makes no sense for you doesn't mean it doesn't make sense for someone else ;). 

![image](https://user-images.githubusercontent.com/7235787/80241825-943b7e80-8664-11ea-963e-6756d1ae0553.png)

It's simply used as an info label for videos and for music as well. I find it pretty interesting to see if or when I last watched that movie or listened to an album

**Comment by Rouzax** [comment] 2020-04-24 17:55
> > There is no watched date in the database
> 
> True. But there's a "watched"-count in the database. So we can differ between videos which have been watched or not. For example "watched != 0" <- not the correct code, but I'm currently too lazy to search for that section ;)
> 
> Just that it makes no sense for you doesn't mean it doesn't make sense for someone else ;).
> 
> ![image](https://user-images.githubusercontent.com/7235787/80241825-943b7e80-8664-11ea-963e-6756d1ae0553.png)
> 
> It's simply used as an info label for videos and for music as well. I find it pretty interesting to see if or when I last watched that movie or listened to an album

I fully agree with you and the use case you are describing  is exactly where I want to use it for but the current way will list Last Played even if I only once play a microsecond and nothing further.

**Comment by DaVukovic** [comment] 2020-04-24 19:00
>Last Played even if I only once play a microsecond and nothing further.

Yeah. That's how it is designed. If you want something else, then you have to be consequent and not hit the play button ;)

By looking at the rule you mentioned above you want to have "In progress" TV-shows which are "Last played" -> "in the last" -> "45" .... and I guess you mean "Days"

I'm not sure in which way this rule does make sense. I personally understand "in progress"-TV-shows as shows I haven't watched at all yet. So the "last played" option is somewhat unnecessary from my POV. 

But, if our wiki is still somewhat correct in that case (which I can't test currently), then I have to say that "last played" is not supported for TV-Shows, but for episodes. Further more, again hoping that our wiki is correct, you have to enter something like "45 days" or "2 weeks" as only the number doesn't make any sense as you can't say what meaning that number has. 

Please see: https://kodi.wiki/view/Smart_playlists#Fields

As said, that wiki is outdated

And I would ask you to continue this discussion on the forums, please. As every answer will trigger an email for multiple devs ;)

**Comment by Rouzax** [comment] 2020-04-25 06:25
Last answer here 😄 
Sometimes you'll have a wife or son that will accidentally press a button.

The `in the last` only allows me to put in a number, there is no selector for days/weeks/months, but it does select shows that have been watched in the last x days so it works

The idea of this playlist is to be used in conjunction with LazyTV to play random next up episodes of your library.
We have about 30 active TV shows (as in new episodes are coming in), but only watch 6 shows actively. Then when a season is finished one on of those 6 shows we start watching one new season of one of the shows in the backlog.

With LazyTV this allows me to start playing random episodes of a playlist so with this Smart Playlist it will start the first available episodes of the current actively watched TV shows. 
Hope my ramblings make some sense.

On the forum some one advised to test with `<ignoresecondsatstart>180</ignoresecondsatstart>` in the AdvancedSettings.xml
https://forum.kodi.tv/showthread.php?tid=353847
