### ISSUE TITLE
Kodi's UPNP server is not detected in VLC unless you start Kodi while viewing VLC's local network section

### ISSUE THREAD

**Issue by Pentaphon** [xbmc/xbmc#16519] opened 2019-08-22 04:22 UTC
### Describe the bug
Kodi's UPNP server is not detected in VLC 3.1.7 for Android unless you start Kodi while viewing VLC's local network section. This also affects Nova Video Player, which also cannot see Kodi's UPNP server unless you enable it while looking at the Local Network section of Nova. Other devices, such as a Samsung TV, can see Kodi's UPNP server perfectly fine, without having to stop and restart Kodi, so it works fine with a Samsung TV but not VLC nor Nova Video Player. 

## Expected Behavior
Kodi's UPNP server should always be visible in VLC's Local Network section no matter what, as long as Kodi's UPNP server is running on the same LAN. You shouldn't have to start Kodi while looking at VLC's local network section to be able to see Kodi's UPNP server. 

## Actual Behavior
Kodi's UPNP server only appears in VLC's network section when Kodi is started while looking at VLC's network section. As soon as you back out of VLC's local network section, Kodi's UPNP server disappears! You can only make Kodi's UPNP server show up again by restarting Kodi. 

## Possible Fix
JB Kempf from VLC says: "I really doubt this is VLC's issue. If it works like you say, it's Kodi server not answering the SSDP requests."

### To Reproduce

1. Run Kodi with its UPNP server enabled on the local network. (every other software and device on my network can see it, including my Samsung smart TV)

1. Open VLC 3.1.7 for Android, and go to local network to see the UPNP servers on the network
Kodi isn't listed at all on the available shares list in the local network section.

1. Close Kodi and restart Kodi with the UPNP server enabled.
Kodi magically pops up in VLC's local network section!

1. Go back to the VLC home menu.

1. Go to VLC's local network section. Kodi is once again missing from the list of available shares!

1. Closing and restarting Kodi makes it show up again while you're looking at VLC's local network section.

1.  The previous steps also happen with Nova Video Player for Android.

### Debuglog

The debuglog can be found here: https://privatebin.net/?2ef9b478e5e70099#4DDFtV1hRXYWYrBqqHk2wGhB58p79LyGGGr29aVNTYpk

### Screenshots 
Here are some links or screenshots to help explain the problem:
None

## Additional context or screenshots (if appropriate)
None

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 64bit.
 - Kodi version: 18.3

**Comment by DaVukovic** [comment] 2019-08-22 04:41
probably a duplicate of: #16335 

But I'lll leave this one open as it has more info in it

**Comment by EricV2** [comment] 2019-08-23 14:42
@DaVukovic I do not think bugs are linked: the orginal problem, that I also reported is on the client side. This one is on the server side.

**Comment by TomasA** [comment] 2019-09-22 18:46
Hello, I have the same problem on Raspberry PI. I am using LibreELEC. When I try to change UPNP source, Raspberry unexpectedly restarts itself and then UPNP works until next restart or shutdown.

**Comment by ashkitten** [comment] 2019-10-15 16:41
same issue, libreelec on raspberry pi 4. vlc doesn't detect the upnp library until shortly after a restart (multiple devices), and bubbleupnp doesn't detect it as a renderer until after a restart as well. vlc on other devices always detects bubbleupnp's library near immediately, but not kodi's

**Comment by danielp123** [comment] 2020-05-17 05:25
Exact same problem with Raspberry Pi version. It's not only VLC that doesn't detect the UPNP server, but all DLNA/UPNP clients. I confirm this bug in Kodi, which is really unfortunate because I wanted to be able to stream my music from the Kodi server to different devices in the family (iPhone, iPad, Android phone...). This bug is still present on latest version (Leia 18.6).

**Comment by ShaheedLegion** [comment] 2020-05-19 08:11
I've found the source code, but the amount of refactoring it takes to solve this is prohibitive - I can see why this is a bug in the first place the the developers are too lazy to fix.

I've seen threads going back - literal years - where fixes are being refused. I'm going to use a different product for my media streaming, since Kodi doesn't work for me either, since my machine has a VM installed with a virtual network switch - on which Kodi is listening for SSDP requests, so obviously it's failing.

Good job being lazy devs.

**Comment by Pentaphon** [comment] 2020-05-19 09:53
> I've found the source code, but the amount of refactoring it takes to solve this is prohibitive - I can see why this is a bug in the first place the the developers are too lazy to fix.

We should ask the devs to sticky difficult bugs like this one when there is no sticky so that everybody takes a look at it and increases the chance of somebody wanting to fix it.

**Comment by TheArgentinian** [comment] 2022-03-19 23:49
Is this ever going to get fixed?

**Comment by enen92** [comment] 2024-02-13 19:09
Status of this on recent omega nightlies?

**Comment by Pentaphon** [comment] 2024-02-14 00:14
> Status of this on recent omega nightlies?

Still an issue. Even worse now actually since the latest VLC for Android doesn't even see the Kodi UPNP server in Omega.

**Comment by enen92** [comment] 2024-02-14 02:30
Can you post a debug log with UPnP component logging enabled? The original one is no more

**Comment by enen92** [comment] 2024-02-14 11:09
Just tested this with Kodi on windows and vlc/nova player for android and everything works as expected - kodi is displayed. Looking at the network traces with wireshark:

- VLC (192.168.1.246) sends an SSDP broadcast looking for mediaservers:

![image](https://github.com/xbmc/xbmc/assets/7375276/5def3d35-079b-48f6-b58f-a5bb0d6031c4)

- Kodi (192.168.1.126) sends the HTTP OK via UDP with its location:

![image](https://github.com/xbmc/xbmc/assets/7375276/3a481b3f-b142-4e4e-b8ac-048f8009dc46)

- Then VLC asks for the profile/identification of the server and Kodi answers:

![image](https://github.com/xbmc/xbmc/assets/7375276/b347101a-4c46-4cb9-b377-804ee28384b2)

![image](https://github.com/xbmc/xbmc/assets/7375276/eb423778-de68-42aa-afd3-ea9ca6ee2ca5)

**Closed** 2024-02-25 12:51 UTC
Labels: Platform: Android, Platform: Windows, v18 Leia, Component: Network, Issue Cleanup: Unable to reproduce, Triage: Tested and not reproduced
