### ISSUE TITLE
Video stop playing

### ISSUE THREAD

**Issue by Tek4Seth** [xbmc/xbmc#25776] opened 2024-09-30 21:52 UTC
### Describe the bug

the video stops after a few seconds. restarting the video sometimes works

### Debuglog

2024-09-30 23:45:08.692 T:10902   error <general>: DoWork - Direct texture file loading failed for resource://resource.images.studios.white/CBS / Paramount+ / CBS Studios.png

### Your Environment
Used Operating system:

 - [X ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 21.1.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment] 2024-10-01 01:04
Please provide the full log that captures the problem.
That single line that you believe is the cause of the problem is actually nothing. You have multiple studios enabled, and the resource image does not work with multi-studios.

**Comment by KarellenX** [comment] 2024-10-06 00:36
You haven't enabled debug mode.

**Comment by Tek4Seth** [comment] 2024-10-06 10:38
So far, with debug mode enabled I can't reproduce the problem.
I only have this problem since version 21.1

**Comment by KarellenX** [comment] 2024-10-07 01:07
Ok, when you are able to reproduce, please post the log. Without it, we won't be able to diagnose the issue.

**Comment by sarbes** [comment] 2024-11-07 23:45
Closing. Feel free to reopen if you can reproduce the issue.

**Closed by sarbes** 2024-11-07 23:45 UTC
Labels: Ignored rules, Triage: Needed
