### ISSUE TITLE
Kodi 18.6 breaks Android TV video

### ISSUE THREAD

**Issue by skerit** [xbmc/xbmc#17513] opened 2020-03-17 09:50 UTC
### Describe the bug

Since my Android TV installation automatically updated to the last Kodi version a few days ago, the video randomly breaks.

I can watch a few streams, but after a while, starting a new stream will only give me sound and no image.

What's even worse is that this affects the entire Android TV installation. After I get this "black screen with audio" issue, I can no longer use the built in chrome cast, I can no longer open netflix, ...

It can only be fixed by restarting the TV by unplugging the cable. 

### Your Environment
Used Operating system:
 - [x] Android
 - Operating system version/name: Android (on TV) 8.0.0 (2019-09-05) on kernel 3.10.79 (2019-11-15)
 - Kodi version: 18.6 20200229-8e967df921

**Comment by DaVukovic** [comment] 2020-03-17 16:43
As the bot mentions, get us a log.

**Comment by popy2k14** [comment] 2020-03-18 14:14
Similar issue here since update to 18.6 on my two android TVs (Philips 65PUS8102 & 55PUS9104).

My issue is a "color" issue with H265 content since the upgrade.
I have several h265 movies which shows some "pink" artifacts every few seconds.
It seems the are on dark parts of the scene.

I can reproduce the issue on my two sets with the same movie!
Restarting kodi 18.6 does'nt help.

After downgrade to 18.5 (and deactivate play store auto update), the issue disapeard on both of my tv sets!

Please find attached a debug log, playing the movie.

[kodi.zip](https://github.com/xbmc/xbmc/files/4349416/kodi.zip)

If this is another issue than the opened, than sorry, i will open another ticket.
Just want to be sure that's not the same.

**Comment by kodihelix** [comment] 2020-03-19 03:00
Just confirm same symptoms user "skerit" precisely described. Complete loss of video "black screen" upon attempting running Kodi, affecting all other video apps installed on TV. Amazon's Prime has sound, even subtitles, yet video is black. Same with YouTube and Tubi app. Appears Kodi kills the video decode app.  Needs a restart for apps to work again.
Android TV: Sony Bravia 4k GB ATV3,
OS: Android 8.0.0 API level 26 (kernel: Linux 3.10.79)
Kodi 18.6 Git:20200229-8e967df921 compiled" 2020-02-29

**Comment by DaVukovic** [comment] 2020-03-19 06:12
@popy2k14 

Your issue is not related to the issue @skerit or @kodihelix are talking about. You (at least) have video visible. The other reporters in here are losing their video completely (ending up with a black screen). So please open another ticket for that as it might also be related to h.265 in your case. 

@skerit @kodihelix we still need the log. This issue will be closed in 5 days if we don't get a log.

**Comment by popy2k14** [comment] 2020-03-19 11:29
@DaVukovic will do so, thx

**Closed** 2020-03-24 06:52 UTC
Labels: Ignored rules, Triage: Needed
