### ISSUE TITLE
"Delay in Playback on refresh rate change" not working on Shield TV

### ISSUE THREAD

**Issue by xinseo** [xbmc/xbmc#15912] opened 2019-04-13 14:35 UTC
### Describe the bug
I have the latest Shield TV update along with the latest Kodi nightly installed. 

Hooked the Shield to a Denon ATMOS receiver and from there to a Samsung 4K TV.

The problem:
There is a delay of about 4 seconds when refresh rate is changed and the setting "Delay in Playback on refresh rate change" does not work whether I set it to 1 second or 8. The same setting works fine on MrMC. On Kodi, audio starts after like 0.5 seconds when i click on play, however,  the screen stays black; as it is switching refresh rates.

Passthrough is ON and Refresh rate switching is ON.

Other people are facing this issue as well:
https://forum.kodi.tv/showthread.php?tid=342877

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Media playback should be paused for the duration that I set while refresh rate switching occurs (it takes up to 4-5 seconds on my setup)

## Actual Behavior

Media playback starts instantly without honoring the DELAY that I set.

## Possible Fix

Delay the playback for the amount that the user sets.

### To Reproduce

1. Set a "Delay in Playback on refresh rate change" 
2. Play any video

### Debuglog

The debuglog can be found here:
http://paste.kodi.tv/ebomajikac

(updated 26-11-2019)

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Kodi version: 18.2-RC1 Git:20190412-36bf9e04a3). Platform: Android ARM 64-bit 

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by xinseo** [comment] 2019-04-16 15:21
Latest Kodi update didn't fix the issue.

**Comment by xinseo** [comment] 2019-04-25 09:27
Issue still exists.

**Comment by fritsch** [comment] 2019-04-25 11:46
No one is working on this issue. You are informed if that changes.

**Comment by justinhow** [comment] 2019-11-19 22:48
Still exists under 18.5. Dragging on and on....

**Comment by xinseo** [comment] 2019-11-20 04:55
Wish someone could just copy the code from MrMC :(

It's so annoying having to rewind every video because i get no video for the first 4-6 seconds.

**Comment by justinhow** [comment] 2019-11-20 13:27
I guess none of the devs involved have a NVIDIA Shield TV ;-)

**Comment by peak3d** [comment] 2019-11-26 12:26
Can someone pls. attach a new kodi log file, or update the one from initial post? Thx!

**Comment by xinseo** [comment] 2019-11-26 12:39
> Can someone pls. attach a new kodi log file, or update the one from initial post? Thx!
> 
> Edit: and, if possible, do the same with a amazon fireTV stick. Interesting would be how it behaves (differnt / same) and a debug kodi log, too

Original post updated.

I don't own a firetv.

**Comment by fritsch** [comment] 2019-11-26 15:50
We are currently fiddleing out things internally and have different approaches. Sadly I current don't get logfiles from Shield.

Could you backup your kodi files and produce a debuglog with: http://mirrors.kodi.tv/test-builds/android/arm64-v8a/kodi-20191126-d134baf1-androidtimer-arm64-v8a.apk

Try different delays: e.g. 5, 10, 15.
Thanks much in advance.

**Comment by xinseo** [comment] 2019-11-26 18:17
> We are currently fiddleing out things internally and have different approaches. Sadly I current don't get logfiles from Shield.
> 
> Could you backup your kodi files and produce a debuglog with: http://mirrors.kodi.tv/test-builds/android/arm64-v8a/kodi-20191126-d134baf1-androidtimer-arm64-v8a.apk
> 
> Try different delays: e.g. 5, 10, 15.
> Thanks much in advance.

Can confirm that the wait feature is working now. I tried the same file around 7-8 times with different wait times and all of them worked fine. However, one time, I did experience a Shield crash (system reboot) when I tried playing the same file with delay of 7 seconds. The file played fine after Shield rebooted. Everything should have been captured in the debug log:

https://paste.kodi.tv/inemowasor

**Comment by fritsch** [comment] 2019-11-26 18:22
Jep - you just upgraded to a v19 Alpha version.

From the log I see that the code works like I intended it. Though - there is an additional bug on the shield that needs special care.

Thanks very much for testing.

**Comment by xinseo** [comment] 2019-11-26 18:24
> Jep - you just upgraded to a v19 Alpha version.
> 
> From the log I see that the code works like I intended it. Though - there is an additional bug on the shield that needs special care.
> 
> Thanks very much for testing.

No problem. Happy to help. Should I move back to the older version or will you be sharing a new version to try out?

**Comment by fritsch** [comment] 2019-11-26 18:33
Basically I wanted to see what works and what not. I see that Mediacodec Decoder is created while we are waiting. This thingy under the hood accesses / creates a Surface, while display is not properly configured. This is a problem for the Shield in certain Netflix scenarios.

If you just want a "working version" - I can create you a preliminary version ontop of Leia, which - obviously won't make this code here merged.

Thanks again for your debuglog.

So - what do you want?

**Comment by xinseo** [comment] 2019-11-26 18:54
> Basically I wanted to see what works and what not. I see that Mediacodec Decoder is created while we are waiting. This thingy under the hood accesses / creates a Surface, while display is not properly configured. This is a problem for the Shield in certain Netflix scenarios.
> 
> If you just want a "working version" - I can create you a preliminary version ontop of Leia, which - obviously won't make this code here merged.
> 
> Thanks again for your debuglog.
> 
> So - what do you want? (Language Barrier: I mean: I can provide you whatever you like best)

Not sure if I understand :)

If you can make a Leia version with this delay on playback code working, I would love to try it out!

**Comment by fritsch** [comment] 2019-11-26 18:55
Will post it here later. It has "fritschfiretv" in name - don't be confused, it won't do anything unwanted on your setup - it's just the device I currently have.

**Comment by fritsch** [comment] 2019-11-26 19:35
64bit: http://mirrors.kodi.tv/test-builds/android/arm64-v8a/kodi-20191126-4022c505-fritschfiretv-arm64-v8a.apk

32bit: http://mirrors.kodi.tv/test-builds/android/arm/kodi-20191126-4022c505-fritschfiretv-armeabi-v7a.apk

Both Leia based.

**Comment by xinseo** [comment] 2019-11-26 19:38
> 64bit: http://mirrors.kodi.tv/test-builds/android/arm64-v8a/kodi-20191126-4022c505-fritschfiretv-arm64-v8a.apk
> 
> 32bit: http://mirrors.kodi.tv/test-builds/android/arm/kodi-20191126-4022c505-fritschfiretv-armeabi-v7a.apk
> 
> Both Leia based.

Both links appear to be dead.

**Comment by fritsch** [comment] 2019-11-26 19:38
Mirror is refreshing. Give it 20 minutes.

**Comment by justinhow** [comment] 2019-11-28 18:39
Good news that headway is being made on this big and thanks to all those involved - will this bugfix eventually roll into Kodi 18.6 - if there is going to be one?

**Comment by HitcherUK** [comment] 2019-11-28 19:12
> will this bugfix eventually roll into Kodi 18.6

I believe that's the plan, yes.

**Comment by fritsch** [comment] 2019-12-01 16:43
Fix is in master. Please test it, if it works for you - backport is possible.

**Comment by xinseo** [comment] 2019-12-01 16:45
> Fix is in master. Please test it, if it works for you - backport is possible. Testing can be done by installing a recent nightly.

Would that be on Leia?

**Comment by fritsch** [comment] 2019-12-01 16:46
No

**Comment by fritsch** [comment] 2019-12-01 16:48
I will create you a Leia build. As the fix included in above builds is not the one that was merged - give me some minutes.

**Comment by fritsch** [comment] 2019-12-01 16:50
Result will end up here: http://mirrors.kodi.tv/test-builds/android/arm64-v8a/ and has "delay" in its name.

**Comment by xinseo** [comment] 2019-12-01 17:21
> Result will end up here: http://mirrors.kodi.tv/test-builds/android/arm64-v8a/ and has "delay" in its name.

**Comment by xinseo** [comment] 2019-12-01 17:23
> I will create you a Leia build. As the fix included in above builds is not the one that was merged - give me some minutes.

Has the issue that you mentioned a couple of posts above been fixed? Cause the older build that you linked (5days ago) crashes sometimes on opening a media file.

**Comment by fritsch** [comment] 2019-12-01 19:43
Reports with "crashes sometimes" and no debuglog is sadly worth absolutely nothing.

Please check this version which contains the official fix: http://mirrors.kodi.tv/test-builds/android/arm64-v8a/kodi-20191201-f1894772-delay-arm64-v8a.apk

If any further issue arrises, that does not happen with "normal" Leia, we cannot merge the backport and need you to verify with a master build.

**Comment by xinseo** [comment] 2019-12-01 19:55
> Reports with "crashes sometimes" and no debuglog is sadly worth absolutely nothing.
> 
> Please check this version which contains the official fix: http://mirrors.kodi.tv/test-builds/android/arm64-v8a/kodi-20191201-f1894772-delay-arm64-v8a.apk
> 
> If any further issue arrises, that does not happen with "normal" Leia, we cannot merge the backport and need you to verify with a master build.

It seems to be working fine so far. If any issues arise, I'll post debug logs.

**Comment by fritsch** [comment] 2019-12-01 19:58
Without kidding, please start a video for 50 times and turn on debug logging before. If that works 50 out of 50 times we can accept this fix into backport - else not.

I don't have a shield, therefore I cannot test.

**Comment by xinseo** [comment] 2019-12-01 19:59
> Without kidding, please start a video for 50 times and turn on debug logging before. If that works 50 out of 50 times we can accept this fix into backport - else not.
> 
> I don't have a shield, therefore I cannot test.

I'll report back within 24 hours :)

**Comment by xinseo** [comment] 2019-12-02 13:23
> Without kidding, please start a video for 50 times and turn on debug logging before. If that works 50 out of 50 times we can accept this fix into backport - else not.
> 
> I don't have a shield, therefore I cannot test.

I was doing as you suggested. On my 7th out of 50th attempt at playing a file using the delay option, my Shield crashed. 

Debug logs:
https://paste.kodi.tv/mopowiquti

**Comment by fritsch** [comment] 2019-12-02 13:30
Do you still have the kodi.log.old file? The log you uploaded has no switch in it.

**Comment by xinseo** [comment] 2019-12-02 13:46
> Do you still have the kodi.log.old file? The log you uploaded has no switch in it.

I have emailed you a copy at fritsch@xbmc

**Comment by fritsch** [comment] 2019-12-02 13:57
I have seen it. Please reproduce without plex, so that we can distinguish between different error cases.

**Comment by xinseo** [comment] 2019-12-02 14:12
> I have seen it. Please reproduce without plex, so that we can distinguish between different error cases.

Trief without PlexKodiConnect addon. Crashed during second attempt.
Logs:
https://drive.google.com/folderview?id=1EWE-iG4cjD_haqwlYnnwYjKPNKbPNysM

**Comment by peak3d** [comment] 2019-12-02 15:03
@xinseo what is "Shield crashed" exactly?

**Comment by xinseo** [comment] 2019-12-02 15:15
> @xinseo what is "Shield crashed" exactly?

Shield gets stuck at "Loading" with the loading circle and then the shield device restarts.

**Comment by peak3d** [comment] 2019-12-02 15:47
then we'll need to look into logcat:

launche kodi, select to the stream you are testing
adb logcat -c (to clear logcat)
adb logcat > logcat.txt

Then try to crash kodi / shield and provide the logcat pls.

**Comment by xinseo** [comment] 2019-12-09 06:34
> then we'll need to look into logcat:
> 
> launche kodi, select to the stream you are testing
> adb logcat -c (to clear logcat)
> adb logcat > logcat.txt
> 
> Then try to crash kodi / shield and provide the logcat pls.

I'll try and do this in a couple of days. Not sure how to adb into shield though lol

**Comment by HitcherUK** [comment] 2019-12-09 17:01
> Not sure how to adb into shield though lol

I use [adblink](http://www.jocala.com/).

**Comment by xinseo** [comment] 2020-01-28 14:20
> I have seen it. Please reproduce without plex, so that we can distinguish between different error cases.

After checking for more than a month (after a complete database reset), I've faced zero crashes. 

Think we can accept this fix.

**Comment by justinhow** [comment] 2020-03-04 09:17
So this fix never got into 18.6?

**Comment by peak3d** [comment] 2020-03-04 13:04
You mean backporting the one we did for matrix?

**Comment by DaveTBlake** [comment] 2020-03-04 13:08
If there is a PR releated to this issue can someone link it please

**Comment by justinhow** [comment] 2020-03-04 13:09
I was not sure whether the fix that was done for xinseo (see above) ever made it into the main Kodi 18.x build stream and therefore into the 18.6 just released today.

**Comment by xinseo** [comment] 2020-03-04 13:14
> > Reports with "crashes sometimes" and no debuglog is sadly worth absolutely nothing.
> > Please check this version which contains the official fix: http://mirrors.kodi.tv/test-builds/android/arm64-v8a/kodi-20191201-f1894772-delay-arm64-v8a.apk
> > If any further issue arrises, that does not happen with "normal" Leia, we cannot merge the backport and need you to verify with a master build.
> 
> It seems to be working fine so far. If any issues arise, I'll post debug logs.

This fix works but I'm not sure if it made it into the main builds.

**Comment by xinseo** [comment] 2020-03-04 20:37
The changelog shows the fix was baked in:
https://github.com/xbmc/xbmc/compare/18.5-Leia...18.6-Leia

**Comment by justinhow** [comment] 2020-03-04 20:41
That is great news. Thanks to all those that made this happen.

**Comment by DaveTBlake** [comment] 2020-03-05 08:04
Assuming that https://github.com/xbmc/xbmc/pull/16978 and backport https://github.com/xbmc/xbmc/pull/16989 for 18.6 fixed this issue

**Closed by DaveTBlake** 2020-03-05 08:04 UTC
Labels: Component: Video, Platform: Android, v18 Leia
