### ISSUE TITLE
"Play using" missing from the context menu for Favorites videos

### ISSUE THREAD

**Issue by Solarunit** [xbmc/xbmc#24970] opened 2024-04-10 16:32 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

"Play using" option is missing from the context menu for Favorites videos, so you can't use external player to play them.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

"Play using" option should be available throughout the Kodi UI

## Actual Behavior

"Play using" missing from the context menu for Favorites videos, so you can't use external player to play them.

## Possible Fix

Adding "Play using" option for all videos

### To Reproduce

1. Add movie, YouTube video from YouTube addon or Vimeo video to Favorites 
2. see that "Play using" option is missing in the context menu

### Debuglog

no logs since the option is missing

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Sometimes I would like to play video in external player and this option is missing. In Kodi 20 it was possible to use external player in YouTube addon (Play using was there), but not anymore. Also "Play using" was available for YouTube channels (folders) added to Kodi Favorites, but not for a single video for some reason.

For local Movies or local videos added to Favorites it was never possible.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Solus
 - Kodi version: 21 flatpak

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment] 2024-04-12 10:53
You are mentioning several things here, mixing bugs with feature request... 

> In Kodi 20 it was possible to use external player in YouTube addon (Play using was there), but not anymore. 

Bug. Add-on or Kodi fault? needs to be investigated.

> Also "Play using" was available for YouTube channels (folders) added to Kodi Favorite

Bug. Add-on or Kodi fault? needs to be investigated.

> but not for a single video for some reason.

Feature request. There was also no `Play` context menu item in Nexus. This was added for Omegae

> For local Movies or local videos added to Favorites it was never possible.

 Feature request. `Play`was added for Omega, `Play using` support needs to be implemented as a new feature.

**Comment by ksooo** [comment] 2024-04-12 10:57
And can you please provide your `playercorefactory.xml`?

**Comment by Solarunit** [comment] 2024-04-12 14:11
>Bug. Add-on or Kodi fault? needs to be investigated. However, can you prove that this worked before? Screenshot? I know the implementation of the favourite's context menu system quite well and would have no explanation why this could have worked.

Luckily I have older Kodi version and youtube addon still available.

Kodi 20.5 (not flatpak) and YouTube addon 7.0.0.2. "Play using" is still there:

![kodi-1](https://github.com/xbmc/xbmc/assets/20891064/f52947e1-360b-4cc7-8270-2cdb28bba8c4)


and after pressing "Play using" I see 2 players  menu to choose from:

![kodi-2](https://github.com/xbmc/xbmc/assets/20891064/0d43235b-b376-4c34-880b-05b72243e480)

I added youtube channel into Kodi favorites category, so it lloks like a folder with videos there. And Option "Play using" work for videos in that folder. But not for a single Youtube video added as favorite.


>And can you please provide your playercorefactory.xml?

`playercorefactory.xml` that was used here:

```xml
<playercorefactory>
  <players>
    <player name="MPV" type="ExternalPlayer" audio="false" video="true">
      <filename>/usr/bin/mpv</filename>
      <args>--fs=yes "{1}"</args>
      <hidexbmc>false</hidexbmc>
    </player>
  </players>
  <rules action="prepend">
    <rule video="false" player="MPV"/>
  </rules>
</playercorefactory>
```

**Comment by Solarunit** [comment] 2024-04-12 14:17
>Bug. But not related to favourites, so not covered by the subject of this issue. ;-) Maybe you should open a separate issue for this.

Sure.

>Feature request. Playwas added for Omega, Play using support needs to be implemented as a new feature.

I would love to have this option available in Favorites :)

**Comment by MoojMidge** [comment] 2024-04-12 15:17
> Bug. Add-on or Kodi fault? needs to be investigated. However, can you prove that this worked before? Screenshot? I know the implementation of the favourite's context menu system quite well and would have no explanation why this could have worked.

The OP is confused - https://github.com/anxdpanic/plugin.video.youtube/issues/692

What they have done is add a folder from the Youtube plugin to their favourites, and when opening that, they were previously able to see a Play using context menu item on the individual videos, but assumed that everything within was a favourite and not just coming from the plugin. 

As to why that doesn't work anymore:

https://github.com/xbmc/xbmc/pull/23901/files#diff-0c47520befb586aae890973984b0ed4038323f60ed43d7b39c364a19cbd5f2b3R257

Compared to the old way
https://github.com/xbmc/xbmc/pull/23901/files#diff-f5bac606e915d72ec6fc5938784499b4f283b2e90ec55fa87282e4b4563711f8L813

There are various other aspects of what they are claiming that didn't make sense in the context of the Youtube plugin, like how they expect MPV to open an unresolved plugin url without enabling certain options in the plugin, but no other details were provided so 🤷

**Comment by MoojMidge** [comment] 2024-04-12 16:24
I can guess what has changed on the plugin side of things, but like I said before I'm not going to waste time playing 20 questions with you. Post a debug log as requested in the issue you already opened.

On the Kodi side of things see previous messages.

**Comment by Solarunit** [comment] 2024-04-12 16:40
>I can guess what has changed on the plugin side of things, but like I said before I'm not going to waste time playing 20 questions with you. 

Well, it's not only YouTube addon, same thing with Vimeo and maybe ather video addons. I opened a separate issue here https://github.com/xbmc/xbmc/issues/24976

>Post a debug log as requested in the issue you already opened.

What steps I should do in the Kodi UI that would be reflected in debug log? Can't you reproduce this issue on you side with playercorefactory.xml example I provided? In the initial report you said  that it works for you. So you can confirm that `Play using` menu is there for you? Can you confirm that `Play using` menu available for Vimeo video too?

**Comment by MoojMidge** [comment] 2024-04-12 21:50
As I said there are two different issues. You haven't provided any info for the plugin side of things. If you want you can continue that discussion in the issue you already opened.

**Comment by ksooo** [comment] 2024-04-13 10:24
> like how they expect MPV to open an unresolved plugin url without enabling certain options in the plugin

@MoojMidge so you are saying "Play using" context menu item for plugin provided videos (YT, Vimeo, ...) never could have worked, because external player would need the resolved url which is not provided by the addon? That's my understanding as well.

**Comment by Solarunit** [comment] 2024-04-13 17:27
It's possible that in earlier YouTube addon versions you had to enable `Support of alternative player` and `Use YouTube website urls` in the addon settings in order to play video in MPV, but I don't remember exactly and can't confirm it.

in Vimeo addon I don't see much setting at all. And those setting are not related to video url to me. I never used Vimeo addon before.

**Comment by ksooo** [comment] 2024-04-13 17:36
> but I don't remember exactly and can't confirm it.

Honestly, from what I understand from what I've read here it is more a bug that prior Omega "Play using", which cannot be guaranteed to work for add-ons (Kodi simply does not know whether the add-on has some magic settings or so and it has worked by pure luck with the YouTube add-on some day, but not with others or the YT add-on nor specially configured), was visible.

I will close this issue as invalid.

BTW: What we can stick with is the feature request (to be placed in the forum, not here) that for for favourites for normal (non add-on provided) videos, "Play using" should be available.

**Closed by ksooo** 2024-04-13 17:36 UTC
Labels: Triage: Needed

**Comment by Solarunit** [comment] 2024-04-13 17:48
I guess I was lucky that it worked for me for months (years) I guess..
I didn't know that you have to create feature requests on the forum, not on github.

**Comment by ksooo** [comment] 2024-04-13 18:06
> I wonder can "Play using" context menu option be implemented on addon side?

That makes no sense.

**Comment by Solarunit** [comment] 2024-04-13 18:18
Why it makes no sense? If video addon provides a valid urls that can be played in various external players, why not add support for it?

I still wonder what `Play with` context menu and `Support of alternative player` should do in YouTube addon :thinking: 
For me it does nothing.

**Comment by enen92** [comment] 2024-04-13 18:47
For what is worth, plugins resolve the plugin:// path before sending it out to players (handled by application player itself) so playing on external players should be possible

**Comment by MoojMidge** [comment] 2024-04-13 19:56
@ksooo - Without the Youtube plugin changing the listitem path to a resolved video stream the Play using context menu item will no longer show up due to the changes mentioned here: https://github.com/xbmc/xbmc/issues/24970#issuecomment-2051964495

The resolved video stream may actually be a locally served adaptive streaming format manifest file for use by InputStream.Adaptive which many/most external players won't be able to open, or a standalone video stream which they should be able to play.

There are options in the YouTube plugin to use remote players and/or urls for the Youtube website, and the latter would allow the Play using context menu to appear and allow mpv to work using its youtube-dl wrapper.

However this would make the listitems unplayable within Kodi itself and mean that an external player would need to be used as the default player.

It's unclear how the OP has set things up and they don't seem to want to provide any information to help fix the issue i.e. provide a log showing what plugin settings are used and what url was passed to mpv that previously worked, but it is actually possible for a plugin to workaround the changes made in Kodi by creating its own context menu item that uses the `SwitchPlayer` action after resolving the plugin url to a stream that an external player can handle

That is a bit of a hack though, and so while this current issue is not technically valid, the other linked issue (https://github.com/xbmc/xbmc/issues/24976) is imo and should be resolved by removing the check for `VIDEO_UTILS::IsItemPlayable(item)`. While it may not work all the time depending on what the plugin listitem needs to do, as @enen92 pointed out it can work.

**Comment by Solarunit** [comment] 2024-04-13 20:08
>It's unclear how the OP has set things up and they don't seem to want to provide any information to help fix the issue i.e. provide a log showing what plugin settings are used and what url was passed to mpv that previously worked,

as I said in initial report I will provide a debug log soon. I am setting a VM to reproduce the ability to play youtube video in mpv that is set as default player in playercorefactory.xml. on a fresh Kodi profile. So a debug log incoming.

**Comment by ksooo** [comment] 2024-04-13 20:20
Sorry guys, I will not invest more time into this. I think, to make this actually work reliably (by means of kodi actually knowing an addon supports external players) is so much effort that I’m simply lacking time. And I consider this a very niche feature.

If somebody else wants to work on this, go for it. 

Simply removing the check for IsItemPlayable is definitely not the way to go.

**Comment by MoojMidge** [comment] 2024-04-13 20:39
> Simply removing the check for IsItemPlayable is definitely not the way to solve this problem correctly.

Probably. You would be in a better position to say in any case, it was just what was done previously, but I obviously don't know what other issues that may have caused.

I guess the assumption was that if it worked, it worked, otherwise too bad, without making any prior evaluation of whether it would work (because how could you do that from the context menu in advance of the plugin actually being called?)

I didn't use this feature so not fussed, and your time is your own anyway.

**Comment by ksooo** [comment] 2024-04-13 21:07
I did some more investigations and set up VLC on my system (macOS) as external player:

```
<playercorefactory>
  <players>
    <player name="VLC" type="ExternalPlayer" audio="false" video="true">
      <filename>/Applications/VLC.app/Contents/MacOS/VLC</filename>
      <args>--video-on-top --play-and-exit --fullscreen {0}</args>
      <hidexbmc>false</hidexbmc>
      <hideconsole>false</hideconsole>
      <warpcursor>none</warpcursor>
    </player>
  </players>
  <rules action="prepend">
    <rule video="false" player="VLC"/>
  </rules>
 </playercorefactory>
 ```

1. @enen92 is right, the add-on is asked (don't know how exactly, though) to provide the resolved URL for the item to play and the resolved URL is handed over to the external player
2. This works for "many" video add-ons (I tested a couple among them NASA, ESA, Madiathekview, heise c't Uplink, ...)
3. It does not work for the YouTube add-on! Tested 7.0.5 on Omega Final.

@MoojMidge Do you expect that VLC should be able to play a URL like this one (where the IP is the machine Kodi and the YT add-on is running on)? If yes, that does not work.

![image](https://github.com/xbmc/xbmc/assets/3226626/cb118a28-4bdb-40a2-ae03-88d8400c5afb)

**Comment by ksooo** [comment] 2024-04-13 21:09
BTW: The YT add-on seems to resolve to an http....mpd URL regardless of the "Support external player" and "Use Youtube website links" setting, if that matters.

**Comment by ksooo** [comment] 2024-04-13 21:11
And ofc I used a patched Kodi version that simply enables "Play using" for everything... ;-)

**Comment by ksooo** [comment] 2024-04-13 21:16
This drives me crazy guys, now even YT works, without any special add-on settings...

Now I'm seeing URLs like 
`https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1713064390/ei/ZvUaZsLvNM6G6dsPlIyeqA0/ip/85.16.226.202/id/7oLK1VcvROg.1/itag/96/source/yt_live_broadcast/requiressl/yes/ratebypass/yes/live/1/sgoap/gir%3Dyes%3Bitag%3D140/sgovp/gir%3Dyes%3Bitag%3D137/rqh/1/hdlc/1/hls_chunk_host/rr2---sn-xfxuxa-cgxy.googlevideo.com/xpc/EgVo2aDSNQ%3D%3D/ctier/SPL/playlist_duration/30/manifest_duration/30/ss/1/spc/UWF9fwyN7iu3zG25W7opCKDaDwfNx3DpkT6Qzek/vprv/1/playlist_type/DVR/initcwndbps/1653750/mh/OP/mm/44/mn/sn-xfxuxa-cgxy/ms/lva/mv/m/mvi/2/pcm2cms/yes/pl/24/dover/11/pacing/0/keepalive/yes/mt/1713042502/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,live,sgoap,sgovp,rqh,hdlc,xpc,ctier,playlist_duration,manifest_duration,ss,spc,vprv,playlist_type/sig/AJfQdSswRAIgLx3Tp17o6oB-Mct8KMi-dL5ncMTRSOo4i0DpIppe9pICIHFHUykwuGY6B9aUZnvlnVwDfD2R1p2yMGgYF3RADY97/lsparams/hls_chunk_host,initcwndbps,mh,mm,mn,ms,mv,mvi,pcm2cms,pl/lsig/ALClDIEwRQIgLw0sRszb4WKqzZwo9PiWPhhm_tp-WfnhD2MrGzY5ycICIQCK-6N_V6xPMQRHfq2XSTWSDJ ...`handed over to the xternal player and playback starts.

So, after all this test I need to revise what I said earlier. Their seems to be a generic mechanism in place that allows external players for add-on-provided media files...

**Comment by MoojMidge** [comment] 2024-04-13 21:16
> Do you expect that VLC should be able to play a URL like this one (where the IP is the machine Kodi and the YT add-on is running on)? If yes, that does not work.

That is what I was referring to regarding the use of a manifest intended for use with InputStream.Adaptive, most external players don't support the loading of these manifests (none that I have come across, but I haven't tested mpv). The Youtube plugin would need to be configured to use lower resolution non-adaptive streams in order for an external player to work.

> The YT add-on seems to resolve to an http....mpd URL regardless of the "Support external player" and "Use Youtube website links" setting, if that matters.
That is fixed in https://github.com/anxdpanic/plugin.video.youtube/pull/691 but @Solarunit was indicating that they didn't use those options anyway, which was why I was confused how they got this to work in the first place, unless mpv actually does support loading MPEG-DASH manifests.

**Comment by MoojMidge** [comment] 2024-04-13 21:20
> This drives me crazy guys, now even YT works, without any special add-on settings...

It depends on the type of video being played, and what the external player supports. In this particular example, you have opened a live stream, and the Youtube plugin extracts a HLS playlist for playback, which evidently VLC can also open.

**Comment by Solarunit** [comment] 2024-04-13 21:23
I just replaced MPV with VLC in my playercorefactory. 
So Vimeo videos work.
Youtube videos doesn't. I tried `Support of alternative player` setting on and off. It's trying to play `....mpd` file/stream
My guess is that maybe mpv using yt-dlp underneath to make that possible.

**Comment by ksooo** [comment] 2024-04-13 21:27
Let me summarize what I experienced with YT add-on 7.0.5 + Omega Final + VLC as external player on macOS:

External playback works just fine, none of the possible combinations of the settings "support alternative player" and "use yt website urls" make a difference.

@Solarunit which version of the yt add-on are you using exactly? I think it started working with 7.0.5 - my first test were unintended done with 7.0.4 beta something

**Comment by Solarunit** [comment] 2024-04-13 21:32
>@Solarunit which version of the yt add-on are you using exactly? I think it started working with 7.0.5 - my first test were unintended done with 7.0.4 beta something

Everything latest versions, YT addon 7.0.5, Kodi 21.

UPDATE: Now VLC works for youtube videos after I disabled `Use MPEG-Dash for all videos` in addon settings

**Comment by ksooo** [comment] 2024-04-13 21:35
> It depends on the type of video being played, and what the external player supports. In this particular example, you have opened a live stream, and the Youtube plugin extracts a HLS playlist for playback, which evidently VLC can also open.

> UPDATE: Now VLC works for youtube videos after I disabled Use MPEG-Dash for all videos in addon settings

That's it. works for some type of streams, for others not. works for some combinations of settings, for others not.

=> So, back to square 1. No way for Kodi to say whether the URL provided by the plugin can be handled by the player. Big question is whether with such a context it is a good idea to offer "Play using" for add-on-provided items. I say "no", because I already see all the issues opened stating that for the YT add-on and others the "play using" item does not work, although external player is setup correctly. No, thanks.

**Comment by Solarunit** [comment] 2024-04-13 21:44
IMO "Play using" menu only available when user setup external player, it's already a pretty niche feature and I assume such user is already a power user. 

Were there already many reports related to external players and videos items provided with video addons?

**Comment by enen92** [comment] 2024-04-13 21:44
> > It depends on the type of video being played, and what the external player supports. In this particular example, you have opened a live stream, and the Youtube plugin extracts a HLS playlist for playback, which evidently VLC can also open.
> 
> > UPDATE: Now VLC works for youtube videos after I disabled Use MPEG-Dash for all videos in addon settings
> 
> That's it. works for some type of streams, for others not. works for some combinations of settings, for others not.
> 
> => So, back to square 1. No way for Kodi to say whether the URL provided by the plugin can be handled by the player. Big question is whether with such a context it is a good idea to offer "Play using" for add-on-provided items. I say "no", because I already see all the issues opened stating that for the YT add-on and others the "play using" item does not work, although external player is setup correctly. No, thanks.

I'd say the kodi role as a frontend is to handover the resolved URL to the external player. If the external player is not able to playback the content it's not kodi's fault anymore. Plus, you can also have remote players (UPnP), and Kodi can be set as one of them. Playing items from Kodi to another Kodi instance is a perfectly valid use case that should not be removed just because some external player may not be able to handle some URLs

**Comment by Solarunit** [comment] 2024-04-13 21:57
Does `Use MPEG-Dash for all videos` activates `Input Stream Adaptive` addon that converts stream to `*.mpd` format, that VLC can't play (but mpv can)?

Can we say that `Input Stream Adaptive` addon interferes with external player or there is something else? :thinking:

**Comment by MoojMidge** [comment] 2024-04-13 23:14
> Does `Use MPEG-Dash for all videos` activate `Input Stream Adaptive` addon

Yes

> that converts stream to `*.mpd` format

No

> that VLC can't play (but mpv can)?

Yes (don't know, need a log to confirm)

> Can we say that `Input Stream Adaptive` addon interferes with external players

No

> or there is something else?

Yes

> Maybe in case if Input Stream Adaptive is the only thing that can break playback in external player we can update External Players wiki page with such a note, or maybe (if it's possible) we can change stream format on Input Stream Adaptive side.

Completely irrelevant. If you want this fixed by the plugin just provide a debug log as requested, many times, over a week ago.

**Comment by Solarunit** [comment] 2024-04-14 04:24
@MoojMidge here is a debug log link https://bpa.st/XQCH5GEATOOY2RNXMFSRQE7BLA

Kodi 21 flatpak, fresh profile, YT addon 7.0.5 with all default settings, mpv is set as default player.
I pressed `Enter` on a video thumbnail and it started playing in mpv.
See line 1164 when `OpenFile` process starts.

Let me know if you need log with some specific addon settings.

**Comment by MoojMidge** [comment] 2024-04-15 04:11
> Let me know if you need log with some specific addon settings.

All good, that has all that I needed to see. A workaround for the changes in Kodi has been added in [v7.0.6+beta.1](https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.0.6%2Bbeta.1)

There are pros and cons to the approach used:

Cons:
- It is a complete hack that relies on the timing between starting playback, invoking the switch players dialog, and playback failing/stopping, to be just right otherwise it will all fall apart.
- It needs some way to delay the playback of internet streams, luckily the YouTube plugin already implements a http server, but not all plugins would do the same.
- It needs the external player to support redirects. I only tested the players I had on my system and 1 out of 2 of them (MPC-HC) did not support redirects properly. VLC and mpv will work. I think MPC-BE will also work.
- It is a very niche feature, and while it works for me, with the limited testing I did, the experience is not good IMO. The external players are slow to load as they rely on youtube-dl or similar, and they don't allow for the same video qualities by default (this may be able to be configured through youtube-dl) or stream selection features that Kodi and InputStream.Adaptive provide.

Pros:
- It is more customisable than a non-plugin specific, generalised Kodi implementation, so it can cater for different external player capabilities.
- It resolves the issue for the YouTube plugin, if it is deemed as something that Kodi itself will not support moving forward, because of how variable the results may be.

**Comment by Solarunit** [comment] 2024-04-15 15:47
I installed YT addon v7.0.6+beta.1 on Kodi flatpak 21. MPV is set as default player.

I tried all possible combinations in `Advanced` > `Support Alternative Player` section:

- MPV can play every video, regardless of settings
- I don't see "Play with" menu at all

Maybe I should set internal player as default to see it? 

>Fix 6s delay on video playback start

thanks, that delay was annoying, now playback starts a lot faster.

**Comment by ksooo** [comment] 2024-04-15 16:02
> I installed YT addon v7.0.6+beta.1 on Kodi flatpak 21. MPV is set as default player.

@Solarunit can you guys please stop discussing this (now) unrelated things in this closed issue? Otherwise I will lock the conversation. Thanks.

**Comment by Solarunit** [comment] 2024-04-15 16:03
ok

**Comment by antonsoroko** [comment] 2024-10-03 11:38
@ksooo Hi. For last few months I have seen many confused people in "local" Kodi forums, who do not understand why suddenly after many years of using Kodi, "Play using" stopped working for addons since version 21.
I understand your position:
> I say "no", because I already see all the issues opened stating that for the YT add-on and others the "play using" item does not work.
but i support this opinion:
>I'd say the kodi role as a frontend is to handover the resolved URL to the external player. If the external player is not able to playback the content it's not kodi's fault anymore. 

If user can't use "Play using" - user should contact addon developer.

And "Play using" was working for addons for years. And users were using it for many addons.
So adding `IsItemPlayable` introduced major/medium regression, imho.

Please consider removing `IsItemPlayable` check. Thank you.
