### ISSUE TITLE
Music Playback: Screensaver/Idle Issue on FireTV?

### ISSUE THREAD

**Issue by godoll** [xbmc/xbmc#14949] opened 2018-11-26 10:47 UTC
### Describe the bug
While listening to music with Kodi on my FTVs for a while the TV screen gets dark, but the playback of the sound continues.
When hitting a button on my remote the screen gets lit again, but the display shows the main menu of the Amazon FTV, rather than Kodi's.
When starting Kodi again, though music's still playing, display turns dark again and it takes a while till the playback stops and we're back to the AFTV main menu.
Starting Kodi a third time it "boots" up properly.
There's no screensaver enabled in Kodi and Kodi is configured to stop when being idle for 25 min
There's no screensaver set on FireTV

## Expected Behavior
When playing Music Kodi app should stay in foreground as it does when playing movies

### To Reproduce
Start Kodi and play Music for a while (e.g. longer playlist)

### Your Environment
Used Operating system:
 - [x] FireTV(s) / Android

 - Operating system version/name:
 - Kodi version: 18.0.xx

**Comment by HitcherUK** [comment] 2018-11-26 15:18
We're going to need a debug log because I've just tested on my FTV with both screensavers off and it's still on Kodi after 30+mins.

**Comment by HitcherUK** [comment] 2018-11-27 16:59
OK, just after I posted it went to a black screen. Pressing any button 'woke' the Fire TV up but it was on the Fire home screen. Clicking on Kodi brings it back up (after several seconds).

Here's my degub log -

[kodi.old.log](https://github.com/xbmc/xbmc/files/2620998/kodi.old.log)

**Comment by hhoitz** [comment] 2018-11-30 13:09
I just want to tell that I have exactly the same issue. Skin is standard Estuary. But I have FTV screen saver on. Play music. While music is playing, FTV screen saver comes up and music has dropouts for some seconds. Music plays on. Then after a while, screen goes black.
After screen goes dark, music is playing on. When the music is finished, I only can wakeup the stick by pressing "home" on the remote. Then FTV home screen appears. Start Kodi again, and the screen ist black. After some time home screen appears again (seems like KODI is crashed). Then start Kodi a 3rd time, and it comes up normally with its splash screen.

**Comment by Erestris** [comment] 2018-12-03 00:01
Same Problem here. Annoying... i often have to pause a video and after round about 20 min it Görs Black and so on... with 17.6 this Never happened.

**Comment by Erestris** [comment] 2018-12-03 00:05
@godoll please change the title. It also Happens with paused videos or if you do nothing.

**Comment by pkerling** [comment] 2018-12-21 15:10
@peak3d can you have a look?

**Comment by jakenl** [comment] 2019-02-19 21:24
Glad I found this thread. With Xbian (Kodi on RPI) I updated last weekend to V18, form V17.6 and experience the behaviour with audio:
Kodi is reporting 'screensaver kicked in' while playing audio, but Kodi should delay that message until audio session ends.
My screensaver delay is set at 5:00 minutes.

Kodi 17:

Play an audio album or movie: During the whole album/movie, the status reported by Kodi would be 'audio' or 'video'. Good

Kodi 18:

Play movie: during the whole movie, the status remains 'video'. Good

Play audio: after 5:00 minutes, Kodi status broadcast changes to 'screensaver' (while the audio keeps playing, with the littlest interruption at the 5:00 minute sign). This status remains until the next track at some point after 5:00 minutes will start. After that the Kodi status will remain 'Audio' until the end of the whole album, no matter how long it takes. (During that whole album the screen will be 'dim', so that part is OK, just it's broadcasting is wrong

Pause Audio and restart: 5:00 minutes after restart, the screensaver status becomes active again. Also reset to 'Audio' by the first new track after those 5 minutes.

After the audio album is finished, the Kodi status should change to screensaver indeed, but it doesn't do that, while the actual screensaver (dim) is 'on'.

**Comment by jakenl** [comment] 2019-12-28 13:46
In Kodi 18.5 the issue is still the same as desribed here above. Yesterday I played audio through the tunein addon for Kodi. Works fine, but after 5:00 minutes my home automation shutdown my receiver, since Kodi is broadcasting "sleeping". Since tunein plays one continues sound, the broadcasted radio, there is no 'other audio track' that will remove this wrong behaviour

**Comment by godoll** [comment] 2019-12-28 17:17
Unfortunately the situation became even worse with the latest 18.5+ nightlies (https://forum.kodi.tv/showthread.php?tid=346575)
Though the playback of an e.g. m3u continued when the screen went blank / dark, it now stops a few seconds after the screen gets into "indle" mode and Kodi is "off".
Also the stuttering is still there, though I think it's only related to when playing mp3s (I also have some 5.1 encoded "DTS" wav files, which seem to play properly.

**Comment by fritsch** [comment] 2019-12-28 17:30
Random forum thread without any debuglogs, but a lot of words - we won't get anything fixed with that. Install  latest Leia build you find, turn on debug logging and reproduce. Everything else is not helpful at all.

For stuttering: Test a nightly (take care other stuff might have been broken, do a backup).

**Comment by fritsch** [comment] 2019-12-28 18:07
For your Leia Testing choose: https://jenkins.kodi.tv/job/Android-ARM/16077/artifact/kodi-20191225-5107f3c3-PR17075-merge-armeabi-v7a.apk

For the stuttering (this will only be fixed in nightlies): http://mirrors.kodi.tv/nightlies/android/arm/master/kodi-20191227-97728b63-master-armeabi-v7a.apk (make a backup of your stuff, before)

**Comment by StevenMeadowbrook** [comment] 2020-07-22 19:48
The original bug report reminded me on how I solved it on my FTV: I had used Method #1A from [the following description](https://kinkeadtech.com/how-to-prevent-fire-tv-stick-from-going-to-sleep/) to prevent going to sleep mode after exactly 20 minutes. HTH :)

**Comment by godoll** [comment] 2020-07-22 20:55
Thx, but there must be a better solution for this issue, as if and when you watch a video, Kodi doesn't go into the background but stays in front.

**Closed** 2022-09-06 20:13 UTC
Labels: Platform: Android, v18 Leia, Issue Cleanup: Obsolete
