### ISSUE TITLE
[Kodi 20.3] Controller integration on Android broke (tested on Ayn Odin and Retroid devices)

### ISSUE THREAD

**Issue by notimp** [xbmc/xbmc#24502] opened 2024-01-14 07:10 UTC
Issue: 

- When clicking on "Map Controller buttons" and then "map A" and then subsequently clicking on the a button on the controller (or the b button...) no controller input registers.

- When migrating from an earlier version (20.2) where the controller mapping worked, the controller is now mapped differently (Triggers dont work, b button seems to register as back and not b button)

so everything points at "the controller (portion of the retroid devices, probably not relevant though) is not recognized as a controller anymore".

Which is so great, when you use it on those kinds of devices.... Not. Please fix.

I reproduced it twice (restoring backup of 20.2 then updating to 20.3 again), and ultimately had to stick to the downgrade to 20.2 to fix it.

Also data folder restoring on android 13 is eh.... no bueno. Had to resort to an obscure "run script as root" feature the manufacturer had built into the rom to finally get my backuped files back into the data folder. Just as a warning/headsup, when you try downgrading.

For reference, see: https://forum.kodi.tv/showthread.php?tid=375723&pid=3179726#pid3179726

Thanks, and all the best,

notimp

**Comment by notimp** [comment] 2024-01-14 07:11
Please remove the ignored rules label, I think I was concise enough. Thank you.

The pain....

**Comment by fuzzard** [comment] 2024-01-14 07:33
The bare minimum for any issue report is a full debug log.

**Comment by garbear** [comment] 2024-01-14 07:54
Please post a debug log, it will have info on why controllers are broken.

**Comment by notimp** [comment] 2024-01-14 08:38
Sure thing:
https://paste.kodi.tv/muwisiqaqe

I ran Kodi a couple of times before updating, hope its not too long.

**Comment by garbear** [comment] 2024-01-14 10:17
The problem seems to be that the `peripheral.joystick` add-on is disabled. Can you try enabling it and see if the problem is fixed? Currently it's required to use any controller, though this constraint is being evaluated.

**Comment by mark-laing** [comment] 2024-01-15 22:05
Hi @garbear Where does one find this add-on to test. I cannot seem to find it. Here is a bit more information from my end on this one as I and several others on Reddit as facing it too.

Updated on Sunday 14th - Everything was working, went out to lunch, Button mapping changed and several no longer functioning.

Controller - Xbox Wireless Controller

Controller Reset in System does absolutely nothing at present.

L & R Trigger - Not working
Right Shoulder - Not working

Right Stick - Not working (volume control)

A, B, X, Y - All functions have changed.
Example - Play/Pause is now a press/hold on B, it used to be press. Stop function removed from B

Basic navigation is possible and still workable but it is quite annoying.

[kodi.log](https://github.com/xbmc/xbmc/files/13943312/kodi.log)
[kodi.old.log](https://github.com/xbmc/xbmc/files/13943313/kodi.old.log)
![IMG_3379](https://github.com/xbmc/xbmc/assets/74227420/b4fb8fe3-cbc2-430d-8f21-a4559a9b481c)

**Comment by garbear** [comment] 2024-01-17 03:21
Can someone give my latest test build a try? https://github.com/garbear/xbmc/releases/tag/retroplayer-21beta2-20240116

I added some Android buttonmaps recently. They could be the cause of the breakage.

**Comment by stratus-ss** [comment] 2024-01-17 13:46
I'll see if I can give this a try.

I experienced the same as @mark-laing on my nVidia shield TV. It didn't matter which remote I plugged in, it was all the same. 

I suspect, though I am not sure, that its related to https://github.com/xbmc/xbmc/pull/24382 which is what I stumbled across researching this issue.

I had to side load via adb the 20.2 version from fdroid because I couldn't find a way to revert via google play

**Comment by garbear** [comment] 2024-01-17 23:10
It could also be related to https://github.com/xbmc/xbmc/pull/23498, as that was merged just barely after 20.2.

**Comment by mark-laing** [comment] 2024-01-19 07:54
> Can someone give my latest test build a try? https://github.com/garbear/xbmc/releases/tag/retroplayer-21beta2-20240116
> 
> I added some Android buttonmaps recently. They could be the cause of the breakage.

Hi @garbear :) 

I have loaded this build and updated my Kodi. I have now been able to reset my controller properly and all buttons are now working again. Thank you so much for jumping on this one and fixing it for us!

**Comment by garbear** [comment] 2024-01-28 03:59
@mark-laing Your confirmation shows at least one person is made whole again by reverting the Android buttonmaps. I've released new versions of peripheral.joystick for Nexus and Omega with the android maps removed.

Linking:

* https://github.com/xbmc/peripheral.joystick/pull/295 (Version 21.1.11)
* https://github.com/xbmc/peripheral.joystick/pull/296 (Version 20.1.15)

Can anyone else who's having Android problems on 20.3 try peripheral.joystick 20.1.15? It should be on the mirrors in a few hours.

If that doesn't fix controllers on Android, we still have reverting https://github.com/xbmc/xbmc/pull/24382 and https://github.com/xbmc/xbmc/pull/23498 to test.

**Comment by garbear** [comment] 2024-01-30 04:29
I was able to debug most of the controller issues for controllers I have. I opened a PR with my fixes: https://github.com/xbmc/xbmc/pull/24604

There's still more work needed. Can those with controller issues try my 2024-01-29 builds with this PR integrated, available here? https://github.com/garbear/xbmc/releases. The Player Viewer now includes keyboard input and debug logging has been added, so debug logs will be helpful.

**Comment by garbear** [comment] 2024-01-31 08:08
I updated the PR with new findings on Android joysticks. So far all joysticks I've tested with Android buttonmaps are working.

We're hunting down issues with generic buttons/axes that Android doesn't map: https://github.com/garbear/xbmc/issues/137

If you could give the latest build, 2024-01-30, a try that would be appreciated: https://github.com/garbear/xbmc/releases

**Closed** 2024-02-02 16:40 UTC
Labels: Platform: Android, Component: Input, Triage: Needed
