### ISSUE TITLE
Background playback is stalled without "videowindow" control in the skin / gui

### ISSUE THREAD

**Issue by sualfred** [xbmc/xbmc#15119] opened 2018-12-22 22:42 UTC
### Describe the bug
The playback is stalled after a few seconds (~10s) if the gui is active and the used skin has no "videowindow" control placed in the skin to show the video in the background. 

The player won't pause or stop, but you will hear a short sound stuttering and then nothing. 
Player.Paused is still returning false and Player.Time is still showing a ongoing playback. As soon as you return to the videofullscreen window the playback will proceed at the timestamp where it stopped.

## Expected Behavior
No stalling? :)

## Actual Behavior
see bug description

### To Reproduce
1.  Use a skin that has the option to disable video playback in the background. Or temporary remove the videowindow control of Estuary in includes.xml -> "DefaultBackground"
2. Start a random YouTube video of the YT addon
3. Go back to home and listen to the sound of the video. It will stop after a few seconds.

> 20:40:08.486 T:12476  NOTICE: CVideoPlayerAudio::Process - stream stalled
20:40:09.136 T:7284 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
20:40:16.394 T:12476 WARNING: Previous line repeats 135 times.`

### Debuglog
The debuglog can be found here:
https://pastebin.com/8qbdKaBh

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Leia RC4 - Build 20181220

**Comment by Wellknown4** [comment] 2019-01-09 16:03
I have the same issue, but it is also playing a video from the hdd. It is the main reason I can not use Leia and keep getting back to krypton. When playing a movie and go back to the GUI the movie seems to pause. I hope it will be fixed. I have searched and searched, hope i am not the only one having thins on my Windows 10 64bit pentium i7 16GB nVidia 750ti ....

**Comment by sualfred** [comment] 2019-03-09 14:28
@ronie @FernetMenta 
Sorry for the ping, but this bug still exists. There are some skins out there that have videocontrol because of speed penalties for very very slow devices or just have it optional because of design reasons. 
I just want to make sure it's not going to be missed for Leia.

**Comment by ronie** [comment] 2019-03-09 15:21
i can't really comment on if it's a bug or not, as it has always been like this. 
adding a videowindow control to every window is a mandatory thing afaik.

**Comment by sualfred** [comment] 2019-03-09 15:54
It wasn't the case in previous Kodi versions. As far as I can tell this issue has been introduced in Leia.

**Comment by Wellknown4** [comment] 2019-03-09 16:01
I agree, introduced in Leia .

Op 9 mrt. 2019, om 16:54, "Sebastian S." <notifications@github.com<mailto:notifications@github.com>> schreef:

It wasn't the case in previous Kodi versions. As far as I can tell this issue has been introduced in Leia.

**Comment by FernetMenta** [comment] 2019-03-10 08:28
I am not aware that this has ever been a requirement explicitly considered in the code. That assumption is supported by the "?" in expected behaviour in this report. How should a requirement be tested, if the default skin does not even allow to deactivate rendering video in the background?

> adding a videowindow control to every window is a mandatory thing afaik.

That sounds like an ugly workaround. I am not aware that this has been a requirement either.

> It wasn't the case in previous Kodi versions. As far as I can tell this issue has been introduced in Leia.

What has been introduced? A different behaviour of undefined? This is not a bug but a missing feature.
First you should define the expected behaviour. IMO a reasonable behaviour would be to pause videoplayer if there is no active videocontrol.

**Comment by sualfred** [comment] 2019-03-10 08:40
@FernetMenta
Pause is not possible on all scenarios (eg some PVR setups).

The issue has been introduced. On Krypton and previous versions the playback wasn't stalled without videowindow control and it was played fine in the background without having a visible video output. 

I have no clue what's going on, but It seems like Kodi tries to sync video/audio but that fails because of the "missing video output".  As workaround it's enough to place this videowindow control as hidden object somewhere outside of the visible screen. But that's just a workaround.

**Comment by FernetMenta** [comment] 2019-03-10 08:46
> The issue has been introduced.

Definitely not. I should know because I wrote most of the code and I did not explicitly consider this scenario. Neither for v17 nor any other version.

**Comment by sualfred** [comment] 2019-03-10 08:56
I just can say that it only happens on Leia. The player is your baby and compared to you I have no single knowledge about how all this stuff works together. 

I wish I could assist more or give more technical background informations, but that core/player/gui handling goes far beyond my technical horizon.

If you need anything to test from me or need further information -> Just ping me and I'll be there and try to assist as much as I can.

**Comment by FernetMenta** [comment] 2019-03-10 11:43
> The player is your baby

I am just helping out here :)

> I wish I could assist more or give more technical background informations

Not required. It is very clear what happens here and it works as designed. If neither fullscreen window nor video control renders the frames from videoplayer, all buffers fill up until the demuxer queue is full. In this state no new packets are read from demuxer and as a result audio stalls.

You want to use videoplayer without any output for rendering video. This is a new requirement and should be discussed in a feature request.

**Comment by sualfred** [comment] 2019-03-10 12:00
Ok, but why it was acting differently in previous Kodi versions? 
Because that means - like Ronie said - that the videowindow control is mandatory now if the users doesn't want to hear sound issues.

Anyway, if any skinner is coming here to to find a possible "solution", that's how to bypass this behaviour:

`<control type="videowindow"
		<left>-3000</left>
		<top>-3000</top>
		<width>1</width>
		<height>1</height>
</control>`

**Comment by FernetMenta** [comment] 2019-03-10 14:16
> Ok, but why it was acting differently in previous Kodi versions?

Behaviour for this has been undefined. Undefined behaviour can be anything and change at any time. 

btw: I would not call this workaround a "solution" because it wastes a lot of resources. Video is still rendered and scaled down. It might even be downscaled using high quality scalers.

**Comment by HitcherUK** [comment] 2019-03-10 14:39
Back button = stop video
Problem solved. ;)

**Comment by sualfred** [comment] 2019-03-10 14:57
If you you want me to get killed by users, why not ;)

Anyway. I prefer possible wasted resources over stuttering sound.

**Comment by Keksebacker** [comment] 2019-03-14 11:31
I can confirm this issue.

It's the only point which prevents me to switch to Kodi 18 on the main system because its annoying if you browse through the EPG and the currently running content (in my case 99% pvr) is stuttering in the background.

Kodi 16 and 17 do not have this behaviour described by sualfred.

Win 10 x64
Skin Titan / Black Glass

**Comment by Wellknown4** [comment] 2019-03-18 17:46
Me too.

Op 14 mrt. 2019, om 12:32, Keksebacker <notifications@github.com<mailto:notifications@github.com>> schreef:

I can confirm this issue.

It's the only point which prevents me to switch to Kodi 18 on the main system because its annoying if you browse through the EPG and the currently running content (in my case 99% pvr) is stuttering in the background.

Kodi 16 and 17 do not have this behaviour described by sualfred.

Win 10 x64
Skin Titan / Black Glass

**Comment by Wellknown4** [comment] 2019-04-15 14:56
Probably off topic.
The described bug in Windows10 with Leia, I also have with Linux Mint 19.1 and Leia.

**Comment by Wellknown4** [comment] 2019-09-18 13:11
Well got back to krypton for a while, all went good. Saw Leia 18.4 installed it, and see the problem still exists. Is there any progress or idea why this is happening on Leia and not on Krypton?

**Closed** 2022-04-19 17:17 UTC
Labels: Issue Cleanup: Obsolete

**Comment by ray2301** [comment] 2022-06-18 16:27
lol, i can't believe this still hasn't been fixed in matrix.
