### ISSUE TITLE
[MSVC] xbmc failed to build with error C2027 on MSVC

### ISSUE THREAD

**Issue by Zhaojun-Liu** [xbmc/xbmc#21548] opened 2022-06-13 08:57 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

The MSVC team recently test XBMC project failed with error C2027 on Windows.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

build successfully.

## Actual Behavior

error C2027: use of undefined type 'D3DX11Effects::TTopLevelVariable<ID3DX11EffectVariable>'

### To Reproduce

1. git clone https://github.com/xbmc/xbmc.git F:\gitP\xbmc\xbmc
2. set _CL_= /permissive-
3. cd F:\gitP\xbmc\xbmc\build_amd64
4. set _LINK_=%_LINK_% /alternatename:__imp_fribidi_remove_bidi_marks=fribidi_remove_bidi_marks /alternatename:__imp_fribidi_log2vis=fribidi_log2vis
5. msbuild /m /p:Platform=x64 /p:Configuration=Release kodi.sln /t:Rebuild 2>&1

### Debuglog

The debuglog can be found here:
[build.log](https://github.com/xbmc/xbmc/files/8889648/build.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Attached a generated preprocessed file:
[d3dxGlobal.i.txt](https://github.com/xbmc/xbmc/files/8889667/d3dxGlobal.i.txt)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows server 2019
 - Kodi version: master branch : 877b723

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment] 2022-09-16 22:29
Duplicate of https://github.com/xbmc/xbmc/issues/20295

**Closed by enen92** 2022-09-16 22:29 UTC
Labels: Ignored rules, Triage: Needed
