### ISSUE TITLE
Channel OSD hangs up after switching 1-2 times (not closing after 5 Sec.) (Estuary Skin)

### ISSUE THREAD

**Issue by Starfoxfs** [xbmc/xbmc#24113] opened 2023-11-17 18:25 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

Channel OSD hangs up (not closing after 5Sec) after 1 or 2 times changing TV Channels
Skin Standard Estuary

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Channel OSD closing after 5 Seconds as setup in settings PVR->Playback-> Show Channel Information when switching Channels.

## Actual Behavior

Channel OSD hangs up when Switching between TV Channels.
Skin Standard Estuary

### To Reproduce

1. Open TV Channel
2. Switch TV Channels
3. Channel OSD stays in Picture (not closing)

### Debuglog

The debuglog can be found here:
[kodi.log](https://github.com/xbmc/xbmc/files/13395249/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android (Nvidia Shield TV Pro 2019)
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Kodi 21 Omega Nightly ([kodi-20231114-543d2268-master-arm64-v8a.apk](https://mirrors.kodi.tv/nightlies/android/arm64-v8a/master/kodi-20231114-543d2268-master-arm64-v8a.apk)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment] 2023-11-17 18:42
Tried really hard, but cannot reproduce.

The log shows that you are not using Standard Estuary skin. Please provide a log proving the problem with the standard skin, otherwise I tend to say that this could be a skin problem. I have no clue might work different in that mod...

**Comment by ksooo** [comment] 2023-11-17 18:43
Also, uninstalling any other add-ons (watchdog, ...) would be helpful so we can exclude them all from the list of problem candidates.

**Comment by ksooo** [comment] 2023-11-18 04:15
And, as far as I can see from the log we are not even talking about the channel OSD here. Please provide proper and complete information. Otherwise this issue will be closed as invalid.

**Comment by Starfoxfs** [comment] 2023-11-18 08:45
I reinstalled Kodi Nightly on my Nvidia Shield without addons and now it works. sorry for the circumstances

**Closed** 2023-11-18 08:56 UTC
Labels: Triage: Needed
