### ISSUE TITLE
Volume name USB drive not displayed in Kodi Matrix 19 (Android)

### ISSUE THREAD

**Issue by shota2021** [xbmc/xbmc#19339] opened 2021-03-05 18:10 UTC
### Describe the bug
With version 19, the volume name of hard disks attached to my Nvidia Shield (Android) no longer appears. Instead, Kodi displays the UUID (serie of numbers and letters). Version 18 did show the volume name.

### Your Environment

- Kodi version: Matrix 19 on a Nvidia Shield TV (Android).

**Comment by lrusak** [comment] 2021-03-05 18:12
probably a duplicate of #19307

**Comment by ksooo** [comment] 2021-04-06 18:37
> probably a duplicate of #19307

 yep.

**Closed by ksooo** 2021-04-06 18:37 UTC
Labels: Platform: Android, Triage: Confirmed, v19 Matrix
