### ISSUE TITLE
ScanTags: no tag found when scanning "Web server directory (HTTP)" source

### ISSUE THREAD

**Issue by mpenkov** [xbmc/xbmc#18866] opened 2020-11-26 00:46 UTC
### Describe the bug

Here is a clear and concise description of what the problem is:

Kodi fails to scan tags from music files accessible via HTTP.

I'm serving a subdirectory using Apache/2.4.41 (Ubuntu) Server. I've added the server as a "Web server directory (HTTP)" source and requested that Kodi scan that source for music. Kodi retrieves the list of files correctly, but fails to scan the music files into the DB.

The logs for Kodi are here: https://paste.kodi.tv/nuyocacuto.kodi. The files I'm trying to scan are under the "Jet/Get Born" subdirectory. Kodi reports this for all the files:

```
2020-11-26 09:27:25.453 T:140487877252864   DEBUG: ScanTags - No tag found for: http://172.16.15.89/Jet/Get%20Born/1-13%20Timothy.mp3
```

That seems wrong because the tags are definitely there:

```
$ ffprobe -i "http://172.16.15.89/Jet/Get%20Born/1-13%20Timothy.mp3" -hide_banner 2>&1 | head
Input #0, mp3, from 'http://172.16.15.89/Jet/Get%20Born/1-13%20Timothy.mp3':
  Metadata:
    title           : Timothy
    artist          : Jet
    track           : 13/14
    album           : Get Born
    disc            : 1/2
    genre           : Rock
    TMED            : CD
    encoded_by      : Lame 3.96
```

If ffprobe can read the tags, then Kodi's ScanTags should be able to read them too, right?

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I expected Kodi to scan each of the files into the music library.

## Actual Behavior

Kodi accessed the Web server, obtained the file listing, but did not add anything to the music library.

## Possible Fix

I suspect there may be a problem with the ScanTags function.

### To Reproduce

1. Set up a Web server (e.g. Apache, or Python's `python -m http.server` to serve a subdirectory with tagged MP3 files
2. Add the Web server as a HTTP source in Kodi
3. Attempt to add the files to Kodi's music library

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/nuyocacuto.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu 20.04 LTS
 - Kodi version: 18.6 (I've tried 18.9 as well, but on a different machine, with same results)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaveTBlake** [comment] 2020-11-26 12:38
This behaviour is by design, Kodi deliberately does not scan HTTP sources into the music library.  Hence closing this issue

There is no way for Kodi to tell if the urls provided point to finite music files  (that could be handled by the library) or a continuous stream of music, hence they are skipped. You would need to use DAV or WebDAV rather than pure http.

**Closed by DaveTBlake** 2020-11-26 12:38 UTC
Labels: Resolution: By design

**Comment by mpenkov** [comment] 2020-11-27 00:55
Thank you for getting back to me.

> There is no way for Kodi to tell if the urls provided point to finite music files (that could be handled by the library) or a continuous stream of music

Why not use the filesize from the directory listing that you just parsed the filename from? Knowing that the object is of finite size would mean you're dealing with a file as opposed to a stream, wouldn't it?

Failing that, you could rely on HTTP HEAD to tell you what the object at the URL is:

```
curl "http://192.168.0.21/Jet/Get%20Born/1-13%20Timothy.mp3" --head -o -
HTTP/1.1 200 OK
Date: Fri, 27 Nov 2020 00:53:35 GMT
Server: Apache/2.4.41 (Ubuntu)
Last-Modified: Thu, 08 Oct 2020 09:46:45 GMT
ETag: "603919-5b125b5cf78bd"
Accept-Ranges: bytes
Content-Length: 6306073
Content-Type: audio/mpeg
```

Not sure if you've already thought of that and there's a legit reason not to do it, but just thought I'd let you know.

**Comment by DaveTBlake** [comment] 2020-11-27 09:41
> Why not use the filesize from the directory listing that you just parsed the filename from?

That is a reasonable idea in response to my explanation, but unfortunately my explanation was an over-simplification of the situation. I am also looking at code designed over 11 years ago by other people and trying to make sense of it. Any weakness likely lies in my explanation rather than the design itself. But it is clear that skipping http (and a number of other protocols consistered internet streams) is definitely deliberate.

The music library scanning process is based around setting up shares as music sources and then on each source iterating through a folder hierarchy looking for music files, artwork and NFO files (for artists and albums). I'm not sure how that would work on pure http. Library scanning was designed to work on local folders and files, or shares mounted using  protocols like NFS of SAMBA that provide access to file systems over a network as if they were local. 

I don't doubt that a media player could be designed to handle scanning pure http sources, just that isn't how Kodi has been implemented. 

> Not sure if you've already thought of that and there's a legit reason not to do it, but just thought I'd let you know.

Thank you, if you have technical skills then contributions to the project are welcome. The team of active devs is very small and so it makes it hard to be as responsive to either fixing bugs or mentoring new contributors as we would like. The code is sitting there to explore - OK it is a mountain, and it can be tough without a guide - stepping through it in a debugger can give a feel for the terrain.
