### ISSUE TITLE
I use Kodi nightlies on my computer running Windows 7 with updates as often as they are sent. The Kodi version I am using is 10/11/19. Each nightly update after that date will not load. I get a statement saying the api-win-core-com-l1-1-0.dll is missing from my computer.

### ISSUE THREAD

**Issue by shockr45** [xbmc/xbmc#16820] opened 2019-10-23 05:02 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

I am running Windows 7 with all the most recent updates. On the internet I have noticed others having similar issues, but mostly with Windows 10. Also some have reason to think it is caused from Visual C++. I have Visual C++ 2017 Redistributable (x64), Visual C++ 2013 Redistributable(x86) and Visual C++ 2008 Redistributable(x64).  Since the 10/11/19 nightly, I am unable to load the nightlies. Each day when I try to install a new nightly, I get a pop-up stating that the program cannot be opened because the api-win-core-com-l1-1-0.dll is missing from my computer. But I then go back and load the 10/11/19 nightly and it will load and play fine. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Since the earlier version of Kodi (the 10/11/19 nightly) will load properly, it seems that something was changed in Kodi after the 10/11/19 nightly. 

## Actual Behavior

Cannot load nightlies after the 10/11/19.

## Possible Fix

?

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: 7 sp1
 - Kodi version: latest 19

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment] 2019-10-23 06:06
You haven't filled in any information in the template, just provided one enormous title.

Please fill in the required information or your Issue will be closed.

**Comment by DaVukovic** [comment] 2019-10-23 09:23
This sounds more like an OS related problem rather than a Kodi problem: 

https://wikidll.com/microsoft/api-ms-win-core-com-l1-1-0-dll

**Comment by M2k80** [comment] 2019-10-26 20:23
@DaVukovic just read around a little, i found maybe something for interest?

> hose DLLs are Windows's implementation detail and are subject to change at anytime. Basically Microsoft started moving around APIs starting from Windows 8. For example, APIs in Windows 8's api-ms-win-core-file-l1-2-0.dll got moved to api-ms-win-core-file-l1-2-1.dll in Windows 8.1. Old software still work because the dlls developer linked to are now just placeholders redirecting calls to the actual implementation. But nobody should link to the implementations directly, as that would be defeating the purpose of having such a redirection. Any software that report those dlls are missing are failing to accommodate the redirection (e.g. reporting a delay-loaded dependency as hard one). 

Don't try to obtain those dlls. The only supported way to get those DLLs is to do a major Windows upgrade (e.g. from Windows 7 to Windows 10). Distributing those files is against Windows end user agreement, and those files you get from a higher version of Windows won't work if your Windows version is too low.

If you are a developer, just use the APIs documented in the Windows SDK (unless absolute necessary like writing antivirus) and do not take any dependency on those dlls, as they may only exist in one Windows version. Those APIs may or may not use the DLLs you listed, but their dependencies are not yours to worry. You should only depend on documented APIs, not implementation details like the name of those DLL. E.g. instead of taking a direct dependency on api-ms-win-core-file-l1-2-0.dll you should take a dependency on kernel.dll which supports Windows 7 as well.

**Comment by shockr45** [comment] 2019-10-26 20:41
I have read similar explanations especially about upgrading to Windows 10. But most of the articles having the dll issues are Windows 10. So I deduce that is not the issue. I am not having this issue with other apps except Kodi.  Can you explain why I get this this comment when downloading any new nightly after 10/11/19. In doing the new downloads it erases the old version of what I had for Kodi. After the new downloads doesn't work, I can then go back and download the 19/11/19 nightly and it works fine. So if this were a Windows change, wouldn't it affect any download I would do after the Windows change? If it's Windows, I shouldn't be able to download the earlier nightly, right?

Sent from Yahoo Mail on Android 
 
  On Sat, Oct 26, 2019 at 1:24 PM, M2k80<notifications@github.com> wrote:@DaVukovic just read around a little, i found maybe something for interest?

hose DLLs are Windows's implementation detail and are subject to change at anytime. Basically Microsoft started moving around APIs starting from Windows 8. For example, APIs in Windows 8's api-ms-win-core-file-l1-2-0.dll got moved to api-ms-win-core-file-l1-2-1.dll in Windows 8.1. Old software still work because the dlls developer linked to are now just placeholders redirecting calls to the actual implementation. But nobody should link to the implementations directly, as that would be defeating the purpose of having such a redirection. Any software that report those dlls are missing are failing to accommodate the redirection (e.g. reporting a delay-loaded dependency as hard one).


Don't try to obtain those dlls. The only supported way to get those DLLs is to do a major Windows upgrade (e.g. from Windows 7 to Windows 10). Distributing those files is against Windows end user agreement, and those files you get from a higher version of Windows won't work if your Windows version is too low.

If you are a developer, just use the APIs documented in the Windows SDK (unless absolute necessary like writing antivirus) and do not take any dependency on those dlls, as they may only exist in one Windows version. Those APIs may or may not use the DLLs you listed, but their dependencies are not yours to worry. You should only depend on documented APIs, not implementation details like the name of those DLL. E.g. instead of taking a direct dependency on api-ms-win-core-file-l1-2-0.dll you should take a dependency on kernel.dll which supports Windows 7 as well.

**Comment by Dnkhatri** [comment] 2019-10-27 00:12
Windows 7 is getting out of life in 2-3 months. I don't think any effort should be put to maintain capabilities for the newer versions Kodi. Change the minimum requirements and move on.

**Comment by Montellese** [comment] 2019-11-17 10:28
I've run into the same issue after rebasing some of my branches from bf90ec9f91 to eb24dddef3 so the issue must have been introduce somewhere between those two revisions (maybe with the migration to Python 3?). I also tried a full `BuildSetup.bat` and ran the installer to get any VC++ redistributable packages but same problem.

**Comment by DaveTBlake** [comment] 2019-11-17 10:50
>Windows 7 is getting out of life in 2-3 months. I don't think any effort should be put to maintain capabilities for the newer versions Kodi. Change the minimum requirements and move on.

Given the lack of active Windows devs on the team that may well be the decision that is made @Dnkhatri . Also Win7 is not the only flavour of Windows that could become unsuported in later Kodi versions because of lack of developer interest. 

Since @Montellese is a team member and has reproduced this issue it is reasonable to mark this as "triage confirmed"

**Comment by Montellese** [comment] 2019-11-18 20:08
Based on my manual bisecting I figured out that Kodi does not require these DLLs right before the Python 3 merge (#16116) and with that PR merged it requires them so I assume that they come in with the python 3 lib. Who built the python 3 dependencies for win64 and are there any instructions? I could try to build them on windows 7 and see if that helps.

**Comment by DaveTBlake** [comment] 2019-11-19 09:12
> Who built the python 3 dependencies for win64 and are there any instructions? 

The work on the Py3 PR was done over 6 months before merge, patches were applied manually and undocumented, so who knows @Montellese :(

The suggestion is that digging about in those depends is a dead end. The route forwards is the approach here https://github.com/xbmc/xbmc/pull/16850 . That change isn't for Win64 (yet) because the jenkins build for Win64 currently works so isn't a priority. Could be worthwhile to test the 32 bit version on Win7. I'm sure @Rechi would be happy to have your input.

**Comment by CastagnaIT** [comment] 2020-01-03 10:04
does anyone have 64bit Windows 7 available to do a test?
I think i found the problem, but i can't know if it works, because in virtual pc it creates problems.

this is the fixed build for W7 x64 builded with latest master:
https://www.mediafire.com/file/9wbm7qt6vohkgke/KodiPortable_Build_19_W7_x64.zip/file

extract to a folder and run with the portable parameter `-p`

if c++ runtime complains, remove all c++ runtime versions and install the unified package:
https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

if it works then i can publish the fix

**Comment by Rechi** [comment] 2020-01-03 10:25
@CastagnaIT `dumpbin /dependents kodi.exe` looks correct for your version.
Please post your changes, then I can tell you if those are the correct fix.

**Comment by CastagnaIT** [comment] 2020-01-03 10:45
I would have liked to wait for a practical confirmation
but all right, i will do the PR

**Comment by Montellese** [comment] 2020-01-03 11:05
@CastagnaIT I will give it a try on my old Win7 x64 setup where I also noticed this issue. I've since migrated to Windows 10 though.

**Comment by Montellese** [comment] 2020-01-03 11:22
@CastagnaIT just tried it on my old Win7 x64 setup and after installing the latest vc++ runtime I was able to start Kodi, install the Youtube add-on and use it to browse and watch videos. So looks like you're on the right track.

**Comment by CastagnaIT** [comment] 2020-01-03 14:18
thanks @Montellese, @Rechi PR open ^^

**Comment by bigretromike** [comment] 2020-03-11 10:50
looks like this one got merged, congrats on fixing this for win7

**Comment by shockr45** [comment] 2020-03-11 15:18
Thanks for your work on this. Glad it is fixed. I couldn't be without Kodi, so I finally upgraded to Win 10.

Sent from Yahoo Mail on Android 
 
  On Wed, Mar 11, 2020 at 3:50 AM, BigRetroMike<notifications@github.com> wrote:   
looks like this one got merged, congrats on fixing this for win7

**Closed** 2020-03-11 19:11 UTC
Labels: Component: Depends, Platform: Windows, Triage: Confirmed, v19 Matrix
