### ISSUE TITLE
Kodi 19.1 won't play DVD

### ISSUE THREAD

**Issue by ukbeast** [xbmc/xbmc#20048] opened 2021-08-16 16:18 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi is unable to play DVDs kodi is detecting them as an incorrect image format
Detecting DVD-ROM media filesystem...
2021-08-16 17:00:55.662 T:28       INFO <general>: CD Analysis Report
2021-08-16 17:00:55.663 T:28       INFO <general>: __________________________________
                                                   
2021-08-16 17:00:55.664 T:28       INFO <general>: CD-ROM with ISO 9660 filesystem
2021-08-16 17:00:55.664 T:28       INFO <general>: ISO 9660: 0 blocks, label 
2021-08-16 17:00:55.664 T:28       INFO <general>: Tracks overall:1; Audio tracks:0; Data tracks:1
2021-08-16 17:00:55.664 T:28       INFO <general>: Using protocol iso9660://
2021-08-16 17:00:55.664 T:28       INFO <general>: Disc label: 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

 Kodi shold be able to play a DVD.

## Actual Behavior
Does does nothing when clicking on disc in menu.

### To Reproduce

1. Start Kodi
2. Put DVD in drive
3. Click the disc icon in kodi's menu

### Debuglog

The debuglog can be found here:
[kodi.log](https://github.com/xbmc/xbmc/files/6993844/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [✔ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by howie-f** [comment] 2021-08-16 16:49
@ukbeast what happens on the screen when you click the disc icon in the gui? activity at your dvd drive? does your dvd play with a different player like vlc or smplayer?

**Comment by DaVukovic** [comment] 2021-08-16 16:53
The issue is mostly that the DVD is not mounted automatically by the OS (even if it's mentioned in the Kodi logfiles). So I would try the following:

* stop kodi
* open a filemanager your OS provides
* try to access the disc via that filemanager
* if it's accessable then start Kodi again and see if you are able to play the disc via the `Play Disc` button. 

Could you please try that

**Comment by enen92** [comment] 2021-08-16 17:24
Iirc Kodi uses udisks to automount dvds, please double check if you have it installed

**Comment by DaVukovic** [comment] 2021-08-16 17:46
Unfortunately even with udisks installed Kodi will mount the disc automatically:

```
dnf list installed | grep -i udisks
libudisks2.x86_64                              2.9.3-1.fc34                                               @updates                                       
udisks.x86_64                                  1.0.5-17.fc34                                              @fedora                                        
udisks2.x86_64                                 2.9.3-1.fc34                                               @updates                                       
udisks2-iscsi.x86_64                           2.9.3-1.fc34                                               @updates                                       
```

But it's 100% reproducable if you mount the disc manually (either via commandline or via a filemanager), then Kodi will play the disc.

**Comment by ukbeast** [comment] 2021-08-16 18:15
The issue is happening under Plasma Desktop on Fedora 34.
I just installed the Gnome 40 and now my DVDs are working fine.
![Screenshot from 2021-08-16 19-14-18](https://user-images.githubusercontent.com/6401168/129610460-840536b3-057f-4ec6-b517-4ecb64111d45.png)

Might be the way kio handles things?

**Comment by DaVukovic** [comment] 2021-08-16 18:18
Cool

I'm using Fedora 34 with XFCE. 

So we can probably say. Kodi plays DVDs fine on GNOME but not with XFCE and/or Plasma (KDE)

**Comment by howie-f** [comment] 2021-08-16 18:34
> fine on GNOME but not with XFCE and/or Plasma 

yup, think i can confirm because i had the same issue on Debian/XFCE.. unfortunately no solution at hand :(

**Comment by kokika86** [comment] 2021-08-28 08:34
Hello,

If i can help with my experience :

I recently upgrade my Linux OS (From Debian Buster to Debian Bullseye, with the deb-repository beside).
After that no possibility to play dvd with kodi, but no problem to do that with mplayer for instance.
I had to open gnome-disks, go to the DVD drive and adjust mount options to set "defaults setting for user session". Without, i had to mount manually my dvd drive to grant access in Kodi.

I hope that may help you. Sorry for my bad English, i'm french, so i can cook, but i speak english very bad...

**Comment by basilgello** [comment] 2021-08-29 13:47
> so i can cook, but i speak english very bad

Definitely an excuse :D

**Comment by basilgello** [comment] 2021-08-29 13:49
> Debian/XFCE.. unfortunately no solution at hand :(

Interesting…  Is it an issue with "proper" video DVDs or dara DVDs containing rips?

**Comment by howie-f** [comment] 2021-08-29 14:48
yes in my case an official proper dvd. i once added a nullptr check to prevent kodi from crashing here https://github.com/xbmc/xbmc/pull/19000. maybe a good idea to show a gui message, not just log a debug message. i‘m not quite sure if we‘re running into the same issue here. would @ukbeast / @kokika86 check if the message is logged in debug mode?

**Comment by ElCoyote27** [comment] 2021-08-29 17:48
Just FYI, I had problems playing DVDs (ISOs mostly) with kodi 19.1 on Linux as well. I grabbed the source rpm (I'm on Fedora Linux 33) and rebuilt kodi with 'dvdcss' and it appears to work fine for playing un-encrypted DVDs again.
For Windows, I didn't know how to rebuild kodi with dvdcss on Windows so I reverted back to 18.5 and DVD playing works fine again there.

**Comment by afranchuk** [comment] 2022-01-22 03:32
I just went through a hassle to get DVDs to play as expected on my setup. I had to:
1. Make sure Kodi was launched with `--standalone` (my setup is a dedicated media server on void linux, Kodi won't automount with udisks unless run in standalone mode or automounting is configured manually).
2. Install libdvdcss, libdvdnav, libdvdread, udisks2, dbus, and polkit
3. Ensure dbus and polkit services were running
4. Configure polkit to allow the Kodi user to perform udisks2 actions without authentication.

At long last I can put in a DVD and it will play!

**Comment by dmahurin** [comment] 2023-06-28 17:07
hi @enen92,

It seems that this issue has prevented dvd disc playback in Batocera (and Recalbox I think), for every version with Kodi 19 and Kodi 20.

https://github.com/batocera-linux/batocera.linux/issues/4304

Did Kodi start requiring a mounted disc starting in Kodi 19.  That did not seem to be the case in Kodi 18.

If this is the case, could this old regression be fixed in Kodi 20 or Kodi 21?

**Comment by ElCoyote27** [comment] 2023-06-28 22:39
I am not sure how it worked previously within Kodi (Linux with libdvdread and libdvdcss) but it used to work for me with ISO images of DVDs on a fileserver share (over NFS).

**Comment by mmortal03** [comment] 2023-06-29 04:10
Could it be some sort of DVD drive region issue? The reason I ask is I just tested on Debian 12 (SparkyLinux), and neither Kodi 20.1 or VLC would play a physical, copy-protected, DVD *until* I installed regionset and set the DVD drive region. Then it worked. (I'm testing this on a second-hand laptop and I didn't think to check beforehand if the drive region had *already* been set to a different region, or if it had never been set -- but, obviously, it was one of the two.)

>I am not sure how it worked previously within Kodi (Linux with libdvdread and libdvdcss) but it used to work for me with ISO images of DVDs on a fileserver share (over NFS).

Before I did anything, I first tested this. Kodi 20.1 was able to play an ISO image of a non-copy-protected DVD movie stored on a fileserver share (tested over SMB, in my case).

**Comment by basilgello** [comment] 2023-06-29 04:27
@mmortal03 That's because Kodi from Debian has @enen92 's patchset for dvd play fix. dvdcss is not installed by default, though.

**Comment by dmahurin** [comment] 2023-06-29 14:37
@enen92, I checked this again on old live systems.  With Kodi 18.9 or Batocera (release 30 and before) and Kodi 18 on Retropie, the disc is not mounted, and DVD's play fine.  The mount requirement ( regression ) started in Kodi 19 I believe.

**Comment by dmanlfc** [comment] 2023-07-11 11:51
@dmahurin yes it's fixed

**Closed** 2023-07-26 21:11 UTC
Labels: Platform: Linux, v19 Matrix, Triage: Has proposed fix, v20 Nexus, Component: Discs
