### ISSUE TITLE
Kodi does not pick up a change in FLAC cover art when updating the Music library

### ISSUE THREAD

**Issue by CRCulver** [xbmc/xbmc#16437] opened 2019-08-04 03:00 UTC
### Describe the bug

In Kodi 18.3, Kodi will pick up the cover art embedded in a FLAC file the first time it is added to the Music database. However, if the cover art in that file is changed, and then the user performs “Update library”, Kodi continues to show the old cover art in the library interface.

## Expected Behavior

Kodi should treat a change in a FLAC file’s embedded cover art in the same way that it treats changes in that file’s other metadata tags. So, when one updates the library and then navigates to that music in the library, the new cover art should be shown instead of the old cover art.

## Actual Behavior

Kodi continues to show the old cover art in the library interface.

### To Reproduce

1. Add a FLAC file with embedded cover art to the Music library.
2. Using a tool such as metaflac, replace the embedded cover art with a different image.
3. Choose “Update library” from the menu
4. Navigate to that song and see that the old cover art is still shown instead of the new one.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaveTBlake** [comment] 2019-08-04 13:41
@CRCulver if you had discussed your experience on the forum first I would have been able to explain that it is normal behaviour resulting from the latency in thumbnail cache updates. Same thing happens is you have album cover art in an external file e.g. folder.jpg and having scanned it into Kodi later change the image in that file. You do not see that change immediately, but only after the thumbnail cache has updated. That is a background process, and images get recached the next time they are displayed **at least 24 hours since they were previously re-cached**.

This is longstanding behaviour inherent in the texture caching design, and not specific to FLAC files or the way metadata is read. Thus is  not a bug and so I am going to close this issue. However if you would like to post a feature request in the forum (not Github) regarding changing the texture cache management so that  changes to the file contents of local art are seen immediately then that is the right place for that discussion.

**Closed** 2019-08-04 13:42 UTC
Labels: Ignored rules, Triage: Needed
