### ISSUE TITLE
Hidden files and directories are ALWAYS displayed in Video Library

### ISSUE THREAD

**Issue by dm1825** [xbmc/xbmc#19440] opened 2021-03-18 05:50 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

I have set up my video library to point to a shared directory my Windows 10 PC.  My shared directory has hidden files and directories in it.

Hidden files and directories are ALWAYS displayed in my video library whether or not the setting “Show hidden files and directories” in “Settings/Media/General” is on or off.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Hidden files and directories should only be displayed in my video library when the setting “Show hidden files and directories” in “Settings/Media/General” is on; otherwise, hidden files and directories should not be displayed in my video library.

## Actual Behavior

Hidden files and directories are ALWAYS displayed in my video library.

### To Reproduce

1. Create a Windows 10 shared directory.  Add several files and directories.  Make a few of the files and directories hidden
2. Set up your video library to point to the Windows 10 shared directory
3. View your video library, it will display the hidden files and directories
4. Change the setting “Show hidden files and directories” in “Settings/Media/General” to ON (default is OFF)
5. View your video library, it will display the hidden files and directories
6. Change the setting “Show hidden files and directories” in “Settings/Media/General” to OFF
7. View your video library, it will display the hidden files and directories.

### Debuglog

The debuglog can be found here:

[FTPManager - Mar 16, 2021 at 8:00 PM.pdf](https://github.com/xbmc/xbmc/files/6161365/FTPManager.-.Mar.16.2021.at.8.00.PM.pdf)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 Android: Firestick 4K
Windows: 10
 
 - Kodi version:
19.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by dm1825** [comment] 2021-10-02 00:39
“Show hidden files and directories” in “Settings/Media/General” option does not exist in Kodi 19.1

I hope this not “the fix” for this issue as I found this option very useful.

**Comment by zaochen365** [comment] 2022-08-27 16:12
The shield TV Android system has the same problem

**Comment by zaochen365** [comment] 2023-04-21 03:58
Kodi v21 (Omega) Pre release Builds has the same issue

**Comment by dm1825** [comment] 2024-04-21 23:10
Still an issue in Kodi 21.0

**Comment by CrystalP** [comment] 2024-04-22 01:12
I'm closing the ticket because github issues are for confirmed bugs and not for support requests. Please start a thread in the forums for support.
I still gave this a quick try with a Windows server and client and the "show hidden..." setting worked exactly as expected (files/folders hidden by Windows hidden attribute or by leading . character). At first I had a little trouble making the hidden files appear, because they don't appear in directories defined as sources for the library.
Anyway there probably is something different in your environment, to be figured out in forum support.

**Closed by CrystalP** 2024-04-22 01:12 UTC

**Comment by dm1825** [comment] 2024-04-22 02:28
You did not read the ticket carefully enough.  Windows PC, android client as stated in the Kodi log.

This once worked, it no longer does.  I just now changed half of my folders on my WINDOWS machine to hidden.

I went to my FIRE STICK (NOT MY WINDOWS CLIENT) that runs KODI, flipped the “show hidden” multiple times back and forth and the files ALWAYS show.  I also exited Kodi and then retried.

zaochen365 replied to this ticket at one time stating that the issue still existed in 21 prerelease:
![image](https://github.com/xbmc/xbmc/assets/80797644/5dd8fcf8-a660-44d1-9e3a-7cf322a149c3)

At this point, over 3 years since I created the ticket, I’m sorry I wasted my time creating this ticket for a feature I found extremely useful.

**Comment by dm1825** [comment] 2024-04-22 02:57
﻿I updated the ticket after your closed it.  Please read my comments, I believe you are incorrect.On Apr 21, 2024, at 6:13 PM, CrystalP ***@***.***> wrote:﻿
I'm closing the ticket because github issues are for confirmed bugs and not for support requests. Please start a thread in the forums for support.
I still gave this a quick try with a Windows server and client and the "show hidden..." setting worked exactly as expected (files/folders hidden by Windows hidden attribute or by leading . character). At first I had a little trouble making the hidden files appear, because they don't appear in directories defined as sources for the library.
Anyway there probably is something different in your environment, to be figured out in forum support.

**Comment by CrystalP** [comment] 2024-04-22 07:39
This is not the correct channel to request support, the forum is. There is no link here to a forum thread showing troubleshooting efforts. No team member went "I have this issue as well" either.

I tried with the equipment I have on hand to be helpful. I knew it wasn't exactly like yours but still shows that the function is not completely broken and more investigating is needed. The fact that your client is on Android may be a clue. You also just stated that it used to work and that could also be a useful clue if the date it broke can be precise enough.

**Comment by dm1825** [comment] 2024-04-22 14:04
Thanks for your incompetence.On Apr 22, 2024, at 12:40 AM, CrystalP ***@***.***> wrote:﻿
This is not the correct channel to request support, the forum is. There is no link here to a forum thread showing troubleshooting efforts. No team member went "I have this issue as well" either.
I tried with the equipment I have on hand to be helpful. I knew it wasn't exactly like yours but still shows that the function is not completely broken and more investigating is needed. The fact that your client is on Android may be a clue. You also just stated that it used to work and that could also be a useful clue if the date it broke can be precise enough.
