### ISSUE TITLE
Test failures

### ISSUE THREAD

**Issue by candrews** [xbmc/xbmc#14943] opened 2018-11-25 20:55 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

I'm building Kodi 18.0rc1 and running the tests using `make -C <builddir> kodi-test` (exact commands can be found in the build log).

Here's the output:
```
94% tests passed, 29 tests failed out of 520

Total Test time (real) =  66.23 sec

The following tests FAILED:
         28 - TestXBMCTinyXML.ParseFromFileHandle (Failed)
        201 - TestPOUtils.General (Failed)
        439 - TestMassEvent.Polling (Child aborted)
        440 - TestPlayListXSPF.Load (Failed)
        449 - TestWebServer.CanHeadFile (Failed)
        451 - TestWebServer.CanGetFile (Failed)
        452 - TestWebServer.CanGetFileForcingNoCache (Failed)
        453 - TestWebServer.CanGetCachedFileWithOlderIfModifiedSince (Failed)
        456 - TestWebServer.CanGetCachedFileWithNewerIfModifiedSinceForcingNoCache (Failed)
        457 - TestWebServer.CanGetCachedFileWithOlderIfUnmodifiedSince (Failed)
        458 - TestWebServer.CanGetCachedFileWithExactIfUnmodifiedSince (Failed)
        459 - TestWebServer.CanGetCachedFileWithNewerIfUnmodifiedSince (Failed)
        460 - TestWebServer.CanGetRangedFileRange0_ (Failed)
        461 - TestWebServer.CanGetRangedFileRange0_End (Failed)
        462 - TestWebServer.CanGetRangedFileRange0_2xEnd (Failed)
        463 - TestWebServer.CanGetRangedFileRange0_First (Failed)
        464 - TestWebServer.CanGetRangedFileRangeFirst_Second (Failed)
        465 - TestWebServer.CanGetRangedFileRange_Last (Failed)
        466 - TestWebServer.CanGetRangedFileRangeFirstSecond (Failed)
        467 - TestWebServer.CanGetRangedFileRangeFirstSecondLast (Failed)
        468 - TestWebServer.CanGetCachedRangedFileWithOlderIfRange (Failed)
        469 - TestWebServer.CanGetCachedRangedFileWithExactIfRange (Failed)
        470 - TestWebServer.CanGetCachedRangedFileWithNewerIfRange (Failed)
        479 - TestZipFile.Read (Failed)
        480 - TestZipFile.Exists (Failed)
        481 - TestZipFile.Stat (Failed)
        482 - TestZipFile.CorruptedFile (Failed)
        484 - TestFileFactory.Write (Failed)
        485 - TestFile.Read (Failed)
Errors while running CTest
```
Here's the full log (including building and running tests): https://www.integralblue.com/kodi/18.0rc1-test-failures/build.log
And here's Temporary/LastTest.log: https://www.integralblue.com/kodi/18.0rc1-test-failures/LastTest.log

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I expect all tests to pass to ensure all Gentoo users have a trouble-free Kodi experience.

## Actual Behavior

29 tests currently fail.

## Possible Fix

Not sure; the reasons for any of the failures are not apparent to me. I'm happy to try different things (different configuration options, dependency versions, patches, etc) and report results, please let me know how I can help :)

### To Reproduce

1. Build Kodi
2. Run tests

### Debuglog

The debuglog can be found here:

This is a build time and test issue, so the debuglog is not applicable.

### Screenshots 
Here are some links or screenshots to help explain the problem:

This is a build time and test issue, so screenshots are not applicable.

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I'd like to have the tests pass to make sure that the build is fully functionality and users (myself included) won't have any problems.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Gentoo/Linux
 - Kodi version: 18.0rc1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Rechi** [comment] 2018-11-26 10:40
@ksooo it is caused by https://github.com/xbmc/xbmc/pull/14511/commits/c617d4c5624eeac181fb5f00e94a79f33947e30b in #14511.

**Comment by candrews** [comment] 2018-12-03 18:07
@ksooo since PR caused these test failures, can you please take a look at fixing this issue?

**Comment by wsnipex** [comment] 2018-12-06 08:12
>100% tests passed, 0 tests failed out of 521
I can't reproduce this on ubuntu 18.04 with system libs

**Comment by candrews** [comment] 2018-12-06 18:49
Testing with c617d4c~:
> 99% tests passed, 1 tests failed out of 518
> Total Test time (real) =  66.10 sec
> The following tests FAILED:
>     447 - TestWebServer.CanHeadFile (Failed)

Testing with c617d4c:
>95% tests passed, 27 tests failed out of 518
>Total Test time (real) =  69.53 sec
>The following tests FAILED:
>         28 - TestXBMCTinyXML.ParseFromFileHandle (Failed)
>        201 - TestPOUtils.General (Failed)
>        447 - TestWebServer.CanHeadFile (Failed)
>        449 - TestWebServer.CanGetFile (Failed)
>        450 - TestWebServer.CanGetFileForcingNoCache (Failed)
>        451 - TestWebServer.CanGetCachedFileWithOlderIfModifiedSince (Failed)
>        454 - TestWebServer.CanGetCachedFileWithNewerIfModifiedSinceForcingNoCache (Failed)
>        455 - TestWebServer.CanGetCachedFileWithOlderIfUnmodifiedSince (Failed)
>        456 - TestWebServer.CanGetCachedFileWithExactIfUnmodifiedSince (Failed)
>        457 - TestWebServer.CanGetCachedFileWithNewerIfUnmodifiedSince (Failed)
>        458 - TestWebServer.CanGetRangedFileRange0_ (Failed)
>        459 - TestWebServer.CanGetRangedFileRange0_End (Failed)
>        460 - TestWebServer.CanGetRangedFileRange0_2xEnd (Failed)
>        461 - TestWebServer.CanGetRangedFileRange0_First (Failed)
>        462 - TestWebServer.CanGetRangedFileRangeFirst_Second (Failed)
>        463 - TestWebServer.CanGetRangedFileRange_Last (Failed)
>        464 - TestWebServer.CanGetRangedFileRangeFirstSecond (Failed)
>        465 - TestWebServer.CanGetRangedFileRangeFirstSecondLast (Failed)
>        466 - TestWebServer.CanGetCachedRangedFileWithOlderIfRange (Failed)
>        467 - TestWebServer.CanGetCachedRangedFileWithExactIfRange (Failed)
>        468 - TestWebServer.CanGetCachedRangedFileWithNewerIfRange (Failed)
>        477 - TestZipFile.Read (Failed)
>        478 - TestZipFile.Exists (Failed)
>        479 - TestZipFile.Stat (Failed)
>        480 - TestZipFile.CorruptedFile (Failed)
>        482 - TestFileFactory.Write (Failed)
>        483 - TestFile.Read (Failed)

**Comment by Millak** [comment] 2019-01-13 09:45
test 449 fails for me on upgrading from 18.0rc1 to rc3 or rc4
https://ci.guix.info/log/s4qb9raga39mk2rq3yrwki7s8085k8zr-kodi-18.0rc3
(build occurs with no network access if it makes a difference)

**Comment by fuzzard** [comment] 2020-06-17 03:53
Hows this fairing for tests now against master/leia tip?

**Comment by Millak** [comment] 2020-06-17 11:33
I tested just now. 18.7.1 still fails TestWebServer.CanHeadFile for me, as does the tip of Leia (1bcc91bb25b58b94a973c1b470b15505ef38d607). I ran into issues trying to get the tip of master to compile.

**Comment by fuzzard** [comment] 2020-06-17 19:24
Can you provide more details of the build environment.

**Comment by enen92** [comment] 2022-01-08 19:28
closing as stalled, no idea if it still happens on v20. Looking at current jenkins automated builds I guess it doesn't.

**Closed by enen92** 2022-01-08 19:28 UTC
Labels: Platform: Linux, v18 Leia
