### ISSUE TITLE
Select "Timer rules" causes restart Kodi18 Leia (or LibreElec) in Spanish language

### ISSUE THREAD

**Issue by Davizator** [xbmc/xbmc#15142] opened 2018-12-27 10:53 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

In language spanish, if select the option in TV->"Reglas de programación", Kodi restarts if exists al least one rule added.
If there isn't some rule added then works ok.
Other languages works ok.
In kodi for android works ok.
## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The "Timer rules" window must appear.

## Actual Behavior

The "Timer rules" windows doesn't appear, in place Kodi restarts.

## Possible Fix

Is posible the character non ascii "ó" is the guilty'?

### To Reproduce

1. Change the language to "Spanish". Add one Timer rule.
2. Go to TV->"Reglas de programación"
3. Select the option and kodi restarts.

### Debuglog

The debuglog can be found here:
[kodi.log](https://github.com/xbmc/xbmc/files/2729841/kodi.log)
[kodi.old.log](https://github.com/xbmc/xbmc/files/2729842/kodi.old.log)
[kodi_crashlog_20190105204701.log](https://github.com/xbmc/xbmc/files/2729843/kodi_crashlog_20190105204701.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 Pro
 - Kodi version: Kodi 18.0 RC3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Davizator** [comment] 2018-12-27 23:38
It's right now? Need something else?

**Comment by DaVukovic** [comment] 2018-12-28 05:42
> Need something else?

Yes a clean log. You have banned add-ons installed.

**Comment by Davizator** [comment] 2018-12-28 09:43
ok, I updated the bug report and there is a new log.
Sorry, is my first bug report.

**Comment by DaVukovic** [comment] 2018-12-30 08:30
And still there are banned add-ons involved

Start with a clean Kodi and only add the PVR addon you need.

I tried with a fresh compiled Kodi from master on Ubuntu and also compiled pvr.hts and I can't reproduce that issue at all. Might be windows specific, but noone will take care if you won't remove those banned add-ons

**Comment by Davizator** [comment] 2018-12-30 19:15
OK. I do a fresh installation of LibreElec, the logs are updated.
If there is timer rules and some programing activated, the option fails and Libreelec is restarted. If all programing is deativated or there is not timer rules then works fine.
No addons banned, only VDR VNSI client and server(with no plugins activated), the movie database,universal artist scraper and universal album scraper configured.

**Comment by DaVukovic** [comment] 2019-01-05 18:47
Could you please test one of the latest [milhouse nightlies](https://forum.kodi.tv/showthread.php?tid=298462)

There was a PR lately where another language caused a similar issue. Maybe it's already fixed. 

If not, please provide a new debuglog. Thanks and sorry for the late response

**Comment by Davizator** [comment] 2019-01-05 20:01
Sorry, crash persist after update Libreelec with LibreELEC-Generic.x86_64-9.0-Milhouse-20190103214509-#0103-g321744c
Log files updated. Thanks.

**Comment by fritsch** [comment] 2019-01-05 20:20
The stack trace seems that something in GetStatus goes wrong ... when a cons str is passed into Format. Just try to copy the string before passing it as a string, not as cstring.

**Comment by fritsch** [comment] 2019-01-05 20:42
Please try http://paste.ubuntu.com/p/qGWB4jJWZY/ to see if I am on the right page.

**Comment by fritsch** [comment] 2019-01-05 20:46
Ah perfect - after syncing with @DaVukovic the format was wrong - all fine.

**Comment by pkerling** [comment] 2019-01-06 10:36
@Davizator Please take care not to close issues by accident (presumably by pressing the wrong button).

**Comment by Davizator** [comment] 2019-01-06 19:17
Oooopsss, sorry, that was no my intention.

**Comment by DaVukovic** [comment] 2019-01-06 20:53
@Davizator 

Could you please update your language addon and see if Kodi still cashes? I fixed some modifiers of different languages and there was also an issue with one string of your language

Pease report back if Kodi is now working so we can mark this as solved and close it.

Thanks

**Comment by Davizator** [comment] 2019-01-07 07:59
OK. I'll do it.

**Comment by Davizator** [comment] 2019-01-07 16:49
After update the spanish language addon to 9.0.17 all works fine, no bug. You can close it. Thanks.

**Comment by DaVukovic** [comment] 2019-01-07 17:46
Thx for the feedback :+1:

Closed

**Closed by DaVukovic** 2019-01-07 17:46 UTC
