### ISSUE TITLE
Music playback stops when screen goes off (Shield)

### ISSUE THREAD

**Issue by RayBan91** [xbmc/xbmc#15632] opened 2019-02-27 21:06 UTC
### Describe the bug
Hello,
according to topic created on forum: https://forum.kodi.tv/showthread.php?tid=341266, I want to report problem. After upgrade Kodi to 18 and now 18.1 version I lost pssibility to lissten my music when screen is off.
In 17.x version I controled music playback using Yatse without turning on scrren, now I need to power on my projector.

Regards, Rafał.

## Expected Behavior
Music still plays when screen goes off.

## Actual Behavior
Music stops playing after screen goes off.

## Possible Fix
Restore this function or give possibility to choose.

### To Reproduce
1. Start listen music
2. Off the screen

### Debuglog
The debuglog can be found here:
https://paste.kodi.tv/edamudidac.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
 - Android
 - Nvidia Shield 
 - external USB audio DAC.
 
- Operating system version/name:
 - Kodi version: 18.1

**Comment by KarellenX** [comment] 2019-02-28 03:45
Neither this Issue or your forum thread contains a Debug Log.

Please provide one which captures your issue.

**Comment by RayBan91** [comment] 2019-02-28 20:46
Log added.
At 18:34 I turned off screen.

**Comment by KarellenX** [comment] 2019-03-01 01:56
Thanks, but please provide the **full** debug log which captures the issue.

**Comment by RayBan91** [comment] 2019-03-01 18:52
I have been change URL address.

**Comment by KarellenX** [comment] 2019-03-01 19:09
I am not sure what  you mean by your last post. 

We need the **FULL** log. We do not want a piece of the log that you decide is all we need.

Can you provide that? If no, then this issue will be closed.

**Comment by RayBan91** [comment] 2019-03-01 21:32
I have been change URL address with debug LOG. If it's not enought please tell me what I need to upload.
I thougt You are here to help not to require proof, but if it's nesesery I will place it below:
https://1drv.ms/v/s!AoWffRc_P_i7g6xZOXGR5N5W93NY0A
This is my whole log: https://paste.kodi.tv/qoyadocavi.kodi

**Comment by KarellenX** [comment] 2019-03-01 22:07
That log is still not correct. You have not followed the instructions correctly. You need to **RESTART** kodi once you enable debug mode. So now we have missed out on ciritical information during the startup process.  It is up to you if you want to try again, but be warned the issue will go no further without it.

What have you done about all those network errors in your log? Do you think they could be contributing to your problem?? I am guessing you will say no.

Also, this should have remained on the forum, not opened here. One of the reasons you did  not receive a response is that you provided no debuglog. I am inclined to close this issue, but I will wait for other Moderators to agree.

**Comment by RayBan91** [comment] 2019-03-02 00:19
So, You are perfectly sure that my errors with problems to open directory is the reason of my issue. And this is olny one thing what I need to do to resolve my that problem?
So when I will install fresh Kodi and connect only one direcotry with album (without those errors) my problem will be resolved?
Becouse I want to be sure this solution when I will remove all of my Kodi configuration.

**Comment by KarellenX** [comment] 2019-03-02 00:45
> So, You are perfectly sure that my errors with problems to open directory is the reason of my issue.

No I am not sure. But when your log is full of errors, I think that it is just common sense that you fix those first before sending volunteers on a wild goose chase.

At this stage your issue is not a bug in Kodi, but an issue with your setup, and I have spent more than enough time just trying to get a proper log out of you. I will close this issue. You can continue on the forum where there are **more** members that may have the knowledge to assist you.

**Closed by KarellenX** 2019-03-02 00:45 UTC
Labels: INVALID, Music
