### ISSUE TITLE
Letterboxing on iPad mini 6

### ISSUE THREAD

**Issue by S0ulf3re** [xbmc/xbmc#21717] opened 2022-07-29 17:45 UTC
I just installed Kodi  19.4.0 on my iPad mini 6. And it appears that there is some letterboxing due to the aspect ratio changes from the 5 to the 6's bezels. Below is a picture of the system info
<img width="1133" alt="Screenshot 2022-07-29 at 13 43 30" src="https://user-images.githubusercontent.com/50301900/181815489-33e8306f-8f5a-457d-8a06-e0d2c5939876.png">

**Comment by thexai** [comment] 2022-08-04 09:19
Duplicate of https://github.com/xbmc/xbmc/issues/21723

**Closed by thexai** 2022-08-04 09:19 UTC
Labels: Resolution: Duplicate
