### ISSUE TITLE
Nvidea Shield tv crashed na update kodi v21.0  crasht na afspelen *.iso bestanden

### ISSUE THREAD

**Issue by Romesly** [xbmc/xbmc#25088] opened 2024-04-29 11:21 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

With all 3 x Nvidea Shield TV we can't play *.iso files anymore. It's a big problem because we have a big *.iso file collection. We have edit a lot old private movies in a blue ray menu that's why we use *.iso in our NAS synology system. Hope it can fixed soon with a new update.

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:v21.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Romesly** [comment] 2024-04-30 08:01
Sorry, I'm not handy with share the logs because Kodi don't show logs from this issue! The problem is when I select an *.iso file in a clean Kodi installation at my Nvidea Shield Tv android system then Kodi crasht to the begin screen from Nvidea shield tv. There's no error log also when I select report error logs in system. Hopefully can someone explain how to report this issue easy and clearly that Kodi can fix this problem! That's why and other friends the kodi.

Please help us to fix this.

Kindly regards ,

Romesly



Verzonden vanaf mijn Galaxy



-------- Oorspronkelijk bericht --------
Van: "xbmc-gh-bot[bot]" ***@***.***>
Datum: 29-04-2024 19:42 (GMT+01:00)
Aan: xbmc/xbmc ***@***.***>
Cc: Romesly ***@***.***>, Author ***@***.***>
Onderwerp: Re: [xbmc/xbmc] Nvidea Shield tv crashed na update kodi v21.0 crasht na afspelen *.iso bestanden (Issue #25088)


Thank you for using Kodi and our issue tracker. This is your friendly Kodi GitHub bot 😉

The issue that you have opened was marked as ignoring the rules of our bug tracker by a team member. Please review the following requirements for issue reports and make sure that you follow all of them:

  *   Reports must follow our template<https://github.com/xbmc/xbmc/blob/master/.github/ISSUE_TEMPLATE.md> and have all relevant fields filled in.
  *   A full debug log<https://kodi.wiki/view/Log_file> is always mandatory.
     *   Make sure that you restart Kodi after setting the log level to debug.
     *   Log files may not be modified except for the removal of personally identifying information, usernames/passwords and similar.
     *   For build errors, include a full build log instead.
  *   You may not have any banned add-ons<https://kodi.wiki/view/Official:Forum_rules/Banned_add-ons> installed.
  *   Bugs should be reproduced on a clean Kodi installation whenever possible.

Please understand that adherence to these rules is required for the team to be able to handle the volume of open issues efficiently. The issue will be closed after one week has passed without satisfactory follow-up from your side.

**Comment by neo1973** [comment] 2024-04-30 10:45
Duplicate of #24955, will be fixed in 21.1. Until then the Omega nightlies can be used: https://mirrors.kodi.tv/nightlies/android/

**Closed by neo1973** 2024-04-30 10:45 UTC
Labels: Ignored rules, Triage: Needed

**Comment by Romesly** [comment] 2024-04-30 11:15
Dear Markus,

Super thanks for the information! I will try install the nightflies edition later today.

Kindly regards,

Romesly



Verzonden vanaf mijn Galaxy


-------- Oorspronkelijk bericht --------
Van: Markus Härer ***@***.***>
Datum: 30-04-2024 12:45 (GMT+01:00)
Aan: xbmc/xbmc ***@***.***>
Cc: Romesly ***@***.***>, Author ***@***.***>
Onderwerp: Re: [xbmc/xbmc] Nvidea Shield tv crashed na update kodi v21.0 crasht na afspelen *.iso bestanden (Issue #25088)


Duplicate of #24955<https://github.com/xbmc/xbmc/issues/24955>, will be fixed in 21.1. Until then the Omega nightlies can be used: https://mirrors.kodi.tv/nightlies/android/
