### ISSUE TITLE
StreamDetails broken for DVD, Bluray and ISO 

### ISSUE THREAD

**Issue by KarellenX** [xbmc/xbmc#18702] opened 2020-11-01 23:44 UTC
### Describe the bug

Sometime early 2019 a change to v18 caused a break in populating the **streamdetails** table. 

A few attempts were made to fix the issue, ultimately resulting in a change to the way streamdetails were read and saved.

This new method will only read and save streamdetails in the following instances:

1. First scan of the movie \ episode (not subsequent delete from library and rescan)
2. Refresh of the movie \ episode

It no longer saves streamdetails from playback.

This caused a flood of complaints, and we still receive complaints about missing streamdetails and missing flags

Some relevant PR's here...
https://github.com/xbmc/xbmc/pull/12651
https://github.com/xbmc/xbmc/pull/15589
https://github.com/xbmc/xbmc/issues/15896
https://github.com/xbmc/xbmc/issues/15929
https://github.com/xbmc/xbmc/pull/16342

## Expected Behavior

Streamdetails for every type of video file/folder handled by Kodi should populate the streamdetails table.

## Actual Behavior
The current implemented method in v18 and v19 does not work for the following:

Movies or episodes saved with Bluray folder structure
Movies or episodes saved with DVD folder structure
Movies or episodes saved as an ISO file

Which means this works in a single instance only - when using single video files.

This does not work as expected for TV Shows even when using standard single video files like mkv. Refreshing the TV Show and then answering Yes to refresh the episodes does not refresh streamdetails.

Each episode needs to be refreshed individually for this to work. If there are 50 episodes in the show, that is a lot of work to refresh each episode.

Refreshing is not the way to go. It kills any personal edits the user has made for that movie/episode.

Could this entire approach be redesigned. It really is making a mess of peoples libraries.

### To Reproduce
1.  Scan a bluray structure movie into the library.
2.  Note the missing codecs / flags.
3.

### Debuglog
The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

Flags / codecs displayed for single file videos (mkv, avi, etc)
![singlefile](https://user-images.githubusercontent.com/44626605/97818458-a3c41000-1cf6-11eb-963a-6b3501916e49.jpg)

Bluray structure displays no flags / codecs
![bluray](https://user-images.githubusercontent.com/44626605/97818483-c6eebf80-1cf6-11eb-9746-00941e7edc9f.jpg)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: All
 - Kodi version: v18 and v19

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by arnova** [comment] 2021-01-02 14:34
Note that I'm still puzzled as to why VideoPlayer is no longer able to extract stream details from DVD/BR. This wasn't caused by the changes in the thumb/details extraction logic but rather something in VideoPlayer itself. A while back I already tried to isolate the issue but I was unable to resolve it, also because VideoPlayer is not really my area of expertise (and an area where a lot has changed over the years). Have a look at #15929 & #16555

**Comment by KarellenX** [comment] 2021-01-05 21:47
Hi @arnova 

IIRC the break was caused by changes made by FernetMenta. 

It is a shame it no longer works the way it used to, but thanks for your efforts to bring some of that feature back.

**Comment by Reemtsman** [comment] 2021-03-27 12:30
Not sure if this helps:
From my Experience 18.3 was the last version that was still able to display the Media Info from Iso Files after Playback. So the rootcause of this problem most likely lies in the changes implemented AFTER 18.3.

**Comment by TeHaX** [comment] 2021-03-27 14:24
Then one of the 28 fixes from 18.4 cause the issue, but which?
[https://github.com/xbmc/xbmc/milestone/127](url)

**Comment by Reemtsman** [comment] 2021-03-28 12:21
@TeHaX That is probably the 50 Dollar Question. Unfortunately i am only a enduser with zero IT and programming skills. Therefore i can only support by sharing my observations. Analyzing the fixes is way beyond my abilities.

**Comment by arnova** [comment] 2021-03-29 07:04
> Not sure if this helps:
> From my Experience 18.3 was the last version that was still able to display the Media Info from Iso Files after Playback. So the rootcause of this problem most likely lies in the changes implemented AFTER 18.3.

Are you 100% sure about this? Afaik the problem was introduced with 18.0.

**Comment by arnova** [comment] 2021-03-29 07:21
Ah yes it "broke" with 18.4 because of #16322. Perhaps that PR could be revived if would force an update of streamdetails for dvd/br/iso only. Need to think about that.

**Comment by arnova** [comment] 2021-03-29 12:19
Well as it turns out, it's not only #16332 that's responsible for breaking. Can someone verify this actually still worked in 18.3 ? And if not, in which version it did break?

**Comment by Reemtsman** [comment] 2021-03-29 16:50
@arnova 
Last weekend i had worked my way backwards through Kodi 18.6, 18.5 to 18.3 and 18.3 was the first that displayed Media Info again after short playback of the Iso. I could not test 18.4 as i had no backup from the corresponding install.exe. 
But it defenitely worked NOT in 18.6 and 18.5
But it worked in 18.3..... at least in my setup.

I just cehecked again with another Iso and Kodi 18.3: NO Media Info PRIOR Playback, WITH Media Info AFTER Playback.

If that helps and somebody can provide me the corresponding install.exe i can try out 18.4 as well.

**Comment by the-black-eagle** [comment] 2021-04-02 09:49
This doesn't work (AFAICT) for two reasons.
1) I can't find anywhere where this property is set
https://github.com/xbmc/xbmc/blob/145e4133eb924ed5bfe28179868575222b104778/xbmc/Application.cpp#L3176
`grep -nHIrF "get_stream_details_from_player"` only gives me that one line.

2) I think the code is meant to match the currently playing stream against the stream details in `m_SelectionStreams` to get an index which is used to look up the required info.
https://github.com/xbmc/xbmc/blob/145e4133eb924ed5bfe28179868575222b104778/xbmc/cores/VideoPlayer/VideoPlayer.cpp#L4932-L4956
I've tested several ISO's against this and `m_content.m_videoIndex` & `m_content.m_audioIndex` are always -1, thus no match is found and no stream details are returned.
I don't know enough (anything really!) about how the available streams are added and then matched against the currently playing stream to be able to fix this properly.  I did hack in some code that uses `m_currentVideo.hint.foo` as a test and that works but it's not the correct way to do it.
Hopefully this might help someone with more in-depth knowledge than me to be able to fix this correctly.

**Comment by arnova** [comment] 2021-04-02 10:02
> This doesn't work (AFAICT) for two reasons.
> 
> 1. I can't find anywhere where this property is set
>    https://github.com/xbmc/xbmc/blob/145e4133eb924ed5bfe28179868575222b104778/xbmc/Application.cpp#L3176
>    
>    `grep -nHIrF "get_stream_details_from_player"` only gives me that one line.
> 2. I think the code is meant to match the currently playing stream against the stream details in `m_SelectionStreams` to get an index which is used to look up the required info.
>    https://github.com/xbmc/xbmc/blob/145e4133eb924ed5bfe28179868575222b104778/xbmc/cores/VideoPlayer/VideoPlayer.cpp#L4932-L4956
>    
>    I've tested several ISO's against this and `m_content.m_videoIndex` & `m_content.m_audioIndex` are always -1, thus no match is found and no stream details are returned.
>    I don't know enough (anything really!) about how the available streams are added and then matched against the currently playing stream to be able to fix this properly.  I did hack in some code that uses `m_currentVideo.hint.foo` as a test and that works but it's not the correct way to do it.
>    Hopefully this might help someone with more in-depth knowledge than me to be able to fix this correctly.

Yes, but unfortunately I already figured that out also but couldn't come up with a fix either (VideoPlayer is not my area of expertise). FYI: the "get_stream_details_from_player"-property is used by addons to allow get them to get streamdetails. I already planned on adding rules for DVD/BR there but then first the other issue needs to be fixed else it's useless....

**Comment by arnova** [comment] 2021-04-02 10:11
I think this is where it should happen and isn't: https://github.com/xbmc/xbmc/blob/145e4133eb924ed5bfe28179868575222b104778/xbmc/cores/VideoPlayer/VideoPlayer.cpp#L431-L470

**Comment by arnova** [comment] 2021-04-02 13:51
> @arnova
> Last weekend i had worked my way backwards through Kodi 18.6, 18.5 to 18.3 and 18.3 was the first that displayed Media Info again after short playback of the Iso. I could not test 18.4 as i had no backup from the corresponding install.exe.
> But it defenitely worked NOT in 18.6 and 18.5
> But it worked in 18.3..... at least in my setup.
> 
> I just cehecked again with another Iso and Kodi 18.3: NO Media Info PRIOR Playback, WITH Media Info AFTER Playback.
> 
> If that helps and somebody can provide me the corresponding install.exe i can try out 18.4 as well.
> 
> Update:
> i found 18.4 in the Legacy Download Section, installed it and tried it out with 5 different Iso files (BD and UHD). In ZERO cases Media Info was displayed after playback.
> Based on this i would conclude that the cause of this problem must lie somewhere in the updates from 18.3 to 18.4......can anybody else confirm??

I think the problem is that it initially broke with #16332, but something else was later on changed that makes reverting #16332 NOW, not fix the issue.

**Comment by arnova** [comment] 2021-04-03 06:40
@FernetMenta : Isn't 7ef0c864466b1e156e41c2de8be3f965a7961e41 responsible for introducing this issue?

**Comment by FernetMenta** [comment] 2021-04-03 07:58
@arnova The commit you referenced is from 2017 but @Reemtsman reported 18.3 (June 2019) working. How would you explain this?

**Comment by the-black-eagle** [comment] 2021-04-03 09:40
@FernetMenta In spite of that, would you agree that the commit referenced above removed some code that appears to look up the stream details in a different way for `DVDSTREAM_TYPE_DVD` , demuxerId always being -1 and the stream id is obtained in a different way also rather than using `m_CurrentVideo.id` ?
You know this code better than anyone. Would it be acceptable to use the information held in `m_CurrentVideo.hint` etc to fill in the video and audio info for an iso, it appears to contain everything needed?  I'm unsure how to obtain subtitle info though (and have nothing to test with currently).

**Comment by FernetMenta** [comment] 2021-04-03 10:56
Before suggesting code changes you should try to understand what's going wrong and why. If SelectionStreams wasn't populated with the stream details, VP couldn't play the stream.

**Comment by the-black-eagle** [comment] 2021-04-03 12:00
Fair comment, I am trying to figure out exactly what is wrong.  From what I can see, SelectionStreams contains the following data for the video stream when playing my test iso. `source = 512`, `id = 1`, `demuxerId = -1`.  m_CurrentVideo contains `source = 256`, `id = 0`, `demuxerId = 3`.  So `m_SelectionStreams.TypeIndexOf()` is never going to find a match and the returned streamId is always -1
The older code obtained the stream id via `CDVDInputStreamNavigator()` for DVD's and used m_CurrentVideo/Audio for everything else.  My assumption from this is that m_CurrentVideo.id does not hold the correct stream id when playing dvd related content.  The older code also uses `STREAM_SOURCE_NAV` for the source id, rather than `m_CurrentVideo.source`. I presume this is for a similar reason, i.e. that the details held in `m_CurrentVideo/Audio` are not populated correctly when playing dvd related material.  Is that anywhere near being correct ?  If not, I do not see why that code was originally necessary ?

**Comment by arnova** [comment] 2021-04-03 12:12
> @arnova The commit you referenced is from 2017 but @Reemtsman reported 18.3 (June 2019) working. How would you explain this?

Yes but I'm pretty sure @Reemtsman  is wrong. I tried 18.0 this week on Linux and there it already didn't show any flags for DVD. And that is in line with what I remember: it broke between v17 and v18.0....

**Comment by Reemtsman** [comment] 2021-04-03 12:28
> 
> 
> > ....
> Yes but I'm pretty sure @Reemtsman is wrong. .......

...definitely NOT!
I can provide you some Screenshots or even some short Video to proove my observation.
And just to metion: It was also confirmed by @TeHaX that 18.3 is still working.
See "Media Info from Iso Files" in the Kodi / Video Support Forum. Link below
https://forum.kodi.tv/showthread.php?tid=360927&pid=3027990#pid3027990

**Comment by arnova** [comment] 2021-04-03 13:35
> > > ....
> > > Yes but I'm pretty sure @Reemtsman is wrong. .......
> 
> ...definitely NOT!
> I can provide you some Screenshots or even some short Video to proove my observation.
> And just to metion: It was also confirmed by @TeHaX that 18.3 is still working.
> See "Media Info from Iso Files" in the Kodi / Video Support Forum. Link below
> https://forum.kodi.tv/showthread.php?tid=360927&pid=3027990#pid3027990

Then for your system/plaform it broke with https://github.com/xbmc/xbmc/pull/16332. But apparently something else that was merged way before this already caused "some" (including mine) systems to fail.

**Closed** 2021-04-24 12:06 UTC
Labels: Component: Database, Component: Video, Triage: Confirmed, v18 Leia, v19 Matrix

**Comment by thesimplethingsinc** [comment] 2024-02-26 13:28
> > and the item is scanned in the library.
> 
> That is where the problem is. It is not scanned into the library. User is just browsing movies through file tree.

Was a solution or workaround ever found for this?
