### ISSUE TITLE
Skipping tracks rapidly makes the player stop / Skipping is sluggish

### ISSUE THREAD

**Issue by verybadsoldier** [xbmc/xbmc#16600] opened 2019-09-10 19:36 UTC
### Describe the bug
I like to play audio books from an SMB share so I have many tracks in my playlist. When skipping through them quickly either forwards or backwards then often unexpectedly the player just stops. The playlist gets cleared then. No more tracks can be played.
Also skipping through the tracks generally feels a bit slow and lagging.

This problem did not happen in previous Kodi version. Skipping was always working and very fluent.

Here is a clear and concise description of what the problem is:

## Expected Behavior
I expect being able to skip through audio playlist quickly when pressing 'next' or 'previous' on the remote control.

## Actual Behavior
When skipping quickly backwards or forwards in the playlist makes the player stop and clears the playlist. Also skipping through tracks is generally sluggish.

### To Reproduce
I don't know what exactly triggers it but this is what I do to reproduce it. 100% reproducible for me in a couple of seconds. I can also reproduce it on a second machine.

1.  Start Kodi
2. Navigate to an SMB share the contains directories with lots of mp3s each (~ 60)
3. Right-click a directory and choose "Play"
4. Kodi starts playing the first track
5. Hit "SkipNext" rapidly multiple times to navigate to a later track (let's say track 40 or something)
6. Kodi will stop playing and the playlist gets emptied after a couple of hits

### Debuglog
The debuglog can be found here:
https://pastebin.com/6Y7Gasay
2019-09-10 21:28:59 - Starting to play

Afterwards I am hitting SkipNext multiple times

### Your Environment
Used Operating system:
LibreELEC 9 on a Shuttle XS35GTv2
also reproduced
on a Notebook with Windows 10 64bit and Leia

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

**Comment by KarellenX** [comment] 2019-09-11 01:49
I notice you are using mp3 files and have separate files for each chapter in the book. And I presume you are skipping quickly through chapters as a form of "manual resume" to pick up the book from where you stopped last session.

This seems quite inefficient.

Have a read of this page and try the suggestion of converting your books...

https://kodi.wiki/view/Audiobooks

**Comment by DaVukovic** [comment] 2019-09-11 04:31
If Karellens suggestion gives you similar results, could you also please try the following: 

- get a newer Kodi version. 
For both OSs (Windows and LibreELEC) there have been Kodi 18.4 builds released

- copy the files locally to the machine
depending on where the files are located and if it's some NAS with multiple discs and a RAID in use, it might also be possible that it might take some time to wake sleeping HDDs (wild guess).

Are we generally talking about a wired or a wireless connection?

But I guess this a long known bug. AFAICS, by skipping, Kodi stops the actual playback, tries to open/play the next file, read info from that file (ffmpeg gives an error also the tag reading seems to fetch something 'unrecognized') and then you already hit the next skipping action. IIRC play->stop->play->stop done very!! fast (like when you are skipping), always causes Kodi to crash. 

So it would be somewhat interesting if the behavior is the same while you try to play the same files from a local machine.

**Comment by verybadsoldier** [comment] 2019-09-11 07:30
@KarellenX 
Yes, thank you. I wrote a small plugin that saves the current playing position every couple of seconds so I can resume from that on the next day. The problem is that I often want to switch back a couple of tracks when resuming and the problem happens then usually.

@DaVukovic 
I reproduced the problem on latest Kodi version with files from hard disk. My Windows machine is on Wifi and the Linux one is wired. But I guess it doesn't matter anymore with the locally played mp3s.

This is a log with Kodi 18.4 played locally:
https://pastebin.com/qUp92E2d

> But I guess this is a long known bug. AFAICS, by skipping, Kodi stops the actual playback, tries to open/play the next file, read info from that file (ffmpeg gives an error also the tag reading seems to fetch something 'unrecognized') and then you already hit the next skipping action. IIRC play->stop->play->stop done very!! fast (like when you are skipping), always causes Kodi to crash.

That sounds reasonable. I am using Kodi since XBMP 2.0 and I am pretty sure that something inside Kodi 18 degraded since Kodi 17 in regards to skipping in playlists. As said, the whole skipping behavior feels quite sluggish and slow (even when it works). This stop-bug might really be old but now the chances are quite high to trigger it due to the sluggishness. That's at least my guess which fits to your theory.

I guess the bug should be easily reproducible for others or does it actually only happen for me? It's really just loading a playlist and skipping in it rapidly.

**Comment by DaveTBlake** [comment] 2019-09-11 18:04
>I guess the bug should be easily reproducible for others or does it actually only happen for me? It's really just loading a playlist and skipping in it rapidly.

Sorry no I can't reproduce.  There is a slowness when swapping to and from the current playlist screen (if you have enough items you will even get a dialog box), but nothing with skipping.

Are the items you are playing in the music library? Does this happen with music not just audio books? - I know mp3 files but maybe something odd in the metadata format??

**Comment by verybadsoldier** [comment] 2019-09-12 07:31
Hm, this is strange, I really hoped it would be easily reproducible for others.

I tested it again on a third machine (Win10) with a freshly installed Kodi 18.04 (no modifications/addons whatsoever) and it happened instantly.

I used another set of mp3s I downloaded here (royalty free):
http://freemusicarchive.org/genre/Soundtrack/

I uploaded the exact set I used here:
https://drive.google.com/open?id=1Q6fxuZv6sqqKWdh1-nVdVcfJrDgfgC4Z

What I did is (basically as before):
1. Installed Kodi freshly
2. Added `d:\mp3` as a source without adding it to the library
3. Played the folder
4. Rapidly skipped forward

What happened:

- The error appeared and the playing stopped before reaching the end of the playlist
- Usually when reaching the end of the playlist there is a popup saying "No more items to play. Reached end of playlist" (or similar). In this case playing stops without any notification
- Skipping was often slow and I sometimes got the dialog box (like hourglass) you mentioned.

Please find the debug log here:
https://pastebin.com/jrMWju9e

**Comment by enen92** [comment] 2024-02-14 13:55
I cannot reproduce this on omega nightlies even if hoding the key down, it just skips instantaneously.
Since this is reported for Leia which is now unsuported I'll just close it as obsolete.
Please let us know if you manage to reproduce the issue in the current nightlies.

**Closed by enen92** 2024-02-14 13:55 UTC
Labels: Component: Music, Triage: Confirmed
