### ISSUE TITLE
Onscreen keyboard has delay

### ISSUE THREAD

**Issue by GavinDarkglider** [xbmc/xbmc#14891] opened 2018-11-16 19:26 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

If using the Onscreen keyboard with a joystick, when you get to a letter it lights up, but if you select it to fast, it submits the last letter you were on to the string in the text box. if you wait a second or 2 on the letter before selecting it, it prints the right letter. This makes typing in passwords and stuff with a joystick much slower, as you cant actually see what is in the text box.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

If the letter is lit up when I select it I expect that to be the letter that gets appended to the string in the text box, without waiting to select it.

## Actual Behavior

the previous letter is being put in the box, if I dont wait to select the current letter.

## Possible Fix

Update which letter is going to get appended to the string, before the visual animation on the onscreen keyboard happens. This way when the letter is selectable, the loop has already updated the which character you are selecting.

### To Reproduce

1. use on screen keyboard with a joystick, and select letters as you are passing on them
2.
3.

### Debuglog

The debuglog can be found here:
Nothing in the log, as this doesnt cause crashes

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ x] Linux arm32 on aarch64 kernel
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:Gentoo Linux armhf on AARCH64 Kernel on Nintendo Switch
 - Kodi version: latest git version

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by MartijnKaijser** [comment] 2018-11-16 21:57
Try again on an actual working or supported platform and confirm or we will close this as invalid cause switch is not a platform we support

**Comment by GavinDarkglider** [comment] 2018-11-17 02:45
I have to ask how linux arm is not a supported platform? It compiles flawlessly, and everything works perfectly, except for this one small bug. Since I dont have another arm linux device, that is officailly supported, available to me at the moment to test this on, and I cant connect the controllers to the computer, I am not sure how you propose I do this.

**Comment by pkerling** [comment] 2018-11-17 09:17
> I have to ask how linux arm is not a supported platform?

A processor alone hardly defines a platform.

The reality is that no one on the team is actively running Kodi on the Switch (hence: unsupported platform), so we have no way of knowing whether this problem is caused by Kodi or the way Linux works there. Be prepared to reproduce this in whatever way you find comfortable on a supported platform if you want someone to seriously look at this. If you can't reproduce on a regular PC with any input method (be that mouse or gamepad or whatever), it is very likely to be a Switch-specific controller issue.

**Comment by Razzeee** [comment] 2019-01-09 15:35
@GavinDarkglider did you find anything?

**Comment by GavinDarkglider** [comment] 2019-01-12 00:49
I honestly havnt had time to test it on another platform, holidays and such. lol. I will try to do that this week some time.

**Comment by DaVukovic** [comment] 2019-01-12 01:03
Ok, we all know how limited time can be. Please be aware that we will close this issue in 3 days if you haven't reported anything.

**Closed** 2022-04-19 17:14 UTC
Labels: Component: Input, Issue Cleanup: Obsolete
