### ISSUE TITLE
Kodi 20 : Only 15 video addons listed 

### ISSUE THREAD

**Issue by karlo2105** [xbmc/xbmc#23641] opened 2023-08-20 14:18 UTC
### Describe the bug
Since i upgraded from Kodi 19.5 to Kodi 20.2, i noticed only 15 video addons are listed out of 17 though all work with Kodi 20.2. 

## Expected Behavior
In previous Kodi versions, all installed video addons have been displayed in addons tab in my case 17.

## Actual Behavior

I have 17 video addons installed but since Kodi 20.2 upgrade, only 15 are shown. When i open unlisted video addon from my addons folder, it shows in addons tab but last video addon in the extreme right row disappears which makes only 15 addons are shown instead of all installed. 

## Possible Fix

It would be fine if al installed video addons could be shown as before Kodi 20.

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 10
 - Kodi version: Kodi 20.2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment] 2023-08-20 15:12
What exactly is the „addons tab“? Maybe you can post a screen shot?

**Comment by karlo2105** [comment] 2023-08-20 16:40
In main menu items on the left side in section "Add-ons", it lists all video add-ons installed. However, since Kodi 20 upgrade, 15 video add-ons are shown only but i have 17 installed. Any solution to show all add-ons as in Kodi 19?
You can see below main menu items. 
![2023_08_20 18_34 Office Lens](https://github.com/xbmc/xbmc/assets/5579457/45d95f2f-1637-47e0-85cc-1f3a049804a1)

**Comment by ksooo** [comment] 2023-08-26 22:21
@karlo2105 I can reproduce the issue.

**Comment by ksooo** [comment] 2023-08-26 22:36
@karlo2105 can you proof that before Nexus (Kodi 20) more than 15 items were displayed? Looking at the code of the skin for Matrix (Kodi 19), 15 seems to be the limit since 2016...

**Comment by karlo2105** [comment] 2023-08-26 22:52
I shall try it with Kodi 19 because i have 18 addons installed right now and i am sure every one was displayed with 19.4 and prior. I wonder why is it limited to 15 addons only. When major version is released, i always wait for 6 to 9 months to upgrade.

**Comment by ksooo** [comment] 2023-08-27 07:13
> i am sure every one was displayed with 19.4 and prior.

 To be honest, from what I see in the code this seems not to be possible.

> I wonder why is it limited to 15 addons only.

No idea, it was the designer of the skin who decided this.

**Comment by karlo2105** [comment] 2023-09-07 14:01
@ksooo 
I just installed Kodi 19.3 on Windows. I restored data from backed up Kodi and I can confirm 15 addons are listed only. You were right it was there but i didn't pay much attention probably because i never had more than 15 addons installed before Kodi 20.  Thanks for clarification.

**Comment by ksooo** [comment] 2023-09-07 15:40
So, not actually an issue. Works as designed, no regression. Closing the issue.

Bit you might be interested in a new feature of Kodi Omega, that relates to the problem you raise here: https://github.com/xbmc/xbmc/pull/23682

**Comment by ksooo** [comment] 2023-09-07 15:41
So, not actually an issue. Works as designed, no regression. Closing the issue.

Bit you might be interested in a new feature of Kodi Omega, that relates to the problem you raise here: https://github.com/xbmc/xbmc/pull/23682

**Closed** 2023-09-07 15:42 UTC
