### ISSUE TITLE
Kodi Picture Slideshow can't be paused with a remote (Android TV)

### ISSUE THREAD

**Issue by Esokrates** [xbmc/xbmc#18328] opened 2020-08-25 20:07 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

On my Android TV (Sony Bravia) when starting a Picture Slideshow pausing the slideshow using the pause button does not work. Only way to halt the slideshow is to use a number bigger than 0 in order to zoom into the picture which is a quite ugly way to pause a slideshow.
On my Linux Boxes pressing the mouse button or spacebar pauses the slideshow, I expect similar functionality from my remote on my TV.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

There should be an option to pause a slideshow, for example to tell something about the images which might take longer.

## Actual Behavior

Pause button and middle button presses are ignored, pressing 0 pauses the slideshow animation just for a fractal of a second.

## Possible Fix

I see four possibilities:
1. Pressing "down" pauses and pressing "down" again resumes the slideshow, or some other combination between "up" and "down"
2. Middle click button pauses the slideshow and clicking again resumes the slideshow (right now middle click rotates the current picture, so this would break an existing mapping)
3. Pressing 0 pauses the slideshow and pressing 0 again resumes the slideshow
4. Pause button pauses the slideshow and clicking play continues the slideshow (this would maybe break pausing music running in the background)

Edit: My favorite approach would be to make the middle button pause/resume the slideshow and remap up/down to rotate the picture when not in zoom mode. Anyhow I consider pausing a slideshow more fundamental than rotating a picture during the slideshow.

### To Reproduce

1. Go to Pictures
2. Go to the Sidebar
3. Start Slideshow

### Debuglog

Debug Log can be found here: https://paste.kodi.tv/iberaqajuf

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 8.0
 - Kodi version: 18.8

**Comment by Esokrates** [comment] 2020-08-25 20:41
@ronie Will you remove the ignored rules label once I attach a debug log?

**Comment by DaVukovic** [comment] 2020-08-25 21:15
A debuglog is very much relevant in that case

Imagine we can not reproduce and close this issue because we say "not reproducible". Then you might ask, what and how we test it. Then we will ask, what and how YOU tested it, as we don't have the problem.....many questions, many explanations which all can be answered by a single debuglog. 

And now think once again if a log is relevant or not ;)

**Comment by Esokrates** [comment] 2020-08-25 21:17
@DaVukovic Agreed, I'll come back to it once I have access to the TV again. Would be great if someone with a respective device could have a look in the meantime.

**Comment by Esokrates** [comment] 2020-08-26 09:33
@ronie @DaVukovic I edited the report, debug log is now attached. Furthermore I updated the description on the possible fix: Right now the "up" and "down" buttons are not reserved for the slideshow, so those could be made to pause and resume the slideshow if the picture is not set to manually zoomed in. This has the advantage that it should work on any platform, since "up" and "down" are present on any remote.

**Comment by DaVukovic** [comment] 2020-08-26 17:32
>2020-08-26 11:22:45.496 T:23267  NOTICE: Disabled debug logging due to GUI setting. Level 0.

Not a debuglog

**Comment by Esokrates** [comment] 2020-08-26 21:28
@DaVukovic Updated the link once again, should be correct now, thanks for the feedback.

**Comment by ronie** [comment] 2020-08-26 22:20
thanx, the is the relevant part in the log:
`2020-08-26 23:23:20.767 T:19854   DEBUG: HandleKey: play_pause (0xf0bd) pressed, action is PlayPause`

so the remote button you are pressing isn't sending a Pause command, but a PlayPause command.

looking at our code, the Slideshow handles the Play and Pause actions, but not the PlayPause action:
https://github.com/xbmc/xbmc/blob/5af8467a005995be8cba9136538ca80ad921c361/xbmc/pictures/GUIWindowSlideShow.cpp#L822-L856

i don't think that will be too hard to fix... i'll have a look at it

**Comment by ronie** [comment] 2020-08-27 01:19
fix pending: https://github.com/xbmc/xbmc/pull/18331

**Comment by bossanova808** [comment] 2020-08-27 05:53
Just as a workaround before the fix comes in - I've always used (globally) - the ok button (centre of the arrows on most remotes) to handle play pause (everywhere)...it's very intuitive and the way many other media playing systems to do it...

So in `keymap.xml` I have:

```
    <FullscreenVideo>
        <remote>
            <Select>Pause</Select>
        </remote>
    </FullscreenVideo>
```

To make this work in the Slideshow, I just added the same thing to that keymap:

```
    <Slideshow>
        <remote>
            <Select>Pause</Select>
        </remote>
    </Slideshow>
```

...that has worked for years, is very logical and consistent between video/pictures/music etc. (and I've always personally thought should be the Kodi default TBH!)

**Closed** 2020-09-05 22:47 UTC
Labels: Platform: Android, Triage: Confirmed, Triage: Has proposed fix

**Comment by Esokrates** [comment] 2020-09-06 07:50
@ronie Thanks very much, could this be backported to the next 18.x release?

**Comment by DaVukovic** [comment] 2020-09-06 08:33
We won't release another Kodi 18 version. If you want that fix, either use Kodi 19 or compile Kodi 18 yourself with that patch applied.

Sorry
