### ISSUE TITLE
stereoscopic not working properly

### ISSUE THREAD

**Issue by ZiminN** [xbmc/xbmc#15561] opened 2019-02-20 09:47 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:
1) The menu for selecting the viewing mode appears only when playing the first file, when viewing others it does not appear (until the reboot). (option "Playback mode of stereoscopic 3d videos" - "Ask me")
2) Stereoscopic mode does not turn off when playback is stopped. (option "Disable stereoskopic 3d mode when playback ended" - "on")

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/amolamelin.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
18.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment] 2019-02-20 11:28
You haven't followed our  issue template where we also ask for a debuglog.

Please submit a full debuglog from Kodi start. I'll mark this issue as invalid for the time being

Thanks in advance.

**Comment by ZiminN** [comment] 2019-02-20 12:06
add

**Comment by ZiminN** [comment] 2019-02-20 12:11
> You haven't followed our issue template where we also ask for a debuglog.
> 
> Please submit a full debuglog from Kodi start. I'll mark this issue as invalid for the time being
> 
> Thanks in advance.

add

**Comment by DaVukovic** [comment] 2019-02-20 12:19
> 14:37:35.450 T:140607594170496  NOTICE: GL_VENDOR = VMware, Inc.

Running LibreELEC in a VM is not officially supported. Please provide a log with an officially supported Kodi platform or head over to the LibreELEC forums for any further discussion.

**Comment by ZiminN** [comment] 2019-02-20 12:23
> > 14:37:35.450 T:140607594170496  NOTICE: GL_VENDOR = VMware, Inc.
> 
> Running LibreELEC in a VM is not officially supported. Please provide a log with an officially supported Kodi platform or head over to the LibreELEC forums for any further discussion.

Windows on the VM fit? Same behavior.

**Comment by DaVukovic** [comment] 2019-02-20 12:25
Can't you use Kodi natively installed on the OS and avoid using a VM?

**Comment by ZiminN** [comment] 2019-02-20 12:27
> Разве вы не можете использовать Kodi, изначально установленный в ОС, и не использовать виртуальную машину?

Unfortunately there is no free PC

**Comment by ZiminN** [comment] 2019-02-20 12:28
> Can't you use Kodi natively installed on the OS and avoid using a VM?

Unfortunately there is no free PC

**Comment by killerhaehnchen** [comment] 2019-02-20 19:19
Reproduced this issue on a (real) Windows 7 64bit PC without using a VM. Debuglog can be found [here](https://paste.kodi.tv/cayeyigoga.kodi).

I played back this [3D sample file](https://thedigitaltheater.wetransfer.com/downloads/5f67d777b663a9aeba45ae5db939ffbd20190115005442/cc3bff). In debuglog it will be mentioned as `Alita_Battle_Angel_INTL_TLR_35FL_3D_SBS_1080p_DTS-HD_MA_51-thedigitaltheater.mkv`. Other 3D video files have also shown the above described behavior.

Additonally I would like to add to the bug description at item 2.):

_Afterwards, when playback is started again (same 3D file or different 3D file does not matter) stereoscopic mode **does** turn off._

It seems that stereoscopic mode toggles on start of playback, but not on stop of playback.
If I can be of any help by providing additional debuglogs etc., please let me know.

**Comment by DaVukovic** [comment] 2019-02-21 08:31
@killerhaehnchen 

unfortunately you have banned add-ons installed. We appreciate the effort and the help, but could you please try to reproduce that issue with a vanilla Kodi, please (or at least without those banned add-ons involved)?

Thanks in advance

**Comment by killerhaehnchen** [comment] 2019-02-21 17:23
@DaVukovic 
I could also reproduce the issue with a vanilla Kodi (v18.1), see the new [debuglog](https://paste.kodi.tv/zuhewiqudi.kodi). Please let me know, if logging with more details enabled is helpful.

**Comment by DaVukovic** [comment] 2019-02-21 17:25
Thanks much for your effort. We talked internally about that and it seems to be a known issue: 

https://github.com/xbmc/xbmc/pull/13878

Bunch of dicussions about it. So we'll leave that open. Thanks for your report. Much appreciated.

**Comment by killerhaehnchen** [comment] 2019-02-21 17:39
Glad I could help, but the real effort is made by Team Kodi. Wish I was more into C++ and this project to contribute a bit.

**Comment by Memphiz** [comment] 2019-04-06 17:46
Will be fixed in next nightly and leia 18.2

**Closed by Memphiz** 2019-04-06 17:46 UTC
