### ISSUE TITLE
Kodi 19 RC1 cannot display jpg pictures, taken by Samsung Galaxy S9+ smartphone

### ISSUE THREAD

**Issue by guenniguenzelsen** [xbmc/xbmc#19103] opened 2021-01-22 17:21 UTC
### Describe the bug
Kodi 19 RC1 cannot display jpg pictures, taken with a Samsung Galaxy S9+ camera
Kodi 18.x can show these pictures without any issues.

## Expected Behavior
Kodi 19 shall have the same compatibility for picture formats like the previous version.

## Actual Behavior
By opening one of these pictures, the screen turns black.

## Possible Fix
Implement the same compatibility, the prvious version has.

### To Reproduce

1. Use my example jpg pics, attached to this ticket
2. Try to show/display one of these pics in Kodi 19 RC1

### Debuglog

Debuglog attached to this ticket

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ x] Linux
 - [ ] OSX
 - [ x] Windows
 - [ ] Windows UWP

 - Operating system version/name: 1: Windows 10 64bit / 2: Libreelec 9.80 nightly / 3: FireOS
 - Kodi version: 19 RC1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by guenniguenzelsen** [comment] 2021-01-22 17:33
[kodi2.log](https://github.com/xbmc/xbmc/files/5857516/kodi2.log)

[Testbilder.zip](https://github.com/xbmc/xbmc/files/5857519/Testbilder.zip)

**Comment by fritsch** [comment] 2021-01-22 17:45
Upstream bug, see: https://trac.ffmpeg.org/ticket/8967

**Comment by fritsch** [comment] 2021-01-22 17:46
Duplicate of: https://github.com/xbmc/xbmc/issues/18744

**Comment by fritsch** [comment] 2021-01-24 08:19
Can you try with this: https://github.com/xbmc/xbmc/pull/19113 included? I can build you an android apk if you need one.

**Comment by fritsch** [comment] 2021-01-24 08:33
Please try this: http://mirrors.kodi.tv/test-builds/android/arm/kodi-20210124-034edd10-image2-armeabi-v7a.apk and report back.

**Comment by guenniguenzelsen** [comment] 2021-01-24 09:00
The issue is solved with your version attached.
Verified on my Fire Tv Stick.
Do you need more input from my side? Any log or other testing for potential side-effects?

**Comment by fritsch** [comment] 2021-01-24 09:21
Thanks for your feedback.

Let me ask differently: Did you realize any sideeffects? Something unusual?

**Comment by guenniguenzelsen** [comment] 2021-01-24 09:41
I cannot see anything unusual or any side-effect.
All picture functions are back to normal.
Picture Slideshow Screensaver also working again with this fix.
Thanks for taking action on that issue!
Would be gerat to see this implemented into upcoming nightly versions/final Kodi.

**Closed** 2021-01-25 18:01 UTC
