### ISSUE TITLE
WebOS: Black screen after switching to guide and pressing back button

### ISSUE THREAD

**Issue by alexhass** [xbmc/xbmc#25087] opened 2024-04-28 22:02 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

Black screen after switching to guide and pressing back button.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The previous video output should resume automatically.

## Actual Behavior

i see a black screen only.

### To Reproduce

1. watch TV in Kodi (tvheadend frontend)
2. press the guid button (you try to open the kodi guide, but the LG sat guide will start)
3. press the back button on lg remote.
4. Switches back to kodi, but I only see a black screen
5. workaround - Press stop and play and the video resumes.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP
 - [x] Webos

 - Operating system version/name: webos 8.3.0
 - Kodi version: 21.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by sundermann** [comment] 2024-04-28 22:11
Kind of a duplicate of #25084

**Closed by sundermann** 2024-04-28 22:11 UTC
Labels: Triage: Needed

**Comment by alexhass** [comment] 2024-04-29 06:48
This is not a duplicate of https://github.com/xbmc/xbmc/issues/25084

**Comment by alexhass** [comment] 2024-07-20 21:34
The issue is not fixed in latest nightly. Any chance this goes in?
