### ISSUE TITLE
jsonrpc Player.SetSubtitle fails with -32100/Failed to execute method. when actual playerid is 0

### ISSUE THREAD

**Issue by jplusc** [xbmc/xbmc#15700] opened 2019-03-08 04:45 UTC
### Describe the bug
 
When a json request such as this is issued:
```
{"jsonrpc": "2.0",
 "method": "Player.SetSubtitle",
 "params": {
           "playerid": 0,
           "enable": false,
           "subtitle": "off"
           },
  "id": 57 }
```
or
```
{"jsonrpc": "2.0",
 "method": "Player.SetSubtitle",
 "params": {
           "playerid": 0,
           "enable": true,
           "subtitle": "on"
           },
  "id": 56 }
```
a `-32100/Failed to execute method` is returned instead of  turning on or off the subtitles.

if the playerid is > 0 then the call works fine.

**it is important to note, that the playerid of 0 is the actual playerid** as reported by `Player.GetActivePlayers`.

it is important to note, that calls such as `Player.Seek` and `Player.PlayPause` work as expected when playerid=0

it may be important to note, that forcing playerid=1 or some other value while `Player.GetActivePlayers` reports it as 0 will NOT work.

it may be important to note, that my playerid only seems to be 0 when launching the video from the command line.  when loading the video with `Player.Open` the playerid will be 1 and the  'Player.SetSubtitle' call works as expected.

## Expected Behavior

subs should change as the RPC instructed with the correct playerid, or the playerid should not be 0 so that the RPC call can work.

## Actual Behavior

 -32100/Failed to execute method.

## Possible Fix

was digging thru `/xbmc/interfaces/json-rpc/PlayerOperations.cpp` and the section for `Player.SetSubtitle` explicitly errors out if the switch statement is not video.

in cases where the behavior is correct, such as `Player.Seek` and `Player.PlayPause` both 
```
case Video:
case Audio:
```
falls thru to the same code.

we could either hide the problem by letting both players fall thru the SetSubtitle code, or find the cause of why playerid is being set as 0.

### To Reproduce
run the above shown api call when a video is playing.
when ran when the video is started with the Player.Open command, the playerid will be >0 and all will work well.
when ran when the video is launched from the command line, the playerid will be =0 and will fail.

### Debuglog
no crash occurs.  only a failed api call

 

 

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
win 6.1.7601 (win 7 pro sp1 64bit)
 - Kodi version:
tested on 17.6 and 18.1 (32 and 64 bit) (release versions)

**Comment by enen92** [comment] 2019-03-16 19:49
@jplusc how are you launching videos from the command line? Using event server clients such as kodi-send?

**Comment by enen92** [comment] 2019-03-17 14:12
A few infos regarding this issue if someone wants to look into it. This happens because `AppParamParser` creates a `PLAYLIST_MUSIC` (id = 0) by default:

https://github.com/xbmc/xbmc/blob/26ba8488fc3ad428cf9c7ce894d42061b06836dd/xbmc/XBApplicationEx.cpp#L51

Hence when `Player.GetActivePlayers` gets called it fallbacks to the playlist id despite the fact the active player is video:

https://github.com/xbmc/xbmc/blob/1c60cbda7c0986a5d6277a7e0aa7d569e87a4b61/xbmc/interfaces/json-rpc/PlayerOperations.cpp#L56

https://github.com/xbmc/xbmc/blob/1c60cbda7c0986a5d6277a7e0aa7d569e87a4b61/xbmc/interfaces/json-rpc/PlayerOperations.cpp#L1123

I tried changed the `GetPlaylist` call to `GetPlayer` but even there if the playlistid and the playerid do not match player is returned as unknown:

https://github.com/xbmc/xbmc/blob/master/xbmc/interfaces/json-rpc/PlayerOperations.cpp#L1238

All this looks like the expected behaviour and was introduced in 2015 in https://github.com/xbmc/xbmc/commit/200e60df99ad9afa25bb7be8acddcaaebbbe617b#diff-9c2a40e0c0359d72671c8181d11db75d .
Unfortunately the implementation is hard to grasp and looks too fragile. As a result I won't event try to fix it.

**Comment by jplusc** [comment] 2019-03-25 14:52
Thanks for your help in this matter.   Looks like since this problem has been around since 2015 and hasn't really been brought to light until now, it's impact to users must be pretty low...

Probably not worth fixing until, for some other reason, XBApplicationEx.cpp/PlayerOperations.cpp needs to be revisited.

In the mean time, I am going to change my scripts from launching kodi at the command line with the media file, to launcing kodi with no parameters,   waiting for it to fully load, then issuing a json rpc Player.Open command with the media file.

my only question, is finding a good way to wait for kodi to fully load,  i guess I could keep querying the json rpc with a JSONRPC.Version for an OK response, then issue the Player.Open

**Comment by enen92** [comment] 2019-03-25 14:54
have you looked into autoexec.py?

**Comment by jplusc** [comment] 2019-03-25 15:13
> have you looked into autoexec.py? Or simply service addons?

I have not, but will now.  thanks again for all your help.

**Comment by malard** [comment] 2024-01-28 13:10
while I acknowledge this is a bug, its fairly edge case in that it only happens during a specific scenario and with additional jsonrpc querying you can work round this. So closing as its not something any of the team is committing effort to. As always, happy to accept a PR

**Closed by malard** 2024-01-28 13:10 UTC
Labels: v18 Leia, Triage: Confirmed, Component: JSON-RPC
