### ISSUE TITLE
TV-Show folders not working on Milhouse RPI2 

### ISSUE THREAD

**Issue by Timmiotool** [xbmc/xbmc#15217] opened 2019-01-08 06:07 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

same as #15210:
When selecting a TV Show icon from the "In progress TV shows" instead of being presented with a list of episodes I'm taken to the screen with a list of sources e.g.
Movies
TV Shows
Files
Playlists
Video add-ons

Also if I click into the TV Shows menu on the left I get the list of TV Shows but if I select a show the busy spinner displays for a second then nothing happens. No drill-down into the show and no error message.

If I navigate to the Videos menu item I can drill down into the folders and I can also play shows from the "Recently added episodes" list

-----------------------------------------------
more Information:

this is happend since:

0104, 04-Jan-2019: RPi / RPi2 -- Release post ([database] Make season_view and tvshow_view SQL ANSI92-compliant; libnfs: nfsv3: skip commit if the file has not changed; pvr.vuplus: move nlohmann-json to depends)
0103, 03-Jan-2019: RPi / RPi2 -- Release post (Replace CREATE TABLE [] AS SELECT [])

with Video Database 114.... when i go back to an older Build with Video Database 113 evrythings OK !

--------------------------------------------

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. update Kodi with existing Data to 0104, 04-Jan-2019: RPi / RPi2 -- Release post ([database] Make season_view and tvshow_view SQL ANSI92-compliant; libnfs: nfsv3: skip commit if the file has not changed; pvr.vuplus: move nlohmann-json to depends)
2. Go to TV -Shows List pick up a Show an go to the Seasons List...nothing happend it only shows
list of sources e.g.
Movies
TV Shows
Files
Playlists
Video add-ons

### Debuglog

The debuglog can be found here:

https://paste.ubuntu.com/p/H3nPS45kh8/

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
0104, 04-Jan-2019: RPi / RPi2 -- Release post ([database] Make season_view and tvshow_view SQL ANSI92-compliant; libnfs: nfsv3: skip commit if the file has not changed; pvr.vuplus: move nlohmann-json to depends)

with MySQL Database.

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment] 2019-01-08 06:41
As you already found the other one (and for the reason it's kind of duplicate, this one might get closed soon) you might also have noticed, that I requested a full debuglog showing this behaviour. 

As you also got it managed to ignore our issue template, I'll mark this as invalid as well. If you will provide a full debuglog within the next 3 days, we probably consider removing the invalid label and also might consider re-opening this issue if it gets closed.

**Comment by Timmiotool** [comment] 2019-01-08 08:40
heres the Log : https://paste.ubuntu.com/p/9nWsZ6HSFr/


you can see the problem at:

09:21:58.594 T:9380   ERROR: SQL: [xbmc_video114] Undefined MySQL error: Code (3)
                                            Query: SELECT * FROM season_view  WHERE season_view.idShow = 139
09:21:58.597 T:9380   ERROR: CVideoDatabase::GetSeasonsByWhere failed

i think.

**Comment by MilhouseVH** [comment] 2019-01-08 09:02
```
09:19:25.651 T:9380  NOTICE: Log level changed to "LOG_LEVEL_NORMAL"
```
You enabled debug logging some time after the system had booted/Kodi started, so your log is missing useful information such as your version of MySQL server.

Enable debug logging, reboot the system (or restart Kodi), reproduce the problem, _then_ upload the complete debug log and post the link.

I've tested MySQL 5.5.21 with MyVideos114 and am not seeing an issue.

I'm not getting any google hits on error code 3, but I am seeing results which might suggest your server is out of space, so check your server logs too.

**Comment by pkerling** [comment] 2019-01-08 09:08
Also please connect to the MySQL server with some tool, enter the query `SELECT * FROM season_view LIMIT 0,1` and paste the output please.

**Comment by Timmiotool** [comment] 2019-01-08 12:19
I can view the Table season_view in xbmc_video113 without any Problems. 
In xbmc_video114 i can't view the Table got Error 3 can't write temp file - Server is good i think the Problem is the View himself overflow or whatever....

I do the following: export the Table season_view from xbmc_video113 delete in xbmc_video114 and then import the table from xbmc_video113 in xbmc_video114.

After these the everythings in Kodi ist good, TV-Show Seasons now present ...

I don't know  what is going wrong but it seems thatthe View season_view Table in xbmc_video114 is not good. When I Upgrade from xbmc_video113 to xbmc_video114 once again the same error. Problem with If i use a Clean Database xbmc_video114 and add a TV-Show it worked without any Problem semms ist a Problem with the migration from the xbmc_video113 to xbmc_video114.

![image](https://user-images.githubusercontent.com/45381363/50829846-1b68c400-1346-11e9-837b-18c263fca0c3.png)

I use on a QNap TS-420

![image](https://user-images.githubusercontent.com/45381363/50830196-5f0ffd80-1347-11e9-9c2c-b6b84479f617.png)

**Comment by pkerling** [comment] 2019-01-08 13:53
Please post a screenshot of browsing `season_view` in PMA with the view as it was created on upgrade so we can see the actual error

**Comment by Timmiotool** [comment] 2019-01-08 14:06
the view from the upgrade does not work. The SQL Server crashes (only this view have the Problem).

![image](https://user-images.githubusercontent.com/45381363/50835360-cb462d80-1356-11e9-91e4-671079988522.png)

**Comment by Timmiotool** [comment] 2019-01-08 14:07
...and Yes my Server have enought Space and all Rights ;-)

**Comment by pkerling** [comment] 2019-01-08 14:10
Can you try with the mysql console client?

**Comment by Timmiotool** [comment] 2019-01-08 14:41
Sorry, i have no Console Client on the Nas :-(

What i found is this:

**https://github.com/xbmc/xbmc/issues/15172**

I think after the Changes heres now a Problem with (perhaps older MYSQL Server ?) ...

**Comment by pkerling** [comment] 2019-01-08 14:46
> Sorry, i have no Console Client on the Nas :-(

You can use the client from any other machine, doesn't have to run on the NAS - just like kodi connects to your MySQL server

**Comment by MilhouseVH** [comment] 2019-01-08 15:00
MySQL uses /tmp for scratch files (sorting, grouping etc.) so either your database (tv shows) is quite large, or your /tmp partition is very small, and the updated query is now creating a sufficiently large scratch file that it blows up your /tmp partition.

https://dev.mysql.com/doc/refman/8.0/en/temporary-files.html

How large is your /tmp partition? How many tv shows and seasons do you have?

What engine are you using for your database, MyISAM or InnoDB? You might be better off using InnoDB.

Alternatively, can you increase the size of the `/tmp` partition, or can you configure `mysqld` so that it uses a different/larger partition for scratch files?

**Comment by pkerling** [comment] 2019-01-09 08:39
Non-reproducible problem with DB setup. Closing.

**Closed by pkerling** 2019-01-09 08:39 UTC
Labels: NOT A BUG, v18 Leia

**Comment by MilhouseVH** [comment] 2019-01-09 09:13
> On qnap you have only the possibility to switch from MySQL 5.1.73 to Maria db 5.5.44. I do this.
Now the Problems are gone -everythings ok.

It could have been a peculiarity of your (very old) MySQL 5.1.x. I'm using MySQL 5.5.21 without a problem and I consider that version to be ancient (it's on my list of things to upgrade, when I get the time...). Hopefully we don't have too many MySQL 5.1.x users... :)

**Comment by kib** [comment] 2019-01-09 17:30
https://forum.qnap.com/viewtopic.php?t=113824

QNAP uses a /tmp volume which is only 64MB - are you sure you checked this correctly ?

**Comment by MartijnKaijser** [comment] 2019-01-10 05:55
Here's another report
https://forum.kodi.tv/showthread.php?tid=331408&pid=2807262#pid2807262

**Comment by pkerling** [comment] 2019-01-10 08:41
@MartijnKaijser that is SQLite and happening since April, so different issue

**Comment by Timmiotool** [comment] 2019-01-10 12:46
@KIB: checked this by use : sudo mount -t tmpfs -o remount,size=200m,mode=1777 tmp /tmp bevor i update to maria db...

then:

[~] # df -h
Filesystem                Size      Used Available Use% Mounted on
/dev/ram0                32.9M     16.7M     16.2M  51% /
tmpfs                    200.0M    184.0k     199.8M   0% /tmp
/dev/sda4               371.0M    358.6M     12.4M  97% /mnt/ext
/dev/md9                509.5M    141.2M    368.3M  28% /mnt/HDA_ROOT
/dev/md0                  8.1T      7.4T    762.2G  91% /share/MD0_DATA
tmpfs                    16.0M     48.0k     16.0M   0% /share/MD0_DATA/.samba/lock/msg.lock
tmpfs                    16.0M         0     16.0M   0% /mnt/ext/opt/samba/private/msg.sock
tmpfs                     1.0M         0      1.0M   0% /mnt/rf/nd
tmpfs                    16.0M         0     16.0M   0% /share/NFSv=4
/dev/md0                  8.1T      7.4T    762.2G  91% /share/NFSv=4/Public

same result - cant write tmp file.
Dont know i think the mySQL Server in the QNAP QTS Fimware is to old and to shitty ... 
As an all in one solution it was enough for kodi and ran without any problems the last years...

Solution is install Maria (manuell, old Models like TS-420 not official supp.) Works fine on my TS-420.
Link: http://download.qnap.com/QPKG/QMariaDB_5.5.44.002_arm-kw.zip

**Comment by Timmiotool** [comment] 2019-01-10 17:14
What i can say now is: 
the Problem is not the old MYSQL its the QNAP QTS himself. At least i mount the temp Folder from NAS ROM to a Share on my RAID Harddrive Space.

Then everything works perfekt looks like the temp Space is indeed to small. The wired thing is when I look on the temp space in the Moment when SELECT * FROM season_view ....  The maximal temp size is only 9MB also 69 MB free temp Space from QNAP in original should be enough...

Maybe the sizes do not match the physical size... anyway, solved. Temp away from ROM Space solved the Problem.

edit: /etc/my.cnf
tmpdir	= /tmp to /share/*yourshareonRaid*

Sorry, my shitty Nas make the Mistake and not Kodi ;-)
