### ISSUE TITLE
Regression 20.0a3-Nexus has issue #19883 (Turkish I) problem

### ISSUE THREAD

**Issue by fbacher** [xbmc/xbmc#21976] opened 2022-10-04 13:16 UTC
### Describe the bug See Issue 19883. If LANG=tr_TR then Kodi UI is non-functional
Here is a clear and concise description of what the problem is:

Examining the code shows that the changes made for 19883 are not present in Nexus. See LangInfo.cpp:SetCurrentRegion
There should be the lines:
  ```
// Check if locale is affected by "Turkish I"
  // See https://github.com/xbmc/xbmc/issues/19883 for details
  if (std::tolower('i') != std::tolower('I'))
```

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

On Ubuntu, install Kodi and the Turkish locale (Ubuntu language-pack-tr)
Start Kodi:
LANG=tr_TR /usr/bin/kodi
You might also need to set Kodi's language to Turkish.
Kodi should have a usable UI

## Actual Behavior

Kodi has a nearly blank screen and is not usable

## Possible Fix

One solution is to repeat the incomplete, problematic fix for 19883. The ideal fix is to use ICU, but that is not going to happen for this release. I'm working on a workaround which should be superior to the one in 19883. This fix creates StringUtils::FoldCase which is not a true FoldCase, but is a wrapper around ToLower but using the locale en_GB.UTF8. This forces ToLower to obey the rules of English instead of the current locale. Using the current locale, when Turkish, causes the problem, due to the odd treatment of the various forms of the letter 'I'. 

ToLower with English locale is a good approximation for Kodi's use of ToLower (without a locale specified) of 'normalizing' keywords, etc.. The keywords are at least nearly always ASCII. It is possible that an addon or other piece of code uses non-ASCII as a setting id, or other id, but not highly likely and generally unwise. 

I have tested a build with the ToLower changes outlined above (plus several small related changes). I should be able to submit it within a week. There are a large number of small changes (nearly every use of ToLower needs to change to FoldCase).

### To Reproduce

1. See original defect and instructions above
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 20 alpha 3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment] 2022-10-04 19:14
Duplicate of #19883 that's still open. No need for another

**Closed by fuzzard** 2022-10-04 19:14 UTC
Labels: Resolution: Duplicate
