### ISSUE TITLE
KODI Interface Does Not Adjust When Switching Between Monitors with Different Resolutions in Full-Screen Mode on Windows

### ISSUE THREAD

**Issue by selmant** [xbmc/xbmc#25697] opened 2024-09-02 21:05 UTC
### Describe the bug
When using KODI on a Windows environment with two monitors (21:9 and 16:9), switching from one monitor to another using the \ shortcut for full-screen mode causes the menus to remain in the resolution of the previous monitor. The menus do not get redrawn or resized according to the new resolution.

## Expected Behavior
When switching KODI between monitors of different resolutions in full-screen mode, the application should recalculate and redraw the menus and interface elements to fit the new monitor’s resolution.

## Actual Behavior

Upon switching between monitors of different resolutions (21:9 to 16:9 or vice versa) using the \ shortcut, the menus and interface elements remain in the resolution of the previous monitor and do not adjust to the new resolution.

## Possible Fix

To fix this issue, KODI could recalculate the interface layout every time it is switched to full-screen mode on a different monitor. This would ensure the menus and interface elements are redrawn according to the new resolution.

### To Reproduce

1. Use KODI on a Windows environment with two monitors, one with a 21:9 aspect ratio and another with a 16:9 aspect ratio.
2. Start KODI and set it to full-screen mode on one monitor.
3. Use the \ shortcut to switch KODI to the other monitor in full-screen mode.
4. Observe that the menus and interface do not adjust to the new monitor's resolution.

### Debuglog

The debuglog can be found here:

Use KODI on a Windows environment with two monitors, one with a 21:9 aspect ratio and another with a 16:9 aspect ratio.
Start KODI and set it to full-screen mode on one monitor.
Use the \ shortcut to switch KODI to the other monitor in full-screen mode.
Observe that the menus and interface do not adjust to the new monitor's resolution.

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 11
 - Kodi version: 21.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by thexai** [comment] 2024-10-25 16:06
Duplicate of https://github.com/xbmc/xbmc/issues/25875

(root cause is window resize, regardless of whether it is on the same monitor or another)

**Closed by thexai** 2024-10-25 16:06 UTC
Labels: Triage: Needed
