### ISSUE TITLE
PVR: regression: Wrong channel numbers in groups

### ISSUE THREAD

**Issue by bam80** [xbmc/xbmc#17324] opened 2020-02-05 15:53 UTC
### Describe the bug

Channels have the same numbers in all groups. There is no way to set them for any group (other than `All Channels`).

## Expected Behavior

There should be a way to set channel numbers for groups independently.
That behavior was in Krypton.
In Group Manager, channel were added to the end of the group and take sequential numbers, starting from 1. That way user could manage channel numbers in groups. 

## Actual Behavior

Wherever channel is added to the group in Group Manager, it keeps it's number and position from `All Channels` group and there is no way to change it. 

## Possible Fix

Restore previous behavior. At least, make it optional.

### To Reproduce

1. Install any PVR addon, e.g PVR Demo.
2. in [Settings/TV/General](https://kodi.wiki/view/Settings/TV/General), TURN OFF both options below:
- [Use channel order from backend(s)]( https://kodi.wiki/view/Settings/TV/General#Use_channel_order_from_the_backend.28s.29)
- [Use channels number from backend](https://kodi.wiki/view/Settings/TV/General#Use_channels_number_from_backend)
3. Go to [Group manager](https://kodi.wiki/view/Settings/TV/General#Group_manager), add some random channels to any group.
4. The channels get added with the same numbers and order they had in "All Channels" group (effectively, when they were ungrouped). There is no way to change that. (see screenshots)

### Debuglog

The debuglog can be found here:
http://sprunge.us/yqaXZw

### Screenshots 

Leia, wrong numbering in Group #3
![screenshot000](https://user-images.githubusercontent.com/233979/73853379-ce556b00-4841-11ea-9a35-7a3ceaf1c874.png)
Krypton, right numbering
![image](https://user-images.githubusercontent.com/233979/73857006-54c07b80-4847-11ea-883f-6180930501e1.png)

## Additional context or screenshots (if appropriate)

If group's channel numbers are changed in the database directly (from external program), they are overwritten by Kodi with those fake numbers. So the user's data from e.g previous Kodi version are just lost.

#16593

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Leia

@ksooo @phunkyfish @Leatherface75

**Comment by phunkyfish** [comment] 2020-02-05 16:04
You didn’t mention which PVR addon you use?

In all likelihood this could be intended behaviour in kodi 18.

**Comment by phunkyfish** [comment] 2020-02-05 16:07
Can you also check what happens in Kodi 19?

**Comment by ksooo** [comment] 2020-02-05 16:37
> Restore previous behavior. At least, make it optional.

Intended change in behavior in Kodi 18, "fixed" in Kodi 19. It's optional now.

**Comment by bam80** [comment] 2020-02-05 17:10
> You didn’t mention which PVR addon you use?

Fixed. It happens regardless off PVR addon. In the screenshot above I used PVR Demo addon, but first faced it with IPTV Simple.

> In all likelihood this could be intended behaviour in kodi 18. Which would mean it’s not a regression.

Looking at the linked PR, I see now it probably was by intention. But I still think it is a regression, since it was extremely useful functionality which was broken without possibility to bring it back.
I'm personally heavily depend on it in my every day usage. Later I'll explain why it's important.

So Dear Developers. If you see new behavior more appropriate for you personally, please still let us users decide and at least add an option to return old group numbering for those who find it highly welcomed.
After all, we could have that option temporary, and if no one really need old behavior - remove it in next version.

Unfortunately, it's not first time things was intentionally ~~improved~~ broken recently.
I ask you maybe change things more carefully. Please don't take personally.

> Intended change in behavior in Kodi 18, "fixed" in Kodi 19. It's optional now.

Thanks @ksooo , I see you are along those who voted for new numbering. I'll try to explain my position and hope it will be more clear to you.
For now, the question is if that option always accessible or only if I use backend channel numbers?
You see, I use IPTV Simple and it usually brings no meaningful channel numbers, so backend channel numbers make no sense for me..

**Comment by ksooo** [comment] 2020-02-05 17:30
> So Dear Developers. If you see new behavior more appropriate for you personally, please still let us users decide and at least add an option to return old group numbering for those who find it highly welcomed.

 I see your point. However, what I've learned  is that every change in behavior is welcomed by some users and seen as a regression/bug by others. Making something optional makes the code more complex and finally it's up to those who maintain the code to make the decision.

**Comment by bam80** [comment] 2020-02-05 20:45
Ok, let me describe my use-case.
I have about 500 channels in IPTV Simple, it's from randomly arranged remote M3U playlist, so no backend numbering/ordering is useful here and I can only rely on local arrangement (which resets every time the remote decides to change their channel URL's but that is [another](https://github.com/kodi-pvr/pvr.iptvsimple/issues/322)  problem).
From those, only ~40 are ordered, and that are mostly ungrouped channels. Others than that are just a mess, and have no meaningful numbers to be retained for other groups.
Other actual channels are grouped and have their own numbers in their groups.
All of that were carefully crafted, it was mach efforts to do so, not for that one day it would be happily smashed by next Kodi update or something..
So in my usage, if I want to watch movie, I won't recall it's 3-digit number in All Channels list. Instead, I go to group Movies and select needed channel there, by 1-2 digits or by cursor.

I don't think my usage is so unique. Having that, I thinks it's crucial for Kodi to keep old behavior, even if it takes a little more code. After all, in the first place Kodi exists for it's users and not for the code. And I appreciate for all the maintaining work here and trying to do it too, but I'm not so familiar with the code yet to do certain PR myself.

So I really hope we can get to compromise here, so let me repeat my question above:
> if that option is always accessible or only if I use backend channel numbers?

**Comment by ksooo** [comment] 2020-02-05 21:03
I see two options:

1. Get familiar with the code and come up with a PR that re-introduces the old behavior as a user setting.
2. Stick with Krypton.

**Comment by bam80** [comment] 2020-02-05 21:12
Does it mean that the answer to my question is NO?
If so, can we slightly change this PR #16593 to make the option always accessible?
About Krypton, thank you but I put too much efforts to Kodi to just stick with it :)

**Comment by phunkyfish** [comment] 2020-02-05 23:10
Is what you want is to start the channel numbering from one in each group?

**Comment by bam80** [comment] 2020-02-06 00:40
Yes, but I need both backend number/order options set to off. I could check Matrix tomorrow on mainstream distro ;) Looking into the code, it might actually work for me. Fingers crossed!

**Comment by phunkyfish** [comment] 2020-02-06 08:59
Please try it first.

**Comment by bam80** [comment] 2020-02-06 17:04
Seems I having troubles to get PVR working on Matrix: https://forum.kodi.tv/showthread.php?tid=337622&pid=2922207#pid2922207

**Comment by bam80** [comment] 2020-02-06 17:33
Ok I tried Matrix. I turned on the numbering from 1. Observing strange behavior:

Krypton:
> In Group Manager, channel were added to the end of the group and take sequential numbers, starting from 1. That way user could manage channel numbers in groups.

This doesn't the case any more. While the channels starts from 1 in group, when I try to add Demo TV Channel 1 to Group #3, it oddly inserted to number 2 instead of the end of the list:
![image](https://user-images.githubusercontent.com/233979/73962500-9fadc200-491f-11ea-9f69-4bd980e724e7.png)

**Comment by bam80** [comment] 2020-02-07 10:26
@phunkyfish any thoughts?

**Comment by ksooo** [comment] 2020-02-07 10:41
Could you just be patient? I'm pretty sure phunkyfish will speak up without any "reminder" if he has something to say. Every GitHub comment sends out email to lots of people. Stop spamming us, thanks.

**Comment by phunkyfish** [comment] 2020-02-07 11:06
I will take a look at this when I have time, what you are looking for makes sense. As ksooo said, please be patient.

**Comment by phunkyfish** [comment] 2020-02-08 16:37
Ok, so I checked back to my notes when I added the group specific numbering back in. Your use case was tested and worked correctly. I also just checked it now.

The only difference I can see is that all my data was created in matrix. I assume yours was carried from Krypton.

**Comment by phunkyfish** [comment] 2020-02-08 16:38
![C95EFD75-62D4-4FDB-B38B-75C8B4E466E9](https://user-images.githubusercontent.com/4601187/74088741-7ad95c00-4a91-11ea-8332-89d57cee4675.jpeg)

**Comment by phunkyfish** [comment] 2020-02-08 16:40
Above are my pvr settings. Only numbering from 1 is checked.

**Comment by phunkyfish** [comment] 2020-02-08 16:42
Ah, but if I go back and edit the group again it doesn’t work. Hmmm

**Comment by bam80** [comment] 2020-02-08 16:44
Thanks for checking @phunkyfish .
So you tried on PVR Demo also?
I freshly installed Matrix nightly on Ubuntu, and had no Kodi db before that.
Do I need to check it again? (Ubuntu is not on my computer so I'm asking)

**Comment by bam80** [comment] 2020-02-08 16:55
> Above are my pvr settings. Only numbering from 1 is checked.

As far as I remember I had [Synchronise channel groups with backends](https://kodi.wiki/view/Settings/TV/General#Synchronise_channel_groups_with_backends) enabled, if it matters.
The others are same.

**Comment by phunkyfish** [comment] 2020-02-08 17:19
I think might just be that the group manager code did not get updated when I added group numbering back in. So it’s just some missing logic in the GUI dialog hopefully.

**Comment by bam80** [comment] 2020-02-08 17:22
So you checked on some custom build? Could you check on one of the official nightlies?

**Comment by phunkyfish** [comment] 2020-02-08 17:38
You misunderstand me. There is logic missing in the group manager dialog that I need to add to support this.

**Comment by phunkyfish** [comment] 2020-02-08 17:39
What platform do you run on?

**Comment by bam80** [comment] 2020-02-08 17:42
Ah, so you could reproduce the issue?
I tested on Ubuntu 19.10 x64

**Comment by phunkyfish** [comment] 2020-02-08 17:44
Yes

**Comment by bam80** [comment] 2020-02-08 17:47
Ok. Hope you'll sort that out. Please ping me if you need my assistant to test, etc.
Thanks!

**Comment by phunkyfish** [comment] 2020-02-08 17:51
Can you test this PR: https://github.com/xbmc/xbmc/pull/17348

If you have linux do you Build Kodi yourself?

**Comment by bam80** [comment] 2020-02-08 17:55
Oh, actually I don't build it myself for a long time already..
Could we just merge it and I'll check on the next nightly?

**Comment by phunkyfish** [comment] 2020-02-08 17:59
Nightlies require the PR is merged.

Can you test on windows or OS X?

**Comment by bam80** [comment] 2020-02-08 18:03
Nope. Ok, if you really need me to test before the merge, I'm ready to dig in to the building.
Should I?

**Comment by phunkyfish** [comment] 2020-02-08 18:06
Let me see if I can do a Ubuntu testbuild.

**Comment by phunkyfish** [comment] 2020-02-08 18:20
Nope. No testbuilds for Ubuntu as far as I can tell.

**Comment by bam80** [comment] 2020-02-08 18:24
Ok, probably I could try to build it tomorrow.

**Comment by bam80** [comment] 2020-02-08 23:36
@ksooo BTW, don't we have CI to make testbuilds?

**Comment by phunkyfish** [comment] 2020-02-08 23:44
We have CI to make testbuilds for most platforms. But generally not Linux users as far as I’m aware as they tend to build themselves.

**Closed** 2020-02-10 10:24 UTC
Labels: Component: PVR
