### ISSUE TITLE
Kodi v19.0, does not see External SSD Drive, but v18.9 did without issue.

### ISSUE THREAD

**Issue by sammydc77** [xbmc/xbmc#19447] opened 2021-03-20 16:12 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

Hello:

I have a Google Pixelbook i5 8GB / 256GB, with a Silicon Power B75 Pro 1TB External SSD.  Prior to the upgrade to Kodi v19.0, I ran v18.9, with the External recognized by Kodi v18.9 [System Information and Plugin's], by its Label [SP B75 Pro].  Kodi v19.0, does not see it.  Only Plugins, present in Kodi v18.9, prior to the upgrade to v19.0 [Seren / Oath / Venom / Backup...], can see it, but only by the UUID/GUID, not the Label [SP B75 Pro], which they did in v18.9.  If I have to uninstall/reinstall a Plugin, to fix an issue, as I tried to do with Backup - v1.66 - robweber, it does not even see the UUID/GUID anymore  I had to copy my backup [from this morning] to my Pixelbook Download Folder, to restore, then all was well, baring the fact that I still do not see the Label [SP B75 Pro], only the UUID/GUID.  This is frustrating, as I was really hoping that Kodi v19.0 would finally treat Android [as Koying, in the SPMC days], as well as the Windows, Apple and Linux Versions are supported.  I am running the Latest Chrome OS Stable State and really do not want to Root this machine.  I can only use the Google Play Version available, which always seems to be an ARM Version, not 64-bit x86 Intel based,  I would appreciate any thought you may have on how to fix this.  I am 64, and have spent 25 years in IT, now retired, so I could make a simple fix, if that is all that is needed, otherwise, will this be rectified in the next iteration?  Additionally, I am blind in one-eye, with poor vision now, so I connected the Pixelbook to my Sony 4K TV, via HDMI, so I can read stuff and watch Kodi v19.0.  I really appreciate any time you can give this issue. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/mivoboxazo.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by the-black-eagle** [comment] 2021-03-20 18:21
We do not support installations containing addons that facilitate piracy. Please edit your post to remove any references to such addons and submit a clean log, otherwise your issue will be closed.

Thanks

**Comment by sammydc77** [comment] 2021-03-20 18:53
Hello:

Which Add-ons are you referring too?   Most everything has been disabled and/or removed, when Kodi v19.0 was updated.  I really do not know what is left that is considered facilitating piracy?  Please review the attached PDFs [very short list], which show the only active Video Add-ons.  I really appreciate your time.

Regards,

Joseph
 
[Current Kodi v19.0 Add-ons I.pdf](https://github.com/xbmc/xbmc/files/6176208/Current.Kodi.v19.0.Add-ons.I.pdf)
[Current Kodi v19.0 Add-ons II.pdf](https://github.com/xbmc/xbmc/files/6176209/Current.Kodi.v19.0.Add-ons.II.pdf)

**Comment by the-black-eagle** [comment] 2021-03-20 19:27
Basically, anything in your debug log that is orange in colour.  It's quite simple.  If you have some addon (or repo) installed that fetches (or can fetch) content for free that one would normally expect to pay a fee for, then that's piracy.  There is a non-exhaustive list on our wiki -> https://kodi.wiki/view/Official:Forum_rules/Banned_add-ons

**Comment by sammydc77** [comment] 2021-03-20 19:38
Hello:

I will take a look, but the ones I have, were recommended, by kodi.tv?  I
appreciate your reply ad will take a closer look at the wiki, is it
current?  Are you referring to Add-ons, that are not currently working, nor
active, in Kodi v19.0, if so I do not have access from within Kodi v19.0 to
remove them?  Any thought on how to remove something [from Kodi Databases],
if I do not have access, from within Kodi v19.0?

Regards,

Joseph

**Comment by sammydc77** [comment] 2021-03-20 19:56
Hello:

You are welcome to close this issue, but please fix the problem.  I am sure I am not the only person to have noticed, Kodi v19.0 broke the Kodi v18.9 use of External SSD Drives primarily used for Backup of Kodi v19.0, now exceeding 1.5GB per Backup.

Regards,

Joseph

**Comment by sammydc77** [comment] 2021-03-20 19:59
Hello:

I would still like to know how to remove items from the Kodi v19.0 Databases, when they are not present, nor accessible.

Regards,

Joseph

**Comment by ksooo** [comment] 2021-04-06 18:38
duplicate of #19307

**Closed by ksooo** 2021-04-06 18:38 UTC
Labels: Platform: Android, Triage: Confirmed, v19 Matrix
