### ISSUE TITLE
TV show art string from scraper is larger that TEXT field (64k) in database resulting in failed TV show addition

### ISSUE THREAD

**Issue by 78andyp** [xbmc/xbmc#25918] opened 2024-11-01 19:32 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

Trying to add The Simpsons TV show. Directory `The Simpsons (1989)` contains subdirectories `Season 01` through `Season 31` with the individual .MKV episodes in each directory.

Using the TVDB TV show scraper.

Error in log:

https://paste.kodi.tv/ewapinaqor
It's too long for this comment as well!!

As you can see - the `c06` text is approx 120k.

You can fix it by `ALTER TABLE tvshow MODIFY c06 LONGTEXT` but I'm not sure this works in all database flavours (I don't think LONGTEXT exists in SQLite).

I'm happy to push a PR but I just want to make sure I get the right solution first (ie. should the scraper truncate the response, should the database field `c06` be modified etc..)

Intrestingly it works on a local database but fails on a remote database (as is here) - but I believe local databases are SQLite and the remote database is MarinaDB.

Thanks

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Can scrape show.

## Actual Behavior

Show not added properly. Blank entry in TV show library.

## Possible Fix

As above.

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/sicumupebe.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: master

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by neo1973** [comment] 2024-11-01 19:50
Closed as duplicate of #15768.

**Closed by neo1973** 2024-11-01 19:50 UTC
Labels: Triage: Needed
