### ISSUE TITLE
Local network connection delay when "Combine Split Video Items" feature activated 

### ISSUE THREAD

**Issue by kleczerx** [xbmc/xbmc#23212] opened 2023-04-27 14:32 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

- This bug has existed since Version 19 to present day version 21.0 Omega Alpha1.

- The setting feature "Combine split video item" when set to ON, effects the local network access via KODI's main menu "Video" to enter any server. When activated to ON, and then using Main Menu "Video > Files > entering the 1st level folder of the local-server (over a 10Gbit link) there is a full 60-second delay before finally given entry, and then another 60-sec wait before entry to the 2nd level folder. > Once beyond the first two level folders moving among folders beyond this point is normal; working with video/other files files is normal. When exiting from a server back to Kodi, there are similar delays before clearing the server(s).

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Expected, the entry into any server folder should be instantaneous, without delays.

## Actual Behavior

I have two different model QNAP servers where this delay in connecting occurs; but only if the feature "Combine split video items" is set to ON, if set to OFF passage into the servers is instantaneous and no delays experienced.

## Possible Fix

The feature code likely effects the refresh-function when KODI tries to recognize the server. Worth noting, the KODI library interface (Movies & TV shows libraries) has no obvious effect (no delaying) when selecting or playing video.

### To Reproduce

1.  First activate the buggy feature:  Kodi Settings > Media > Videos > Files "Combine split video items".
2.  Second: Try entering any server using KODI: Kody's main side-menu > Videos > Files > select any previously listed server. > on selection a 60sec delay occurs > then select a server's sub-folder - 60sec delay > any folder/file selected from this point will respond normal and faster.
3.

### Debuglog

The debuglog can be found here:

xxx

### Screenshots 
Here are some links or screenshots to help explain the problem:

xxx

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Want to enter a server via the KODI application.

### Your Environment
Used Operating system:

 - [ x] Android - Nvideo Shield TV
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ x] Windows - Windows 11 x64 latest update
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Kodi 21.0 Omega alpha1 arm64-v8a AND 21.0 x64 for Windows.

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by thexai** [comment] 2023-06-09 17:43
Duplicate of https://github.com/xbmc/xbmc/issues/21851

**Closed by thexai** 2023-06-09 17:43 UTC
Labels: Ignored rules, Triage: Needed

**Comment by CrazyEarthGuy** [comment] 2023-08-28 04:46
This is still a major issue using Kodi v20.2 on a FireTV 4K Max, when using NFS to connect to a Synology ds920+ NAS.
I have about 2300 movies stored on my NAS in a movie folder (each in their own subfolder), and the NAS & FireTV are both connected using Ethernet. When I try to open/browse that movie folder from FireTV using Kodi, it takes about 45 seconds to open when "Combine split video items" is set to TRUE, but only a few seconds to open when set to FALSE. That is the only setting I need to toggle to see the difference.
