### ISSUE TITLE
KODI Matrix - XMBChelper and Harmony keymap load issue

### ISSUE THREAD

**Issue by requa3r0** [xbmc/xbmc#19321] opened 2021-03-02 21:04 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

When starting KODI Matrix on OSX, the harmony keymap is not loaded, although its has been set to use the harmony remote under settings - input - apple remote

It does not matter if you use the standard customcontroller.Harmony.xml provided in the masterprofile, or if you use a custom keymap verson of customcontroller.Harmony.xml placed in the userdata/keymap folder.

If you set the remote to -disabled- then -standard- then -harmony- the keymap is loaded correctly but not reloaded when KODI is started at a later time.
Both masterprofile or userprofile version will load correctly if done manually.

The XBMChelper is NOT keeped alive, even if you have select the -allow KODI to be started with the remote- option.

It would appear that it is killed unless you do above load of the keymap manually.
If you dont, XBMChepler is closed on KODI exit.

It seems like the remote setting is not properly activated on load.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

KODI should load the correct keymap as set under settings-imput-apple remote
And XBMChelper should be kept alive on exit

## Actual Behavior

It does not load the correct keymap 
And XBMChelper is killed on exit.

## Possible Fix

Review the remote - settings loading process and fix the bug.

### To Reproduce
Steps to reproduce the behaviour:

1. install KODI MATRIX on OSX - with a fully fresh userdata / masterprofile 
2. setup the harmony remote to be used as a KODI remote. There are various guides for this.
3. select the harmony under settings-imput-apple remote

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/xahuraweka.kodi

2 lines are interesting

What is this error. 
Could especially the first error be related to a load of settings issue.

2021-02-22 17:36:10.807 T:203828 WARNING <general>: JSONRPC: Could not parse type "Setting.Details.SettingList"

2021-02-22 17:37:11.243 T:204039 WARNING <general>: DARWINOSX: underflow (0 vs 4096 bytes) 

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [x ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Matrix 19.0 Build 19.0.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Fabeuss** [comment] 2021-04-08 20:09
You have described very well the problem I am facing since kodi 19... 
(mac mini and harmony)
I hope that a solution will be found soon, change the remote setting every time I start up  is really boring....

**Comment by requa3r0** [comment] 2021-04-09 15:30
Fabeuss 

> You have described very well the problem I am facing since kodi 19...
> (mac mini and harmony)
> I hope that a solution will be found soon, change the remote setting every time I start up is really boring....

I know your pain. And I am not getting any more popular with the family either ;O)

I have also made a forum post here, to raise awareness and see if other remotes etc are affected. 
Perhaps out a comment here to.
https://forum.kodi.tv/showthread.php?tid=360694

I hope it will get solved soon.

**Comment by requa3r0** [comment] 2021-05-05 13:55
Dear fuzzard.

That is very good news. 
When can we expect a new release with the fix implemented?

Is there anything I can do? If you give me a link or directions to files that I can replace, I will be happy to test your solusion.

Kind regards Requaero

**Comment by fuzzard** [comment] 2021-05-05 16:54
The change is available in any master nightly build after ~10 days ago. http://mirrors.kodi.tv/nightlies/osx/x86_64/master/

**Comment by glorious1** [comment] 2021-05-05 21:05
I can confirm that both issues (xbmchelper and the remote mapping) are fixed in the nightlies.  Thank you @fuzzard!!

**Comment by requa3r0** [comment] 2021-05-07 06:12
I can also confirm that both issues are fixed. Thank you @fuzzard

**Closed** 2021-05-07 06:12 UTC
Labels: Resolution: Fixed

**Comment by requa3r0** [comment] 2021-05-15 11:49
JUST FYI
The latest stabel Matrix 19.1 does not include the fix.

Latest nightly is needed.

The fix is included  in the latest master http://mirrors.kodi.tv/nightlies/osx/x86_64/master/

@fuzzard 
If you read this...let me know when the fix is included in a matrix 19.x stable release, and ill check and verify.
Thanks for the fix.

**Comment by phunkyfish** [comment] 2021-05-15 12:08
Due to the scale of this change it’s likely not a candidate for backport I’m afraid.

**Comment by requa3r0** [comment] 2021-05-15 12:13
ill stay on nighties then ;O)

**Comment by glorious1** [comment] 2021-05-15 14:13
What does “not a candidate for backport” mean?  That it won’t be incorporated into a stable release?

**Comment by phunkyfish** [comment] 2021-05-15 14:21
> What does “not a candidate for backport” mean? That it won’t be incorporated into a stable release?
> […](#)

Correct. If a change is to extensive it’s unlikely it would be backported as the risk of introducing further problems would be to high.

But I’ll leave @fuzzard to confirm as he would know being the author.
