### ISSUE TITLE
Kodi 18 crash using script.extendedinfo 

### ISSUE THREAD

**Issue by scott967** [xbmc/xbmc#15226] opened 2019-01-09 23:11 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi 18 crashes when extendedinfoscript dialog window YoutubeList.xml is closed.  Current viewmode for the media window is changed without user action.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

dialog window YoutubeList.xml closes and Kodi returns to the existing media window with the existing viewtype mode.

## Actual Behavior

When the dialog is closed by keyboard action "back" the dialog closes and gui shows the media window.  Within a couple of seconds Windows 7 error popup launches that Kodi has stopped working debug/close 

## Possible Fix

After extensive testing of available Windows nightly builds, nightly 170517 is the last one that does not crash, and 170629 is the first one that does crash.  I don't have any builds between those dates for further testing.

What I found is that script.extendedinfo loads modules from script.module.kodi65
kodi65 has a file dialogbaselist.py that handles setting up YoutubeList.xml as an XMLdialog and populating the container with listitems (links to youtube videos).

Dialogbaselist.py implements Class DialogBaseList(object) and a method in that class is def OnInit(self):

OnInit contains the following:

        viewtype = addon.setting("viewtype_selection")
        if viewtype:
           xbmc.executebuiltin("Container.SetViewMode(%s)" % viewtype)

In a default install "viewtype_selection" is set to -1.  I tried manually changing it to 500 (the id of the container in YoutubeList.xml) but that didn't change the crash.  I then commented out the
xbmc.executebuiltin("container.SetViewMode(%s)" % viewtype)

That fixed the problem of the media window changing its viewmode (but still crashed).

I then located the method def update_ui(self):

In update_ui is 

```
for item in self.listitems:
    item.set_label2(self.LABEL2[self.sort](item))
    items.append(item.get_listitem())
    self.addItems(items)
```

which I changed last line to

    self.getControl(500).addItems(items)

After which I no longer get the crash (limited testing tho)

However, this seems like a work-around, AFAIK, the Python API allows scripts to use XMLwindow containers with view modes (and other Dialogs in this addon do have multiple views).  So I consider the problem to be in the Python API xbmc.gui, not the addon itself (which is just the trigger).

### To Reproduce

1. Install Kodi 18 RC4 Winx64
2. Install Kodi addon ExtendedInfoScript from Kodi repo
3. Add a music source and scan to populate the library
4. Open music library artists node.  Select any artist.
5. Open the musicinfo dialog (Estuary) for the selected artist.  In the dialog select/click "search youtube" button.
6.  YoutubeList.xml dialog opens
7.  Exit the youtubeList dialog (keyboard "back")
8.  Dialog closes / Kodi crashes

### Debuglog

The debuglog can be found here:  https://pastebin.com/8vTkjjwZ

No crash files or stack traces are produced.

I did try to run VS2015 debugger and it seemed to indicate a problem in de-allocating a pointer. 

### Screenshots 
Here are some links or screenshots to help explain the problem:

None needed

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

There's also a problem in script.module.kodi65 where it attempts to open a busy dialog.  That can be fixed for Kodi 18 and it doesn't change the crash behavior at all.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Win 7 x64 sp1
 - Kodi version:  Kodi (18.0-RC4 Git:20181228-14086a7bd3). Platform: Windows NT x86 64-bit

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment] 2019-01-10 12:03
I tested as well on OSX and was able to reproduce. However, for me it only happened if you don't wait long enough for the youtube dialog to open and request a new one while the first request is still waiting to be completed. Makes me wonder if the main issue is in the addon itself and not in kodi (the script should avoid opening a new window if the same window is already being loaded).

**Comment by ronie** [comment] 2019-01-13 00:34
> After extensive testing of available Windows nightly builds, nightly 170517 is the last one that does not crash

PR https://github.com/xbmc/xbmc/pull/11766 was merged a few months before that (2017-03-17)?

**Comment by enen92** [comment] 2019-01-14 14:39
I reverted the said PR and the error still shows, so definitely not the cause.

**Comment by scott967** [comment] 2019-01-15 19:09
Thanks for checking 11766.  I probably jumped on that too quickly.  I do suspect the problem revolves around WindowXML creating media containers though.  In this script, though, I guess it actually opens a WindowDialogXML and I don't have the OOP chops to understand how the inheritance works for media containers in a WindowDialogXML object.

**Comment by ronie** [comment] 2019-01-15 21:03
looking at the crashlog, the crash seems to be happening somewhere here (i could be wrong):
https://github.com/xbmc/xbmc/blob/3baca5a0e2826fde455ab5e60fc1663c7339cd1f/xbmc/guilib/GUIControlLookup.cpp#L100-L109

that piece of code was introduced by this PR: https://github.com/xbmc/xbmc/pull/12300

perhaps @peak3d can find a bit of time to take a look at it?

**Closed** 2019-01-23 11:20 UTC
