### ISSUE TITLE
remote (WAN) recording playback with TVheadend fails

### ISSUE THREAD

**Issue by jeee** [xbmc/xbmc#16410] opened 2019-07-27 12:25 UTC
TV recordings do not play properly in kodi via TV>Recordings while the content seems to play fine on the same device as well as the same content directly streamed via Live TV.

See:
https://trac.kodi.tv/ticket/16915
​https://tvheadend.org/boards/5/topics/21750?r=21799

**Comment by jeee** [comment] 2019-07-27 12:27
Sent in error: all info is already described in the but on trac. The bug is still active in kodi on ubuntu (18.04).

**Comment by DaVukovic** [comment] 2019-07-27 13:26
Both report are over 3 years old. Don't you think things might have changed since? Beside the fact Kodi 18 didn't exist at that time

Please get us a logfile using a current Kodi version which shows the error. We can't do anything without that log and a 3yo report is absolutely useless. 

Tbanks in advance

**Comment by jeee** [comment] 2019-07-27 15:12
I reopened it because it still exists of course and I am hoping on a fix for quite a while now ;-)

I get the same behavior everywhere. Probably as described in the ticket it is a different implementation for the 2 streams.

the log is from the current version on ubuntu 18.04 LTS:
$ kodi -v
17.6 Debian package version: 2:17.6+dfsg1-1ubuntu1 Media Center Kodi from Debian
Copyright (C) 2005-2013 Team Kodi from Debian - http://kodi.tv

In the log: I play the recording it starts, plays a second then starts buffering a bit plays a second again etc. Then I start the live TV from the same channel and after a second or so it plays without any issues.

[kodi.log](https://github.com/xbmc/xbmc/files/3438290/kodi.log)

**Comment by DaVukovic** [comment] 2019-07-27 15:28
The log you provided is neither a debuglog (see the link from our bot above) nor is it a complete log as the beginning is missing. 

If you hope for a fix, then I would suggest to follow the advices you have been given ;) (no offense). We will need a log with debugging enabled. Otherwise it's useless unfortunately. 

Anyway, by reading: 
> 17.6 Debian package version

I highly guess you installed Kodi from the Ubuntu repositories. That version is patched by debian and nearly unsupported in here. We always recommend to install Kodi from our ppa. The version you installed is EOL anyway as there won't be any fixes for Kodi 17.6 anymore and you obviously haven't tested Kodi 18 yet. 

Please read this wiki carefully and report back if you have Kodi 18 installed and are able still able to reproduce your issue. If you are able to reproduce, then please get us a **debug**-log. 

Installing instructions: https://kodi.wiki/view/HOW-TO:Install_Kodi_for_Linux#Installing_Kodi_on_Ubuntu-based_distributions

Thanks

**Comment by jeee** [comment] 2019-07-27 18:28
Thank you for your fast reply.

I installed the packages as described in the page you gave me. Have to say it is already much better; it now buffers longer and plays longer. However the difference in playback quality remains: live tv plays without issue and recordings are buffering. I attached a debug log this time in which I first played live tv and then a recording (recorded from same channel)

Hope this is something you can use.

[kodi-debug.log](https://github.com/xbmc/xbmc/files/3438467/kodi-debug.log)

**Comment by DaVukovic** [comment] 2019-07-28 08:32
ok thanks. I'm not so sure, what this issue has to do with **WAN** as that would mean outside your local network (LAN)....WAN = Wide area network, but that's probably a decision need to be made by one of our devs ;) @ksooo probably?!

**Comment by jeee** [comment] 2019-07-28 10:16
> ok thanks. I'm not so sure, what this issue has to do with **WAN** as that would mean outside your local network (LAN)....WAN = Wide area network, but that's probably a decision need to be made by one of our devs ;) @ksooo probably?!

Seems like a normal requirement with current fiber connections; being able to watch ones recordings on vacation ;-)

> 
> > Host CPU: Common KVM processor, 2 cores available
> 
> are you running Ubuntu 18.04 in a VM?

That one did. Just tried kodi on android from google play as well (18.3) and that has the same issue.

**Comment by DaVukovic** [comment] 2019-07-28 10:28
Could you please share more/all needed info?

How do you connect to your home network? Via VPN? Maybe that's the culprit/bottleneck. As from the log, I only see that you are opening: 

`VideoPlayer::OpenFile: pvr://recordings`

Where I guess Kodi assumes it's connected to your home network as there's no other IP/path mentioned. 

If yes, and the VPN is the bottleneck then, then I would probably take a look at: 

https://kodi.wiki/view/HOW-TO:Modify_the_video_cache

and see if modifying it will help. 

Anyway, if we are talking about a VPN connection, there's not much we can do here at this location. As it would end up in a support question and those need to be done at our forums. Also be aware that we have a VPN policy: https://kodi.wiki/view/Official:VPN_policy

**Comment by jeee** [comment] 2019-07-28 11:02
If it was a VPN it would be under point 4 described there; connecting 2 own home LANs. It would be the safest/most secure option I suppose. However to prevent any overhead I connect to the tvheadend server directly (it does not care if the client is on the LAN or remote).

The content that is played is the same; it's the same channel; either recorded or played via live tv. So I suppose the bottleneck cannot be the connection, only the way it is handled.

Just tried with the cache settings from example 5 described in the page you gave me but that makes no difference. The log shows it finds it:
`2019-07-28 12:50:54.888 T:140531344685184  NOTICE: Contents of special://profile/advancedsettings.xml are...
                                            <advancedsettings>
                                              <cache>
                                                <buffermode>1</buffermode>
                                                <memorysize>4289999999</memorysize>
                                                <readfactor>1000</readfactor>
                                              </cache>
                                            </advancedsettings>
`
I remember I had tried all kind of different cache settings on the old kodi as well (old ticket). Nothing seemed to make a difference back then.

**Comment by arnova** [comment] 2019-07-29 05:37
> If it was a VPN it would be under point 4 described there; connecting 2 own home LANs. It would be the safest/most secure option I suppose. However to prevent any overhead I connect to the tvheadend server directly (it does not care if the client is on the LAN or remote).
> 
> The content that is played is the same; it's the same channel; either recorded or played via live tv. So I suppose the bottleneck cannot be the connection, only the way it is handled.
> 
> Just tried with the cache settings from example 5 described in the page you gave me but that makes no difference. The log shows it finds it:
> `2019-07-28 12:50:54.888 T:140531344685184 NOTICE: Contents of special://profile/advancedsettings.xml are... <advancedsettings> <cache> <buffermode>1</buffermode> <memorysize>4289999999</memorysize> <readfactor>1000</readfactor> </cache> </advancedsettings> `
> I remember I had tried all kind of different cache settings on the old kodi as well (old ticket). Nothing seemed to make a difference back then.

Cache won't help here since it only applies to items played from our filesystem and unfortunately that's not the case here.

**Comment by ksooo** [comment] 2019-08-06 15:37
Go to pvr.hts addon settings and increase "Stream read chunk size for recordings (KB)". Does that help?

**Comment by jeee** [comment] 2019-08-06 16:27
> Go to pvr.hts addon settings and increase "Stream read chunk size for recordings (KB)". Does that help?

Awesome. Is that a new option? seems to help! Thank you.

**Comment by ksooo** [comment] 2019-08-06 16:41
You are welcome. Closing the issue...

**Closed** 2019-08-06 16:41 UTC
Labels: Component: PVR, Component: Video, Platform: Linux, v18 Leia
