### ISSUE TITLE
Kodi occasionally aligns the same episode information to multiple episodes

### ISSUE THREAD

**Issue by otrconvert** [xbmc/xbmc#18275] opened 2020-08-11 08:49 UTC
### Describe the bug

Kodi occasionally displays the wrong episode details for a small number of episodes.

## Expected Behavior

I name all my tv programs with the syntax "Program Name - xxx - Episode Title" where xxx is the season/series number combined with the episode number. e.g. "Fresh Prince of Bel Air - 108 - Someday Your Prince Will be in Effect - Part 1".  However Kodi is occasionally misaligning episodes when retrieving program information from TheTVDB.com
## Actual Behavior

Generally this works fine and I have a program catalogue via TheTVDB.com covering hundreds of TV series that link to the correct series and episode information. However occasionally some episodes will link to the same episode incorrectly. e.g. "Fresh Prince of Bel Air - 101 - The Fresh Prince Project" links correctly, but the above episode 108 also links to 101, along with 401, 501, 609, 614 and 623. Episode 102 is correct, but episodes 109, 402, 502, 610, 615 and 624 also link to it.

### To Reproduce

1. Create a folder called "Fresh Prince of Bel Air" and populate with episode titles using the above examples
2. "Scan to Library" using TheTVDB.com as the Information Provider
3. Open the folder and validate the epsiode names

### Debuglog

The debuglog can be found here: https://paste.kodi.tv/oqamurajey.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
18.8

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment] 2020-08-11 09:14
We need a debuglog before we look at the issue.

Thanks.

**Comment by otrconvert** [comment] 2020-08-11 11:03
Apologies - Log now added

**Comment by KarellenX** [comment] 2020-08-11 19:32
Thanks.

The problem is due to the method you have chosen to number your files. You have used the **101** pattern instead of the **S01E01** pattern that we always recommend.

Your pattern is the last pattern to be scanned and is susceptible to false matching which is what is happening in your case. Did you note all the wrong entries have **Part 1** or **Part 2** in the file name? Because  you are just using numbers, Kodi cannot distinguish which is numbers and which is SxxExx. To the scanner 101 and  1 are numbers so it picks the last number in your file name.

Using SxxEyy, then the scanner can clearly see this is meant to be the episode number. 

Change to the **SxxEyy** naming and all will be fixed.

This is not a bug, and please next time start on the forum first before posting here as this area is not used for support. Your issue will be closed. If you still believe this is a bug, then it won't be fixed.

**Closed by KarellenX** 2020-08-11 19:32 UTC
Labels: Triage: Needed
