### ISSUE TITLE
Poster Thumbnails in folders are gone AND scanning individual files to the library is gone. #195 post from xbmc / skin.confluence

### ISSUE THREAD

**Issue by froSTed1030** [xbmc/xbmc#22650] opened 2023-01-31 11:46 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

In 19 and below, browsing thumbnail views in Confluence displayed posters. The context menu to scan an individual file to the library allowed this functionality. On NFS shares in subfolders where scanning is not automatic, both the context menu is missing, and despite being previously scanned to the library thumbnail view does NOT show posters.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
Setup: 

Nvidia shield Pro
NFS shares on a NAS with nested folders.
Confluence skin

Long-pressing a file brings up a context menu with the option to scan the file to the library and pull data from various sources.
The thumbnail view displays a poster.
Thumbnails of content not scanned display a checkmark when you have marked the file played or when the file has been played.
The info context menu selection allows you to customize the poster and/or correct an incorrect result from the scan.

## Actual Behavior

Long-pressing a file brings up a context menu WITHOUT the option to scan the file to the library. This context menu seems to only appear on folders now.
The thumbnail view DOES NOT display a poster, even on previously scanned files and even with nfo and jpgs with -poster or -fanart in the same directory as the file named correctly. 
Thumbnails of content not scanned do not display a checkmark when you have marked the file played or when the file has been played.
The info context menu selection is not there on individual files.

### To Reproduce

1. In confluence navigate through the Video, Files menu to an NFS share where a video media file (movie) is nested within at least 3 folders resides.
2.  Long press the file, and note that there are context menu options missing
3. Place an NFO and JPG file in the same folder as your movie. Restart Kodi. Navigate to the folder. Thumbnails do not display Posters.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 20

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment] 2023-02-01 08:32
Duplicate of...

https://github.com/xbmc/skin.confluence/issues/195

**Closed by KarellenX** 2023-02-01 08:32 UTC
