### ISSUE TITLE
Kodi 18 - Button play on Sony TV don't work anymore via CEC

### ISSUE THREAD

**Issue by thedonalfonso** [xbmc/xbmc#15444] opened 2019-02-06 14:53 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

Nvidia Shield with last android version available
Updated automatically to kodi 18
The "play" button on my sonyTV remote is not working anymore. I was using it to play/pause.
tried to manage the button with the mapper app but nothing worked

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Expect it to work as on kodi 17 : Play/pause behavior

## Actual Behavior

when clicking play button nothing appens

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android TV 8 on nvidia Shield
 - Kodi version: KODI 18.0 LEIA 

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by zeldin** [comment] 2019-02-11 20:23
I have a similar problem, with an IR remote connected using USB (also on Nvidia Shield).
What I found was the following.  The play button works:
* For starting a video from the library (i.e. as replacement for pressing the Select button)
* For unpausing a video which has been paused using the popup menu

However, it does _not_ work
* For pausing a video that is playing
* For returning to normal playback from FF or REW

both of which worked in Krypton.

I then turned on the debug log, and noticed something interesting:  While in the media browser, pressing the play button results in one "DEBUG: Keyboard" and one "DEBUG: HandleKey", both indicating the play button as being pressed (scancode 0x7e == KEYCODE_MEDIA_PLAY, HandleKey play_pause (0xf0bd), action PlayPause).  However, in the media player, _none_ of the media keys produce any "DEBUG: Keyboard" or "DEBUG: HandleKey" printouts.  The FF and REW buttons work correctly, but do not produce any traces.  The Menu button both works and produces traces.

I'm wondering if this is all caused by Kodi changing the target API level to 5.0, which according to https://developer.android.com/guide/topics/media-apps/mediabuttons will affect how media buttons are handled in Android...

**Comment by nadav74** [comment] 2019-02-22 11:11
This is practically a duplicate of #15395.

**Comment by zeldin** [comment] 2019-02-22 19:00
@nadav74 Yup, the log there matches mine in that there are no "Keyboard" traces for the media keys, only for the navigation keys.  Which means that "Play" is not going through HandleKey at all...

**Comment by nadav74** [comment] 2019-03-20 06:47
@zeldin It seems to be fixed on git head.

**Comment by zeldin** [comment] 2019-03-20 08:02
@nadav74 Yes, I actually got a system ("experience") upgrade on the Shield which fixed the problem for me.  :smiley_cat:

**Closed** 2022-05-04 17:04 UTC
Labels: v18 Leia, Issue Cleanup: Obsolete
