### ISSUE TITLE
Heavy stuttering on Android TV (Sony A95L)

### ISSUE THREAD

**Issue by dbarkar** [xbmc/xbmc#24421] opened 2024-01-03 21:05 UTC
### Describe the bug
Stuttering is so bad that it's impossible to watch movies. 
Most movies in my library are affected.
Tried opening from NAS and locally.
TV shows are played a little better but still with stuttering. 
Every other player (VLC, MX Player, Internal media player) handle this media file properly.
Mediainfo: https://paste.kodi.tv/agotusicud

## Expected Behavior
Smooth playback.

## Actual Behavior
Heavy stuttering.

## Possible Fix
Probably wrong media codec.
See CPU usage on the screenshot.
Maybe it depends on file size? 

### To Reproduce

1. Open media file
2. See the result

### Debuglog
The debuglog can be found here: https://paste.kodi.tv/decoqehayo.kodi

### Screenshots 
![screenshot](https://github.com/xbmc/xbmc/assets/1224655/4fe3df00-a0ce-4579-a0a6-0ec55d2853d2)

### Your Environment
Used Operating system:
 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 12
 - Kodi version: nigthly 20240102

**Comment by fritsch** [comment] 2024-01-03 21:26
It is SW accelerated on your device only, as all other codecs your mediacodec provides fail to open.

As plenty of other players work nicely, please find out which hw codec they use.

**Comment by dbarkar** [comment] 2024-01-03 23:19
Thanks for the tip!
I got this from logcat after playing video in internal player:
```
01-04 00:08:51.596 12537  6491 I SonyExoPlayer: LocalDlnaSampleSource$TrackCountManager#setTrackState: line 327: <FCHANGE> track=0 state=2
01-04 00:08:51.596 12537  6491 I SonyExoPlayer: MediaCodecTrackRenderer#onInputFormatChanged: line 1081: <FCHANGE> needsDrmInit = false, formatHolder.format = MediaFormat(null, video/VC1, -1, -1, 1920, 1080, -1, -1.0, -1, -1, eng, 5956000000, false, -1, -1, -1, -1, -1, 24), formatHolder.format = MediaFormat(null, video/VC1, -1, -1, 1920, 1080, -1, -1.0, -1, -1, eng, 5956000000, false, -1, -1, -1, -1, -1, 24) --->
01-04 00:08:51.597 12537  6491 I SonyExoPlayer: MediaCodecTrackRenderer#onInputFormatChanged: line 1101: formatHolder.format = MediaFormat(null, video/VC1, -1, -1, 1920, 1080, -1, -1.0, -1, -1, eng, 5956000000, false, -1, -1, -1, -1, -1, 24) init codec --->
01-04 00:08:51.597 12537  6491 I SonyExoPlayer: MediaCodecTrackRenderer#maybeInitCodec: line 500: MediaCodec.createByCodecName(c2.mtk.vc1.decoder) videoCodec=true
01-04 00:08:51.601 12537  6517 D CCodec  : allocate(c2.mtk.vc1.decoder)
```
My guess is that `c2.mtk.vc1.decoder` must be used.
Look like it was tested but rejected, howto find out why?

Is it possible to make a build that forces `c2.mtk.vc1.decoder` so I can test it? 
Or can you tell me what line to change in the source code?

**Comment by dbarkar** [comment] 2024-01-03 23:22
I also see some mentions of `c2.android.raw.decoder` in logcat, not sure if it's related.

**Comment by fritsch** [comment] 2024-01-04 12:57
You said that all other players work properly, e.g. VLC and the others you mentioned. I basically don't care about the hacked Sony ExoPlayer, which they hack to not need to support standards.

You have a log of VLC?

**Comment by dbarkar** [comment] 2024-01-07 07:37
Sorry, I was wrong in my original assumptions, overall stuttering is caused by another issue.
And you are right, I couldn't open VC-1 videos in any player (tried all samples from multimedia.cx).
Only internal player works :(

**Comment by dbarkar** [comment] 2024-01-08 20:57
Jellyfin AndroidTV client can successfully play VC-1 videos using `c2.mtk.avc.decoder`, I guess it's because it's using ExoPlayer.

**Comment by dbarkar** [comment] 2024-01-10 17:46
I found out the problem and fixed the issue locally.

Android defines MIME type for VC-1 video as `video/wvc1`. That's incorrect, the proper name is `video/vc1` and this is what Sony supports for `c2.mtk.vc1.decoder`.

So just replacing `video/wvc1` to `video/vc1` solves the issue.

I'd like to propose solution to search for `video/vc1` if capable codec for  `video/wvc1`. I can do everyting and post PR.
I understand that you don't want per-device hacks in the codebase, but this might affect a lot of users. 
I wonder how many vendors used official name instead Android's?..
@fritsch what do you think?

**Comment by malard** [comment] 2024-01-10 17:49
knowing Sony as I know Sony, Sony will always follow standards, and this will carry across their entire platform. Panasonic will also act in the same way. So this is more an Android bug than anything else. I would recommend we add some sort of exception code for this edge case more generally.

**Comment by fritsch** [comment] 2024-01-11 18:08
This is what I say: https://developer.android.com/reference/androidx/media3/common/MimeTypes#VIDEO_VC1()

**Comment by fritsch** [comment] 2024-01-11 18:21
Let's do it that way: https://github.com/google/ExoPlayer/blob/release-v2/library/extractor/src/main/java/com/google/android/exoplayer2/extractor/mkv/MatroskaExtractor.java#L2445

Official google exoplayer _exactly_ 100% does it like kodi does it -> file a bug with the Google People and tell them, that poor Sony could not read the simple String spec. If google's exoplayer adds a workaround for them - I will add one as well.

**Comment by malard** [comment] 2024-01-11 18:43
Google is wrong and so they should fix it  here is he RFC and IANA definition https://www.iana.org/go/rfc4425

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by fritsch** [comment] 2024-01-11 19:18
It has nothing to do with JANA definition. This is an API definition chosen for the Android API. They can do whatever they want there.

**Comment by fritsch** [comment] 2024-01-11 19:28
While I fully agree, that using WVC1 is a bad idea, especially as this is meant for the advanced profile used in windows - but hey - I did not make the android API. They want that VC-1 mediatype towards their decoder is to be identified with video/wvc1 - if we like that or not. They even have chosen video/AVC1WEROCK or video/AHVAUZEH1 if they are happy.

It's their ecosystem, they define their standard. If we like it or not, if JANA likes it or not.

**Comment by fritsch** [comment] 2024-01-11 19:51
Does this work for you? 
https://jenkins.kodi.tv/job/android-arm-docker/5158/artifact/kodi-20240111-fa37e8ab-vc1-armeabi-v7a.apk

While I am not the "fixer" for google nor JANA :P - I always hate it when making it works is just three lines of code ...

**Comment by dbarkar** [comment] 2024-01-11 20:20
> Does this work for you? https://jenkins.kodi.tv/job/android-arm-docker/5158/artifact/kodi-20240111-fa37e8ab-vc1-armeabi-v7a.apk
> 
> While I am not the "fixer" for google nor JANA :P - I always hate it when making it works is just three lines of code ...

Actually no. 
I checked your patch, please change mime type in the if clause to `video/VC1`, not `video/vc1` (sorry about that).

> While I fully agree, that using WVC1 is a bad idea, especially as this is meant for the advanced profile used in windows - but hey - I did not make the android API. They want that VC-1 mediatype towards their decoder is to be identified with video/wvc1 - if we like that or not. They even could have chosen video/AVC1WEROCK or video/AHVAUZEH1 if they are happy.
> 
> It's their ecosystem, they define their standard. If we like it or not, if JANA likes it or not.

You are absolutelty right.
I will report the issue to Sony, maybe they will fix it some day. Must be a quck fix though, just add string to the supported codecs list.

**Comment by dbarkar** [comment] 2024-01-11 20:27
> Lol IANA won't be happy ;-)

More important is that Kodi users will be happy :)

**Comment by fritsch** [comment] 2024-01-11 20:30
No ... It's not my freetime's job - to fix the TV that was sold to someone for 1000 € ...

**Comment by fritsch** [comment] 2024-01-11 20:32
https://jenkins.kodi.tv/job/android-arm-docker/5159/artifact/kodi-20240111-e554f723-vc1-armeabi-v7a.apk <- for what it's worth.

**Comment by fritsch** [comment] 2024-01-11 20:33
As it's your TV and you paid the money ... feel free to finegrain the change and come up with a PR.

**Comment by fritsch** [comment] 2024-01-11 20:34
This bug was traced down to Sony not obeying Android Standards, nor IANA standards for their implementation of the given string API.

Let me close it. We can discuss further in the PR, now that it triple proven that it is not a bug with kodi.

**Closed by fritsch** 2024-01-11 20:34 UTC
Labels: Platform: Android, Triage: Needed

**Comment by dbarkar** [comment] 2024-01-11 20:36
> https://jenkins.kodi.tv/job/android-arm-docker/5159/artifact/kodi-20240111-e554f723-vc1-armeabi-v7a.apk <- for what it's worth.

This one works!

> No ... It's not my freetime's job - to fix the TV that was sold to someone for 1000 € ...

I'm happy to do this freetime's job for you :) 
PR is on the way.

**Comment by fritsch** [comment] 2024-01-11 20:37
Hrhr. You do this in YOUR freetime for YOUR TV ;.-)

But fine - taken. Awesome.

**Comment by TheArgentinian** [comment] 2024-02-18 18:22
I'm having the same stuttering issue on an Android box. So it's not a Sony problem.

**Comment by fritsch** [comment] 2024-02-18 18:28
Not sure why you are posting here @TheArgentinian  - but the issue above was identified as a Sony Firmware issue and workarounded. So not sure what your comment should say?

There are many bad boxes out there and every day some new bad ones appear ...

**Comment by TheArgentinian** [comment] 2024-02-18 18:37
> Not sure why you are posting here @TheArgentinian - but the issue above was identified as a Sony Firmware issue and workarounded. So not sure what your comment should say?
> 
> There are many bad boxes out there and every day some new bad ones appear ...

Why bother creating a new topic when it's going to get blamed on the hardware and not bad coding?

**Comment by fritsch** [comment] 2024-02-18 19:02
I still have no idea what you want to say. The guy "making the hardware" and the guys "writing the software" are both Sony ... that Sony did not manage to implement the Android API properly is sad ... but yeah, what can users do ... nothing ... which is why the workaround was implemented.
