### ISSUE TITLE
[kodi 21][androidtv]Cant play anything after wakeup

### ISSUE THREAD

**Issue by diogosena** [xbmc/xbmc#24950] opened 2024-04-06 20:49 UTC
### Describe the bug
Using kodi on chromecast 4k, shutdown via android remote,  then turn on. Kodi will open with blue circle animation stuck, and only work after exit and reopen.

## Expected Behavior
Kodi should work normaly without the need to reopen.

## Actual Behavior

Kodi only works after reopen.

### To Reproduce

Using kodi on chromecast 4k, shutdown via android remote,  then turn on. Kodi will open with blue circle animation stuck, and only work after exit and reopen.

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/wicagojovu ,this one is a clean install without anything but kodi log uploader
https://paste.kodi.tv/wemihamima  , this one too..

https://paste.kodi.tv/wahavucape
https://paste.kodi.tv/akurecegup
https://paste.kodi.tv/qikekacica

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android TV 12
 - Kodi version: 21 stable

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment] 2024-04-07 00:37
@diogosena 

It's not a Kodi issue. It is a Jellyfin problem.

`JELLYFIN.jellyfin_kodi.views -> ERROR::jellyfin_kodi/views.py:157 Unable to retrieve libraries: ('MissingSchema', {'Id': 'None'})`

IIRC there should be an update for the Jellyfin addon. If not, you will need to notify the addon developer.

I will close this report. Feel free to post back if your findings are different.

**Comment by diogosena** [comment] 2024-04-07 02:01
It's not a jellyfin problem, just did a clean install , added only the kodi logfile uploader, and the problem persists.

https://paste.kodi.tv/wemihamima

**Comment by KarellenX** [comment] 2024-04-07 07:01
Ok, I will reopen.
I don't deal with Android, so can't see the issue. Maybe someone else will.

**Comment by diogosena** [comment] 2024-04-07 12:06
> Ok, I will reopen. I don't deal with Android, so can't see the issue. Maybe someone else will.

Seems audio related, if i press back to stop the loading animation, I can see that even the menu sounds are not working

**Comment by diogosena** [comment] 2024-04-08 19:27
Just retested all v21 versions, this bug was introduced sometime between beta2 and beta3,  beta 2 doesn't have this bug, beta 3 has it

**Comment by hugbug** [comment] 2024-04-09 10:18
The Wake-up routine isn't executed.

According to your logs the device doesn't receive ACTION_HDMI_AUDIO_PLUG event. That shouldn't be an issue because the code should be able to handle this case: 

https://github.com/xbmc/xbmc/blob/f0b18b55c5778b6428d0928ab086d0d4890c9385/xbmc/platform/android/activity/XBMCApp.cpp#L1363-L1368

The OnWakeup-routine isn't called meaning variable `m_supportsHdmiAudioPlug` is set to `true`. This variable is set when event ACTION_HDMI_AUDIO_PLUG is received for the first time. But as I said there are no messages about these events in the log, meaning the variable shouldn’t be `true` but it seems to be.

I have only one explanation for this phenomenon: one event ACTION_HDMI_AUDIO_PLUG is sent during very soon stage of app startup. At this stage the app log system isn't initialised yet. Nonetheless all messages are printed into system log and can be logged using logcat-command.

Can you please catch the logging using adb and logcat-command to verify that?

Please note that during initialisation Kodi prints all messages at Verbose log level, which might not be active on your device by default. Please activate Verbose logging for logcat first:

Globally:
`adb shell setprop persist.log.tag V`

or for Kodi only:
`adb shell setprop persist.log.tag.Kodi V`

**Comment by diogosena** [comment] 2024-04-09 17:49
> The Wake-up routine isn't executed.
> 
> According to your logs the device doesn't receive ACTION_HDMI_AUDIO_PLUG event. That shouldn't be an issue because the code should be able to handle this case:
> 
> https://github.com/xbmc/xbmc/blob/f0b18b55c5778b6428d0928ab086d0d4890c9385/xbmc/platform/android/activity/XBMCApp.cpp#L1363-L1368
> 
> The OnWakeup-routine isn't called meaning variable `m_supportsHdmiAudioPlug` is set to `true`. This variable is set when event ACTION_HDMI_AUDIO_PLUG is received for the first time. But as I said there are no messages about these events in the log, meaning the variable shouldn’t be `true` but it seems to be.
> 
> I have only one explanation for this phenomenon: one event ACTION_HDMI_AUDIO_PLUG is sent during very soon stage of app startup. At this stage the app log system isn't initialised yet. Nonetheless all messages are printed into system log and can be logged using logcat-command.
> 
> Can you please catch the logging using adb and logcat-command to verify that?
> 
> Please note that during initialisation Kodi prints all messages at Verbose log level, which might not be active on your device by default. Please activate Verbose logging for logcat first:
> 
> Globally: `adb shell setprop persist.log.tag V`
> 
> or for Kodi only: `adb shell setprop persist.log.tag.Kodi V`

this is the kodi log

https://paste.kodi.tv/imojigafis

and this is the logcat

https://paste.kodi.tv/zinafolera

**Comment by hugbug** [comment] 2024-04-09 19:57
>I have only one explanation for this phenomenon: one event ACTION_HDMI_AUDIO_PLUG is sent during very soon stage of app startup.

Confirmed from your log that is indeed the case. Thanks.

I'm working on a fix. Once I have it, it would be great if you can test it before I create a pull request. From your previous posts I conclude you can compile Kodi. If that is correct, I'll point you to a fix-commit. Alternatively I can provide you with a test build if you are not afraid of running apps built by strangers.

**Comment by diogosena** [comment] 2024-04-09 20:08
Not afraid, just point me to the build (armv7), and I'm glad to help you test.

**Comment by hugbug** [comment] 2024-04-09 22:06
Please test this build: [kodiapp-armeabi-v7a-release-hugbug-hdmi-wakeup-1.apk](https://drive.google.com/file/d/1NdJOfKEdso7NODvaA8iYGbacmW9UcH_j/view?usp=drivesdk).

Notes: this build uses a different package id and will not overwrite/update your existing Kodi installation. The build is based on current master (v22). App name is changed to "Kodi (hugbug)" (but the icon is the default one).

**Comment by diogosena** [comment] 2024-04-09 22:21
That's was fast and it worked great, thanks for the fix!

**Comment by LeonZawodowiec123** [comment] 2024-04-11 09:04
I have the same problem on Mi box 4k, I described it here
https://forum.kodi.tv/showthread.php?tid=376989&page=3

**Comment by diogosena** [comment] 2024-04-11 12:31
> I have the same problem on Mi box 4k, I described it here https://forum.kodi.tv/showthread.php?tid=376989&page=3

it's already fixed, try the test version provided in the comment above yours.

**Comment by LeonZawodowiec123** [comment] 2024-04-11 18:26
ok I saw it, thanks

**Closed** 2024-04-12 14:47 UTC
Labels: Platform: Android, Triage: Needed, v21 Omega

**Comment by adiepev** [comment] 2024-05-06 18:54
When will the fix be implemented in a new version for official distribution?

**Comment by sfransen** [comment] 2024-08-05 19:14
this happens on the Nvidia shield also when will this patch make it to release?

**Comment by garbear** [comment] 2024-08-06 07:08
@sfransen The fix was backported in https://github.com/xbmc/xbmc/pull/24993 and will be in the upcoming v21.1 release.

**Comment by Xmetalfanx** [comment] 2024-10-23 18:29
hate to hijack this but i am still (for daily use on 19.5 but i am trying to fix/help pinpoint an issue i have had since 20.x and on 21.x too now) am troubleshooting and i wonder if this has to do with https://github.com/xbmc/xbmc/issues/19539 (i am not the OP of the issue) ... where say i am selecting music .. then i shut the TV off (audio still playing through android tv box bt out or 3.5mm to speakers... i then turn the TV back on and try to play anything else ... it is like it loops through not being able to find the media ... (BY THE WAY, I know this is another thread and am not asking here just saying this MAY BE related?)  ... if i close the Kodi process and restart it i can play the other media i was trying to play but if i shut the tv off and do it all again, the problem happens again.

SAME exact media and drives and whatnot (local media in all cases btw) .. .no issue with any Kodi i have tried in the 18.x or 19.x range
