### ISSUE TITLE
Kodi 20 freezing when accessing folders or addon page with non English characters

### ISSUE THREAD

**Issue by steph09** [xbmc/xbmc#22565] opened 2023-01-23 12:21 UTC
### Describe the bug
I installed Kodi 20 on my Windows 10 PC when it was released & everything seemed to be working OK. However I noticed that when trying to access a folder, Browse a Youtube channel or some other addon page that included a file with odd characters in the filename (Which usually displayed as square boxes on Kodi 19) it immediately causes Kodi to freeze.

I was using the xonfluence skin initially but experienced the same thing on several other skins which I have tried although at times more severe as it would freeze with just Japanese or Korean characters in filenames/video titles.

The issue isn't present when using Estuary with the default font however Kanji & other asian text is displayed as boxes & upon changing the font to 'Arial Based' Estuary then also starts causing freezes when trying to access folders/addon pages that feature non western characters in filenames/video titles.

## Expected Behavior
It should load the file lists without issue, Usually displaying non supported characters with boxes or not at all.

## Actual Behavior
It crashes.

### To Reproduce
The title of this Youtube video is one that causes it.
https://youtu.be/n15z5sRskxE

### Debuglog
https://paste.kodi.tv/cazacecozo.kodi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 Pro
 - Kodi version: 20

**Comment by scott967** [comment] 2023-01-23 23:50
Thank you for submitting your issue.  I have reproduced the issue on Windows x64 desktop
Preliminary testing was done with this environment:
1. Added a Kodi video source with filename containing unicode emoji and cjk characters as well as filename with unicode emoji without cjk characters.
2. In Kodi navigated to videos file node and attempted to list the files

I tested with both default Estuary font noto sans-regular and option font arial.  In noto sans-regular Kodi navigated the file list with expected "no glyph" box for emojis and cjk characters.  I then switched to optional font "arial based" (arial.ttf) and Kodi UI locked up when attempting to display the filename with emoji and cjk.  I also tested with my skin (using a font I created) and also experienced the UI freeze/lockup.

I don't know that this is the minimal filename string but it does reproduce the issue.  I provide detailed list as I'm not sure how github editor/browser might adjust text strings.
View in 3 cols: codepoint / rendered char/ utf-8 encoding

U+C591  양  EC 96 91
U+C9C0  지 EC A7 80
U+C740  은  EC 9D 80
U+1F33C  🌼  F0 9F 8C BC
U+B098  나  EB 82 98
U+B3C4 도 EB 8F 84
U+0020   
U+D55C 한 ED 95 9C
U+C794 잔 EC 9E 94
U+1F33C 🌼 F0 9F 8C BC
U+ADF8 그 EA B7 B8
U+0020   
U+C815 정 EC A0 95
U+0020   
U+B54C 때 EB 95 8C
U+BB38 문 EB AC B8
U+C5D0 에 EC 97 90
U+0020   
U+1F6D1 🛑 F0 9F 9B 91
U+C5F0 연 EC 97 B0
U+C18D 속 EC 86 8D
U+0033 33
U+BC88 번 EB B2 88
U+0020

**Comment by sarbes** [comment] 2023-01-28 11:30
Please define freezing.

**Comment by steph09** [comment] 2023-01-28 11:53
Basically as soon as I enter a folder or addon page which has a video name/title featuring emoji and/or weirdly formatted text Kodi just stops responding and has to be closed via task manager.

It doesn't crash as in automatically close or bring up the Windows 'Program is not responding' box, Kodi just hangs & the only way to close it is to end task via task manager.

With the default Estuary skin & font it's fine but if you switch the font to 'Arial based' or use another skin that features a font that can display asian text Kodi stops responding.

**Comment by zketas** [comment] 2023-01-28 13:32
maybe same as https://github.com/xbmc/xbmc/issues/22473

**Comment by scott967** [comment] 2023-01-28 19:22
Freezing means UI does not update and input from keyboard or mouse events is not accepted.

**Comment by steph09** [comment] 2023-01-28 23:36
I made a gif showing what happens.
https://i.imgur.com/VplcEDl.gif

You can see that as soon as I click on the folder Kodi just freezes (The memory counter in the log & Twitch notification scroll show when it freezes).

Thats with a file with the same video title as the youtube video I linked to in the initial post.

**Comment by darksol736** [comment] 2023-01-31 07:18
My PR #22648 above likely addresses the same root cause.

**Comment by thexai** [comment] 2023-02-01 10:26
Fixed by https://github.com/xbmc/xbmc/pull/22658

**Closed by thexai** 2023-02-01 10:26 UTC
