### ISSUE TITLE
Kodi 19 Beta 1 show green screen when play a .mkv file

### ISSUE THREAD

**Issue by tngan0531** [xbmc/xbmc#18902] opened 2020-12-05 17:24 UTC
[cut.zip](https://github.com/xbmc/xbmc/files/5696072/cut.zip)

### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi 19 Beta-1, When play one type of mkv file which codec is MPEG-H Part 2/HEVC (H.265), It will only a green screen, Audio is playing ok.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The same file is playing normally in Kodi v18.6 and VLC

## Actual Behavior

When play the video file, it show as green screen

## Possible Fix

Nil

### To Reproduce

1. Play the file
2.
3.

### Debuglog

The debuglog can be found here:
https://surbanajurong-my.sharepoint.com/:u:/g/personal/terence_ngan_bharchitects_com/EdouKUcd7DJMt6ud6ohHDE0BzkZEGlgoahn0EKX7GIgpGQ?e=rLVy72

### Screenshots 
Here are some links or screenshots to help explain the problem:

![image](https://user-images.githubusercontent.com/75537724/101258668-1bb89800-36f2-11eb-8a82-74d3891f2a1c.png)
![image](https://user-images.githubusercontent.com/75537724/101258678-2bd07780-36f2-11eb-8250-0a8ff0335c30.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: v19 Beta 1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment] 2020-12-14 05:26
Could you please provide a snipped from that video you are trying to play? Our windows devs might need a sample to reproduce

**Comment by tngan0531** [comment] 2020-12-15 02:12
Hi DaVukovic,
I don't know how to provide a snipped from the video file. Could you give me some instruction on how to make it. It is .mkv file.
Best Regards,
Terence Ngan
 

    On Monday, December 14, 2020, 12:27:09 a.m. EST, DaVukovic <notifications@github.com> wrote:  
 
 


Could you please provide a snipped from that video you are trying to play? Our windows devs might need a sample to reproduce

**Comment by tngan0531** [comment] 2020-12-15 02:47
Hi DaVukovic,
I found a way to cut a snip from the video file. I am using avidemuxplease found the attached cut.mkv


Best Regards,
Terence Ngan
 

    On Monday, December 14, 2020, 9:12:24 p.m. EST, terence_ngan@yahoo.com <terence_ngan@yahoo.com> wrote:  
 
 Hi DaVukovic,
I don't know how to provide a snipped from the video file. Could you give me some instruction on how to make it. It is .mkv file.
Best Regards,
Terence Ngan
 

    On Monday, December 14, 2020, 12:27:09 a.m. EST, DaVukovic <notifications@github.com> wrote:  
 
 


Could you please provide a snipped from that video you are trying to play? Our windows devs might need a sample to reproduce

**Comment by enen92** [comment] 2020-12-15 11:07
@tngan0531 I don't think attaching the file to the email will work. Can you please use the GitHub web Ui to attach the file? https://github.com/xbmc/xbmc/issues/18902

**Comment by tngan0531** [comment] 2020-12-15 13:15
[cut.zip](https://github.com/xbmc/xbmc/files/5696088/cut.zip)
Here is the file

**Comment by fritsch** [comment] 2020-12-16 17:19
It should work if you disable DXVA in Video Player settings, right?

**Comment by tngan0531** [comment] 2020-12-17 03:13
No. Disable DXVA in Video Player still show the green screen when play this video file.Other video file is fine.

Best Regards,
Terence Ngan
 

    On Wednesday, December 16, 2020, 12:20:04 p.m. EST, Peter Frühberger <notifications@github.com> wrote:  
 
 


It should work if you disable DXVA in Video Player settings, right?

**Comment by fritsch** [comment] 2020-12-17 06:40
Okay, then we wait forn the windows devs. Your file is 10 bit hevc, works nicely on my linux setup, therefore cannot help much.

**Comment by thexai** [comment] 2020-12-23 11:00
`2020-12-05 12:14:42.603 T:7276     INFO <general>: DX::DeviceResources::CreateDeviceResources: device is created on adapter 'Intel(R) HD Graphics' with D3D_FEATURE_LEVEL_9_1`

This indicates very old or unsupported video driver. On Windows 10 DX feature level should be 11.x - 12.x

Try update Intel video driver.

Also this driver does not support DXVA HEVC decoding (HW):

```
2020-12-05 12:15:09.319 T:2200    DEBUG <general>: DXVA: open decoder.
2020-12-05 12:15:09.319 T:2200  WARNING <general>: DXVA::CContext::CreateContext: using app d3d11 device for decoding due extended NV12 shared textures it's not supported.
2020-12-05 12:15:09.319 T:2200    DEBUG <general>: DXVA: supports 'MPEG2 variable-length decoder'
2020-12-05 12:15:09.319 T:2200    DEBUG <general>: DXVA: supports 'MPEG2 inverse discrete cosine transform'
2020-12-05 12:15:09.319 T:2200    DEBUG <general>: DXVA: supports 'MPEG2 motion compensation'
2020-12-05 12:15:09.319 T:2200    DEBUG <general>: DXVA: supports 'VC-1 variable-length decoder (Intel)'
2020-12-05 12:15:09.319 T:2200    DEBUG <general>: DXVA: supports 'H.264 variable-length decoder, no film grain technology (Intel ClearVideo)'
2020-12-05 12:15:09.319 T:2200    DEBUG <general>: DXVA: supports A74CCAE2-f466-45ae-86f5-ab8be8af8483
2020-12-05 12:15:09.319 T:2200    DEBUG <general>: DXVA: supports 'Windows Media Video 9 motion compensation'
2020-12-05 12:15:09.319 T:2200    DEBUG <general>: DXVA: supports 'Windows Media Video 9 inverse discrete cosine transform'
2020-12-05 12:15:09.319 T:2200    DEBUG <general>: DXVA: supports 'VC-1 motion compensation'
2020-12-05 12:15:09.319 T:2200    DEBUG <general>: DXVA: supports 'VC-1 inverse discrete cosine transform'
2020-12-05 12:15:09.319 T:2200    DEBUG <general>: DXVA: supports 'H.264 motion compensation, no film grain technology (Intel)'
2020-12-05 12:15:09.319 T:2200    DEBUG <general>: DXVA: supports 'H.264 inverse discrete cosine transform, no film grain technology (Intel)'
2020-12-05 12:15:09.319 T:2200    DEBUG <general>: DXVA: unable to find an input/output format combination.
2020-12-05 12:15:09.319 T:2200    DEBUG <general>: DXVA::CDecoder::~CDecoder: destructing decoder, 0x2324a756290.
2020-12-05 12:15:09.319 T:2200     INFO <general>: DXVA::CDecoder::Close: closing decoder.
```

**Comment by Sopor** [comment] 2021-02-20 16:45
Kodi 19 FINAL:
I also get a green screen in the DVD menu of almost all ISO files i try to play.

![image](https://user-images.githubusercontent.com/5789283/108602597-0541e480-73a3-11eb-8509-78c70465dc68.png)

The line you see in the picture is the selected option, so that moves when pressing on the remote, but i have to guess what i press on.

**Comment by DaVukovic** [comment] 2021-02-21 12:53
@Sopor 

Great. I'm not sure if this bug report is related to your problem. Your "DVD" ISO won't contain a HEVC file and is also not a MKV. 

Please consider to open your own bug and provide a log file or do what @thexai mentioned above. 

In any way a "me too" won't help anyone if a log is missing

**Comment by overtheedge** [comment] 2021-03-05 23:17
I am having the same problem as the original reporter, and I think we might have the same older Intel graphics processor (the gen 5 Intel HD Graphics from 2010). Every h.264/hevc file produces a green screen in 19.0. Plays fine in 18.9. Here's my debug log: https://paste.kodi.tv/begehugafe.kodi

@thexai you'll find the same D3D_FEATURE_LEVEL_9_1 and the same list of DXVA support. h.265 hw decoding is obviously not supported by this chip, but it always played back fine in earlier versions of Kodi/XBMC.

**Comment by thexai** [comment] 2021-03-06 12:11
> I am having the same problem as the original reporter

> Every h.264/hevc file produces a green screen in 19.0.

Original reporter only has issues with 10-bit videos. It's your issue is with "all videos" maybe is another ting.

The point is that these chips are discontinued (by Intel) and there are no compatible drivers for Windows 10.

**Comment by overtheedge** [comment] 2021-03-06 17:04
> > I am having the same problem as the original reporter
> 
> 
> 
> > Every h.264/hevc file produces a green screen in 19.0.
> 
> 
> 
> Original reporter only has issues with 10-bit videos. It's your issue is with "all videos" maybe is another thing.
> 
> 
> 
> The point is that these chips are discontinued (by Intel) and there are no compatible drivers for Windows 10.
> 
> 
> 
> 
Oops I mistyped h.264 in my original comment. I meant h.265. H.264 plays fine so it isn't "all videos", it's "all hevc videos". Since they play fine in 18.9 and earlier and only don't play in 19.0, why do you say it is a driver limitation? Is it because 19.0 now requires driver features which 18.9 did not? If so I guess 18.9 is the end of the road for this media player.

**Comment by overtheedge** [comment] 2021-03-06 17:12
> > I am having the same problem as the original reporter
> 
> 
> 
> > Every h.264/hevc file produces a green screen in 19.0.
> 
> 
> 
> Original reporter only has issues with 10-bit videos. It's your issue is with "all videos" maybe is another thing.
> 
> 
> 
> The point is that these chips are discontinued (by Intel) and there are no compatible drivers for Windows 10.
> 
> 
> 
> 
Oh also, the original reporter said it affects hevc/x.265. I didn't see any mention that it was limited to 10-bit. His example file was 10-bit though. FWIW, VLC also has no trouble playing these files.

**Comment by thexai** [comment] 2021-03-06 18:18
> If so I guess 18.9 is the end of the road for this media player.

Yep, is the end (for you).

> "all hevc videos"

No, all hevc **10-bit** videos

**Comment by DaVukovic** [comment] 2021-03-06 22:07
@thexai can you please elaborate more?

Why does a modern video file (like h265 10bit) works fine with an older software usiing old hardware driven by an old driver but doesn't work with newer software using the same old GPU and the same driver? Where's the driver limitation of only the player software has changed and other players are working fine (obviously)

I'm not saying you are wrong. Just confused and if you know the solution it would be nice to have a bit mor of explanation,  if possible.

Thanks

**Comment by overtheedge** [comment] 2021-03-07 01:23
> > If so I guess 18.9 is the end of the road for this media player.
> 
> Yep, is the end (for you).
> 
> > "all hevc videos"
> 
> No, all hevc **10-bit** videos

For me it is all hevc - 10 bit or not. I don't think the original reporter said it was limited to 10 bit for him either, but his example file was 10 bit.

**Comment by FernetMenta** [comment] 2021-03-07 08:31
If you look for a decoder issue, you dig in the wrong place. In general a green screen indicates a rendering problem. 

```
2021-03-05 13:41:30.443 T:5560    ERROR <general>: CD3DTexture::Create: unsupported texture format 56
```

Looks like renderer lacks to detect capabilities and as a result misses conversion of a 10 bit image to some supported format. Obviously a regression in Windows video rendering.

**Comment by thexai** [comment] 2021-03-07 09:27
More info here:
https://forum.kodi.tv/showthread.php?tid=359422&pid=2999002#pid2999002

Seems this "issue" is already present in very early v19 Alphas  `20190418-10ac461b`

So the regression has nothing to do with any of my commits...

Just to be clear: 
I am not willing to spend my time solving this because I am not interested and I think it does not contribute anything.
Users interested in 10-bit video, HDR, etc. they are also interested in using more modern (and well supported) HW.

**Comment by overtheedge** [comment] 2021-03-07 19:29
> Just to be clear:
> I am not willing to spend my time solving this because I am not interested and I think it does not contribute anything.
> Users interested in 10-bit video, HDR, etc. they are also interested in using more modern (and well supported) HW.

I disagree that it does not contribute anything. A lot of video is being encoded 10-bit these days, and people with older hardware would like to be able to play it even if they don't have a modern HDR setup. I for one would be very grateful for a fix and I suspect others with older hardware would as well. I understand this is not your problem and I'm certainly not asking you to spend time solving something you aren't interested in. I do think it contributes something though.

**Comment by overtheedge** [comment] 2021-03-07 20:00
I want to correct myself, per my edit above. I was incorrect in saying this affects "all hevc files". It indeed only affect 10-bit encodes.

**Comment by thexai** [comment] 2021-03-07 21:40
Just to have more context.

Kodi already works fine on (very) old HW: 

VitualBox Windows 7 x64 with basic VGA driver (128 MB video ram). DX profile level 9.3...... Playing 4K HDR 10-bit HEVC source..... with tone mapping enabled (Hable algorithm). Perfect picture.....

![Captura de pantalla 2021-03-07 222610](https://user-images.githubusercontent.com/58434170/110255700-594ceb80-7f95-11eb-8c59-f31ace5ecc18.png)

Does it really have to work perfect even in more older systems?    forever.... Kodi 20....21...22  why not on XP?

**Comment by thexai** [comment] 2021-03-07 22:00
And I am wondering. People who have this kind of problem tried to install an Intel driver? even if it's old?

https://downloadcenter.intel.com/download/24970/Intel-Graphics-Driver-for-Windows-15-28-

https://downloadcenter.intel.com/download/24970/Intel-Graphics-Driver-for-Windows-15-28-

**Comment by overtheedge** [comment] 2021-03-07 22:13
> And I am wondering. People who have this kind of problem tried to install an Intel driver? even if it's old?
> 
> https://downloadcenter.intel.com/download/24970/Intel-Graphics-Driver-for-Windows-15-28-

I don't think the Intel driver works in Win10. I used to use that driver package in the Win8 days because it has more features than the Microsoft driver, but I think it didn't work after I upgraded. It was a while back though so my memory is a little fuzzy.

**Comment by thexai** [comment] 2021-03-27 09:37
@tngan0531 , @overtheedge

Try this build to confirm if issue it's fixed:
https://www.mediafire.com/file/z3jo7xjs42tjlvi/KodiSetup-20210327-e8fc8194-Matrix-x64.exe/file

**Comment by overtheedge** [comment] 2021-03-28 02:00
Thank you so much @thexai for working on this! (Let me know if there is a tip jar somewhere.) I can confirm that I no longer get a green screen. Unfortunately, now I get a black (blank) screen. :-(

Here's the debug log: https://paste.kodi.tv/exayoxiyij.kodi

And here's an 18.9 debug log where it plays fine: https://paste.kodi.tv/owacoqawat.kodi

Let me know if there's any more information I can provide you. Thank you again.

**Comment by thexai** [comment] 2021-03-28 11:33
```
2021-03-27 18:47:21.937 T:9468  WARNING <general>: CRendererShaders::GetWeight: Texture format DXGI_FORMAT_R16_UNORM is not supported.
2021-03-27 18:47:21.937 T:9468  WARNING <general>: CRendererDXVA::GetWeight: Texture format 104 is not supported.
```

The problem is that your DirectX FL 9.1 systems do not seem to support the  DXGI_FORMAT_P010 (104) format either.

https://docs.microsoft.com/en-us/windows/win32/direct3ddxgi/format-support-for-direct3d-feature-level-9-1-hardware#dxgi_format_p010v-104

In my DirectX FL 9.1 test system it does support it and with the patch it goes from green screen => correct picture.

Right now I have no more ideas. More research is needed...

**Comment by thexai** [comment] 2021-03-29 11:59
This one should fix black screen when render method Software is used:

https://www.mediafire.com/file/5j7v8z792871b1y/KodiSetup-20210329-d7f8d39c-Matrix-x64.exe/file

**Comment by jgnagy-fs** [comment] 2021-03-30 01:01
I can confirm that the problem is fixed with that build. My 10-bit h265 files play perfectly. Thank you!!!

**Comment by overtheedge** [comment] 2021-03-30 01:03
I can confirm that the problem is fixed with that build. My 10-bit h265 files play perfectly. Thank you!!!

**Closed** 2021-03-30 17:18 UTC
Labels: Component: Video, Platform: Windows, v19 Matrix
