### ISSUE TITLE
Kodi does not play blu-ray discs

### ISSUE THREAD

**Issue by glaubersm** [xbmc/xbmc#15848] opened 2019-03-30 23:01 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi plays DVDs and audio CDs but it does not blu-ray video discs.
VLC player 3.0.6 installed on the same system plays the same blu-ray discs as expected.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi plays blu-ray video discs.

## Actual Behavior

Kodi does not play blu-ray video discs.
Nothing happens when I click "Play disc" button.

### To Reproduce

1. insert a blu-ray video disc
2. open Kodi and click "Disc" in the left side
3. click "Play disc" button

### Debuglog

The debuglog can be found here:
[kodi.log](https://github.com/xbmc/xbmc/files/3026034/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Arch Linux
 - Kodi version: 18.1 (both flatpak and distribution packages)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment] 2019-03-31 06:16
Your debuglog has been modified and required information is now missing. Please provide a **FULL** debug log which captures your issue.

Are you aware Kodi cannot play encrypted Blurays as it requires proprietary and paid software. If you are attempting to play an official movie release Bluray, then it will not play.

**Comment by DaVukovic** [comment] 2019-03-31 09:07
@glaubersm 

please have a read here: https://www.howtogeek.com/240487/how-to-play-dvds-and-blu-rays-on-linux/

Some BluRay will work with linux using the steps above. Some will not. Those which don't work in Kodi won't work for me using VLC as well (I tried a few now). If you still claim that discs will play in VLC but not in Kodi using the steps in the link mentioned above, then simply use VLC as an external player and you should be fine. 

Native Bluray disc playback is still an experimental feature. 

Also be aware that Kodi seems to have problems if 2 optical drives are built in into your machine (at least for me). So I simply disconnected one under Ubuntu here. 

Still, I guess that's a discussion which should be continued on the forums as BD playback under linux is, was and will be always kind of a PITA.

**Comment by glaubersm** [comment] 2019-04-02 22:13
My disc is not encrypted. Previous versions of Kodi played the same disc on linux as expected.
My computer has only one optical device. I use Arch Linux, not Ubuntu.
Instructions for my system in the following link:
https://wiki.archlinux.org/index.php/Blu-ray

Libbluray and libaacs packages are installed here and  I have KEYDB.cfg file on my system.

**Comment by DaVukovic** [comment] 2019-04-03 11:39
well...

```
2019-03-30 22:18:15.452 T:140221827159808    INFO: CD-ROM with unknown filesystem
2019-03-30 22:18:15.452 T:140221827159808    INFO: Tracks overall:1; Audio tracks:0; Data tracks:1
2019-03-30 22:18:15.452 T:140221827159808    INFO: Using protocol D:\
2019-03-30 22:18:15.452 T:140221827159808 WARNING: Filesystem is not supported
```

Is that a bought disc or something self-authored? 

get me `lsscsi | pastebinit` please

**Comment by glaubersm** [comment] 2019-04-03 12:10
I downloaded a BMDV folder and burned it on a blu-ray disc.

https://pastebin.com/yZa8TJHA

**Comment by DaVukovic** [comment] 2019-04-03 18:16
Well, I can't say what's wrong on your side. 

This is a log where I just played a BD I rented today: http://paste.ubuntu.com/p/J8J7h29bYC/

Starting at line 2434. 

So I would suggest to seek assistance at the forums as I can't reproduce your problem with a native (in meaning 'not self burned') disc. Maybe you did something wrong while authoring the BD structure and VLC simply plays the file instead of the complete structure. I guess if you browse the BD using Kodis filemanager you are able to play the specific file as well. 

Anyway, I'll close this one for now and please open a thread at forums.

Thanks

**Closed by DaVukovic** 2019-04-03 18:16 UTC
Labels: Ignored rules, Platform: Linux, v18 Leia

**Comment by fr4nk3n5731n** [comment] 2019-04-29 14:12
@glaubersm hey man, just had the same issue as you. For me the problem was that I didn't have  [`udisks2`](https://www.archlinux.org/packages/extra/x86_64/udisks2/) installed (for automatically mounting optical media and stuff). I found out that you have to have the disk mounted in order to play it with kodi, so installing udisks, letting udisks mount the disk allowed kodi to play BluRays directly without the need for VLC.
Also while we are at it make sure you have the `sg` module loaded (`/etc/modules-load.d/sg.conf` with `sg` as content to automatically load the module) and or run `modprobe sg`.
Also also you can install [`makemkv-cli`](https://aur.archlinux.org/packages/makemkv-cli/) and use it instead of `libaacs` and `libbdplus`
```Bash
sudo ln -s /usr/lib/libmmbd.so.0 /usr/lib/libaacs.so.0
sudo ln -s /usr/lib/libmmbd.so.0 /usr/lib/libbdplus.so.0 
```
Hope that helps you and solves your problem.

**Comment by glaubersm** [comment] 2019-04-29 14:46
udisks2 is already installed here.
My system does not mount optical discs automatically when they are inserted,
now I can play blu-ray disc with kodi 18.2 if I mount the disc (via Dolphin file manager)
befeore start Kodi. Weirdly I can play dvd with Kodi even if such disc is unmounted
while I start Kodi. VLC 3.0.6 can play blu-ray disc even if it is unmounted.
Kodi should play blu-ray disc even if it is unmounted like VLC or hide "Disc" entry in the side bar
when the disc can not be played back because it is not mounted.

Thank you very much for your post @fr4nk3n5731n.

**Comment by slynobody** [comment] 2023-03-24 20:00
'play disc' does *not* work with bluray-discs, if you have udisk2 installed or not, mounted though kodi-standalone, through os, with different fstab-configs etc.

you have to go to the file browser, open the bd then navigate to the bdmv-folder. 
Why cant you simply add this to the 'play disc' button.
This seems to be no rocket-science but some minor bug.

**Comment by enen92** [comment] 2023-03-24 23:47
@slynobody if it is no rocket science it should be easy enough for you to submit a pr.
