### ISSUE TITLE
Atmos dropouts when playing 4K MKV at 23.98Hz but not 59.94Hz on Windows

### ISSUE THREAD

**Issue by 78andyp** [xbmc/xbmc#22531] opened 2023-01-20 20:33 UTC
## Bug report

Playing a 4K MKV file has audible audio dropouts about every 8 seconds when played at 23.98Hz but not when played at 59.94Hz with 3:2 pulldown. I alter the whitelist to control the screen resolution/refresh rate.

This has happened all the way through Kodi 20 alpha/beta/RC and now with Kodi 21 alpha with the latest audio fixes.

I've tried several files MKV and UHD ISO. I've tried network and local. I've tried various buffer settings in advancedsettings.xml.

### Describe the bug
Here is a clear and concise description of what the problem is:

As above

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

No audio dropouts.

## Actual Behavior

Dropouts as above.

### To Reproduce

1. Allow 3840x2160 @ 23.98Hz in whitelist
2. Play MKV
3. Audio dropout about evey 8 seconds

### Debuglog

The debuglog can be found here:

Debuglog at 23.98Hz - https://filebin.net/paoveengazyso6iy
Debuglog at 59.94Hz - https://filebin.net/rhjtjs7rs7zuz8wm

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ X ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 11
 - Kodi version: 20 and 21

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by thexai** [comment] 2023-01-21 17:40
Tested on a similar system:

Windows 11 22H2 (i7-13700k) + NVIDIA RTX 2060 + Denon X1600H + Sony AG9

Settings / Player / Switch display refresh rate at Start/Stop  (23.98 Hz)
Passthrough enabled  (Denon displays ATMOS)

NVIDIA driver: `528.02-desktop-win10-win11-64bit-international-dch-whql.exe`

I can not reproduce any audio dropout.

**Comment by 78andyp** [comment] 2023-02-02 14:34
Hi
Thanks. Apologies for delay in replying.
For completeness I've just reinstalled windows 11 from scratch, updated, installed most up to date nvidia driver and intel chipset drivers and kodi (lastest master build).
No change.

File info:
General
Unique ID                                : 193062987578266127748406505483114709108 (0x913E943254A3BFA28A91F2B9ABDD0074)
Complete name                            : \\mediamaster\media\My UHD Blu-Rays\Resident Evil Welcome to Raccoon City (2021)\MKV\Resident Evil- Welcome to Raccoon City-FPL_MainFeature_t00.mkv
Format                                   : Matroska
Format version                           : Version 2
File size                                : 46.3 GiB
Duration                                 : 1 h 47 min
Overall bit rate mode                    : Variable
Overall bit rate                         : 61.7 Mb/s
Movie name                               : Resident Evil: Welcome to Raccoon City
Encoded date                             : UTC 2022-04-04 19:07:24
Writing application                      : MakeMKV v1.16.7 win(x64-release)
Writing library                          : libmakemkv v1.16.7 (1.3.10/1.5.2) win(x64-release)

Video
ID                                       : 1
ID in the original source medium         : 4113 (0x1011)
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L5.1@High
HDR format                               : Dolby Vision, Version 1.0, dvhe.07.06, BL+EL+RPU, Blu-ray compatible / SMPTE ST 2086, HDR10 compatible
Codec ID                                 : V_MPEGH/ISO/HEVC
Duration                                 : 1 h 47 min
Bit rate                                 : 52.7 Mb/s
Width                                    : 3 840 pixels
Height                                   : 2 160 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0 (Type 2)
Bit depth                                : 10 bits
Bits/(Pixel*Frame)                       : 0.265
Stream size                              : 39.6 GiB (86%)
Language                                 : English
Default                                  : No
Forced                                   : No
Color range                              : Limited
Color primaries                          : BT.2020
Transfer characteristics                 : PQ
Matrix coefficients                      : BT.2020 non-constant
Mastering display color primaries        : Display P3
Mastering display luminance              : min: 0.0001 cd/m2, max: 1000 cd/m2
Maximum Content Light Level              : 748 cd/m2
Maximum Frame-Average Light Level        : 241 cd/m2
Original source medium                   : Blu-ray

Audio #1
ID                                       : 2
ID in the original source medium         : 4352 (0x1100)
Format                                   : MLP FBA 16-ch
Format/Info                              : Meridian Lossless Packing FBA with 16-channel presentation
Commercial name                          : Dolby TrueHD with Dolby Atmos
Codec ID                                 : A_TRUEHD
Duration                                 : 1 h 47 min
Bit rate mode                            : Variable
Bit rate                                 : 4 487 kb/s
Maximum bit rate                         : 8 118 kb/s
Channel(s)                               : 8 channels
Channel layout                           : L R C LFE Ls Rs Lb Rb
Sampling rate                            : 48.0 kHz
Frame rate                               : 1 200.000 FPS (40 SPF)
Bit depth                                : 24 bits
Compression mode                         : Lossless
Stream size                              : 3.37 GiB (7%)
Title                                    : Surround 7.1
Language                                 : English
Default                                  : Yes
Forced                                   : No
Original source medium                   : Blu-ray
Number of dynamic objects                : 11
Bed channel count                        : 1 channel
Bed channel configuration                : LFE

Audio #2
ID                                       : 3
ID in the original source medium         : 4352 (0x1100)
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Commercial name                          : Dolby Digital
Codec ID                                 : A_AC3
Duration                                 : 1 h 47 min
Bit rate mode                            : Constant
Bit rate                                 : 640 kb/s
Channel(s)                               : 6 channels
Channel layout                           : L R C LFE Ls Rs
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Compression mode                         : Lossy
Stream size                              : 492 MiB (1%)
Title                                    : Surround 5.1
Language                                 : English
Service kind                             : Complete Main
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Audio #3
ID                                       : 4
ID in the original source medium         : 4353 (0x1101)
Format                                   : DTS XLL
Format/Info                              : Digital Theater Systems
Commercial name                          : DTS-HD Master Audio
Codec ID                                 : A_DTS
Duration                                 : 1 h 47 min
Bit rate mode                            : Variable
Bit rate                                 : 2 283 kb/s
Channel(s)                               : 6 channels
Channel layout                           : C L R Ls Rs LFE
Sampling rate                            : 48.0 kHz
Frame rate                               : 93.750 FPS (512 SPF)
Bit depth                                : 16 bits
Compression mode                         : Lossless
Stream size                              : 1.71 GiB (4%)
Title                                    : Surround 5.1
Language                                 : English
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Audio #4
ID                                       : 5
ID in the original source medium         : 4353 (0x1101)
Format                                   : DTS
Format/Info                              : Digital Theater Systems
Codec ID                                 : A_DTS
Duration                                 : 1 h 47 min
Bit rate mode                            : Constant
Bit rate                                 : 1 509 kb/s
Channel(s)                               : 6 channels
Channel layout                           : C L R Ls Rs LFE
Sampling rate                            : 48.0 kHz
Frame rate                               : 93.750 FPS (512 SPF)
Bit depth                                : 16 bits
Compression mode                         : Lossy
Stream size                              : 1.13 GiB (2%)
Title                                    : Surround 5.1
Language                                 : English
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

**Comment by thexai** [comment] 2023-06-09 16:57
We are unable to reproduce this on any other Windows systems and no other users appear to be affected either.

During this time the NVIDIA drivers have changed and a TrueHD rework has been done that basically solves problems on Android but the changes affect all platforms: https://github.com/xbmc/xbmc/pull/22705

In any case this seems to be a very specific issue of this system. I'm going to close the issue and if the problem persists please use the forum for support.

Take into account that the causes can be multiple: for example a driver or any other process can generate latency problems and cause too many interrupts to the processor (or too long interrupts). See LatencyMon (https://www.resplendence.com/latencymon) which can help to troubleshoot this.  But the root cause could also be anywhere else: AVR, TV, etc.

**Closed by thexai** 2023-06-09 16:57 UTC
Labels: Platform: Windows, Triage: Needed, v20 Nexus, Triage: Tested and not reproduced, v21 Omega
