### ISSUE TITLE
No video on live TV when PRIME DRM HW is enabled

### ISSUE THREAD

**Issue by Salokyn** [xbmc/xbmc#23222] opened 2023-05-01 12:18 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:
With Kodi 20 (Libreelec 11) on RaspberryPi 4,
With TVHeadend 4.2 plugin installed and configured,
With DRM PRIME HW decoding activated,
Playing live DVB TV (h264, 50p) give a black or frozen image while sound plays.

## Possible Fix
It works fine when DRM PRIME HW decoding is deactivated.
It used to work fine on Kodi 18 (Libreelec 9)
It seems to be a buffer issue according to the logs.

### Debuglog
The debuglog can be found here:

http://ix.io/4ugC

I made 3 plays:  
* 18:43:29
* 18:43:58
* 18:45:10

Most relent errors:

```
2023-04-25 18:45:14.528 T:3317    debug <general>: CVideoPlayer::CheckContinuity - update correction: 1847644.000000
2023-04-25 18:45:14.576 T:3324    error <general>: CDVDVideoCodecDRMPRIME::AddData - send packet failed: End of file (-541478725)
2023-04-25 18:45:14.739 T:1462     info <general>: Skipped 14 duplicate messages..
2023-04-25 18:45:14.739 T:1462    debug <general>: ActiveAE::SyncStream - average error 0.896288 below threshold of 30.000000
2023-04-25 18:45:14.752 T:3324    error <general>: CDVDVideoCodecDRMPRIME::AddData - send packet failed: End of file (-541478725)
2023-04-25 18:45:19.321 T:3317     info <general>: Skipped 226 duplicate messages..
2023-04-25 18:45:19.321 T:3317    debug <general>: CDVDClock::SetSpeedAdjust - adjusted:0.000000
2023-04-25 18:45:19.321 T:3324    error <general>: CDVDVideoCodecDRMPRIME::AddData - send packet failed: End of file (-541478725)
```

### Screenshots

https://youtu.be/AFPYZFAmRJc

### Your Environment
Used Operating system:
- Operating system version/name:
  - Kodi version: 20.1
  - Libreelec 11.0.1

**Comment by Salokyn** [comment] 2023-05-03 08:46
> Does it work if you disable deinterlace?

No, I get a deinterlaced frozen image

> Does it work if you record the channel, then play the recording?

Yes it works. It also works with timeshift.

> Does it work if you play the recording through the files interface rather than PVR interface?

Yes

**Comment by popcornmix** [comment] 2023-05-03 08:51
Is it any different if you switch audio output from hifiberry to hdmi?

**Comment by Salokyn** [comment] 2023-05-03 09:14
> Is it any different if you switch audio output from hifiberry to hdmi?

No, that's same.

Well note that while I made the tests it worked a couple of times (with hifiberry or hdmi). It's a bit random.

**Comment by popcornmix** [comment] 2023-05-04 14:55
Can you enable ffmpeg in component specific debug and catch a failure to play?

It's going to be hard to track this down without a reproducible case (which is why I was hoping a recording would have the same failure).

I use TV Headend and decode with DRM HW enabled with no problem. I'm in the UK where channels are a mixture of 1080p H.264 and SD MPEG2.

One other thing you could try is the Demo PVR client.
That will probably work with the default Big Bug Bunny channel,
but you could change the path of that to a recording you've made
and that may possibly provoke the issue (and be reproducible).

**Comment by Salokyn** [comment] 2023-05-13 07:28
Here are logs with FFmeg and PVR debug logs (5.4 MB): https://paste.chapril.org/?306662521a644975#FXQL75NssTwF6nS1DPoYjArr5WEoLJzRRLKGZyn1QPR7

I made a recording. Played it (worked fine). And finally watched live TV (frozen image).

I'll try the Demo PVR client trick.

**Comment by Salokyn** [comment] 2023-05-13 07:38
> you could change the path of that to a recording you've made

I don't find how to change the default BBB streams with something else.

**Comment by popcornmix** [comment] 2023-05-13 10:33
> I don't find how to change the default BBB streams with something else.

edit PVRDemoAddonSettings.xml (in /storage/.kodi/addons), e.g. [this line](https://github.com/kodi-pvr/pvr.demo/blob/be2a4367623f0a123f1e99991b638477c9aa454e/pvr.demo/PVRDemoAddonSettings.xml#L34)
to point to your file.

**Comment by Salokyn** [comment] 2023-05-13 15:50
It cannot reproduce with PVR demo. The recording plays fine.

It also works with TVH, when timeshifting. Only live play is a problem.

**Comment by jc-kynesim** [comment] 2023-05-14 09:39
Assuming that the failing run is the one that starts at ~09:17:13 then what appears to be going on is that the stream starts OK then ffmpeg gets an EOS request, possibly due to observed change in output dimensions? the kodi output pipe is reconfigured (deint is shut down)? then kodi continues to drain the remaining pictures from the decode Q which eventually EOFs. Then the EOF condition isn't cleared (by flush or whatever) so no more pictures appear.
Or that's my best guess anyway.  Certainly there is a persistent EOS condition on decode.

**Comment by popcornmix** [comment] 2023-05-15 10:36
@Salokyn to narrow down the issue can you confirm if it still occurs with deinterlace disabled?

**Comment by Salokyn** [comment] 2023-05-15 17:09
> @Salokyn can you give [this test build](https://drive.google.com/uc?id=1ybDe9Pi7hj7jWbpGn_vXiXxuXi-gJ9B3&export=download) a try? (copy to /storage/.update and reboot). It should be a build from top of libreelec-11.0 branch with a commit added to flush codec after an eof.
> 
> Without being able to reproduce, it's a bit of a long shot, but that seems to be the area the log indicates.

Done.

The image still freeze the same way.

Note that I can't reproduce it 100% of the time. Sometimes it works. I don't know why.

Here the logs of my last try with the build test : https://paste.chapril.org/?b5a4752c9b5b7b9a#Fv8uXriBLCu4tP5yPTY6GHsbaDEza3oj9EoAuDhn237A

**Comment by Salokyn** [comment] 2023-05-15 17:37
Oops, you're right ...

![image](https://github.com/xbmc/xbmc/assets/11018648/ccd6e07e-d09d-48ff-9d45-c37a68daaeb5)

**Comment by popcornmix** [comment] 2023-05-15 18:15
[This](https://drive.google.com/uc?id=1Kub1PROAQVkQELSjy49oMu8FhnaOPY_r&export=download) should be an arm32 version of previous build.

**Comment by Salokyn** [comment] 2023-05-15 18:52
Thank you!
It works! The first 5-10 sec are jerky (perhaps the time to buffer?) and then it's fine.

**Comment by popcornmix** [comment] 2023-05-15 18:55
Great - thanks for the detailed report and testing.
I'll make sure this appears in future updates.

**Comment by Salokyn** [comment] 2023-05-15 19:18
Thank you!

Do you think these jerky first seconds could be reduced? Maybe this needs its own ticket.

**Comment by Salokyn** [comment] 2023-05-15 19:19
Thank you!

Do you think these jerky first seconds could be reduced? Maybe this needs its own ticket.

**Comment by jc-kynesim** [comment] 2023-05-16 09:21
Ah! The joys of AVsync on paced streams. I remember them well (and the strategies you want for clean startup are quite different from on-demand streams). Not my bug, but I'd definitely recommend a different PR.

**Comment by popcornmix** [comment] 2023-05-16 10:18
> Do you think these jerky first seconds could be reduced? Maybe this needs its own ticket.

Yes - best to close this and open a new issue. The cause will be unrelated to the bug discovered here.

**Comment by Salokyn** [comment] 2023-05-16 16:37
@popcornmix Is there a PR for this fix ?

**Comment by popcornmix** [comment] 2023-05-16 17:29
The fix is [here](https://github.com/popcornmix/xbmc/commit/49240a89dacc793e99237cee764c7918e1fc402d).
It doesn't affect this repo as the bug was introduced in a patch that adds deinterlace to DRMPrime, which isn't supported here.
The patch will be PR'd to LibreELEC soon.

**Comment by Salokyn** [comment] 2023-05-16 17:47
Thank you!

**Comment by sarbes** [comment] 2023-12-27 06:54
Closing this then...

**Closed** 2023-12-28 13:55 UTC
Labels: Resolution: External
