### ISSUE TITLE
No GUI sound when using controller

### ISSUE THREAD

**Issue by MaxmaxOk** [xbmc/xbmc#22025] opened 2022-10-13 08:34 UTC
No GUI sound when using controller

### Describe the bug
Here is a clear and concise description of what the problem is:
Using the keyboard or a remote the problem doesn't occur

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
GUI sound effects doesn't work using controller

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19.4

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment] 2022-10-15 13:25
Duplicate of https://github.com/xbmc/xbmc/issues/15031

@garbear fyi

**Closed by enen92** 2022-10-15 13:25 UTC
Labels: Resolution: Duplicate
