### ISSUE TITLE
Reproducible segfault with Kodi 20.0-ALPHA1

### ISSUE THREAD

**Issue by bacon-cheeseburger** [xbmc/xbmc#21147] opened 2022-03-19 22:35 UTC
### Describe the bug
Segfault occurs when playing trailers (via context menu) for library movie entries. The first attempt usually works but when playing a second trailer almost always segfaults. This seems to be python3.9 related.

## Expected Behavior
No segfault.

## Actual Behavior
Segfault.

## To Reproduce
1. start Kodi
2. play a movie trailer via context menu
3. repeat step 2 with a different movie trailer

If it hasn't segfaulted yet, then:

4. Go into the youtube addon settings, then back out to the main menu and repeat from step 2.

I don't know that step 4 actually does anything, but it seems like it "encourages" the segfault to happen if by some chance it didn't happen at step 2.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/uzodotemol.kodi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Debian Sid
 - Kodi version: 20.0-ALPHA1-r59338-git+5244df5a44

I set up a test environment with test video library using dummy media files so the errors trying to parse from them is expected.

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment] 2022-03-24 19:33
I could not reproduce this, but I'm running Python 3.10.2.

**Comment by bacon-cheeseburger** [comment] 2022-03-26 04:11
Thank you for checking enen92. I can't speak for other Linux distros but Debian Sid is on Python 3.9 so this problem is going to exist for Debian users for quite some time I think. If you have the chance to test with Python 3.9, you should see the problem.

**Comment by wsnipex** [comment] 2022-03-26 06:02
known issue, see https://forum.kodi.tv/showthread.php?tid=363499&pid=3064373&highlight=python+crash#pid3064373

**Comment by bacon-cheeseburger** [comment] 2022-03-26 15:07
I recompiled Kodi against Python 3.10.4 and the problem persists. It sounds like users will just have to live with the segfaults until the LanguageInvoker is converted to that new "multi phase init"? In my case, why does playing a trailer for the first time work fine with no LanguageInvoker crash but subsequent attempts segfault?

**Comment by arigit** [comment] 2022-09-30 18:09
I am seeing the same "crash on the second playback" behavior in a just-updated ubuntu 22.04 (20.04 > 22.04) htpc that had no issues before with kodi 19.4, exact same setup as before the upgrade. I am using Team Kodi's ppa version. 


2022-09-29 22:09:22.500 T:46923    INFO <general>: Kodi compiled 2022-03-30 by GCC 11.2.0 for Linux x86 64-bit version 5.15.27 (331547)
2022-09-29 22:09:22.500 T:46923    INFO <general>: Running on Ubuntu 22.04.1 LTS, kernel: Linux x86 64-bit version 5.15.0-48-generic
2022-09-29 22:09:22.500 T:46923    INFO <general>: FFmpeg version/source: 4.3.2-Kodi

journalctl -r :

Sep 29 22:09:13 htpc runKodi-start.sh[42629]: Crash report available at /home/kodi/kodi_crashlog-20220929_220913.log
Sep 29 22:09:13 htpc runKodi-start.sh[42629]: Segmentation fault (core dumped)
Sep 29 22:09:13 htpc kernel: Code: 00 00 a9 a4 70 01 00 00 00 00 10 d4 76 ec 62 7f 00 00 e0 40 a4 ba 62 7f 00 00 40 34 a9 ba 62 7f 00 00 f0 35 a4 ba 62 7f 00 00 <01> 00 00 00 00 00>
Sep 29 22:09:13 htpc kernel: LanguageInvoker[46685]: segfault at 7f62baac72c0 ip 00007f62baac72c0 sp 00007f62b9bf3018 error 15


given that the exact same kodi binary had no issues on ubuntu 20.04 (kernel 5.4) but crashes every second play on 22.04/kernel 5.15, isn't this more of a kernel/cpython interaction issue? I'm assuming that kodi embeds it's own cpython binary. 
Posting here in case anyone finds a kodi version/kernel version combo that doesn't crash. 
I'm thinking about upgrading the kernel to the also-supported linux-oem (5.17) to see what happens

**Comment by wsnipex** [comment] 2022-10-01 14:29
anyone affected on ubuntu 22.04: this should be fixed by installing python 3.10.6-1~22.04 from jammy-updates

```
$ apt policy python3
python3:
  Installed: 3.10.6-1~22.04
  Candidate: 3.10.6-1~22.04
  Version table:
 *** 3.10.6-1~22.04 500
        500 http://at.archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     3.10.4-0ubuntu2 500
        500 http://at.archive.ubuntu.com/ubuntu jammy/main amd64 Packages

```

see https://bugs.launchpad.net/ubuntu/+source/python3.10/+bug/1982108/comments/10

**Comment by prahal** [comment] 2023-05-10 05:43
@bacon-cheeseburger  [Crash when using sqlite3 with subinterpreters](https://github.com/python/cpython/issues/92036#top) fixed in python3.10 3.10.5 and  python3.9 3.9.13 and python3.11 3.11.0b1 upstream.
Debian has 3.11.2-1+b1 in bookworm and sid nowadays.
Only bullseye could be affected has it is still at 3.9.2-3 and might not ship the fixes from the above and the related [[subinterpreters] crash when importing _sre in subinterpreters in parallel (Python 3.9 regression)](https://github.com/python/cpython/issues/90228#top) .
Either way it is a Debian issue only now.
This report should be closed once confirmed the issue is fixed for you too with the up to date python3.

**Comment by prahal** [comment] 2023-05-10 05:45
@arigit Debian kodi does not embed python per its own policy. I believe Ubuntu does the same.

**Closed** 2023-07-10 13:43 UTC
Labels: Resolution: External, Triage: Needed
