### ISSUE TITLE
Kodi Leia freezes when trying to add subtitle from external source

### ISSUE THREAD

**Issue by gnffilos** [xbmc/xbmc#15799] opened 2019-03-22 08:44 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

When i try to add subtitle to a movie or series episode from external source such as usb stick or external hard drive kodi leia freezes and i have to force close it.
It happens all the time using PC or Smart Tv

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

It should open hard drives to find the subtitle that i have already inside them

## Actual Behavior

Freezes the system

## Possible Fix

It is a bug for over 6 months..tried different versions, nothing happened even if i upgrade or downgrade

### To Reproduce

1. search for subtitles for a movie or series episode from every single video addon (used everything)
2. kodi freezes
3. force close kodi by ctrl+alt+del--->end kodi proccess

### Debuglog

The debuglog can be found here:

https://github.com/xbmc/xbmc/files/2996453/kodi.old.log
https://github.com/xbmc/xbmc/files/2996489/kodi.log

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

Android
Windows

 - Operating system version/name:
 - Kodi version:

18.0
18.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by pkerling** [comment] 2019-03-22 09:46
Where is the debug log?

**Comment by gnffilos** [comment] 2019-03-22 09:59
sorry i don't have one

**Comment by pkerling** [comment] 2019-03-22 10:27
Please capture and upload a debug log, see https://kodi.wiki/view/Log_file/Easy

**Comment by gnffilos** [comment] 2019-03-22 12:41
[kodi.old.log](https://github.com/xbmc/xbmc/files/2996453/kodi.old.log)

here is the debug log

**Comment by gnffilos** [comment] 2019-03-22 15:31
i have edited my first post..don't know what else to add for bug description

**Comment by pkerling** [comment] 2019-03-22 15:47
Please read the message --> "You may not have any unsupported add-ons installed"

**Comment by gnffilos** [comment] 2019-03-22 21:14
i installed kodi from scratch...does the same thing with only one addon installed

**Comment by TugaPowerROM** [comment] 2019-03-22 21:59
This is also happening to me since Kodi 18 exists, being for mounths now.

**Comment by DaVukovic** [comment] 2019-03-23 00:40
@gnffilos either provide a full and clean debuglog or we will close that issue. It's easy as that. You have now been told 2 times to do so. We are most likely not interested at all in your issue if banned add-ons are involved. Read the message above.

To get a full and clean log, simply rename your `%appdata%\Kodi` folder to `%appdata%\Kodi-old` and restart Kodi. That's like a factory reset but all settings and add-ons are stored at the "Kodi-old" folder. So you could easily rename it back.

As the message above tells you, we will close this issue in 7 days if no clean debuglog was submitted. No further postings needed if they don't contain a log. 

Thanks in advance

**Comment by gnffilos** [comment] 2019-03-23 08:03
and how on earth will i have the problem i described above if i have not a single addon in my kodi that can play a video?
I can have a kodi installation in my pc that has no addons inside. I will open it, see if it has a beautiful blue skin and close it. In that way there is no bug with subtitles.
It's ok..you can close this.

**Comment by DaVukovic** [comment] 2019-03-23 10:34
You are fine installing required add-ons to reproduce your problem. At no point I said, that it's not allowed to install any add-on. If one of the banned add-ons is required to reproduce your problem, then yes, we are not interested.

Please read the links above which add-ons are banned and which not. 

As a hint and a rule of thumb:

If an add-on gives you the possibility to get content for free which others have to pay for, then it's pretty much common sense that this is something illegal. OTOH paying for something doesn't make it legal. Think of the example of buying a stolen car. 

So please, do what you have been told, install the required add-ons to reproduce your problem and if the add-on in question is on the banned list, then you are able to close this issue yourself by clicking "Close"

**Comment by gnffilos** [comment] 2019-03-23 23:01
clean install of kodi 18.1
installed tempest addon that is NOT in the banned list
same problem and the log file is here
[kodi.log](https://github.com/xbmc/xbmc/files/2999854/kodi.log)

**Comment by DaVukovic** [comment] 2019-03-24 06:58
> installed tempest addon that is NOT in the banned list

First result on google by searching for "Kodi addon Tempest":
https://www.wirelesshack.org/how-to-install-tempest-kodi-addon.html

> Tempest is a Exodus/Covenant Fork that is currently pulling in many links.

It will also fall under the case I mentioned above:

> If an add-on gives you the possibility to get content for free which others have to pay for, then it's pretty much common sense that this is something illegal. 

So I guess it's enough now as you haven't even read the wiki page properly, not even the big fat red note at the top of that wiki, telling:

> This list is only an example. Due to the dynamic nature of Piracy streams and the add-ons that access them, it is impossible to list all Builds/Repositories/Add-ons that violate the forum rules

Anyway, this is closed now

**Closed by DaVukovic** 2019-03-24 06:58 UTC
Labels: Ignored rules, Need more information, Triage: Needed

**Comment by peno64** [comment] 2019-04-02 19:55
I had the same issue and also posted this as a bug report and had the same answers and no solution...
Contact me for a work-around: peno64@gmail.com
