### ISSUE TITLE
 Subtitle Storage Location "NEXT TO VIDEO" not working when "Play Next Video Automatically" is turned on

### ISSUE THREAD

**Issue by tekwarp** [xbmc/xbmc#19168] opened 2021-02-03 16:11 UTC
### Describe the bug
Subtitles are not saved next to video even when specified in settings. **SEE Screenshot 1**

## Expected Behavior
Subtitles should be saved next to video when specified in settings.

## Actual Behavior
Subtitles are cached temporarily. When video playback is stopped and later resumed, the subtitle is no longer available.

## Possible Fix
This happens when "Play Next Video Automatically" is turned on. Disabling this feature fixes the problem.

1. Turn off all options under "Play Next Video Automatically".
2. Start any video (Moive or TV Episode) and download subtitles (e.g. using OPENSUBTITLES add on)
3. Subtitles are saved Next to Video. **SEE DEBUGLOG LINES 3511 to 3518 (Screenshot 2)**

### To Reproduce
1. Turn on all/some options under "Play Next Video Automatically".
2. Start any video (Movie or TV Episode) and download subtitles (e.g. using OPENSUBTITLES add on)
3. Subtitles are not saved Next to Video. **SEE DEBUGLOG LINES 2133 to 2137 (Screenshot 3)**

### Debuglog

The debuglog can be found here:

https://controlc.com/d97b6001

### Screenshots
Here are some links or screenshots to help explain the problem:

Screenshot 1: https://snipboard.io/E0qRZS.jpg

Screenshot 2: https://snipboard.io/3tqBuV.jpg

Screenshot 3: https://snipboard.io/aVzsTx.jpg

### Your Environment
Used Operating system:

 - [X] Android OS 10
 - [X] Android TV OS 10
 - [X] Windows 10 20H2, kernel: Windows NT x86 64-bit version 10.0.19042.746

KODI versions:

 - [X] Kodi for Android : 19.0-RC1 kodi-19.0-Matrix_rc1-armeabi-v7a.apk
 - [X] Kodr for Windows: 19.0-RC1 (18.9.910) Git:20210115-90a1e12804). Platform: Windows NT x86 64-bit

KODI database:

 - [X] mysql (MARIA 10 running on Synology NAS). Note: There are no rd/wr permission issues.

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by joseluismarti** [comment] 2021-02-04 07:51
Hi @tekwarp, I've tried to reproduce the issue with **Addic7ed Addon** and everything works as it should. Can you try with this addon?

I will try to reproduce the issue with **Opensubtitles Addon**, it downloads the subtitles in a zip file, this may be the cause.

**Comment by tekwarp** [comment] 2021-02-04 13:16
Hi Jose Luis, I will try today on both platforms and report back. PS. Since posting, i came across 2 other postings describing this issue and solution on quora and reddit.

**Comment by tekwarp** [comment] 2021-02-04 17:17
Hi JL,

Unfortunately, Addic7ed Addon doesn't seem to run on Android or Windows platforms with Kodi 19 RC1.

2021-02-04 12:14:50.992 T:32900    INFO <general>: service.subtitles.rvm.addic7ed: Searching for subs...
2021-02-04 12:14:51.026 T:33464 WARNING <general>: CRenderManager::WaitForBuffer - timeout waiting for buffer
2021-02-04 12:14:51.476 T:32900   ERROR <general>: service.subtitles.rvm.addic7ed: Addic7ed.com returned status: 503
2021-02-04 12:14:51.477 T:32900   ERROR <general>: service.subtitles.rvm.addic7ed: Unable to connect to addic7ed.com

Regardless of the Addon, turning on/off **Play next video automatically** should not impact the subtitle location storage.

**Comment by joseluismarti** [comment] 2021-02-04 22:11
Hello, I've proposed a fix #19174

**Comment by enen92** [comment] 2021-02-07 10:12
Fixed in the PR above

**Closed by enen92** 2021-02-07 10:12 UTC
