### ISSUE TITLE
Windows Store Build Wrong Folder

### ISSUE THREAD

**Issue by Tigerman2309** [xbmc/xbmc#15703] opened 2019-03-08 23:46 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi.Log shows special://home/ as mapped to: C:\Users\<user>\AppData\Roaming\Kodi\ 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The real location is C:\Users\..\AppData\Local\Packages\XBMC...\LocalCache\Roaming\Kodi\

### To Reproduce

1. Install Store Version
2. Launch Kodi
3. View Kodi.Log

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [x] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: 18.1 Git: 20190217

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment] 2019-03-09 05:02
The location depends on your install method. 

If you download the installer, it is in the location you mention under Describe the Bug

If you installed the MS Store version, it is in the location you mention in Expected Behaviour.

The wiki clearly states the locations.

I will consider this solved and close this issue.

**Comment by KarellenX** [comment] 2019-03-09 05:30
I don't see a problem. This is from my own log and it records the correct location **for the MS Store version**

`special://home/ is mapped to: C:\Users\Master\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState`

And this is a copy of path from Windows Explorer.
`C:\Users\Master\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState`

If you used the downloadable installer, the location is here...
`C:\Users\Master\AppData\Roaming\Kodi`

I note you have not provided a debug log to support your issue, so it will be marked invalid and closed in due course if the log is not submitted.

**Comment by Tigerman2309** [comment] 2019-03-09 09:51
Hi,

2019-03-08 23:54:01.560 T:2420  NOTICE: Starting Kodi (18.1 Git:20190217-8cfdc895f3). Platform: Windows NT x86 64-bit
2019-03-08 23:54:01.560 T:2420  NOTICE: Using Release Kodi x64 build
2019-03-08 23:54:01.560 T:2420  NOTICE: Kodi compiled 2019-02-17 by MSVC 191627026 for Windows NT x86 64-bit version 10.0 (0x0A000006)
2019-03-08 23:54:01.560 T:2420  NOTICE: Running on Windows 10, kernel: Windows NT x86 64-bit version 10.0.17134
2019-03-08 23:54:01.560 T:2420  NOTICE: FFmpeg version/source: 4.0.3-Kodi
2019-03-08 23:54:01.560 T:2420  NOTICE: Host CPU: Intel(R) Core(TM) i5-3317U CPU @ 1.70GHz, 4 cores available
2019-03-08 23:54:01.560 T:2420  NOTICE: Desktop Resolution: 1920x1080 32Bit at 60Hz
2019-03-08 23:54:01.560 T:2420  NOTICE: Running with restricted rights
2019-03-08 23:54:01.560 T:2420  NOTICE: Aero is enabled
2019-03-08 23:54:01.560 T:2420  NOTICE: special://xbmc/ is mapped to: C:\Program Files\WindowsApps\XBMCFoundation.Kodi_18.1.500.0_x64__4n2hpmxwrvr6p
2019-03-08 23:54:01.560 T:2420  NOTICE: special://xbmcbin/ is mapped to: C:\Program Files\WindowsApps\XBMCFoundation.Kodi_18.1.500.0_x64__4n2hpmxwrvr6p
2019-03-08 23:54:01.560 T:2420  NOTICE: special://xbmcbinaddons/ is mapped to: C:\Program Files\WindowsApps\XBMCFoundation.Kodi_18.1.500.0_x64__4n2hpmxwrvr6p/addons
2019-03-08 23:54:01.560 T:2420  NOTICE: special://masterprofile/ is mapped to: C:\Users\tiger\AppData\Roaming\Kodi\userdata
2019-03-08 23:54:01.560 T:2420  NOTICE: special://home/ is mapped to: C:\Users\tiger\AppData\Roaming\Kodi\
2019-03-08 23:54:01.560 T:2420  NOTICE: special://temp/ is mapped to: C:\Users\tiger\AppData\Roaming\Kodi\cache
2019-03-08 23:54:01.560 T:2420  NOTICE: special://logpath/ is mapped to: C:\Users\tiger\AppData\Roaming\Kodi\
2019-03-08 23:54:01.560 T:2420  NOTICE: The executable running is: C:\Program Files\WindowsApps\XBMCFoundation.Kodi_18.1.500.0_x64__4n2hpmxwrvr6p\Kodi.exe
2019-03-08 23:54:01.565 T:2420  NOTICE: Local hostname: SurfacePro
2019-03-08 23:54:01.565 T:2420  NOTICE: Log File is located: C:\Users\tiger\AppData\Roaming\Kodi\kodi.log

This is the startup from my log file, as you can see the home location does not match the location that the xbmc.

**Comment by Tigerman2309** [comment] 2019-03-09 22:22
I have uninstalled and reinstalled, also been through both Local and Roaming removing any folders with Kodi name and still the log states :-

special://home/ is mapped to: C:\Users\tiger\AppData\Roaming\Kodi\

Any suggestions would be helpful....

**Comment by idolpx** [comment] 2019-12-13 22:41
I'm having the same issue.

----------------------------------
2019-12-13 14:06:02.704 T:6640  NOTICE: -----------------------------------------------------------------------
2019-12-13 14:06:02.704 T:6640  NOTICE: Starting Kodi (18.5 Git:20191116-37f51f6e63). Platform: Windows NT x86 64-bit
2019-12-13 14:06:02.705 T:6640  NOTICE: Using Release Kodi x64 build
2019-12-13 14:06:02.705 T:6640  NOTICE: Kodi compiled 2019-11-16 by MSVC 191627034 for Windows NT x86 64-bit version 10.0 (0x0A000006)
2019-12-13 14:06:02.705 T:6640  NOTICE: Running on Windows 10, kernel: Windows NT x86 64-bit version 10.0.18362
2019-12-13 14:06:02.705 T:6640  NOTICE: FFmpeg version/source: 4.0.4-Kodi
2019-12-13 14:06:02.705 T:6640  NOTICE: Host CPU: Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz, 2 cores available
2019-12-13 14:06:02.706 T:6640  NOTICE: Desktop Resolution: 3858x2144 32Bit at 60Hz
2019-12-13 14:06:02.706 T:6640  NOTICE: Running with restricted rights
2019-12-13 14:06:02.706 T:6640  NOTICE: Aero is enabled
2019-12-13 14:06:02.706 T:6640  NOTICE: special://xbmc/ is mapped to: C:\Program Files\WindowsApps\XBMCFoundation.Kodi_18.5.500.0_x64__4n2hpmxwrvr6p
2019-12-13 14:06:02.706 T:6640  NOTICE: special://xbmcbin/ is mapped to: C:\Program Files\WindowsApps\XBMCFoundation.Kodi_18.5.500.0_x64__4n2hpmxwrvr6p
2019-12-13 14:06:02.706 T:6640  NOTICE: special://xbmcbinaddons/ is mapped to: C:\Program Files\WindowsApps\XBMCFoundation.Kodi_18.5.500.0_x64__4n2hpmxwrvr6p/addons
2019-12-13 14:06:02.706 T:6640  NOTICE: special://masterprofile/ is mapped to: C:\Users\jjohnston\AppData\Roaming\Kodi\userdata
2019-12-13 14:06:02.706 T:6640  NOTICE: special://home/ is mapped to: C:\Users\jjohnston\AppData\Roaming\Kodi\
2019-12-13 14:06:02.706 T:6640  NOTICE: special://temp/ is mapped to: C:\Users\jjohnston\AppData\Roaming\Kodi\cache
2019-12-13 14:06:02.706 T:6640  NOTICE: special://logpath/ is mapped to: C:\Users\jjohnston\AppData\Roaming\Kodi\
2019-12-13 14:06:02.706 T:6640  NOTICE: The executable running is: C:\Program Files\WindowsApps\XBMCFoundation.Kodi_18.5.500.0_x64__4n2hpmxwrvr6p\Kodi.exe
2019-12-13 14:06:02.710 T:6640  NOTICE: Local hostname: DESKTOP-NFPM461
2019-12-13 14:06:02.710 T:6640  NOTICE: Log File is located: C:\Users\jjohnston\AppData\Roaming\Kodi\kodi.log
2019-12-13 14:06:02.710 T:6640  NOTICE: -----------------------------------------------------------------------

**Comment by fuzzard** [comment] 2020-09-27 08:27
Ill mark this one as duplicate of https://github.com/xbmc/xbmc/issues/18260

Purely because the other issue has a few more details/possible fix in the ticket.

**Closed by fuzzard** 2020-09-27 08:27 UTC
Labels: Resolution: Duplicate, Triage: Needed
