### ISSUE TITLE
[Android v18] Non-ASCII characters are not sorted

### ISSUE THREAD

**Issue by xjdic** [xbmc/xbmc#15026] opened 2018-12-10 01:08 UTC
### Describe the bug

(This is output by Google translation. Sorry...)
(I am using Kodi in Japanese.)

In Kodi v18, non-ASCII characters are not sorted.

In Kodi v18, if non-ASCII characters and ASCII characters are mixed in the file name or movie name, it will be sorted by ASCII characters only.
In Kodi v18, if file names and movie names are only non-ASCII characters, they are not sorted but displayed in library registration order.

In Kodi v 17.6, non-ASCII characters are sorted in Unicode order.

## Expected Behavior

Sorted in Unicode order like Kodi 17.6.

### Screenshots 
Here are some links or screenshots to help explain the problem:

https://drive.google.com/file/d/1kTgTDMTZdk1YljHw8uHIfC1MY0hAVxd8/view?usp=sharing
This linked image is a library when sorting by title in Kodi v18.
Non-ASCII characters are not sorted.

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: 
Android 8.0 (GalaxyS7edge), AndroidTV 8.0(BRAVIA)

 - Kodi version: 
v18rc2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment] 2018-12-10 11:54
I edited your posting to make the link to the screenshot working. 

Even if it might probably not needed, but could you please submit a full debuglog? That would be awesome and probably helpful.

Thanks in advance.

**Comment by pkerling** [comment] 2018-12-20 10:45
Works on Linux. I bet it's that weird Android sorting thing again.

**Comment by pkerling** [comment] 2018-12-20 12:19
Confirmed duplicate of #14952 (caused by same underlying issue). Thanks for reporting anyway, I hope we can sort this out.

**Closed by pkerling** 2018-12-20 12:19 UTC
