### ISSUE TITLE
Loading *.iso forces close Kodi 21

### ISSUE THREAD

**Issue by Endur** [xbmc/xbmc#25105] opened 2024-05-02 08:05 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

If I try to load an *.iso file from a directly attached USB3 device Kodi forces close immediality.
Kodi 20.* was working fine - also master/nightly 22alpha is working fine. #24964 doesn't fix that. It's a different issue.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Simply play the *.iso as usual.

## Actual Behavior

Force close of Kodi.

### To Reproduce

1.  Open any *.iso file
2.
3.

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/edifeconal.kodi

The log is done with adb debugging over ssh. Also with | grep -i kodi.
Kodi 21 opens the *. iso with OnPlayMedia <file> which forces close
05-01 13:48:53.280  9015  9031 D Kodi    : **ERROR: fseeko (): Invalid argument

Kodi 22 master/nighly opens the *. iso with VideoPlayer::OpenFile: <file> which is working well

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

It's on Minix NEO U22-XJ Max. Kodi 20 was working fine. Kodi 21 can't play the *.iso even fix #24964 was applied.
Kodi 22alpha of master/nightly is working fine.

### Your Environment
Used Operating system:

 - [x ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 21

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by joseluismarti** [comment] 2024-05-03 11:33
Can confirm that it occurs when opening an .iso file that is stored on the internal storage and only affects v21. 

Debug message: 
```
D Kodi : **ERROR: fseeko (): Invalid argument`
```

This crash is caused by  `libcdio-gplv3` library when trying to open the file from:
https://github.com/xbmc/xbmc/blob/a9076fe4140c666744a66c859df422bc47b6f458/xbmc/filesystem/ISO9660Directory.cpp#L38

I think it's because the `fseeko()` function is not available before API level 24. We'll have to wait for a workarround.

**Comment by Endur** [comment] 2024-05-03 15:22
Don't understand this right...The device is running on Android 9 which has API level 28, also shown well on Kodi -> System information.

**Comment by mjoseph81** [comment] 2024-05-04 14:47
I'm having this same issue.  I use Kodi to play DVDs I ripped as ISOs and store on an NFS server.  This function is completely broken. I back loaded Kodi to v19.5 where this was working but I had to disable all auto-updates on my chromecast otherwise it keeps loading v21 and breaking the ISO function.  Please fix.

**Comment by joseluismarti** [comment] 2024-05-04 21:37
@mjoseph81 if the ISOs are on network storage, the cause is different and has been fixed. Try an Omega 21.1 [nightly build](https://mirrors.kodi.tv/nightlies/android/).

**Comment by mjoseph81** [comment] 2024-05-06 00:49
Jose,

Thanks for the feedback but the version in the Google play store is 21.0
which does not work.  Until a functioning version is released to google I
will have to disable auto- updates.

Thanks,
Matt

**Comment by joseluismarti** [comment] 2024-05-08 06:35
@Endur tests this [build](https://jenkins.kodi.tv/job/android-arm-docker/6520/artifact/kodi-20240507-889cfa07-PR25156-armeabi-v7a.apk) which includes a possible fix

**Comment by Endur** [comment] 2024-05-08 11:39
Have that build tested. The force close is gone, this error was fixed!
Thanks... 
/Matthias

**Comment by thexai** [comment] 2024-05-14 13:07
Fixed by https://github.com/xbmc/xbmc/pull/25156

**Closed by thexai** 2024-05-14 13:07 UTC
Labels: Platform: Android, Triage: Confirmed, Component: FileSystem, v21 Omega
