### ISSUE TITLE
PVR EPG first channel data missing and +1 shift all list

### ISSUE THREAD

**Issue by lama18** [xbmc/xbmc#15960] opened 2019-04-22 18:08 UTC
### Describe the bug

PVR is missing the first line of EPG data and at the same time it is shifted by one channel, ie. (see screenshot) program that is for CT1 is in position for CT2 etc, interesting that everything in the "All channels" view is OK, only "Guide" is problem.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Open Kodi
Open PVR (TV), Channel list etc.

## Possible Fix

In <19 it works .. at the moment I have 18.2 and i works fine.

### To Reproduce

1.  Open Kodi
2. Open PVR (TV), Channel list etc.
3. If I try to erase the program data, or the epg12.db file, everything will load fine, but the error will be repeated after Kodi restarts.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/kodosoxenu.kodi

### Screenshots
![image](https://user-images.githubusercontent.com/20426629/56516723-8d52cb00-653b-11e9-9b51-44dcaa19727b.png)

![image](https://user-images.githubusercontent.com/20426629/56516383-9727fe80-653a-11e9-9ef9-29f5c8decbf9.png)

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19.0-ALPHA1 Git:20190421

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment] 2019-04-23 04:38
Unfortunately you have banned add-ons installed and the log you posted misses debug infortmation. So please enable debug logging, remove the banned add-ons and get us a new log

Thanks in advance ;)

**Comment by lama18** [comment] 2019-04-23 06:51
https://paste.kodi.tv/bilupofico.kodi

Ok, sry.

**Comment by DaVukovic** [comment] 2019-04-23 07:34
You still have banned add-ons installed

**Comment by lama18** [comment] 2019-04-23 07:55
https://paste.kodi.tv/afujoruhat.kodi

Ok, this one?

**Comment by Rechi** [comment] 2019-04-23 07:58
no

**Comment by lama18** [comment] 2019-04-23 08:01
https://paste.kodi.tv/iwicagasiq.kodi

last one..

**Comment by DaVukovic** [comment] 2019-04-23 10:35
2019-04-23 10:00:37.877 T:12816  NOTICE: ADDON: plugin.video.stream-cinema v1.3.14 installed

That's still installed. So you haven't changed anything yet. 

If you don't know how to uninstall banned add-ons, close Kodi and simply rename your Kodi folder at `%appdata%\Kodi` to something else ("Kodi-backup" for example). That will be like a factory reset but everything is still stored at the Kodi-backup folder. 

Then only add the add-ons which are needed to reproduce your issue and get us a new and clean logfile. 

Thanks in advance

**Comment by lama18** [comment] 2019-04-23 14:01
Ok, 
uninstall:
https://paste.kodi.tv/ulagufesag.kodi

Why is this plugin banned?

**Comment by ksooo** [comment] 2019-04-23 14:35
Have you tried to clear locally cached EPG data (Settings -> PVR & Live TV -> General -> Clear data)?

**Comment by lama18** [comment] 2019-04-23 14:38
Sure, As I wrote, if I delete data, respectively. I will try epg12.db directly, load the data correctly, but after restart it is the same.

It's happening in version 19 alpha + in version 18 is all right.

**Comment by ksooo** [comment] 2019-04-23 14:40
> In <19 it works .. at the moment I have 18.2 and i works fine.

 Not a Leia issue.

**Comment by ksooo** [comment] 2019-04-23 14:40
Final 18.2 works fine?

**Comment by lama18** [comment] 2019-04-23 14:41
Yes, 18.2 Ok. I know in the description it wrote 19 issue. Label is bad.

**Comment by djp952** [comment] 2019-04-25 02:14
@ksooo, I've been trying to replicate this as well for a couple weeks based on reports on my project. I have personally seen it on 18.1 and 18.2 (rc1).  It's been very difficult to catch in the act on a system where I could dig deeper.

If this is the same thing I've seen I can add a couple pieces of information that I have.  First, when the EPG is shifted the program name displayed on the TV Home screen under "Recently played channels" will still be correct.  Second, restarting Kodi resolves the problem -- clearing data does not fix it.  A simple close/open does it, even if no new EPG data is requested.

I speculate that it's a UI concern since the data in the Epg database is clearly correct.

Hopefully this helps, if not I apologize to @lama18 for interjecting an unrelated matter. I have been waiting for more evidence before opening this exact Issue, I figure I would need to be able to provide proof that it's not an addon issue.

**Comment by walterheisenberg** [comment] 2019-04-25 06:32
I just wanted to say, that everything works on Milhouse LE9 nightly [#0424](https://forum.kodi.tv/showthread.php?tid=343068&pid=2848997#pid2848997) from today together with TVH (pvr.hts)

**Comment by lama18** [comment] 2019-04-25 07:00
Yes, from 19.0-ALPHA1 Git:20190424, solved issued.

Issue closed.

**Comment by ksooo** [comment] 2019-04-25 18:25
It's actually not solved, so, let's keep this open.

**Comment by lama18** [comment] 2019-04-25 18:28
Thank you ;-)

Current findings:

When I physically delete the **epg12.db** file, the data is loaded correctly after startup, the problem repeats after the restart, so the only solution at the moment is to delete the **epg12.db** file before each run.

**Comment by ksooo** [comment] 2019-04-25 18:42
What happens if you **activate** "Settings" -> "PVR & Live TV" -> "Guide" -> "Don't cache in local database"? This is usually **deactivated**.

**Comment by ksooo** [comment] 2019-04-25 18:43
Could you please provide a 'broken' epg12.db file to me?

**Comment by ksooo** [comment] 2019-04-25 18:43
Before you change the setting, ofc.

**Comment by ksooo** [comment] 2019-04-25 18:43
There are no private data in that file, just the epg tags.

**Comment by ksooo** [comment] 2019-04-25 18:45
(BTW, epg cache is known to be buggy and in most usage scenarios not even to get performance gains. That's why I always disable the cache by **activating** the above mentioned setting.)

**Comment by lama18** [comment] 2019-04-25 18:46
I activated this option by performing several reboots and everything is fine.

**Comment by ksooo** [comment] 2019-04-25 18:49
If you provide me with a broken epg12.db we have chances to find the cause of the bug and to fix it. Otherwise, as I cannot reproduce, we will be lost, I'm afraid. 

So, if you activate the epg cache again, reproduce the problem and send me the epg12.db file, I maybe able to help. Otherwise not.

**Comment by lama18** [comment] 2019-04-25 18:49
epg12.db (before change) https://yadi.sk/d/l5Mvlpu7gLhUsA

**Comment by ksooo** [comment] 2019-04-25 18:50
Thanks, I will try to find something in that file and report back, then.

**Comment by lama18** [comment] 2019-04-25 18:51
Ok, great. thank you. ;-)

**Comment by ksooo** [comment] 2019-04-25 18:58
That file content looks really strange. There are only three epg events stored, for channel "Nova HD". That is definitely crap. There should be hundred if not thousands of events stored. As I said, the epg cache is crappy and buggy.

Another question: If you look into pvr.hts addon settings, "Advanced settings" -> ""Async EPG transfer", is it enabled?

**Comment by lama18** [comment] 2019-04-25 19:02
Yes, async enabled.

**Comment by ksooo** [comment] 2019-04-25 19:08
That's fine and you should leave "async epg transfer" activated. With this, pvr.hts will send epg updates immediately to Kodi when tvh has epg updates. Otherwise, Kodi polls for updates with a fixed (user configurable) interval which can lead to out-of-date epg data.

Unfortunately, async epg in combination with local epg cache semms to have a (hard to catch) bug. OTOH, as epg cache gives no real adiitional value, just turn it of and you will be fine.

I have the feeling the I cnanot motivate myself to hunt and fix that bug, to be honest, as I do not use that damn epg cache. ;-)

However, let's keep this issue open as it is definitely a bug. Maybe somebody else picks up the ball. I think I wont.

**Comment by ksooo** [comment] 2019-04-25 19:10
Again, you are loosing nothing when deactivating the epg cache, except your tvh server is located at "the other end of the world with a very slow internet connection".

**Comment by lama18** [comment] 2019-04-25 19:14
Thank you, disable the cache is an elegant and functional solution.

maybe the default setting for this ...? :-)

**Comment by ksooo** [comment] 2019-04-25 19:16
Yeah I thought several times about disabling epg cache by default, but never did it...

**Comment by djp952** [comment] 2019-04-30 03:04
Hi @lama18 and @ksooo, I was able to come up with a scenario on 18.2 that causes this.  I will be digging into it a little and filing a separate Issue with the appropriate logs, but what causes this to happen for me is adding a channel while Kodi isn't running.  

The EPG data for the new channel will be shown in the first channel's slot, and the remaining channel EPG data will be pushed to the next EPG slot, causing all the channels in the EPG UI to be wrong.  The data shown under "Channels" as well as the tiles on the home screen is accurate.

As I said, I will be opening my own issue with the logs and whatnot as I collect it.  I am going to step through some code first to see if I can narrow it down a bit for you first.  I was hoping this information would be useful here since it's something you may be able to reproduce.

**Comment by ksooo** [comment] 2019-07-08 14:03
@lama18 could you check whether this is still an issue with Kodi 18.3?

**Comment by lama18** [comment] 2019-07-08 14:05
18.3 clean install works fine.

**Comment by ksooo** [comment] 2019-07-08 14:09
What about latest v19 nightly build?

**Comment by lama18** [comment] 2019-07-08 14:15
19.0 (build 8.7) "Store guide in database" (with or without) works fine ;-)

**Comment by ksooo** [comment] 2019-07-08 14:28
Thanks for reporting back. I will close this issue now.

**Closed by ksooo** 2019-07-08 14:28 UTC
Labels: Component: PVR, Platform: Android, Platform: Windows, v19 Matrix
