### ISSUE TITLE
CreateLoader - unsupported protocol(udp) in udp://

### ISSUE THREAD

**Issue by centizen** [xbmc/xbmc#20539] opened 2021-11-17 18:58 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

Unable to start playing a UDP Multicast stream on more recent versions of kodi (19.1). Other devices running 17.6 are capable of playing the stream without issue.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Stream should start and play without issue.

## Actual Behavior

Receive error message "One or more items failed to play. Check the log for more information about this message."
Logs show several lines of output that seem to indicate the protocol is not being handled correctly

### To Reproduce

1. Create a .strm file with a UDP multicast stream url ("udp://xxx.xxx.xxx.xxx:xxxx/") and place it in "videos" directory
2. From GUI, navigate to movies, navigate to videos directory and try to play .strm file

Alternatively:
1. Create and enable an autoexec service script which calls xbmc.Player().Play("udp://xxx.xxx.xxx.xxx:xxxx/")
2. Reboot device

### Debuglog

The debuglog can be found here:

Debug Log of non-working unit: https://pastebin.com/JXua3rgC
Debug log of working unit (running 17.6): https://pastebin.com/yR28EKTT

### Screenshots
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I have been using an older version of Kodi on Raspberry Pi 2/3's for many years as a reliable driver for digital signage and displays. These older boards have been getting more and more difficult to get, so I am trying to rebuild the solution using more readily available Raspberry Pi 4's. 

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [*] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19.1 on problem unit, 17.6 on working unit
 

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment] 2021-11-17 19:43
I guess one issue per topic is enough, no? ;)

This is a duplicate of: #20538 

Closed

**Closed by DaVukovic** 2021-11-17 19:43 UTC
