### ISSUE TITLE
Kodi crash on Huawei matebook 11 at 120hz  ? bugfix needed

### ISSUE THREAD

**Issue by tim-24** [xbmc/xbmc#21288] opened 2022-04-20 11:18 UTC
Kodi crashes at startup on Huawei matebook 11 at 120hz  !  bugfix needed

**Comment by popcornmix** [comment] 2022-04-20 12:48
Duplicate of https://github.com/xbmc/xbmc/issues/15872

**Closed by popcornmix** 2022-04-20 12:48 UTC
Labels: Ignored rules, Triage: Needed
