### ISSUE TITLE
Playing IPTV streams or TS file freezes kodi

### ISSUE THREAD

**Issue by radoslavv** [xbmc/xbmc#15669] opened 2019-03-04 16:23 UTC
### Describe the bug
KODI freezes on
- playig some IPTV streams like [this](http://185.134.40.41:1980/play/a00w) or
- playing TS streams (files) recorded by DVB-T recorder application.

Affected versions:
- kodi 18.0 Git:20190128-d81c34c, compiled 2019-01-28
- kodi 18.1 Git:20190217-8cfdc89, compiled 2019-02-17

Didn't experience such a behaviour on previous version of kodi 17.x.

## Expected Behavior
IPTV streams have to be played withouth freezing KODI.
TS streams (files) have to be played withouth freezing KODI.

## Actual Behavior

Kodi freezes on playing specific IPTV streams or TS files (seems some substream makes problem, didn't find which exactly).

## Possible Fix

FIX a bug.
No workaround found (tried ffmpeg pipe way with stream copy, but same issue).

### To Reproduce

1. add IPTV channel to IPTV Simple Client, **_sample.m3u8_** file to load
#EXTM3U
#EXTINF:-1,Freezing KODI
http://185.134.40.41:1980/play/a00w
2. switch to this channel
3. KODI frozen

### Debuglog

The debuglog can be found here:
[IPTVfreeze_kodi.old.log](https://github.com/xbmc/xbmc/files/2927227/IPTVfreeze_kodi.old.log)

### Screenshots 

Nothing special to show here. Screen remains frozen on selected TV channel that is to be played, no video or audio playback is started.

## Additional context or screenshots (if appropriate)

Please fix.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
Linux version 4.15.0-45-generic (buildd@lgw01-amd64-031) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)) #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 (Ubuntu 4.15.0-45.48-generic 4.15.18)
patched (updated & upgraded) today
 - Kodi version:
18.0 Git:20190128-d81c34c, compiled 2019-01-28,
18.1 Git:20190217-8cfdc89, compiled 2019-02-17

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment] 2019-03-04 17:01
The stream you provided (not sure if that's even legit) doesn't freeze Kodi here on Ubuntu 18.04.2. It stutters much, but it doesn't freeze. 

AFAICS, you are using pretty old hardware and in case you might have hardware acceleration activated, I would suggest to disable that, because...

2019-03-04 16:38:27.005 T:140636065856896  NOTICE: GL_RENDERER = AMD RV710 (DRM 2.50.0 / 4.15.0-45-generic, LLVM 6.0.0)

is the "minimum without hardware decoding" according to our wiki: 

https://kodi.wiki/view/Supported_hardware#Desktop

**Comment by radoslavv** [comment] 2019-03-04 17:11
This is 1 second SD MPEG2 MPG file, freezing KODI.
[KODI_video_freeze_1sec.zip](https://github.com/xbmc/xbmc/files/2927430/KODI_video_freeze_1sec.zip)
MPEG2 is HW supported with many VGA cards, including my old RADEON.

As I wrote, in older KODI versions (at least v17) no such a problem occured.

**Comment by DaVukovic** [comment] 2019-03-04 17:25
I don't see you playing this file in your log. Could you provide a log which shows that you are playing this file

btw...the file you provided doesn't freeze here. But I use a different GPU.

**Comment by radoslavv** [comment] 2019-03-04 17:25
With HW acceleration switched off it plays both
- IPTV stream
- MPG file
Seems this helped, but do not understand why HW acceleration was enabled after upgrade from v17 to v18 if there is compatibility issue...

**Comment by radoslavv** [comment] 2019-03-04 17:30
Attaching kodi.log, with disabled acceleration IPTV channels are working also MPG videos. With enabled video freezes.
[KODI_video_freeze_1sec_kodi.old.log](https://github.com/xbmc/xbmc/files/2927503/KODI_video_freeze_1sec_kodi.old.log)

**Comment by DaVukovic** [comment] 2019-03-04 17:35
ok, so if deactivated hardware acceleration helped in your case, then I guess it's fine to close this issue. For the "why" I would suggest to open a thread at our forums as this place is for bug reports. Yours seems not to be a bug rather than a wrong configuration (no offense ;) ). 

Your GPU is about 11 years old. As a suggestion...even a RPi 3 could do the task better.

But, your CPU should be good enough. Keep it that way.

**Closed by DaVukovic** 2019-03-04 17:35 UTC

**Comment by radoslavv** [comment] 2019-03-04 18:29
I do not like "solving"/closing issues this way.

For many MPEG2 IPTV streams acceleration works, but for some not. Also MPG file playing worked in KODI v17 withouth issues, with KODI v18 same files NOT.
That's certainly a BUG.
Seems something what worked in v17 is broken in v18.

MPEG4 HW acceleration works fine.
Only issue is with MPEG2 acceleration - I tried to disable only this one acceleration in KODI options and problematic IPTV streams and MPG files work wit this configuration.
But this is just WORKAROUND not fix.

Any issue with playback should report error not freeze app... Common user expectation.

KODI I like because I could upcycle old HW (sufficient for this purpose) this way.

**Comment by wodkab** [comment] 2019-12-04 08:13
I have exactly the same issue with every version V18.x on RPi3 and also on RPi4 ... and also with complete clean and new installations ... it happens with SD recordings (TS format) from TV Mosaic (former DVBLink). It happens playing them for a longer time from the PVR-Addon and also playing them directly from the Video section. I can confirm ... this is a BUG!

**Comment by phunkyfish** [comment] 2019-12-04 14:25
If your issue is with a particular addon please post your issue there.

**Comment by zbyte64** [comment] 2020-12-11 03:35
I am having trouble determining which addon is responsible for playing `.ts` files. I have disabled my PVR addon (HTSP) but still kodi becomes unresponsive when I try to play a `.ts` file that has data transmission errors from an HD Homerun.

**Comment by phunkyfish** [comment] 2020-12-11 07:54
> I am having trouble determining which addon is responsible for playing `.ts` files. I have disabled my PVR addon (HTSP) but still kodi becomes unresponsive when I try to play a `.ts` file that has data transmission errors from an HD Homerun.

Please use the kodi forum if you require support.
