### ISSUE TITLE
[PVR] Crash when open Guide (EPG)

### ISSUE THREAD

**Issue by AreaScout** [xbmc/xbmc#21609] opened 2022-06-27 15:16 UTC
### Describe the bug
Running KODI with PVR.HTS and tvheadend, when opening Guide, KODI crashes, opening program list works, viewing channels works also, just Guide crashes (EPG View)

## Expected Behavior
The EPG view should be opened like so

![screenshot00002](https://user-images.githubusercontent.com/1681560/175974845-fce73d26-09f0-40d7-937a-27de9a49d439.png)

## Actual Behavior
KODI crashes

## Possible Fix
It works on arm32 (armhf) build, but not on arm64 build !

### To Reproduce
Run this KODI build on ODROID-M1, install PVR and see four yourself
https://forum.odroid.com/viewtopic.php?f=217&t=44564  

### Debuglog
https://pastebin.com/raw/nmsr539g

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu 20.04 minimal server
 - Kodi version: 19.4

**Comment by ksooo** [comment] 2022-06-27 16:55
This one will be really hard to fix without having the EPG+PVR data causing the crash as we need to find out what's wrong with your EPG data. If you can reproduce the issue 100%, please post Epg and TV database files and we have chances.

**Comment by ksooo** [comment] 2022-06-27 16:57
And please activate component debugging for EPG and PVR and if it crashes, post that respective log.

**Comment by AreaScout** [comment] 2022-06-27 17:29
The last messages are:

2022-06-27 17:00:24.613 T:5933    ERROR <general>: GetItem: EPG tag (1, 288) not found!
2022-06-27 17:00:24.613 T:5933    ERROR <general>: GetGridItemPtr: Got no EPG tag (1, 288)!

**Comment by ksooo** [comment] 2022-06-27 17:38
> I have already postet the component debug log

I don't think so. I cannot see any single EPG log entry. You know how to enable component debug logging, don't you?

**Comment by AreaScout** [comment] 2022-06-27 19:29
Sorry I don't get anything other than that, I have enabled it and I only get that log, you are right normally it should be a note from which component the entry is, I saw that already for CEC, but for PVR and EPG there seems to be no unique entry :(

![screenshot00003](https://user-images.githubusercontent.com/1681560/176019431-d70b6162-32f2-49df-bfda-d5783945434d.png)

Tried it multiple times --> no unique entry

**Comment by ksooo** [comment] 2022-06-27 20:21
Strange that component logging seems not to work for you. 

Anyway, is the crash 100% reproducible, even if you removed Epg and TV db files while Kodi is down and start Kodi with no dbs?

**Comment by ksooo** [comment] 2022-06-27 21:09
Have you tried a recent Nexus nightly? Many fixes for PVR/EPG went into the new version.

**Comment by ksooo** [comment] 2022-06-28 05:58
@AreaScout I think component logging works as expected for you. There is nothing to log from EPG. Looked at the code and it seems that the name of the component does not appear in the log file. The `<general>` we see is the name of the logger, I thought it would be the logged component's name.

**Comment by AreaScout** [comment] 2022-06-28 07:09
@ksooo I thought that too, because with CEC logging you will get the component name instead of `<general>`

I didn't build Nexus to test it, I will build it today, but please if Nexus has already a fix for this and it works please backport the changes, 19.4 still has support so it would be nice to see it working here too

**Comment by ksooo** [comment] 2022-06-28 07:30
There are chances, yes, but I don't know whether Nexus actually has a fix for the crash you reported and which commit this could be, sorry. Otherwise I would have pointed you to it already. ;-)

**Comment by ksooo** [comment] 2022-06-28 08:26
If I can reproduce your crash, I will try to fix and backport it, yes. But I'm afraid that I will not be able to reproduce. Looking at the log and the db files content I cannot see anything suspicious. The last ERROR resulting in a crash is most probably due to in a way broken EPG data, that is not handled correctly. But I'm just guessing from former experience.

**Comment by ksooo** [comment] 2022-06-28 08:28
What I read from the data you provided is, that something is wrong with channel with number 2 in all channels group, which should be ORF2O HD, right? The Guide window is crashing will populating with data from this channel it seems. 

Could you for a test try to disable this channel in tvh backend and check whether Kodi still crashes? If yes, please send the log.

**Comment by AreaScout** [comment] 2022-06-28 08:33
Ok, well it coincides with my experiences, I normally fix things for myself but in this case I had to give up, it seems to difficult for me as I do not know fundamental concepts of the PVR backend.

Had to say that I am not alone with this crashes, other peoples using this installation having different TV providers (SAT, cable, terrestrial) also have this crashes, they are reporting exactly the same behavior.

Regards,
Daniel

**Comment by AreaScout** [comment] 2022-06-28 08:34
Yes, I will do

**Comment by AreaScout** [comment] 2022-06-28 08:58
Still the same :(

https://pastebin.com/raw/ZE3aqrCs

Found a note inside the source about the last log entry we get, maybe a hint ?

https://github.com/xbmc/xbmc/blob/Matrix/xbmc/pvr/guilib/GUIEPGGridContainerModel.cpp#L354

Regards,
Daniel

**Comment by ksooo** [comment] 2022-06-28 09:17
> Still the same :(

Not exactly, now we found the next channel with broken EPG data, which is channel with number 5.

Could you do me a favour and temporarily disable all channels in tvh, except channel number 1 (ORF1 HD)?

**Comment by ksooo** [comment] 2022-06-28 09:19
Wait, no. Please disable all channels except channel number 2, which as bad data. Delete TV and EPG db files, restart Kodi, it should crash, send log and db files. Not having many data in these files may help to understand what wrong with those data.

**Comment by AreaScout** [comment] 2022-06-28 09:37
It does not crash anymore but there is also no EPG data available yet after deleting the database

![screenshot00004](https://user-images.githubusercontent.com/1681560/176146713-e24a6144-de10-4677-91f4-2d33456e34f0.png)

**Comment by ksooo** [comment] 2022-06-28 09:40
Have you enabled async epg transfer in pvr.hts (which is the default)? Then it can take some time until the data are delivered from TVH. Have you EPG data for that channel after a Kodi restart?

**Comment by AreaScout** [comment] 2022-06-28 09:42
Ok I switched to that channel and that forced a EPG update, now it crashes, here are the db's and log

https://www.areascout.at/epg_tv_db2.tgz

https://pastebin.com/raw/qApUf5tq

**Comment by ksooo** [comment] 2022-06-28 09:50
The Epg db file does not contain any EPG data. Didn't you say the channel has EPG data?

**Comment by AreaScout** [comment] 2022-06-28 09:51
Yes it had EPG data when I was switching to it, so it was from memory and not DB ?

**Comment by ksooo** [comment] 2022-06-28 09:53
Oh yes, you said it crashed, right, then it crashed before data were committed to the db. Please start Kodi, force update of epg data, but do NOT open the Guide window. Exit Kodi, send the db files.

**Comment by ksooo** [comment] 2022-06-28 10:12
When you exit Kodi, any EPG data that might be in memory will be committed to the EPG db.

**Comment by AreaScout** [comment] 2022-06-28 10:22
Did that already but still no EPG data ...

**Comment by ksooo** [comment] 2022-06-28 12:23
Could you try to apply the following (untested) patch which adds additional logging and send me the log after the crash for the one channel only scenario?

```diff
diff --git a/xbmc/pvr/guilib/GUIEPGGridContainerModel.cpp b/xbmc/pvr/guilib/GUIEPGGridContainerModel.cpp
index 8adcab2056..1a2c3294d7 100644
--- a/xbmc/pvr/guilib/GUIEPGGridContainerModel.cpp
+++ b/xbmc/pvr/guilib/GUIEPGGridContainerModel.cpp
@@ -154,10 +154,15 @@ std::shared_ptr<CFileItem> CGUIEPGGridContainerModel::CreateEpgTags(int iChannel
   const auto tags =
       GetEPGTimeline(iChannel, GetStartTimeForBlock(firstBlock), GetStartTimeForBlock(lastBlock));
 
+  CLog::LogFC(LOGDEBUG, LOGPVR, "##### got {} tags, firstBlock = {}, lastBlock = {}, iBlock = {}", tags.size(), firstBlock, lastBlock, iBlock);
+
   const int firstResultBlock = GetFirstEventBlock(tags.front());
   const int lastResultBlock = GetLastEventBlock(tags.back());
   if (firstResultBlock > lastResultBlock)
+  {
+    CLog::LogFC(LOGDEBUG, LOGPVR, "##### firstResultBlock < lastResultBlock!");
     return result;
+  }
 
   auto it = m_epgItems.insert({iChannel, EpgTags()}).first;
   EpgTags& epgTags = (*it).second;
@@ -167,16 +172,32 @@ std::shared_ptr<CFileItem> CGUIEPGGridContainerModel::CreateEpgTags(int iChannel
 
   for (const auto& tag : tags)
   {
-    if (GetFirstEventBlock(tag) > GetLastEventBlock(tag))
+    CLog::LogFC(LOGDEBUG, LOGPVR, "##### checking tag, start = {}, end = {}",
+                tag->StartAsUTC().GetAsDBDateTime(), tag->EndAsUTC().GetAsDBDateTime());
+
+    const int first = GetFirstEventBlock(tag);
+    const int last = GetLastEventBlock(tag);
+    if (first > last)
+    {
+      CLog::LogFC(LOGDEBUG, LOGPVR, "##### first > last. continue");
       continue;
+    }
 
     const std::shared_ptr<CFileItem> item = std::make_shared<CFileItem>(tag);
-    if (!result && IsEventMemberOfBlock(tag, iBlock))
-      result = item;
+    if (!result)
+    {
+      if (IsEventMemberOfBlock(tag, iBlock))
+        result = item;
+      else
+        CLog::LogFC(LOGDEBUG, LOGPVR, "##### tag is not member of block {}", iBlock);
+    }
 
     epgTags.tags.emplace_back(item);
   }
 
+  if (!result)
+    CLog::LogFC(LOGDEBUG, LOGPVR, "##### returning empty result!");
+
   return result;
 }
 
@@ -188,26 +209,40 @@ std::shared_ptr<CFileItem> CGUIEPGGridContainerModel::GetEpgTags(EpgTagsMap::ite
 
   EpgTags& epgTags = (*itEpg).second;
 
+  CLog::LogFC(LOGDEBUG, LOGPVR, "##### firstBlock = {}, lastBlock = {}, size = {}, iBlock = {}",
+              epgTags.firstBlock, epgTags.lastBlock, epgTags.tags.size(), iBlock);
+
   if (iBlock < epgTags.firstBlock)
   {
+    CLog::LogFC(LOGDEBUG, LOGPVR, "##### GetEpgTagsBefore");
     result = GetEpgTagsBefore(epgTags, iChannel, iBlock);
   }
   else if (iBlock > epgTags.lastBlock)
   {
+    CLog::LogFC(LOGDEBUG, LOGPVR, "##### GetEpgTagsBefore");
     result = GetEpgTagsAfter(epgTags, iChannel, iBlock);
   }
   else
   {
     for (const auto& item : epgTags.tags)
     {
+      CLog::LogFC(LOGDEBUG, LOGPVR, "##### checking tag, start = {}, end = {}",
+                  item->GetEPGInfoTag()->StartAsUTC().GetAsDBDateTime(),
+                  item->GetEPGInfoTag()->EndAsUTC().GetAsDBDateTime());
+
       if (IsEventMemberOfBlock(item->GetEPGInfoTag(), iBlock))
       {
         result = item;
         break;
       }
+      else
+        CLog::LogFC(LOGDEBUG, LOGPVR, "##### tag is not member of block {}", iBlock);
     }
   }
 
+  if (!result)
+    CLog::LogFC(LOGDEBUG, LOGPVR, "##### returning empty result!");
+
   return result;
 }
 
@@ -342,10 +377,12 @@ std::shared_ptr<CFileItem> CGUIEPGGridContainerModel::GetItem(int iChannel, int
   auto itEpg = m_epgItems.find(iChannel);
   if (itEpg == m_epgItems.end())
   {
+    CLog::LogFC(LOGDEBUG, LOGPVR, "##### channel {} not found in epg items, creating tags", iChannel);
     result = CreateEpgTags(iChannel, iBlock);
   }
   else
   {
+    CLog::LogFC(LOGDEBUG, LOGPVR, "##### channel {} found in epg items, getting tags", iChannel);
     result = GetEpgTags(itEpg, iChannel, iBlock);
   }
 
```

**Comment by ksooo** [comment] 2022-06-28 15:15
Is it still reproducible? Can you post another log, please?

**Comment by AreaScout** [comment] 2022-06-28 15:24
Well it is crashing all the time now, it was just working once

Here again a log, it does not distinguish from the last but anyway https://www.areascout.at/kodi_crashlog-20220628_172225.log

**Comment by ksooo** [comment] 2022-06-28 15:36
I'm afraid I have to give up on this one for now. I cannot reproduce the crash, sorry.

One last thing you could do is to test on Nexus.

**Comment by AreaScout** [comment] 2022-06-28 16:07
Hmm thanks anyway for investigating in this, let's see if I can find something now with the more evolved log feature 👍

**Comment by ksooo** [comment] 2022-06-28 17:17
Is the kodi code you are using Matrix 19.4 vanilla or altered in any way?

**Comment by AreaScout** [comment] 2022-06-28 17:31
Of course it is altered, I didn't see any KODI release running with just vanilla code especially on Single Board Computers, even LibreELEC and CoreELEC use there own patches, but you can be 99% sure that this does not produce this errors, it is more likely the underlying OS is the problem as if it's my patches, I use patches for GBM/DRM (VOP2 modifications) and FFmpeg patches.

But of course I can remove it

**Comment by AreaScout** [comment] 2022-06-29 06:50
Nope, I can't at least remove one patch, it would crash KODI after some seconds without it, so thanks again for your investigation but I can't provide you with a vanilla KODI, so I guess I am on my own, I am not afraid ;)

**Closed** 2022-06-29 07:34 UTC
Labels: Component: PVR, v19 Matrix, Triage: Needed

**Comment by ksooo** [comment] 2022-06-29 08:07
Okay, again, I strongly suggest to give Nexus a try.
