### ISSUE TITLE
KODI 19.3 cannot show the CPU info on Minix U9-H

### ISSUE THREAD

**Issue by m2840** [xbmc/xbmc#20693] opened 2021-12-17 18:07 UTC
### Describe the bug

On Minix U9-H the system info of KODI 19.3 does not show the CPU info.
The info was present in Kodi 18.9

## Expected Behavior

Show CPU info

## Actual Behavior

CPU info empty

### To Reproduce

1. Settings\System Information\Hardware
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Minix U9-H, Android 6.0.1, Linux kernel 3.14.29
 - Kodi version: 19.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment] 2021-12-17 18:13
Duplicate of #20619

**Closed** 2021-12-17 18:14 UTC
