### ISSUE TITLE
Playing huge playlists of music causes 100% CPU load due to xbmc.Monitor notifications

### ISSUE THREAD

**Issue by CastagnaIT** [xbmc/xbmc#18437] opened 2020-09-17 17:13 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

If you have a music library with 20000 songs or more 
and you try to play e.g. from SONGS menu, Kodi become unusable
due to high CPU usage (100%) from 30s to also 5 minutes! (depends on number of songs)

This _only_ when there is installed one or more addons/scripts that integrate a `xbmc.Monitor` object as class
that stays in listening of the `onNotification` events.

Why?
`onNotification` method of `xbmc.Monitor` notify the events of the playlist,
In the our case there are more than 20000 songs, a massive playlist of files,
actually Kodi will send to the all Monitors classes, _every single file of playlist_,
then more than 20000 monitor notifications will be sent to all Monitor's that listening on all add-ons/scripts,
this in too short time then cause a very big load to the languageInvoker's that manage the addons and stuck the CPU.

Note that an addon may also have more than a single Monitor in listening so the load will be multiply!!

# UPDATE 07/10/2020

From last nightly test made by @mrblond18 with 19.0-ALPHA1 (18.9.701) Git:20201005-cdcee0d820
the situation is improved a lot, there is no more 100% CPU load to many seconds or minutes,
but anyway 20000 monitor notifications are comuque notables, when all this notifications happen
Kodi slow down for some seconds before return to normal responsive operation
so i leave it open for future Kodi improvements

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi have to be responsive and not stuck on big playlists

## Actual Behavior

When you play a big playlist Kodi become unresponsive
due to high CPU load caused to Monitors in python addons/scripts

## Possible Fix

Some suggestions, not sure if possible,
When there are to play big playlist:
- Manage the python Monitor event notification as asycronous mode
or/and
- Send only one event to all monitor's and pass to "data" argument all the changes when the operations are done (then avoid to send 20000 or more monitor notifications!)

### To Reproduce

1. Kodi 18 or also 19
2. Add music to Kodi library, at least 20.000 tracks to see the better the problem
2. Install this addon test (automatically start a service with more Monitor object that listen)
[test.addon.zip](https://github.com/xbmc/xbmc/files/5240735/test.addon.zip)
3. Open Kodi music library -> and play music by select the "Songs" menu
4. See the high CPU load

When you close Kodi the test.addon service will be closed and will print in the Log,
the number of Monitor notifications received per single monitor object.

### Debuglog

The debuglog can be found here:
https://bartthbo.stackstorage.com/s/qFu8A8sxJqaQBkfv

You can notice in the log all the "SERVICE TEST - RECEIVED" outputs
that are all the events fired to the Monitor object when the CPU was at 100%

at the end of the log you can read the test.addon statistics at line 33919

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I have do a lot of test not understand where the problem came from
after i have found this Kodi issue,
all test are in this NF issue thread (see latest comments):
https://github.com/CastagnaIT/plugin.video.netflix/issues/859

The test was conducted on Kodi 18 and 19, with same behaviour on Linux and Windows

Personally I do not have so many songs,
then if needed @mrblond18, is the user who encountered the problem
and can provide other logs or some info

@mrblond18 has linked also this forum thread where a user in the past has proposed some changes:
https://forum.kodi.tv/showthread.php?tid=213737
seems to be a similar problem, I'm not sure it can help or really same problem

This was my forum thread https://forum.kodi.tv/showthread.php?tid=357047
where i was asking help, but i think that now could be closed

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu/Windows 10
 - Kodi version: 18/19

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by mrblond18** [comment] 2020-09-17 18:39
The problem is not only seen for samba shares, but also for local music files.

The problem is not only seen for mysql libraries but also for local libraries.

**Comment by CastagnaIT** [comment] 2020-09-18 06:42
yes you are right, notifications are sent in any case, i will simplify the thread

**Comment by malard** [comment] 2024-01-28 13:47
this is an excessive amount of content and an extreme edge case (in my opinion) while yes, there is options to improve this messaging making a change like this will require significant regression testing. You are welcome to submit a PR to resolve this for your own requirements, but closing as its not something the team has picked up in 3 years

**Closed by malard** 2024-01-28 13:47 UTC
Labels: Triage: Needed
