### ISSUE TITLE
Translation string for action labels are overwriten with first label

### ISSUE THREAD

**Issue by bigretromike** [xbmc/xbmc#15578] opened 2019-02-22 07:13 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

Having multiply <setting lable="30xxx" type=action>in settings.xml no matter what lable id those use the traslation for all of them are used from ANY first type=action lable in settings.xml they ignore strings.po file.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

String.po should be used for all label action types settings

## Actual Behavior

Only first lable action in translated correct, any other lables with action use same translation as first one ignoring anything in string.po

### To Reproduce

1. make settings.xml for plugin that use type=action with different ids (30000-30200)
2. put translation into /resources/language/resource.language.en_gb/strings.po 
3. enter settings of given plugin video.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/sipilewani.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.1 (stable, nightly 17-02)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ronie** [comment] 2019-02-22 09:15
duplicate of https://github.com/xbmc/xbmc/issues/15252

**Closed by ronie** 2019-02-22 09:15 UTC

**Comment by bigretromike** [comment] 2019-02-22 09:19
@ronie I dont think so, your duplicat is about visible mine is about NON-COPY settings that get wrongly translated.

**Comment by ronie** [comment] 2019-02-22 09:22
it's explained on the other ticket why that is happening:
https://github.com/xbmc/xbmc/issues/15252#issuecomment-455622755

as mentioned in the forum (https://forum.kodi.tv/showthread.php?tid=341187&pid=2825973#pid2825973) you simply need to use unique setting id's and you'll be fine.

**Comment by bigretromike** [comment] 2019-02-22 09:23
so this changed between 17 <-> 18. thanks for clarification
