### ISSUE TITLE
Kodi failing to open - recurring black screen (issue with profiles.xml and guisettings.xml)

### ISSUE THREAD

**Issue by stevooo2** [xbmc/xbmc#16617] opened 2019-09-13 14:01 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

Periodically, the Kodi application fails to open on the Amazon Fire TV Stick (Android), leading to a black screen and Kodi failing to open. This issue occurs approximately 1-3 times per week.

Further investigation suggests this may occur on other platforms (Linux, Windows etc) but at a lesser frequently.

The issue is caused by _profiles.xml_ being 'emptied' / corrupted by an unknown trigger/event, preventing Kodi from loading.  At the same time, _guisettings.xml_ will also be corrupted, but this does not prevent Kodi from opening.

The Fire Stick issue was reported here, with at least 3 users able to reproduce at the same frequency:
https://forum.kodi.tv/showthread.php?tid=346907   There are further reports across the forum and wider web of users reporting the same issue.

_Investigation updates and links to further reports of the issue (including on non-Android platforms) are copied into the ticket below._

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Clicking the Kodi app should successfully load and open the Kodi interface.
Reviewing the profiles.xml and guisettings.xml shows they both have data.

## Actual Behavior

Clicking the Kodi app leads to a black screen and failure to load the app.
Reviewing the profiles.xml and guisettings.xml shows they are both empty (0KB)

## Possible Fix

Deleting or replacing profiles.xml appears to fix the issue.

**_Ideal fixes_** - prevent profiles.xml and guisettings.xml from getting erased e.g. preventing system modifications of the files. Fixing the (unknown) trigger event that erases the files.

**_Workaround fixes_** - automating a restore (from a backup) of these files when the system detects they are 0kb.

### To Reproduce

There is no known trigger/precursor to the following behaviour:
1. Click the Kodi app on the platform
2. *Screen flickers for 1sec as if the app is opening, but immediately returns to the Fire Stick home screen
3. Click the Kodi app again
4. Black screen for a period of time (if waiting long enough, it may return to the platform homescreen)
5. Any subsequent attempts to open the app takes user back to Step 4 (black screen)

*N.B. At Step 2, Sometimes the Kodi loading screen appears briefly, instead of a screen flicker

Reviewing the profiles.xml and guisettings.xml shows they are both empty (0KB)

### Debuglog

Latest debug log (error recurred 16/9/2019)
https://paste.kodi.tv/pixurocoti.kodi

Previous debuglogs:
https://paste.kodi.tv/evubiwiwah.kodi
https://paste.kodi.tv/cecigowise.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

_**Other platforms**_
It appears this issue is most frequent (e.g. 1-3 times per week) on recent versions of the Amazon Fire TV Stick.  However, the same issue has been found on other platforms, albeit potentially less frequently (including original Amazon Fire TV 1st Gen).  In all instances, it is not clear what is corrupting profiles.xml or guisettings.xml

_Android:_
https://forum.kodi.tv/showthread.php?tid=346907
https://forum.kodi.tv/showthread.php?tid=347817
https://forum.kodi.tv/showthread.php?tid=346153
https://forum.kodi.tv/showthread.php?tid=347514
https://forum.kodi.tv/showthread.php?tid=347479
https://forum.kodi.tv/showthread.php?tid=329888
_Windows 10:_
https://www.reddit.com/r/Addons4Kodi/comments/bgak74/kodi_refusing_to_open/
_Linux:_
https://forum.kodi.tv/showthread.php?tid=340912
https://forum.kodi.tv/showthread.php?tid=340909
https://forums.linuxmint.com/viewtopic.php?t=288170
https://forum.libreelec.tv/thread/14811-safe-mode-and-now/
https://forum.libreelec.tv/thread/15112-fatal-unable-to-load-profile/

_**Failed solutions / workarounds**_
The following preventions/workarounds have been tested **without** success:
- On-going clean shutdowns (i.e. ensuring to use power button to exit app)
- Force stop / clear cache
- Powering down Fire Stick and re-launching
- Daily clearing of app cache
- Vanilla installation (no add ons)
- Deleting the addons.db file

_**MyVideos116.db and addons27.db-journal**_
User update 14th Oct -
I launched the Fire Stick this morning (9:15am) and found profiles.xml and guisettings.xml were corrupted _before_ opening the Kodi app.  A few observations:
- _Profiles.xml_ and _Guisettings.xml_ were timestamped (last modified) at 23:44pm.  This is approximately when Kodi was last closed (I can't be certain if it was the exact time, or shortly during/after streaming).
- Having reviewed all the files in the system structure, only two other files were also timestamped 23:44pm - _addons27.db-journal_ and _MyVideos116.db_

Could these files somehow be involved in corrupting _profiles.xml_, or help narrow down the problem? These can be made available on request (I have not attached as I am not certain if they contain sensitive data).

No debug log was available to review (as I had not yet opened Kodi). Is there a way to get a 'deeper' debug log, which captures all events? 

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version - reproduced on: 18.3, 18.4, 18.5
 - Amazon Fire Stick - reproduced on 2nd gen, 2k and 4k sticks (does not appear to occur on 1st gen)
 - Vanilla / stock installation of Kodi
 - Over 3GB space available on Fire Stick
 - No issues reported with other apps on Fire Stick when issue occurs

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by stevooo2** [comment] 2019-10-14 09:35
Team - just a note that I am editing the ticket to include any updates on this issue as they happen.  Please let me know if I should add updates as a new "comment" instead!
Thanks.
Steve

**Comment by adx-git** [comment] 2019-12-01 13:40
I get this issue as well, I think it is related to hard powering off the Fire TV, seems if Kodi is not prober closed the profile file will be invalid.

**Comment by 0xFelix** [comment] 2019-12-01 13:57
I've got this issue as well and it is rather infuriating to recover Kodi with adb every time the TV was shut down.

**Comment by Tigerduck01** [comment] 2019-12-02 07:51
Same here, I guess it could happen is you take the fire tv from power without proper shutting down KODI. However, not other apps get "hurt" by that, only KODI.

**Comment by fritsch** [comment] 2019-12-02 09:19
Kodi requires the OS to properly stop kodi. We don't arbitrarily save settings to disk, it might be a NAND / NOR / something else. You would never pull out the powercable from your desktop computer, right? So don't do it here.

**Comment by stevooo2** [comment] 2019-12-02 09:34
Great to see a lot of activity finally!

Just to chip in - per the ticket, I have tested doing "clean" shutdowns of Kodi when using it, i.e. using the UI power (exit) button to close down the app each time it is opened. This did not prevent the issue from eventually re-occuring.

So If there is any evidence you can provide to demonstrate that behaviour it would be really great to see. It would suggest Kodi's own power (exit) button may require a fix at bare minimum

**Comment by adx-git** [comment] 2019-12-02 09:42
Should it not be possible to prevent the destruction of the file, you have to go at least one step further.
**Kodi should start even with an invalid profile file and not just quit.**

However, especially on the Fire TV, it will often happen that the Fire TV is disconnected directly from the power. 
Other APPs can handle this case too, so there seems to be possible solutions to save the profile file.

**Comment by fritsch** [comment] 2019-12-02 09:59
```
diff --git a/xbmc/profiles/ProfileManager.cpp b/xbmc/profiles/ProfileManager.cpp
index 3b57dcd16f..4e1991ecc8 100644
--- a/xbmc/profiles/ProfileManager.cpp
+++ b/xbmc/profiles/ProfileManager.cpp
@@ -189,6 +189,11 @@ bool CProfileManager::Load()
       ret = false;
     }
   }
+  if (!ret)
+  {
+    CLog::Log(LOGERROR, "Failed to load profile - might be corrupted - falling back to master profile");
+    m_profiles.clear();
+  }
 
   if (m_profiles.empty())
   { // add the master user

```

Should fix it

**Comment by Tigerduck01** [comment] 2019-12-02 10:28
> 
> 
> Kodi requires the OS to properly stop kodi. We don't arbitrarily save settings to disk, it might be a NAND / NOR / something else. You would never pull out the powercable from your desktop computer, right? So don't do it here.

Yes and no. I pull the powecable of my PC after shutdown. The FireTV has no real shutdown, it goes to "sleeping mode" (whatever that is) and then I take away the power. At least that's how I do it. My wife just takes away the power no matter in what state any hardware is ;-)

**Comment by fritsch** [comment] 2019-12-02 10:32
Okay.
https://github.com/xbmc/xbmc/pull/16987 <- will fix it.

It will try to load / parse the file. If that fails, I will whipe it and go back to original master profile. XML recovery is currently out of scope.

**Comment by 0xFelix** [comment] 2019-12-02 10:37
> ```
> diff --git a/xbmc/profiles/ProfileManager.cpp b/xbmc/profiles/ProfileManager.cpp
> index 3b57dcd16f..4e1991ecc8 100644
> --- a/xbmc/profiles/ProfileManager.cpp
> +++ b/xbmc/profiles/ProfileManager.cpp
> @@ -189,6 +189,11 @@ bool CProfileManager::Load()
>        ret = false;
>      }
>    }
> +  if (!ret)
> +  {
> +    CLog::Log(LOGERROR, "Failed to load profile - might be corrupted - falling back to master profile");
> +    m_profiles.clear();
> +  }
>  
>    if (m_profiles.empty())
>    { // add the master user
> ```
> 
> Should fix it

This would result in loading an empty default profile every time, correct? That is at least a workaround but I think we should figure out why the files get emptied in the first place. Does Kodi empty the file deliberately if it is corrupted?

**Comment by fritsch** [comment] 2019-12-02 10:48
Nope. 

See the final fix in the PR.

kodi will check if the file exists. If not a new file is created.
If file exists, but is unparseable, not loadable, kodi will remove it and create a new default profile - only in that case.

**Comment by fritsch** [comment] 2019-12-02 11:04
Someone of you guys can run a test build? I will prepare one for Leia.

**Comment by fritsch** [comment] 2019-12-02 12:15
Tested myself :-) works as it should.

**Comment by 0xFelix** [comment] 2019-12-02 13:10
> Nope.
> 
> See the final fix in the PR.
> 
> kodi will check if the file exists. If not a new file is created.
> If file exists, but is unparseable, not loadable, kodi will remove it and create a new default profile - only in that case.

This would lead to using a default profile every restart given the mentioned use case?

I would regard this as a workaround, but wouldn't it be better to prevent the corruption of the xml files? In previous versions of Kodi (e.g. 17) this was not a problem.

**Comment by fritsch** [comment] 2019-12-02 13:24
You really consider it a use-case to forcefully kill your /sdcard partition and relying on the FireTV itself to "come up" with whatever it can restore?

Kodi corruption is something you see, but imagine how much other files on the stick itself also get broken in the background?

Never the less, if you look at the change again, there are two things:
a) Whenever we are asked to write to disk, we fully flush. Means we ask the filesystem: No matter, what you are currently doing, no matter what you want to optimize so that poor user's NAND is not fucked up and broken after a very short time, fully write the file to disk.
b) We recover if the above fails.

So: Are you volunteer to test?

E.g. Start kodi, create some profiles. Clean exit kodi. <- Mandatory

And then:
pull off the plug 25 times and see how kodi comes back. If it does not come back, please post the log.

**Comment by 0xFelix** [comment] 2019-12-02 13:48
I definitely consier it use-case for the FireTV. There is no real way to shut it down other than turning off the TV it is attached to. As @Tigerduck01 said there is some kind of sleep mode but I guess most users are not even aware that this mode exists.

I'm just curious because with older versions of Kodi this never happened. Something inside of Kodi must have changed too.

I can do some testing later.

**Comment by fritsch** [comment] 2019-12-02 14:07
I will post the build here, after it is finished: http://mirrors.kodi.tv/test-builds/android/arm/kodi-20191202-975d20bb-profileleia-armeabi-v7a.apk (mirror might need to sync) - it's for 32 bit ARM.

Please do as described above. The first clean exit is important.

**Comment by 0xFelix** [comment] 2019-12-02 17:40
I tested with your APK and managed to reproduce the problem with the following steps:

1. Start Kodi
2. Start playback of video file
3. Press "Power Off" button on Fire TV remote
--> Profile is corrupt

Here are log files of two tries:
[kodi-1.txt](https://github.com/xbmc/xbmc/files/3912459/kodi-1.txt)
[kodi-2.txt](https://github.com/xbmc/xbmc/files/3912461/kodi-2.txt)

Thinking again about shutting the Fire TV down hard I realized it even encourages you to do so. As I mentioned before the Fire TV remote has a "Power Off" button (at least newer generations). Pressing this button turns off the attached TV by sending a command via HDMI-CEC.

**Comment by fritsch** [comment] 2019-12-02 17:48
Good, it recovers.

Sadly you did not follow the description I asked for - to at least quite kodi _once_ fine.

I _always_ and only use my FireTV 4K's CEC off Button. I hope your power the FireTV from an external powerplug and not with the USB of your TV, cause then it will completely destroy everything on it, when TV powers off.

**Comment by 0xFelix** [comment] 2019-12-02 20:16
I initially quit Kodi once fine, then tried several times to reproduce the bug. You meant quitting Kodi before each time?

No I do not power the FireTV from an external powerplug. But I'm doing so since several years and never had a problem, even with Kodi. This issue only started recently. Is Kodi really constantly writing to `profiles.xml` and `guisettings.xml` during playback? Seems odd to me.

**Comment by fritsch** [comment] 2019-12-02 20:42
No, it does not. Killing an active partition by what you are doing will damage the device during long-term.

Perhaps the location kodi writes to is already broken?

We can find out. Start kodi, enable debug logging, create your profile, restart kodi. Post the log.

**Comment by adx-git** [comment] 2019-12-03 10:21
While I agree with you, that just turning of the power can and will harm the device, this is common practice for the Fire TV stick.
Actually this is exactly what Amazon is recommending in order to turn off the stick.  
![grafik](https://user-images.githubusercontent.com/42860828/70041954-573ff400-15be-11ea-99de-133e9eecf200.png)
Sorry for the German.

I would not expect that Kodi can handle this behaviour, but maybe it would be possible to at least limit the chance of running into this kind of issues. 
As  @0xFelix  wrote, it did not happen with previous versions of Kodi.

Anyway, thanks a lot for this fast response and modification, I will update to your testing version!

**Comment by fritsch** [comment] 2019-12-03 10:37
This is exactly what the linked pr does:
1) if we write, fully write and flush
2) if broken, fallback

What else do you have in mind?

**Comment by adx-git** [comment] 2019-12-03 10:39
You tell me ^^
I need to give the modification a try and see how Kodi is going to behave on this matter, will feedback you once I got more experience.

Thanks again for this great support!

**Comment by Dnkhatri** [comment] 2019-12-03 16:39
I also get this problem once in a while on my nvidia shield maybe 3-4 times in the last 3-4 months. I did not shut it down or anything. Just changed the hdmi input to something else while kodi was running went back to my shield after an hour or so kodi was not running and would not start. Deleted the gui settings still didnt start then deleted the profiles  xml it started. Both files were empty when I deleted them. I dont even use profiles so why I was effected I don't know. Currently I am using kodi 18.5 latest nightly. 
In my opinion the fallback should be user changeable instead of just the default as redoing all the settings is a pita.

**Comment by Garfield999** [comment] 2019-12-06 13:23
a good solution would be:

if kodi start is good with valid profile and guisettings.xml (filesize>0):
create a copy from the files to profiles.xml.bak and guisettings.xml.bak

if files have 0 bytes while kodi start (or not present):
copy the .bak files back to profiles.xml. and guisettings.xml

**Comment by fritsch** [comment] 2019-12-06 21:00
That's not a good solution at all, especially as it neglegts the chicken - egg issue and only tries to solve exactly one error case, e.g. assumption that when error occurs guisettings.xml / profile.xml is of filesize 0.

a) Filesize does not say anything about its content. 
b) Imagine only "half" of the file" gets written to disk, then filesize is > 0 but then not startable (poweroff in flush) and not recoverable.

Any other ideas?

**Comment by stevooo2** [comment] 2019-12-06 23:08
Hi. First all thanks so much everyone for helping with this issue and contributing!

I really appreciate the proposed fixes. If I'm reading correctly, it is a half-workaround - it will allow Kodi to start (really positive!) but both guisettings and profiles will be reset?

I agree with Garfield's idea in principle (is what I alluded to in the possible fixes in the ticket). I can confirm that when this issue occurs, the file ALWAYS becomes 0kb and contents emptied. I don't know if that helps make Garfield's solution any more feasible? (I'm not very technical!).

Can I ask - are we 100% sure the issue is caused by bad powering down? If so, this suggests there are still processes running after shutdown.... can these not be killed on exiting app too? It will only help when people do clean shutdowns of the app, but that's a good start.

**Comment by Garfield999** [comment] 2019-12-07 01:41
I can agree that the filesize is correct or 0 bytes - never a "half" file.

The question is: Why does/has Kodi open the two xml files (or "reset" them) only since v18. I can't reproduce the error with v17. The backup way, mentioned above, would be only a dirty fix - but workable, but this solves not the cause.

I saw this "error" often in last weeks with firetv 4k generation. Yes, it must be caused by remote power off (hdmi-cec?). I pulled out power supply several times in the past - and never had this issue.

**Comment by fritsch** [comment] 2019-12-07 07:25
@stevooo2 Try to produce the issue with shutting kodi down "normally", e.g. start kodi, stop kodi, start kodi, stop kodi and so on - I don't think you get it broken. We don't talk about shutdown here, but pulling out the powerplug.

@Garfield999 Then just use v17.

**Comment by Tigerduck01** [comment] 2019-12-07 08:33
> 
> 
> @stevooo2 Try to produce the issue with shutting kodi down "normally", e.g. start kodi, stop kodi, start kodi, stop kodi and so on - I don't think you get it broken. We don't talk about shutdown here, but pulling out the powerplug.
> 
> @Garfield999 Then just use v17.

Can confirm, files are either 0 or totally OK. So this backup/restore approach would be very nice indeed. I think what Garfield999 wants to say is that since the problem does not occur at all in v17 there must have been some changes in 18 that make this error possible. That could give a hint where the problem is located. I agree that taking away the power is sub-optimal at least, but when KODI 17 was immune to it and 18 is not, there should be a solution which is related to different behaviour of 17 and 18.

**Comment by Tigerduck01** [comment] 2019-12-07 08:45
> 
> 
> No, it does not. Killing an active partition by what you are doing will damage the device during long-term.
> 
> Perhaps the location kodi writes to is already broken?
> 
> We can find out. Start kodi, enable debug logging, create your profile, restart kodi. Post the log.

About the "long-term" damages of taking away the power: I use a firetv 1st gen where this error only very rarely occurs. It is now more than 5 years old and power loss breaks no app, no file system, not the fire tv itself. Only these two KODI 18 files. I have another FireTV Stick 2k, with daily instant power-loss since 2 years. Never had this problem with KODI 17. Had it now like 5 times with v18. Nothing else broke on the stick since these 2 years of daily power loss. No other app, not the Stick OS itself. I agree that taking away power might be bad and you should not do it just to be on the safe side, BUT: This only damages KODI v18 and NOTHING ELSE so far. If my Stick or FireTv 1st. gen were "already broken" I would expect far more problems than just with 2 files of KODI.

**Comment by fritsch** [comment] 2019-12-07 10:43
Yes - I hear you and want to get that solved as good as possible. Sadly my ideas vanished a bit after reading the code once again the last 30 minutes.

Therefore I prepare a debugbuild for you, that you please test. No need to enable any debugging. Just start the build and post me after the issues happens: kodi.log.old and kodi.log please

Build will result here and has profileleia in name: http://mirrors.kodi.tv/test-builds/android/arm/

Thanks much

**Comment by fritsch** [comment] 2019-12-07 12:18
Test-apk is here: http://mirrors.kodi.tv/test-builds/android/arm/kodi-20191207-1683b317-profileleia-armeabi-v7a.apk - logfiles needed as stated above.

**Comment by fritsch** [comment] 2019-12-08 10:04
Guys any news?

**Comment by Tigerduck01** [comment] 2019-12-09 14:24
> Test-apk is here: http://mirrors.kodi.tv/test-builds/android/arm/kodi-20191207-1683b317-profileleia-armeabi-v7a.apk - logfiles needed as stated above.

Is there away to install test versions next to the stabil version? Or do I have to make a complete backup of my stable version first and write it back after the test?

**Comment by stevooo2** [comment] 2019-12-09 14:55
Hi fritsch. Thanks for your help. Is there a way to reliably to replicate the behaviour, then I can try to test?  I've tried removing the power source while Kodi is running, and that doesn't seem to break it.  Conversely, I've tried the opposite (Always doing clean shutdowns) and this has caused the issue.

The only thing I ever noticed was the more I streamed on Kodi, the more likely it was to happen next time i logged in... but unfortunately don't have free access to use my TV for hours at a time at the moment!

Thanks

**Comment by fritsch** [comment] 2019-12-09 15:15
The above SW is Leia based, means: it does not break your current installation - a backup is always good to have, though.

@stevooo2 I would also like to have this log, cause I think we have some issues when storing the file.

**Comment by fritsch** [comment] 2019-12-12 08:44
Hi guys,

is there any news? I really honestly want to get it fixed for 18.6 - but your input is mandatory for that as I cannot reproduce here.

**Comment by adx-git** [comment] 2019-12-12 09:00
I am still on your first test version and did not have the time to update to the latest test version.
On the first test version I saw that my general profile settings will be preserved, but the language settings.
I will update to the latest test version as soon as possible, but I am afraid it might still take a while.

**Comment by 0xFelix** [comment] 2019-12-12 09:46
Will test this evening!

**Comment by fritsch** [comment] 2019-12-12 16:49
Curious on your results and your logs. I worked with @Rechi today and we changed the logic when profile is stored and if it's saved at all. If nothing changes, no need to rewrite it, etc.

_After_ your logs, please have a try with this build, please: https://jenkins.kodi.tv/job/Android-ARM/15945/artifact/kodi-20191212-089d4b15-PR16988-merge-armeabi-v7a.apk

**Comment by 0xFelix** [comment] 2019-12-12 19:42
With the 18.5 release APK the instructions in https://github.com/xbmc/xbmc/issues/16617#issuecomment-560500884 allow to reproduce the issue easily.

> Test-apk is here: http://mirrors.kodi.tv/test-builds/android/arm/kodi-20191207-1683b317-profileleia-armeabi-v7a.apk - logfiles needed as stated above.

After some trying I was able to reproduce the issue.

[kodi.log](https://github.com/xbmc/xbmc/files/3957537/kodi.log)
[kodi.old.log](https://github.com/xbmc/xbmc/files/3957538/kodi.old.log)

> After your logs, please have a try with this build, please: https://jenkins.kodi.tv/job/Android-ARM/15945/artifact/kodi-20191212-089d4b15-PR16988-merge-armeabi-v7a.apk

Also, after some trying it is reproducible with this build.

[kodi.log](https://github.com/xbmc/xbmc/files/3957501/kodi.log)
[kodi.old.log](https://github.com/xbmc/xbmc/files/3957502/kodi.old.log)

**Comment by fritsch** [comment] 2019-12-12 21:26
Thanks much. 
I did not expect that. First in the "debug" build above, you see the entire, complete profile / guisetting.xml printed into the log - which is exactly the one that got written to disk.

Second in the PR build, we don't touch / overwrite the profile at all - if not changed.

What we see in both old logs:

```
2019-12-12 20:37:45.660 T:5519 WARNING: CPeripheralBusAndroid: failed to remove input device with ID 4 because it couldn't be found
2019-12-12 20:37:46.012 T:5735  NOTICE: CWinSystemAndroid::DestroyWindow
```

**Comment by fritsch** [comment] 2019-12-12 21:30
@Rechi do you have an idea? Might be the shutdown sequence? In the first logs (debug build) I just printed the xml to be written.

**Comment by stevooo2** [comment] 2019-12-12 22:36
Just to say - I've had no success generating the bug in 18.4 leia (my old build), 18.5, nor fritsch's first test build.  I know I keep saying the same thing, but I don't think my issues have been related to cutting the power to the fire stick!

On a separate note.... I don't use profiles, but then I never have.  Has that got something to do with it maybe?  I wasn't using profiles before of course, so i'm guessing it shouldn't have any bearing on the issue (see logs in original ticket)....

Imagine this is no help as I'm pretty sure the bug did not occur, but here are the logs for your first test build (20191207-1683b317):

**Opening before pulling out power**
https://paste.kodi.tv/awoligejiw.kodi
old:
https://paste.kodi.tv/okabegelez.kodi

**Opening after removing power:**
https://paste.kodi.tv/fimopebiyu.kodi
old:
https://paste.kodi.tv/oqiwobusok.kodi

**Comment by 0xFelix** [comment] 2019-12-13 09:38
> What we see in both old logs:

Small detail that I noticed: In kodi.old.log of the PR build the last line is missing a character (DestroyWindo != DestroyWindow). The file never made it to the disk completely... but then it could also be a coincidence and I happened to turn off the FireTV in the exact moment the line was written.

**Comment by fritsch** [comment] 2019-12-13 13:49
Yes, exactly. That's what I have seen as well with the "w" missing. Looking at the shutdown sequence, it might very well be that kodi crashes hard.

Could you by chance also add the adb logcat of such an incident?

**Comment by 0xFelix** [comment] 2019-12-14 15:05
I will do so as soon as I can.

**Comment by pychopaul** [comment] 2019-12-23 17:03
just wanted to add that i have this problem on the fire stick 4k. with kodi 18.5 and i almost always(99%) do a clean exit of kodi through the power menu.  for now, i have backed up the 2 xml files and when they get fuked to zero, i use esexplorer to delete them and replace them with copies of my backups. although it would be nice to have this happen automatically with a script.

**Comment by fritsch** [comment] 2019-12-23 18:32
@pychopaul please try to capture kodi's exit in adb logcat - I think something segfaults there and kodi crashes on exit while having those two files open.

**Comment by 0xFelix** [comment] 2019-12-25 17:44
This is what logcat says on my device when shutting down during playback.

[kodi-logcat.txt](https://github.com/xbmc/xbmc/files/4000700/kodi-logcat.txt)

Kodi crashes after this but I guess the log does not look so helpful.

**Comment by ryamoo** [comment] 2019-12-29 00:49
What skin are people using that have the issue?
I was having consistent black screens. Sometimes after launching, sometimes after pressing the fire tv home button and returning after the fire tv slept, sometimes when backing out of something playing the menus wouldn't load properly, and I couldn't get into settings or the shutdown menu.

I had to go into the Fire TV's application list and force quit. 
Reopening would be okay for a little while.

I saw something in my legs that suggested it was a skin issue, so I deleted/reinstalled and problem remained.
So I've switched skins from the default that I was using (Estuary). 
I've been using the FTV skin and haven't had the problem happen once, it's been working consistently though sleepsnwith Jodi still open, or pressing the Home button during playback. Nothing I try will break it to the black screen again. 
I've switched to Amber skin (because I cant find PVR in the FTV skin), and that's also working without any issues.

**Comment by 0xFelix** [comment] 2019-12-29 09:55
I am using the Confluence skin. Haven't tried another one yet.

**Comment by misery** [comment] 2020-01-10 18:24
I have a native crash and a stacktrace with FireTV 4k and Kodi 18.5.

[crash.log](https://github.com/xbmc/xbmc/files/4047102/crash.log)

**Comment by djhifi** [comment] 2020-02-03 02:19
Is this going to be pushed into 18.6?

**Comment by azx0021** [comment] 2020-02-20 14:11
My fire 4k happens almost every day :/

**Comment by hdhani** [comment] 2020-05-02 16:16
Hi any planned fix for this yet? I can get kodi to boot up by restoring a backup of the profiles.xml file I took but then I lost the skin I applied plus its setting. Having to do a full restore instead when it breaks.

**Comment by fritsch** [comment] 2020-05-02 17:23
Nobody is working on it. As stated multiple times: When I had time to look for it, I could not reproduce - in fact I still run the very same profile / guisettings from that time on my FireTV4K without a single issue.

**Comment by hdhani** [comment] 2020-05-02 17:30
How do you switch off your fire TV? Are you using any skins? For me it only happened once so far in a few months I've been using my firestick 4k. I dont really exit kodi as long as I stopped playing something and then pulled the plug out I was OK.

Also I tried to restore both my profiles and guisettings, when I restore profiles file only kodi boots up but I lose my skin. If I then put guisettings kodi does not boot up anymore... so I can't replace both files with my backed up ones for some reason. Have to do a full restore using adblink.

**Comment by fritsch** [comment] 2020-05-02 17:40
For my normal use-case I use CEC. That turns off my TV and my AVR with pressing FireTV's remote power button. My FireTV stays plugged in all the time.

**Comment by hdhani** [comment] 2020-05-02 17:45
So you have never switched your fire tv off before and just let it sleep? Maybe this is why you cant reproduce the issue.

**Comment by fritsch** [comment] 2020-05-02 17:48
I described my "normal use-case". I am not an idiot :-) - When I tried to catch the bug I played videos, let it sit in main screen and just pulled the powerplug.

**Comment by stevooo2** [comment] 2020-05-02 17:51
I havn't been using Kodi much, but have picked up again the last month (lockdown!) and this issue has resurfaced twice.

Heres what I can tell you (only anecdotal stuff, no new evidence to share):

- I use the OneDrive addon to stream content (movies/TV)
- I've tried 'clean' exits, using CEC, unplugging the device etc.... the issue always resurfaces eventually, with seemingly no link to a particular way of closing Kodi
- If I watch one 4K movie (e.g. >5GB), it is more likely to happen next time I login.  Likewise if I streamed a whole series of a TV show in one go, it is more likely to happen next time I login.

So my working theory is that its something to do with the amount of GB of content streamed or otherwise the amount of minutes spent using the device prior to when the issue occurs....

**Comment by hdhani** [comment] 2020-05-02 18:16
> I described my "normal use-case". I am not an idiot :-) - When I tried to catch the bug I played videos, let it sit in main screen and just pulled the powerplug.

Sorry I didn't mean to call you an idiot. I will try to reproduce myself and report back. Seems like something with this android os on the firestick or maybe ram / storage issues. Unless some kodi code is emptying out files somewhere which would seem strange...

**Comment by I-Cat** [comment] 2020-05-09 19:10
Sounds like a cashe issue. For some odd reason I can't see the debug log can you please post one more log. Thnx

**Comment by stevooo2** [comment] 2020-05-11 15:44
> Sounds like a cashe issue. For some odd reason I can't see the debug log can you please post one more log. Thnx

Hi I-Cat.   Unfortunately I dont have the error logs, but copied this from another site.  This is what the log looks like when the issue occurs:

**ERROR: CProfileManager: error loading special://masterprofile/profiles.xml, Line 0
                                            Failed to open file
NOTICE: special://profile/ is mapped to: special://masterprofile/
FATAL: unable to load profile**

Incidentally a quick google of "cprofilemanager error" will show you how widespread this problem actually is!!

**Comment by hdhani** [comment] 2020-05-11 16:33
> > Sounds like a cashe issue. For some odd reason I can't see the debug log can you please post one more log. Thnx
> 
> Hi I-Cat. Unfortunately I dont have the error logs, but copied this from another site. This is what the log looks like when the issue occurs:
> 
> **ERROR: CProfileManager: error loading special://masterprofile/profiles.xml, Line 0 Failed to open file NOTICE: special://profile/ is mapped to: special://masterprofile/ FATAL: unable to load profile**
> 
> Incidentally a quick google of "cprofilemanager error" will show you how widespread this problem actually is!!
> 
> EDIT: Re it being a cache issue - I also tried an addon on that periodically clears the cache (and clearing it manually via fire stick menu prior to each login). Neither worked!

Interesting, seems like people have this issue on Linux os too. I thought it only happened on a fire tv. The last time it happened to me I checked how much data the kodi app used and it said around 823mb. I dont know if kodi has a data size limit before going crazy and emptying out the profiles.xml file :)

**Comment by stevooo2** [comment] 2020-05-29 07:39
Hi guys. Small update - I've had the issue happen a couple of times recently (Although no luck reproducing when I need it to for logging purposes!).

One thing I noticed - I _think_ profiles.xml and guisettings.xml (and the aforementioned database files myvideos and addons) may be timestamped when a video stream ends but BEFORE Kodi and the Firestick shuts down.  I'm not an expert, but I imagine this would virtually eliminate shutdown of the app as a potential cause, and suggest something wrong with how these files are handled when a stream stops.

I'll post back as soon as I have further info confirming/rejecting the above. I've enabled advanced logging and some of the component logging - Hopefully will help a smarter person than me narrow down the possible cause!

**Comment by hdhani** [comment] 2020-05-29 16:52
I've managed to keep kodi working so far by stopping playback and then pressing the home button on the firestick remote, bringing it out of kodi and back onto the firestick menus and then pulling the plug to turn it off.

But that just might be luck though so far...

**Comment by stevooo2** [comment] 2020-05-30 11:47
Hi guys.  Great news I think - I have found a way to consistently replicate the issue (at least on my side).

I have split this into 2 posts/comments:
- My findings (this post)
- My thoughts (next post)

**1. BEHAVIOUR**
The "last modified" time of the following files changes within 1-5 secs of a video playback ending:
- profiles.xml
- guisettings.xml
- addons27.db-journal
- myvideos116.db

When I switch off my TV/Fire Stick within that 1-5sec period (after the video playback has ended AND Kodi has returned to the menu UI), I will find profiles.xml and guisettings.xml are 0KB.

**2. STEPS TO REPLICATE**
_**It would be great if others can try this**_
1) Play a video file (in my case, I stream a video file from my onedrive, using the onedrive addon)
2) "Stop" the video playback* 
3) Within 3 seconds of the video stopping (as soon as possible AFTER the video player is gone and the Kodi menu appears), immediately switch off the Fire Stick.

*_Note - you must "stop" the video playback, not "pause". I use my TV's remote control via CEC with a stop button to do this._

**3. STEPS THAT WILL NOT REPLICATE**
- Switching off the Fire Stick WITHOUT playing a video file does not replicate the issue
- Switching off the Fire Stick DURING video playback does not replicate the issue
- Switching off the Fire Stick TOO QUICKLY or TOO LONG AFTER stopping video playback, does not replicate the issue
- Pausing instead of stopping the video playback does not replicate the issue

This may help explain why there were previous difficulties replicating the issue!

**4. LOGS & ATTACHMENTS**
Logs 1 and 2:
These logs are taken  AFTER doing the above 'steps to replicate', but BEFORE re-opening Kodi (so the 'black screen' issue HAS NOT yet occurred).  I can also provide copies of the database files and archive cache if that would be helpful.

Log 3:
This log is taken AFTER doing the above 'steps to replicate', and AFTER re-opening Kodi (i.e. so the 'black screen' issue HAS occurred)

NB The timings are accurate to within ~1sec.

**Log 1 notes**
https://paste.kodi.tv/saledudiho.kodi
- Video playback stopped at 10:37:00
- Fire Stick was shut down at 10:37:02
- Profiles.xml was last modified at 10:37:01
- Guisettings.xml was last modified at 10:37:01
- addons27.db-journal was last modified at 10:37:01
- myvideos11.db was last modified at 10:37:01
- archived cache was last modified at 10:36:07
- Kodi.log was last modified at 10:37:01

**Log 2 notes**
https://paste.kodi.tv/sisewexoyu.kodi

- Video playback stopped at 10:45:40
- Fire Stick was shut down at 10:45:41
- Profiles.xml was last modified at 10:45:40
- Guisettings.xml was last modified at 10:45:40
- addons27.db-journal was last modified at 10:45:41
- addons27.db was last modified at 10:44:38
- myvideos11.db was last modified at 10:45:40
- archived cache was last modified at 10:44:41
- Kodi.log was last modified at 10:45:40

**Log 3 notes**
https://paste.kodi.tv/guhijubiye.kodi

This shows the CProfileManager error (re-opening Kodi after the files are corrupted)

**Comment by stevooo2** [comment] 2020-05-30 11:50
**5. MY THOUGHTS**
- I guess Kodi immediately starts to do 'stuff' (I don't know what!) with these files within milliseconds of video playback stopping.  Presumably, interrupting this process may be what corrupts profiles.xml and guisettings.xml

- What is strange is that when the issue _doesn't_ occur, the files will show as modified, but no changes to the contents have actually taken place - they're exactly the same.

- The timing issue explains why some users found the issue occurs less frequently with 'cleaner' or longer shutdowns. Presumably - the longer it takes to go from video playback ending to switching off Kodi, the less likely it is these file changes would be interrupted.

- I have also found instances where the files are timestamped a long while after video playback has finished (and I _think_ - when playback of a video has not even started).  This may explain why the 'clean' shutdowns do not always prevent the issue. I will try to find evidence of this.

- I wonder if this behaviour explains the differences in frequency between different platforms as well as other versions of the Fire Stick.  Perhaps the speed or timing of these file modifications is different depending on the platform, operating systen, what the user has installed, what other apps are running at the time etc.?




**6. APPROACHING A POSSIBLE SOLUTION**
The first question in my mind would be - what is Kodi doing that causes the profiles.xml and guisettings.xml files to be shown as modified?

A quick check shows that the contents of these files remains exactly the same after these 'modifications' have occurred.

Given the contents do not change - perhaps someone can find a way to run those processes as "read only", to prevent them from being modified? That way, if the processes are interrupted, it might not cause the files to become corrupted?

**Comment by thexai** [comment] 2022-05-04 16:41
Seems that related fix https://github.com/xbmc/xbmc/pull/16987 already merged but issue never closed.

Also, the master branch has recently merged several changes related to shutdown sequence in Android, so this is no longer relevant.

**Closed by thexai** 2022-05-04 16:41 UTC
Labels: Component: Settings, Platform: Android, v18 Leia
