### ISSUE TITLE
SQL error after migrating to Kodi 21 beta 2

### ISSUE THREAD

**Issue by bartmans** [xbmc/xbmc#24341] opened 2023-12-28 10:16 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:
SQL error on updating database when installing Kodi 21 beta 2.

Updating took a long time. I still get an SQL error. The MyMusic83 database is created.

2023-12-28 11:04:18.703 T:3412    error <general>: SQL: [MyMusic83] Undefined MySQL error: Code (1060)
                                                   Query: ALTER TABLE song ADD strVideoURL TEXT
                                                   
2023-12-28 11:04:18.703 T:3412    error <general>: Exception updating database MyMusic83 from version 82 to 83
2023-12-28 11:04:18.703 T:3412    error <general>: Error updating database MyMusic83 from version 82 to 83
2023-12-28 11:04:18.732 T:3412     info <general>: Old database found - updating from version 82 to 83
2023-12-28 11:04:18.733 T:3412    error <general>: SQL: Can't create database for copy: 'MyMusic82' (1007)
2023-12-28 11:04:18.733 T:3412    error <general>: Unable to copy old database MyMusic82 to new version MyMusic83

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

After creating MyMusic83 the error should not occur. Is Kodi using the 82 or 83 version?

## Actual Behavior

2023-12-28 11:04:13.675 T:3412     info <general>: MYSQL: Connected to version 10.11.2-MariaDB
2023-12-28 11:04:14.624 T:3412     info <general>: Attempting to update the database MyMusic83 from version 82 to 83
2023-12-28 11:04:15.779 T:3412     info <general>: CMusicDatabase::UpdateTables - updating tables
2023-12-28 11:04:17.281 T:15048    info <general>: CIRServerSuite::Process: failed to connect to irss, will keep retrying every 5 seconds
2023-12-28 11:04:18.703 T:3412    error <general>: SQL: [MyMusic83] Undefined MySQL error: Code (1060)
                                                   Query: ALTER TABLE song ADD strVideoURL TEXT
                                                   
2023-12-28 11:04:18.703 T:3412    error <general>: Exception updating database MyMusic83 from version 82 to 83
2023-12-28 11:04:18.703 T:3412    error <general>: Error updating database MyMusic83 from version 82 to 83
2023-12-28 11:04:18.732 T:3412     info <general>: Old database found - updating from version 82 to 83
2023-12-28 11:04:18.733 T:3412    error <general>: SQL: Can't create database for copy: 'MyMusic82' (1007)
2023-12-28 11:04:18.733 T:3412    error <general>: Unable to copy old database MyMusic82 to new version MyMusic83

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:
2023-12-28 11:04:13.675 T:3412     info <general>: MYSQL: Connected to version 10.11.2-MariaDB
2023-12-28 11:04:14.624 T:3412     info <general>: Attempting to update the database MyMusic83 from version 82 to 83
2023-12-28 11:04:15.779 T:3412     info <general>: CMusicDatabase::UpdateTables - updating tables
2023-12-28 11:04:17.281 T:15048    info <general>: CIRServerSuite::Process: failed to connect to irss, will keep retrying every 5 seconds
2023-12-28 11:04:18.703 T:3412    error <general>: SQL: [MyMusic83] Undefined MySQL error: Code (1060)
                                                   Query: ALTER TABLE song ADD strVideoURL TEXT
                                                   
2023-12-28 11:04:18.703 T:3412    error <general>: Exception updating database MyMusic83 from version 82 to 83
2023-12-28 11:04:18.703 T:3412    error <general>: Error updating database MyMusic83 from version 82 to 83
2023-12-28 11:04:18.732 T:3412     info <general>: Old database found - updating from version 82 to 83
2023-12-28 11:04:18.733 T:3412    error <general>: SQL: Can't create database for copy: 'MyMusic82' (1007)
2023-12-28 11:04:18.733 T:3412    error <general>: Unable to copy old database MyMusic82 to new version MyMusic83

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Windows 11

 - Operating system version/name:
 - Kodi version:
 Kodi 21 beta 2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by the-black-eagle** [comment] 2023-12-28 10:20
Error 1007 is "Database already exists"  I would suggest you log into MariaDB and drop MyMusic83 completely (whilst Kodi is not running) and then re-start Kodi and see if it errors (It shouldn't).

1060 is duplicate column name - again because the db already exists and has had that column added.

**Comment by bartmans** [comment] 2023-12-28 10:39
I dropped the new database and tried migrating again. First run (no MyMusic83 database):
2023-12-28 11:12:05.439 T:13248    info <general>: WakeOnAccess [192.168.178.20] triggered by accessing : MySQL : MyMusic83
2023-12-28 11:12:05.441 T:13248    info <general>: WakeOnAccess success exit, server already running
2023-12-28 11:12:05.442 T:13248    info <general>: MYSQL: Connected to version 10.11.2-MariaDB
2023-12-28 11:12:05.444 T:13248   error <general>: Unable to open database: MyMusic83 [1049](Unknown database 'MyMusic83')
2023-12-28 11:12:05.447 T:13248    info <general>: Old database found - updating from version 82 to 83
2023-12-28 11:12:09.340 T:1924     info <general>: CIRServerSuite::Process: failed to connect to irss, will keep retrying every 5 seconds
2023-12-28 11:25:28.461 T:13248    info <general>: WakeOnAccess [192.168.178.20] triggered by accessing : MySQL : MyMusic83
2023-12-28 11:25:28.464 T:13248    info <general>: WakeOnAccess success exit, server already running
2023-12-28 11:25:28.468 T:13248    info <general>: Attempting to update the database MyMusic83 from version 82 to 83
2023-12-28 11:26:49.320 T:13248    info <general>: CMusicDatabase::UpdateTables - updating tables
2023-12-28 11:26:52.898 T:13248    info <general>: CMusicDatabase::CreateAnalytics - creating indices
2023-12-28 11:30:12.846 T:13248    info <general>: create triggers
2023-12-28 11:31:12.516 T:13248    info <general>: Create native MySQL/MariaDB functions
2023-12-28 11:31:16.916 T:13248    info <general>: create song view
2023-12-28 11:31:16.918 T:13248   error <general>: SQL: [MyMusic83] Undefined MySQL error: Code (1050)
                                                   Query: CREATE VIEW songview AS SELECT         song.idSong AS idSong,         song.strArtistDisp AS strArtists,        song.strArtistSort AS strArtistSort,        song.strGenres AS strGenres,        strTitle,         iTrack, iDuration,         song.strReleaseDate as strReleaseDate,         song.strOrigReleaseDate as strOrigReleaseDate,         song.strDiscSubtitle as strDiscSubtitle,         strFileName,         strMusicBrainzTrackID,         iTimesPlayed, iStartOffset, iEndOffset,         lastplayed,         song.rating,         song.userrating,         song.votes,         comment,         song.idAlbum AS idAlbum,         strAlbum,         strPath,         album.strReleaseStatus as strReleaseStatus,        album.bCompilation AS bCompilation,        album.bBoxedSet AS bBoxedSet,         album.strArtistDisp AS strAlbumArtists,        album.strArtistSort AS strAlbumArtistSort,        album.strReleaseType AS strAlbumReleaseType,        song.mood as mood,        song.strReplayGain,         iBPM,         iBitRate,         iSampleRate,         iChannels,         song.strVideoURL as strVideoURL,         album.iAlbumDuration AS iAlbumDuration,         album.iDiscTotal as iDiscTotal,         song.dateAdded as dateAdded,         song.dateNew AS dateNew,         song.dateModified AS dateModified FROM song  JOIN album ON    song.idAlbum=album.idAlbum  JOIN path ON    song.idPath=path.idPath
                                                   
2023-12-28 11:31:16.918 T:13248   error <general>: Exception updating database MyMusic83 from version 82 to 83
2023-12-28 11:31:16.918 T:13248   error <general>: Error updating database MyMusic83 from version 82 to 83
2023-12-28 11:31:16.919 T:13248    info <general>: WakeOnAccess [192.168.178.20] triggered by accessing : MySQL : MyMusic81
2023-12-28 11:31:16.922 T:13248    info <general>: WakeOnAccess success exit, server already running
2023-12-28 11:31:16.924 T:13248   error <general>: Unable to open database: MyMusic81 [1049](Unknown database 'MyMusic81')
2023-12-28 11:31:16.927 T:13248   error <general>: Unable to open database: MyMusic80 [1049](Unknown database 'MyMusic80')
2023-12-28 11:31:16.929 T:13248   error <general>: Unable to open database: MyMusic79 [1049](Unknown database 'MyMusic79')
2023-12-28 11:31:16.932 T:13248   error <general>: Unable to open database: MyMusic78 [1049](Unknown database 'MyMusic78')
2023-12-28 11:31:16.934 T:13248   error <general>: Unable to open database: MyMusic77 [1049](Unknown database 'MyMusic77')

On second run start is delayed and eventually I get the same error message:
2023-12-28 11:32:50.585 T:15960    info <general>: Attempting to update the database MyMusic83 from version 82 to 83
2023-12-28 11:32:54.257 T:10200    info <general>: CIRServerSuite::Process: failed to connect to irss, will keep retrying every 5 seconds
2023-12-28 11:36:10.120 T:15960    info <general>: CMusicDatabase::UpdateTables - updating tables
2023-12-28 11:36:11.763 T:15960   error <general>: SQL: [MyMusic83] Undefined MySQL error: Code (1060)
                                                   Query: ALTER TABLE song ADD strVideoURL TEXT
                                                   
2023-12-28 11:36:11.763 T:15960   error <general>: Exception updating database MyMusic83 from version 82 to 83
2023-12-28 11:36:11.763 T:15960   error <general>: Error updating database MyMusic83 from version 82 to 83
2023-12-28 11:36:11.767 T:15960    info <general>: Old database found - updating from version 82 to 83
2023-12-28 11:36:11.768 T:15960   error <general>: SQL: Can't create database for copy: 'MyMusic82' (1007)
2023-12-28 11:36:11.768 T:15960   error <general>: Unable to copy old database MyMusic82 to new version MyMusic83

**Comment by bartmans** [comment] 2023-12-28 10:44
And when I try to access to Music Kodi crashes and gives up.

**Comment by the-black-eagle** [comment] 2023-12-28 10:49
Those errors (on the first run) still indicate the presence of another database.  1050 is Table already exists.

Please do the following.  Put  Kod into debug mode and then close iti - Log into mariadb and do
`show databases;` and post the output from that command.  Then,  do `drop database MyMusic83;`  It should return something like "Query OK, 23 rows affected (2.188 sec)"
Verify that the db has indeed gone using `show databases;` again.
Log out of mariadb and start kodi.  Post the debug log to a pastebin site (eg https://paste.kodi.tv/) and put the link to it here.

Thanks

**Comment by bartmans** [comment] 2023-12-28 11:56
MariaDB command
https://paste.kodi.tv/poyenogoye 

Kodi first run
https://paste.kodi.tv/amirojaxuq.kodi

Kodi second run
https://paste.kodi.tv/rufuqalagu.kodi

**Comment by the-black-eagle** [comment] 2023-12-28 12:45
I can't reproduce that here :(  See relevant log https://paste.kodi.tv/aqokuyeban

The only difference I can really see is that in my log, the music database function `GetSongsCount()` fails with an error.  This is to be expected as the `song` table has not yet been created.  (Lines 31-34 in my log)

However, there is no such error in your log.  It should be around line 826 in your first log.  That still, to me, indicates that the tables still exist despite the db being dropped (or appearing to be dropped).  That is also borne out by the error when trying to create the songview (first thing created) as the error is that the view still exists.

This can happen if you have changed the db engine or your db schema has been corrupted.   Also if you have updated mariadb recently you must run mysql_upgrade before starting Kodi and trying to upgrade.

Although my upgrade went perfectly just by dropping the db and starting Kodi, I would always advise that MySQL/MariaDB is stopped and restarted after dropping the database.

**Comment by bartmans** [comment] 2023-12-28 14:24
Okay. I solved my issue by renaming MyMusic82, removing MyMysic83, running Kodi and the renaming MyMusic82 to its original name.

When not migrating from 82 --> 83 Kodi succesfully build the new database.

**Closed** 2023-12-28 14:27 UTC
Labels: Triage: Needed
