### ISSUE TITLE
Audio stutter on win11 due to broken Directsound

### ISSUE THREAD

**Issue by MoetaYuko** [xbmc/xbmc#20567] opened 2021-11-23 14:08 UTC
### Describe the bug
After moving from win10 to win11, I can no longer enjoy videos on kodi. Audio stutters all the way including UI sound. A workaround I found is switching the audio backend to WASAPI, where Directsound, the *default* choice, seems to be broken. **Both the UWP version from M$ store and the .exe installer suffer from the same problem.**

## Expected Behavior

Audio plays normally.

## Actual Behavior

Both UI sound and video sound stutter all the way. 

## Possible Fix

No idea.

### To Reproduce

1. Fresh install Kodi 19.3 on a win11 machine.
2. Play a random video or use arrow keys to browse the menus to trigger UI sound.

### Debuglog

The debuglog can be found here, which is full of:
```
WARNING <general>: CWin32DirectSound::GetSpace - buffer underrun - W:16248, P:4294965000, O:384.
```
Full log: https://fars.ee/nYT6.log (captured from a fresh UWP install)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [X] Windows
 - [X] Windows UWP

 - Operating system version/name: Windows 11 Home 21H2 22000.348
 - Device: Surface Pro 7
 - Kodi version: 19.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by thexai** [comment] 2021-11-25 14:21
Tested on Intel NUC8i3BEK + Windows 11 + DirectSound and I can **not** reproduce.

**Comment by MoetaYuko** [comment] 2021-11-25 14:28
Could this be a hardware-specific issue? However, Kodi is the only broken app I observed so far. My win11 is clean installed via official iso downloaded from MS website and all drivers are automatically installed via windows update, so it can't be an issue due to improper OS configuration.

**Comment by thexai** [comment] 2021-11-25 14:34
Try set default audio device to "Speakers - 扬声器 (2- Realtek High Definition Audio(SST))"

Maybe only occurs with  "Headphones - 耳机 (EDIFIER TWS1 Pro)"

Anyway log posted is no debug log...

**Comment by MoetaYuko** [comment] 2021-11-25 16:08
> Try set default audio device to "Speakers - 扬声器 (2- Realtek High Definition Audio(SST))"
> 
> Maybe only occurs with "Headphones - 耳机 (EDIFIER TWS1 Pro)"

Wow exactly, Directsound works well with the speaker. It's problematic with my BT headset. Unpairing and re-pairing didn't help. What else should I provide to assist in diagnosing?

**Comment by thexai** [comment] 2021-11-25 16:18
Is not Kodi bug. Is specific hardware/driver issue. I am going to close this as github issues is not for support.

Please use forum (https://forum.kodi.tv/forumdisplay.php?fid=59) for support.

**Comment by thexai** [comment] 2021-11-25 21:43
Windows 11 update KB5007262 may fix this issue.

**November 22, 2021—KB5007262 (OS Build 22000.348) Preview**

> Updates volume control issues that affect Bluetooth audio devices.

https://support.microsoft.com/en-us/topic/november-22-2021-kb5007262-os-build-22000-348-preview-7f3e18d7-4189-4882-b0e9-afc920253aee

**Comment by MoetaYuko** [comment] 2021-11-26 02:05
Mine is already 22000.348, but pretty sure the issue persists before and after this update.

**Comment by richardsampson** [comment] 2022-04-01 11:29
I also have this issue on a desktop running Windows 11 (version 22000.593) with Kodi 19.4 and using Sony WH-1000XM3 bluetooth headphones. Switching from DirectSound to WASAPI in Kodi does seem to fix it. The exact same configuration with DirectSound works fine on Windows 10 so it definitely seems to be a Windows 11 problem.

**Comment by antiphon0** [comment] 2022-09-18 20:34
can confirm this happens on Win 11, also using bluetooth headphones.

**Comment by Henrique-Tadeu** [comment] 2023-03-22 01:26
Same problem here with BT headphone (Soundcore Q30) on Win11. Win10 worked perfeclty, but win11 only works with WASAPI. Any fix? I really need directsound to work as i'm wanting to use with 'dolby atmos for headphones'.

**Comment by webitube** [comment] 2023-12-09 23:58
I'm using **Kodi 20.2** with a **Sony WH-1000XM4** with a **bluetooth** connection on **Windows 11** and have the same stutter issue.
I've had to set to **wasapi** and **Fixed 5.1** before it would not stutter. 
As a bonus, **Dolby Atmos for Headphones** works fine with this setup.

**Comment by MoetaYuko** [comment] 2023-12-10 04:22
@thexai please reopen this issue. It's confirmed by different people and happening on various hardware.

**Comment by webitube** [comment] 2023-12-22 19:01
I've found a strange workaround which has worked reliably so far. I call it "priming the pump." 
Basically, play a different video (or the same video) in a different program. (I was using [mpc-hc](https://github.com/clsid2/mpc-hc/releases).) Play the video (with sound on) for about a minute. Then, play the original video in Kodi.

**Comment by denny099** [comment] 2023-12-29 16:22
I'm using Kodi 20.2 with a Sony WH-1000XM4 with a bluetooth connection on Windows 11 and have the same stutter issue as well.

**Comment by FrankYu2018** [comment] 2024-02-15 23:50
**Solution** 

To use WASAPI (Windows Audio Session API) instead of DirectSound in Kodi, you'll need to adjust the audio settings within Kodi. Here's how you can do it:

1. **Open Kodi:** Launch Kodi on your system.

2. **Navigate to Settings:** Go to the Kodi settings menu. You can usually find this by clicking on the gear icon in the Kodi home screen.

3. **Go to System Settings:** Depending on your version of Kodi, you may need to select "System" or "System Settings" from the settings menu.

4. **Select Audio Settings:** Within the System Settings menu, look for an option related to audio or sound settings. It might be labeled as "Audio" or "Audio Settings."

5. **Choose Audio Output Device:** Look for an option to select the audio output device. This is where you can choose between different audio APIs, including DirectSound and WASAPI.

6. **Select WASAPI:** If WASAPI is available as an option, choose it from the list of available audio output devices. It may be listed as "WASAPI" or "Windows Audio Session API."

7. **Save Settings:** Once you've selected WASAPI as the audio output device, make sure to save your settings. This might involve clicking on a "Save" or "Apply" button within the Kodi settings menu.

8. **Restart Kodi:** After saving your audio settings, it's a good idea to restart Kodi to ensure that the changes take effect.

By following these steps, you should be able to switch Kodi's audio output from DirectSound to WASAPI. Keep in mind that the availability of WASAPI as an option may depend on your system configuration and the version of Kodi you're using.

**Comment by kbjunky** [comment] 2024-02-23 11:23
You have to uninstall Realtek Audio Console if you happen to have it.

**Closed** 2024-04-23 14:38 UTC
Labels: Platform: Windows, Component: Audio, Triage: Has proposed fix, v20 Nexus, v21 Omega, v22 "P"

**Comment by WyattGorman** [comment] 2024-06-21 14:07
Came here to say I'm having this exact problem. WASAPI is the only audio output that doesn't stutter, but it doesn't then work when other audio is playing.

**Comment by thexai** [comment] 2024-06-21 14:58
Issue is fixed and fix is included in v22 nightlies:

https://mirrors.kodi.tv/nightlies/windows/win64/master/

**Comment by brupec** [comment] 2024-07-06 21:22
Hi all, tested on latest 22 nightly, sounds now outputs constantly but lot of glitch/pops (not sure how to say it) but to make it simple, quality of sound is bad 😢

**Comment by fritsch** [comment] 2024-07-07 08:50
Can you post a log, please? I suspect this is underruns (due to buffer / period configuration) ... let's see.

**Comment by brupec** [comment] 2024-07-07 11:50
Indeed my friend, there seems to be buffers underrun.

here is the log of yesterday

Le dim. 7 juil. 2024 à 03:51, Peter Frühberger ***@***.***> a
écrit :

**Comment by fritsch** [comment] 2024-07-07 12:42
The attachment, did not make it. Please reply on github and post a link to a paste.kodi.tv url.

**Comment by brupec** [comment] 2024-07-07 13:40
oups sorry, seems it didn't go via email. here it is
[kodi.old.log](https://github.com/user-attachments/files/16119495/kodi.old.log)

**Comment by brupec** [comment] 2024-07-07 13:41
https://paste.kodi.tv/uwuxadozed.kodi

**Comment by thexai** [comment] 2024-07-20 16:01
@brupec

Can you test this new build: 
https://forum.kodi.tv/showthread.php?tid=376406&pid=3204473#pid3204473

**Comment by brupec** [comment] 2024-07-21 04:20
> @brupec
> 
> Can you test this new build: https://forum.kodi.tv/showthread.php?tid=376406&pid=3204473#pid3204473

Hi

Works perfect for me :-)
