### ISSUE TITLE
UX improvements for Kodi mute/unmute functionality

### ISSUE THREAD

**Issue by krystalcode** [xbmc/xbmc#20887] opened 2022-01-24 02:36 UTC
### Describe the bug
Ability to mute/unmute by clicking the relevant icon.

This is a follow up on this forum post: https://forum.kodi.tv/showthread.php?tid=366641

It is not necessarily obvious to new users that with certain keyboard shortcut you can mute/unmute Kodi. This can cause accidental muting from which there is no obvious way to recover because you are not aware of what exactly happened.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I'd expect to be provided a more obvious 

## Actual Behavior

I accidentally muted Kodi without being aware of it. I spent a lot of time troubleshooting thinking there is a problem with connecting to the sound device after an upgrade that problem coincided with, and stopped using Kodi for quite some time until figuring out what the problem was.

## Possible Fix

* Have a text notice to the right of the icon, if it fits well in the UI e.g. "muted".
* Alternative to the above, show a text with the click action i.e. "mute/unmute" when hovering the mouse above the icon. Potentially display the shortcut as well.
* Kodi should unmuted when the user clicks on the icon.
* The icon could be always there so that the user is made aware of such functionality.

### To Reproduce

1. Mute Kodi using `F8`.
2. Observe that there is no obvious notification to the user that there is no sound because Kodi is muted.

### Debuglog

The debuglog can be found here:

### Screenshots
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment] 2022-01-24 06:37
This is not a bug. 

Kodi works as designed in that case and therefore this is a feature-request or (as the title says) an improvement. Both should have been done on the forums. Some things need to be done in core, some things need to be done on the skin itself. 

But I'll try to answer on the suggestions

> Alternative to the above, show a text with the click action i.e. "mute/unmute" when hovering the mouse above the icon. Potentially display the shortcut as well.

Might have to be done in core, but I doubt that will ever happen as we do not show any context-texts for section if you hover the mouse over it. Also be aware that this probably need to be done differently on the systems we support Kodi on and some don't even have mouse support (Android for example).

> Have a text notice to the right of the icon, if it fits well in the UI e.g. "muted".

What sense would a text next to a mute icon make? The icon is clear by itself and if you don't get what the icon means, how much would a text next to it help?

> Kodi should unmuted when the user clicks on the icon.

That might be possible. But as said, as that's a feature request and it has to be done on the skin, I would suggest to post that request here: 

https://forum.kodi.tv/showthread.php?tid=262603

Which is the skin Estuary feature request section. 

Closing this now

**Closed by DaVukovic** 2022-01-24 06:37 UTC
Labels: Triage: Needed
