### ISSUE TITLE
[Estuary] PVR Channels: top/bottom entries obscured by text overlays

### ISSUE THREAD

**Issue by biberesser** [xbmc/xbmc#19144] opened 2021-01-30 04:40 UTC
## Bug report
**Estuary Skin: PVR/LiveTV Channels List View:**
When using PGUP/PGDOWN keyboard shortcuts in the channels list,
both the top and the bottom TV channel entries are sometimes obscured by text and "fade out" overlays.
Some channel names/numbers can never be read when "paging" up and down.

Remark: This is less of a problem when smoothly scrolling the list vertically instead of "paging".

## Expected Behavior
All of the listed channels are always clearly visible and not never covered by GUI overlays making it illegible.

## Actual Behavior
The topmost list slot is sometimes hidden by the PVR Channels view's title/label overlay text and "fade out".
The bottom list slot is hidden by "Options" overlay text and "fade out".

## Possible Fixes
* a) Reduce number of visible vertical list slots by 2 (do not use current top and bottom slots anymore).
* b) Reduce the list number of items "scrolled per page" value by 1 or 2, so when "paging" the overlayed items are still obscured sometimes, but are at least once properly visible.
* c) move or remove the current overlays in the problematic positions (see screenshots)

### To Reproduce,
* open the PVR Channels List View
* use PGUP/PGDOWN keyboard shortcuts to scroll by page up and down
(requires PVR/LiveTV configured with more than ~20 channels (multiple pages of channels))

### Debuglog
(debug log not relevant here I think - this is a layout problem)

### Screenshots
* [Screenshot: initial view: only bottom entry obscured](https://ibb.co/xqWJtXv)
* [Screenshot: after pressing PGDOWN: top and bottom entry obscured](https://ibb.co/80t5HBt)

## Additional context or screenshots
for comparison:
Confluence Skin only uses 9 vertical channel slots @ 1080p. No problem here.
[Screenshot:  PVR Channels view, using reduced number of items (no problem here)](https://ibb.co/s6RFhG5)

### Your Environment
* Operating system: Windows 10
* Kodi versions: 18.x, 19.x

**Comment by ksooo** [comment] 2021-01-30 07:30
This is by design. If you don't like it, you need to use another skin.

**Comment by biberesser** [comment] 2021-01-30 08:39
Sad to hear :(

This issue makes using a **TV remote** (Harmony etc.) also way more clunky,
since you always overscroll 2 channels when quickly paging through the channels :(
(I mostly use Kodi to watch TV.)

**Comment by ksooo** [comment] 2021-01-30 10:23
Don't mix different problems in one issue, please. 

If you have a problem with "overscrolling 2 channels", this is unrelated to the skin design and you should open a separate issue for that.

**Comment by biberesser** [comment] 2021-01-31 10:26
A minimal fix without changing the visible layouts could be to change only the _number of lines scrolled when paging_ by 1 or 2 items, I think.

**Comment by ksooo** [comment] 2021-01-31 10:29
> A minimal fix without changing the visible layouts could be to change only the number of lines scrolled when paging by 1 or 2 items, I think.

 That's not so easy to implement as you might think. Nothing that can be done by a skinner, afaik.

**Comment by biberesser** [comment] 2021-01-31 10:35
OK, I see :(
This problem is the only reason for not using Estuary, which is really nice overall otherwise.
Then this means Confluence forever for me, it seems.
Thank You anyway.

**Comment by ksooo** [comment] 2021-03-27 11:52
Fixed by #19471. ;-)

**Comment by biberesser** [comment] 2021-03-27 12:23
Awesome, thank you for reconsidering the issue!
Will try out an upcoming v20 nightly soon and report back if the issue should still manifest.

**Comment by ksooo** [comment] 2021-03-27 13:10
> if the issue should still manifest.

 Be assured it is fixed. ;-)

**Closed** 2021-04-06 18:41 UTC
