### ISSUE TITLE
Kodi crashes when accessing the PC through Remote Desktop

### ISSUE THREAD

**Issue by TheArgentinian** [xbmc/xbmc#25634] opened 2024-08-19 01:09 UTC
### Describe the bug
Kodi closes itself when you access the computer its running on through a mobile device using remote desktop. This did not happen with kodi 21 and older versions. 

## Expected Behavior
For coding to keep running. 

## Actual Behavior
Kodi crashes immediately. 

### To Reproduce
Use the official Microsoft Remote desktop app on an Android device to access your computer. 

 - Operating system version/name: Windows 11

 - Kodi version: 21.1

**Comment by thexai** [comment] 2024-08-19 16:13
Duplicate of https://github.com/xbmc/xbmc/issues/25635

**Closed by thexai** 2024-08-19 16:13 UTC
Labels: Ignored rules, Triage: Needed

**Comment by raymondjpg** [comment] 2024-08-21 01:40
Same here with production release of 21.1. In rdp session Kodi closes immediately after starting.

**Comment by thexai** [comment] 2024-08-25 07:34
@TheArgentinian or @raymondjpg 

Would be good if can you test this build and confirm is working:
[KodiSetup-20240824-17913b84-fix-crash-rdp-Omega-x64.exe](https://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20240824-17913b84-fix-crash-rdp-Omega-x64.exe)

**Comment by snakegtx** [comment] 2024-08-25 08:17
Workaround: set remotedesktop audio to be played on the remote computer

**Comment by thexai** [comment] 2024-08-25 08:49
Yeah, but want a confirmation if this build fix the issue without the workaround 🙂

**Comment by snakegtx** [comment] 2024-08-26 09:25
It work for me too, no crashing!

**Comment by Dronkie007** [comment] 2024-09-06 06:31
> Workaround: set remotedesktop audio to be played on the remote computer

Thank you. This fixed my problem. +rep
