### ISSUE TITLE
Kodi Matrix tvOS live tv some channels no video when hardware acceleration on

### ISSUE THREAD

**Issue by BTopbas** [xbmc/xbmc#18287] opened 2020-08-13 07:16 UTC
### Describe the bug
When Allow hardware accelerator VTBDecoder ON some tv channels not opening (only audio no display)(I am using tvheadend). When this setting is OFF all channels open with no problem but other video files like mkv stuttering. So need to ON again.

## Expected Behavior
When hardware accelerator VTBDecoder ON live tv channels and other video files need smooth playback.

## Actual Behavior
When hardware accelerator VTBDecoder ON some live tv channels not opening video. When hardware accelerator VTBDecoder OFF all live tv channels opening but other video files not smooth playback.

## Possible Fix
Guess this is the same problem as we had with the Kodi 17 build where hw decoding didn’t work for interlaced content. That was bypassed/worked around by disabling hw decoding for interlaced content in general afaik. (CPU handles this fine)

Here are similar fixes on Kodi 17.6 tvOS version:
https://github.com/Memphiz/xbmc/commit/e505fbfa6411e2e1b1569bc4ee647ef5f4f40fe8
https://github.com/Memphiz/xbmc/commit/a58fd7b6bc9bfb6c924fa2255ae6fdc8187ecf00

### To Reproduce

1. Player Setting -> hardware accelerator VTBDecoder -> ON
2. Try some live tv channels
3.

### Your Environment
Used Operating system:

-Apple TV 4K

 - Operating system version/name: tvOS 13.4.5
 - Kodi version: 19.0-ALPHA-1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by sy6sy2** [comment] 2020-08-27 15:37
May be useful:

* http://www.openradar.me/30669495
* https://stackoverflow.com/questions/29142472/ios-vtb-decoder-for-field-interlaced-h264

I will try to reproduce your issue when at home on the Apple TV.

**Comment by sy6sy2** [comment] 2020-08-27 17:37
Apple TV 4K tests:

* French Live TV (TNT-HD) from TVheadend (1920x1080i H.264) No problem: https://paste.kodi.tv/cuqoqaxare.kodi
* This [video](https://forum.kodi.tv/showthread.php?tid=312805&pid=2970804#pid2970804l): Black screen: https://paste.kodi.tv/hibiduhape.kodi

**Comment by sy6sy2** [comment] 2020-09-01 07:43
Hi, so I can confirm that this issue is valid for both iOS and tvOS devices.
I you said, VideoToolbox failed to hardware decode some interlaced H264 videos on iOS and tvOS devices but not on macOS.

A patch is provided here: https://patchwork.ffmpeg.org/project/ffmpeg/patch/20170926003631.55571-3-ffmpeg@tmm1.net/#16694

I applied it for us, Jenkins is currently building a test build with this patch for Apple TV ; I will paste the deb link here a soon it will be available.

**Comment by sy6sy2** [comment] 2020-09-01 10:18
@BTopbas If you want to try this build: http://mirrors.kodi.tv/test-builds/darwin/tvos/kodi-20200901-582b190d-ios-fix-interlaced-tvos.deb
There is "iOS" in the filename but this build run only on Apple TV 😉 
Thank you!

**Comment by BTopbas** [comment] 2020-09-01 10:42
@sy6sy2 I tried this build on my Apple TV 4K and I can confirm the issue is fixed. Thank you for your works!

**Comment by sy6sy2** [comment] 2020-09-01 10:57
Perfect! Thank you for your fast test. I will see to include the patch in master and will close this issue when it's done.

**Comment by BTopbas** [comment] 2020-10-10 06:47
I know you are trying to fix this issue in the core and system-wide. But while searching for a solution, we can detect live tv entry and bypass hardware acceleration automatically? I think all channels okay with it. Not so much 4k, no hdr on live tv's. So we need to detect if the stream opened in PVR and bypass/temporality disable hardware accel. If stream not from PVR then continues with hardware accel. I manually switch on and off every time and this is annoying...

**Comment by sy6sy2** [comment] 2020-10-12 15:47
Yes this handle should resolve the issue, but this is not a real fix on the long run 😕
I did not have time to try again to resolve the issue on ffmpeg side (busy with my thesis ATM).

I am also facing this issue with some French live TV channels, and I just set the HW setting to false everytime and I have no issue to watch movies.
Do you have any issue when you let this setting off?

**Comment by BTopbas** [comment] 2021-06-05 19:49
Nearly 1 year ago I have opened this issue. And this issue still exists on the latest version for tvos. Please, somebody, add this logic: if stream live tv (I am sure there is a method to check live tv streams) automatically disable hw acceleration..

**Comment by JanSchr** [comment] 2022-11-01 15:23
Still persists, disabling the VTB Decoder is also not really an option because a lot of videos (especially 4k ones with high bitrates) are stuttering badly with software decoder (on apple tv 4k second gen).

Would be awesome if this could be fixed.

**Comment by loadamasta** [comment] 2023-03-06 18:34
I have this issue, too. Without that, Apple TV 4K would be the best Kodi hardware...

**Comment by matthijst** [comment] 2023-07-28 22:13
Have this issue as well. Apple TV 4K.
When playing downloaded videos with high bitrate.

**Closed** 2024-02-09 09:18 UTC
Labels: Component: Video, Platform: iOS, v19 Matrix, Platform: tvOS
