### ISSUE TITLE
Kodi 18.1 problem with backup/restore to another device

### ISSUE THREAD

**Issue by xalaros** [xbmc/xbmc#15911] opened 2019-04-13 14:01 UTC
I have made backup of my Kodi 18.1 installation on Android device and trying to restore it to another Android one or PC Windows, I have problems with binary addons (Inputstream adaptive, RTMP Input, Archive Support for subtitles and so on) not enabled although at initial backup are enabled or can't install it from official Kodi repo appearing error.
The methods making backup were the easy one copy-paste folders addons & userdata or making backup via wizard I have after first converted paths to special and then restore it but not changed at all.
Any possible fix for this?

**Comment by chewitt** [comment] 2019-04-13 16:35
Kodi has never supported backup/restore between different platforms so you should expect "copy and paste" data migrations to be troublesome. There are numerous areas of Kodi config where /linux/paths/ from Android will not play with C:\Windows\Paths\ and binary addons compiled for Android are not going to work on Windows (and maybe not different version so Android either). As this is PEBKAC and not a bug I am closing the ticket. Please use the forums for further advice and support on what data you can migrate and how to do it.

**Closed by chewitt** 2019-04-13 16:35 UTC
Labels: Triage: Needed
