### ISSUE TITLE
Aspect Ratio (Zoom) Dialog showing all values as zero (v18.1 build 20190311)

### ISSUE THREAD

**Issue by emadmahdi** [xbmc/xbmc#15733] opened 2019-03-13 00:30 UTC
While playing any video and pressing the keyboard shortcut "Z" to change the AspectRatio (Zoom) ... The dialog is working perfectly but showing all values as zeros ... i used to see actual numbers while using kodi v17.6

I tested this on Android using fresh new installation of ... Kodi v18.1 build 20190311 ... using the default Estuary skin and same problem using a variant of skin "Metropolis" on Android 7.1.1 and also Android 6.0

**Comment by KarellenX** [comment] 2019-03-13 04:36
Hello @emadmahdi

I realise that this is your first ever post on github, but we have a requirement that all Issues are submitted using the template and all questions are answered.

A screenshot showing the problem is required, and a debug log is also useful.

I'll mark this issue as "Ignored Rules" which will be removed once the post is submitted correctly, or it will be closed in a week.

Thanks.

**Comment by KarellenX** [comment] 2019-03-13 04:39
I'll help you out and upload an image for you...

![z-log](https://user-images.githubusercontent.com/44626605/54254013-17575d80-45a6-11e9-9465-1b12aabb98b0.jpg)

**Comment by emadmahdi** [comment] 2019-03-13 17:52
Hello @KarellenX 

Thanks for the photo ... i tried to upload a photo but i did not know how to do that in github issues

As for the logs ... i did not find any log lines generated by kodi while pressing on "Z" or while changing the aspect ratio

As for the problem ... it is clear that the second line of the photo you uploaded is showing zeros instead of actual numbers

Thanks

**Comment by DaVukovic** [comment] 2019-04-17 05:12
@emadmahdi 

Please read: https://kodi.wiki/view/Log_file

And please provide a logfile. Then we could remove the 'ignored rules' label and a dev might look into it. If there's no response for the next 3 days we will close this issue.

Thanks in advance

**Comment by emadmahdi** [comment] 2019-04-17 23:36
I am sorry that I reported this bug ... it is my mistake ... next time i will ignore any bug that i see ...

**Comment by KarellenX** [comment] 2020-12-06 19:15
@enen92 

Is this an easy fix? It is still broken in the latest v19 nightly

![aratio](https://user-images.githubusercontent.com/44626605/101289933-8c2afa80-3853-11eb-904a-8dc8dad50d71.jpg)

**Comment by enen92** [comment] 2020-12-06 19:55
There are no easy fixes in Kodi :) but I'll try to find out the reason

**Comment by KarellenX** [comment] 2020-12-06 20:02
Thanks :)

**Closed** 2020-12-07 08:57 UTC
Labels: Component: Logging, Platform: Android, Platform: Windows, Triage: Confirmed, Triage: Has proposed fix, v18 Leia
