### ISSUE TITLE
Skin Estuary: movie genre fanart backgrounds are missing with foreign languages

### ISSUE THREAD

**Issue by pilian** [xbmc/xbmc#18938] opened 2020-12-15 21:40 UTC
### Describe the bug

I am using Kodi 18.9 on a Raspberry Pi3 with LibreELEC.
I am using the standard skin Estuary.
The language is set to German.
'Use Fanart as background' is enabled
Skin background is set to 'Skin Backgrounds - Metrocity'
Move genre background is set to 'Movie Genre Fanart - Metrocity'

My movie genre items are shown in german language.
The genre backgrounds for the german items are missing.
Only the items with identical names (like Western or Science fiction) display the fanart background.
Therefore most of the fanart background is missing.
It is the same with 'Movie Genre Fanart - Blue Wall' and other image collections.

## Expected Behavior

The movie genre fanart background should refer to the english name of the genre.
Most genre items come from TMDB and are english names.
There is no need to refer the genre fanart background to any foreign translations.

## Actual Behavior

Movie genre fanart backgrounds are missing with foreign languages

## Possible Fix

Refer the movie genre fanart background to the original english pronunciation.

### To Reproduce

This issue was tested with several different movie genre fanart image collections.

### Debuglog

The debuglog can be found here:

### Your Environment
Used Operating system:

 - Operating system version/name: LibreELEC 9.2.6
 - Kodi version: 18.9 Leia
 - Hardware: Raspberry Pi3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment] 2020-12-16 06:04
@pilian 

I understand what the problem is, but I don't understand what fix you are after. It sounds like you want English genres to be scraped regardless of what language your scraper is set to, according to your Possible Fix comment?

Genre's are scraped according to the language you have set in your scraper.

The genre add-ons are English based. Why? Because no member has taken the time to submit the add-on in another language.

There is no bug. But a possible fix is described in this post...
https://forum.kodi.tv/showthread.php?tid=358018&pid=2985124#pid2985124

Hope that helps. I'll close this report as it is not a bug.

**Closed by KarellenX** 2020-12-16 06:04 UTC
Labels: Triage: Needed

**Comment by pilian** [comment] 2020-12-16 07:54
Hi KarellenX,
I am new do Kodi and don't know all the background connections.
I thought the scraper fetch the english movie genre and then Kodi translate it do German for the user display.
I found the translation in the addon:German string.po.
My assumption was, that the genres are still existent in english in the database. Is that right or not?
Then the movie genre fanart background can refer to the english original.
Otherwise we need a language adaption for all fanart image collection. This will cause a great number of fanart addons.

My idea is that it should work like the skinbackground of the main menu items.
These are also translated to german: Pictures to Bilder, Movies to Filme ...
But the fanart skinbackground images still work, without changing the files from 'pictures.jpg' to 'bilder.jpg', 'movies.jpg' to 'filme.jpg' ...

I looked at your link, but I think this is far too complicated for me.
How can I create new language variants of the addon:  'Movie Genre Fanart - Metrocity' ?
I think german, french, spanish, italian will be a good start.
And how can these new addons be inserted in the Kodi repository?

Thank you in advance.

**Comment by pilian** [comment] 2020-12-16 08:01
Another question.

How can I create a new addon:German_mod ?
In this addon I will change the translation of the movie genres to the original english terms.
How do I tell Kodi to use this modified addon?
Will the english 'movie genre fanart image collections' work when I use this modified translation?

**Comment by KarellenX** [comment] 2020-12-16 08:22
>I thought the scraper fetch the english movie genre and then Kodi translate it do German for the user display.

No, that is not how it works.  The language that you set in the scraper is what is scraped from TheMovieDB. Have a look at this entry and you will note the Genre's are in German... https://www.themoviedb.org/movie/39513-paul?language=de-DE
All Kodi does is download the data that is already translated at that site.

>My assumption was, that the genres are still existent in english in the database. Is that right or not?

No. If you scraped German, then you will have German genre's in the database, and because of that the rest of your comments won't work.
>I looked at your link, but I think this is far too complicated for me.
How can I create new language variants of the addon: 'Movie Genre Fanart - Metrocity' ?

Ha, if you think those few instructions in my link were too difficult for you, then you will really struggle to create a new add-on in different languages.
I suggest you get a feel for how Kodi works first. Try following those instructions, then when you get comfortable you can then start looking at creating add-ons.

If you haven't already done so, register at the Kodi forum and ask your questions there. We don't use Github for general support.
