### ISSUE TITLE
switching language issue

### ISSUE THREAD

**Issue by selmen2004** [xbmc/xbmc#25431] opened 2024-07-03 20:40 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:
Switching to some languages ( arabic for exemple ) makes the interface's text  unreadable

## Expected Behavior
Switching language to arabic makes menus in arabic 

## Actual Behavior

text interface becomes squares

## Possible Fix
go to settings -> interface -> skin -> fonts 
choose "arial based"

### To Reproduce

just switch to arabic language after clean install

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

maybe it is better to link languages to some font settings to automatically resolve this

### Your Environment
Used Operating system:

 - [X ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: latest

**Comment by neo1973** [comment] 2024-07-03 21:36
Duplicate of #23201.

**Closed by neo1973** 2024-07-03 21:36 UTC
Labels: Triage: Needed
