### ISSUE TITLE
ActivateWindow() behaves inconsistently wrt. trailing slashes

### ISSUE THREAD

**Issue by dagwieers** [xbmc/xbmc#16516] opened 2019-08-20 03:18 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:
We discovered that when using `ActivateWindow()` using a URL without a trailing slash causes the wrong URL to be taken into account in some cases.

It appears that if the last path fragment is an number (e.g. 2016) it is chopped off the URL, unless it is followed by a trailing slash.

|URL used                         |Ends up in                |
|----------------------------|------------------------|
|plugin://plugin.video.vrt.nu/programs/pano/2016|**/programs/pano/**|
|plugin://plugin.video.vrt.nu/programs/pano/2016/|/programs/pano/2016/|
|plugin://plugin.video.vrt.nu/programs/pano/allseasons|/programs/pano/allseasons|
|plugin://plugin.video.vrt.nu/programs/pano/allseasons/|/programs/pano/allseasons/|

More information when we discovered this: https://github.com/pietje666/plugin.video.vrt.nu/pull/425#discussion_r315485160

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

`ActivateWindow()` should go to the exact URL that is requested.

## Actual Behavior
`ActivateWindow()` chops off numbers at the end of a URL.

### To Reproduce
1. Run `ActivateWindow(Videos,plugin://plugin.video.vrt.nu/programs/pano/2016`
2. Check the path that is requested
3. See it is chopped off

### Debuglog

The debuglog can be found here:
Here is an overview of commands I ran:
```shell
kodi01:~ # kodi-send -a 'ActivateWindow(Videos,plugin://plugin.video.vrt.nu/programs/pano/2016)'
Sending: {'content': 'ActivateWindow(Videos,plugin://plugin.video.vrt.nu/programs/pano/2016)', 'type': 'action'}
kodi01:~ # kodi-send -a 'ActivateWindow(Videos,plugin://plugin.video.vrt.nu/programs/pano/2016/)'
Sending: {'content': 'ActivateWindow(Videos,plugin://plugin.video.vrt.nu/programs/pano/2016/)', 'type': 'action'}
kodi01:~ # kodi-send -a 'ActivateWindow(Videos,plugin://plugin.video.vrt.nu/programs/pano/allseasons)'
Sending: {'content': 'ActivateWindow(Videos,plugin://plugin.video.vrt.nu/programs/pano/allseasons)', 'type': 'action'}
kodi01:~ # kodi-send -a 'ActivateWindow(Videos,plugin://plugin.video.vrt.nu/programs/pano/allseasons/)'
Sending: {'content': 'ActivateWindow(Videos,plugin://plugin.video.vrt.nu/programs/pano/allseasons/)', 'type': 'action'}
```
And this is the resulting log:
```
2019-08-20 05:07:26.444 T:1222632304  NOTICE: [plugin.video.vrt.nu] Access: plugin://plugin.video.vrt.nu/programs/pano/
2019-08-20 05:07:26.458 T:1222632304  NOTICE: [plugin.video.vrt.nu] URL get: https://vrtnu-api.vrt.be/search?i=video&facets[programUrl]=//www.vrt.be/vrtnu/a-z/pano/&si
ze=300
2019-08-20 05:07:30.636 T:1222632304  NOTICE: [plugin.video.vrt.nu] Access: plugin://plugin.video.vrt.nu/programs/pano/2016/
2019-08-20 05:07:30.653 T:1222632304  NOTICE: [plugin.video.vrt.nu] URL get: https://vrtnu-api.vrt.be/search?i=video&facets[seasonTitle]=2016&facets[programUrl]=//www.
vrt.be/vrtnu/a-z/pano/&size=300
2019-08-20 05:07:50.770 T:1222632304  NOTICE: [plugin.video.vrt.nu] Access: plugin://plugin.video.vrt.nu/programs/pano/allseasons
2019-08-20 05:07:50.785 T:1222632304  NOTICE: [plugin.video.vrt.nu] URL get: https://vrtnu-api.vrt.be/search?i=video&facets[programUrl]=//www.vrt.be/vrtnu/a-z/pano/&si
ze=300
2019-08-20 05:07:55.188 T:1222632304  NOTICE: [plugin.video.vrt.nu] Access: plugin://plugin.video.vrt.nu/programs/pano/allseasons/
2019-08-20 05:07:55.202 T:1222632304  NOTICE: [plugin.video.vrt.nu] URL get: https://vrtnu-api.vrt.be/search?i=video&facets[programUrl]=//www.vrt.be/vrtnu/a-z/pano/&si
ze=300
```

### Your Environment
Used Operating system:
 - [x] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC 9.0.2
 - Kodi version: v18.2

**Comment by michaelarnauts** [comment] 2019-09-09 14:29
I can confirm this issue.

I have a plugin with a path like this for example: `plugin://plugin.example.com/program/1485`

When I want to bookmark this, I get the following in the favourites.xml file:
```xml
<favourite name="Example show" thumb="https://example.com/image.png">ActivateWindow(10025,&quot;plugin://plugin.example.com/program/1485&quot;,return)</favourite>
```
This seems fine, but when opening this favourite, the following url is accessed: `plugin://plugin.example.com/program/`

This is incorrect. As @dagwieers explains, this only seems to happen with numeric id's.

**Comment by michaelarnauts** [comment] 2019-09-09 14:38
See https://forum.kodi.tv/showthread.php?tid=342791

**Comment by notspiff** [comment] 2019-09-09 14:41
a directory path ends with a /. end of story. anything ending in a file will get chopped off. it's just a consequence of how urls work. nothing to do with numbers or anything, a url is of the form protocol://<directory>/<file> and that's exactly how the url parser will parse them.

if there is no file part, it shall end in a slash. those add-ons using non-slash-terminated urls for directories are simply broken.

**Comment by michaelarnauts** [comment] 2019-09-09 14:45
Sure, but why does `plugin://plugin.example.com/program/test` works fine, and `plugin://plugin.example.com/program/1485` doesn't? 
And it's perfectly fine to add a bookmark to a file, and they should not end with a slash.

**Comment by notspiff** [comment] 2019-09-09 14:47
for a bookmark, yes, but activatewindow takes a directory parameter, not a random parameter.

**Comment by dagwieers** [comment] 2019-09-09 14:50
@notspiff What makes `/program/test` a directory parameter and `/program/1485` not?
Can directories not include numerical parts?

**Comment by notspiff** [comment] 2019-09-09 14:50
that bit sounds like a bug indeed.

**Comment by dagwieers** [comment] 2019-09-09 15:05
@notspiff The URL scheme does not talk about directories or filenames. There is only a `path`, so I don't think your statement that a directory must end with a trailing slash is correct. It is not true for URLs, and it is not true for Unix either.

https://en.wikipedia.org/wiki/Uniform_Resource_Identifier

**Comment by michaelarnauts** [comment] 2019-09-09 15:07
It's quite common to leave out trailing slashes. I don't see a reason why Kodi can't support both.

```
root@osmc:~# cd /usr/local/bin/
root@osmc:/usr/local/bin# pwd
/usr/local/bin
root@osmc:/usr/local/bin# 

root@osmc:~# cd /usr/local/bin
root@osmc:/usr/local/bin# pwd
/usr/local/bin
root@osmc:/usr/local/bin# 

```

**Comment by notspiff** [comment] 2019-09-09 16:25
i am not talking about unix paths. i am talking about the url parser of kodi. you can argue me to death, i'll even fold, there you go. did the problem get fixed by that?

**Comment by michaelarnauts** [comment] 2019-09-09 16:45
No need to get hostile... I'm just trying to figure out if this was a bug, or really intended behavior. I can look trough the code myself and try to fix it, but then I would need to know for sure how this is intended behavior.

**Comment by notspiff** [comment] 2019-09-09 18:41
It is not intended behavior, as such. But since you cannot stat these urls
to figure out if they are dirs or files like you'd do for local paths, a
convention is necessary. That convention is stick it through the url parser
and use whatever it returns in its folder without filename method.

The number part, at least intuitively, is likely a bug with the support for
numeric window ids as parameter.

man. 9. sep. 2019, 18:46 skrev Michaël Arnauts <notifications@github.com>:

**Comment by da3dsoul** [comment] 2019-09-10 07:18
Thanks for writing this up. I had it on the forums months before, but this clearly got more attention. It's a horribly annoying bug whenever kodi-plugin-routing is involved

**Comment by mediaminister** [comment] 2020-03-16 18:04
I found the problem, when the last part of the path is an integer, it gets removed:
https://github.com/xbmc/xbmc/blob/88eaaa5d8754e5215960fdc5cd5743e63d54e055/xbmc/windows/GUIMediaWindow.cpp#L528-L531

Introduced by https://github.com/xbmc/xbmc/commit/01dbdf956f47e1df3c96261d154848b673fe996a

**Comment by DaveTBlake** [comment] 2020-03-16 19:15
You need to think about the many kinds of path that Kodi processes, that includes using what looks like a URL to encode and pass information about what to show on the music or video nav screen e.g. `musicdb://genres/57/5703/4242/?albumartistsonly=false&artistid=5703&genreid=57` or `musicdb://artists/5703/`. The screen identity is `musicdb://artists/` with numbers (indicating ID filtering) stripped. See https://kodi.wiki/view/Opening_Windows_and_Dialogs

So even if having to add an ending `/` avoid having a trailing number stripped for plugins is frustrating for you, the trailing number stripping is not something you can just remove without risk of breaking other things.

**Comment by dagwieers** [comment] 2020-03-16 19:29
@DaveTBlake It would have been ideal if it was documented why this was added, and what is to be expected. Not sure if there are any unit-tests that may give some insights on how this is expected to behave, but now it looks like the original change may have broken specific use-cases as well. And it is unclear what the desired behaviour looks like, and why. I do not understand that commit or why it is needed in the PR it came with. It is undocumented in the PR and in the code. (And this is not even legacy code, it is a 2017 patch)

Can you explain that commit and why this was added and why it was not needed before?

**Comment by DaveTBlake** [comment] 2020-03-16 19:43
It would be ideal if Kodi was documented, but it isn't (of course feel free to take on that task).  Sometimes you can work things out from PR and code comments, sometimes someone remembers, but often not. Yet before you undo something it is best to assume that those who went before you had good reasons for the things they implemented.

>Can you explain that commit and why this was added and why it was not needed before?

No, but I am used to the string that is passed to ActiveateWindow terminating in '/'. And honestly there are far more productive things that need attention.

**Comment by da3dsoul** [comment] 2020-03-16 20:07
I can understand both sides of the argument, but I also am fully aware that people, especially in side projects, make simple mistakes without realizing the case where it fails. If it was intentional to cause a breaking change, then that needs to be obviously stated, otherwise it can only be assumed a mistake. It's immeasurably more important in a project of this scale. I know that PRs are generally debated significantly if a breaking change is involved here, so I assume that it actually was just overlooked.
I've been personally affected by this, and I'm on the side of fixing the bug.

**Comment by dagwieers** [comment] 2020-03-17 10:36
According to @Razzeee in https://github.com/xbmc/xbmc/commit/01dbdf956f47e1df3c96261d154848b673fe996a#r37868099:

> Wild guess, but I think it's a hack, cause android items on the leanback screen are numberd (ids) and this is a hack to get handle those cases?
>
> Similar to https://github.com/xbmc/xbmc/pull/11901/files#diff-60cebdb0fa4b464e4b757634a37b17c8R46

**Comment by mediaminister** [comment] 2020-05-14 18:40
@DaveTBlake 

> You need to think about the many kinds of path that Kodi processes, that includes using what looks like a URL to encode and pass information about what to show on the music or video nav screen e.g. musicdb://genres/57/5703/4242/?albumartistsonly=false&artistid=5703&genreid=57 or musicdb://artists/5703/. The screen identity is musicdb://artists/ with numbers (indicating ID filtering) stripped. See https://kodi.wiki/view/Opening_Windows_and_Dialogs

This already taken care of in the `GetStartFolder` function of the CGUIWindowMusicNav class
https://github.com/xbmc/xbmc/blob/31d84c748c05f41341bfdecec3d24b4c6044f59d/xbmc/music/windows/GUIWindowMusicNav.cpp#L889-L922

**Closed** 2020-06-18 10:38 UTC
Labels: Triage: Needed
