### ISSUE TITLE
Bluetooth Playback Issue with Directsound

### ISSUE THREAD

**Issue by JuliusBairaktaris** [xbmc/xbmc#25379] opened 2024-06-25 21:12 UTC
### Describe the bug
When playing a media file on Windows 11 using Bluetooth headphones (tested with multiple pairs), the audio plays very fast for the first 2 seconds and then drops entirely when the audio mode is set to DirectSound. However, using WASAPI mode works fine.

## Expected Behavior
Audio plays normaly

### To Reproduce

1. 
2.
3.

### Debuglog

024-06-25 23:02:28.599 T:14480    info <general>: RetroPlayer[RENDER]: Registering renderer factory for DirectX
2024-06-25 23:02:28.676 T:14480    info <general>: load keymapping
2024-06-25 23:02:28.679 T:14480    info <general>: Loading special://xbmc/system/keymaps/appcommand.xml
2024-06-25 23:02:28.688 T:14480    info <general>: Loading special://xbmc/system/keymaps/customcontroller.AppleRemote.xml
2024-06-25 23:02:28.696 T:14480    info <general>: Loading special://xbmc/system/keymaps/customcontroller.Harmony.xml
2024-06-25 23:02:28.705 T:14480    info <general>: Loading special://xbmc/system/keymaps/customcontroller.SiriRemote.xml
2024-06-25 23:02:28.713 T:14480    info <general>: Loading special://xbmc/system/keymaps/gamepad.xml
2024-06-25 23:02:28.721 T:14480    info <general>: Loading special://xbmc/system/keymaps/joystick.xml
2024-06-25 23:02:28.729 T:14480    info <general>: Loading special://xbmc/system/keymaps/keyboard.xml
2024-06-25 23:02:28.738 T:14480    info <general>: Loading special://xbmc/system/keymaps/mouse.xml
2024-06-25 23:02:28.746 T:14480    info <general>: Loading special://xbmc/system/keymaps/remote.xml
2024-06-25 23:02:28.755 T:14480    info <general>: Loading special://xbmc/system/keymaps/touchscreen.xml
2024-06-25 23:02:28.763 T:14480    info <general>: GUI format 2880x1800, Display Lenovo HDR Monitor #1: 2880x1800 @ 60.00Hz
2024-06-25 23:02:28.785 T:15296    info <general>: Found 2 Lists of Devices
2024-06-25 23:02:28.785 T:15296    info <general>: Enumerated DIRECTSOUND devices:
2024-06-25 23:02:28.785 T:15296    info <general>:     Device 1
2024-06-25 23:02:28.785 T:15296    info <general>:         m_deviceName      : {7F0DF5BF-AFE4-4F6C-8D52-F0FA151DD29E}
2024-06-25 23:02:28.785 T:15296    info <general>:         m_displayName     : Speakers - Speakers (Realtek(R) Audio)
2024-06-25 23:02:28.785 T:15296    info <general>:         m_displayNameExtra: DIRECTSOUND: Speakers (Realtek(R) Audio)
2024-06-25 23:02:28.785 T:15296    info <general>:         m_deviceType      : AE_DEVTYPE_PCM
2024-06-25 23:02:28.785 T:15296    info <general>:         m_channels        : FL, FR
2024-06-25 23:02:28.785 T:15296    info <general>:         m_sampleRates     : 48000
2024-06-25 23:02:28.785 T:15296    info <general>:         m_dataFormats     : AE_FMT_FLOAT
2024-06-25 23:02:28.785 T:15296    info <general>:         m_streamTypes     : No passthrough capabilities
2024-06-25 23:02:28.785 T:15296    info <general>:     Device 2
2024-06-25 23:02:28.785 T:15296    info <general>:         m_deviceName      : {CB7E67E6-4669-4D22-8D74-A32514A420D6}
2024-06-25 23:02:28.785 T:15296    info <general>:         m_displayName     : Headphones - Headphones (Jabra Elite 8 Active)
2024-06-25 23:02:28.785 T:15296    info <general>:         m_displayNameExtra: DIRECTSOUND: Headphones (Jabra Elite 8 Active)
2024-06-25 23:02:28.785 T:15296    info <general>:         m_deviceType      : AE_DEVTYPE_PCM
2024-06-25 23:02:28.785 T:15296    info <general>:         m_channels        : FL, FR
2024-06-25 23:02:28.785 T:15296    info <general>:         m_sampleRates     : 48000
2024-06-25 23:02:28.785 T:15296    info <general>:         m_dataFormats     : AE_FMT_FLOAT
2024-06-25 23:02:28.785 T:15296    info <general>:         m_streamTypes     : No passthrough capabilities
2024-06-25 23:02:28.785 T:15296    info <general>:     Device 3
2024-06-25 23:02:28.785 T:15296    info <general>:         m_deviceName      : default
2024-06-25 23:02:28.785 T:15296    info <general>:         m_displayName     : default
2024-06-25 23:02:28.785 T:15296    info <general>:         m_displayNameExtra: 
2024-06-25 23:02:28.785 T:15296    info <general>:         m_deviceType      : AE_DEVTYPE_PCM
2024-06-25 23:02:28.785 T:15296    info <general>:         m_channels        : FL, FR
2024-06-25 23:02:28.785 T:15296    info <general>:         m_sampleRates     : 48000
2024-06-25 23:02:28.785 T:15296    info <general>:         m_dataFormats     : AE_FMT_FLOAT
2024-06-25 23:02:28.785 T:15296    info <general>:         m_streamTypes     : No passthrough capabilities
2024-06-25 23:02:28.785 T:15296    info <general>: Enumerated WASAPI devices:
2024-06-25 23:02:28.785 T:15296    info <general>:     Device 1
2024-06-25 23:02:28.785 T:15296    info <general>:         m_deviceName      : {7F0DF5BF-AFE4-4F6C-8D52-F0FA151DD29E}
2024-06-25 23:02:28.785 T:15296    info <general>:         m_displayName     : Speakers - Speakers (Realtek(R) Audio)
2024-06-25 23:02:28.785 T:15296    info <general>:         m_displayNameExtra: WASAPI: Speakers (Realtek(R) Audio)
2024-06-25 23:02:28.785 T:15296    info <general>:         m_deviceType      : AE_DEVTYPE_PCM
2024-06-25 23:02:28.785 T:15296    info <general>:         m_channels        : FL, FR
2024-06-25 23:02:28.785 T:15296    info <general>:         m_sampleRates     : 192000,176400,96000,88200,48000,44100,32000,22050,11025
2024-06-25 23:02:28.785 T:15296    info <general>:         m_dataFormats     : AE_FMT_S24NE3,AE_FMT_S24LE3,AE_FMT_S24BE3,AE_FMT_S24NE4MSB,AE_FMT_S16NE,AE_FMT_S16LE,AE_FMT_S16BE,AE_FMT_U8
2024-06-25 23:02:28.785 T:15296    info <general>:         m_streamTypes     : No passthrough capabilities
2024-06-25 23:02:28.785 T:15296    info <general>:     Device 2
2024-06-25 23:02:28.785 T:15296    info <general>:         m_deviceName      : {CB7E67E6-4669-4D22-8D74-A32514A420D6}
2024-06-25 23:02:28.785 T:15296    info <general>:         m_displayName     : Headphones - Headphones (Jabra Elite 8 Active)
2024-06-25 23:02:28.785 T:15296    info <general>:         m_displayNameExtra: WASAPI: Headphones (Jabra Elite 8 Active)
2024-06-25 23:02:28.785 T:15296    info <general>:         m_deviceType      : AE_DEVTYPE_PCM
2024-06-25 23:02:28.785 T:15296    info <general>:         m_channels        : FL, FR
2024-06-25 23:02:28.785 T:15296    info <general>:         m_sampleRates     : 48000
2024-06-25 23:02:28.785 T:15296    info <general>:         m_dataFormats     : AE_FMT_S16NE,AE_FMT_S16LE,AE_FMT_S16BE
2024-06-25 23:02:28.785 T:15296    info <general>:         m_streamTypes     : No passthrough capabilities
2024-06-25 23:02:28.785 T:15296    info <general>:     Device 3
2024-06-25 23:02:28.785 T:15296    info <general>:         m_deviceName      : default
2024-06-25 23:02:28.785 T:15296    info <general>:         m_displayName     : default
2024-06-25 23:02:28.785 T:15296    info <general>:         m_displayNameExtra: 
2024-06-25 23:02:28.785 T:15296    info <general>:         m_deviceType      : AE_DEVTYPE_PCM
2024-06-25 23:02:28.785 T:15296    info <general>:         m_channels        : FL, FR
2024-06-25 23:02:28.785 T:15296    info <general>:         m_sampleRates     : 48000
2024-06-25 23:02:28.785 T:15296    info <general>:         m_dataFormats     : AE_FMT_S16NE,AE_FMT_S16LE,AE_FMT_S16BE
2024-06-25 23:02:28.785 T:15296    info <general>:         m_streamTypes     : No passthrough capabilities
2024-06-25 23:02:28.786 T:15300    info <general>: CActiveAESink::OpenSink - initialize sink
2024-06-25 23:02:28.809 T:15296 warning <general>: CActiveAE::ActiveAE::CActiveAE::StateMachine - signal: 0 from port: OutputControlPort not handled for state: 7
2024-06-25 23:02:28.809 T:14480    info <general>: Skipped 1 duplicate messages..
2024-06-25 23:02:28.809 T:14480    info <general>: CLangInfo: loading resource.language.en_gb language information...
2024-06-25 23:02:28.831 T:14480    info <general>: global locale set to en-us
2024-06-25 23:02:28.832 T:14480    info <general>: CLangInfo: loading resource.language.en_gb language strings...
2024-06-25 23:02:29.042 T:14424    info <general>: Running database version Addons33
2024-06-25 23:02:29.044 T:14424    info <general>: Running database version ViewModes6
2024-06-25 23:02:29.046 T:14424    info <general>: Running database version Textures13
2024-06-25 23:02:29.049 T:14424    info <general>: Running database version MyMusic83
2024-06-25 23:02:29.053 T:14424    info <general>: Running database version MyVideos131
2024-06-25 23:02:29.056 T:14424    info <general>: Running database version TV44
2024-06-25 23:02:29.057 T:14424    info <general>: Running database version Epg16
2024-06-25 23:02:29.106 T:14480    info <general>: Unloaded skin
2024-06-25 23:02:29.117 T:14480    info <general>:   load skin from: C:\Users\juliu\AppData\Roaming\Kodi\addons\skin.arctic.fuse\ (version: 0.7.25~omega)
2024-06-25 23:02:29.117 T:14480    info <general>:   load fonts for skin...
2024-06-25 23:02:29.132 T:14480    info <general>: Loading skin includes from C:\Users\juliu\AppData\Roaming\Kodi\addons\skin.arctic.fuse\1080i\Includes.xml
2024-06-25 23:02:29.336 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294935808, O:5288.
2024-06-25 23:02:29.337 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294935864, O:1872.
2024-06-25 23:02:29.337 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294935896, O:1872.
2024-06-25 23:02:29.337 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294935928, O:1872.
2024-06-25 23:02:29.337 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294935960, O:1872.
2024-06-25 23:02:29.337 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294935984, O:1872.
2024-06-25 23:02:29.337 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294936008, O:1872.
2024-06-25 23:02:29.337 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294936040, O:1872.
2024-06-25 23:02:29.337 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294936064, O:1872.
2024-06-25 23:02:29.337 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294936096, O:1872.
2024-06-25 23:02:29.337 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294936128, O:1872.
2024-06-25 23:02:29.337 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294936152, O:1872.
2024-06-25 23:02:29.337 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294936184, O:1872.
2024-06-25 23:02:29.338 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294936232, O:1872.
2024-06-25 23:02:29.338 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294936256, O:1872.
2024-06-25 23:02:29.338 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294936288, O:1872.
2024-06-25 23:02:29.338 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294936320, O:1872.
2024-06-25 23:02:29.338 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294936344, O:1872.
2024-06-25 23:02:29.338 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294936376, O:1872.
2024-06-25 23:02:29.338 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294936408, O:1872.
2024-06-25 23:02:29.338 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294936432, O:1872.
2024-06-25 23:02:29.338 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294936464, O:1872.
2024-06-25 23:02:29.338 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294936496, O:1872.
2024-06-25 23:02:29.338 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294936512, O:1872.
2024-06-25 23:02:29.338 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294936544, O:1872.
2024-06-25 23:02:29.339 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294936576, O:1872.
2024-06-25 23:02:29.339 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294936600, O:1872.
2024-06-25 23:02:29.339 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294936632, O:1872.
2024-06-25 23:02:29.339 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294936664, O:1872.
2024-06-25 23:02:29.339 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294936688, O:1872.
2024-06-25 23:02:29.339 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294936720, O:1872.
2024-06-25 23:02:29.339 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294936752, O:1872.
2024-06-25 23:02:29.339 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294936776, O:1872.
2024-06-25 23:02:29.339 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294936800, O:1872.
2024-06-25 23:02:29.339 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294936832, O:1872.
2024-06-25 23:02:29.339 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294936864, O:1872.
2024-06-25 23:02:29.339 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294936888, O:1872.
2024-06-25 23:02:29.340 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294936920, O:1872.
2024-06-25 23:02:29.340 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294936952, O:1872.
2024-06-25 23:02:29.340 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294936976, O:1872.
2024-06-25 23:02:29.340 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294937008, O:1872.
2024-06-25 23:02:29.340 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294937032, O:1872.
2024-06-25 23:02:29.340 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294937056, O:1872.
2024-06-25 23:02:29.340 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294937088, O:1872.
2024-06-25 23:02:29.340 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294937120, O:1872.
2024-06-25 23:02:29.340 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294937144, O:1872.
2024-06-25 23:02:29.340 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294937176, O:1872.
2024-06-25 23:02:29.340 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294937208, O:1872.
2024-06-25 23:02:29.340 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294937232, O:1872.
2024-06-25 23:02:29.341 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294937264, O:1872.
2024-06-25 23:02:29.341 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294937296, O:1872.
2024-06-25 23:02:29.341 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294937320, O:1872.
2024-06-25 23:02:29.341 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294937344, O:1872.
2024-06-25 23:02:29.341 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294937376, O:1872.
2024-06-25 23:02:29.341 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294937408, O:1872.
2024-06-25 23:02:29.341 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294937432, O:1872.
2024-06-25 23:02:29.341 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294937464, O:1872.
2024-06-25 23:02:29.341 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294937496, O:1872.
2024-06-25 23:02:29.341 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294937520, O:1872.
2024-06-25 23:02:29.341 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294937544, O:1872.
2024-06-25 23:02:29.341 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294937576, O:1872.
2024-06-25 23:02:29.341 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294937600, O:1872.
2024-06-25 23:02:29.342 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294937632, O:1872.
2024-06-25 23:02:29.342 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294937664, O:1872.
2024-06-25 23:02:29.342 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294937688, O:1872.
2024-06-25 23:02:29.342 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294937720, O:1872.
2024-06-25 23:02:29.342 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294937752, O:1872.
2024-06-25 23:02:29.342 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294937776, O:1872.
2024-06-25 23:02:29.342 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294937808, O:1872.
2024-06-25 23:02:29.342 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294937840, O:1872.
2024-06-25 23:02:29.342 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294937864, O:1872.
2024-06-25 23:02:29.342 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294937888, O:1872.
2024-06-25 23:02:29.342 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294937920, O:1872.
2024-06-25 23:02:29.343 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294937984, O:1872.
2024-06-25 23:02:29.343 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294938048, O:1872.
2024-06-25 23:02:29.343 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294938088, O:1872.
2024-06-25 23:02:29.343 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294938136, O:1872.
2024-06-25 23:02:29.343 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294938176, O:1872.
2024-06-25 23:02:29.343 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294938216, O:1872.
2024-06-25 23:02:29.343 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294938256, O:1872.
2024-06-25 23:02:29.343 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294938304, O:1872.
2024-06-25 23:02:29.344 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294938344, O:1872.
2024-06-25 23:02:29.344 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294938392, O:1872.
2024-06-25 23:02:29.344 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294938432, O:1872.
2024-06-25 23:02:29.344 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294938464, O:1872.
2024-06-25 23:02:29.344 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294938496, O:1872.
2024-06-25 23:02:29.344 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294938520, O:1872.
2024-06-25 23:02:29.344 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294938552, O:1872.
2024-06-25 23:02:29.344 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294938584, O:1872.
2024-06-25 23:02:29.344 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294938608, O:1872.
2024-06-25 23:02:29.344 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294938640, O:1872.
2024-06-25 23:02:29.344 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294938672, O:1872.
2024-06-25 23:02:29.345 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294938696, O:1872.
2024-06-25 23:02:29.345 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294938720, O:1872.
2024-06-25 23:02:29.345 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294938752, O:1872.
2024-06-25 23:02:29.345 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294938776, O:1872.
2024-06-25 23:02:29.345 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294938808, O:1872.
2024-06-25 23:02:29.345 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294938840, O:1872.
2024-06-25 23:02:29.345 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294938864, O:1872.
2024-06-25 23:02:29.345 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294938896, O:1872.
2024-06-25 23:02:29.345 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294938928, O:1872.
2024-06-25 23:02:29.345 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294938952, O:1872.
2024-06-25 23:02:29.345 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294938976, O:1872.
2024-06-25 23:02:29.345 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294939008, O:1872.
2024-06-25 23:02:29.346 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294939040, O:1872.
2024-06-25 23:02:29.346 T:15300 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7160, P:4294939064, O:1872.

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 11 22361.3737
 - Kodi version: 21.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by thexai** [comment] 2024-06-26 14:51
Duplicate of https://github.com/xbmc/xbmc/issues/20567

The fix is already merged in master branch, you can use a build from here:
https://mirrors.kodi.tv/nightlies/windows/win64/master/

Or this build of Omega/v21:
https://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20240626-46dc0e31-fix-DirectSound-Omega-x64.exe

**Comment by JuliusBairaktaris** [comment] 2024-06-26 19:48
Can confirm that it works. Thanks and please excuse the duplicate

**Comment by JuliusBairaktaris** [comment] 2024-06-27 19:09
Hey, I also noticed that all UI sounds regardless if using Estuary or Artic Fuse are doubled. 

Thanks in advance for your help.

**Comment by thexai** [comment] 2024-06-28 15:26
Then you should provide full debug log: paste text in https://paste.kodi.tv/ and copy link here.

**Comment by thexai** [comment] 2024-07-12 17:52
No response

**Comment by thexai** [comment] 2024-07-20 15:58
Can you test this new build?

https://forum.kodi.tv/showthread.php?tid=376406&pid=3204473#pid3204473

**Comment by JuliusBairaktaris** [comment] 2024-07-20 20:24
Excuse the long response. This build fixed my BT audio issues. Thank you very much!

**Comment by thexai** [comment] 2024-07-21 06:45
Thank you for testing!

I'm preparing a new PR. Logs are not necessary for now as it works :)

**Closed** 2024-07-21 10:24 UTC
Labels: Platform: Windows, Ignored rules, Triage: Has proposed fix, v21 Omega
