### ISSUE TITLE
Problems with sources not being accessible via LAN

### ISSUE THREAD

**Issue by Mister-XY** [xbmc/xbmc#24289] opened 2023-12-21 08:22 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:
Hello, Kodi from version 21 has the problem that it takes a very long time to start (we're talking about 7-10 minutes).
However, the problem only occurs as soon as Kodi can no longer find or access the sources.
I enter the films as normal via Kodi, scrape the films via The MovieDatabase and then restart Kodi, then the start only takes a few seconds. If my NAS is no longer accessible (because I switched it off) then it takes 7-10 minutes to start. But if I start the NAS during this time, the time will be reduced because KODI will find the source immediately.
The whole thing only happens with OMEGA. There were no problems under Nexus.
I have the problem via Coreelec and with Kodi, which is installed on a Fire TV.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### Debuglog
[Kodidebugcoreelec.log](https://github.com/xbmc/xbmc/files/13738194/Kodidebugcoreelec.log)
[Kodidebugcoreelec2.log](https://github.com/xbmc/xbmc/files/13738199/Kodidebugcoreelec2.log)

### Your Environment
Used Operating system:

 - [x ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 21 beta 2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment] 2023-12-21 08:32
Duplicate of https://github.com/xbmc/xbmc/issues/23958

**Closed by fuzzard** 2023-12-21 08:32 UTC
Labels: Triage: Needed

**Comment by Mister-XY** [comment] 2023-12-21 08:44
Why do you closed this, the problem is since 2 month open and did not found a solution.
